- README.md
- [] Reviewed by Snyk internal team
Improve the README for clarity and correctness -- and OCD nits ;)
README.md
reading?
Great project; improving the docs as a "thank you" gesture. Slainte! :)
n/a
n/a
n/a
> fix: minor README.md improvements

- docker/Dockerfile.python-2
- docker/Dockerfile.python-3
- docker/docker-python-entrypoint.sh
Grabbing @julienduchesne 's addition to support python-based docker images of the CLI. Will go through our internal release process, stay tuned.
> Add python3 docker

- .travis.yml
- scripts/travis_after_success.sh
Remove automated github assets publishing for now, we need to figure out a better way of doing this.
> chore: remove github assets publishing, not functional yet

- .releaserc
- .travis.yml
Automating the build and publishing of standalone binary assets on every CLI release.
As discussed on https://github.com/semantic-release/semantic-release/issues/897
> chore: automate pkg assets publishing

- lib/snyk-test/npm/index.js
- package-lock.json
- package.json
- test/acceptance/cli.acceptance.test.js
Fixing situation when cyclic dependency is found in a `package-lock.json`.
At https://github.com/snyk/nodejs-lockfile-parser/pull/17
Runnning test command against a `package-lock.json` with cyclic dependencies (e.g. https://github.com/MarkGriffiths/trucolor/).
> fix: bump lockfile-parser to fix cyclic dependecies

- .releaserc
- .travis.yml
Adding `pkg` and automated binary assets building to the release process. Aiming to have binary assets uploaded by `semantic-release`!
> chore: add pkg to semantic-release process

- cli/commands/test.js
Catching up with code review, a nicer way to repeat spaces for padding.
> fix: nicer way to pad

- cli/commands/test.js
When an actual `Error` is thrown during a `snyk test` we don't log it's actual stack trace, but rather the stack leading to https://github.com/snyk/snyk/blob/632a425af87d6c3c7c7433d554a89c6a7a68096c/cli/commands/test.js#L146 which is not so useful.
This PR prints the stacks of all (in case multiple projects were tested) the failed projects for which we have an `Error` object.
so now we'll have:
```
snyk Failed to test 1 projects, errors: +0ms
snyk error: TypeError: Cannot set property 'koko' of undefined
at assembleLocalPayload (/Users/michael/projects/snyk/snyk-cli/lib/snyk-test/run-test.js:116:18)
at assemblePayload (/Users/michael/projects/snyk/snyk-cli/lib/snyk-test/run-test.js:111:18)
at /Users/michael/projects/snyk/snyk-cli/lib/snyk-test/run-test.js:26:12
at <anonymous>
at …
```
> fix: debug-print original stack of Error()s thrown during `test`

- docker/docker-entrypoint.sh
Will add more debugging info to our docker flows.
> feat: add debugging info on docker entrypoint

- docker/docker-entrypoint.sh
Add more tracing info on docker entrypoint
> feat: add more tracing info on docker entrypoint

- package.json
Bump the snyk mvn plugin to latest version for an error type fix
> feat: Bump snyk mvn plugin to latest

- .travis.yml
- package.json
- Upgrade `snyk-docker-plugin` to v1.11.0
- See: https://github.com/snyk/snyk-docker-plugin/pull/38
> feat: upgrade snyk-docker-plugin

- package-lock.json
- package.json
- snyk-gradle-plugin version bump to fix vuln annotation issue
- snyk-gradle-plugin version bump to fix (n) markers
> fix: bump gradle plugin to fix dep tree annotations

- package.json
Use latest resolve-deps for smaller dep trees without peer deps
> feat: Bump resolve-deps to latest

- package.json
- src/cli/commands/test.js
- src/lib/monitor.js
- src/lib/snyk-test/run-test.js
- test/acceptance/cli.acceptance.test.js
- enables docker base image remediation advice
- `snyk test --docker my-image:latest --file=Dockerfile`
> feat: docker base image remediation advice

- src/cli/index.ts
update message for "path with file name" error
https://github.com/snyk/snyk/pull/232
> fix: update message for path with file name error

- package.json
nodejs-lockfile-parser PR: https://github.com/snyk/nodejs-lockfile-parser/pull/23
> fix: bump nodejs-lockfile-parser to allow 0 deps

- src/cli/commands/protect/wizard.js
Quick fix for one misplaced delete (deletes answers containing `.`, since it fails in docker related flows).
> fix: not delete from this

- test/acceptance/cli.acceptance.test.js
- test/prompts.test.js
- test/severity-threshold.test.js
- test/wizard-prepare.test.js
Upgrade sinon
Resolve the deprecated warnings.
> chore: upgrade sinon

- src/cli/commands/test.js
Displays suggestion for using `--file` option when using `test` command with `docker`.
https://snyksec.atlassian.net/browse/SC-6516
> feat: display suggestion for using dockerfile

- package.json
see https://github.com/snyk/snyk-docker-plugin/pull/43
for more info
> fix: remove docker image from scan

- package.json
Bump lockfile parser version for perf update when parsing yarn.lock or package-lock.json
No functional changes only speedier performance
> feat: Bump lockfile parser version for perf update

- package.json
- Updates the `snyk-docker-plugin` to handle hosts with ports: https://github.com/snyk/snyk-docker-plugin/pull/45
> fix: update snyk-docker-plugin to handle hosts with ports

- package.json
- bumps snyk-gradle-plugin to fix a parsing bug: https://github.com/snyk/snyk-gradle-plugin/pull/21
> fix: bump snyk-gradle-plugin to fix version parsing edge-case

- package.json
Updates lockfile parser dependency, which fixes a bug with `file` specification of package version.
https://github.com/snyk/nodejs-lockfile-parser/pull/26
> chore: bump lockfile parser

- .travis.yml
Currently, we are running the Release stage also pull requests, and exit early.
This PR should remove the Release stage for PRs.
> chore: show travis release stage only for master

- package.json
Bump minimum required nodejs lockfile parser version to latest
> feat: Bump required lockfile parser version

- package.json
Bump docker plugin version to latest
> feat: bump docker plugin

- package.json
> feat: bump docker plugin version

- .releaserc
introduced in previous PR: https://github.com/snyk/snyk/pull/293
> fix: missing comma in .releaserc

- package.json
Bump version of snyk-go-plugin.
https://github.com/snyk/snyk-go-plugin/pull/33
> chore: bump snyk-go-plugin

- test/acceptance/cli.acceptance.test.ts
- test/package-no-name.test.ts
Small ES6 adjustments in cli.acceptance and package-no-name tests
> refactor: leftovers for es6 adjustments

- src/lib/snyk-test/npm/index.js
This PR corrects the keys used for analytics so they conform to conventions.
> fix: corrected analytics keys to match conventions.

- src/cli/commands/test.js
- test/acceptance/cli.acceptance.test.ts
Display docker binaries issues in a dedicated section.
> feat: dedicated display docker binaries issues

- package.json
Updates the keywords list for the npm package
> fix: update keywords for npm package

- README.md
- SECURITY.md
- help/help.txt
Corrects grammar and typos
Supercedes #285, #286
> fix: typos and grammar cleanup

- package.json
the new version should handle whitespaces better in targetFile paths, and add single quotation marks (instead of double) only if needed.
> fix: bumping snyk-gradle-plugin

- package.json
Bump docker plugin to `1.18.1`
> fix: bump docker plugin

- package.json
Bumps `snyk-php-plugin` to address an issue with manifest file path handling. Resolves https://github.com/snyk/snyk/issues/256
See https://github.com/snyk/snyk-php-plugin/pull/28
> fix: bump php plugin to better support file paths

- README.md
The build section is no longer exist anymore, hence removing it.
fixes https://github.com/snyk/snyk/issues/316
> chore: remove build from TOC

- package.json
fixed version: https://github.com/snyk/nodejs-lockfile-parser/releases/tag/v1.10.2
> fix: bump nodejs-lockfile-parser to update vulnerable deps

- package.json
Bump lockfile parser version to latest to give us ability to start using detection of yarn workspaces
> feat: Bump lockfile parser version to detect yarn workspaces

- package.json
This version contains:
SCM integration dockerfile analysis
adoptopenjdk openjdk binary analysis support
global docker options support
> feat: docker options passthrough and adoptopenjdk support

- .gitignore
- help/file.txt
- package.json
- src/cli/commands/protect/wizard.js
- src/lib/detect.ts
- src/lib/plugins/index.js
- src/lib/snyk-test/index.js
- test/acceptance/cli.acceptance.test.ts
- test/acceptance/workspaces/paket-app/paket.dependencies
- test/acceptance/workspaces/paket-obj-app/obj/project.assets.json
- test/acceptance/workspaces/paket-obj-app/paket.dependencies
> feat: add paket support

- src/lib/protect/apply-patch.js
Improve `patch-fail` error analytics by serialising error properly.
> fix: improve patch-fail error analytics

- package.json
bump docker plugin to `1.22.0` - handle SHA256 as tag name
PR: https://github.com/snyk/snyk-docker-plugin/pull/71
> feat: bump docker plugin to  - handle SHA256 as tag name

- src/lib/protect/apply-patch.js
Minor cosmetic change to the way patch errors are logged.
> fix: concise patch error metadata

- src/cli/commands/auth.js
Updates auth text display, removes `github auth page` which is no longer accurate.
before:
after:
> feat: update auth text to snyk auth

- package.json
bumping snyk gradle plugin to 2.1.4
> feat: bumping snyk gradle plugin to 2.1.4

- README.md
- docker/Dockerfile.docker
```bash
cd snyk/docker
docker build -f Dockerfile.docker -t snyk/snyk-cli:docker .
docker run -it --rm -e SNYK_TOKEN=$SNYK_TOKEN -v $PWD:/project -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk-cli:docker test --docker snyk/snyk-cli:docker --file=/project/Dockerfile.docker
```
> feat: Add snyk/snyk-cli:docker image for Docker images testing

- src/cli/commands/test.ts
- src/lib/snyk-test/legacy.ts
- src/lib/snyk-test/run-test.ts
- test/acceptance/cli.acceptance.test.ts
- test/acceptance/fixtures/docker/find-result-remediation.json
- test/acceptance/fixtures/docker/plugin-multiple-deps.ts
supports the flag `--exclude-base-image-vulns` in json output option as well by moving the filtering to earlier in the response processing. 
see here https://github.com/snyk/snyk/pull/352
> feat: exclude base image vulns in json option

- package.json
Bump snyk plugin version to resolve a bug that changes project names by adding targetFile to them.
`monitor`
`monitor --project-name=banana`
> feat: send target file for kotlin but not groovy projects

- package.json
> feat: bump Gradle plugin version (improved Windows support)

- package.json
…y expansion)
https://snyksec.atlassian.net/browse/BST-505
> feat: bump Gradle plugin (all configs merged)

- package.json
Updates resolve-deps to support Yarn aliasing: https://yarnpkg.com/lang/en/docs/cli/add/#toc-yarn-add-alias
https://github.com/snyk/snyk/issues/330
> feat: handle Yarn aliases (renamed dependencies)

- package.json
* fixes a race condition causing breakages in Gradle parallel builds support
* fixes Gradle support in prebuilt Snyk CLI binaries
https://snyksec.atlassian.net/browse/BST-530
snyk/snyk#409
> fix: Gradle: parallel builds and standalone CLI support

- package.json
Do not rush the `snyk-nuget-plugin` upgrade just yet, allow for more testing.
> fix: downgrade nuget plugin

- .travis.yml
- appveyor.yml
- package.json
- test/wizard-prepare.test.js
- test/wizard-prepublish.test.js
> chore: run tests on Windows

- src/lib/snyk-test/run-test.ts
> fix: show analyzing label for multi projects

- src/lib/detect.ts
- test/acceptance/cli.acceptance.test.ts
> fix: update the link to "language support" documentation page

- package.json
Bump `snyk-python-plugin` to 1.9.2
add fix to handle paths to local dir in requirements.txt
https://github.com/snyk/snyk-python-plugin/pull/52
> fix: bump python-plugin (1.9.2); handle local dir in requirements.txt

- package.json
Bump nodejs-lockfile-parser to latest version that can extract `engines` property form package.json
> feat: Parse node engines from package.json

- package.json
Bumps Gradle plug in to pick up https://github.com/snyk/snyk-gradle-plugin/pull/59
https://snyksec.atlassian.net/browse/BST-528
> fix: enable a workaround for Gradle Android configuration resolution problem

- package.json
bump nuget plugin version to fix a bug for project with no deps
> feat: bump nuget plugin

- package.json
- src/lib/plugins/types.ts
Upgrade to a typescript-ified go-plugin. 
The new go plugin now outsources parsing to the https://github.com/snyk/snyk-go-parser.
https://github.com/snyk/snyk-go-plugin/pull/41
https://github.com/snyk/snyk-go-plugin/pull/40
https://github.com/snyk/snyk-go-plugin/pull/39
https://github.com/snyk/snyk-go-plugin/pull/37
https://github.com/snyk/snyk-go-plugin/pull/35
> feat: upgrade go-plugin with more logs and error handling

- src/lib/module-info/index.js
- src/lib/snyk-test/run-test.ts
adding some `debug` logs to debug reported performance issues of local inspection taking few
minutes.
> feat: new debug logs around plugin's inspect

- package.json
Bump PHP plugin version to pull in the simple fix for tree size explosion for projects with interdependent packages. (the fix trims the tree if there are too many repeated dependencies).
https://snyk.zendesk.com/agent/tickets/278
> fix: handle PHP projects with interdependent packages

- package.json
Release latest version of the plugin that has improved tests for java 8 & 9
> feat: Release gradle plugin with improved tests per Java versions

- src/cli/commands/monitor.ts
- src/cli/commands/test.ts
- src/lib/snyk-test/run-test.ts
- src/lib/types.ts
- test/acceptance/cli.acceptance.test.ts
Displays a suggestion to try `--all-sub-projects` flag.
https://snyksec.atlassian.net/browse/BST-540
> feat: suggests --all-sub-projects flag for multi-project gradle builds

- .snyk
> feat: Update snyk ignores

- package.json
Pulls is https://github.com/snyk/snyk-gradle-plugin/pull/65
> feat: if a non-existing Gradle config is specified, suggest existing ones

- package.json
Solves the Go performance issue (simplified package graph scan algorithm in the Go plugin).
https://snyksec.atlassian.net/browse/BST-593
> fix: improve the performance of Go scans

- src/lib/detect.ts
> Fix typo in debug message.

- README.md
Fix a link that is now broken after a site migration
https://github.com/snyk/snyk/issues/508
> chore: Update broken snyk link

- package.json
Improves dependency scanning speed for Go projects consisting of many interdependent packages.
> fix: optimize scanning of large Go projects

- package.json
More logging to debug "no line with JSONDEPS" (sen https://github.com/snyk/snyk-gradle-plugin/pull/69)
> chore: more logging for Gradle errors

- package.json
Release SBT `coursier` support, users that are using `coursier` in their project will have their dependencies analysed using this with a fall back to the old plugin.
> feat: release coursier suport fot for sbt

- src/cli/commands/auth.ts
- src/cli/commands/auth/index.ts
- src/cli/commands/auth/is-authed.ts
- src/cli/commands/ignore.js
- src/cli/commands/index.js
- src/cli/commands/protect/wizard.js
- src/cli/commands/scenario.js
- src/cli/commands/test.ts
- src/lib/analytics.js
- src/lib/errors/authentication-failed-error.ts
- src/lib/errors/custom-error.ts
- src/lib/errors/legacy-errors.js
- src/lib/errors/misconfigured-auth-in-ci-error.ts
- src/lib/errors/token-expired-error.ts
- src/lib/hotload.js
- src/lib/is-ci.ts
- src/lib/monitor.ts
- src/lib/snyk-test/run-test.ts
- src/lib/spinner.js
- test/acceptance/docker-promotion.test.js
- test/cli.test.js
> refactor: Convert auth.js to => .ts

- README.md
Reduce words, better structure.
Update the wording in docs to be more precise around badges advantages
> chore: Reduce words around badges advantages

- package.json
Propagation of https://github.com/snyk/snyk-python-plugin/pull/59
> fix: bump python plugin to fix bug with urls in req.txt

- src/lib/config.ts
- src/lib/snyk-test/run-test.ts
> chore: convert config to ts

- package.json
Update snyk-go-plugin to the version that supports first level of
dependencies for go modules.
> feat: preparation for go modules support

- help/help.txt
Help update only, "fix" to trigger a release.
> fix: added a link to the Gradle documentation

- package.json
Revering offending changes introduced by the gradle plugin since 2.11.2
> feat: revert gradle plugin to undo breaking change

- package.json
- src/cli/args.ts
- src/lib/request/request.ts
- src/lib/request/types.ts
> fix: typescriptify request.js

- src/lib/monitor.ts
Small (5% gzipped) payload size optimization. Why not.
> fix: drop empty dependencies (payload size optimization)

- package.json
- src/lib/plugins/types.ts
Update snyk-php-plugin version
See https://github.com/snyk/snyk-php-plugin/pull/30
[BST-677](https://snyksec.atlassian.net/browse/BST-677)
> feat: update snyk-php-plugin version

- package.json
- src/cli/args.ts
- src/lib/plugins/types.ts
- test/acceptance/cli.acceptance.test.ts
enable logging from sbt-plugin by running `snyk` with `-d` option.
> fix: add logging to sbt-plugin

- package.json
upgrade sbt-plugin. See: https://github.com/snyk/snyk-sbt-plugin/pull/37
> fix: sbt-plugin stdin hanging

- package.json
- Release the latest version of the `sbt` plugin with optional timeout handling + typescript
> feat: Release typescripted sbt with timeout handling

- .releaserc
Adding `alpine` platform to the list of standalone binaries we release via github assets, following customer demand.
> fix: add alpine platform to standalone binary release assets

- docker/Dockerfile.docker
chore: reduces the size of the resulting Docker image
`./docker/Dockerfile.docker`
```
docker image pull snyk/snyk:docker && docker image ls | grep snyk/snyk:docker
cd ./docker/ && docker image build -t snyk-docker:local -f Dockerfile.docker .
docker image ls | grep snyk-docker:local 
```
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers
> Docker container size reduction

- src/cli/commands/monitor.ts
Add package manager & plugin options to analytics to help with debugging via logs.
> feat: Add more analytics around monitor

- src/lib/monitor.ts
> feat: Add branch analytics back

- src/lib/monitor.ts
add isDocker analytics to better monitoring
> feat: add isDocker to monitor analytics

- .travis.yml
- appveyor.yml
> test: Add node 12 to test matrix

- src/lib/plugins/nodejs-plugin/npm-modules-parser.ts
Add fall back to package manager to fix an issue where sometime the error shows `undefined` for package manager.
> fix: fix undefined in error for node_modules traversal

- .releaserc
Fixes a bug in the publishing process, debuggable via travis...
> fix: publishing container cannot run with TTY

- src/cli/commands/protect/index.ts
- refactor to `async/await`
- Remove unused function prop
> feat: remove unused function prop & improve error handling

- src/cli/commands/policy.js
- src/cli/commands/protect/index.ts
- src/lib/errors/failed-to-load-policy-error.ts
- src/lib/errors/index.ts
- src/lib/errors/legacy-errors.js
- src/lib/errors/policy-not-found-error.ts
Rewrite the legacy errors into new format:
- Missing policy error -> can't locate a policy file
- Failed to load a policy error -> something wen't wrong loading up the policy
> Feat: refactor policy errors

- help/help.txt
Add exit statuses to cli help text 
[BST-737](https://snyksec.atlassian.net/browse/BST-737l)
> chore: add exit statuses to cli help text

- help/help.txt
- remove experimental wording
- add nuget option `--packages-folder`
> chore: Update docs with usage options

- .snyk
> fix: ignore new lodash vuln

- package.json
- src/cli/commands/monitor.ts
- src/lib/snyk-test/run-test.ts
Upgrade version of sbt plugin to generate dependencies using a newly written scala plugin.
pending https://github.com/snyk/snyk-sbt-plugin/pull/46
> feat: upgrade sbt plugin to use custom dependency generation plugin

- help/file.txt
- src/lib/detect.ts
- test/acceptance/cli.acceptance.test.ts
Enable autodetection of go.mod file
https://snyksec.atlassian.net/browse/BST-725
> feat: autodetect go.mod file

- src/cli/commands/test.ts
- src/lib/errors/failed-to-get-vulnerabilities-error.ts
- src/lib/errors/index.ts
- src/lib/errors/internal-server-error.ts
- src/lib/errors/legacy-errors.js
- src/lib/snyk-test/run-test.ts
- src/lib/types.ts
- test/fixtures/cli-test-results/lodash@4.17.11
- test/system/cli.test.ts
- test/system/remote-package.test.ts
- Add custom errors to test results
- Remove old code around handling package vulns
- Add a tip to try testing with `--dev` not as part of error flow
> feat: refactor snyk test http errors

- appveyor.yml
- test/acceptance/cli-args.test.ts
- test/acceptance/protect.test.ts
> fix: reinstate windows cli tests

- package.json
Update sbt plugin version, so output will contain `packageFormatVersion` key
> feat: update sbt plugin, so output will contain packageFormatVersion

- docker/Dockerfile.docker
- docker/Dockerfile.gradle-2.8
- docker/Dockerfile.gradle-4.4
- docker/Dockerfile.gradle-5.4
- docker/Dockerfile.maven-3.5.4
- docker/Dockerfile.npm_ruby
- docker/Dockerfile.python-2
- docker/Dockerfile.python-3
- docker/Dockerfile.sbt-0.13.16
- docker/Dockerfile.sbt-1.0.4
Install git in the docker images.
Check that git is installed in the docker images, and that snyk monitor is able to get the remote URL and branch information.
Git is used in `snyk monitor` to fetch the remote URL and branch. If git is not installed, no error is shown or logging is done, and the behaviour is inconsistent.
https://support.snyk.io/hc/en-us/requests/967
> fix: Install git in snyk docker files

- package.json
> feat: bump dep-graph semver

- package.json
Upgrade sbt plugin to https://github.com/snyk/snyk-sbt-plugin/releases/tag/v2.5.7
Fixes "undefined references" issues when using on an sbt-native-packager project
> fix: upgrade sbt-plugin to support native packager

- package.json
Update the sbt plugin to include `tslib` as prod dependency, as
it fails with `pnpm`.
Solves https://github.com/snyk/snyk/issues/667
> feat: update the sbt plugin to accommodate a github issue

- package.json
bump nodejs-lockfile-parser version
> chore: bump nodejs-lockfile-parser version

- src/cli/commands/monitor.ts
- src/lib/errors/index.ts
- src/lib/errors/unsupported-feature-flag-error.ts
- test/acceptance/cli.acceptance.test.ts
Add custom error for unsupported feature flags cases
Add test for that
> chore: unsupported flag error

- src/lib/monitor.ts
- test/acceptance/cli.acceptance.test.ts
Change monitor graph body prop name to more
> fix: monitor graph send body key

- src/cli/commands/protect/wizard.js
- test/wizard-package-changes.test.js
> Revert "Feat/windows compatible scripts"

- package.json
`tslib` was missing from the go plugin, this upgrade should include
it on the ts-lib.
Solves https://github.com/snyk/snyk/issues/667
> fix: update go plugin to allow installation with `pnpm`

- package.json
Update php plugin to move `tslib` as production dependency
Helps to solve https://github.com/snyk/snyk/issues/667
> feat: update php plugin to move tslib as production dependency

- src/lib/errors/index.ts
- src/lib/errors/unsupported-package-manager-error.ts
- src/lib/plugins/index.ts
- src/lib/snyk-test/index.js
- test/acceptance/cli-args.test.ts
> feat: Unsupported package manager error

- src/cli/commands/test/formatters/legacy-format-issue.ts
- src/cli/commands/test/index.ts
- src/lib/snyk-test/legacy.ts
- src/lib/snyk-test/run-test.ts
- Add types to expect remediation object back from the main app
- Introduce formatter dir to start moving to a plugin based formatter structure
> feat: Actionable remediation types + refactor to introduce formatter concept

- package.json
Update sbt plugin version that is fixing 2 bugs:
1. Correct sbt version resolving
2. Correct project name for multi-projects case for new plugin
> feat: update sbt plugin that fixes wrong sbt version retrieving

- package.json
upgrade nodejs-lockfile-parser to add cyclic label on tree
> feat: add pruned-cyclic label to nodes

- src/lib/monitor.ts
- src/lib/package-managers.ts
- test/acceptance/cli.acceptance.test.ts
- test/acceptance/workspaces/sbt-simple-struts/monitor-graph-result.json
add `sbt` to PMs using graphs on monitor flow
> feat: use trees for handling sbt projects monitor

- src/cli/commands/auth/index.ts
- src/cli/commands/monitor.ts
- src/cli/commands/protect/prompts.ts
- src/cli/commands/protect/tasks.ts
- src/cli/commands/protect/wizard.ts
- src/lib/module-info/index.ts
- src/lib/npm.ts
- src/lib/plugins/nodejs-plugin/npm-modules-parser.ts
- src/lib/snyk-test/legacy.ts
- src/lib/snyk-test/run-test.ts
- src/lib/spinner.ts
- src/lib/types.ts
Makes the wizard a bit less magical.
Wherever they can pour themselves a hard drink. This code needs some preparation.
> fix: converted wizard to Typescript

- package.json
upgrade to typescriptified plugin that adds the dev option to be passed through
> fix: add nuget dev option

- help/help.txt
Update outdate help doc for `ignore-policy`
> fix: Update ignore policy option description

- help/help.txt
- src/cli/args.ts
- test/acceptance/cli.acceptance.test.ts
Change option `strictOutOfSync ` to kebab case & maintain backwards compatibility
> fix: make strictOutOfSync option kebab case

- package.json
Use latest version of graph lib that preserves `cyclic` labels
> feat: bump graph lib to use cyclic labels

- package.json
bump snyk-mvn-plugin to v2.3.3, after lodash has been upgraded to latest due to a vuln.
> feat: bump snyk-mvn-plugin to v2.3.3

- package.json
Much needed performance improvements for core dotnet projects thanks to @talik077
> fix: upgrade nuget plugin for performance improvements

- package.json
- use a later version fo resolve-deps that has some refactored changes
> feat: release refactored resolve-deps

- docker/Dockerfile.maven-3.6.1
- docker/Dockerfile.maven-3.6.1_java-11
Merging contribution to the side-branch to be able to perform all necessary tests.
> Maven 3 6 1

- src/cli/commands/test/formatters/legacy-format-issue.ts
- src/cli/commands/test/formatters/remediation-based-format-issues.ts
- src/lib/snyk-test/legacy.ts
Add fixed in info when available, even though there is no direct upgrade it is helpful still as some deps can be pinned.
> feat: fixed in info on vulns

- package.json
Update based on https://github.com/snyk/snyk-mvn-plugin/issues/31
> feat: Update snyk-mvn-plugin

- package.json
Improved Dockerfile parsing:
- Resolve aliases names on multi-stage builds
- Resolve variables on packages install commands
> feat: docker-plugin bump

- package.json
Bump snyk-nuget-plugin version to 1.12.0 to pick up a fix related to a support issue.
> fix: bump snyk-nuget-plugin to 1.12.0

- package.json
Update based on https://github.com/snyk/snyk-sbt-plugin/issues/60
> feat: Update snyk-sbt-plugin

- package.json
Update `snyk-nuget-plugin` version to bring `net4` target framework support.
> feat: update nuget plugin to support net4 target framework

- src/cli/commands/test/formatters/remediation-based-format-issues.ts
> fix: correct order of parameters in formatIssue

- package.json
Release a new plugin version that includes:
https://github.com/snyk/snyk-sbt-plugin/pull/62
https://github.com/snyk/snyk-sbt-plugin/pull/63
> feat: release new sbt plugin

- src/cli/commands/test/formatters/remediation-based-format-issues.ts
> feat: Actionable remediation license info section

- README.md
- docker/docker-entrypoint.sh
Allows jq to parse array of results when running in docker.
> fix: support subprojects in docker image and update docs

- src/lib/snyk-test/run-test.ts
Improves the runTest error logs to help debugging what went wrong.
> feat: improve run test error logs

- src/cli/commands/test/formatters/remediation-based-format-issues.ts
Fixes an issue when running `snyk test` on an org with the `actionableCliRemediation` flag and filtering by severity levels `snyk test --severity-threshold=...`
> fix: actionableCliRemediation FF with severity treshold flag

- package.json
Update after https://github.com/snyk/snyk-gradle-plugin/issues/93 was implemented
> feat: Update to 3.1.0 snyk-gradle-plugin

- help/help.txt
Fix a couple of spelling mistakes in docs
> fix: correct docs spelling

- package.json
Update to the latest snyk-cocoapods-plugin to consume the fixes around lockfile parsing: https://github.com/snyk/cocoapods-lockfile-parser/pull/18 and https://github.com/snyk/cocoapods-lockfile-parser/pull/17.
> fix: update snyk-cocoapods-plugin

- .snyk
- package.json
- Tidies snyk policy file
- Removes expired ignores, and unapplied patches
> chore: tidy snyk policy file

- src/cli/commands/auth/index.ts
Refactor auth to use async / await
> feat: refactor auth to use async await

- package.json
Bump snyk-nuget-plugin to latest version to keep it up to date, no functional changes in the last relase that will affect the CLI
> feat: keep nuget plugin up to date, no functional impact

- package.json
- src/lib/snyk-test/run-test.ts
Revert the package version lookup patch after the root cause was fixed in the plugin [snyk-docker-plugin/pull/115](https://github.com/snyk/snyk-docker-plugin/pull/115)
> fix: use plugin fix and revert package version lookup

- package.json
bump of version after merge of https://github.com/snyk/snyk-cli-interface/pull/21
https://github.com/snyk/snyk-cli-interface/pull/21
> feat: updated snyk-cli-interface to latest version

- package.json
- src/cli/commands/auth/index.ts
- Gradually swap out custom spinner for a spinner library.
- Swap it out on auth in this PR
Ora by default has different loader, it looks nice WDYT?
> feat: user new spinner lib for auth

- src/cli/commands/test/formatters/remediation-based-format-issues.ts
- src/lib/snyk-test/legacy.ts
- test/acceptance/workspaces/pip-app-transitive-vuln/response-with-remediation.json
Refactor PinRemediation datastructure to align with UpgradeRemediation, chaning 'issues' to 'vulns'.
> chore: refactor pin remediation data structure

- test/monitor-target.test.ts
Use tap instead of tape on a flaky test
> fix: rewrite test to use mocked server

- src/lib/plugins/nodejs-plugin/npm-lock-parser.ts
- src/lib/plugins/nodejs-plugin/npm-modules-parser.ts
- src/lib/snyk-test/run-test.ts
- test/acceptance/cli.acceptance.test.ts
- test/acceptance/protect.test.ts
- test/missing-node-modules.test.ts
- test/package-no-name.test.ts
- test/system/remote-package.test.ts
Temporarily revert snyk/snyk#807 as the spinner clearing is adding in `ansi` escape characters that break the `--json` output in console, tests did not catch this.
> Revert "Feat: replace spinner"

- package.json
bumping gradle-plugin after merge of https://github.com/snyk/snyk-gradle-plugin/pull/100
> feat: updated snyk-gradle-plugin to latest version

- src/cli/commands/monitor.ts
- src/cli/commands/monitor/formatters/format-monitor-response.ts
- src/cli/commands/monitor/index.ts
- src/cli/commands/test/formatters/legacy-format-issue.ts
Refactor to use more functions for easier to read & understand code
Added more types
> Refactor: monitor to tidy & use more functions for readability and maintanability

- src/lib/monitor.ts
- test/acceptance/cli.acceptance.test.ts
- test/monitor-target.test.ts
Fix the relative path sent back to registry, to be relative to the path from where the targetFile was found.
> fix: propagate correct relative path

- .releaserc
Following on from other PR which validates this flow within our CI this makes the actual change.
https://github.com/snyk/snyk/pull/854
> fix: adds back update functionality on npm versions of release

- package.json
- test/acceptance/cli.acceptance.test.ts
- test/acceptance/workspaces/composer-app/composer.json
- test/acceptance/workspaces/composer-app/composer.lock
Bump snyk-php-plugin to v1.7.0.
This version includes facility to parse dev packages.
Added acceptance test to ensure dev option would be passed to
snyk-php-plugin.
Added dev dependency to composer-app test fixture.
Run CLI against composer project with '--dev' flag, to see results make sure the project has require-de dependencies.
BST-917
Example using composer-with-vulns snyk-fixture:
> feat: composer dev require

- help/file.txt
- help/help.txt
- package.json
- src/lib/detect.ts
- test/acceptance/cli.acceptance.test.ts
- Release CocoaPods `test` and `monitor` (GA)
- Enable auto-detect
- Add `help` docs for CocoaPods options
> feat: Release CocoaPods `test` and `monitor`

- package.json
bump after https://github.com/snyk/snyk-sbt-plugin/pull/66 was merged
> feat: update snyk-sbt-plugin to latest

- package.json
bump version after https://github.com/snyk/snyk-gradle-plugin/pull/103 was merged
> feat: bump snyk-gradle-plugin version to latest

- package.json
Bumps the Gradle plugin to the version tested with Gradle 6.
> test: ensure Gradle 6 is supported

- help/help.txt
- package.json
- src/cli/args.ts
- Update docs to document `--allow-missing` command for Python
- propagate `allowMissing` expected by the plugin as a `--skip-unresolved` cli flag
> feat: pass down allowMissing as `--skip-unresolved` down to the Python plugin

- package.json
- src/lib/errors/index.ts
- src/lib/project-metadata/target-builders/git.ts
- test/system/cli.test.ts
adds support for maven central managed unmanaged jar packages. 
see: https://github.com/snyk/snyk-mvn-plugin/pull/41
install and build, and run test/monitor with --file=path/to/.jar file.
> feat: add unmanaged jar scanning

- package.json
- src/lib/errors/index.ts
- src/lib/project-metadata/target-builders/git.ts
- test/system/cli.test.ts
> Revert "feat: add unmanaged jar scanning"

- src/lib/errors/index.ts
- src/lib/project-metadata/target-builders/git.ts
Fix prettier issue and trigger new release
> fix: prettier issue

- package.json
re-enable jar scanning with needle instead of request-promise-native
> feat: re-enable single jar scanning

- package.json
- src/lib/detect.ts
- test/acceptance/cli-test/cli-test.python.spec.ts
- test/acceptance/workspaces/setup_py-app/setup.py
> feat: add support for setup.py

- src/cli/commands/monitor/index.ts
- test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
- test/acceptance/fake-server.ts
This reverts commit 631b0fa87d11a75f2db724b4bdf1e28c6a18ab70, reversing
changes made to f92319f3537fca9c1f263a87abe87ab8c2cdeb6a.
> feat: Revert "Merge pull request #884 from snyk/feat/parallelize-monitor"

- package.json
It uses a latest parser that has the props parsing logic
but this is all still unused
> feat: bump nuget plugin to 1.14.0 no functional changes

- package.json
- use latest nuget plugin, no functional changes.
> feat: bump nuget plugin, no functional changes

- test/runtime.test.ts
> chore: convert test to ts

- src/cli/commands/monitor/index.ts
- src/cli/commands/protect/wizard.ts
- src/cli/commands/test/index.ts
- src/lib/feature-flags.ts
- src/lib/monitor.ts
- test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
- test/acceptance/fake-server.ts
- test/monitor-target.test.ts
Send a graph for monitor if org supports it.
> feat: monitor graph by default if enabled for npm and sbt

- src/cli/index.ts
- src/cli/runtime.ts
Drop showing Node 6 end of life message as the backend will send an alert when relevant.
> feat: drop node 6 alert, it will come from the back end

- package.json
Bump plugin to latest version (brings in unused functionality from dotnet-parser)
> feat: bump plugin no functional changes

- src/lib/package-managers.ts
- test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
Enable yarn to post monitor graph
> feat:  enable yarn to send graphs for cli monitor

- package.json
Use latest parser that has some perf improvements for larger projects.
> feat: perf improvement for yarn lockfile projects

- src/lib/monitor/count-total-deps-in-tree.ts
- src/lib/monitor/drop-empty-deps.ts
- src/lib/monitor/filter-out-missing-deps.ts
- src/lib/monitor/index.ts
- src/lib/monitor/prune-dep-tree.ts
- src/lib/plugins/get-deps-from-plugin.ts
- src/lib/plugins/get-multi-plugin-result.ts
- src/lib/plugins/get-single-plugin-result.ts
- src/lib/policy/index.ts
- src/lib/policy/pluck-policies.ts
- src/lib/snyk-test/run-test.ts
Split out helper functions into their own files
> chore: refactor shared code out and split out helper functions

- package.json
fix for https://github.com/snyk/snyk-sbt-plugin/pull/70
https://github.com/snyk/snyk-sbt-plugin/issues/67
> feat: scan with --sbt-graph by default

- src/cli/commands/monitor/formatters/format-monitor-response.ts
- src/cli/commands/monitor/index.ts
Move constructing manageUrl to a more appropriate place.
> chore: refactor manage url into a function

- src/cli/commands/monitor/index.ts
- src/cli/commands/test/formatters/docker/format-docker-advice.ts
- src/cli/commands/test/formatters/docker/format-docker-binary-heading.ts
- src/cli/commands/test/formatters/docker/format-docker-binary-issues.ts
- src/cli/commands/test/formatters/docker/index.ts
- src/cli/commands/test/formatters/format-error-result-summary.ts
- src/cli/commands/test/formatters/format-test-meta.ts
- src/cli/commands/test/formatters/format-vulnerable-result-summary.ts
- src/cli/commands/test/formatters/index.ts
- src/cli/commands/test/index.ts
- src/lib/plugins/get-sub-project-count.ts
- src/lib/right-pad.ts
- src/lib/snyk-test/legacy.ts
- src/lib/snyk-test/run-test.ts
- split out formatting functions as helpers
- split & re-use the subProjecctCount helper 
- add some types
> Refactor project count test & test formatters

- test/acceptance/cli-test/cli-test.acceptance.test.ts
> chore: enable accidentally disabled tests

- src/cli/commands/protect/wizard.ts
- src/lib/types.ts
Slight refactor of wizard flow
> refactor: Drop some promise chains in wizard flow

- src/cli/commands/test/formatters/legacy-format-issue.ts
- src/cli/commands/test/index.ts
- src/lib/types.ts
- test/acceptance/cli-test/cli-test.python.spec.ts
Drop pinning flag handling it is supported by default to Pip projects
> feat: drop pinning flag

- src/lib/plugins/get-deps-from-plugin.ts
Add analytics for --all-projects CLI arg
> feat: add analytics for --all-projects

- package.json
Bump snyk-gradle-plugin to not use unused dependency
> fix: update snyk-gradle-plugin version

- help/help.txt
- src/cli/copy.ts
- src/cli/index.ts
- src/lib/errors/exclude-flag-bad-input.ts
- src/lib/errors/exclude-flag-invalid-input.ts
- src/lib/errors/index.ts
- src/lib/errors/option-missing-error.ts
- src/lib/plugins/get-deps-from-plugin.ts
- src/lib/types.ts
- test/acceptance/cli-args.test.ts
- test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
- test/acceptance/cli-test/cli-test.all-projects.spec.ts
Ignore directories when using --all-projects.
Added tests for test and monitor with --exclude.
`snyk test --all-projects --detection-depth=2 --exclude=example-dir,example-2`
BST-1126
> feat: add exclude arg and use to ignore

- test/git-repos.test.ts
The git-repos test is failing on Windows, Node 8, reporting connection
errors.
Skipping for now to unblock CLI pull requests.
> fix: skipping git-repos test

- src/cli/commands/monitor/index.ts
- src/lib/plugins/convert-multi-plugin-res-to-multi-custom.ts
- src/lib/plugins/convert-scanned-projects-to-custom.ts
- src/lib/plugins/convert-single-splugin-res-to-multi-custom.ts
- src/lib/plugins/get-multi-plugin-result.ts
- src/lib/snyk-test/run-test.ts
- test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
- propagate the plugin meta as is to each test run to support the fact some projects send TargetFile in there and some do not.
> feat: propagate full plugin meta always

- help/help.txt
Adding docker --file option to help.
> fix: add docker file flag option to help

- help/file.txt
Small textual update for `--file` option with `monitor` command
Resolving https://github.com/snyk/snyk/issues/967
> chore | Added info about --file for monitor

- help/help.txt
Adds documentation for jar scanning
> fix: add documentation for jar scanning

- README.md
- link to all the image tags for all languages
- update Python examples to show all supported
scan types
https://github.com/snyk/snyk/issues/786
> chore: update docs for Python Docker

- package.json
- it dropped some update deps logic which is not used in CLI
- no functional change for cli
> feat: use latest python plugin

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
Fix emojis to show in github by using unicode version of them
> chore: fix emojis in github

- package.json
Release support for `mvnw`.
contribution from @sfat: https://github.com/snyk/snyk-mvn-plugin/pull/50
solving issue: https://github.com/snyk/snyk/issues/957
> feat: snyk-mvn-plugin with mvnw support

- src/lib/protect/update.js
- src/lib/yarn.ts
> chore: convert yarn util to ts

- package.json
Update go plugin to respect --file option
> feat: update go plugin to respect --file option

- package.json
Bumping the version for the snyk-go-plugin
> fix: Bump version for the snyk-go-plugin

- scripts/check_circleci_status.sh
Fix for build process Windows checker
On merge PR use correct commit SHA
> fix: on merge PR use correct commit SHA

- package.json
Update `snyk-gradle-plugin` to use --daemon option if passed
> feat: update snyk-gradle-plugin to use --daemon option if passed

- src/lib/errors/failed-to-get-vulns-from-unavailable-resource.ts
- src/lib/errors/index.ts
- src/lib/snyk-test/run-test.ts
- test/acceptance/cli-test/cli-test.generic.spec.ts
fix: cli error message when <snyk test> command fails.
before was appearing only `intenal error`
> fix: cli error message when <snyk test> command fails.

- .github/CODEOWNERS
Make content team be flagged for any docs changes
> feat: add content team as code owner

- package.json
bumping the snyk-docker-plugin to a version that now supports an experimental analysis for Google's Distroless images.
this analysis is opted in by providing the `--experimental` flag.
https://github.com/snyk/snyk-docker-plugin/pull/157
https://github.com/snyk/snyk-docker-plugin/pull/159
```node ./dist/cli/index.js test --docker gcr.io/distroless/base-debian9:latest --experimental```
#feat-distroless-image-scanning
https://snyksec.atlassian.net/browse/RUN-789
> feat: snyk-docker-plugin with experimental Distroless scanning

- src/cli/commands/protect/wizard.ts
- [X ] Ready for review
- [ X] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
The wizard is trying to read from the disk before we are making sure that writing has finished. This will cause the process to fail later on
> fix: making sure writing to disk has finished before reading

- help/help.txt
fixes some of the snyk help text
> docs: fix up some of the language

- help/help.txt
Updates python options' documentation
> docs: updated python options documentation.

- .circleci/config.yml
Install missing semantic-release package
> fix: install missing semantic-release package

- .circleci/config.yml
Global packages permissions during the release process
> fix: global packages permissions during release

- .circleci/config.yml
- .releaserc
Add missing global package to global packages
> fix: add missing global package to global packages

- src/lib/package-managers.ts
- test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
- test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
Allow ruby to monitor a graph  behind FF if this is enabled on the org.
> feat: enable ruby graph monitor

- src/cli/commands/test/formatters/remediation-based-format-issues.ts
- src/cli/commands/test/index.ts
- src/lib/cloud-config-projects.ts
- src/lib/snyk-test/legacy.ts
- src/lib/snyk-test/run-test.ts
- src/lib/types.ts
NO logic changes!
2 main parts:
* Break big functions (displayResult and runTest)into smaller ones - to make the next PR much more easy
* Add SupportedProjectTypes for Cloud Config support
> chore: preps for cloud config support

- package.json
upgrade of snyk-nodejs-lockfile-parser from v1.18.0 to v1.21.0
> feat: upgrade of snyk-nodejs-lockfile-parser

- src/lib/analytics.js
Prettify failing for CLI for `src/lib/analytics.js`
> chore: fix prettify for analytics.js

- package.json
- src/lib/monitor/index.ts
- src/lib/project-metadata/index.ts
- src/lib/project-metadata/target-builders/container.ts
- src/lib/project-metadata/target-builders/git.ts
- src/lib/project-metadata/types.ts
- src/lib/snyk-test/run-test.ts
In order to support app+os projects, we need a way to set the target on the project so they can be properly grouped in the UI
> feat: app+os cli changes. bump docker-plugin. adding target to container/docker projects

- src/lib/monitor/index.ts
- [ X] Ready for review
- [ X] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ X] Reviewed by Snyk internal team
A small fix to make sure the branch exists on a git target
> fix: make sure branch exists

- src/lib/snyk-test/run-test.ts
bump [`snyk-mvn-plugin`](https://github.com/snyk/snyk-mvn-plugin/) to 2.12.0 (introduced in https://github.com/snyk/snyk-mvn-plugin/pull/59) which includes a set of metrics related to reachableVulns.
Checking the `snyk-mvn-plugin` PR for context.
`node ${snyk_cli_path}/dist/cli/index.js test --reachable-vulns` should produce no errors.
> feat: add callgraph metrics to run-tests

- package.json
Following a contribution (https://github.com/snyk/snyk/pull/1099).
The contributor had an issue w/ signing CLA (was signed before), so this was created in order to speed things up;
> chore: bump @snyk/dep-graph to 1.18.3

- package.json
Bumps snyk-mvn-plugin to get a fix on `java call graph builder` to fix an issue with multiple nested target dirs.
https://github.com/snyk/java-call-graph-builder/pull/17
> fix: bump snyk-mvn-plugin to 2.15.1

- .github/workflow/release-notes.yaml
This pr allows the preview of expected release notes on every pull request.
> chore: add snyk/release-notes-preview.

- test/cli-server.js
Cleared a log for less noise in our logs;
Was a part of a bigger PR and was let in by mistake
> chore: forgotten log removed to reduce noise

- package.json
- src/lib/container/index.ts
- src/lib/monitor/index.ts
- src/lib/monitor/utils.ts
- src/lib/plugins/convert-scanned-projects-to-custom.ts
- src/lib/project-metadata/index.ts
- src/lib/project-metadata/target-builders/container.ts
- src/lib/project-metadata/target-builders/git.ts
- src/lib/snyk-test/run-test.ts
- test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
- test/cli-monitor-utils.test.ts
- test/container.test.ts
- test/fixtures/dep-graph/dep-graph.json
- [ X] Ready for review
- [ X] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ X] Reviewed by Snyk internal team
- snyk monitor | container manifest file scanning in --experimental flag
- Bump the snyk-docker-plugin
Notes:
1. All the code changes are under the `--experimental` flag
2. snyk test changes will be done on another PR
This is an example output of an image with a node app inside:
> feat: container manifest file scanning in --experimental flag

- help/help.txt
improve policy-path help text and example
There was some confusion on how to use --policy-path, so improving messaging
> chore: improve policy-path help text and example

- package.json
Updates the `test:acceptance` script in the package.json so that acceptance tests in the root of `test/acceptance` are run.
https://snyk.slack.com/archives/CFTAUCYQ7/p1589208414100000
> chore: update test:acceptance include root tests

- package.json
Bump the nuget plugin. Critically, this removes an abandoned version of core-js from our dependency tree.
> feat: upgrade nuget-plugin, removing core-js

- package.json
> fix: bug in rpm non-existence error handling in snyk-docker-plugin

- src/lib/utm.ts
- test/system/cli.test.ts
adding default utms for cli auth flow
run `snyk-auth`
> feat: added default utm params for cli auth flow

- package.json
This bump of version brings the initial graph support to snyk-gradle-plugin, to help fix the OOM issues that we are current having with big trees.
> fix: initial graph support to solve gradle oom

- package.json
fix gradle legacy support version v2
the issue was that we were it was not cloning the legacy task into the customer's environment
> fix: gradle legacy version

- package.json
Upgrade go-plugin to release this fix: https://github.com/snyk/snyk-go-plugin/pull/70
> fix: go-plugin js heap oom using reverse for loop

- package.json
fix command issue on check gradle version
> fix: command issue on check gradle version

- package.json
https://github.com/snyk/snyk-docker-plugin/pull/215
[Slack thread/request](https://snyk.slack.com/archives/CGSNWAE76/p1590592306170600)
> fix: upgrade docker-plugin to resolve crashes when scanning binaries

- package.json
This PR allows gradle v2 of use the new gradle task, and drops the legacy one that was being used by gradle v2.
> feat: support gradle v2 on new task and drop legacy one

- package.json
Update mvn plugin to include new java call graph generator
> feat: update mvn plugin to include new java call graph generator

- package.json
Revert apk package name origin change.
> fix: revert apk package name origin change

- package.json
Correct error on missing target folder for reachable vulns,
Based on https://github.com/snyk/snyk-mvn-plugin/pull/72
> fix: correct error on missing target folder for reachable vulns

- config.default.json
Allows project that have a large path than the current allowed to pass after they are pruned
> feat: allow large projects to pass after prune

- package.json
bump snyk-docker-plugin to improve alpine scanning
https://snyksec.atlassian.net/browse/RUN-987
> fix: bump snyk-docker-plugin to improve alpine scanning

- src/lib/snyk-test/run-test.ts
Type scanned projects to graph or tree.
No functional changes, just Typescript.
> chore: type scanned projects to graph or tree

- src/cli/commands/monitor/index.ts
The scenario of this pr is the following one:
Imagine an user tries to scan a mono-repo and this repository possess 200 sub-projects.
What we normally do? If a single project import is unsuccessful we just abort everything without push forward the others that could be imported without issues.
So now what's gonna happen? If 1 or 5 projects of 200 fails, they will be just skipped and the import will continue, and this will be really helpful to import large scale-projects.
> fix: allows scanning even if a single proj import fails

- help/container.txt
* Fixed alignment of options
* Added missing global options
* Added examples, including for archive files
Improves the help text in the CLI for the `snyk container` commands.
`snyk container --help`
The features around archives are already in the CLI, just not in the docs.
> chore: update Snyk Container help text

- src/cli/commands/test/formatters/format-reachability.ts
- src/lib/snyk-test/legacy.ts
- test/acceptance/display-test-results.test.ts
- test/reachable-vulns.test.ts
support potentially reachable on `snyk test`.
Also, changed removed the "likely" wording from the other
reachability buckets.
Run `snyk test --reachable-vulns`
https://snyksec.atlassian.net/browse/FLOW-242
> feat: support potentially reachable on snyk test

- src/lib/prune.ts
- src/lib/snyk-test/run-test.ts
Updates snyk test prune logic be the same as the new one that was applied on snyk monitor.
> feat: update snyk test prune logic

- src/cli/commands/protect/wizard.ts
- test/acceptance/cli-wizard/cli-monitor.acceptance.test.ts
- test/acceptance/fake-server.ts
- test/acceptance/workspaces/npm-package-no-vulns/node_modules/ms/index.js
- test/acceptance/workspaces/npm-package-no-vulns/node_modules/ms/license.md
- test/acceptance/workspaces/npm-package-no-vulns/node_modules/ms/package.json
- test/acceptance/workspaces/npm-package-no-vulns/node_modules/ms/readme.md
- test/acceptance/workspaces/npm-package-no-vulns/package-lock.json
- test/acceptance/workspaces/npm-package-no-vulns/package.json
Fix incorrect option passed for targetFileRelativePath
Add test for wizard and supported package manager
> fix: snyk-wizard

- package.json
high level break of cyclic dependencies on gradle plugin
> fix: break of cyclic dependencies on gradle cli

- src/lib/plugins/nodejs-plugin/yarn-workspaces-parser.ts
Use lodash fork, regression introduced in https://github.com/snyk/snyk/pull/1183
> fix: use lodash fork

- .github/CODEOWNERS
- help/iac.txt
- src/cli/commands/test/formatters/format-test-meta.ts
- src/cli/commands/test/formatters/legacy-format-issue.ts
- src/cli/commands/test/formatters/remediation-based-format-issues.ts
- src/cli/commands/test/iac-output.ts
- src/cli/commands/test/index.ts
- src/lib/errors/invalid-iac-file.ts
- src/lib/snyk-test/run-test.ts
- test/acceptance/cli-test/cli-test.iac-k8s.spec.ts
- test/acceptance/workspaces/iac-kubernetes/test-iac-result.json
Some refactoring to IaC test output:
* Create a separate function for formatting IaC issues (`formatIacIssue()`)
* Add a description to the issue
* Removed the link from the issue
* Add scan type instead of package manager
* Format IaC exceptions
> feat: improve IAC test output

- config.default.json
increases max limit of a project paths to be processed
> feat: increases max limit of a project paths to be processed

- help/help.txt
- src/lib/find-files.ts
- test/find-files.test.ts
Looks in 4 sub-folders deep by default.
https://github.com/snyk/snyk/pull/1233/files#r446505065
https://github.com/snyk/snyk/pull/1233/files#r446505065
> feat: bump default depth to 4

- package.json
- src/lib/spinner.ts
- tsconfig.json
Bump nodejs-lockfile-parser to 1.25.0
Adds initial support for yarn v2
Support for yarn workspace alternative configurations
Typescript 'dom' compiler option is required by transitive
dependency @yarnpkg/core introduced by yarn v2 feature
> feat: bump nodejs-lockfile-parser

- package.json
bumps snyk-docker-plugin
https://snyksec.atlassian.net/browse/RUN-995
> feat: scan container images without docker client

- package.json
- src/lib/plugins/nodejs-plugin/npm-lock-parser.ts
- test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
- test/acceptance/cli-test/cli-test.yarn.spec.ts
- test/acceptance/workspaces/yarn-v2/package.json
- test/acceptance/workspaces/yarn-v2/yarn.lock
add support to yarn v2
this depends of https://github.com/snyk/nodejs-lockfile-parser/tree/feat/yarn-v2
> feat: add support yarn v2

- .circleci/config.yml
Add test to check if new version of snyk is not broken
> chore: add test to check if new version of snyk is not broken

- .circleci/config.yml
Add checkout step to release job
> chore: add checkout step to release job

- test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
- test/acceptance/cli-test/cli-test.yarn.spec.ts
> test: run yarn v2 tests for Node 10

- docker/Dockerfile.gradle-5.4_java11
Update node version for Gradle with Java 11 standalone binary
> chore: Update node version for Gradle with Java 11 standalone binary

- .github/workflows/smoke-tests.yml
- test/smoke/install-shellspec-win.sh
- test/smoke/install-snyk-binary-win.sh
- test/smoke/run-shellspec-win.sh
- test/smoke/spec/snyk_basic_spec.sh
This is a GitHub actions workflow to run our new "Smoke Tests" through a variety of execution permutations:
- binary install
- npm install using NPM 8, 10, and 12
- macos, windows, linux
https://snyksec.atlassian.net/browse/HAMMER-80
> feat: GitHub Actions test runner for smoke tests

- .circleci/config.yml
- .releaserc
Tested [built v14 artifacts on CI](https://app.circleci.com/pipelines/github/snyk/snyk/1491/workflows/ccd98361-ceb3-40f6-bf74-c7358e20d4a1/jobs/7076/artifacts) on these platforms:
Can't reproduce the issues with previous update to v10 https://github.com/snyk/snyk/pull/672 - couldn't replicate the original reported issues with Alpine build
> Node v14 binaries build

- src/lib/snyk-test/index.js
- test/acceptance/cli-args.test.ts
Import the correct error & add tests to ensure this is covered.
> fix: correct infrastructure as code error import

- release-scripts/snyk-mac.sh
Allows to run the script from anywhere instead of just the folder it resides in.
Download and extract https://github.com/snyk/snyk/releases/download/v1.365.0/docker-mac-signed-bundle.tar.gz
Run
```
$ ls docker/
cli			config.default.json	help			node-v14.6.0-darwin-x64	node_modules		package-lock.json	package.json		snyk-mac.sh
$ ./docker/snyk-mac.sh 
./docker/snyk-mac.sh: line 7: ./node-v14.6.0-darwin-x64/bin/node: No such file or directory
```
Replace `snyk-mac.sh` with the one from this PR and notice that snyk runs successfully.
> Run mac-snyk.sh from anywhere

- .gitignore
- .npmignore
- .releaserc
- release-scripts/docker-desktop-release.sh
- release-scripts/sign-windows-binary.sh
- release-scripts/snyk-mac.sh
Adds a build steps for:
- signed windows binary
- archive of built CLI (npm-like package) with Node.js runtime embedded
> Docker partnership bundle

- src/lib/snyk-test/index.js
Simplify the validation logic & extract it for readability.
Blocked by https://github.com/snyk/snyk/pull/1292
> chore: simplify supported projects validation on test

- test/acceptance/fake-server.ts
Small refactoring - remove a comment (there by mistake :see_no_evil: )
> chore: remove irrelevant comment

- .gitignore
Adding `.vscode` to `.gitignore`
> chore:updated gitignore with vscode folder

- package.json
- src/lib/snyk-test/run-test.ts
Bump the Maven plugin version, and make some small adjustments to accommodate the changes in error reporting introduced in the latest version.
Also fixes --reachable behaviour on Windows
Run `snyk test -d --reachable --reachable-timeout=5`, and check the error reported for call graph generation.
https://snyksec.atlassian.net/browse/FLOW-373
> feat: improve error reporting for reachable vulnerabilities

- .github/CODEOWNERS
- src/lib/detect.ts
- src/lib/errors/unsupported-options-iac-error.ts
- src/lib/snyk-test/run-iac-test.ts
- test/acceptance/cli-args.test.ts
- test/acceptance/cli-test/cli-test.iac-k8s.spec.ts
Remove `--file` flag for IaC tests so the new command will be
`snyk iac test {file_name}`
> feat: remove file flag from iac tests

- src/cli/commands/protect/prompts.ts
- src/cli/commands/test/formatters/legacy-format-issue.ts
- src/cli/commands/test/formatters/remediation-based-format-issues.ts
- src/cli/commands/test/formatters/types.ts
- src/cli/commands/test/index.ts
- src/lib/snyk-test/legacy.ts
- test/acceptance/display-test-results.test.ts
- test/acceptance/fixtures/npm-package-with-severity-override/test-graph-result-no-remediation.json
- test/acceptance/fixtures/npm-package-with-severity-override/test-graph-result-patches.json
- test/acceptance/fixtures/npm-package-with-severity-override/test-graph-result-same-severity.json
- test/acceptance/fixtures/npm-package-with-severity-override/test-graph-result-unresolved.json
- test/acceptance/fixtures/npm-package-with-severity-override/test-graph-result-upgrade.json
- test/fixtures/original-severity-vulns.json
- test/prompts-show-original-severity.test.ts
https://snyksec.atlassian.net/browse/GOV-748
> feat: show original severity CLI

- package.json
- Bump cocoapods plugin that uses latest dep-graph lib & cli interface
> feat: bump cocoapods plugin to update graph & cli interface deps

- package.json
Adding windows support to snyk-docker-plugin.
> Bumping snyk-docker-plugin to 3.17.0

- src/lib/plugins/rubygems/inspectors/gemfile.ts
- test/acceptance/cli-test/cli-test.ruby.spec.ts
- test/acceptance/workspaces/ruby-app-custom-names/gemfiles/Gemfile.lock.rails-2.3.6
- test/acceptance/workspaces/ruby-app-custom-names/gemfiles/Gemfile.rails-2.3.6
Include a test that shows targeting a custom Gemfile with --file will not be able to determine the lockfile name and asks the user to use the lockfile.
> test: ruby custom gemfile test

- help/help.txt
Clarify yarn workspaces support level in help docs
> chore: update yarn workspaces support commands help text

- .gitignore
- .vscode/launch.json
It was removed few days ago https://github.com/snyk/snyk/pull/1308 - but actually it would be useful to have this shared for development.
> chore: add VS launch.json config

- help/iac.txt
- src/lib/errors/invalid-iac-file.ts
Explicitly mention that we support K8s only right now (as part of IaC)
https://snyk.slack.com/archives/CRV0PMFDH/p1598243270020000
> feat: explicitly write we support K8s only (IaC)

- src/cli/commands/monitor/index.ts
- src/cli/commands/test/index.ts
- src/lib/is-multi-project-scan.ts
- src/lib/options-validator.ts
- src/lib/reachable-vulns.ts
- src/lib/snyk-test/index.js
Simply the check as more flavours are added to be a simple function
<sub><img src="https://user-images.githubusercontent.com/4775299/87437657-e7332b00-c5ee-11ea-958d-589dfb19d72c.png" alt=" " width="10" height="9"> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>
> feat: simplify multi scan check with a function

- package.json
Bump snyk-cpp-plugin
Ignore broken files during cpp scan, see https://github.com/snyk/snyk-cpp-plugin/pull/12
> fix: ignore broken files during cpp scan

- .gitignore
- package.json
- src/lib/find-files.ts
- src/lib/plugins/get-deps-from-plugin.ts
- src/lib/plugins/get-extra-project-count.ts
- src/lib/plugins/nodejs-plugin/npm-lock-parser.ts
- test/acceptance/cli-test/cli-test.all-projects.spec.ts
- test/acceptance/workspaces/gradle-with-orphaned-build-file/settings.gradle
- test/acceptance/workspaces/gradle-with-orphaned-build-file/subproj/build.gradle
- test/find-files.test.ts
- https://github.com/snyk/snyk-cli-interface/pull/38
- https://github.com/snyk/snyk-gradle-plugin/pull/142
Detect and log orphaned or errored gradle project scans by comparing detected files vs scanned.
This is useful to find any gradle files that looked like they are part of a multi-project build but were in fact not included or had an error being scanned. Since only the root level file is detected these errors can otherwise fo unnoticed.
https://github.com/snyk/snyk/pull/1355/files#diff-91534f3e6e36be30e5b2863969dc6417R82
Drop a gradle file in a folder in a multi-build project, this file is not included as a sub-project and will be detected but not scanned since the gradle build will not return it.
> feat: Detect and log orphaned or errored gradle project scans by comparing detected files vs scanned.

- package.json
introduces https://github.com/snyk/snyk-mvn-plugin/pull/84 to the cli
> fix: mvnw incorrect execution path

- package.json
- src/lib/ecosystems.ts
- test/fixtures/cpp-project/display.txt
- test/fixtures/cpp-project/error.txt
- test/fixtures/cpp-project/testResults.json
Add color and improve how test results are displayed when running 'snyk
source test' for C/C++ projects.
Add spinner test to give more feedback to user as we test dependencies.
Remove type from ScanResult interface.
> feat: improve snyk source test display

- package.json
Adding error handling for `snyk container test` and `snyk container monitor` `--platform` flag when unknown platform or architecture passed.
https://snyksec.atlassian.net/browse/RUN-1162
> feat: Error handling for `--platform` flag

- package.json
- src/lib/monitor/index.ts
- test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
Adding platform extracted during static scanning to project metadata. This information will be then displayed on the project page.
https://snyksec.atlassian.net/browse/RUN-1155
> feat: Add platform to project metadata

- package.json
- src/lib/ecosystems.ts
- src/lib/types.ts
- test/ecosystems.spec.ts
- test/fixtures/cpp-project/debug-display.txt
- test/fixtures/cpp-project/error.txt
Bump to snyk-cpp-plugin and update CLI tests.
Only show fingerprint information when running with debug option.
> feat: use debug option with snyk-cpp-plugin

- src/cli/commands/woof.ts
https://es.wikipedia.org/wiki/Ladrido
> feat: add spanish language to snyk woof

- src/cli/commands/woof.ts
https://www.omniglot.com/language/animalsounds/dogs.htm
Adds another language spoken to `woof` command.
> chore: add czech language to snyk woof

- src/cli/commands/monitor/index.ts
- src/lib/monitor/dev-count-analysis.ts
- src/lib/monitor/index.ts
- src/lib/types.ts
- test/dev-count-analysis.spec.ts
- minor refactoring of src/lib/monitor/dev-count-analysis.ts to facility improved testing
- add additional testing to ensure merge commits are not counted in CLI dev count feature
Reviewing this very small PR: https://github.com/snyk/snyk/pull/1408
I should have included more testing in the last PR. This adds testing to make sure that adding `no-merges` to the git log command works as intended.
HAMMER-156
> Refactor git log analysis and add more testing

- package.json
- test/dev-count-analysis.spec.ts
> feat: add sles scanning support

- docker/Dockerfile.python-3.6
Signing for https://github.com/snyk/snyk/pull/1417
Modified the commit message to be aligned with contributing guidelines https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md#commit-messages
After merging, I'll setup dockerhub tag.
> feat(docker): create Dockerfile.python-3.6

- src/lib/analytics-sources.ts
Updates comment on CLI tracking usage
> chore: update comment on integration name

- package.json
updates `snyk-docker-plugin` dependency from `3.24.0` to `3.26.2`
* [v3.25.0](https://github.com/snyk/snyk-docker-plugin/releases/tag/v3.25.0) add platform info to CLI output
* [v3.26.0](https://github.com/snyk/snyk-docker-plugin/releases/tag/v3.26.0) display scan result as human readable format
* [v3.26.1](https://github.com/snyk/snyk-docker-plugin/releases/tag/v3.26.1) display scan result as human readable format
* [v3.26.2](https://github.com/snyk/snyk-docker-plugin/releases/tag/v3.26.2) fix --app-vulns flag parsing
1) should the commit message be a `fix` or a `feat`?
> feat: updated snyk-docker-plugin to v3.26.2

- src/cli/commands/woof.ts
- src/cli/commands/woof/getWoof.ts
- test/smoke/spec/snyk_basic_spec.sh
- test/woof.spec.ts
Woof command stopped working after #1441 
This PR fixes the functionality and introduces a woof smoke test
> fix: woof command

- package.json
Release latest snyk-gradle-plugin with extra logging to display any gradle attributes when scanning Android projects
> feat: release latest snyk-gradle-plugin with extra logging

- src/cli/commands/woof/getWoof.ts
Add Ukrainian language spoken to `woof` command
> chore: add Ukrainian language to snyk woof

- test/smoke/spec/iac/snyk_test_k8s_spec.sh
- test/smoke/spec/iac/snyk_test_terraform_spec.sh
Removes issue counters from expected results in smoke tests.
The count of discovered issues depends on amount of policies in remote service.
> fix: Remove flaky counters

- src/cli/commands/test/formatters/format-test-meta.ts
- src/lib/snyk-test/legacy.ts
- src/lib/snyk-test/run-test.ts
- test/acceptance/cli-test/cli-test.all-projects.spec.ts
- test/acceptance/cli-test/cli-test.docker.spec.ts
Add platform metadata to human-readable output
> chore: add platform metadata to human-readable output

- src/cli/args.ts
> chore: fixed typo in 'maven'

- src/cli/args.ts
Signed for a commit in https://github.com/snyk/snyk/pull/1481 so that PR can be merged
> chore: fix typo in 'maven'

- package.json
- test/acceptance/cli-args.test.ts
When running 'container test/monitor --platform', throw an error for multi arch images when image manifest specified by --platform does not exist.
https://snyksec.atlassian.net/browse/RUN-1172
> [RUN-1172] feat: Fail if container image manifest does not exist

- src/lib/ecosystems/monitor.ts
The spinner was flickering and overlapping with other messages and caused a bad user experience.
> fix: clear spinner in container monitor command

- help/help.txt
Minor fix in help text ordering
> fix: line in help against wrong command

- .github/workflows/cli-alert.yml
- test/cli-alert/package-lock.json
- test/cli-alert/package.json
- test/cli-alert/src/index.ts
- test/cli-alert/tsconfig.json
Using GitHub Actions, check the 3 most recent Smoke Tests every hour. If all three of them failed, re-run them and send a Slack alert if the re-run fails as well.
> feat: get slack alert when smoke tests fail

- package.json
Bump docker plugin version to include jar scanning in container
> feat: bump docker plugin version to include jar scanning in container

- .github/CODEOWNERS
Refactor iac owners of to encompass all files and directories
> refactor: fix iac codeowners

- .circleci/config.yml
- src/cli/args.ts
- src/cli/commands/help.ts
- test/smoke/spec/snyk_basic_spec.sh
- test/smoke/spec/spec_helper.sh
> feat: improve help command

- package.json
Update docker-plugin to avoid parsing bad base images.
- [ZenDesk #7256](https://snyk.zendesk.com/agent/tickets/7256)
> fix: update docker-plugin to avoid parsing bad base images

- package.json
Bump snyk-cpp-plugin 2.2.1 to fix:
* event loop blocking
* max function arg limit
When finding files during source scan.
See https://github.com/snyk/snyk-cpp-plugin/pull/19 and https://github.com/snyk/snyk-cpp-plugin/pull/20
> fix: snyk-cpp-plugin blocking event loop

- help/commands-docs/iac-examples.md
- help/commands-docs/iac.md
- package.json
- src/cli/args.ts
- src/cli/index.ts
- src/lib/detect.ts
- src/lib/errors/invalid-detection-depth-value.ts
- src/lib/iac/detect-iac.ts
- src/lib/iac/makeDirectoryIterator.ts
- test/makeDirectoryIterator.spec.ts
This PR implements the `--detection-depth` flag for the `snyk iac test` command to limit the depth of subdirectories that will be traversed when looking for files. For example:
```bash
% snyk iac test --detection-depth=3 # limit to only 3 subdirectories
```
The implementation forgoes the use of the existing `glob` module and instead walks the directory tree using the built in file system node module. This has several advantages:
1) The code is simpler and clearer\*. Rather than relying on the glob syntax and constructing an appropriate string we're just using a loop and recursive call allowing us to exit early when we reach the desired depth.
2) The use of the generator provides fine grained control over to the caller allowing them to use the `break`, `continue` & `return` constructs to …
> feat: Implement --detection-depth flag in iac command

- README.md
Improves the readability of one sentence in the project README.
> docs: fix a small grammatical issue in the README

- package.json
Pull in a version of the call graph builder with improved newline handling: https://github.com/snyk/java-call-graph-builder/pull/40
> fix: improve newline handling on windows

- package.json
Bump `snyk-docker-plugin` version to enable Go binaries scanning inside containers
> feat: enable Go binaries scanning inside containers

- test/cli-alert/src/index.ts
> fix: cli alert logic flaws

- help/commands-docs/_ENVIRONMENT.md
- help/commands-docs/container.md
Explain how to configure remote container registry credentials via environment variables and/or flags
> docs: Document username/password inputs

- package.json
Upgrades mvn-plugin to add support for .aar unmanaged files in the maven ecosystem.
> feat: maven support aar unmanaged files

- package.json
Uses the java call graph builder with improved logic. Details: snyk/java-call-graph-builder#41.
The changes to the java call graph builder should handle various platform differences better. They also add support for custom Maven configurations and better submodule handling.
Pull the changes in this branch, install the deps & build your local copy of the CLI. Run it on `java-reachability-playground`. It should have the same results as the current version.
This uses Maven plugins to derive the build and output directories as well as the list of submodules.
https://snyksec.atlassian.net/browse/FLOW-487
> feat: improve class path discovery for maven projects

- src/lib/ecosystems/test.ts
Show spinner scanning dependencies
> fix: show spinner scanning ecosystem

- help/commands-docs/_SNYK_COMMAND_OPTIONS.md
update help text for unmanaged aar files
> chore: help text for unmanaged aar files

- src/lib/prune.ts
Adds durations of graph conversion to tree and tree to graph while pruning to analytics.
> fix: add graph conversion while pruning duration analytics

- package.json
Bump gradle plugin to support non root gradlew for reachable vulns.
For more context go to https://github.com/snyk/java-call-graph-builder/pull/42
https://snyksec.atlassian.net/browse/FLOW-564
> feat: bump gradle plugin to support non root gradlew

- test/cli-alert/src/index.ts
Check latest 2 smoke tests' jobs. If the same jobs failed 2 times in a row, try to re-run the latest smoke test and check the job's conclusion. 
This ensures CLI alerts become less chatty and more focused on urgent problems Hammer should take care of.
> chore: check jobs’ success instead of workflow

- package.json
Upgrade go-plugin
This potentially resolves issue from customer: https://snyk.zendesk.com/agent/tickets/7956
> fix: update go plugin

- .github/ISSUE_TEMPLATE/bug-report.md
removing 1 typo and correcting markdown tag
No test beyond review: doc only
No
None
None
None
> Fixing bug report md - removing 1 typo and correcting markdown tag

- package.json
Bump snyk-python-plugin version to include fix for circular dependencies in poetry
> fix: bump python plugin version

- package.json
Improves how reachability handles gradle and android projects.
Relevant PRs:
https://github.com/snyk/java-call-graph-builder/pull/45
https://github.com/snyk/snyk-gradle-plugin/pull/160
> feat: improves reachability on gradle

- package.json
Discover aar and war file in the scan-all-unmanaged mode
Today we say that we support this in the documentation, but the code doesn't acts accordingly
> fix: mvn discover aar and war file in the scan-all-unmanaged mode

- .github/workflows/smoke-tests.yml
Adds a new variant to the smoke tests to test the signed macos Docker bundle.
> Add smoke test variant for Docker macos bundle

- test/cli-alert/src/index.ts
- Alert only for jobs that failed again (not the whole array of failedJobs)
- Wait for current run to finish before attempting re-run (fixes failures of CLI alerts)
CLI alerts failed a lot recently, as a result of trying to re-run smoke tests that are already running. This PR fixes this problem by waiting for the current run to finish before attempting a re-run.
> fix: alert msg, constant failure of CLI alerts

- package.json
Added auto detecting user instructions from container image config, so from now on customer won't need to provide a Dockerfile and will get this info for free. This can be seen on the individual vulnerability card as "Dockerfile instruction" and is also used to provide a filter on the project page. Bumping the plugin releases that feature for `snyk container monitor`.
https://snyksec.atlassian.net/browse/CAP-111
> [CAP-111] feat: Auto detect user instructions from image

- .circleci/config.yml
- release-scripts/validate-checksums.sh
Validates the computed checksums for the binary releases and fail build if they are not ok.
https://snyk.slack.com/archives/CH6616JU8/p1612466243049700
ZD 8834, 8836
> Validate binary release checksums

- help/commands-docs/_SNYK_COMMAND_OPTIONS.md
- src/cli/args.ts
- src/cli/commands/test/formatters/format-reachability.ts
- test/acceptance/display-test-results.test.ts
Some small improvements around reachability:
- Update reachability level from "no info" to "no path found"
- Add reachability to the Gradle help section
- Only pass reachabilityTimeout flag is we pass the `--reachable` flag.
https://snyksec.atlassian.net/browse/FLOW-613
https://snyksec.atlassian.net/browse/FLOW-589
> feat: update reachability level from "no info" to "no path found"

- src/lib/analytics-sources.ts
This PR adds Visual Studio as an official Snyk integration into analytic sources.
> feat: add Visual Studio as an official integration

- .circleci/config.yml
- release-scripts/should-i-release.sh
Just formatting and making it fail nicely in Circle
> Move release check to a standalone file

- Contributor-Agreement.md
> CLA update

- .circleci/config.yml
We have 4 groups of tests:
- the Tap tests in the "root" of the test directory
- the Jest tests
- the Acceptance tests
- the System tests
This PR groups these up into two groups:
1. the "root" Tap tests
2. the Jest, Acceptance, and System tests
Each of these groups runs for roughly the same time.
Splitting them as such and running them in parallel cuts down significantly on the total pipeline time.
It takes too long to run the pipeline.
> Run tests suites with additional parallelism

- package.json
includes fix to build connection for nodes that have already been added to dependency graph in Poetry
> fix: bump snyk-python-plugin

- test/cli-json-file-output.spec.ts
- test/ecosystems-test-cpp.spec.ts
> test: add longer timeoutsfor flaky tests

- package.json
Upgrade snyk-gradle-plugin to version 3.13.2, which involves cleaner interfaces on the plugin's side.
> fix: update snyk-gradle-plugin to 3.13.2

- test/ecosystems-test-cpp.spec.ts
> chore: bump flaky cpp test timeout

- package.json
Updates the version of `snyk-go-plugin` to add support for `replace` directive in go-modules
> feat: support gomod replace directive

- package.json
Add better support for [big yarn projects](https://github.com/snyk/nodejs-lockfile-parser/pull/93)
> feat: optimised dependency tree for yarn projects

- src/lib/version.ts
Gotta start somewhere. Picking a file and refactoring it with modern standards to make it more readable.
> chore: Convert some Promise code to async..await

- release-scripts/update-versions.sh
Switches the source of truth for releases to npm package
> Use npm release as source of truth for version

- .circleci/config.yml
Use Lerna version 3.22.1 for release since v4 broke the release.
Latest releases have failed without any message since starting to use Lerna v4.0.0
> Use lerna v3 for release

- package.json
We had some missing functionality inside `code-client` to support `snyk code test` flow on node10.
we needed just some minor adjustment in the `code-client` package to resolve this issue.
> feat: code client to support node10 functionality

- src/cli/commands/test/index.ts
- src/cli/commands/test/validate-credentials.ts
Refactor re-usable code in `test` and `monitor` in preparation for adding a new command that has similar needs.
> refactor: validateCredentials token check

- src/cli/commands/test/generate-snyk-test-error.ts
- src/cli/commands/test/index.ts
Extract complex error extraction into a callable function so it can be re-used in a new command
Move the result array closer to where they are needed
> refactor: generate snyk test error

- src/cli/commands/test/index.ts
- src/cli/commands/test/validate-test-options.ts
Extract snyk test option validation into a function so it can be easily re-used when needed across other commands.
> feat: extract validate test options

- README.md
It updates the README with a badge from the [Snyk Advisor page for Snyk CLI package](https://snyk.io/advisor/npm-package/snyk)
Should this be a commit of type "fix" instead of "docs" to also reflect the README changes on the npmjs package page?
> docs: update the project README with the Snyk Advisor score

- src/cli/commands/monitor/index.ts
- src/cli/commands/process-command-args.ts
- src/cli/commands/test/index.ts
- test/process-command-args.spec.ts
Extract command args processing that generate the test paths & options from input which can be a variety of shapes coming in. All in preparation for a new command that will need to re-use most of snyk test flow.
> feat: convert args into paths & options

- src/cli/commands/test/iac-local-execution/parsers/terraform-plan-parser.ts
Adds meaningful error messages to Terraform plan scanning and fixes cases where the child modules array is missing from the data structure.
The bug was in the reducing function which assumed `child_modules` is always present and didn't have safe defaults.
> fix: terraform plan parse bug

- .circleci/config.yml
Use CircleCI's Orb for AWS CLI: https://circleci.com/developer/orbs/orb/circleci/aws-cli
> Use Circle Orb for AWS CLI installation

- package.json
Adds support for cyclic graphs
> feat: support cyclic graph convertion to tree

- src/lib/plugins/sast/index.ts
- test/snyk-code-test.spec.ts
Adding better error handling for snyk code.
> fix: snyk code add more error handling

- src/lib/plugins/sast/index.ts
- test/snyk-code-test.spec.ts
This pr adds sarif support to snyk code
> feat: add sarif support for snyk code

- package.json
- scripts/format/prettier-changes.sh
This PR adds an option to run `npm run format:change`, which will run Prettier on all of the changed files (staged + not staged)
> chore: add script for formatting changed files

- test/snyk-code-test.spec.ts
when running `test/snyk-code-test.spec.ts`, locally and  we provide SNYK_TOKEN the test fails
> fix: snyk code - test fails if token provided

- packages/snyk-fix/src/index.ts
Let the consumers print the full summary. Only print progress summary. If nothing was fixed, print as error.
Needed in linked PR https://github.com/snyk/snyk/pull/1707
> feat: let CLI display the full summary

- src/lib/analytics-sources.ts
Unblocks https://github.com/snyk/snyk-maven-plugin/pull/119
> Analytics: add maven plugin as source

- src/cli/commands/test/iac-local-execution/results-formatter.ts
- src/cli/commands/test/iac-local-execution/types.ts
- test/jest/unit/iac-unit-tests/results-formatter.fixtures.ts
- test/jest/unit/iac-unit-tests/results-formatter.spec.ts
Adds a unit test to the results formatter + a minor naming refactor.
> test: results formatter for iac

- src/lib/plugins/sast/format/output-format.ts
- test/fixtures/sast/test-output-windows.txt
- test/fixtures/sast/test-output.txt
[COD-299]
Takes the title of SAST issues from the `shortDescription` field
[COD-299]: https://snyksec.atlassian.net/browse/COD-299
> [COD-299] fix: issue's title for SAST tests

- package.json
- src/lib/plugins/sast/analysis.ts
- test/fixtures/sast/sample-analyze-folders-response.json
- test/fixtures/sast/sample-sarif.json
This Pr bumps the version of code client to support the new filtering of categories not tags
> chore: update code-client for new security rule filtering

- test/smoke/spec/iac/snyk_test_local_exec_spec.sh
Fixes a broken smoke test that was merged to master after we changed the output format in a separate PR that landed immediately before.
> chore: fix broken IaC smoke test

- test/smoke/spec/iac/snyk_test_directory_spec.sh
- test/smoke/spec/iac/snyk_test_k8s_spec.sh
- test/smoke/spec/iac/snyk_test_local_exec_spec.sh
- test/smoke/spec/iac/snyk_test_terraform_spec.sh
Fixes broken tests in master. These tests were asserting explicit output which fails due to live data being changed.
We are going to have our smoke tests re-thought soon.
> refactor: Fixes iac smoke tests to be less explicit

- package.json
updates code client to the newest version giving alot more issues
> feat: update code-client to for more issues

- package.json
Use latest version of @snyk/fix that support fixing multiple related `pip` requirements.txt files that require other requirements via `-r` directive.
> feat: @snyk/fix supports -r directive

- src/cli/commands/test/iac-local-execution/file-loader.ts
- src/cli/commands/test/iac-local-execution/file-parser.ts
- src/cli/commands/test/iac-local-execution/local-cache.ts
- src/cli/commands/test/iac-local-execution/parsers/terraform-plan-parser.ts
- src/cli/commands/test/iac-local-execution/results-formatter.ts
- test/jest/unit/iac-unit-tests/file-loader.spec.ts
- test/jest/unit/iac-unit-tests/file-parser.spec.ts
- test/jest/unit/iac-unit-tests/file-scanner.spec.ts
A PR that tidies up some of the iac files:
removing unused imports, refactoring according to the eslint json config, inline variables, shorten import paths, etc.
> refactor: General tidying up of iac files

- package.json
Use the latest version of @snyk/fix with constraints.txt support for pinning dependencies for Python.
> feat: @snyk/fix version with constraints support

- package.json
Better naming for umbrella's apps in hex PM
> feat: better naming for umbrella's apps in hex pm

- src/lib/plugins/sast/analysis.ts
This introduces the Proxy env functionality in request.ts to deeproxy requests.
> fix: snyk code respecting HTTPS_PROXY env vars

- src/cli/commands/fix/convert-legacy-test-result-to-new.ts
- test/jest/unit/lib/commands/fix/__snapshots__/convert-legacy-test-result-to-new.spec.ts.snap
- test/jest/unit/lib/commands/fix/__snapshots__/convert-legacy-tests-results-to-fix-entities.spec.ts.snap
- convert legacy `vulnerabilities`  to `IssueData` and `Issues` so they are available in @snyk/fix to display meta about fixed issues, # of issues per severity etc.
> feat(@snyk/fix): send issue data to @snyk/fix for summary

- packages/snyk-fix/package.json
- packages/snyk-fix/src/lib/issues/fixable-issues.ts
- packages/snyk-fix/src/lib/issues/issues-by-severity.ts
- packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
- packages/snyk-fix/src/types.ts
- packages/snyk-fix/test/acceptance/plugins/python/pip-requirements/update-dependencies/__snapshots__/update-dependencies.spec.ts.snap
- packages/snyk-fix/test/acceptance/plugins/python/pip-requirements/update-dependencies/update-dependencies.spec.ts
- packages/snyk-fix/test/helpers/generate-entity-to-fix.ts
- packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
- packages/snyk-fix/test/unit/lib/issues/fixable-issues.spec.ts
- packages/snyk-fix/test/unit/lib/issues/issues-by-severity.spec.ts
- packages/snyk-fix/test/unit/lib/output-formatters/__snapshots__/show-results-summary.spec.ts.snap
- packages/snyk-fix/test/unit/lib/output-formatters/show-results-summary.spec.ts
- Show a summary of total issues + breakdown by severity
- Count how many are fixable via patch or upgrade from
remediation data for now as only projects with remediation data are supported.
Note `Fixed` issues count is coming in a next PR
> feat(@snyk/fix): issues breakdown by severity

- package.json
Bump the version of @snyk/fix package to one that has issue and fixed issue summary
> feat: release @snyk/fix with fix summary data

- package.json
Fix support for homebrew distrubition for hex pm
> fix: hex pm homebrew support

- test/smoke/README.md
Update `test/smoke/README.md` about how to run smoke tests locally.
> Update smoke tests README re running local

- package.json
Latest version of @snyk/fix has some user error messaging improvements and tips to run in debug mode.
> feat: release @snyk/fix error messaging improvements

- help/commands-docs/_ENVIRONMENT.md
Bold the word 'key'
https://snyk.slack.com/archives/C1NREQSG0/p1618868667109100
> docs: bold the word ‘key’

- package.json
See https://github.com/snyk/snyk-nuget-plugin/pull/95
> fix(nuget): invalid "file not found" logging

- package.json
The lockfile verison of node projects is now reported to the cli from the parser.
> feat: lockfile version reported from nodejs parser

- package.json
Updates code-client to the version, which respects --insecure flag
https://github.com/snyk/code-client/pull/78
> fix: enable --insecure in snyk code

- package.json
Update the version of snyk-mvn-plugin to the latest one.
Update the version of snyk-mvn-plugin to the latest one.
As part of propagating arguments to the maven module of the call graph builder.
https://snyksec.atlassian.net/jira/software/projects/FLOW/boards/96?selectedIssue=FLOW-692
> feat: update snyk-mvn-plugin version.

- src/cli/commands/test/iac-local-execution/analytics.ts
- src/cli/commands/test/iac-local-execution/index.ts
- src/cli/commands/test/iac-local-execution/measurable-methods.ts
- src/cli/commands/test/iac-local-execution/types.ts
- src/cli/commands/test/iac-test-shim.ts
Adds performance analytics to the different IAC parts for monitoring:
run the `snyk iac test --experimental` command with `--debug` and see the values.
This will be used in our GA dashboard
https://snyksec.atlassian.net/browse/CC-831
> feat: iac performance analytics [CC-831]

- test/jest/acceptance/cli-args.spec.ts
I've switched from exec to spawn which runs a process directly without a shell (which has platform-specific weirdness) and handles escaping arguments automatically. This should allow Windows support.
To keep the same signature as before, `runCLI` still takes a string rather than an array. The string is split by whitespace to forward to `spawn` as individual arguments (otherwise it's just one big argument). It's a bit naive but works for our current use case. We can have a array input support in the future if needed (e.g. for quoted strings with whitespace).
I've also switched the container test from `ubuntu` to [`hello-world`](https://hub.docker.com/_/hello-world) which is available on Windows too. The fact that there are vulns is irrelevant to the test as the suite is checking for …
> test: support windows in cli args tests

- src/cli/commands/test/iac-local-execution/measurable-methods.ts
Update the typings in the measurable-methods.ts  directory to use generics to determine the argument and return type of the wrapped function. This removes the need to do the casting to `AsyncMeasurableMethod` when passing the function into the wrapper. 
Start with `performanceAnalyticsDecorator()` and `asyncPerformanceAnalyticsDecorator()`. The main awkward bit of TypeScript here is the `Awaited<T>` type which is used to unwrap a `Promise`. We need to use this in the definition for `asyncPerformanceAnalyticsDecorator()` because TypeScript insists on the return value of an async method to be a `Promise<T>`.
```ts
// Should work as the return type:
async (...args: Parameters<T>) => ReturnType<T>
// TypeScript wants the async function to return a Promise so we have to unwrap and re-wrap the …
```
> chore: Use generics to simplify measurable-methods

- help/commands-docs/_SNYK_COMMAND_OPTIONS.md
- src/lib/errors/exclude-flag-invalid-input.ts
- test/jest/acceptance/cli-args.spec.ts
`--exclude` flag works for directories AND files. Changed docs accordingly and added a test.
> docs: —exclude works with files and directories

- package.json
Release latest @snyk/fix version that introduces support for Pipfile & Pipfile.lock fix.
> feat: release snyk fix Pipfile support

- packages/snyk-fix/package.json
- packages/snyk-fix/src/index.ts
- packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
Latest @snyk/fix-pipenv-pipfile package uses child process package instead of the same functionality in the package for code reuse.
No visible changes/effect
> feat: use latest pipfile fix package

- packages/snyk-fix/src/plugins/python/get-handler-type.ts
- packages/snyk-fix/test/unit/plugins/python/handlers/pip-requirements/get-handler-type.spec.ts
Drop unused Pipfile project check.
> chore: drop unused Pipfile check

- packages/snyk-fix/src/plugins/package-tool-supported.ts
- packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/index.ts
- packages/snyk-fix/test/acceptance/plugins/package-tool-supported.spec.ts
Make the tool version & supported check generic to be used across multiple package managers that are used directly for fix purposed.
> feat(@snyk/fix): make tool version check generic

- packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/update-dependencies.spec.ts
Assert that expected fix parameters are being passed down
to the individual fix library. Since the actual calls are mocked it
will help catch any accidental changes.
> test(@snyk/fix): assert expected fix parameters sent

- packages/snyk-fix/src/index.ts
- packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
- packages/snyk-fix/src/types.ts
- packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
Send back meta about number of fixed, failed & total **_issues_** for `snyk fix`
> feat: send back meta on fixed, failed & total issues

- packages/snyk-protect/README.md
> docs: protect readme changes

- packages/snyk-protect/help.txt
- packages/snyk-protect/src/lib/index.ts
- packages/snyk-protect/test/acceptance/protect.spec.ts
- packages/snyk-protect/test/fixtures/help-flag/README.md
- packages/snyk-protect/test/fixtures/help-flag/package.json
- packages/snyk-protect/test/fixtures/version-flag/README.md
- packages/snyk-protect/test/fixtures/version-flag/package.json
Add `--help` flag to `@snyk/protect`.
> feat: add --help to snyk protect

- test/jest/unit/iac-unit-tests/results-formatter.spec.ts
Test is importing from 'dist' rather than 'src'.
> test: fix import path

- packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
- packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
To prepare for introduction of fixing issues 1 by 1, move existing
logic into `fixAll()` so it can be used as a default fix strategy
> refactor: move default upgrade logic into fixAll

- packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
- packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/pipenv-add.ts
Use the new refactored out `pipenvAdd` function and delete no longer needed code.
> fix: use new refactored pipenvAdd

- packages/snyk-fix/src/index.ts
- packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/pipenv-add.ts
- packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/poetry-add.ts
- packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/fails-to-lock/poetry.lock
- packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/fails-to-lock/pyproject.toml
- test stdout for errors too to surface them, sometimes stderr is putting legacy Python warnings and actual error is in stdout
- add more debugging statements
- update a test fixture for better local testing
> feat: test stdout for errors and surface

- package-lock.json
- package.json
This PR just increases a version of dependency @snyk/code-client: https://github.com/snyk/code-client/
Which has an improved retry mechanism for network outages
> fix: updated 'code-client' with improved torelance to network issues

- package-lock.json
- package.json
Updating the snyk-nuget-plugin release version
> feat: update snyk-nuget-plugin release version

- package-lock.json
- package.json
Updating version of snyk nuget plugin on the cli
> feat: update version of snyk nuget plugin

- src/lib/plugins/sast/checks.ts
- src/lib/plugins/sast/validate.ts
- test/jest/unit/snyk-code/snyk-code-test.spec.ts
Throws an error if LCE is enabled, to prevent code upload
> feat: preventing code upload if LCE is on [NEBULA-194]

- src/lib/plugins/sast/checks.ts
- src/lib/plugins/sast/validate.ts
- test/jest/unit/snyk-code/snyk-code-test.spec.ts
This reverts commit 10d9bd981ee7eaf31aad644b30efe011a30b922c.
> Revert "feat: preventing code upload if LCE is on"

- help/commands-md/snyk.md
- src/cli/commands/help/markdown-renderer.ts
> fix: spacing in help command

- .snyk
Not affecting Snyk CLI. No upgrade path currently available. We'll revisit it in a few months
> Ignore SNYK-JS-ANSIREGEX-1583908

- packages/snyk-protect/README.md
- src/cli/commands/test/index.ts
- src/lib/protect-update-notification.ts
- src/lib/theme.ts
- test/fixtures/protect-update-notification/no-package-json/placeholder.txt
- test/fixtures/protect-update-notification/with-package-json-with-snyk-dep-2/package-lock.json
- test/fixtures/protect-update-notification/with-package-json-with-snyk-dep-2/package.json
- test/fixtures/protect-update-notification/with-package-json-with-snyk-dep/package-lock.json
- test/fixtures/protect-update-notification/with-package-json-with-snyk-dep/package.json
- test/fixtures/protect-update-notification/with-package-json-without-snyk-dep/package-lock.json
- test/fixtures/protect-update-notification/with-package-json-without-snyk-dep/package.json
- test/jest/acceptance/snyk-test/protect-upgrade-notification.spec.ts
- test/jest/unit/lib/protect-update-notification.spec.ts
Adds a warning recommending that the user upgrade to the new Snyk protect mechanism if they run `snyk test` and we see a package.json that has the `snyk` package as a dependency.
> snyk protect upgrade notification for test command

- src/cli/commands/test/iac-local-execution/analytics.ts
Adds new analytics for project type counts
> feat: add projct type count analytics

- src/lib/plugins/sast/checks.ts
- src/lib/plugins/sast/validate.ts
- test/jest/unit/snyk-code/snyk-code-test.spec.ts
If LCE settings are on, it throws and error and disable SAST
> feat: preventing code upload if LCE is on

- .circleci/config.yml
> chore(ci): add node@16 to test pipelines

- .github/workflows/smoke-tests.yml
This PR is separate to #2412 as we need the `smoke/` branch name to execute smoke tests in PRs.
> chore(ci): run smoke tests on node 16

- help/cli-commands/snyk-monitor.md
- help/cli-commands/snyk-test.md
Clarify docs to explain how to clear existing tags/attributes on projects.
> docs: update how to clear project tags/attributes

- package.json
This circumvents log4j vulnerability.
> fix: Upgrade maven plugin.

- src/cli/commands/test/index.ts
- src/lib/spotlight-vuln-notification.ts
- test/fixtures/mvn-log4j-fixture/pom.xml
- test/fixtures/mvn-log4j-fixture/test-dep-graph-response.json
- test/jest/acceptance/snyk-test/spotlight-vuln-notification.spec.ts
- test/jest/unit/lib/spotlight-vuln-notification.spec.ts
Displays a special notification when SNYK-JAVA-ORGAPACHELOGGINGLOG4J-2314720 (Log4j) is found.
> Special notification to spotlight log4j critical vulns

- package-lock.json
- package.json
This PR adds an alias --nested-jars-depth in addition to --shaded-jars-depth
> feat: add alias --nested-jars-depth

- package-lock.json
- package.json
instead of 0
this also applies to --app-vulns with no --nested-jars-depth flag
> feat: change default of nested jars unpacking to 1

- package-lock.json
- package.json
> fix: rename loaded packages fact

- src/lib/plugins/sast/analysis.ts
- src/lib/plugins/sast/checks.ts
- src/lib/plugins/sast/errors/index.ts
- src/lib/plugins/sast/errors/missing-configuration-error.ts
- src/lib/plugins/sast/format/output-format.ts
- src/lib/plugins/sast/index.ts
- src/lib/plugins/sast/settings.ts
- src/lib/plugins/sast/types.ts
- test/jest/unit/snyk-code/snyk-code-test.spec.ts
Adding support for local code engine
> [NEBULA-276] feat: add local code engine support

- package-lock.json
- package.json
This fixes upgrades the version of snyk-nuget-plugin in order to release a bug fix. For more information, see https://github.com/snyk/snyk-nuget-plugin/pull/113
> fix: update snyk-nuget-plugin version

- package-lock.json
- package.json
- src/lib/plugins/sast/analysis.ts
- test/jest/unit/snyk-code/snyk-code-test.spec.ts
Adds analysis context for SAST analysis request.
See here: https://snyksec.atlassian.net/browse/PUL-327 for feature reference.
Also related: snyk/code-client#118
> feat: add analysisContext to SAST analysis

- src/cli/commands/test/iac-local-execution/file-loader.ts
- Updates the `getFilePathsFromDirectory` function to return only IaC file paths.
- `src/cli/commands/test/iac-local-execution/file-loader.ts`
- This PR hosts a simplified implementation for [this previous PR](https://github.com/snyk/snyk/pull/2442).
- Currently in the `test` flow for IaC, when loading IaC files from the provided directory, we do so in the following steps:
1. Fetch **all** file paths (IaC and non-IaC) inside the directory.
2. Load all files:
ii.a If IaC file - Return the loaded file's data.
ii.b If not IaC file - Return `null`.
3. Filter out files with `null` as their loaded data.
4. Return the remaining files' data.
This PR's implementation offers the following alternative flow:
1. Fetch **only** IaC file paths inside the directory.
2. Load these IaC files.
3. Return the …
> refactor: Load IaC files flow

- package-lock.json
- package.json
This PR bumps the version of snyk-docker-plugin to v4.33.0
which adds support for private JARs
> feat: Adding support for private JARs

- src/lib/formatters/test/format-test-results.ts
- test/jest/unit/lib/formatters/test/__snapshots__/display-result.spec.ts.snap
- test/jest/unit/lib/formatters/test/display-result.spec.ts
remove the pro tip for the base image remediation
https://snyksec.atlassian.net/browse/CAP-443
> fix: remove pro tip for base image remediation

- help/cli-commands/README.md
> Hide wizard and protect from main help

- src/lib/analytics/getStandardData.ts
- test/jest/unit/lib/analytics/getStandardData.spec.ts
We'd like to know adoption of various architectures to ensure we're providing adequate support for customers. It's also useful for debugging.
> feat: include os architecture in analytics

- README.md
[JIRA ticket](https://snyksec.atlassian.net/browse/HMMR-487)
[Slack thread](https://snyk.slack.com/archives/C0127HWU0E7/p1640179843480800)
Reorder `readme.md` "Supported languages and tools" section to make docs more visible for users.
> docs: reorder readme for better visibility of docs

- src/lib/formatters/test/format-test-results.ts
- test/acceptance/workspaces/fail-on/docker/fixable/vulns-with-docker-remediation.json
- test/jest/unit/lib/formatters/test/__snapshots__/display-result.spec.ts.snap
- test/jest/unit/lib/formatters/test/display-result.spec.ts
To try to minimize the questions to support regarding how we give remediation advice, we add a link to the documentation page explaining it.
Run `snyk container test ...`
> feat: add link to docs for base image remediation

- package-lock.json
- package.json
This patch bumps the SBT plugin versin to pick up the new, improved behaviour for SBT deps discovery.
https://github.com/snyk/snyk-sbt-plugin/pull/103
> feat: pick up SBT plugin with improved logic

- .github/CODEOWNERS
For log4shell command ownership
> chore: update codeowners with @snyk/tundra

- help/cli-commands/ignore.md
> docs: update ignore command help

- help/cli-commands/policy.md
> docs: update policy command help

- help/cli-commands/auth.md
The file has all revisions through January 3, 2022, for review by the Hammer team.
> docs: update auth command help

- help/cli-commands/log4shell.md
> docs: update log4shell command help

- help/cli-commands/monitor.md
> docs: update monitor command help

- help/cli-commands/config.md
> docs: update config command help

- help/cli-commands/iac.md
- test/smoke/spec/snyk_basic_spec.sh
This file has all revisions through January 3, 2022, for review by the Hammer team. Question: For commands with the sub-command test, should the test command be explained the same as as the snyk test command: test a project for open source vulnerabilities and license issues? At this time, the code and iac commands say: test for any known issue. The container command says: test for any known vulnerabilities.
> docs: update iac command help

- help/cli-commands/test.md
This PR has all the changes to date (Dec. 14) for the test command. Please read from beginning to end and especially review the questions posted in the private Hammer Slack channel.
> Updates to test command help

- help/cli-commands/wizard.md
docs: update the wizard command help
This update aligns the wizard command help with the other help files we have been working on.
> docs: update wizard.md

- .github/CODEOWNERS
> Team Tardis own reachability

- src/lib/errors/no-supported-sast-files-found.ts
Updates docs link for Snyk code language support.
> fix: update docs for snyk code language support.

- src/lib/errors/invalid-iac-file.ts
Updates docs link for Snyk IaC support.
> fix: Update broken doc support links for IaC

- src/lib/plugins/sast/analysis.ts
- test/jest/unit/snyk-code/snyk-code-test.spec.ts
https://snyksec.atlassian.net/browse/NEBULA-299
> style: links to docs when throwing an error  [NEBULA-299]

- src/lib/plugins/sast/settings.ts
- test/jest/unit/snyk-code/snyk-code-test.spec.ts
https://snyksec.atlassian.net/browse/NEBULA-330
> feat: allowing CLI usage if LCE is enabled [NEBULA-330]

- .circleci/chocolatey.config
- .circleci/config.yml
Ensure we use the same AWS version for every job to avoid any weird differences.
> chore(ci): use same aws version

- package.json
> chore: fix 'npm test' script

- test/jest/unit/snyk-code/snyk-code-test.spec.ts
Added a unit test as per https://snyksec.atlassian.net/browse/NEBULA-303
> test: added a unit test to validate LCE url is baseURL [NEBULA-303]

- release-scripts/hcl-to-json-parser-generator/README.md
Add .md extension for readability
> chore: Update Readme extension to read markdown

- package-lock.json
- package.json
- implement archive extraction supporting zip & tar formats (including gzip compression)
- fix casing for the package IDs in the vulnerabilities list
- fix json payloads used for json file serialization
- bump the cpp-plugin's version to reflect the above
> feat: archive extraction for the unmanaged flows

- src/lib/formatters/test/format-test-results.ts
This PR fixes an OOM issue caused by group-issues.
Group issues mechanism was extending the "from" and "name" arrays in the current vuln it was iterating on, and only then assigning it to acc[vuln.id]. This meant that needs to be grouped, an array larger by 1 (of "from" and of "name") is added to the vuln. In large vulns results this may cause may OOM issues, because of duplicate data.
This fix changes the the mechanism so that when acc[vuln.id] exists, it add the current vuln's 'from' and 'name' values to the existing acc[vuln.id].from and name arrays.
**Please note**: In order to keep the "from" and "name" arrays order as it was before, and in order to use the last vuln's data (e.g. upgradePath) in the output, we need to iterate over the reversed array. We then reverse the order back, …
> perf: Fix OOM issue caused by group-issues

- package.json
- src/lib/plugins/sast/analysis.ts
- src/lib/plugins/sast/index.ts
- test/jest/unit/snyk-code/snyk-code-test.spec.ts
https://snyksec.atlassian.net/browse/NEBULA-339
Ignore the request ID difference in one of the screenshots 🙃
> feat: observability in snyk code [NEBULA-399]

- package-lock.json
- package.json
- src/lib/plugins/sast/index.ts
> fix: bumped up code-client feater

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- dangerfile.js
To match changes in #2742.
Also updated some links and Danger rules to match.
> docs: explain new release pipeline

- .github/CODEOWNERS
- help/cli-commands/iac-drift-scan.md
- help/cli-commands/iac-drift.md
Builds on the more flexible help system introduced in
https://github.com/snyk/snyk/pull/2778.
Help copied from https://github.com/snyk/snyk/pull/2735. This is an
alternative to that.
Make IaC codeowners of their own help pages.
> [CFG-1484] feat: add help page for iac-drift-scan

- package-lock.json
- package.json
- src/lib/ecosystems/test.ts
- src/lib/types.ts
- remove the vulndb feature flag for the unmanaged flows
- bump the cpp plugin version
> feat: remove vulndb ff for unmanaged

- release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/go.mod
- release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/go.sum
Includes the fix in https://github.com/snyk/snyk-iac-parsers/pull/15 for the pipeline: https://app.circleci.com/pipelines/github/snyk/snyk/10178/workflows/e88f0cbb-5c37-4263-8b2c-aa33cc413fbd/jobs/78906
The only way to test it is to build the CLI in a Windows OS, which we already did. See screenshot for prood.
> fix: tfvars path windows

- .github/CODEOWNERS
- help/cli-commands/iac-describe.md
- help/cli-commands/iac-drift.md
- src/cli/commands/describe.ts
- src/cli/commands/index.js
- src/cli/modes.ts
- src/lib/iac/drift.ts
- src/lib/types.ts
- test/jest/acceptance/iac/describe.spec.ts
- test/jest/acceptance/iac/dift.spec.ts
- test/jest/unit/cli/commands/help/help.spec.ts
- test/jest/unit/lib/iac/drift.spec.ts
That PR just simply rename `iac drift scan` to `iac describe`
`src/cli/commands/describe.ts`
`$ snyk iac describe`
https://snyksec.atlassian.net/browse/CFG-1625
> chore: renamed `iac drift scan` to `iac describe`

- help/cli-commands/iac-describe.md
Just reflect this [new feature](https://github.com/snyk/driftctl-docs/pull/222) in snyk doc
https://snyksec.atlassian.net/browse/CFG-1442
> Add azure blob storage drift source
