.circleci/config.yml
The "default" setup we're using prevents us from defining jobs with custom parameters. We can use pipeline parameters as global defaults instead. We can also use executors to reduce boilerplate and provide pre-configured default environments for every job.
=> chore(ci): configure pipeline params and executors

src/lib/analytics/index.ts, test/jest/unit/lib/analytics/index.spec.ts
Today a user can test multiple files/directories by using the command snyk iac test {path1} {path2}.
When doing so we are saving the `iac-type` and `iac-metric` analytics incorrectly, for example:
```
"iac-type": [
{
"cloudformationconfig": {
"count": 1,
"low": 1,
"medium": 9
}
},
{
"terraformconfig": {
"count": 1,
"medium": 15,
"high": 10,
"low": 20
}
},
{
"terraformconfig": {
"count": 1,
"low": 5
},
"cloudformationconfig": {
"count": 1,
"low": 2,
"medium": 1
}
}
],
```
We should save it as a single object that aggregates the values of all the items in the array.
Run a test with multiple args and use the -d flag to check the metadata field at the bottom.
This PR is a continuation of the work done in https://github.com/snyk/snyk/pull/2620.
https://snyksec.atlassian.net/browse/CFG-1446 …
=> fix: IaC analytics

package-lock.json, package.json
Align the exit codes of the `snyk unmanaged test` command to mirror the other ecosystems.
Currently, the supported exit codes for the unmanaged flows are:
&nbsp;&nbsp;&nbsp;&nbsp; 0: success, no vulns found
&nbsp;&nbsp;&nbsp;&nbsp; 1: action_needed, vulns found
&nbsp;&nbsp;&nbsp;&nbsp;  2: failure, try to re-run command
&nbsp;&nbsp;&nbsp;&nbsp;  3: failure, no supported projects detected
The above logic is available in the updated version of the c++ plugin.
This is just a version bump for the c++ plugin.
=> fix: proper exit codes for the unmanaged flows

.github/CODEOWNERS
This assigns @snyk/nebula as code owner for all Snyk Code related files.
=> chore: make team nebula (sub-team of sast-team) codeowner for snyk code parts of snyk CLI

help/cli-commands/ignore.md, src/cli/commands/ignore.ts, src/cli/commands/types.ts, test/jest/acceptance/snyk-ignore/snyk-ignore.spec.ts, test/jest/util/runSnykCLI.ts
- Adds a new optional argument called `path` to the `snyk ignore` command, which allows users to specify the resource path for the generated ignore rule.
`src/cli/commands/ignore.ts`
Use the `snyk ignore` command and provide the desired resource path using the `--path` flag.
As part of [Allow CLI `ignore` command to receive path for IaC ](https://snyksec.atlassian.net/browse/CFG-1489), we'd like to provide a way to specify a specific resource path for the ignore rules to help with the functionality that the IDE provides. 
- [CFG-1489](https://snyksec.atlassian.net/browse/CFG-1489) 
- [ROAD-628](https://snyksec.atlassian.net/browse/ROAD-628)
=> Feat: Add path argument for ignore [CFG-1489]

help/cli-commands/code.md, src/lib/ecosystems/test.ts, src/lib/ecosystems/types.ts, src/lib/plugins/sast/index.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts
This PR adds support to the `--sarif-file-output` flag in `snyk code test`.
The commands `snyk test` and `snyk iac test` support this flag, while `snyk code test` only supports `--sarif` but not writing to a file directly.
Run `snyk code test --sarif-file-output` in a repository to generate a file with the sarif result. This can be used simultaneously with other flags like `--sarif` and `--no-markdown`.
- [Jira ticket NEBULA-157](https://snyksec.atlassian.net/browse/NEBULA-157)
- [Zendesk ticket 15314](https://snyk.zendesk.com/agent/tickets/15314)
- [Zendesk ticket 15028](https://snyk.zendesk.com/agent/tickets/15028)
=> feat: added option --sarif-file-output for snyk code test [NEBULA-157]

package-lock.json, package.json
Bumping our SBT plugin to pick up new additional warning we've added to inform users regarding the new 
sbt-dependency-graph annotation.
See https://github.com/snyk/snyk-sbt-plugin/pull/104
=> feat: bump snyk sbt plugin for warning on sbt-dep-graph plugin

src/lib/plugins/sast/index.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts
When code-client was throwing an error, regardless what type of error, users were seeing this:
```
Unauthorized: Failed to run 'code test'
```
With this PR when running with `-d`, users will see:
=> fix: remove 'unauthorized' msg for non 403/1 stautscodes [COD-634] [NEBULA-334]

.github/CODEOWNERS, .github/workflows/sync-cli-help-to-user-docs.yml, help/README.md, src/cli/commands/help/markdown-renderer.ts, src/cli/commands/help/reflow-text.ts
Automatic action to sync CLI Help from snyk/user-docs repository
Example of such automatic PR: https://github.com/snyk/snyk/pull/2592 (also updated the renderer to handle the non-XHTML newline break `<br />` vs. `<br>`)
This update handles line breaks better:
=> GH Action for syncing help files

dangerfile.js
Related to https://github.com/snyk/snyk/pull/2591
Warn when changes to help files are made in the `snyk/snyk` repo instead of in the `snyk/user-docs` repo.
=> chore: add warning for help files changes

src/lib/iac/drift.ts, test/acceptance/fake-server.ts, test/jest/acceptance/iac/dift.spec.ts
Fix acceptance test for `snyk iac drift` on windows.
Test was using `/tmp` and custom concatenated path so it could not work.
But the test also run a bash script that echos it's own args. As I'm not sure how to handle this I disabled the test on windows to restore or ability to run acceptance tests.
=> fix acceptance test for `snyk iac drift` on windows

src/cli/args.ts, src/lib/plugins/sast/index.ts
`debugLib.enable` was overriding the debug namespaces defined by the CLI.
https://github.com/snyk/snyk/blob/49b07498ed5c95d8cbb0841553e4b5eab616b360/src/cli/args.ts#L111-L121
This silenced debug output _after_ the SAST plugin.
Since this is a command specific _and_ global behavior, it's somewhat tricky to test properly. Debug module might need some more love.
Follow up to https://github.com/snyk/snyk/pull/2692
=> fix: don't override debug namespace

.circleci/vendor/sdkman-install.sh
Attempt to fix [pipelines failing](https://snyk.slack.com/archives/C0127HWU0E7/p1644921029594519) due to SDKMAN prompting to be updated.
=> chore: dont check for new versions of sdkman

.eslintignore, .prettierignore, release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/go.mod, release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/go.sum, release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/sg_open_ssh_defaults.tf, release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/test.js, src/cli/commands/test/iac-local-execution/file-loader.ts, src/cli/commands/test/iac-local-execution/file-parser.ts, src/cli/commands/test/iac-local-execution/index.ts, src/cli/commands/test/iac-local-execution/parsers/hcl-to-json-v2/index.ts, src/cli/commands/test/iac-local-execution/types.ts, test/acceptance/fake-server.ts, test/fixtures/iac/terraform/var_deref/nested_var_deref/sg_open_ssh.tf, test/fixtures/iac/terraform/var_deref/nested_var_deref/variables.tf, test/fixtures/iac/terraform/var_deref/sg_open_ss.tf, test/fixtures/iac/terraform/var_deref/variables.tf, test/jest/acceptance/iac/test-directory.spec.ts, test/jest/acceptance/iac/test-terraform-var-deref.spec.ts, test/jest/unit/iac/file-parser.spec.ts, test/jest/unit/iac/file-parser.terraform.fixtures.ts, test/jest/unit/iac/index.spec.ts
This PR introduces a new parsing flow for Terraform files, which supports dereferencing variables. This flow is behind the `iacTerraformVarSupport` feature flag and currently only supports scanning Terraform files in the current directory.
Scanning nested directories is out of scope for this PR.
The changes are split in commits:
1. the changes in `release-scripts]/` are to update the version of the `snyk/snyk-iac-parsers` library to the latest, https://github.com/snyk/snyk-iac-parsers/releases/tag/v0.2.0
2. the acceptance tests verify backwards compatibility, optional flag support, and dereferencing
3. the `parseTerraformFiles` function will take in the Terraform files, send them to the `snyk-iac-parsers` library, and modify them into the desired output
4. the main flow is split into two …
=> feat: TF Language Support - dereference variables in CWD while parsing [CFG-1496]

test/jest/acceptance/iac/test-terraform-plan.spec.ts
This test started failing because it finds less issues. I think it must be related to https://github.com/snyk/cloud-config-opa-policies/pull/720 but it's hard to tell.
See the test failure [here](https://app.circleci.com/pipelines/github/snyk/snyk/10037/workflows/6ad6d181-4509-4b4a-aeac-01306e874151/jobs/77740)
=> test: fix terraform plan tests

package-lock.json, package.json
Updates the CPP-plugin to version [v2.16.5](https://github.com/snyk/snyk-cpp-plugin/releases/tag/v2.16.5), to include following fixes:
- Add support for larger projects to prevent recursion problems
- Adds support for dependencies with omitted version number:
- Use dependency ID with empty string as version.
- Use "unknown" in the standard output, if version has been omitted.
Use `snyk unmanaged test` to verify that some specific projects now works without failures due to number of files.
=> fix: support C++-dependencies with unknown version

help/cli-commands/iac-drift.md, src/cli/args.ts, src/cli/commands/help/index.ts, test/jest/unit/cli/commands/help/help.spec.ts
Follow up to #2735
Refactored the `snyk help` command to allow documenting subcommands like `snyk iac drift`
=> Allow documenting sub-commands in --help

.github/CODEOWNERS, src/lib/iac/drift.ts, test/jest/acceptance/iac/dift.spec.ts, test/jest/unit/lib/iac/drift.spec.ts
This PR is a follow-up of #2634 and add a new subcommand `gen-driftignore` based on 
Everything is in `src/lib/iac/drift.ts`
You can use the following file as input
`snyk iac drift gen-driftignore --input=driftctl.json --output=/dev/stdout`
```json
{
"summary": {
"total_resources": 2,
"total_changed": 0,
"total_unmanaged": 2,
"total_missing": 0,
"total_managed": 0
},
"managed": null,
"unmanaged": [
{
"id": "AKIA5QYBVVD26LL6K7LW",
"type": "aws_iam_access_key"
},
{
"id": "AKIA5QYBVVD2RGR7VCH4",
"type": "aws_iam_access_key"
}
],
"differences": null,
"coverage": 0,
"alerts": {},
"provider_name": "aws",
"provider_version": "3.19.0"
}
```
https://docs.driftctl.com/0.20.0/usage/cmd/gen-driftignore-usage
https://snyksec.atlassian.net/browse/CFG-1300
=> [CFG-1300] add `iac drift gen-driftignore` command

release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/go.mod, release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/go.sum, src/cli/commands/test/iac-local-execution/index.ts, src/cli/commands/test/iac-local-execution/types.ts, test/fixtures/iac/terraform/var_deref/a.auto.tfvars, test/fixtures/iac/terraform/var_deref/b.auto.tfvars, test/fixtures/iac/terraform/var_deref/sg_open_ssh.tf, test/fixtures/iac/terraform/var_deref/terraform.tfvars, test/fixtures/iac/terraform/var_deref/variables.tf, test/jest/acceptance/iac/test-directory.spec.ts, test/jest/acceptance/iac/test-terraform-var-deref.spec.ts, test/jest/unit/iac/file-parser.terraform.fixtures.ts
This PR enables support for dereferencing variables defined in`terraform.tfvars` and `*.auto.tfvars` . It does not aim to support `terraform.tfvars.json` and `*.auto.tfvars.json` files, or files provided via the `-var` and `-var-file`flags. Tfvars files are explained [here](https://www.terraform.io/language/values/variables#variable-definitions-tfvars-files).
It requires https://github.com/snyk/snyk-iac-parsers/pull/12 to be merged first in order to generate a new release of the parser.
There are only two code changes required in `src/cli/commands/test/iac-local-execution/index.ts`, to start reading `.tfvars` files. The rest of the changes in this PR are tests, making sure we are able to read and dereference variables from both `terraform.tfvars` and `*.auto.tfvars` files, with the right …
=> feat: dereference variables from terraform.tfvars and *.auto.tfvars [CFG-1502]

release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/go.mod, release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/go.sum, src/cli/commands/test/iac-local-execution/file-parser.ts, src/cli/commands/test/iac-local-execution/parsers/hcl-to-json-v2/index.ts
This PR adds debug logs, which show up when the command is run with a `--debug` option. This will help customers debug why their files fail.
Needs https://github.com/snyk/snyk-iac-parsers/pull/10 first so we can update the version of `snyk/snyk-iac-parsers` and generate a new release.
2. Run `snyk iac test ./test/fixtures/iac/terraform/sg_open_ssh_invalid_hcl2.tf -d` and see no debug logs
3. Enable the `iacTerraformVarSupport` feature flag
4. Run `snyk iac test ./test/fixtures/iac/terraform/sg_open_ssh_invalid_hcl2.tf -d` and see no debug logs (see screenshots)
5. Run `snyk-dev iac test ./test/fixtures/iac/terraform/sg_open_ssh_invalid_hcl2.tf -d` and see the new debug logs (see screenshots)
[CFG-1582](https://snyksec.atlassian.net/browse/CFG-1582)
- before
- after
=> feat: add debug logs for tf vars [CFG-1582]

src/lib/plugins/sast/index.ts, src/lib/plugins/sast/types.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts
When running `snyk code test`, the organization would appear as `undefined`.
This was solved by passing the `org` from the `SastSettings` API endpoint (which is the default `org` when not specified by the flag or config) and displaying it in the CLI.
Check the [PR](https://github.com/snyk/registry/pull/26282) on the registry side as well for the API changes.
Run `snyk code test` in a repository and check the printed `Organization` line. It should not be undefined.
Notes:
- Undefined organizations will assume the default organization.
- Specify an `org` by using the flag `--org=org.name` or by setting the `org` in the config by running `snyk config set org=org.name`
- Check if an org is in the config by running `snyk config get org`
- To remove an assigned org in the config, run `snyk …
=> feat: add org name to snyk code test [NEBULA-195]

packages/snyk-fix/src/types.ts, src/cli/commands/test/iac-local-execution/assert-iac-options-flag.ts, src/cli/commands/test/iac-local-execution/file-utils.ts, src/cli/commands/test/iac-local-execution/index.ts, src/cli/commands/test/iac-local-execution/results-formatter.ts, src/cli/commands/test/iac-local-execution/share-results-formatter.ts, src/cli/commands/test/iac-local-execution/share-results.ts, src/cli/commands/test/iac-local-execution/types.ts, src/cli/commands/test/index.ts, src/lib/ecosystems/types.ts, src/lib/iac/cli-share-results.ts, src/lib/iac/envelope-formatters.ts, src/lib/polling/types.ts, src/lib/types.ts, test/acceptance/fake-server.ts, test/jest/acceptance/iac/cli-share-results.spec.ts, test/jest/acceptance/iac/helpers.ts, test/jest/unit/iac/cli-share-results.fixtures.ts, test/jest/unit/iac/cli-share-results.spec.ts, test/jest/unit/iac/results-formatter.fixtures.ts, test/jest/unit/iac/results-formatter.spec.ts, test/jest/unit/iac/share-results-formatters.fixtures.ts, test/jest/unit/iac/share-results-formatters.spec.ts
This PR adds the ability to send IaC scan results to the Snyk platform (or in other words, IaC's implementation of the `monitor` feature).
The new feature is enabled by adding the flag `--report` to the currently available `snyk iac test` command.
https://github.com/snyk/snyk/pull/2702/files#diff-3c191734c1a12b3652b05f2a05c377ec9ccf30a5510e8b668c104b1c8349e19aR80
1. Locally run the following registry [branch](https://github.com/snyk/registry/pull/26028).
2. Enable the FF named `iacCliShareResults`
3. In the CLI test any IaC file / directory with the command `snyk-dev iac test {path_to_the_file} --report`
4. Check that the projects were created successfully in the Snyk platform.
[Feature plan
](https://www.notion.so/snyk/Share-test-results-from-IaC-CLI-6e8287fcc7534a4f8d628d1f8f4187ba) …
=> feat: IaC CLI Share Results [CFG-1532]

src/cli/commands/test/iac-local-execution/parsers/terraform-plan-parser.ts, src/cli/commands/test/iac-local-execution/types.ts, test/fixtures/iac/terraform-plan/expected-parser-results/delta-scan/tf-plan-create.resources.json, test/fixtures/iac/terraform-plan/expected-parser-results/delta-scan/tf-plan-v4.resources.json, test/fixtures/iac/terraform-plan/expected-parser-results/full-scan/tf-plan-create.resources.json, test/fixtures/iac/terraform-plan/expected-parser-results/full-scan/tf-plan-v4.resources.json, test/fixtures/iac/terraform-plan/tf-plan-v4.json, test/jest/acceptance/iac/test-directory.spec.ts, test/jest/unit/iac/terraform-plan-parser.fixtures.ts, test/jest/unit/iac/terraform-plan-parser.spec.ts
This PR introduces single depth reference resolution in terraform plan parsing. It is the TypeScript equivalent of https://github.com/snyk/snyk-iac-parsers/pull/8. In the future it might be better to use `gopherjs` to include the Terraform Plan parsing in the CLI, like we already do for Terraform Variable Dereferencing. However that requires a bit more work so for now this quick re-implementation of the logic in TypeScript will have to do.
Review commit by commit:
- The first commit includes a new Terraform Plan output from the Terraform v4 provider. 
- The second commit includes the change in code to include references to resources in the parsed Terraform Plan. The same files as in were changed, but the No Op one already contained `"service_role": …
=> feat: resolve single depth references [CFG-1623]

src/lib/iac/drift.ts
Update Driftctl version to v0.21.0
Driftctl version and corresponding [checksums](https://github.com/snyk/driftctl/releases/download/v0.21.0/driftctl_SHA256SUMS) are updated. 
Running `snyk iac drift scan` should trigger a download of the new binary.
=> chore: Update Driftctl version to v0.21.0

help/cli-commands/iac-describe.md, src/lib/iac/drift.ts, test/jest/unit/lib/iac/drift.spec.ts
driftctl support variadic --from to input multiple state source. We decided to go with coma separated value in snyk cli in order to not change too much how the arg parsing is working.
https://github.com/snyk/snyk/pull/2812
=> [CFG-1510] allow multiple from params to snyk iac drift

help/cli-commands/iac-describe.md, src/cli/commands/drift.ts, src/lib/iac/drift.ts, test/jest/unit/lib/iac/drift.spec.ts
This PR make sure that driftctl return code are translated into snyk cli idiomatic codes. 
https://snyksec.atlassian.net/jira/software/c/projects/CFG/boards/328?modal=detail&selectedIssue=CFG-1600
=> [CFG-1600] adapt `iac drift` exits codes to snyk cli

src/lib/errors/policy-not-found-error.ts
Don't recommend running `snyk wizard` when a policy file cannot be found.
=> refactor: don’t recommend running snyk wizard

src/lib/iac/drift.ts, test/jest/unit/lib/iac/drift.spec.ts
We just release version v0.22 of driftctl with 2 new flags `--only-managed` and `--only-unmanaged`. This PR bump the version of driftctl and add both flags to the list of our compatible flags.
```bash
$ snyk iac drift scan --from=tfstate://../driftctl/terraform.tfstate --only-managed
Found missing resources:
- vol-1234567890 (aws_ebs_volume)
From tfstate://terraform.tfstate
- i-1234567890 (aws_instance.bar)
Found changed resources:
From tfstate://terraform.tfstate
- i-0987654321 (aws_instance.foo):
~ instance_type: "t2.nano" => "t2.micro"
Found 4 resource(s)
- 50% coverage
- 2 resource(s) managed by Terraform
- 1/2 resource(s) out of sync with Terraform state
- 2 resource(s) found in a Terraform state but missing on the cloud provider
$ snyk iac drift scan …
```
=> [CFG-1591] --only-managed / --only-unmanaged for drifts

src/cli/commands/test/iac-local-execution/file-loader.ts, src/cli/commands/test/iac-local-execution/handle-terraform-files-utils.ts, src/cli/commands/test/iac-local-execution/handle-terraform-files.ts, src/cli/commands/test/iac-local-execution/index.ts, src/cli/commands/test/iac-local-execution/types.ts, src/lib/iac/iac-parser.ts, test/jest/acceptance/iac/test-terraform-var-deref.spec.ts, test/jest/unit/iac/file-parser.spec.ts, test/jest/unit/iac/handle-terraform-files-utils.spec.ts, test/jest/unit/iac/handle-terraform-files.spec.ts, test/jest/unit/iac/index.spec.ts
This PR introduces TF variable dereferencing support in nested directories. Imagine this project structure:
```
.
├── arm-test.tf
├── dev
│   └── my-local-module
│       ├── terraform.tfvars
│       └── test-file.tf
├── file-with-input-var.tf
├── pre-prod
│   └── my-local-module
│       ├── terraform.tfvars
│       └── test-file.tf
├── prod
│   └── my-local-module
│       ├── terraform.tfvars
│       └── test-file.tf
├── empty-directory
├── staging
│   └── my-local-module
│       ├── terraform.tfvars
│       └── test-file.tf
├── terraform.tfvars
└── test-file.tf
└── empty-file.tf
9 directories, 13 files
```
We have several directories and files. So far, we supported running a scan and dereferencing variables only on the current working directory. This PR extends it to nested directories …
=> feat: Add TF Variable support for nested directories [CFG-1483]

src/lib/iac/drift.ts, test/jest/acceptance/iac/describe.spec.ts, test/jest/acceptance/iac/gen-driftignore.spec.ts, test/jest/unit/lib/iac/drift.spec.ts
Driftctl update checking should be turned off when running driftctl from Snyk CLI. This PR adds `--no-version-check` option to driftctl by default so it doesn't perform this check anymore. This is a global flag in driftctl so I added it for both scan and gen-driftignore commands.
```
$ SNYK_API=http://localhost:8000/api/v1 ./bin/snyk iac describe --service=aws_s3
```
- https://snyksec.atlassian.net/browse/CFG-1639
- https://docs.driftctl.com/0.22.0/usage/flags/version-check
=> [CFG-1639] Add default --no-version-check flag to driftctl

package-lock.json, package.json, test/tap/cli-monitor.acceptance.test.ts
Snyk CLI treats each project (pom.xml) file as a project. Previously we have been including aggregate (modules) projects underneath the root project. Now (using '--all-projects') Snyk scans all maven projects at once and creates Snyk projects for each and there is no need to nest aggregate projects under the root.
See https://github.com/snyk/snyk-mvn-plugin/pull/114
=> fix: maven root project scan exclude aggregate projects

package-lock.json, package.json, src/lib/plugins/sast/analysis.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts
The change propagates org name returned from `sast-settings`. This will be
either a default org or org provided in the CLI options (and verified to
exist)
-
-
We want to add more observability into our `snyk code test` flow. This will allow us to see what are specific orgs experiencing when using the command. 
-
-
-
=> feat: propagate org name

release-scripts/hcl-to-json-parser-generator-v2/Makefile, release-scripts/hcl-to-json-parser-generator-v2/test-and-release.sh
This PR fixes the release process for new versions of `snyk-iac-parsers`.
There were a couple problems:
- the `version` argument was required by `make test` unnecessarily
- the `make release version=...` script was failing randomly
=> chore: fix issues with release process of snyk-iac-parsers

src/cli/commands/test/iac-local-execution/handle-terraform-files.ts, test/jest/acceptance/iac/test-terraform-var-deref.spec.ts, test/jest/unit/iac/handle-terraform-files.spec.ts
This commit fixes the issue introduced on a previous PR where a single file scan of a non-Terraform file (.tf, .tfvars) would fail as a non-valid IaC file.
This is because we didn't ignore the error when the file has already successfully been parsed in the file take of the parsing.
We will now ignore the error and continue with the scan.
I also added regression tests that will check each one of the other supported fileTypes for a single file scan with the FF on.
They are duplicate but can be removed when we remove the FF.
Thread: https://snyk.slack.com/archives/C030WL9BLSW/p1646759529069249
=> fix: Single files scans of non-tf files behind FF

src/cli/commands/test/iac-local-execution/handle-terraform-files.ts, test/jest/acceptance/iac/test-terraform-var-deref.spec.ts, test/jest/unit/iac/handle-terraform-files.spec.ts
This reverts commit 473abef6c3f22e6b665c6e104340bbda9152c91d that looks to break tests in master.
All tests have passed [there](https://github.com/snyk/cli/pull/2848/checks?check_run_id=5486360429) and I can't replicate locally, so I'm reverting the commit to clear the pipeline.
=> Revert "fix: Single files scans of non-tf files behind FF"

package-lock.json, package.json
Previously the plugin used "=>" whereas pep508 specifies ">=" as the ge operator.
=> fix: upgrade snyk-python-plugin

src/cli/commands/test/iac-local-execution/handle-terraform-files.ts, test/jest/acceptance/iac/test-terraform-var-deref.spec.ts, test/jest/unit/iac/handle-terraform-files.spec.ts
This commit fixes the issue where we scanned single non-tf files and they failed when using the new flow (behind FF). This is because we were throwing an (non-iac-file) error early in the flow, without checking if files have already been parsed or not.
This is a quick fix for the bug, refactoring to follow.
I also added regression tests that will check each one of the other supported fileTypes for a single file scan with the FF on.
They are duplicate but can be removed when we remove the FF.
This is an "almost" duplicate of https://github.com/snyk/cli/pull/2848#event-6212805181 which I had to revert due to failing tests on master.
Non-TF single file
TF single file
=> fix: non-tf single files scan successfully in new flow

src/cli/commands/test/iac-local-execution/index.ts, src/cli/commands/test/iac-local-execution/measurable-methods.ts
Adds the loadAndParseTerraformFiles to the measurable methods file so that we can track metrics and see them in the `Total`  analytics.
Question for the reviewer:
I haven't added it to its own analytics key yet - it might need to change depending the refactoring on that function so I'm leaving it to the total for now.
=> chore: Measure loadAndParseTerraformFiles function

src/cli/commands/test/iac-local-execution/index.ts, src/cli/commands/test/iac-local-execution/share-results.ts, src/lib/iac/cli-share-results.ts, src/lib/iac/envelope-formatters.ts, test/jest/unit/iac/cli-share-results.fixtures.ts, test/jest/unit/iac/cli-share-results.spec.ts, test/jest/unit/iac/fixtures/.snyk
This PR adds to the Iac CLI Share Results feature support for the `.snyk` policy file.
1. Run registry locally with [the following branch](https://github.com/snyk/registry/pull/26636).
2. Scan an IaC directory with a `.snyk` file inside that ignores a relevant issue using the command `snyk iac test --report`
3. Watch the issues getting ignored in the platform.
https://snyksec.atlassian.net/jira/software/c/projects/CFG/boards/301?modal=detail&selectedIssue=CFG-1522
=> feat: add support for snyk policy

src/cli/commands/describe.ts, src/cli/commands/test/iac-local-execution/analytics.ts, src/lib/iac/drift.ts, src/lib/iac/types.d.ts, test/fixtures/iac/drift/args-echo.sh, test/fixtures/iac/drift/download-test.sh, test/jest/unit/lib/iac/drift.spec.ts
This PR enables the `snyk iac describe` to send drift analytics to registry.
I also changed the way we exit the process after running driftctl. Before we were just `process.exit` but that prevented us from using the builtin `analytics.addDataAndSend` function already written for us. Now we're just using the `process.exitCode` that changes only the exit code that will be returned without exiting the process.
`src/cli/commands/describe.ts`
```
$ snyk iac describe
```
https://snyksec.atlassian.net/browse/CFG-1647
https://snyksec.atlassian.net/browse/CFG-1649
=> Enable drift analytics to be sent to registry

package-lock.json, package.json, src/lib/plugins/sast/analysis.ts, src/lib/plugins/sast/types.ts
This PR is for supporting beta languages from feature flag supported in the cli
The flow starts from registry - who passes supported languages array including the beta languages that are supported by FF and sends it to code-client to exclude non necessary files.
The corresponding ticket is :
https://snyksec.atlassian.net/browse/NEBULA-347
=> feat:adding beta language support

src/cli/commands/describe.ts, src/cli/commands/test/iac-local-execution/analytics.ts, test/jest/unit/lib/iac/drift.spec.ts
It should add the `is-iac-drift` analytics metadata when `driftctl scan` command exit with an error.
`snyk iac describe`
=> Should add is-iac-drift on error exit code too

src/lib/iac/drift.ts
That PR allow us to lookup for a driftctl binary in `/bin`.
This enable us to use `snyk/driftctl` as base image for our docker run.
You can see more context here : https://github.com/snyk/snyk-images/pull/26
Probably by reading the [README.md](https://github.com/snyk/snyk-images) of `snyk/snyk-images`
```$
$ touch /bin/driftctl && chmod +x /bin/driftctl
$ rm /home/elie.charra/.cache/snyk-nodejs/driftctl_*
$ env | grep DRIFTCTL_PATH
```
There is currently no way to easily E2E test that since we should be able to have a released version with that PR to test it in docker.
https://github.com/snyk/snyk-images/pull/26
https://snyksec.atlassian.net/browse/CFG-1621
=> Allow to lookup for driftctl binary in `/bin` too

.github/CODEOWNERS, src/cli/commands/describe.ts, src/lib/errors/describe-exclusive-argument-error.ts, src/lib/errors/describe-required-argument-error.ts, src/lib/iac/drift.ts, src/lib/iac/types.d.ts, test/jest/acceptance/iac/describe.spec.ts, test/jest/unit/lib/iac/drift.spec.ts
`snyk iac describe` show help by default and has to be called with right flags:
--all, --only-managed or --only-managed
Added a way to validate flags (both exclusive and required). It calls help command to get the help markdown rendered before throwing ab error that ask to add the right flag.
`snyk iac describe --all --only-unmanaged` should throw an error asking to only use one of the flags
`snyk iac describe` should throw an error asking to add one of the required flags
=> `snyk iac describe` show help by default and has to be called with right flags

src/cli/commands/test/iac-local-execution/handle-terraform-files.ts, src/cli/commands/test/iac-local-execution/index.ts, test/jest/acceptance/iac/test-terraform-var-deref.spec.ts, test/jest/unit/iac/handle-terraform-files.spec.ts, test/jest/unit/iac/index.spec.ts
This PR fixes a bug in the CLI when `iacTerraformVarSupport` is enabled (by default for free users) and multi-file Kubernetes resources are scanned. 
2. `mkdir empty`
3. `snyk-dev iac test empty` - still generates an empty error
4. `snyk-dev iac test ./test/fixtures/iac/terraform/empty_file.tf` - now generates an empty error, because that's what the old CLI does too and it makes sense to tell the customer if their TF file was empty
5. `snyk-dev iac test ./test/fixtures/iac/kubernetes/pod-privileged.yaml` - still generates vulnerabilities
6. `snyk-dev iac test ./test/fixtures/iac/kubernetes/pod-privileged-multi.yaml` - now generates vulnerabilities instead of an empty error, thus fixing the problem
7. `snyk-dev iac test ./test/fixtures/iac/` - still works for mixed …
=> fix: TF Vars bug when scanning multi-file Kubernetes resource

src/cli/commands/describe.ts, src/lib/iac/drift.ts, test/jest/unit/lib/iac/drift.spec.ts
Before this commit, by modifying the args object, the entire content of
the `exclude/iac-drift` part of the policy file was being included in
the `args` analytics column:
https://console.cloud.google.com/bigquery?project=snyk-main&d=snyk&p=snyk-main&t=cli_tracking_data&page=table&ws=!1m5!1m4!4m3!1ssnyk-main!2ssnyk!3scli_tracking_data!1m5!1m4!1m3!1ssnyk-main!2sbquxjob_673b5721_17fabce8705!3sUS
For huge policy files, this risks hitting bigquery's 10MiB limit for
columns and failing to send analytics: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types
=> fix: don't send drift excludes to analytics

src/lib/ecosystems/monitor.ts, src/lib/ecosystems/policy.ts, src/lib/ecosystems/resolve-test-facts.ts, src/lib/ecosystems/test.ts, src/lib/policy/find-and-load-policy.ts, src/lib/polling/common.ts, src/lib/polling/types.ts, test/jest/unit/lib/ecosystems/policy.spec.ts, test/jest/unit/lib/ecosystems/resolve-test-facts.spec.ts
- add support for ignoring the issues when a `.snyk`-like policy is defined in the scanned project (for the unmanaged c/c++ flows)
- add tests
=> feat: ignore issue support for c/c++ flows

packages/snyk-fix/src/types.ts, src/cli/commands/test/iac-local-execution/types.ts, src/lib/ecosystems/types.ts, src/lib/iac/cli-share-results.ts, src/lib/iac/envelope-formatters.ts, test/jest/acceptance/iac/cli-share-results.spec.ts, test/jest/unit/iac/cli-share-results.fixtures.ts
This PR consists of two commits:
1. The first commit utilises the `getInfo()` from the gitBuilder to get the remote url and branch and add it back to the iac-cli-share-results endpoint. We override the branch with `master` as in this feature, we do not care about branches.
2. The second commit utilises the existing 'getContributors()' function to count the developers of the repo we scan.
It returns the emails and the lastCommitDate for each one of the commits in the last 90 days.
We then send this as part of the body to '/iac-share-cli-results'.
So, the payload we send now for the body is:
```
{
scanResults: [ ],
contributors: { }
}
```
an example curl:
```
curl --location --request POST 'http://127.0.0.1:8000/api/v1/iac-cli-share-results' \
--header 'Authorization: token a-token-here' \ …
```
=> feat: Send git contributors to /iac-share-results

src/lib/iac/envelope-formatters.ts, test/jest/acceptance/iac/cli-share-results.spec.ts, test/jest/unit/iac/cli-share-results.fixtures.ts, test/jest/unit/iac/cli-share-results.spec.ts
Currently, when running a scan from a directory that is a part of a git repo we will save inside the `target` filed the repo remote URL and branch.
We are using the remote URL to get information for the contributing developers but we currently don't have any use for the branch.
In addition to that, a side affect of sending the branch inside the `target` is that it gets auto-assigned as the `target-reference` which is not the desired outcome.
Due to all the reasons I mentioned above we've decided to remove the branch from the `target`.
1. Enable the `iacCliShareResults` FF.
2. Use the command `snyk iac test --report` to test your IaC files.
3. Check that the projects have been created successfully in the platform WITHOUT target-reference.
=> fix: remove target.branch

package-lock.json, package.json, src/lib/display-policy.ts, test/acceptance/workspaces/npm-package-policy/.snyk, test/acceptance/workspaces/npm-package-policy/custom-location/.snyk, test/acceptance/workspaces/npm-with-dep-missing-policy/.snyk, test/fixtures/npm/with-vulnnerable-lodash-and-snyk-file/.snyk, test/fixtures/project-with-patchable-dep-fixture-and-snyk-patched/.snyk, test/fixtures/protect-lodash-skip/.snyk, test/fixtures/protect-semver/.snyk, test/fixtures/snyk-config-no-version/.snyk, test/fixtures/snyk-config-no-version/expected, test/jest/unit/iac/cli-share-results.fixtures.ts
- include the 'exclude' rules on the demunge implementation
- exclude might contain 2 categories/ids: `global` and `code`
- the entries for `exclude.global/code` might be simple paths (strings) or objects (including metadata like reason, creation/expiration dates).
The changes on the policy library were done here: https://github.com/snyk/policy/pull/70
=> feat: display policy's exclude entries

src/cli/commands/test/iac-local-execution/assert-iac-options-flag.ts, src/cli/commands/test/iac-local-execution/index.ts, src/cli/commands/test/iac-local-execution/share-results.ts, src/cli/commands/test/iac-local-execution/types.ts, src/lib/ecosystems/types.ts, src/lib/iac/cli-share-results.ts, src/lib/iac/envelope-formatters.ts, test/jest/acceptance/iac/cli-share-results.spec.ts, test/jest/unit/iac/cli-share-results.fixtures.ts, test/jest/unit/iac/cli-share-results.spec.ts
- Adds support for the `--target-reference` flag for the CLI Share Results feature for Snyk IaC
- `src/cli/commands/test/iac-local-execution/index.ts` - Branching into all CLI Share Results related steps.
1. Enable the FF named `iacCliShareResults`
2. In the Snyk CLI, test any IaC file/directory with the following commands:
```
snyk-dev iac test {path_to_the_file} --report --target-reference={target_reference}
```
3. The API call to Registry for publishing this project should include a top-level property, named `targetReference`, which includes the provided value to the `--target-reference` flag.
- The `--target-reference` flag provides a reference that differentiates this project, for example, a branch name, or version.
Projects having the same reference can be grouped based on that …
=> feat: Add support for `--target-reference` for CLI Share Results [CFG-1521]

.github/CODEOWNERS, src/cli/commands/index.js, src/cli/commands/report/errors/unsupported-report-command.ts, src/cli/commands/report/index.ts, src/cli/commands/test/iac-local-execution/types.ts, src/cli/modes.ts, src/lib/types.ts, test/jest/acceptance/iac/report.spec.ts, test/jest/unit/iac/report.spec.ts
- Introduces a new command in the Snyk CLI -  `snyk iac report`, which servers as an alias to an existing command: `snyk iac test --report`
- `src/cli/commands/report.ts`
1. Ensure your org *does not have* the `iacCliShareResults` feature flag.
2. In the Snyk CLI, run:
```
snyk iac report <path-to-iac-file-or-directory>
```
3. in the Snyk CLI, run:
```
snyk iac test <path-to-iac-file-or-directory> --report
```
4. Ensure the `report` command has the same output as the previously existing `test --report` command.
1. Ensure your org *has* the `iacCliShareResults` feature flag.
2. In the Snyk CLI, run:
```
snyk iac report <path-to-iac-file-or-directory>
```
4. Ensure that an error appears for the missing feature flag.
We’d like to explore various approaches for introducing the new …
=> Feat: Create IaC report command [CFG-1730]

src/cli/commands/test/iac-local-execution/index.ts, src/cli/commands/test/iac-local-execution/results-formatter.ts, src/cli/commands/test/iac-local-execution/share-results.ts, src/cli/commands/test/iac-local-execution/types.ts, src/cli/commands/test/index.ts, src/lib/formatters/iac-output.ts, src/lib/iac/cli-share-results.ts, src/lib/types.ts, test/jest/acceptance/iac/cli-share-results.spec.ts, test/jest/unit/lib/formatters/iac-output.spec.ts
When a user runs a scan inside a git repo we pointed to the wrong projects collection, in this PR we fix this issue.
When invoking `snyk iac test --report` the command shows a message to the user telling him that the projects are available at his projects page under a dropdown menu with a certain name.
In cases where the user ran the scan inside a directory which is part of a git repo the dropdown menu name is incorrect.
This PR fixes this issue.
1. Run a test using the command `snyk iac test --report` inside of a directory which is part of git repo
2. The output should include the line: "Your test results are available at: http://localhost:8000/org/{org_name}/projects under the name {repo_name}"
3. Run a test using the command `snyk iac test --report` inside of a directory which is NOT …
=> fix: point to the correct projects collection in the platform

src/lib/iac/drift.ts
This PR updates the endpoint used to download the driftctl binary. Starting at v0.25, driftctl now upload its own release artifacts to Snyk's CDN (static.snyk.io). 
```
$ snyk iac describe
```
Check [the PR](https://github.com/snyk/driftctl/pull/1445) on driftctl side.
- https://snyksec.atlassian.net/browse/CFG-1601
=> [CFG-1601] Use static endpoint to download driftctl

test/jest/acceptance/snyk-apps/create-app.spec.ts, test/jest/util/runCommand.ts
Our prompt library inquirer only receives data from stdin after it has
been initialised. Therefore we can lose some buffered data if we send it
too fast, this is particularly noticeable if there are multiple inquirer
prompts in a row. There is no known way to check if the child process
that is under test is ready to receive input as node will swallow
anything given to stdin if it has nowhere to send it.
This hopefully will decrease the probability that these test fail by
increasing the delay between sending data to the child process.
=> fix: Increase delay between inputs on some acceptance tests

package-lock.json, package.json
Update CLI to use code-client version 4.9.0
=> fix: code-client update to v4.9.0

package-lock.json, package.json
today we fail in the case of '-r requirements # comment' line in the requirements.txt manifest file.
this upgrade fixes it (and ignore the comments)
=> fix: support comments in python manifest in requirements line

.circleci/config.yml, CONTRIBUTING.md
So that contributors can opt into running all tests without needing to misassign the branch as a "chore".
=> chore(ci): add test-all branch filter

src/cli/commands/test/iac-local-execution/rules.ts, test/jest/acceptance/iac/custom-rules.spec.ts
- Adds a warning user message when custom rules are provided for the:
- `snyk iac report` command.
- `snyk iac test --report` command.
`src/cli/commands/test/iac-local-execution/rules.ts`
1. Prepare a bundle of custom rules, using the instructions found [here](https://docs.snyk.io/products/snyk-infrastructure-as-code/custom-rules).
2. If your custom rules bundle is local:
2.1. Run the following in the Snyk CLI:
```
snyk-dev iac report <path-to-iac-file-or-dir> --rules=<path-to-custom-rules-bundle>
```
2.2. Ensure the following message was displayed at the top of the output:
```
Using custom rules to generate misconfigurations.
Please note that your custom rules will not be sent to the Snyk platform, and will not be available on the project's page.
```
2.3. Run the following in the Snyk …
=> chore: Added warning when custom rules with the `report` command [CFG-1737]

src/lib/iac/cli-share-results.ts, test/jest/acceptance/iac/cli-share-results.spec.ts
This PR intercepts 429 responses from the API when creating IaC projects via `snyk iac test --report`. If the API returns such a response, meaning that the user exceeded his test quotas, the CLI prints an error message on the console.
When the user exceeded its limit for IaC projects, the CLI outputs looks like this:
```
$ snyk iac test --report
Testing /Users/frm/src/test...
Test limit reached! You have exceeded your infrastructure as code test allocation for this billing period.
```
- [PR on the Registry](https://github.com/snyk/registry/pull/26868)
=> fix: Enforce test limits when creating IaC projects

package-lock.json, package.json
This patch picks up v2.14.0 if the SBT plugin which includes the following improvements:
- ignore the `scalafix` plugin which breaks the plugin; and
- add a heuristic for multi-project setups with a shared `project/`
folder.
https://github.com/snyk/snyk-sbt-plugin/pull/106
Install the plugin locally and run on a scala SBT project.
=> feat: use sbt plugin with improvements

config.default.json, src/cli/commands/apps/create-app.ts, src/lib/apps/index.ts, src/lib/apps/rest-utils.ts, src/lib/apps/types.ts, src/lib/config.ts, src/lib/request/promise.ts, test/acceptance/fake-server.ts, test/jest/acceptance/config.spec.ts, test/jest/acceptance/snyk-apps/create-app.spec.ts
The new Snyk rest api was originally released as the v3 api, however
since it contains its own versioning scheme it made no sense to have
another version in each endpoint. Therefore it was renamed to the more
generic "rest api" and the url moved from "/v3" to "/rest". The old url
will continue to work for a while during the transition phase but will
eventually go away.
This patch updates all references from the old v3 naming to the new rest
branding.
=> chore: Rename references to v3 api to rest api

src/lib/iac/drift.ts, src/lib/iac/types.d.ts, test/jest/acceptance/iac/describe.spec.ts
This PR remove useless `--json-file-output` flag.
We also added a test for covering the usage of the `html-file-output`, it may look unrelevant to have make those two change in the same PR but it's related to the same bug, see the Jira ticket.
`src/lib/iac/drift.ts`
```shell
$ snyk iac describe --all --json-file-output="test.json"
The following option combination is not currently supported: describe + json-file-output
```
We have decided to remove that flag in flavor of a documenting a redirect
`snyk iac describe --all --json > test.json`
BTW The flag is not working because of a global flag validation related to SARIF.
We have decide not to spend time digging into that, remove the flag and document a redirect
- https://snyksec.atlassian.net/browse/CFG-1741
- [Gitbook …
=> feat: remove `--json-file-output` for `snykl iac describe`

.circleci/config.yml, .github/workflows/smoke-tests.yml, .github/workflows/snyk-protect-production-smoke-tests.yml, package.json, src/cli/runtime.ts, test/jest/unit/runtime.spec.ts, test/smoke/spec/snyk_code_spec.sh, test/smoke/spec/snyk_monitor_spec.sh, test/smoke/spec/snyk_test_spec.sh, test/smoke/spec/spec_helper.sh, tsconfig.settings.json, webpack.common.ts
Snyk announced end of support for Node v10 https://updates.snyk.io/ending-snyk-cli-support-for-node-js-v10-219175
=> Drop Node.js 10 support

.github/CODEOWNERS, src/cli/commands/test/index.ts, src/lib/formatters/iac-output/index.ts, src/lib/formatters/iac-output/v1/index.ts, src/lib/formatters/iac-output/v2/index.ts, src/lib/formatters/test/display-result.ts, test/jest/unit/lib/formatters/iac-output/index.spec.ts, test/jest/unit/lib/formatters/iac-output/v1/index.spec.ts
- Adds versioning for the IaC output formatting logic.
- Creates a new version, labeled as `v2`, which is currently identical to the original logic, labeled as `v1`.
- Wraps the `v2` version with the newly created `iacCliOutput` feature flag.
```
src/lib/formatters/iac-output/index.ts
```
At the moment there's no output difference between the 2 versions.
To test it, you can utilize tools like logs or the debugger, to ensure the correct flows are used for each case.
- Without the `iacCliOutput` feature flag, we expect to use the original output formatters, which can be found in:
```
src/lib/formatters/iac-output/v1/index.ts
```
- With the `iacCliOutput` feature flag, we expect to use the new output formatters, which can be found in:
```
src/lib/formatters/iac-output/v2/index.ts
```
In a …
=> chore: Wrap new CLI output with `iacCliOutput` feature flag

test/jest/unit/lib/ecosystems/policy.spec.ts
"should handle empty issue array" and similar, were using current date as the expiry date which isn't reliable depending on how fast the test gets to the comparison. These tests are expecting nothing to be ignored so they should use an explicit future expiry date.
Example flake: https://app.circleci.com/pipelines/github/snyk/cli/11304/workflows/9daaf35b-f384-497d-acd4-8b28b49bb1de/jobs/86837
=> test: fix flakey policy test

src/cli/commands/ignore.ts, test/jest/acceptance/snyk-ignore/snyk-ignore.spec.ts
feat: add excluded paths to ignore command
Adds support to alter excluded files in the policy file:
- Extract ignoreVuln from ignore-function, and route CLI command to
the correct implementation
- Add excludeFilePathPattern to be called by the ignore-implementation.
Background:
The policy file supports two different groups of file:
- "code", for files being ignored by Snyk Code
- "global", for files being ignored by all products supporting the
exclude field, for instance `snyk test --unmanaged`.
Usage:
> snyk ignore --file-path='./deps/**.cpp'  # Defaults to the global group
> snyk ignore --file-path='./deps/**.go' --file-path-group='code'
> snyk ignore --file-path='./**/vendor/*.java' --file-path-group='global'
=> feature: add excluded paths to ignore command

.circleci/config.yml, release-scripts/upload-artifacts.sh
GitHub CLI by default maps a release to the last commit on the main branch. This is wrong when a release is from an older commit.
I've also updated GitHub CLI and the CircleCI orb to make sure it supports `--target`.
Docs: https://cli.github.com/manual/gh_release_create
You can see this issue here:
1. 8ac4a96 released. https://app.circleci.com/pipelines/github/snyk/cli/11302/workflows/4235d32e-b93c-47d0-a492-875c17a6760c 
2. 8538d31 was tagged with v1.892.0
3. cb8eaee released. https://app.circleci.com/pipelines/github/snyk/cli/11308/workflows/449de045-db6a-4067-9192-9699e52b23f3 
4. d49b534 was tagged with v1.893.0
=> chore(ci): map github release to correct commit

package-lock.json, package.json, src/cli/commands/ignore.ts, test/acceptance/workspaces/npm-package-policy/.snyk, test/acceptance/workspaces/npm-package-policy/custom-location/.snyk, test/acceptance/workspaces/npm-with-dep-missing-policy/.snyk, test/jest/acceptance/snyk-ignore/snyk-ignore.spec.ts, test/jest/unit/iac/cli-share-results.fixtures.ts
Adds support for meta-data during write and update of excluded files.
Meta data supported:
- creation
- expiry
- reason
Some excluded files, should only be excluded during a certain
time. After that date, we will scan and check for vuln. in
those files again.
> snyk ignore --file-path='./**/vendors/**.ts' --expiry=2092-10-10 --reason='files has been patched'
=> feat: support metadata for excluded paths

src/lib/monitor/dev-count-analysis.ts, test/jest/unit/dev-count-analysis.spec.ts
Snyk won't be ignoring merge commits from the dev counts. This behavior is aligned with the SCM import flow
=> Dev Count: count merge commits as well

test/jest/acceptance/iac/test-directory.spec.ts
I added the tests prematurely before fixing the bug associated with it, that's why I have skipped one of them.
It's a bit silly, but my goal was more to have this documented in case the bug does not get prioritised soon enough. [CFG-1477]
[CFG-1477]: https://snyksec.atlassian.net/browse/CFG-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: document variadic path scans for IaC

.github/CODEOWNERS
The test in question is for `src/lib/iac/makeDirectoryIterator.ts` so it was also added in the wrong place. I would move it to the right place here but actually we will remove it in https://github.com/snyk/cli/pull/3041 anyway.
=> chore: change ownership of test file

test/jest/acceptance/iac/cli-share-results.spec.ts, test/jest/acceptance/iac/custom-rules.spec.ts, test/jest/acceptance/iac/file-output.spec.ts, test/jest/acceptance/iac/iac-entitlement.spec.ts, test/jest/acceptance/iac/report.spec.ts, test/jest/acceptance/iac/test-arm.spec.ts, test/jest/acceptance/iac/test-cloudformation.spec.ts, test/jest/acceptance/iac/test-directory.spec.ts, test/jest/acceptance/iac/test-kubernetes.spec.ts, test/jest/acceptance/iac/test-terraform-plan.spec.ts, test/jest/acceptance/iac/test-terraform-var-deref.spec.ts, test/jest/acceptance/iac/test-terraform.spec.ts
This is a non functional change, just reordering the assertions in our iac acceptance tests.
So far, if a test fails - we will only see the exit code assertion and not the actual reason why. 
This commit moves all exit code assertions from the top assertion to the bottom.
In this way we can see the stdout actual text first when a test fails. It will be even easier for checking it in CircleCI.
example before:
=> test: get stdout failure text before exit code

src/lib/plugins/sast/analysis.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts
To make url of docs in the error msg separated from default dot at the end of the error message. 
for more details please look at the jira item below .  
https://snyksec.atlassian.net/browse/NEBULA-453
=> chore : change-error-msg-lce

.circleci/config.yml
When a merge is released, it's still possible to re-run older commits and release them. This prevents that by checking if the commit already has a git tag ahead of it.
=> chore(ci): prevent older commits from releasing

package-lock.json, package.json
See https://github.com/snyk/snyk-mvn-plugin/pull/115
Produce a flat dependency graph when scanning unmanaged Java archives.
We no longer resolver transitive lines. Each archive is a top level dependency with no transitives.
This should fix problems reported when transitive lines were interfering with one another.
=> feat: produce flat dep-graph scanning unmanaged

package-lock.json, package.json
Throws an error with informative message if a folder is empty.
=> fix: scan-failing-on-empty-folder

.github/CODEOWNERS
add Potion to codeowners
add Potion to codeowners
A new team, Potion, is forming to cover some of Capsule's old responsibilities
`#ask-potion` slack channel
=> chore: add Potion to codeowners

src/cli/commands/test/index.ts, test/acceptance/fake-server.ts, test/jest/acceptance/iac/new-test-output.spec.ts
If the feature flag `"iacCliOutput"` is enabled and the `test` command is invoked in `iac` mode, the CLI shows an initial message to the user.
The only change has been performed in the top-level test command (`src/cli/commands/test/index.ts`) because the initial message should be printed only once, independently on the number of tested paths.
Enable the feature flag on the Registry, and execute a `snyk iac test` command.
[CFG-1578](https://snyksec.atlassian.net/browse/CFG-1578)
=> feat: Add an initial user message to the test output

src/lib/formatters/iac-output/index.ts, src/lib/formatters/iac-output/v2/color-utils.ts, src/lib/formatters/iac-output/v2/index.ts, src/lib/formatters/iac-output/v2/test-summary.ts, src/lib/formatters/iac-output/v2/types.ts, test/jest/unit/lib/formatters/iac-output/test-summary.spec.ts
- Adds the implementation for the formatter of the new summary section in the new CLI output for test flow of IaC in the Snyk CLI.
- This formatter was **not applied** to the test flow in this PR, but rather in a future separate PR.
- This formatter is applied to the test flow in this PR: #3102 
- Following the discussion on [this Slack thread](https://snyk.slack.com/archives/C030UA3U1RB/p1649151568166039), the project name and project path were not added to the test summary as part of this ticket, but need to be added at a later point in time.
- `src/lib/formatters/iac-output/v2/test-summary.ts`
- Since this PR adds the formatting logic but does not apply it in the test flow, the output of the IaC test will not be altered yet. That being said, the formatter can be still be executed and …
=> feat: Implemented IaC test summary formatter [CFG-1571]

.circleci/config.yml, CONTRIBUTING.md, test/jest/util/runSnykCLI.ts
Some variants of runSnykCLI did not include the check to see if `TEST_SNYK_COMMAND` was passed in so they we still testing against the NodeJS script.
=> test: use TEST_SNYK_COMMAND in run variants

package-lock.json, package.json
Use CPP-plugin v2.19.2 to support --unmanaged combined with --project-name.
=> fix: support --project-name for unmanaged projects

.github/CODEOWNERS
The new team responsible for SAST, Zenith, doesn't seem to have their Github org setup correctly yet. Removing Nebula's ownership
=> chore: transferred Nebula's ownership to Zenith NEBULA-492

src/lib/iac/drift.ts
This PR bumps the driftctl's version to [v0.27.0](https://github.com/snyk/driftctl/releases/tag/v0.27.0).
- https://snyksec.atlassian.net/browse/CFG-1761
=> [CFG-1761] Bump driftctl version to v0.27.0

src/cli/commands/test/iac-local-execution/assert-iac-options-flag.ts, src/cli/commands/test/iac-local-execution/index.ts, src/cli/commands/test/iac-local-execution/types.ts, src/lib/types.ts, test/fixtures/iac/terraform/var_deref/nested_var_deref/sg_open_ssh.tf, test/fixtures/iac/terraform/vars.tf, test/jest/acceptance/iac/test-directory.spec.ts, test/jest/acceptance/iac/test-terraform-var-deref.spec.ts
Adds a `--var-file` flag to iac test for loading external Terraform variable definition files. See commit messages below for details.
Follow the commits in order: 
1. chore: add 'var-file' flag option to iac test command
This commit adds the 'var-file' flag as an available command under 'iac test'. CFG-1663
2. chore: Throw errors if 'var-file' flag is misused.
This commit adds checks around the 'var-file' flag usage: - If the user does not have the 'iacTerraformVarSupport' feature flag, we will throw an error. - If the user provides a non-existent path, we will throw an error. CFG-1663
3. feat: Load TF variable definitions files via --var-file
This commit adds the ability to load an external file by using 'var-file' flag:
- The user can point to a single filepath, relative to the …
=> feat: Add '--var-file' flag to iac test for loading external TF variable definition files [CFG-1663]

test/acceptance/fake-server.ts
Removes a mocked up API call for the legacy `/test-iac` call that was being called by the legacy `snyk iac test` command.
=> refactor: remove old mock for /test-iac

test/acceptance/fake-server.ts, test/jest/acceptance/iac/test-terraform-var-deref.spec.ts
- Updates the way the `iacTerraformVarSupport` FF is used in the `test/jest/acceptance/iac/test-terraform-var-deref.spec.ts` acceptance tests to match the common practices applied in recent IaC acceptance tests, by:
- Removing the special FF configuration in the fake server that sets the value for all feature flags to be true when the org name is `tf-lang-support`.
- Using the `setFeatureFlag` utility function for controlling feature flag values.
- `test/jest/acceptance/iac/test-terraform-var-deref.spec.ts`
- Run the test file with Jest.
=> test: Updated FF usage in TF vars deref test

test/jest/acceptance/iac/iac-output.spec.ts
- Fixes failing Windows acceptance tests in `test/jest/acceptance/iac/iac-output.spec.ts`, by replacing the newline character instead of `EOL` in the expected output fixtures.
test/jest/acceptance/iac/iac-output.spec.ts
- Ensure these acceptance tests now all pass.
- The tests were originally added in [this PR](https://github.com/snyk/cli/pull/3102). 
- [An example for a failing CircleCI pipeline](https://app.circleci.com/pipelines/github/snyk/cli/11574/workflows/7dd53554-f390-43c1-8190-e680642bf076/jobs/89027)
=> fix: Fixed failing acceptance tests for IaC output

src/cli/commands/test/iac/local-execution/file-utils.ts, src/cli/commands/test/iac/local-execution/process-results/extract-line-number.ts, src/cli/commands/test/iac/local-execution/process-results/results-formatter.ts, src/cli/commands/test/iac/local-execution/process-results/share-results-formatter.ts, src/cli/commands/test/iac/local-execution/process-results/utils.ts, src/cli/commands/test/iac/local-execution/types.ts
This PR does some small cleanup of the code so that anything belonging to the `processResults` functionality and results formatter goes in the right folder.
2. `snyk-dev iac test test/fixtures/iac/terraform/sg_open_ssh.tf`
In https://github.com/snyk/cli/pull/3080 we created this `process-results` folder to hold anything that has to do with displaying issues on the CLI stdout.
=> refactor: move results formatter utilities into process-results

src/cli/commands/test/iac/index.ts, src/lib/formatters/iac-output/index.ts, src/lib/formatters/iac-output/v2/formatters.ts, src/lib/formatters/iac-output/v2/index.ts, src/lib/formatters/iac-output/v2/issues-list.ts, src/lib/formatters/iac-output/v2/types.ts, src/lib/formatters/test/display-result.ts, test/acceptance/fake-server.ts, test/jest/acceptance/iac/iac-output.spec.ts, test/jest/unit/iac/process-results/fixtures/new-output-formatted-results.json, test/jest/unit/lib/formatters/iac-output/index.spec.ts, test/jest/unit/lib/formatters/iac-output/issues-list.spec.ts, test/jest/unit/lib/formatters/iac-output/v2/formatters.spec.ts
We’d like to restructure the layout of the issues list.
The changes include:
1. Shortening the current title, “Infrastructure as code issues:”, to “Issues“ (without colon)
2. Instead of having a list of issues per file, we would like to have a list of issues per severity level.
These sections should be sorted from highest severity to lowest.
Each section should have a title with the number of the issues detected with the corresponding severity. Example: “Medium Severity Issues: 2”.
The titles should be colorized based on the severity they represent. The color mapping can be found in [this design](https://miro.com/app/board/uXjVOOpVGxU=/?moveToWidget=3458764518430874390&cot=14).
Test an IaC configuration files without the FF and check that the output didn't change.
Turn on the FF, test the …
=> feat: restructure the issues list layout

src/lib/formatters/iac-output/v2/issues-list.ts, test/jest/unit/lib/formatters/iac-output/issues-list.spec.ts
- Removes the Bold highlight from the titles of the severity sections in the issues list for the new IaC test output, to align them with [the given design](https://www.figma.com/file/buNFZqr1Uhf4SaifHw4WXE/Snyk-IaC-CLI).
- **Before**
- **After**
=> fix: Unbold severity section titles in IaC test output

src/lib/analytics/sources.ts
Introduce additional tracked integration name
Run `SNYK_INTEGRATION_NAME=CLI_V2 snyk --debug` and see the IntegrationName in the Analytics output
=> chore: add CLI_V2 to TrackedIntegration enum

package-lock.json, package.json, src/cli/commands/describe.ts, src/cli/commands/test/iac/local-execution/analytics.ts, src/lib/iac/drift.ts, src/lib/iac/drift/driftctl.ts, src/lib/iac/drift/output.ts, src/lib/iac/service-mappings.ts, src/lib/iac/types.d.ts, test/jest/acceptance/iac/describe.spec.ts, test/jest/unit/lib/iac/drift.spec.ts, test/jest/unit/lib/iac/fixtures/alldeep.console, test/jest/unit/lib/iac/fixtures/alldeep.json, test/jest/unit/lib/iac/fixtures/only-managed.console, test/jest/unit/lib/iac/fixtures/only-managed.json, test/jest/unit/lib/iac/fixtures/only-unmanaged.console, test/jest/unit/lib/iac/fixtures/only-unmanaged.json
This PR update the `snyk iac describe` output with new ui by the design team.
(https://miro.com/app/board/uXjVOVYR5zg=/?share_link_id=306344151216)
This is a first iteration for the ui.
Sorry about that but I made some refactoring to not have everything inside a single big typescript file, I hope this won't make the reviewing too painfull.
The pr introduce some change in drift.ts for the logic about driftctl first run output handling (mainly to use driftctl fmt only for html output).
Main addition will then be inside drift/output.ts.
https://snyksec.atlassian.net/browse/CFG-1660
=> [CFG-1660] new ui for `snyk iac describe`

src/cli/commands/test/iac/index.ts
- Fixes the results sent for formatting the test summary to exclude potential error objects. These are generated whenever the test for one of the provided paths results in an error.
```
src/cli/commands/test/iac/index.ts
```
1. Provide multiple paths, for some of which the test should entirely fail with an error.
2. Ensure the execution does not end with an error message, and that results for valid files are displayed.
3. Ensure the values in the test summary section are valid.
When providing multiple paths, and having some of which throw an error during the test, these are currently incorrectly included in the results that are being sent for formatting the test summary section. We'd like to ensure errors cannot be included in the results sent for formatting the test summary.
The current …
=> fix: Exclude error results from IaC test summary

src/lib/formatters/iac-output/v2/test-summary.ts
- Removes the reference to the `none` severity in the test summary formatter for the new CLI output.
```
src/lib/formatters/iac-output/v2/test-summary.ts
```
- Having scanned the code to learn more about the usage for the `none` severity for Snyk IaC, it's been concluded that this severity is only available via the custom severities feature. When the test results reach the output formatting stage, issues with the `none` severity are already filtered out, so there's no need to take these into account in the output.
=> fix: Remove `none` severity from test summary

src/cli/commands/test/iac/local-execution/local-cache.ts, src/lib/config.ts
When developing certain Snyk IaC features, it can be useful to override
the OPA WASM bundle with a locally-built version. This commit introduces
and environment variable, SNYK_IAC_BUNDLE_PATH, which is not documented
anywhere. This is intended for Snyk IaC developers, and is not useful
for other users. The user-facing equivalent is custom rule bundles.
This is useful for https://snyksec.atlassian.net/browse/CFG-1776, which is a spike, but I am actually proposing this PR to be merged, as it is useful for similar development work.
=> [CFG-1776] feat: developer flag to override IaC bundle path

src/cli/commands/update-exclude-policy.ts
Should add the `is-iac-drift` analytics to the `snyk iac update-exclude-policy` command.
Create a json file that represents your infrastructure drifts
`snyk iac describe --all --json > test.json`
Then, use the command update-exclude-policy command
`cat test.json | snyk iac update-exclude-policy`
You should see the `isIacDrift` analytics in your registry logs
https://snyksec.atlassian.net/browse/CFG-1770
=> chore: add is-iac-drift analytics to update-exclude-policy command

src/cli/commands/test/iac/index.ts, src/lib/formatters/iac-output/index.ts, src/lib/formatters/iac-output/v2/color-utils.ts, src/lib/formatters/iac-output/v2/failures-list.ts, src/lib/formatters/iac-output/v2/index.ts, src/lib/formatters/iac-output/v2/initial-user-message.ts, src/lib/formatters/iac-output/v2/issues-list.ts, src/lib/formatters/iac-output/v2/share-results.ts, src/lib/formatters/iac-output/v2/test-summary.ts, test/jest/unit/lib/formatters/iac-output/v2/failures-list.spec.ts, test/jest/unit/lib/formatters/iac-output/v2/initial-user-message.spec.ts, test/jest/unit/lib/formatters/iac-output/v2/issues-list.spec.ts, test/jest/unit/lib/formatters/iac-output/v2/share-results.spec.ts, test/jest/unit/lib/formatters/iac-output/v2/test-summary.spec.ts
- Updates the color utilities for the new CLI output to include the `info` and `success` colors,  and applying them to the relevant output sections.
- Extracts output functions and messages for the initial user message and share results, and adds tests for them.
- `src/lib/formatters/iac-output/v2/color-utils.ts`
- `src/cli/commands/test/iac/index.ts`
=> refactor: Extracted output methods and updated color utilities

src/cli/commands/test/iac/index.ts, src/cli/commands/test/iac/local-execution/index.ts, test/jest/unit/iac/index.spec.ts
This PR moves the code that downloads and prepares custom and built-in rules at the beginning of the `snyk iac test` command. Before, these tasks were performed for each scanned path, resulting in an amount of unnecessary network calls and file system operations directly proportional to the number of scanned paths. Now, custom and built-in rules are downloaded and prepared only once.
The code for downloading rules and cleaning up temporary directories has been moved from `src/cli/commands/test/iac/local-execution/index.ts` to `src/cli/commands/test/iac/index.ts`.
Moreover, one test has been removed from `test/jest/unit/iac/index.spec.ts`. The behaviour under test is already exercised by other tests in `test/jest/acceptance/iac/custom-rules.spec.ts`.
Perform a scan of multiple paths by …
=> refactor: Download rules bundles only once per execution

src/lib/plugins/sast/utils/testEmitter.ts
Adds API request logs in -d mode.
With this change, I was able to solve 2 big problems with CLI/deeproxy -- the short connection timeout problem (fails to scan big-sized repos) and a CDN issue in ST envs for deeproxy, blocking request with 403.
Hence, I think its worth printing API request logs when running in -d mode especially since our error handling is not perfect
)
=> feat: more logs in code in -d mode

package-lock.json, package.json, src/lib/formatters/iac-output/v2/issues-list.ts, test/jest/acceptance/iac/iac-output.spec.ts, test/jest/unit/lib/formatters/iac-output/v2/issues-list.spec.ts
- Adds a green `No vulnerable paths were found!` user message for when no issues are found.
src/lib/formatters/iac-output/v2/issues-list.ts
- Test a file/path without issues, ensure the new user message appears and matches the design found [here](https://snyk.slack.com/archives/C030UA3U1RB/p1649583059675669).
Currently, whenever no issues are discovered in the provided paths to test, we display the Issues title, with an empty list below, with none of the severity subsections. See the image below:
Rather than displaying an empty list, we’d like to display a green user message, that says No vulnerable paths were found!, as can be seen below:
- [CFG-1773](https://snyksec.atlassian.net/browse/CFG-1773)
=> feat: Added message for no issues found [CFG-1773]

src/lib/plugins/sast/index.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts
Adds the `--json-file-output` argument to `snyk code test`. Since `--json` currently produces the same output as `--sarif`, `--json-file-output` also produces the same output as `--sarif-file-output`.
Bother `--json-file-output` and `--sarif-file-output` are supported at the same time. 
Run `snyk code test --json-file-output=vuln.json`
[ZEN-128](https://snyksec.atlassian.net/browse/ZEN-128)
=> feat: add --json-file-output support to `code test`

src/cli/commands/test/iac/local-execution/file-parser.ts, test/jest/acceptance/iac/test-directory.spec.ts, test/jest/acceptance/iac/test-terraform-var-deref.spec.ts, test/jest/unit/iac/file-parser.spec.ts
This commit will fix an issue where unsupported IaC files were printed in the scan output for users without the iacTerraformVarSupport flag.
This was due to a refactoring, where a check for the valid IaC files was skipped. 
It is also not considered part of the failedFiles, as it was not tested at all. (I checked the previous behaviour with an older version as well, e.g 1.840.0)
This is now added (hardcoded) for the flow that the flag is off. This flow is planned to be deprecated next week so I chose to do a quick fix for the customers now.
- Make sure the `iacTerraformVarSupport` flag is off.
- Run `snyk-dev iac test test/fixtures/iac/terraform/var_deref` (which contains non supported IaC files such as auto.tfvars) and see that the results do not contain `unsupported file extension …
=> fix: Skip unsupported IaC files

.vscode/launch.json, src/lib/plugins/sast/analysis.ts, test/fixtures/sast/sample-sarif.json, test/jest/unit/snyk-code/snyk-code-test.spec.ts
Set the `ruleIndex` of a result to match the index of the rule in the security rules map
`src/lib/plugins/sast/analysis.ts`
run `code test` on a repo, in each result, look for rule index and make sure it matches in the rules array
When we run a code test, we first alter the rules array to use only security rules. The source of the problem lies when we don't address the `ruleIndex` that is now outdate since the rules indexes have changed.
[Jira Ticket](https://snyksec.atlassian.net/browse/ZEN-23)
N/A
I've also fixed the test fixture to match the desired result
=> fix: set rule index result by security rules mapping

.circleci/config.yml, CONTRIBUTING.md, cliv2/.gitignore, test/jest/acceptance/analytics.spec.ts, test/jest/acceptance/cli-args.spec.ts, test/jest/acceptance/https.spec.ts, test/jest/acceptance/iac/helpers.ts, test/jest/acceptance/iac/iac-output.spec.ts, test/jest/acceptance/iac/update-exclude-policy.spec.ts, test/jest/acceptance/proxy-behavior.spec.ts, test/jest/util/isCLIV2.ts
Running Jest acceptance tests against CLIv2.
- Parameterised test jobs so we can re-use them with different binaries.
- Skipped failing tests so we can work on them separately and avoid blocking on this PR.
=> chore(ci): test v2 against jest acceptance tests

.circleci/config.yml
Similar to #3170. Run regression test job for CLIv2, like we do for CLIv1.
- Parameterised `test_snyk_command` so we can use different binaries.
- Changed regression tests to use binaries instead of npm tarball.
=> chore(ci): test v2 against regression tests

.circleci/config.yml, .github/workflows/smoke-tests.yml, CONTRIBUTING.md, src/lib/spinner.ts, test/smoke/docker-root/Dockerfile, test/smoke/install-shellspec-win.sh, test/smoke/install-shellspec.sh
- git.io is deprecated https://github.blog/changelog/2022-04-25-git-io-deprecation/
Separate commit to fix `test-all` branch name trigger used to run full test pipeline in CircleCI.
=> chore(ci): vendor shellspec install script

.circleci/config.yml, CONTRIBUTING.md, cliv2/Makefile, cliv2/internal/cliv2/cliv2.go
- Move v2's pipeline into v1's pipeline after v1 binaries are built.
- Use locally built v1 binaries for building v2 binaries instead of downloading the latest v1 release.
- Fix v2's versioning to be consistent. Version files no longer contain "v".
- Previous implementations removed the "v" in "dev" versions.
- Use `.` instead of `+` for v2 versioning as `+` is whitespace in URLs.
- Run v2 builds and tests on `master`.
- Prefix jobs with "v2 /" to easily differentiate from v1 jobs.
=> chore(ci): integrate v2 into release pipeline

.circleci/config.yml
- Remove Go install steps for v2 tests as they aren't needed.
- Proxy tests do still need Go for proxy cert/key generation.
=> chore(ci): build and test v2 arm64 binaries

.github/CODEOWNERS, config.default.json, src/lib/code-config.ts, src/lib/plugins/sast/analysis.ts, test/jest/unit/lib/endpoint-config-test.spec.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts
[NEBULA-443](https://snyksec.atlassian.net/browse/NEBULA-443)
We wish that the customer of ST will not need to add this configuration and only configure 'API' value.
Please refer to Jira ticket for more information.
=> feat: remove-deeproxy-url-configuration

cliv2/cmd/cliv2/main.go
Log error objects in error logs to provide better visibility of the error cause.
=> chore: log error objects

package-lock.json, package.json
Bumps up the version of our cloud-config-parser: https://github.com/snyk/cloud-config-parser/pull/42
The new version of the cloud-config-parser returns -1 when an exact lineNumber could not be found and we returned the "closest" match instead.
Functionality wise, this should not be a breaking change for the CLI. It would just avoid the situation where we were returning "incorrect" lineNumbers.
Get a file that used to provide a wrong linenumber, eg https://github.com/snyk/snyk-iac-cloudformation/blob/main/billing-alerts.yml used to provide `2` in some issues when we could not find the exact path. Now it should return `-1` for json, or nothing for sarif
Run `snyk iac test billing-alerts.yml --json` 
Run `snyk iac test billing-alerts.yml --sarif` 
relevant to: …
=> chore: bump cloud config parser to v1.14.1

src/cli/commands/report/index.ts, src/cli/commands/test/iac/index.ts, src/cli/commands/test/index.ts, test/jest/acceptance/iac/report.spec.ts, test/jest/unit/iac/report.spec.ts
We would like to remove the command `snyk iac report` in the least disruptive way, this PR adds a deprecation notice / warning when a user runs the command `snyk iac report` that let them know when are we planning to remove the command and which command and flag are replacing it.
1. Run `snyk iac report`
2. Check that the warning is being printed at the end of output
3. Run `snyk iac test --report`
4. Check that a warning is not being printed 
https://snyksec.atlassian.net/jira/software/c/projects/CFG/boards/301?modal=detail&selectedIssue=CFG-1794
=> feat: deprecation notice when user run `snyk iac report`

cliv2/cmd/cliv2/main.go, cliv2/internal/proxy/proxy.go, cliv2/internal/proxy/proxy_test.go
Updates the CLIv2 proxy so that, if the `x-snyk-cli-version` header is present on a request, we replace it with the v2 version.
=> Replace value of x-snyk-cli-version with v2 version if set

cliv2/internal/cliv2/cliv2.go, test/jest/acceptance/cli-args.spec.ts
* re-enable disabled test for cliv2
Mimic cliv1 behaviour in cliv2 for unsupported command options 
Execute the snyk cliv2 with the parameter `version —json-file-output`
=> fix: cliv2 unsupported combination version + —json-file-output

src/lib/formatters/iac-output/v2/issues-list/index.ts, test/jest/unit/lib/formatters/iac-output/v2/issues-list/index.spec.ts
- Adds issues sorting in each severity section of the issues list, by file path and security rule public ID in this order of prioritization, both ascending.
```
src/lib/formatters/iac-output/v2/issues-list/index.ts
```
- Ensure you have the `iacCliOutput` feature flag activated.
- Run the `snyk iac test` command and ensure the issues in each severity section are sorted according to the order stated above.
- [CFG-1774](https://snyksec.atlassian.net/browse/CFG-1774)
- Slack channel: [#feat-iac-cli-output](https://snyk.slack.com/archives/C030UA3U1RB)
- [Relevant thread](https://snyk.slack.com/archives/C030UA3U1RB/p1649681027260669)
=> chore: Add issues sorting [CFG-1774]

test/jest/acceptance/analytics.spec.ts
Fixes the test `test/jest/acceptance/analytics.spec.ts` - `uses OAUTH token if set` by making it use the `snyk woof` rather than `snyk version` because `snyk version` doesn't do analytics in CLIv2 (yet).
=> Fix analytics test to work with CLIv2

test/jest/acceptance/proxy-behavior.spec.ts
Makes the `test/jest/acceptance/analytics.spec.ts` - `sends analytics for `snyk test` with no vulns found` test work with CLIv2. The error message is different in CLIv2 since it goes through the Go proxy.
=> Fix proxy behavior test to work with cliv2

cliv2/cmd/cliv2/main.go, cliv2/internal/proxy/proxy.go, test/jest/acceptance/https.spec.ts
By default goproxy enables `InsecureSkipVerify` which is equivalent to using `--insecure`. This fix works by overriding goproxy's default and adding v2 support for `--insecure`.
I've also removed the manual handling for HTTPS_PROXY as go already handles that using `ProxyFromEnvironment`.
- goproxy defaults: https://github.com/elazarl/goproxy/blob/a92cc753f88eb1d5f3ca49bd91da71fe815537ca/certs.go#L18-L22
=> fix(v2): verify proxy transport by default

src/lib/formatters/iac-output/v1/index.ts, src/lib/formatters/iac-output/v1/utils.ts, test/jest/unit/lib/formatters/iac-output/v1/index.spec.ts
This PR fixes a problem in the GitHub action where the incorrect `PROJECTROOT` is computed (without a `/` at the end) when there is no `git` command.
The commits show how the code was refactored so it's easier to test, a test added to make sure we don't re-introduce this regression, and the actual fix.
It's hard to test manually because we all have `git` and we don't want to delete it just for this use case. Can see the failure here though: https://github.com/teodora-sandu/terraform-lambda-api-gateway/runs/6322494869?check_suite_focus=true
In https://github.com/snyk/cli/commit/30746efb0cc9b3dc5d466af5603af9abf76e59a2 we can see the regression. The reason we didn't catch it is because the GitHub action acceptance tests in https://github.com/snyk/snyk/blob/0447fcd47b6e2e6d3850a26a3c6b584a185 …
=> fix: SARIF output for IaC

src/cli/commands/test/iac/local-execution/process-results/share-results-formatter.ts
This PR ensures that the paths generated during an IaC scan and shared with the app always use forward slashes, independently of the platform where `snyk` runs.
Run `snyk iac test --report` on Windows and verify that the results are correctly shared with the app and use forward slashes.
=> fix: Ensure that IaC shared results paths use forward slashes

src/cli/commands/test/iac/index.ts, src/lib/formatters/iac-output/v2/test-summary.ts, src/lib/formatters/iac-output/v2/types.ts, test/jest/acceptance/iac/iac-output.spec.ts, test/jest/unit/iac/process-results/fixtures/scan-failures.json, test/jest/unit/lib/formatters/iac-output/v2/test-summary.spec.ts
- Adds the invalid files count to the test summary section, to increase its visibility. This change is based on this design.
src/lib/formatters/iac-output/v2/test-summary.ts
- Test a directory with any number of invalid files (including none), and ensure that the correct number of invalid files appears in the test summary section.
In [the new test output design](https://www.figma.com/file/buNFZqr1Uhf4SaifHw4WXE/CLI-IaC-Output-Improvements?node-id=0%3A1), we are currently not displaying the number of files that failed to be tested in the test summary section, but it's included in the title for the test failures section.
We would like to add it to the test summary section as well, to increase visibility.
- [CFG-1787](https://snyksec.atlassian.net/browse/CFG-1787)
=> chore: Added an invalid files count to the test summary section [CFG-1787]

cliv2/cmd/cliv2/main_test.go, cliv2/internal/proxy/proxy_test.go
Should have been removed in #3184 but tests weren't running.
=> test(v2): upstreamProxy no longer defined

test/jest/unit/iac/process-results/share-results-formatters.fixtures.ts, test/jest/unit/iac/results-formatter.fixtures.ts, test/jest/unit/lib/commands/fix/get-display-path.spec.ts
This PR fixes some unit tests whose behaviour depend on the name of the clone of this repository. These tests always pass on CI because we always clone this repository in a `snyk` directory, but may fail locally if the project is cloned in a directory of a different name.
You can review this PR test by test, and ignore the tests that don't belong to you.
Clone this repository in a directory that is not named `snyk` and run all the unit tests with `npm run test:unit`.
=> test: Fix tests depending on the name of the cloned repository

package-lock.json, package.json, src/lib/code-config.ts, src/lib/plugins/sast/analysis.ts, test/jest/acceptance/snyk-code-config/snyk-code-config.spec.ts, test/jest/unit/snyk-code/snyk-code-config.spec.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts
- Adds support for base64 encoded payloads when executing `snyk code test`
- Targets single-tenant deployments of Snyk only
- Changes made to `src/lib/config.ts` to handle the new config key, and `src/lib/plugins/sast/analysis.ts` to handle setting the new `base64Encoding` variable.
- A version of `deeproxy` with base64 encoding support is required (supported from https://github.com/snyk/deeproxy/pull/135 onwards)
- Either:
- set the `SNYK_CFG_USE_BASE64_ENCODING` environment variable to `true`, or
- set the `USE_BASE64_ENCODING` config value to `true`
- Execute `snyk code test -d` - the debug entry `snyk-code Base 64 Encoding enabled: true +0ms` should be present
- Validate the request to the `/bundle` endpoint is base64 encoded
- This is targeted only for single tenant deployments …
=> feat: support base64 encoding

src/lib/iac/drift/driftctl.ts
Bump driftctl to allow the new client analytics to be sent + bunch of new resources.
=> chore: bump driftctl

.circleci/config.yml, cliv2/Makefile, cliv2/internal/certs/certs.go, cliv2/scripts/lint.sh
Adding linter step to ensure we are following gofmt formatting and avoid misalignment across commit diffs.
gofmt does not fail on unformatted files so I added a wrapper script to do so.
=> chore(ci): add linter to v2 pipeline

package-lock.json, package.json
Updates the code client to the latest version.
This update means Code-client will now retry on 500 failures when making downstream calls. 
Code-client change [here](https://github.com/snyk/code-client/pull/145)
=> feat: update code client

package-lock.json, package.json
Upgrades `code-client` to `4.12.2` to correctly support:
- retries on `500` errors (https://github.com/snyk/code-client/pull/145)
- pin version of `needle` to prevent issues with proxy/global-agent: https://github.com/snyk/code-client/pull/148
- improve the UX of compression/encoding (https://github.com/snyk/code-client/pull/149)
=> feat: upgrade code client to 4.12.2

src/cli/commands/test/iac/index.ts, src/lib/formatters/iac-output/index.ts, src/lib/formatters/iac-output/v2/index.ts, src/lib/formatters/iac-output/v2/user-messages.ts, test/jest/unit/lib/formatters/iac-output/v2/user-messages.spec.ts
- Refactors the code for formatting user messages in the IaC test flow.
- Adds a check for the `quiet` flag when determining whether not to include user messages in the test output. See [thread](https://snyk.slack.com/archives/C0127HWU0E7/p1652104137457429).
src/lib/formatters/iac-output/v2/user-messages.ts
- Ensure user messages are not included in the output when providing the `quiet` option.
- Ensure the output is not changed as a result of this refactor.
- This PR is separated from a follow up PR for adding a new progress indicator to the IaC test flow ([CFG-1757](https://snyksec.atlassian.net/browse/CFG-1757), #3221)
- [CFG-1757](https://snyksec.atlassian.net/browse/CFG-1757)
=> refactor: IaC test user messages

src/cli/commands/test/iac/local-execution/index.ts, src/cli/commands/test/iac/local-execution/process-results/index.ts, src/cli/commands/test/iac/local-execution/process-results/share-results-formatter.ts, src/cli/commands/test/iac/local-execution/process-results/share-results.ts, src/lib/iac/cli-share-results.ts, src/lib/iac/git.ts, src/lib/project-metadata/index.ts, src/lib/project-metadata/target-builders/container.ts, src/lib/project-metadata/target-builders/git.ts, src/lib/sub-process.ts, test/jest/unit/iac/cli-share-results.spec.ts, test/jest/unit/iac/process-results/share-results-formatters.spec.ts, test/tap/get-remote-url.test.ts
Currently when the user is running `snyk iac test --report {path1} {path2}` where `path1` and `path2` are git repo directories we group all the projects in the platform under one dropdown menu which is named after the current working directory, this is not the behaviour our users are expecting because from their point of view they are scanning 2 different directories so the projects should be grouped up into 2 different groups.
This PR fixes this issue by adding to the `git` commands we are executing the context of the path we are currently scanning.
Run `snyk iac test --report {path1} {path2}` before the change and after and check the difference.
In addition to that, `getInfo` is being used by other products in their `monitor` command so we should check that this change doesn't affect …
=> fix: git targets for variadic paths

cliv2/test/testlib.go
t.TempDir() is made for tests and manages naming and cleanup.
https://pkg.go.dev/testing#T.TempDir
=> test(v2): use go testing tempdir

src/lib/formatters/iac-output/v2/failures/list.ts, test/jest/acceptance/iac/iac-output.spec.ts, test/jest/unit/lib/formatters/iac-output/v2/failures/list.spec.ts
CFG-1834 - Part 1
- It renames the `Invalid Files` Tile to `Test Failures`.
- It removes the count from the tile section.
- FF on
- `snyk iac test test/fixtures/iac/kubernetes`
Running a test on a single invalid file, is still the same and displays the generic error "No valid files message":
`snyk-dev iac test test/fixtures/iac/kubernetes/pod-invalid.yaml`
CFG-1834
or on a single invalid file (no change):
=> feat: Update 'Invalid Files' section for IaC [CFG-1834]

release-scripts/make-binaries.sh
Details on how this works is in the script comments.
Once merged, we can see if it's working by reviewing changelogs in GitHub Releases or RELEASE_NOTES.md in CircleCI jobs.
=> chore: exclude v2 changes in v1 changelogs

.circleci/chocolatey.config, .circleci/config.yml, cliv2/go.mod
Update Go version to 1.18 to support generics
=> chore: update go version to 1.18 for generics

src/cli/commands/test/iac/index.ts, test/jest/acceptance/iac/test-directory.spec.ts
This commit fixes a bug where if we had multiple paths in a scan, and one of them threw an error, the entire scan was failing.
Now we are going to still show success results if there are any, and not fail the entire scan. 
Before we were treating the success and failures as the only possible options, but now I extended it to also have a "partial" success, when both sucess and errors were found.
The bug affected both the legacy output and the new output.
For the legacy we reverted to the old behaviour, showing the error when we scanned it.
For the new output we construct these errors in the end, and there's another ticket in play that does that, so I thought I'll open a seperate PR for that ticket to add it. (CFG-1834, CFG-1836)
P.S. the reason that the error is not bold red is that we …
=> fix: ignore errors on multiple paths if there were some results [CFG-1784]

src/lib/iac/drift/driftctl.ts
It bumps the driftctl version to [v0.30.0](https://github.com/snyk/driftctl/releases/tag/v0.30.0).
=> Bump driftctl version to v0.30.0

.circleci/config.yml, Makefile, release-scripts/make-binaries.sh, release-scripts/next-version.sh, release-scripts/prepare-packages-for-release.sh
Build job needs to be split so that we can parallelise it, but we only want to version bump once.
This change introduces a Makefile for CLIv1 which will gradually grow to include more build steps.
=> chore(ci): split versioning from build

src/cli/commands/test/iac/index.ts, src/lib/config.ts
- Creates a temporary `IAC_OUTPUT_V2 ` environment variable for enabling the New CLI Output feature.
```
src/cli/commands/test/iac/index.ts
```
- Ensure the new output is available by configuring either the feature flag or the temporary environment variable.
- Ensure the new output is not available when neither is configured.
- As part of the closed-beta release for this feature, we'd like to increase reachability for this feature and get as many users to test different use-cases and flows of the IaC test command. To do so, [it's been suggested](https://snyk.slack.com/archives/CS61093QC/p1652882875746809) that we create a temporary environment variable which can enable thie feature.
- [Relevant Slack thread](https://snyk.slack.com/archives/CS61093QC/p1652882875746809)
- [PR used for …
=> chore: Add a temporary `IAC_OUTPUT_V2` configuration for New CLI Output

.circleci/config.yml, Makefile, release-scripts/make-binaries.sh, release-scripts/release.json.sh, release-scripts/sha256sums.txt.asc.sh
We want to parallelise the "Build Artifacts" job, and after all those jobs are done, we can generate release metadata. So generating release metadata should be in its own job.
I've split Makefile migrations into separate commits to make reviews easier.
More information: https://www.notion.so/snyk/CLI-Speed-Up-Time-to-Build-in-CI-0d7ce418ecd14fa0bd8fac1ac391eea1
=> chore(ci): split release metadata from build job

src/lib/polling/common.ts, src/lib/polling/polling-monitor.ts, src/lib/polling/polling-test.ts, test/jest/unit/lib/ecosystems/common.spec.ts, test/jest/unit/lib/ecosystems/resolve-monitor.facts.spec.ts, test/jest/unit/lib/ecosystems/resolve-test-facts.spec.ts
- throw an error when the unmanaged c++ jobs are cancelled or contain error
=> fix: unmanaged cancelled jobs

src/cli/commands/test/iac/index.ts, test/jest/acceptance/iac/test-directory.spec.ts
Small regression that happened after we merged https://github.com/snyk/cli/pull/3239.
I had a refactor before merging and accidentally changed the line that stores all the failures, resulting in our scan showing just the last path's failures in the output.
I switched it back to store all failures in the for loop, so now we are going to see all of them in the output.
The test validates the behaviour.
for  `snyk-dev iac test test/fixtures/iac/terraform/ test/fixtures/iac/cloudformation/`, we will see all errors for both outputs:
=> fix: (iac) last error does not override previous

test/jest/acceptance/iac/custom-rules.spec.ts
Skipping this test suite as we see more and more flakes. These tests do network requests outside of our control, and we have decided to replace them with less brittle tests that test the API integration itself in https://snyksec.atlassian.net/browse/CFG-1847. 
We also test this scenario in other systems, less frequently.
In the meantime, we skip these to prevent the pipeline failing because of flakiness. It will also reduce the time of our acceptance tests:
=> test: disable iac oci registries tests

test/jest/acceptance/iac/iac-output.spec.ts, test/jest/acceptance/iac/test-directory.spec.ts
Adds tests for the old and new output to check scenarios of multiple paths, such as:
- three multiple paths - all successful
- two multiple paths - one successful, one non existent -> test that we have both results and failures
- the same scenarios with/without json, sarif flags 
The json,sarif flag scenarios are duplicate in the test-directory.spec.ts with a note "TODO" to delete them once the FF is removed and the new iac output is the default.
There is one test that I added and skiped: one that we have a success path and an invalid path for sarif.
This is an existing bug which was not introduced now. It was easy to add the test as I was adding the rest at the same time, but it is skipped until it's fixed in another PR. 
I added it here for visibility and documentation in the meantime, …
=> test: add multiple paths json,sarif cases

.circleci/config.yml
=> chore(ci): ignore v2 macos code signing errors

src/lib/formatters/iac-output/v2/test-summary.ts, test/jest/acceptance/iac/iac-output.spec.ts, test/jest/unit/lib/formatters/iac-output/v2/test-summary.spec.ts
- Removes the `Invalid files` count from the `Test Summary` section.
```
src/lib/formatters/iac-output/v2/test-summary.ts
```
- Execute the IaC test with the following command:
```
SNYK_IAC_OUTPUT_V2=true snyk-dev iac test
```
- Ensure the `Test Summary` section does not include the `Invalid files` count.
Following the discussion in [this Slack thread](https://snyk.slack.com/archives/C030UA3U1RB/p1653229220797339), it’s been decided that due to the currently ambiguous terminology in the IaC test results, the failure-based counts will not be added to the Test Summary section for the MVP, but rather added later once the flow implementation around multiple paths is refined.
For now, we’d like to remove the Invalid files count from the Test Summary section.
- …
=> chore: Removed the `Inalid files` count from the `Test Summary` section [CFG-1873]

src/cli/commands/test/iac/local-execution/file-scanner.ts, src/cli/commands/test/iac/local-execution/index.ts, test/jest/unit/iac/file-scanner.spec.ts, test/jest/unit/iac/index.spec.ts
-  [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules
This PR adds validation for issues generated from custom rules. This enhances the current custom rule behaviour (e.g. if a custom had a type in `severity` then the CLI would throw a random error, but now we tell them about the problem) and prepares us for when we will store these issues in our database using the `--report` flag. 
- In `src/cli/commands/test/iac/local-execution/file-scanner.ts`, we added a new function `validateResultFromCustomRules`, which contains the validation
- In the same file, the `scanFiles` function now returns an extra array, `failedScans`, that contains custom rules that failed the scanning; we chose to put this code here because it doesn't fit well in `processResults`, …
=> feat: validate custom rules [CFG-1865]

package-lock.json, package.json
See https://github.com/snyk/snyk-mvn-plugin/pull/126
Fixing a bug when scanning Maven projects with nested aggregate projects when the project identity was incorrectly set.
=> fix: maven nested module scans

test/acceptance/fake-server.ts
Removing a very old FF that is not used anymore in the code and is also getting removed from registry flags. We don't need it in the fake-server.ts at all.
=> chore: remove unused FF from code

src/cli/commands/test/iac/index.ts, src/lib/errors/formatted-custom-error.ts, src/lib/errors/index.ts, src/lib/errors/legacy-errors.js, src/lib/formatters/iac-output/index.ts, src/lib/formatters/iac-output/v2/failures/index.ts, src/lib/formatters/iac-output/v2/failures/list.ts, src/lib/formatters/iac-output/v2/index.ts, test/jest/acceptance/iac/iac-output.spec.ts
- Implements the new test failure message format, according to [this design](https://www.figma.com/file/buNFZqr1Uhf4SaifHw4WXE/Snyk-IaC-CLI?node-id=1684%3A15297).
```
src/cli/commands/test/iac/index.ts
```
- This review includes a new class called `FormattedCustomError`, which extends `CustomError`. This class can shift user message formatting from the CLI's error handling middleware, to the error class. The class adds a boolean flag called `isFormatted`, which is set to `true`. This indicates to the error handling middleware whether or not to format the user message.
- The change above was inspired by [this PR comment](https://github.com/snyk/cli/pull/3218#discussion_r868306574).
- For errors that are related to the flow, and not particular paths, such as initializing the local cache, …
=> chore: Implement new test failure message [CFG-1861]

.circleci/config.yml
It seems like "Build" jobs still start even when the required "Version" job has been filtered. This causes issues as we expect there to be a "binary-releases/version" file for later jobs.
To fix this and unblock pipelines, I've reordered "Version" so the "Build" jobs only require "Version".
=> chore(ci): fix build job dependencies

help/cli-commands/apps.md, src/lib/apps/constants.ts
Replaces any reference to `apps:beta` scope and updates it with allowed scopes. Along with minor corrections to docs.
`apps:beta` scope for Snyk Apps was used when we were in the beta phase. It has now been replaced with general scopes.
[MOOSE-509](https://snyksec.atlassian.net/browse/MOOSE-509?atlOrigin=eyJpIjoiYzg1NTlkYjkwMmJmNDhjZDg0MjY5OGNlZmMzOTkwZDciLCJwIjoiaiJ9)
=> chore: remove reference to apps beta scope for app creation

README.md, docker/README.md
Nudge users towards https://github.com/snyk/snyk-images instead of the Docker images in this repository
=> Recommend snyk/snyk docker images instead of snyk/snyk-cli

package-lock.json, package.json
Upgrade `snyk-docker-plugin` to its latest version, that supports
scanning WAR files inside the image, and find nested JAR files within
these WAR archives.
[MYC-109](https://snyksec.atlassian.net/browse/MYC-109)
=> feat: detect JARs in WARs files inside containers [MYC-109]

src/lib/formatters/iac-output/v2/issues-list/issue.ts, test/jest/unit/lib/formatters/iac-output/v2/issues-list/index.spec.ts
- Adds an underline below security rule documentation URLs
src/lib/formatters/iac-output/v2/issues-list/issue.ts
- Run `snyk-dev iac test` and ensure security rule documentation URLs are underlined.
- Run `snyk-dev iac test` with issues generated from custom rules and ensure the `Rule` property was not affected for them.
- [Slack thread](https://snyk.slack.com/archives/C030UA3U1RB/p1653983832072149)
- Before
- After
- After with custom rules:
=> chore: Added underline for docs URL

src/cli/commands/test/iac/index.ts, src/cli/commands/test/iac/local-execution/index.ts, src/cli/commands/test/iac/local-execution/measurable-methods.ts, src/cli/commands/test/iac/local-execution/process-results/index.ts, src/cli/commands/test/iac/local-execution/process-results/v1/extract-line-number.ts, src/cli/commands/test/iac/local-execution/process-results/v1/index.ts, src/cli/commands/test/iac/local-execution/process-results/v1/policy.ts, src/cli/commands/test/iac/local-execution/process-results/v1/results-formatter.ts, src/cli/commands/test/iac/local-execution/process-results/v1/share-results-formatter.ts, src/cli/commands/test/iac/local-execution/process-results/v1/share-results.ts, src/cli/commands/test/iac/local-execution/process-results/v2/cli-share-results.ts, src/cli/commands/test/iac/local-execution/process-results/v2/extract-line-number.ts, src/cli/commands/test/iac/local-execution/process-results/v2/index.ts, src/cli/commands/test/iac/local-execution/process-results/v2/policy.ts, src/cli/commands/test/iac/local-execution/process-results/v2/results-formatter.ts, src/cli/commands/test/iac/local-execution/process-results/v2/share-results-formatter.ts, src/cli/commands/test/iac/local-execution/process-results/v2/share-results.ts, src/cli/commands/test/iac/scan.ts, test/jest/unit/iac/index.spec.ts, test/jest/unit/iac/process-results/policy.spec.ts, test/jest/unit/iac/process-results/results-formatter.spec.ts, test/jest/unit/iac/process-results/share-results-formatters.spec.ts
This PR changes the behaviour of the `iac test` command when multiple paths are passed on the command line. This PR changes the behaviour of the `--report` flag, too. The implemented behaviour is the following:
- `iac test` recursively scans the current working directory by default.
- If one or more paths are passed on the command line, those paths must be relative to the current working directory.
- If one or more paths are passed on the command line, only those files or directories are scanned. If a path is a directory, it will be recursively scanned.
- If the `--report` flag is used, the `iac test` command creates one project group in the platform named after the name of the current working directory.
- If the current working directory is a Git repository, additional information will …
=> refactor: create only one project group per execution

src/cli/commands/test/iac/local-execution/rules/rules.ts, src/lib/formatters/iac-output/index.ts, src/lib/formatters/iac-output/v2/index.ts, src/lib/formatters/iac-output/v2/user-messages.ts, test/jest/acceptance/iac/custom-rules.spec.ts
This commits removes the warning message we used to display when running `snyk iac test --report`, with custom rules (local or remote ones).
We now support custom rules when sharing results to the platform, so we remove this message.
CFG-1868
The ticket can be verified using https://github.com/snyk/custom-rules-examples/
- Install snyk-iac-rules: https://github.com/snyk/snyk-iac-rules
- Build a local bundle: snyk-iac-rules build
- Run the rules to see them in the results: snyk iac test ./rules/CUSTOM-RULE-1/fixtures --rules=bundle.tar.gz 
- Run the rules and send them to the Platform: snyk-dev iac test ./rules/CUSTOM-RULE-1/fixtures --rules=bundle.tar.gz --report 
- Check that no warning message appears now.
Note: You will not see the issues from custom rules populated in the Snyk …
=> fix: remove warning message for custom rules from iac --report

src/cli/commands/test/iac/v2/index.ts, src/cli/commands/test/index.ts, test/jest/acceptance/iac/experimental.spec.ts
This PR adds a divergion from the existing flow to the new flow (TBC) for the UPE integration.
The code currently does nothing. this commit just prepares the directory structure. I added a dummy message for fun :) It can be deleted on the next commit.
I have named the directory v2 but it's open to renaming as we progress with building up this flow.
Also included a simple acceptance test to prove the point of the feature flag and command flag. We can refactor and use this later, when we have actual code. 
follow the same scenarios as the acceptance test.
- with FF on and --experimental
- with FF on , without --experimental
- with FF off, and --experimental
- with FF off, without --experimental
- with typos on the command flag
=> chore: add condition to diverge to new flow for iac [CFG-1816]

src/lib/formatters/iac-output/v2/issues-list/issue.ts
- Fixes the issue's `Info` property to display the expected information when either the issue's description, issue's impact or both are missing. This is especially relevant for issues generated by custom rules, in which these fields are not required.
src/lib/formatters/iac-output/v2/issues-list/issue.ts
- Generate a custom rules bundle in which one of the custom rules lacks the description, another lacks the impact, and another lacks both.
- Use the `snyk-dev iac test` command to test IaC files which would generate issues from these custom rules.
- Ensure that an issue's `Info` property:
- When only the issue's description is missing - The issue's impact is displayed.
- When only the issue's impact is missing - The issue's description is displayed.
- Weh both the issue's description and …
=> fix: IaC issue info when impact or description are missing

package-lock.json, package.json, test/jest/acceptance/snyk-container/container.spec.ts, webpack.common.ts
Notes: https://www.notion.so/snyk/snyk-docker-plugin-sqlite-js-troubleshooting-f6e48ae3da3449c3be819a69b84fbf5e
I'm unable to use `fakeServer` for the test as there's some API which needs to be stubbed. We can revisit and improve this if these tests become unreliable. We can't completely mock out external services anyway as we need access to a Docker base image.
Tests on Windows are skipped as there's no Windows-compatible image we can test against. (If we find one, we can use it)
=> feat: upgrade to snyk-docker-plugin@4.38.0

src/cli/commands/test/iac/local-execution/types.ts, src/cli/commands/test/iac/v2/index.ts, src/cli/commands/test/iac/v2/rules.ts, test/jest/unit/iac/v2/rules.spec.ts
This PR adds the logic to locate a rules bundle based on user input and falling back to the local cache if none is found. Please note that, once the bundle is located, the path is currently printed to the console. This is not going to be the final behaviour, but there is no consumer of the bundle path at the moment.
The bulk of the logic is in `src/cli/commands/test/iac/v2/rules.ts`.
Enable the `iacCliUnifiedEngine` and run `snyk` with different arguments.
Use the bundle provided by the user:
```
SNYK_IAC_BUNDLE_PATH=test/fixtures/iac/custom-rules/custom.tar.gz snyk iac test --experimental
```
Use the bundle from the cache (your system cache might be at a different path):
```
mkdir -p ~/Library/Caches/snyk-nodejs/iac
cp test/fixtures/iac/custom-rules/custom.tar.gz …
```
=> chore: locate rules bundle in iac test v2

src/cli/commands/test/iac/local-execution/rules/rules.ts, src/cli/commands/test/iac/scan.ts, src/lib/formatters/iac-output/index.ts, src/lib/formatters/iac-output/v2/index.ts, src/lib/formatters/iac-output/v2/user-messages.ts, test/jest/acceptance/iac/custom-rules.spec.ts, test/jest/unit/iac/rules/rules.spec.ts
In https://github.com/snyk/cli/pull/3287, we removed the warning for custom rules completely, but we were meant to only remove it if the feature flag is enabled. 
Have a look at the previous PR and notice the added feature flag check in this PR. 
The ticket can be verified using https://github.com/snyk/custom-rules-examples/
- Install snyk-iac-rules: https://github.com/snyk/snyk-iac-rules
- Build a local bundle: `snyk-iac-rules build`
- Run the rules to see them in the results: `snyk iac test ./rules/CUSTOM-RULE-1/fixtures --rules=bundle.tar.gz `
- Run the rules and send them to the Platform: `snyk-dev iac test ./rules/CUSTOM-RULE-1/fixtures --rules=bundle.tar.gz --report`
- Check that no warning message appears now.
=> fix: include the custom rules warning if feature flag is not enabled [CFG-1868]

src/cli/args.ts, src/cli/commands/test/iac/local-execution/types.ts, src/cli/commands/test/iac/v2/index.ts, src/lib/config.ts, src/lib/iac/drift/driftctl.ts, src/lib/iac/file-utils.ts, src/lib/iac/test/v2/index.ts, src/lib/iac/test/v2/setup/index.ts, src/lib/iac/test/v2/setup/policy-engine.ts, src/lib/iac/test/v2/setup/rules.ts, src/lib/iac/test/v2/types.ts, test/jest/acceptance/iac/experimental.spec.ts, test/jest/unit/lib/iac/test/v2/setup/policy-engine.spec.ts, test/jest/unit/lib/iac/test/v2/setup/rules.spec.ts
- Adds logic for locating the UPE executable, which currently needs to be available locally. At a later stage, we will add a downloading step for when the executable is not cached locally.
- Refactors the pre-test step according to [this proposal](https://snyk.slack.com/archives/C02JMMTLUF9/p1655040737968789).
src/lib/iac/test/v2/setup/policy-engine.ts
- Ensure the `iacCliUnifiedEngine` FF is activated.
- Prepare the UPE executable.
- Place it in your CLI's cache directory.
- Run `snyk-dev iac test --experimental -d`
- Ensure the debug logs include `Using cached UPE binary: <path-to-cached-upe>`
- Run `SNYK_IAC_UPE_PATH=<custom-upe-path> snyk-dev iac test --experimental -d`, with a customized path to a UPE executable.
- Ensure the debug logs include `Custom IaC UPE binary path detected in …
=> chore: Locate UPE Executable [CFG-1846]

.github/workflows/cli-alert.yml
Mainly for debugging changes in PRs without setting up some complex trigger using filters.
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
=> chore(ci): allow running cli-alert check manually

cliv2/internal/cliv2/cliv2.go, cliv2/internal/cliv2/cliv2_test.go
When creating the environment variables for CLIv1 invocation ensure to override existing ones and not only append environment variables.
Affected Environment Variables are:
* HTTP_PROXY
* HTTPS_PROXY
* NODE_EXTRA_CA_CERTS
It ensures that environment variables are unique and that there is no possible conflict/uncertainty between externally defined and internally set environment variables when being passed to CLIv1.
Run CLIv2 with --debug and use the following environments for testing:
* HTTP_PROXY: 
env: `SNYK_HTTP_PROTOCOL_UPGRADE=0 SNYK_API=http://snyk.io/api/v1 HTTP_PROXY=http://127.0.0.1:3128` 
expected: `dial tcp 127.0.0.1:3128: connect: connection refused`
* HTTPS_PROXY: 
env: `HTTPS_PROXY=https://127.0.0.1:312`
expected: `dial tcp 127.0.0.1:3128: connect: connection refused`
* …
=> chore: override env variables instead of appending

test/smoke/spec/snyk_code_spec.sh, test/smoke/spec/snyk_monitor_spec.sh, test/smoke/spec/snyk_test_spec.sh, test/smoke/spec/spec_helper.sh
Node 12 support is deprecated, will still support it so we still want tests.
However, we expect stderr output for it, unlike other versions, since we show deprecation warnings.
=> test: ignore node 12 deprecation warnings in assertions

package-lock.json, package.json
Upgrade python plugin version to add support for requirements.txt files with BOM encoding
=> feat: add support for requirements.txt files with BOM encoding

src/cli/commands/test/iac/local-execution/types.ts, src/cli/commands/test/iac/v2/index.ts, src/cli/commands/test/index.ts, src/lib/iac/test/v2/index.ts, src/lib/iac/test/v2/scan.ts, src/lib/iac/test/v2/setup/index.ts, src/lib/iac/test/v2/setup/policy-engine.ts, src/lib/iac/test/v2/setup/rules.ts, src/lib/iac/test/v2/types.ts, test/jest/acceptance/iac/experimental.spec.ts
This PR updates the experimental `iac test` command to execute `snyk-iac-test`, passing to it the rules bundle and the paths to be scanned. The experimental command collects and parses the standard output of the executable, and collects its standard error to be printed to a debug logger.
Follow the flow from `src/cli/commands/test/iac/v2/index.ts`. The execution of `snyk-iac-test` is in `src/lib/iac/test/v2/scan.ts`.
Set the environment variables to point to the engine and the bundle:
```
export SNYK_IAC_POLICY_ENGINE_PATH=...
export SNYK_IAC_BUNDLE_PATH=...
```
Make sure you have the `iacCliUnifiedEngine` feature flag enabled, and invoke the command like this:
```
snyk iac test --experimental
```
[CFG-1896](https://snyksec.atlassian.net/browse/CFG-1896)
=> chore: scan IaC files with the Policy Engine

.circleci/config.yml, CONTRIBUTING.md
We used "v2" in the branch name to toggle CLIv2 pipelines. However this is too generic as other things can be "v2". "cliv2" is more specific and inline with how we name CLIv2 in various places (directories, modules).
=> chore(ci): rename cliv2 toggle keyword

src/cli/commands/test/iac/v2/index.ts, src/lib/iac/drift/driftctl.ts, src/lib/iac/file-utils.ts, src/lib/iac/test/v2/setup/index.ts, src/lib/iac/test/v2/setup/local-cache/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/lookup-local.ts, src/lib/iac/test/v2/setup/local-cache/rules.ts, src/lib/iac/test/v2/types.ts, test/jest/unit/lib/iac/drift.spec.ts, test/jest/unit/lib/iac/test/v2/setup/local-cache/index.spec.ts, test/jest/unit/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.spec.ts, test/jest/unit/lib/iac/test/v2/setup/local-cache/policy-engine/lookup-local.spec.ts, test/jest/unit/lib/iac/test/v2/setup/local-cache/rules.spec.ts
- Fixes the locally cached Policy Engine executable name.
- Adds a local cache initialization step to the test setup which:
- Wraps the logic for initializing the rules bundle and the Policy Engine executable.
- Ensures the IaC local cache directory exists.
- Replaces the specific cache paths for the Policy Engine executable and the rules bundle with an IaC cache path, as it's enough for the former two can be calculated with it.
- The only logic piece this PR should change, is the name of the locally cached Policy Engine executable the CLI will look for.
- Ensure the IaC test v2 tests still pass.
- Ensure the test files are structured correctly following the refactor.
- Ensure the IaC test v2 flow still behaves the same as before.
- The refactor in this PR was extracted from #3327, where …
=> refactor: IaC test v2 setup

cliv2/internal/cliv2/cliv2.go, cliv2/internal/cliv2/cliv2_test.go, cliv2/internal/utils/array.go
avoid accidental and purposeful redirecting of traffic between cliv1 and cliv2
Based on the environment variables used on CLIv1 to determine proxy usage or not, this PR tries to ensure that these environment variables can't be specified to redirect traffic between CLIv1 and CLIv2.
See https://github.com/Rob--W/proxy-from-env/blob/master/index.js#L42
Normally whitelisting would be preferable but it might be more difficult to determine which environment variables are actually required. Missing out on any would cause subtle errors, difficult to track down, so blacklisting is used here for now.
Also no performance optimizations are applied following [Beware of Optimizations!](https://clean-code-developer.com/grades/grade-1-red/#Beware_of_Optimizations)
Run cliv2 and set the environment …
=> chore: override no_proxy from parent env before launching cliv1

src/lib/ecosystems/resolve-test-facts.ts, test/jest/unit/lib/ecosystems/resolve-test-facts.spec.ts
Fix wrong dependencyCount value in support of snyk-to-html
https://github.com/snyk/snyk-to-html/blob/master/README.md
Run the following commands in the folder of unmanaged project/repo:
to create vulnerability test for unmanaged project/repo:
path_to_git/cli/bin/snyk test --json --unmanaged | path_to_git/snyk-to-html/dist/index.js -o result.json
to build HTML report of received test resluts:
path_to_git/snyk-to-html/dist/index.js -i result.json -o result.html
[Jira ticket TUN-27](https://snyksec.atlassian.net/browse/TUN-27)
=> fix: wrong dependencyCount in support of snyk-to-html

src/cli/commands/test/iac/index.ts, src/cli/commands/test/iac/output.ts
This PR moves all the code responsible for building the output of the `iac test` command into its own module. This PR doesn't modify the functionality of the command.
=> refactor: extract the output logic to its own module

package-lock.json, package.json
This PR bumps the snyk-gradle-plugin version to include a change that reduces the amount of logging coming from the Gradle sub-process. Most of the logs are now only visible in debug mode.
Several customers are seeing rangeErrors when max string length is exceeded due to excessive logging. Reducing default logging should help.
[TARDIS-994](https://snyksec.atlassian.net/browse/TARDIS-994)
=> fix: reduce default snyk-gradle-plugin logging

src/cli/commands/test/iac/local-execution/types.ts, src/lib/iac/file-utils.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/download.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/index.ts, src/lib/iac/test/v2/setup/local-cache/utils.ts, test/jest/unit/lib/iac/test/v2/setup/local-cache/policy-engine/download.spec.ts, test/jest/unit/lib/iac/test/v2/setup/local-cache/policy-engine/index.spec.ts, test/jest/unit/lib/iac/test/v2/setup/local-cache/utils.spec.ts
- Adds abstract logic for downloading cache resources for the IaC test flow.
- Adds logic for downloading the Policy Engine executable when it is not cached locally.
- Ensure the binary is not cached locally.
- Ensure you have the `iacCliUnifiedEngine` FF activated.
- Run `snyk iac test --experimental`
- Ensure the flow finishes successfully without errors.
- The step after achieving [CFG-1890: UPE CLI Integration - Milestone #0](https://snyksec.atlassian.net/browse/CFG-1890) is to stop relying on a UPE binary that will be available locally and instead download it, this will enable us to achieve  [CFG-1891: Milestone #1](https://snyksec.atlassian.net/browse/CFG-1891).
- [CFG-1885](https://snyksec.atlassian.net/browse/CFG-1885)
=> chore: Implement UPE executable downloading

package-lock.json, package.json, src/lib/iac/file-utils.ts
In https://github.com/snyk/cli/pull/3347 we refactored the `isArchive` function and used `promisify` to make the function async.
In addition to that, we've started to use a new types package named `@types/tar` that added types support of the `tar` package that is being used in the `isArchive` function.
When testing the refactored functionality we found a bug that we didn't catch when working on the PR, the function threw the following error:
```
TypeError: callback not supported for sync tar functions
```
The cause of the error is the `sync: true` option that we used in the function `tar.list`, `promisfy` couldn't use the callback functionality of the function when it was being run as a sync function.
The problem was that the `@types/tar` package didn't let us run the function without …
=> fix: isArchive()

src/cli/commands/test/iac/local-execution/types.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/download.ts, src/lib/iac/test/v2/setup/local-cache/rules-bundle/download.ts, src/lib/iac/test/v2/setup/local-cache/rules-bundle/index.ts, test/jest/unit/lib/iac/test/v2/setup/local-cache/rules-bundle/download.spec.ts
This PR adds the ability to download the Snyk rules bundle from `https://static.snyk.io/cli/wasm/bundle-experimental.tar.gz` and save it to the user's local cache.
1. Ensure that the `iacCliUnifiedEngine` FF is enabled for your org
2. Run the command `snyk-dev iac test --experimental`
3. Open your local cache and check that the `bundle-experimental.tar.gz` file was downloaded successfully
https://snyksec.atlassian.net/browse/CFG-1886
=> feat: download rules bundle

src/cli/commands/test/iac/index.ts, src/cli/commands/test/iac/output.ts, src/lib/formatters/iac-output/v2/index.ts, src/lib/formatters/iac-output/v2/share-results.ts, src/lib/formatters/iac-output/v2/utils.ts, test/jest/unit/lib/formatters/iac-output/v2/share-results.spec.ts
This PR improves the discoverability of the `--report` flag when used with the `iac test` command. In particular:
- It adds a suggestion to use the `--report` flag is the user doesn't specify it.
- It improves the message the user receives when he uses `--report`.
- It adds a suggestion regarding sharing of custom rules.
Run the command without the `--report` flag. You will se a tip at the end of the output.
Run the command with the `--report` flag. You will see an improved message about the location of the shared results.
Run the command with the `--report` flag and with a custom rules bundle. If you have the `iacCustomRulesEntitlement` entitlement, but you don't have the `iacShareCliResultsCustomRules` feature flag, you will see a message in the share results section: …
=> chore: improve the discoverability of the --report flag

src/lib/formatters/iac-output/v2/utils.ts
- Changes white texts in the new IaC test output to be in the CLI's default text color.
```
src/lib/formatters/iac-output/v2/utils.ts
```
- Ensure the test output hasn't changed apart from white texts being converted to texts in the default color.
- Using a terminal with a bright bg, ensure all texts are visible.
- Using a terminal with a dark bg, ensure all texts are visible.
- At the moment, users with a light terminal background will not be able to see most of the headers in our output. 
- No tickets.
Before: 
After:
- [Slack thread on #iac-config-team](https://snyk.slack.com/archives/C02JMMTLUF9/p1656314579867429)
- [Slack thread on #ask-team-hammer](https://snyk.slack.com/archives/C0127HWU0E7/p1656316284434559)
=> refactor: Remove white texts from IaC test output

.github/CODEOWNERS, src/cli/main.ts, src/lib/formatters/test/format-test-results.ts, test/fixtures/container-app-vulns/resultJsonDataGrouped.json, test/fixtures/container-app-vulns/resultJsonDataNonGrouped.json, test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts, test/jest/unit/lib/formatters/test/format-test-results.spec.ts
We want to support scanning app vulns by default. Before we can do that,
we have to support JSON response without the `experimental` flag, and
without creating any breaking changes for existing users. The solution
is to add another field `applications` to the response object, which
will contain all of the app vulns results.
https://snyksec.atlassian.net/browse/MYC-101
=> feat: container json response with app vulns

src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/download.ts
Upgrade `snyk-iac-test` to v0.3.0.
=> chore: upgrade snyk-iac-test to v0.3.0

config.default.json, src/cli/commands/auth/index.ts, src/lib/code-config.ts, src/lib/config/api-url.ts, src/lib/config/index.ts, test/jest/acceptance/snyk-config/snyk-config-endpoint.spec.ts, test/jest/unit/config/api-url.spec.ts, test/jest/unit/lib/endpoint-config-test.spec.ts, test/jest/unit/policy-display.spec.ts, test/smoke/spec/spec_helper.sh, test/tap/display-test-results.test.ts
Allright, over 300 lines, but the change is actually not that big.
**Goal is to allow users to set a single configuration option pointing to an API endpoint and let CLI figure out the rest.**
With the REST API being the main (and only) API path used in the near future, I think it make sense to settle on the **default as `https://api.snyk.io/rest/` as per https://apidocs.snyk.io**
For example:
```console
SNYK_API=https://api.custom-domain.dev snyk test
```
Additional benefits introduced in this PR:
- making a hierarchy of envvar vs. config option a bit clearer and communicated to the user
- better error AND debug messages for all options (currently we don't show these!)
- no need to configure any other envvar/option by default. But still offer an override for local development and specific …
=> Improve API URL configuration behavior

src/cli/commands/test/iac/local-execution/file-loader.ts, src/cli/commands/test/iac/local-execution/index.ts, src/cli/commands/test/iac/local-execution/parsers/terraform-file-parser.ts, src/cli/commands/test/iac/local-execution/yaml-parser.ts, src/cli/commands/test/iac/scan.ts, test/fixtures/iac/only-invalid/invalid-file1.yml, test/fixtures/iac/only-invalid/invalid-file2.yaml, test/jest/acceptance/iac/iac-output.spec.ts, test/jest/acceptance/iac/test-directory.spec.ts
This commit adds a filename attribute to the CustomErrors that need to keep the filename(path) information.
Next, if the scan is complete, and we have 0 parsed files but some failed files (>0),  we will throw these errors in an array.
As a last step we destructure the array of errors and get the filename(path) information in the results.
This is a "quick" fix which might make the code uglier, but as we will get rid of the entire area in the upcoming weeks, we do not think it's worth the effort of refactoring it now to fix it properly.
CFG-2026
Directory with 1 bad file: Before (left) and After (right)
Directory with 2 bad files: Before (left) and After (right)
we also now return all errors when using --json: 
Multiple paths:
Directory without files or with non-iac files (same behaviour …
=> fix: return paths for files that errrored (IaC) [CFG-2026]

test/jest/acceptance/iac/test-directory.spec.ts
Fixes a windows test. we do not need to actually assert on all paths, as long as the results are 2 and we have different tests that check the paths themselves.
=> chore: fix windows tests

src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts
Upgrade `snyk-iac-test` to v0.4.2.
=> chore: upgrade snyk-iac-test

package-lock.json, package.json, src/cli/commands/test/iac/local-execution/yaml-parser.ts, test/fixtures/iac/only-invalid/invalid-file1.yml, test/fixtures/iac/only-invalid/invalid-file2.yaml
Updates the CLI with a new version of our `cloud-config-parser`. This release includes a change in the way we parse YAML documents. 
We used to throw an error when finding escape characters like "\\/", but this is a valid YAML in YAML 1.2 so we removed this error in our parser. https://github.com/snyk/cloud-config-parser/pull/45
- Take the example from the zip file.
- Run `snyk iac test invalid-file1.yml`
- See the error for no valid YAML file
- Build the CLI locally on this branch
- Run ` node ./dist/cli iac test invalid-file1.yml` again, you will now see that the file is parsed (but not valid iac)
Files to test:
- A non-iac file, previously invalid YAML: [invalid-file1.yml.zip](https://github.com/snyk/cli/files/9070795/invalid-file1.yml.zip)
- An iac file, always invalid YAML: …
=> chore: bump cloud-config-parser [cfg-2016]

src/lib/formatters/iac-output/v2/formatters.ts, src/lib/formatters/iac-output/v2/issues-list/index.ts, src/lib/formatters/iac-output/v2/issues-list/issue.ts, src/lib/formatters/iac-output/v2/issues-list/types.ts, src/lib/iac/test/v2/output.ts, test/jest/unit/iac/process-results/fixtures/new-output-formatted-results.json, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-test-data.json, test/jest/unit/lib/formatters/iac-output/v2/issues-list/index.spec.ts
- Adds line numbers to the human-readable test output format **only** for `snyk-iac-test`, based on [this design](https://www.figma.com/file/buNFZqr1Uhf4SaifHw4WXE/Snyk-IaC-CLI).
```
src/lib/formatters/iac-output/v2/issues-list/issue.ts
```
- Run `snyk-dev iac test`
- Ensure results **do not have** line numbers.
- Activate the `iacCliUnifiedEngine` feature flag.
- Run `snyk-dev iac test --experimental`
- Ensure results **have** line numbers.
- For the local-execution test flow, it’s been decided that since the current line number calculation is not accurate enough, we will not include it in this flow’s test output.
- For the `snyk-iac-test` test flow, we receive accurate line numbers from `snyk-iac-test`, which we can include in the test output.
- The design for the test output with line …
=> chore: Add line numbers to test output [CFG-2055]

package-lock.json, package.json, src/cli/commands/monitor/index.ts, src/cli/commands/test/index.ts, test/tap/cli-monitor.acceptance.test.ts, test/tap/cli-test/cli-test.docker.spec.ts
We had issues with Go modules not being detected. Version 5.0.1 of
`snyk-docker-plugin` should fix those issues.
This commit includes a workaround since we have a blocked PR (#3433) for
making app vulns the default using the lates version of
`snyk-docker-plugin`. Until we are able to make scanning app vulns the
default, we need to make sure that we set `exclude-app-vulns` option
when a user doesn't set the `app-vulns` option.
https://snyksec.atlassian.net/browse/MYC-131
=> fix: bump snyk docker plugin version golang fixes

src/lib/formatters/iac-output/v2/test-summary.ts, test/jest/acceptance/iac/iac-output.spec.ts, test/jest/unit/lib/formatters/iac-output/v2/test-summary.spec.ts
- Adds the project name property to the test summary section of the test output.
```
src/lib/formatters/iac-output/v2/test-summary.ts
```
- Run `snyk-dev iac test`.
- Ensure the correct project name is displayed in the test summary section of the output.
- Ensure the project name is aligned with [the design](https://www.figma.com/file/buNFZqr1Uhf4SaifHw4WXE/Snyk-IaC-CLI?node-id=2626%3A1145).
Following the recent changes introduced by [CFG-1973: Switch to the new scanning and project grouping behavior](https://snyksec.atlassian.net/browse/CFG-1973), which activates the new project grouping behavior, any IaC test will result in a single project name.
We would like to include this project’s name in the output.
- [CFG-2013](https://snyksec.atlassian.net/browse/CFG-2013)
=> chore: Add project name to test summary [CFG-2013]

src/cli/commands/test/iac/local-execution/types.ts, src/lib/iac/test/v2/errors.ts, src/lib/iac/test/v2/output.ts, test/jest/unit/lib/iac/test/v2/errors.spec.ts
This PR adds error handling for `snyk-iac-test` errors that were added in https://github.com/snyk/snyk-iac-test/pull/24 and in addition to that it prints the relevant errors.
1. run `snyk-dev iac test .. --experimental`
2. receive a "No valid paths were provided" error
3.  run `snyk-dev iac test {invalid_file} --experimental`
4. receive an invalid file error
https://snyksec.atlassian.net/browse/CFG-1997
https://snyksec.atlassian.net/browse/CFG-2025
=> feat: snyk-iac-test error handling

src/cli/main.ts, src/lib/errors/nested-custom-error.ts
- A PoC for improving error handling for chained errors, including:
- Chaining error stacks in debug logs.
- Ensuring the original user message is displayed.
```
src/lib/errors/nested-custom-error.ts
```
- The initial idea was to use the optional `cause` property for the `Error` constructor, but following [this discussion](https://snyk.slack.com/archives/C0127HWU0E7/p1656493212716839), it was agreed that since it was only introduced in the latest `Node.js` versions, we cannot apply it for this implementation. Instead, we made our own implementation to mimic the behavior.
- To prevent any unexpected behaviors with the existing errors, I've introduced a new error class, called `NestedCustomError`.
- The new properties introduces with `NestedCustomError` are:
- `nestedName`: Gets the …
=> chore: Error handling PoC

src/cli/commands/test/iac/local-execution/process-results/cli-share-results.ts, test/acceptance/fake-server.ts
While investigating https://snyk.zendesk.com/agent/tickets/26894, we noticed that client errors (e.g. HTTP 422) from the IaC share-results endpoint are not communicated to the CLI caller at all.
Example error returned in prod-registry that is not surfaced to users (example with non english chars in tag, but this can be caused by any non Az09 characters):
`snyk iac test test/fixtures/iac/terraform/var_deref/nested_var_deref/ --project-tags=client=nαδαδσδαomnom,Team=Cloud --report`
```
InvalidUserInputError: invalid tag value: contains invalid characters
at assertValidValue (/srv/app/dist/lib/tags/validation.js:36:15)
at assertValidFields (/srv/app/dist/lib/tags/validation.js:50:34)
at parse (/srv/app/dist/web/routes/project/tags/parse.js:17:38)
at …
```
=> fix: handle errors from /share-results [CFG-2028]

src/lib/config/index.ts, src/lib/display-policy.ts, src/lib/formatters/legacy-format-issue.ts, src/lib/formatters/remediation-based-format-issues.ts, src/lib/spotlight-vuln-notification.ts, test/acceptance/workspaces/pip-app-transitive-vuln/cli-output-actionable-remediation.txt, test/acceptance/workspaces/pip-app-transitive-vuln/cli-output.txt, test/fixtures/snyk-config-no-version/expected, test/jest/unit/policy-display.spec.ts, test/smoke/spec/snyk_test_spec.sh, test/tap/cli-test/cli-test.docker.spec.ts, test/tap/display-test-results.test.ts
Updates URL links for vulns in the CLI output to point to security.snyk.io, the new snyk vulnerability db which generally has better UX and more info than the legacy site the links are currently pointing to.
=> Feat/update vuln urls to point to security.snyk.io

src/lib/formatters/iac-output/v2/formatters.ts, src/lib/iac/test/v2/output.ts, test/jest/unit/cli/commands/test/iac/v2/index.spec.ts, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-test-data.json, test/jest/unit/lib/formatters/iac-output/v2/formatters.spec.ts
This PR adds the test summary section to the `iac test` command when run with the `--experimental` flag.
The bulk of the implementation is in `src/lib/formatters/iac-output/v2/formatters.ts`.
Run a scan using a command similar to this:
```
snyk iac test test/fixtures/iac --experimental
```
You should see a test summary similar to the following at the end of the output:
```
Test Summary
Organization: francescomari
Project name: cli
✔ Files without issues: 10
✗ Files with issues: 1
Ignored issues: 0
Total issues: 1 [ 0 critical, 1 high, 0 medium, 0 low ]
```
[CFG-2024](https://snyksec.atlassian.net/browse/CFG-2024)
=> feat: add test summary section to the experimental output

src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts
Upgrade snyk-iac-test to v0.7.4
=> chore: upgrade snyk-iac-test to v0.7.4

src/lib/iac/drift/driftctl.ts
bump driftctl version to 0.35.2
this will fix https://snyksec.atlassian.net/browse/CTX-114
just updated version and shasum in drift.ts
running `snyk iac describe` should download driftctl new version
=> bump driftctl version to 0.35.2

.github/CODEOWNERS, src/lib/formatters/test/format-test-results.ts, test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts
In a recent [PR](https://github.com/snyk/cli/pull/3417) we released a new JSON structure for container tests with app vulns, eliminating the need for the `experimental` flag when doing so. Since some customers are still using the `experimental` flag and expect the output in the older format, we are reverting the JSON output for container app vulns to how it was when using the experimental flag.
https://snyksec.atlassian.net/browse/MYC-139
=> fix: container app vulns json with experimental flag

package-lock.json, package.json
This change bumps the snyk-gradle-plugin version to include a change that allows us to properly handle scanning Gradle projects using strict lock-mode.
[related snyk-gradle-plugin PR](https://github.com/snyk/snyk-gradle-plugin/pull/217)
=> fix: handle gradle strict lock mode

src/lib/iac/test/v2/json.ts, src/lib/snyk-test/iac-test-result.ts, test/jest/unit/iac/process-results/fixtures/experimental-json-output.json
- Omits `compliance` from issue data in the JSON format, by setting a hardcoded empty array instead.
- Run `snyk-dev iac test --json`
- Ensure the JSON output is valid, and that `compliance` is set to be an empty array.
- Activate the `iacCliUnifiedEngine` FF.
- Run `snyk-dev iac test --experimental --json`
- Ensure the JSON output is valid, and that `compliance` is set to be an empty array.
We started adding compliance information to rules as part of H1 plans to surface compliance information in the product. 
We started by adding the info to the metadata but have not yet decided how to present it best to the user. 
The CLI exposes raw rule metadata to the customer via the --json flag in the CLI.
This means partial and incomplete metadata is surfaced via the --json flag which has not been …
=> chore: Set hardcoded compliance value for JSON output

cliv2/Makefile, cliv2/jest.config.ts, cliv2/test/acceptance/proxy_authentication.spec.ts, cliv2/test/fixtures/kerberos/Dockerfile, cliv2/test/fixtures/kerberos/docker-compose.yml, cliv2/test/fixtures/kerberos/scripts/setup_kerberos.sh, test/acceptance/fake-server.ts, test/jest/util/createProject.ts, test/jest/util/startSnykCLI.ts
In this PR we introduce acceptance tests for proxy authentication implemented in CLIv2. The proxy authentication currently supports [SPNEGO based authentication](https://www.ietf.org/rfc/rfc4559.txt) and thereby mainly kerberos (all platforms) and NTLM (on Windows machines). 
The PR introduces a Docker based test environment spinning up a linux container hosting a Squid Proxy and a Kerberos KDC, with which the executable under test interacts.
Unfortunately due to limitations on our CircleCi Runners, the tests currently only run for linux builds.
The test suite can be found here cliv2/test/acceptance/proxy_authentication.spec.ts
=> test: kerberos/jest setup

src/lib/formatters/iac-output/v2/formatters.ts, src/lib/snyk-test/iac-test-result.ts, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-test-data.json, test/jest/unit/lib/formatters/iac-output/v1/index.spec.ts
- Adds the missing IaC issue properties to the JSON output:
- `references`
- `type`
- `policyEngineType`
```
src/lib/snyk-test/iac-test-result.ts
```
- Fixes the changes made in #3479
- [Relevant thread](https://snyk.slack.com/archives/CRV0PMFDH/p1658759532036059)
=> fix: Add missing IaC issue props in JSON output

src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts
This PR adds support for passing configuration to the `snyk-iac-test` executable. This PR includes in the configuration some values (org name, API endpoint and authorization header) that will be used in future changes to share results in `snyk-iac-test`.
The logic for this change is contained in `src/lib/iac/test/v2/scan/index.ts`.
This test is transparent to the user. Running `snyk iac test --experimental` should work as before. If you run that with the `-d` option, you should see a message from `snyk-iac-test` about finding the configuration:
```
2022/07/25 12:15:12 using config: /var/folders/1d/b93fm2nj567fn0bm8f5mlg6h0000gn/T/snyk-16nA3H/config.json
```
[CFG-2044](https://snyksec.atlassian.net/browse/CFG-2044)
=> feat: pass configuration to snyk-iac-test

src/lib/iac/test/v2/json.ts, test/jest/unit/iac/process-results/fixtures/experimental-json-output.json, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-results.json, test/jest/unit/lib/iac/test/v2/json.spec.ts
- Adding error objects to the JSON output of the new test flow, when a test produces both results and errors.
```
src/lib/iac/test/v2/json.ts
```
- Activate the `iacCliUnifiedEngine` FF for your org.
- Run `snyk-dev iac test --experimental --json <dir>`, where `<dir>` is a directory with both valid and invalid IaC files.
- Ensure the JSON output includes both test results for the valid files, and error objects for invalid files.
- Run `snyk-dev iac test --json <dir>, where `<dir`> is a directory with both valid and invalid IaC files.
- Ensure the JSON output still only includes test results for the valid files, without including error objects for invalid files.
- When running a scan that produces results (or in other words, when scanning valid IaC files) we will not output any of the …
=> chore: Add errors to results for JSON output [CFG-2036]

src/cli/commands/test/iac/scan.ts
- Adds a `projectRoot` property with the CWD path to the `CurrentWorkingDirectoryTraversalError` error.
- This PR was opened following this [#ask post](https://snyk.slack.com/archives/CRV0PMFDH/p1658920411524319) in which the error occurred during scans made by an IDE plugin.
=> chore: Added CWD path to out of CWD error message

src/lib/iac/test/v2/output.ts, test/jest/unit/cli/commands/test/iac/v2/index.spec.ts
- Fixes the exit code for the new IaC test flow to be `1` instead of `0`, as is expected by the Snyk CLI ([source](https://docs.snyk.io/snyk-cli/cli-reference#subcommands-of-cli-commands)).
```
src/lib/iac/test/v2/output.ts
```
- Run `snyk iac test` with a directory/file with issues, in all three formats: text, JSON, SARIF.
- Ensure the exist code is 1.
- Run `snyk iac test --experimental` with a directory/file with issues, in all three formats: text, JSON, SARIF.
- Ensure the exist code is 1.
- Run `snyk iac test` with a directory/file without issues, in all three formats: text, JSON, SARIF.
- Ensure the exist code is 0.
- Run `snyk iac test --experimental` with a directory/file without issues, in all three formats: text, JSON, SARIF. 
- Ensure the exist code is 0.
- At the moment when …
=> chore: Fix IaC test exit code when issues are found

src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts
This PR upgrades snyk-iac-test to v0.11.0.
=> chore: upgrade snyk-iac-test to v0.11.0

src/lib/types.ts
This PR removes a type which we forgot to delete when deprecating the legacy IaC test flow.
=> chore: remove deprecated type

src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/types.ts
This PR adds support for project attributes in the new PE testing flow by sending the values the user provides to the `snyk-iac-test` exe.
`snyk-iac-test` PR - https://github.com/snyk/snyk-iac-test/pull/58
https://snyksec.atlassian.net/jira/software/c/projects/CFG/boards/301?modal=detail&selectedIssue=CFG-2049
=> feat: add project attributes support in --experimental

src/cli/commands/test/iac/local-execution/types.ts, src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/errors.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/types.ts
- Adds support for the `report` flag, which enables sharing test results in `snyk-iac-test` in [this PR](https://github.com/snyk/snyk-iac-test/pull/57).
At this point, you should have the Share Results API client defined by [CFG-2043](https://snyksec.atlassian.net/browse/CFG-2043), all the necessary configuration and authentication information from CFG-[2044](https://snyksec.atlassian.net/browse/CFG-2044), and a way to convert between scan results and API payload with [CFG-2045](https://snyksec.atlassian.net/browse/CFG-2045).
The only missing piece of information is to detect whether the user activated the `--report` flag on the Snyk CLI. For this, you should create a corresponding flag or equivalent mechanism to pass this information to `snyk-iac-test`. The work at …
=> Chore/Send results to API [CFG-2046]

src/cli/commands/test/iac/local-execution/index.ts, src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/types.ts
This PR passes the values of the `--project-tags` flag to the snyk-iac-test binary. You can check it in combination with this branch: https://github.com/snyk/snyk-iac-test/pull/54 where the command accepts the new argument.
I used the existing `parseTags` function in the CLI which handles the validation and errors of the `--project-tags`.  There is a second check on the snyk-iac-test side as well, TBC if we need both.
- Go to this branch: https://github.com/snyk/snyk-iac-test/tree/feat/get-project-tags-arg
- Run locally `go build -o snyk-iac-test .`
- Now on the CLI side, point to the binary you just built (and a bundle) and try it out: 
```
SNYK_IAC_POLICY_ENGINE_PATH=/Users/iliannapapastefanou/snyk-repos/snyk-iac-test/snyk-iac-test \ …
```
=> feat: pass projectTags arg to snyk-iac-test [CFG-2051]

src/cli/args.ts, src/cli/commands/about.ts, src/cli/commands/index.js, src/lib/types.ts, test/jest/acceptance/about.spec.ts, test/smoke/spec/snyk_basic_spec.sh, webpack.common.ts, webpack.prod.ts
Ever since Snyk CLI started [bundling its npm packages](https://github.com/snyk/cli/blob/8331c5518f45a6f9caa222acb5d097f4e1e7f4f3/help/_about-this-project/why-we-are-bundling-dependencies.md), we [generated an attributions file](https://github.com/snyk/cli/blob/8331c5518f45a6f9caa222acb5d097f4e1e7f4f3/webpack.prod.ts#L14) that was part of the npm package we distributed.
However, since we also distribute single executables, we should expose the attribution information from the CLI interface itself. This PR introduces an `--about` option, with a same importance as `--version`. This option will print out the license information if libraries bundled into the Snyk CLI. I chose `about` as a command name following an [SO thread](https://opensource.stackexchange.com/questions/6886/single-executabl …
=> Introduce --about command for printing Open Source attributions

src/lib/iac/test/v2/errors.ts, src/lib/iac/test/v2/index.ts, src/lib/iac/test/v2/json.ts, src/lib/iac/test/v2/output.ts, src/lib/iac/test/v2/sarif.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/scan/results.ts, test/jest/unit/cli/commands/test/iac/v2/index.spec.ts, test/jest/unit/iac/process-results/fixtures/experimental-json-output.json, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-results.json, test/jest/unit/lib/iac/test/v2/json.spec.ts, test/jest/unit/lib/iac/test/v2/sarif.spec.ts
- Adds mapping for the `snyk-iac-test` output (`SnykIacTestOutput`) to the internal test output model (`TestOutput`). This includes:
- Mapping `snyk-iac-test` scan errors to Snyk CLI errors.
- Omitting `snyk-iac-test`'s raw results property, as we currently do not use it in the test flow. 
- Adds the `path` and `fields` properties to `SnykIacTestError`.
- We currently do the mapping of `snyk-iac-test` errors to Snyk CLI errors only for the text output, when this mapping is relevant for all test output formats in the CLI.
- We currently do not use the `rawResults` property received from `snyk-iac-test`.
- We currently don't hold a top-level `path` property in test errors, but the JSON output formatted expects it when adding errors.
- We currently don't add the `fields` property from …
=> chore: Moved snyk-iac-test error mapping to be after scanning

src/cli/commands/test/iac/local-execution/measurable-methods.ts, src/cli/commands/test/iac/local-execution/process-results/process-results.ts, src/cli/commands/test/iac/local-execution/process-results/results-formatter.ts
this is to fix a bug where we mutated the "results" in the formatAndShareResults and these were used again in the formatScanResults below, resulting in double count of issues.
note: this happened only in multi-YAML documents - Tested with other filetypes and none had issue with it.
This is not an issue in --experimental format as the code in go is functionally correct.
how to test:
- Run `snyk iac test output.yml`
- Run `snyk iac test output.yml --report` and see the difference in issues, counts, and docIds.
run with this branch again to see the issue fixed.
TODO: It's not yet clear why it only happened to the multi-doc files, but this code is to be deprecated soon.
=> Fix: iac double counts in multi-yaml documents with --report [CFG-2085]

src/cli/commands/test/iac/v2/index.ts
- Ensures the spinner for the experimental test flow stops, no matter if the flow fails or ends successfully.
```
src/cli/commands/test/iac/v2/index.ts
```
- Run the experimental test flow in a way that should make it fail, e.g., provide a custom ruleset bundle path to a non-existing ruleset.
- Ensure the spinner disappears as expected.
- Before: 
- After:
=> fix: Ensure the test spinner stops

src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts
Pass the IaC cache path to snyk-iac-test so that all subcomponents can
share cached resources.
Companion to https://github.com/snyk/snyk-iac-test/pull/64. **Do not merge** until that is released.
https://snyksec.atlassian.net/browse/CTX-190
=> [CTX-190] feat: share cache path with IaC plugin

src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts
Implements a function to derive the version of the `snyk-iac-test`from the checksum. This allows a developer to upgrade the dependency to `snyk-iac-test` by just pasting a new checksum, which is a change that must be done in one place only.
=> refactor: derive the Policy Engine version from the checksums

src/lib/formatters/iac-output/v2/formatters.ts, src/lib/formatters/iac-output/v2/issues-list/issue.ts, src/lib/formatters/iac-output/v2/types.ts, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-test-data.json
- Creates an `Issue` interface for the text output, to define which properties are relevant for the output. This also makes the mapping of `snyk-iac-test` results to issues used by the text output formatter easier, as it highlights which properties should be mapped and populated.
=> refactor: Create Issue interface for text output

src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/types.ts
Adds support for `--target-reference` to be passed to `snyk-iac-test`. There is no validation as we do not perform any validation on this free text string.
Try in combination with https://github.com/snyk/snyk-iac-test/pull/74
=> chore: add target-reference for iac v2 [CFG-2083]

src/lib/formatters/iac-output/v2/formatters.ts, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-test-data.json
- Adds the `Info` issue property in the text output by:
- Mapping the `results[].vulnerabilities[].rule.title` to the `issue.issue` and `issue.iacDescription.issue` properties.
- Mapping the `results[].vulnerabilities[].rule.description` to the `issue.impact` and `issue.iacDescription.impact` properties.
- Adds the `Docs` issue property in the text output by generating it with `results[].vulnerabilities[].rule.id`.
=> chore: Add missing text output properties

package-lock.json, package.json, src/cli/args.ts, src/lib/formatters/show-multi-scan-tip.ts, src/lib/plugins/get-multi-plugin-result.ts, src/lib/types.ts, test/jest/unit/lib/formatters/show-multi-scan-tip.spec.ts
See https://github.com/snyk/snyk-mvn-plugin/pull/136
Introduces `--maven-aggregate-project` so that we can support Maven module scanning better. Until now if modules depend on each other we would error out when using `--all-projects`. This new flag uses the Maven reactor and a `compile` phase to correctly scan the entire project using one Maven command, passing back a multi scan result to the CLI.
Added a Maven tip if we detect a Maven project with multiple manifests and no relevant options being used.
=> feat: scan maven aggregate projects

src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/output.ts, src/lib/iac/test/v2/scan/results.ts, src/lib/iac/test/v2/types.ts
Removes the project name calculation that we are doing in the CLI and instead starts using the project name that we are returning from `snyk-iac-test`
=> chore: change project name source

src/lib/formatters/get-vuln-url.ts, src/lib/formatters/legacy-format-issue.ts, src/lib/formatters/remediation-based-format-issues.ts, src/lib/spotlight-vuln-notification.ts, test/jest/unit/lib/formatters/get-vuln-url.spec.ts
Update the vulnerability URL generation so that it differentiates between license and security issues. License issues should resolve to a 301 redirect, where as security issues have their own page on https://security.snyk.io
=> fix: add helper for returning vulnerability URLs

src/lib/iac/test/v2/output.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts, test/jest/unit/cli/commands/test/iac/v2/index.spec.ts, test/jest/unit/iac/process-results/fixtures/experimental-json-output.json, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-results.json
- Adds support for exit code 3 when no resources can be found.
```
src/lib/iac/test/v2/output.ts
```
- Scan a directory with no supported IaC files and ensure the exit code is `3`.
- Scan a directory with some supported IaC files and ensure the exit code is `3`.
- Scan an unsupported file and ensure the exit code is `3`.
- Scan a supported IaC file and ensure the exit code is not `3`.
- At the moment, we return an exit code value of 0 when no supported IaC files were found.
- According to the [Snyk CLI docs](https://docs.snyk.io/snyk-cli/cli-reference#subcommands-of-cli-commands), these cases should return an exit code value of 3 for all output formats.
- This is aligned with the exit code return in the local-execution flow, where we also return an exit code of 3.
- [A recent …
=> fix: return exit code 3 when no resources can be found

test/jest/acceptance/iac/output-formats/text.spec.ts
This test is too strict on checking number of issues which depend on the ruleset changes, so we are removing the number in front of it.
=> test: fix broken iac test

src/cli/commands/test/iac/index.ts, src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/types.ts
Add support for `target-name` flag in the new engine. This flag will override the project name when sharing results via -`-report --target-name`.
If the remote-repo-url flag is used too, then the -`-target-name` will override that for the project name too.
PR https://github.com/snyk/snyk-iac-test/pull/88  will accept the target-name as a flag first.
To test: 
- `go build -o snyk-iac-test .`
- run `SNYK_IAC_POLICY_ENGINE_PATH=~/snyk-iac-test/snyk-iac-test SNYK_IAC_BUNDLE_PATH=~/cloud-config-opa-policies/bundle.tar.gz snyk-dev iac test test/fixtures/iac/terraform/sg_open_ssh.tf --experimental --report --target-name=yolo`
CFG-2084
=> feat: pass target-name arg to snyk-iac-test

src/lib/iac/test/v2/setup/local-cache/rules-bundle/index.ts
This PR removes the ability to use the cached rules bundle and instead it will redownload the bundle each time.
The reason behind this is the switch to the legacy rules bundle which is not using versioning so the latest "version" is being uploaded to the same S3 bucket each time.
=> feat: stop using cached rules bundle

src/lib/iac/test/v2/scan/index.ts
The PR fixes the problem where in some cases when scanning a directory with a high number of files, the scan failed due to an [ENOBUFS](https://www.encyclo.co.uk/meaning-of-ENOBUFS) error.
The fix is rather simple, it simply increases the max buffer.
=> fix: increase buffer size

src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/types.ts
Add support for `remote-repo-url` flag in the new engine. This flag will override the remote repository URL when sharing results via `--report --remote-repo-url=<new-url>`.
If the `target-name` flag is used too, then the `--target-name` will override that for the project name.
PR https://github.com/snyk/snyk-iac-test/pull/89 will process the `remote-repo-url` flag in `snyk-iac-test`. 
To test: 
- Build `snyk-iac-test` from https://github.com/snyk/snyk-iac-test/pull/89:
```
go build -o snyk-iac-test .
```
- run `SNYK_IAC_POLICY_ENGINE_PATH=<path-to-snyk-iac-test>  snyk-dev iac test test/fixtures/iac/terraform/sg_open_ssh.tf --experimental --report --remote-repo-url=yolo`
- verify the project was created under the name `yolo`.
- run `SNYK_IAC_POLICY_ENGINE_PATH=<path-to-snyk-iac-test> …
=> chore: Add support for remote-repo-url flag [CFG-2085]

package-lock.json, package.json
- the new version of the golang plugin disables the `shell` when spawning child processes
=> fix: update golang plugin

package-lock.json, package.json
To revert proxy behavior for calling docker registries before the no_proxy behavior change can go live.
=> Upgrade-docker-registry-v2-client

package-lock.json, package.json, test/smoke/spec/snyk_test_spec.sh
* downgrade snyk-go-plugin to 1.19.0: since it broke regression tests and wasn’t actually released yet
* disable failing test to unblock pipeline, the test is failing due to a regression in the api not in the CLI
=> fix: Regression tests

src/cli/commands/test/iac/local-execution/process-results/share-results-formatter.ts, test/acceptance/fake-server.ts, test/jest/acceptance/iac/cli-share-results.spec.ts
Related to this [Tier 3 Zendesk ticket](https://snyk.zendesk.com/agent/tickets/30091) where if you tried to send to `/iac-share-results` endpoint issues with custom policies set to `NONE` in the Snyk UI, you were getting an error using the `--report` in the CLI. Whereas, without the `--report` flag, everything works fine.
Behind the user experience, the problem is that we got a weird bug where registry send back to the CLI a 400 introduced in [this PR](https://github.com/snyk/registry/pull/27508) and we're now throwing an error back to the client due to a change of errors handling introduced [here](https://github.com/snyk/cli/pull/3454).
This PR is simply filtering `NONE` custom policies severity issues prior to sending them through the `/iac-share-results` endpoint.
Create a simple …
=> fix: none custom policies severity issues should be filtered out before sending them to registry

src/cli/commands/test/iac/index.ts, src/cli/commands/test/iac/local-execution/index.ts, src/cli/commands/test/iac/output.ts, src/cli/commands/test/iac/v2/index.ts
I'm suggesting this change for using only the subset of types we actually need. this will also help the next PR which needs the Policy Options to be used at a later point in code. https://github.com/snyk/cli/pull/3602
=> refactor: use IacTestFlags type instead of generic Options

src/cli/commands/test/iac/output.ts, src/cli/commands/test/iac/scan.ts, src/lib/formatters/iac-output/v2/share-results.ts, src/lib/iac/test/v2/output.ts, test/jest/unit/lib/formatters/iac-output/v2/share-results.spec.ts
This PR adds to the text output 2 new sections:
1. When using `--report` it adds a short summary of the generated projects and where to find them
2. When not using `--report` it adds a tip to let users know about the `--report` flag
1. Run `snyk-dev iac test --experimental --report` inside a dir that is a root of a repo and inside a dir which is not and see the correct project name with a link to the relevant projects page.
2. Run `snyk-dev iac test --experimental` and check for the correct tip at the bottom of the text output.
https://snyksec.atlassian.net/jira/software/c/projects/CFG/boards/301?modal=detail&selectedIssue=CFG-2102
Report summary
Report tip
=> feat: add report summary

src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/types.ts
This commit adds the policy file to the config file. We use the existing "policy" library to find and load the policy file.
We have decided that we can only have one .snyk file per repo, so even if we scan multiple paths, we will use the current working directory to load the .snyk file from the root of the project.
- Make sure you have a .snyk file in the project root, or create one.
- Try with one path
`snyk-dev iac test test/fixtures/iac/terraform/sg_open_ssh.tf --experimental`
Then try with multiple paths and multiple .snyk files, it should only load the one from the project root. 
`snyk-dev iac test test/fixtures/iac/terraform/sg_open_ssh.tf test/fixtures/iac/terraform/var_deref/nested_var_deref/variables.tf --experimental`
example output of the config file:
```
{
"org": "my.org", …
```
=> Feat: pass ignores to snyk iac test [cfg-2088]

src/lib/formatters/iac-output/v2/issues-list/issue.ts, test/jest/acceptance/iac/output-formats/text.spec.ts
Sets the spacing in the issue description between property name and values to be consistent, no matter which of the issue properties are available.
Before, the spacing was set based on the longest *available* issue property. With this PR, the space will be determined based on the longest possible property name, regardless of whether it is available or not for a particular issue.
- Before:
- After:
=> fix: Spacing for issue descriptions with custom rules

dangerfile.js
This PR fixes the link to snyk docs which is displayed in the warning when updating the CLI help text.
=> chore: fix docs link in modified-help warning

src/cli/commands/test/iac/local-execution/process-results/cli-share-results.ts, src/lib/ecosystems/types.ts, src/lib/iac/envelope-formatters.ts, src/lib/polling/types.ts, test/jest/unit/iac/cli-share-results.spec.ts
IaC has recently introduced a new flag in the CLI called `--target-name` that as the name suggest allows the user to overwrite the target name in the platform.
We currently have a bug where when scanning a directory that is a root of a repo the target name is not getting overridden with the one that the user set by using the flag.
This PR adds the ability to add the name field to the target together with git information, in registry we can use the `name` to overwrite the `target` name.
1. Run registry using the fix PR linked below
2. cd to a directory that is the root of a repo
3. Run `snyk-dev iac test --report --target-name=test`
4. Open the UI and check for the correct target name
The fix in this PR is dependent on the fix in https://github.com/snyk/registry/pull/28707. …
=> fix: `--target-name` bug

cliv2/internal/httpauth/proxy_authenticator.go, test/jest/acceptance/proxy-behavior.spec.ts
It fixes an issue with the NO_PROXY environment configuration for the Extensible CLI.
In addition a test is added.
=> chore: fix no_proxy behavior in cliv2 and add a test for it

src/cli/commands/test/iac/local-execution/assert-iac-options-flag.ts, src/cli/commands/test/iac/v2/assert-iac-options.ts, src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/types.ts, test/jest/unit/cli/commands/test/iac/v2/index.spec.ts
This PR adds support for the `--scan` flag in the v2 testing flow and in addition to that adds assertion for the flags that the user provided.
1. switch to the [following](https://github.com/snyk/snyk-iac-test/pull/91) `snyk-iac-test` branch and run `make build`
2. Using the file [tf-plan-no-op.json](https://github.com/snyk/cli/blob/master/test/fixtures/iac/terraform-plan/tf-plan-no-op.json) run the commands below:
3. `SNYK_IAC_POLICY_ENGINE_PATH={local_snyk-iac-test_exe_path} snyk-dev iac test tf-plan-no-op.json --scan=resource-changes --experimental` and check for no issues found
4. `SNYK_IAC_POLICY_ENGINE_PATH={local_snyk-iac-test_exe_path} snyk-dev iac test tf-plan-no-op.json --scan=planned-values --experimental` and check for issues found
5. …
=> feat: add scan flag support

src/lib/formatters/iac-output/text/formatters.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/results.ts, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-results.json, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-text-output-data.json
Add support for displaying the amount of ignored vulnerabilities in the summary section of the text output.
Run a scan with the `--experimental` flag.
```
$ snyk iac test --experimental test/fixtures/iac
```
The text output should present this summary:
```
✔ Files without issues: 12
✗ Files with issues: 3
Ignored issues: 0
Total issues: 59 [ 0 critical, 22 high, 10 medium, 27 low ]
```
Add an ignore using the `snyk` command.
```
$ snyk ignore --id=SNYK-CC-TF-98 --path='*'
```
Re-run the same scan as before. The text output should account for the number of vulnerabilities that were ignored:
```
✔ Files without issues: 12
✗ Files with issues: 3
Ignored issues: 5
Total issues: 54 [ 0 critical, 17 high, 10 medium, 27 low ]
```
[CFG-2092](https://snyksec.atlassian.net/browse/CFG-2092)
=> feat: add ignore count in the experimental version of iac test

test/jest/acceptance/snyk-test/spotlight-vuln-notification.spec.ts
Since the test `test/jest/acceptance/snyk-test/spotlight-vuln-notification.spec.ts` often fails with a timeout, I increased the timeout for this specific test from 30s to 60s.
=> chore: increase timeout to 60sec to reduce test flakiness

src/lib/formatters/iac-output/text/issues-list/index.ts, src/lib/formatters/iac-output/text/issues-list/issue.ts, src/lib/formatters/iac-output/text/types.ts, src/lib/formatters/iac-output/text/utils.ts, src/lib/iac/test/v2/json.ts, src/lib/iac/test/v2/scan/results.ts, test/jest/acceptance/iac/output-formats/text.spec.ts, test/jest/acceptance/iac/test-arm.spec.ts, test/jest/acceptance/iac/test-cloudformation.spec.ts, test/jest/acceptance/iac/test-kubernetes.spec.ts, test/jest/acceptance/iac/test-terraform.spec.ts, test/jest/unit/lib/formatters/iac-output/text/issues-list/index.spec.ts
- Fixes the lack of indentation for issue properties that exceed the line width of the CLI.
```
src/lib/formatters/iac-output/text/issues-list/issue.ts
```
- Run `snyk-dev iac test`
- For the issues list in the test output, ensure the issue properties are broken into new indented lines as needed, rather than start at the beginning of the line beneath the property name.
- Before:
- After:
=> chore: Added line breaking for IaC issue description

cliv2/cmd/cliv2/main.go, cliv2/cmd/cliv2/main_test.go
Remove the command line argument `--proxy`, to only support Proxy configuration via environment variables HTTP_PROXY, HTTPS_PROXY, NO_PROXY.
=> chore: remove —proxy cmd argument

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts
Adds custom severities as part of the config we send to the snyk-iac-test. 
This is now an object containing the custom severities set on the IaC Settings on Snyk Platform.
We fetch these from the registry `/iac-org-settings endpoint` and then pass them over to snyk-iac-test through the config.
To test it out:
- Run this branch locally `npm run build-cli:dev`
- Build the `snyk-iac-test` exec from this branch: https://github.com/snyk/snyk-iac-test/pull/103 by running
` go build -o snyk-iac-test . `
- Run an experimental scan `SNYK_IAC_POLICY_ENGINE_PATH=~/snyk-iac-test/snyk-iac-test snyk-dev iac test test/fixtures/iac/depth_detection/root.tf --experimental`
- See that the issue shows SNYK-CC-TF-4 with severity of medium.
- Set up a new severity in your org in snyk platform, eg set …
=> Feat/pass org settings to iac test [CFG-2109]

src/cli/commands/test/iac/v2/assert-iac-options.ts, src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/types.ts
- Updates the checksum values for `snyk-iac-test`.
- Adds support for the `--depth-detection` flag from the CLI, to pass to `snyk-iac-test`.
- The definition of depth in `policy-engine` was different than the definition in the Snyk CLI. In `snyk-iac-test`, files inside a directory are defined as another depth level, whereas in the CLI the definitions are only defined by the directories. Example, for `zero/one/main.tf`, `snyk-iac-test` would define the file to be in depth level `2`, whereas in the CLI, the depth level would be `1`.
- The `depth-detection` flag accepts positive integers (d > 0).
- Build a local `snyk-iac-test` binary with https://github.com/snyk/snyk-iac-test/pull/104
- Build a local Snyk CLI
- Run the following:
```
SNYK_IAC_POLICY_ENGINE_PATH=<path-to-snyk-iac-test> …
```
=> feat: Added support for depth-detection [CFG-2110]

package-lock.json, package.json
The new version of the Gradle plugin introduces a fix for projects that would get a "matching configuration" error when there were no resolvable configurations. These projects will instead return an empty dep graph.   
See this [PR](https://github.com/snyk/snyk-gradle-plugin/pull/221)
=> fix: matching configurations error on gradle version catalog

.github/CODEOWNERS
Team Capsule has been split and no longer exists. Removing their code ownership.
=> chore: remove code ownership from Capsule

src/cli/commands/test/iac/local-execution/assert-iac-options-flag.ts, src/cli/commands/test/iac/v2/assert-iac-options.ts, src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/types.ts
This PR adds support for the `--var-file` flag in the new IaC testing flow.
1. Build a local binary of the [following](https://github.com/snyk/snyk-iac-test/pull/105) `snyk-iac-test` branch
2. Files to test this new functionality are available [here](https://github.com/snyk/snyk-iac-test/tree/be6dc43543a6aa0af7a1d4dfdfe6ddbbb5b8317e/pkg/engine/testdata/terraform-vars)
3. cd to the directory linked above and run the following commands:
4. `SNYK_IAC_POLICY_ENGINE_PATH={local_snyk-iac-test_exe_path} snyk-dev iac test terraform.tf --experimental --var-file=random` and get an error for non-existent vars file
5. `SNYK_IAC_POLICY_ENGINE_PATH={local_snyk-iac-test_exe_path} snyk-dev iac test terraform.tf --experimental --var-file=../valid/terraform.tf` and get an error for an invalid vars file
6. …
=> feat: add --var-file support

.circleci/config.yml, cliv2/Makefile, test/jest/acceptance/iac/file-output.spec.ts
Add handling of alpine builds to the Makefile. It introduces the possibility to run
`make build GOOS=alpine GOARCH=amd64`
While for the golang cli this will actually result in a linux build, the bundled TS cli will have to be build explicitly for alpine.
=> chore: handle GOOS alpine in Makefile

package-lock.json, package.json
- add meaningful error for `golang` when binary is not available on the host machine
- bump the plugin version
=> fix: bump golang plugin version

package-lock.json, package.json
Bumps the version of snyk-gradle-plugin 
The latest version includes a change to the way subprojects of multi-module Gradle project are filtered. Instead of checking if the subproject has the same name as the root project, check if it has the same path. This helps when a project contains a nested subproject with the same name as root. Do not override one with the other.
[Relevant PR](https://github.com/snyk/snyk-gradle-plugin/pull/222)
=> fix: filter subprojects on unique path

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts
This commit creates a temporary filepath and passes it through the `-output` flag to the snyk-iac-test executable.
The snyk-iac-test will then write all the results to this file, which the CLI will have to read and present to the user.
Notes: 
- the flag is not visible to the user, this will all happen in the background.
- the file is created with empty content on the CLI side, and then gets overwritten by the snyk-iac-test with the results. This comment explains also reasoning about runnings scans in parallel: https://snyksec.atlassian.net/browse/CFG-2114?focusedCommentId=509517
- the file is deleted when the results are read on the CLI side.
- if errors happen during the file creation they will get caught on the CLI side too.
- if errors happen during the file writing we will handle …
=> feat: create temp filepath for iac engine to write results [CFG-2114]

src/lib/formatters/iac-output/text/formatters.ts, src/lib/iac/test/v2/json.ts, src/lib/iac/test/v2/sarif.ts, src/lib/iac/test/v2/scan/results.ts, test/jest/unit/iac/process-results/fixtures/experimental-json-output.json, test/jest/unit/iac/process-results/fixtures/experimental-sarif-output.json, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-results.json, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-text-output-data.json
- Includes the one-liner remediation advices from `policy-engine` for any issues in the test output in all relevant output formats:
- Text
- JSON
- SARIF
- Run `snyk iac test --experimental` and ensure any displayed issues include the expected one-liner remediation advice.
- Run `snyk iac test --experimental --json` and ensure any displayed issues include the expected one-liner remediation advice.
- Run `snyk iac test --experimental --sarif` and ensure any displayed issues include the expected one-liner remediation advice.
[A proposal](https://docs.google.com/document/d/13k8rYyTREl6yvGb47EbzR91gTcXIXvnVVlEZcewiGQo/edit#heading=h.2r18umlrg1im) was approved to keep the one-liner format for security rules. In the new format, the remediation property is a dictionary that maps project types to …
=> chore: Add issue remediation to test output [CFG-2124]

src/cli/commands/test/iac/local-execution/types.ts, src/lib/iac/test/v2/errors.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
There will be a request-specific error in the debug log, but we lack the
plumbing to propagate this up without that flag as far as I know. The
message contains a hint to run again with debug logs for this reason.
We tested this with a few scenarios. First, we built snyk-iac-test so that we could use a pre-release version in tests.
On top of this PR, we applied the following patch to hack cloud context into the CLI flow, as that's not actually exposed yet:
```diff
diff --git a/src/lib/iac/test/v2/scan/index.ts b/src/lib/iac/test/v2/scan/index.ts
index 088e84e5a..76f6a0846 100644
--- a/src/lib/iac/test/v2/scan/index.ts
+++ b/src/lib/iac/test/v2/scan/index.ts
@@ -87,6 +87,8 @@ function processFlags(
outputPath: string,
) {
const flags = [
+    '-cloud-context',
+    process.env.CLOUD_CONTEXT …
```
=> feat: custom message for IaC cloud context errors

cliv2/.gitignore, cliv2/Makefile, cliv2/cmd/cliv2/main_test.go, cliv2/internal/cliv2/cliv2.go, cliv2/internal/embedded/_data/README.md, cliv2/internal/embedded/file.go, cliv2/scripts/prepare_licenses.sh
This PR add golang based licenses to the --about dialog. It adds retrieving the licenses on the fly to the build process, bundles them into the binary and prints them to the end of the typescript based license content.
* Retrieve licenses: scripts/prepare_licenses.sh
* Bundle licenses: internal/embedded/file.go
* Print licenses: internal/cliv2/cliv2.go
Run the cli with `--about`, pipe the output into a file and compare the output with the same output for the typescript cli
=> chore: implement --about

package-lock.json, package.json
Bumps the version of the docker-plugin to support trimmed, stripped and Cgo binaries.
See [snyk-docker-plugin #447](https://github.com/snyk/snyk-docker-plugin/pull/447) for more info.
https://snyksec.atlassian.net/browse/MYC-146
=> feat: container Go binary scan

.circleci/config.yml, test/jest/acceptance/iac/file-output.spec.ts
Install git on the alpine test container and re-enable the previously skipped test.
=> chore: install git on alpine and re-enable test

src/lib/formatters/iac-output/text/utils.ts
- Ensures readability for terminals with a width lower than the default `80` columns.
```
src/lib/formatters/iac-output/text/utils.ts
```
- Narrow your CLI to a width lower than `80` columns.
- Run `snyk iac test` to test files.
- Ensures the issue descriptions remain readable and that the indentation acts as expected.
=> chore: Added short-width terminals support for text output

package-lock.json, package.json
This dependency bump should fix the "Invalid version" error we're seeing when scanning some Python projects in containers
=> fix: container python app scan errors

src/cli/commands/test/iac/local-execution/types.ts, src/lib/iac/test/v2/scan/index.ts, test/jest/unit/cli/commands/test/iac/meta.spec.ts, test/jest/unit/cli/commands/test/iac/v2/index.spec.ts, test/jest/unit/iac/index.spec.ts, test/jest/unit/iac/results-formatter.fixtures.ts, test/jest/unit/iac/rules/rules.spec.ts, test/jest/unit/lib/iac/test/v2/json.spec.ts
This PR includes the org public ID, returned from the IaC org settings endpoint, into the configuration passed to `snyk-iac-test`. This piece of information is necessary to `snyk-iac-test` to invoke the Snyk Cloud API.
The changes in this PR are only relevant to the experimental flow of `snyk iac test`.
=> feat: pass the org public ID to snyk-iac-test

src/lib/formatters/iac-output/text/formatters.ts, src/lib/formatters/iac-output/text/test-summary.ts, src/lib/formatters/iac-output/text/types.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/results.ts, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-results-with-suppressions.json, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-text-output-data-with-suppressions.json, test/jest/unit/iac/process-results/fixtures/test-data-with-suppressions.json, test/jest/unit/lib/formatters/iac-output/text/formatters.spec.ts, test/jest/unit/lib/formatters/iac-output/text/test-summary.spec.ts
When snyk-iac-test returns suppressedResults in scan analytics, display a total count of suppressed issues alongside the other scan counts.
This feature `iac test --cloud-context=...` is still undocumented and is only available behind a feature flag. The context-suppressed count will only appear when any issues are actually suppressed, which should not actually occur for non-snyk-developer users yet.
This PR depends on the PR'ed ~+ unmerged~ scanAnalytics field in snyk-iac-test's return payload. If approved, this PR should be updated with the new pinned version that is released after https://github.com/snyk/snyk-iac-test/pull/115 is merged, before merging this one.
https://snyksec.atlassian.net/browse/CTX-403
When cloud-context has found issues:
Note that this field does not appear when …
=> [CTX-403] feat: IaC context-suppressed issue count

src/lib/iac/test/v2/local-cache/rules-bundle/download.ts
feat: can override IaC experimental bundle
Using the same environment variable as we do for the regular bundle. This is intended as a developer feature, and is not useful for most users.
=> feat: can override IaC experimental bundle

src/cli/commands/test/iac/v2/assert-iac-options.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts
This PR upgrades the version of `snyk-iac-test` to enable sharing results with the Snyk Cloud API. Moreover, it enables users to use the `--report`, `--target-name`, and `--remote-repo-url` flags, which can be used to influence how the information about the shared results are computed.
**Note** The `--target-name` flag only works the first time the environment is created. This is because of a bug in the implementation of the Cloud API that is being fixed right now. Once the fix is in place, the user will be able to change the environment's name when sharing results even if the environment already exists.
Share results with:
```
snyk iac test --experimental --report path/to/scan
```
[CFG-2142](https://snyksec.atlassian.net/browse/CFG-2142)
=> feat: share results with the Cloud API

src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/types.ts
When a user configures `HTTPS_PROXY` and `--insecure` to use an HTTP proxy, the settings should be propagated to `snyk-iac-test` so that the requests sent from that component will go through the proxy, too. `snyk-iac-test` already provide support for proxies, so this PR is just about propagating the right settings and flags from the `snyk` CLI to `snyk-iac-test`.
Start a proxy and run the command like this:
```
HTTPS_PROXY=http://localhost:8080 snyk iac test --experimental --insecure path/to/scan
```
=> feat: add support for an HTTP proxy  when using snyk-iac-test

src/lib/formatters/iac-output/text/formatters.ts
snyk iac test scan would fail when trying to access `snykIacTestScanResult?.scanAnalytics.supressedResults`, in the case of `snykIacTestScanResult` being undefined. 
This is because the whole `snykIacTestScanResult?.scanAnalytics` would evaluate to u`ndefine` and `suppressedResults` would fail to read an undefined value. 
Added a "?" operator to scanAnalytics to fix this error.
=> fix: iac test result undefined

src/cli/commands/test/iac/local-execution/types.ts, src/cli/commands/test/iac/output.ts, src/lib/formatters/iac-output/text/share-results.ts, src/lib/iac/test/v2/errors.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/output.ts
When sharing results with the experimental flow of `snyk iac test`, the CLI shows the URL pointing to the projects page. This PR changes the implementation so that the CLI shows a URL pointing to the cloud issues UI, with a query filter that shows only the resources scanned in the execution of the CLI.
Share results with the experimental flow:
```
snyk iac test --experimental --report path/to/scan
```
The CLI will show a summary at the end of the scan with the updated URL:
```
Report Complete
Your test results are available at: https://snyk.io/org/francescomari/cloud/issues?environment_name=snyk%2Fcli
```
[CFG-2155](https://snyksec.atlassian.net/browse/CFG-2155)
=> feat: show Cloud Issues URL when sharing results with snyk iac test

src/lib/ecosystems/resolve-test-facts.ts, src/lib/ecosystems/types.ts, src/lib/ecosystems/unmanaged/types.ts, src/lib/ecosystems/unmanaged/utils.ts, src/lib/polling/polling-test.ts, src/lib/snyk-test/legacy.ts, test/jest/unit/lib/ecosystems/fixtures/create-dep-graph-response.ts, test/jest/unit/lib/ecosystems/fixtures/dep-graph-open-api.ts, test/jest/unit/lib/ecosystems/fixtures/expected-test-result-new-impl.ts, test/jest/unit/lib/ecosystems/fixtures/get-dep-graph-response.ts, test/jest/unit/lib/ecosystems/fixtures/issues-response.ts, test/jest/unit/lib/ecosystems/resolve-test-facts.spec.ts
- Implements Feature Flag to switch to a new polling function that uses a new Unmanaged Service APIs
- Implements a new polling function that uses a new Unmanaged Service APIs
Implementation begins in the following function: resolveAndTestFacts
Use the following options: test --unmanaged, do not forget to enable feature flag, current name is 'snykNewUnmanagedTest'
- [Implement CLI feature flag for new service: TUN-299](https://snyksec.atlassian.net/browse/TUN-299)
- [Update CLI polling functions to point at the unmanaged service: TUN-317](https://snyksec.atlassian.net/browse/TUN-317)
=> feat: add unmanaged service test call ff

.circleci/config.yml
Publishes the new golang CLI as the snyk.exe binary (and corresponding sha256 file) to GH releases and the CDN.
=> chore: add golang binary for windows to releases

.github/CODEOWNERS, .github/workflows/iac-smoke-tests-pulls.yml, .github/workflows/iac-smoke-tests.yml, package.json, test/smoke/iac/README.md, test/smoke/iac/test.spec.ts
- Creates smoke tests for the experimental IaC test.
- Creates a new Github Action to run these smoke tests every hour and for every PR with IaC files.
- As of writing this, the `IAC_SMOKE_TESTS_SNYK_TOKEN` secret with the authentication token was yet to be added by team Hammer, so the tests still fail on the authentication step of the `snyk iac test --experimental` command.
After [CFG-2061: Spike options for testing/monitoring resources availability for the CLI](https://snyksec.atlassian.net/browse/CFG-2061) , we ended up on agreeing that a smoke test which downloads the artefacts and runs an IaC scan will give us enough confidence that the reyling artefacts are available and scans are working.
- Language of choice:  Jest
- CI of choice: Github Action
- Note: Jest vs shellspec was a tie …
=> chore: Create smoke tests for experimental IaC tests

package-lock.json, package.json, src/cli/args.ts, src/lib/module-info/index.ts, src/lib/plugins/get-single-plugin-result.ts, src/lib/request/snyk-http-client.ts, src/lib/types.ts, test/tap/cli-monitor.acceptance.test.ts, test/tap/cli-test.acceptance.test.ts, test/tap/cli-test/cli-test.composer.spec.ts, test/tap/cli-test/cli-test.elixir.spec.ts, test/tap/cli-test/cli-test.go.spec.ts, test/tap/cli-test/cli-test.maven.spec.ts, test/tap/cli-test/cli-test.nuget.spec.ts, test/tap/cli-test/cli-test.python.spec.ts
Creates an HTTP request client wrapper that allows plugins to make authenticated requests to Snyk's backend.
Passes this as an additional argument to `plugin.inspect`
Introduced new snyk-gradle-plugin flag 'gradle-normalize-deps' see https://github.com/snyk/snyk-gradle-plugin/pull/226
=> feat: pass snykHttpClient to plugin.inspect

cliv2/internal/analytics/analytics.go, cliv2/internal/analytics/analytics_test.go
=> Redact static strings from analytics

src/lib/formatters/iac-output/text/formatters.ts, src/lib/iac/test/v2/analytics/iac-type.ts, src/lib/iac/test/v2/analytics/index.ts, src/lib/iac/test/v2/index.ts, src/lib/iac/test/v2/scan/results.ts, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-results-with-suppressions.json, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-results.json, test/jest/unit/lib/iac/test/v2/analytics/fixtures/iac-analytics.json, test/jest/unit/lib/iac/test/v2/analytics/index.spec.ts
- Computes analytics for the experimental test flow.
- Prints the analytics to the debug logs.
- **DOES NOT** send the analytics.
```
src/lib/iac/test/v2/analytics
```
- Run `snyk iac test --experimental -d`
- Ensure the printed analytics are the expected ones.
- The current implementation is discussed in [this Notion page](https://www.notion.so/snyk/Analytics-545ce0ef48e8459a94a8afa5b382b635). The page also describes the analytics that should be computed by the experimental flow, and some ideas for more analytics information that could be useful in the future.
- Because the analytics information that we are going to compute cannot be sent over the network yet, it will be sufficient to print them to a debug logger for the time being. The information we compute must not be shared with the …
=> chore: Add experimental test analytics [CFG-2157]

package-lock.json, package.json, src/lib/dep-graph.ts, src/lib/formatters/test/display-result.ts, src/lib/formatters/test/format-test-results.ts, src/lib/snyk-test/legacy.ts, src/lib/snyk-test/run-test.ts, test/acceptance/workspaces/ruby-app-no-vulns/test-graph-result.json, test/acceptance/workspaces/ruby-app-no-vulns/test-result.json, test/acceptance/workspaces/ruby-app-policy/test-graph-result-cloud-ignore.json, test/acceptance/workspaces/ruby-app-policy/test-graph-result.json, test/acceptance/workspaces/ruby-app-policy/test-result-cloud-ignore.json, test/acceptance/workspaces/ruby-app-policy/test-result.json, test/acceptance/workspaces/ruby-app-thresholds/test-result-critical-severity.json, test/acceptance/workspaces/ruby-app-thresholds/test-result-high-severity.json, test/acceptance/workspaces/ruby-app-thresholds/test-result-low-severity.json, test/acceptance/workspaces/ruby-app-thresholds/test-result-medium-severity.json, test/acceptance/workspaces/sbt-simple-struts/legacy-res-json.json, test/acceptance/workspaces/sbt-simple-struts/test-graph-result.json, test/jest/acceptance/dep-graph.spec.ts, test/jest/unit/python/snyk-test-pyproject.spec.ts
See https://github.com/snyk/snyk-mvn-plugin/pull/137
Adding warning message to indicate when projects have a dep-graph that contains packages with unknown versions (like in the Snyk UI).
=> fix: unmanaged scan unknown archives

.github/workflows/iac-smoke-tests-pulls.yml, .github/workflows/iac-smoke-tests.yml, package-lock.json, package.json, packages/iac-cli-alert/jest.config.js, packages/iac-cli-alert/package.json, packages/iac-cli-alert/src/index.ts, packages/iac-cli-alert/tsconfig.json, test/smoke/iac/test.spec.ts
- Adds Slack alerts for failing Snyk IaC smoke tests triggered by:
- Scheduled executions.
- Releases.
- These alerts will not be triggered by failing smoke tests triggered by pull requests.
- As part of [CFG-2106](https://snyksec.atlassian.net/browse/CFG-2106), we created a smoke tests suite for the experimental test flow in the Snyk CLI. Further details can be found [here](https://github.com/snyk/cli/tree/chore/create-iac-e2e-tests-cfg-2106/test/smoke/iac). 
These tests are triggered for pull requests, new CLI releases, and are also scheduled to run every hour.
Failing tests can currently block pull requests to the master branch of `snyk/cli`.
We are currently not alerted whenever a smoke test fails after a CLI release or on a scheduled execution of these tests, and we would like to be. …
=> chore: Add Slack alerts for IaC smoke tests [CFG-2165]

src/lib/iac/test/v2/output.ts
This PR adds an info message to the end of the new flow of the `snyk iac test` command.
Run the new flow of the `snyk iac test` command, with and without the `--report` flag, and check that the info message is printed correctly.
=> feat: add an info message to the new iac test command

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
This PR upgrades `snyk-iac-test` to version `0.32.1`.
=> chore: upgrade snyk-iac-test to v0.32.1

package-lock.json, package.json
Bumps snyk-gradle-plugin version to 3.24.1
This version includes the following changes:
- use /rest/packages best practice Snyk REST API endpoint, add dependency on packageurl-js https://github.com/snyk/snyk-gradle-plugin/pull/232
- don't throw matching configurations error if one project in a multi-module build doesn't have requested config https://github.com/snyk/snyk-gradle-plugin/pull/235
=> fix: remove gradle matching config error

src/cli/commands/monitor/index.ts, src/cli/commands/test/index.ts, src/lib/types.ts, test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts
Although we already have a `--app-vulns` flag, the plan is to enable app-vulnerability scanning in containers by default. Before doing that, we want to give customers the opportunity to explicitly opt-out of the change in the default by introducing a new flag `--exclude-app-vulns`. This flag will co-exist with the `--app-vulns` flag until it's enabled by default, at which point the `--app-vulns` flag can be removed.
Additionally (second commit) it adds a warning message regarding the app-vuln enablement: 
Run `snyk container test` without the `--app-vulns` flag, where the message should show up. Add `--json` and see how the message magically disappears :) 
https://snyksec.atlassian.net/browse/MYC-163
https://snyksec.atlassian.net/browse/MYC-175
=> feat: add flag to exclude app vulnerabilities

test/smoke/iac/test.spec.ts
Remove the check on stderr, which might not be empty because of code outside of IaC's control, like alerts.
=> fix: do not check stderr output in IaC smoke tests

src/lib/iac/test/v2/output.ts
This PR replaces the long link to the Integrated IaC documentation with a shorter one, which fits better with the output flow of the command.
=> feat: use short link to the Integrated IaC docs

cliv2/internal/analytics/analytics.go, cliv2/internal/analytics/analytics_test.go
In addition to removing the user name, we remove the home directory, which also might contain the user name.
=> chore: additionally redact user homedir if still in analytics data

.circleci/config.yml, .snyk
Publishes the new golang CLI as the snyk-macos binary (and corresponding sha256 file) to GH releases and the CDN.
https://github.com/snyk/cli/pull/3847
=> chore: add golang binary for macos to releases

Makefile, cliv2/Makefile
new targets enable to locally build/clean typescript and golang cli together, to support local development in both worlds
Support parallel development in both worlds, the typescript CLI and the golang CLI
in the cliv2 directory
* run `make clean-full` to get a fresh start first
* run `make build-full` to build both CLIs in the correct order
This is required for near term development
=> chore: build typescript + golang cli locally

package-lock.json, package.json
Bumps version of snyk-gradle-plugin. The latest release includes bug fixes:
- fix for duplicate names in multi-module projects - use path instead of name: https://github.com/snyk/snyk-gradle-plugin/pull/234
- modify rest package path and fix TS2304 error: https://github.com/snyk/snyk-gradle-plugin/pull/238
=> fix: identify gradle projects by path not name

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, cliv2/internal/cliv2/cliv2.go, cliv2/internal/cliv2/cliv2_test.go, cliv2/internal/proxy/proxy.go, cliv2/internal/proxy/proxy_test.go
Adds basic authentication to the internal CLI golang proxy and then invokes TS CLI with proxy credentials.
=> Use basic auth for internal CLI proxy

.github/workflows/iac-smoke-tests.yml, test/smoke/iac/README.md, test/smoke/iac/test.spec.ts
This PR adds smoke tests for the `--report` flag.
Instructions on how to run the test locally are available in the README file.
Before merging the PR we need to update the `IAC_SMOKE_TESTS_SNYK_TOKEN` secret with the new auth token, I'll contact Hammer and ask them to update it (https://snyk.slack.com/archives/C0127HWU0E7/p1666166764583909).
https://snyksec.atlassian.net/jira/software/c/projects/CFG/boards/301?modal=detail&selectedIssue=CFG-2164
=> feat: IaC --report smoke testing

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Upgrade snyk-iac-test to v0.34.1.
=> feat: Upgrade snyk-iac-test to v0.34.1

src/lib/iac/test/v2/json.ts, src/lib/snyk-test/iac-test-result.ts, test/fixtures/iac/output-formats/test-error-json-schema.json, test/jest/unit/cli/commands/test/iac/v2/index.spec.ts, test/jest/unit/iac/process-results/fixtures/integrated-json-output.json
This PR adds to the JSON output of the IaC scan error codes when relevant.
Run `snyk iac test --json` while trying to scan an invalid file and check for an error code in the JSON output.
https://snyksec.atlassian.net/browse/CFG-2193
JSON output for the new integrated IaC(top) and legacy IaC(bottom)
=> feat: add error code to iac json output

src/cli/commands/test/iac/local-execution/types.ts, src/cli/commands/test/iac/v2/assert-iac-options.ts, src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/types.ts
This PR introduces the new `--snyk-cloud-environment` flag for the cloud context feature. Instead of requesting a cloud API (e.g. AWS) to find specific resources of a given type, it will request Snyk Cloud API directly.
=> feat: new cloud context flag --snyk-cloud-environment

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts
This PR follows the latest calling convention established by `snyk-iac-test`.
=> feat: Use separate config variables for the REST and V1 clients

src/lib/formatters/iac-output/text/formatters.ts, src/lib/formatters/iac-output/text/utils.ts, src/lib/iac/test/v2/analytics/iac-cloud-context.ts, src/lib/iac/test/v2/analytics/index.ts, src/lib/iac/test/v2/index.ts, test/jest/unit/lib/iac/test/v2/analytics/fixtures/iac-analytics.json, test/jest/unit/lib/iac/test/v2/analytics/index.spec.ts
This PR adds analytics to the `snyk iac test --cloud-context=aws` command (e.g. cloud context feature).
Run `./bin/snyk iac test --cloud-context=aws -d` with your AWS creds. For a specific use case you can try to use a terraform file with this code and enable in your AWS console the regional EBS volume encryption setting.
```hcl
resource "aws_instance" "this" {
ami           = "ami-0c55b159cbfafe1f0"
instance_type = "t2.micro"
}
resource "aws_ebs_volume" "this" {
availability_zone = "us-east-2a"
size              = 1
}
```
https://snyksec.atlassian.net/browse/CTX-32
```
snyk analytics {
"args": [
"terraform.tf",
{
"cloud-context": "aws",
"debug": true,
"iac": true
}
],
"command": "test",
"metadata": {
"policies": 1,
"policyLocations": [
"/Users/wbeuil/Snyk/snyk"
],
"iac-type": { …
```
=> chore: add cloud-context analytics

src/lib/iac/test/v2/index.ts, src/lib/iac/test/v2/scan/index.ts, test/jest/unit/cli/commands/test/iac/v2/index.spec.ts
This PR prepares the environment for `snyk-iac-test` and runs it using only asynchronous functions. This doesn't have any difference in the functionality but, because the event loop is not blocked, the spinner we show to the user doesn't have any hiccup and runs smoothly.
=> fix: Invoke snyk-iac-test asynchronously

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Updates the `snyk-iac-test` package to include the refactoring of the test flow: https://github.com/snyk/snyk-iac-test/releases/tag/v0.35.2
2. Enable feature flag `iacIntegratedExperience`
3. `snyk-dev iac test ./test/fixtures/iac/terraform-plan/tf-plan-create.json`
4. `snyk-dev iac test ./test/fixtures/iac/terraform-plan/tf-plan-create.json --report` 
https://github.com/snyk/snyk-iac-test/releases/tag/v0.35.2
=> refactor: test flow and update snyk-iac-test library

package-lock.json, packages/snyk-fix/package.json
Bump version of pipenv fix package that introduces support for versions 2022.*
=> feat(@snyk/fix): pipenv support for version 2022.*

src/lib/iac/test/v2/scan/index.ts
This PR fixes a bug where errors returned by `snyk-iac-test` are silently swallowed instead of being thrown and displayed to the user.
=> fix: Errors from snyk-iac-test should not be swallowed

package-lock.json, package.json
Bumps version of snyk-sbt-plugin to 2.16.0
Changes included:
- change conditions under which plugin inspect is used: https://github.com/snyk/snyk-sbt-plugin/pull/115
- added test for sbt v. 1.7.0: https://github.com/snyk/snyk-sbt-plugin/pull/114
- add more debug logs: https://github.com/snyk/snyk-sbt-plugin/pull/112
=> fix: relax conditions for sbt plugin inspect

src/cli/commands/test/index.ts, src/cli/main.ts, src/lib/errors/failed-to-run-test-error.ts, src/lib/snyk-test/run-test.ts, test/jest/acceptance/analytics.spec.ts
This PR adds innerError to CLI analytics as error-details, and uses body in 403 error innerError if body.stack is empty.
This will allow us to get more insights in analytics about 403 errors.
=> chore: add innerError to analytics

package-lock.json, package.json, scripts/apply-patches.sh, src/cli/commands/monitor/index.ts, src/cli/commands/test/index.ts, test/acceptance/fake-server.ts, test/jest/acceptance/cli-args.spec.ts, test/tap/cli-fail-on-docker.test.ts, test/tap/cli-monitor.acceptance.test.ts, vendor/global-agent-socket-exception.patch
This commit adds a check for the `containerCliAppVulnsEnabled` feature flag. If neither `--exclude-app-vulns` nor `--app-vulns` are set, the feature flag will be used to determine whether app vulnerabilities will be scanned or not.
Part of the work to enable app vulnerability scanning in containers by default. Build upon @yaronschwimmer's [change](https://github.com/snyk/cli/commit/d2aac4ba96cef4c93e75cbdf800fc2f7f3125192), but that needed some adjustments to ensure the ordering and precedence of flags.
https://snyksec.atlassian.net/browse/MYC-177
=> feat: disable container app scan with feature flag

package-lock.json, package.json
Bump the version of snyk-sbt-plugin to [2.16.1](https://github.com/snyk/snyk-sbt-plugin/releases/tag/v2.16.1)
Includes a fix for `[error] sbt.internal.util.Init$RuntimeUndefined: References to undefined settings at runtime` - filter out configs that are not public.
=> fix: undefined settings in sbt plugin inspect

src/lib/iac/test/v2/scan/index.ts
- Removes the allowed analytics condition for sharing results in the integrated test flow.
- We currently only share results if the following conditions apply:
- The `report` flag was provided.
- Analytics are not disabled. 
However, when analytics are enabled and the user provides the report flag, we don’t display any error indicating that the share results cannot happen, and we still display the project URL at the end of the test output, even though we did not share results.
- In the previous flow, we skipped adding Git contributors when analytics were disabled, the same happens in the integrated flow. 
- In the previous flow, we did not have the allowed analytics as a condition for sharing results. 
- In the current implementation of Share Results we use the Create Scan endpoint of the …
=> fix: remove allow analytics check for share results

src/cli/commands/test/iac/local-execution/assert-iac-options-flag.ts, src/cli/commands/test/iac/scan.ts, src/lib/iac/test/v2/errors.ts, test/jest/unit/iac/assert-iac-options-flag.spec.ts, test/jest/unit/lib/iac/test/v2/errors.spec.ts
Using cloud context without integrated iac flag on your org will now display a message explaining why it doesn't work.
When an error happen with cloud context we now display the error content instead of juste asking the user to re run with -d.
Testing without the iacIntegratedExperience flag will show a new error. Testing cloud context without a proprer configutation or with a wrong snyk cloud environment id are the easiest way to test the error messages.
https://snyksec.atlassian.net/browse/CTX-442
=> [CTX-442] improve errors for cloud context

package-lock.json, package.json
Bumps the Snyk-Docker-Plugin to bring in some fixes to the Go app vulnerability scanning.
See https://github.com/snyk/snyk-docker-plugin/pull/461
=> fix: improve go file path determination

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts
- Adds support for OAuth tokens for requests made to API clients for:
- `snyk/registry`
- `snyk/cloud-api-service`
- This change is made to align with other CLI flows that currently support OAuth tokens authorization, as can be found [here](https://github.com/snyk/cli/blob/27797617920adf60200306348d7b4d61fcc3142c/src/lib/api-token.ts#L11).
- OAuth tokens are prioritized and API keys are the fallback for both API clients.
- [Slack thread](https://snyk.slack.com/archives/CRV0PMFDH/p1667854904910699)
- Relevant PR in `snyk/snyk-iac-test`: [#158](https://github.com/snyk/snyk-iac-test/pull/158)
- Relevant PR in `snyk/cloud-config-policy-engine`: [#611](https://github.com/snyk/cloud-config-policy-engine/pull/611)
=> chore: support oauth tokens

.snyk, package-lock.json, package.json
- Bumps `snyk-gradle-plugin` to `3.24.5`
- https://github.com/snyk/snyk-gradle-plugin/pull/240 - escape child process arguments
=> fix: bump snyk-gradle-plugin to 3.24.5

package-lock.json, package.json
fix: use full version of go modules in dep-graph
- https://github.com/snyk/snyk-docker-plugin/pull/462
- https://github.com/snyk/snyk-docker-plugin/releases/tag/v5.6.4
=> fix: update snyk-docker-plugin

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
upgrade snyk-iac-test to v0.37.0 which upgrades policy-engine to v1.12.1
https://github.com/snyk/snyk-iac-test/pull/161
=> feat: upgrade snyk-iac-test to v0.37.0

src/lib/ecosystems/resolve-test-facts.ts, src/lib/ecosystems/unmanaged/types.ts
Adds support to filter issues/vulnerabilities based on a severity threshold.
1. Change directory to a folder with unmanaged deps
1. Use `snyk test --unmanaged` to verify that you have both "medium" and "high" severity-issues 
1. Test with an organization with unmanaged-deps enabled and run following command: `snyk test --unmanaged --severity-threshold=high`
1. Verify that `medium` and lower was filtered out, and that "high" and "critical" remains
=> feat: support severity threshold (unmanaged)

package-lock.json, package.json, src/lib/request/promise.ts, src/lib/request/request.ts, src/lib/request/types.ts
Upgrading needle from 2.6.0 to 3.0.0.
This version now supports automatically parsing JSON when HTTP responses
send Content-Type application/vnd.api+json header, which the latest Snyk
APIs use.
Explicitly opting out of this automatic parsing in makeRequestRest
because this currently parses a response using Content-Type
application/text.
=> fix: upgrade http client

src/lib/analytics/getStandardData.ts
Add try-catch block around the usage of os-name which throws an exception on macOS Ventura.
=> chore: wrap osName() in try-catch

package-lock.json, package.json
Includes the latest release of snyk-mvn-plugin v.2.32.0 which uses the `/rest/packages` endpoint to 
search for maven coordinated for unmanaged files.
=> fix: use /rest/packages when searching by checksum

src/cli/commands/monitor/index.ts, src/cli/commands/test/index.ts, test/acceptance/fake-server.ts, test/jest/acceptance/cli-args.spec.ts, test/tap/cli-fail-on-docker.test.ts, test/tap/cli-monitor.acceptance.test.ts
This commit adds a check for the `containerCliAppVulnsEnabled` feature flag. If neither `--exclude-app-vulns` nor `--app-vulns` are set, the feature flag will be used to determine whether app vulnerabilities will be scanned or not.
This commit was merged in #4105 and reverted in #4184 again due to an issue with the global-agent patch.
This PR now builds on top of #4205 instead.
=> feat: disable container app scan with feature flag #4105

src/lib/ecosystems/resolve-test-facts.ts
By lowering the minIntervalMs and maxIntervalMs to 2000ms and 20000ms we will decrease the risk for cancellation, and improve the performance.
Lowers number of seconds between retries for tests of unmanaged ecosystems.
Run tests on following [repo](https://github.com/snyk-fixtures/cpp-goof) and make sure it behaves the same as before the diff.
Old implementation used a max value of 30seconds.
30 seconds or more might trigger a cancellation within our system, and that's the intended design.
Therefor we should lower number of seconds for maxIntervalMs.
We did also decrease number of seconds for the minimum number of seconds between retries, which
means that retries will happen more often and it could improve the performance in some situations.
=> fix: improve the time interval for retries during test of unmanaged

src/lib/ecosystems/resolve-test-facts.ts
`getSelf()` can return undefined so that case must be handled,  otherwise the following error will occur:
```
TypeError: Cannot read properties of undefined (reading 'default_org_context')
```
Take a look at the defintion of the `getSelf()`: https://github.com/snyk/cli/blob/e4d0eaf1bbdcec185890894350d67a446452f164/src/lib/ecosystems/unmanaged/utils.ts#L50
=> fix: handle self being undefined

src/cli/commands/test/iac/local-execution/index.ts, src/cli/commands/test/iac/local-execution/usage-tracking.ts, test/jest/unit/iac/usage-tracking.spec.ts
Fixes an issue in IaC usage tracking where it was not passing the org data to Registry, causing it to count for the default org instead of the custom set org. 
- Run registry locally.
- Create another org in the Admin UI.
- Set the CLI to point to the local registry API.
- Set the CLI to the custom org you created, either via the env `SNYK_CFG_ORG` variable or the `--org` flag.  
- Make a CLI scan to an IaC file.
- See in the UI that the test-count was increased to the default org instead of the custom one.
With this branch, the correct test-count for the custom org will be increased.
1. This came up in a [Customer Support Ticket](https://snyk.zendesk.com/agent/tickets/38402), when a customer was using the VS-Code plugin with a custom org to scan IaC files, they mentioned that scan counts …
=> fix: iac usage tracking missing custom org

.github/CODEOWNERS, packages/iac-cli-alert/src/index.ts
- Expands the alert message for the IaC smoke tests alert to make it clearer.
- Adds the alert's runbook to its message.
- Assigns IaC as the owner for the `iac-cli-alert` package.
- [Slack thread](https://snyk.slack.com/archives/C026G6ESL3Y/p1672759266716499)
=> chore: add runbook to iac smoke tests alert

test/smoke/spec/snyk_code_spec.sh
Removes the explicitly specified org from the Snyk Code smoke tests. As part of [#incident-2023-01-05-circelci-security-alert](https://snyk.slack.com/archives/C04HNK0F144) the `SMOKE_TESTS_SNYK_TOKEN` was rotated and the new service user no longer has access to the org.
=> fix: run snyk code test with the default org

package-lock.json, package.json
Bump the version of snyk-gradle-plugin. The latest release includes the following changes:
- we don't support Gradle's configuration caching (introduced in Gradle 7) so we disable config caching by default, even if it's requested by the user: https://github.com/snyk/snyk-gradle-plugin/pull/249
- remove bulky dependencies from test fixtures https://github.com/snyk/snyk-gradle-plugin/pull/250
=> feat: disable gradle config caching by default

cliv2/scripts/sign_darwin.sh
just to ensure that timestamping is being used.
sets `--timestamp` when running `codesign` for macOS signing, so ensure that timestamping is definitely used.
from the codesign man page
>  --timestamp [=URL]
During signing, requests that a timestamp authority server be contacted to authenticate the time of signing. The server contacted is given by the URL value.  If this option is given without a value,
a default server provided by Apple is used.  Note that this server may not support signatures made with identities not furnished by Apple.  If the timestamp authority service cannot be contacted over
the Internet, or it malfunctions or refuses service, the signing operation will fail.
If this option is not given at all, a system-specific default behavior is invoked.  This may result in some …
=> chore: explicitly set —timestamp for codesign

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Upgrades snyk-iac-test to v037.3 which now uses the policy-engine version of v0.14.1
=> feat: update snyk-iac-test to v0.37.3

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/analytics.spec.ts, test/jest/acceptance/extra-certs.spec.ts, test/jest/acceptance/iac/cli-share-results.spec.ts, test/jest/acceptance/snyk-fix/fix.spec.ts, test/jest/acceptance/snyk-test/fail-on.spec.ts, test/jest/acceptance/snyk-test/missing-node-modules.spec.ts
… through an update of the application framework.
Adds support for specifying an Organization (org) as ID or Slugname. 
The actual logic is part of the application framework udpate.
> snyk sbom --experimental -d
Should show the preferred Organization in the debug output.
> snyk sbom --experimental -d --org=id
> snyk sbom --experimental -d --org=slugname
Should show the Organization ID of the specified org in the debug output.
=> feat: support org slugname lookup

src/lib/plugins/sast/analysis.ts, test/jest/unit/lib/analytics/index.spec.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts
This allows SNYK_OAUTH_TOKEN support instead of just API Key.
Passes an OAuth token into the SAST backend if specified.
The tests: `test/jest/unit/snyk-code/snyk-code-test.spec.ts`
`SNYK_OAUTH_TOKEN=$token snyk code test`
Previously we only passed the api key as an auth header.
This method is deprecated (no `token` scheme), and doesn't support OAuth tokens. Use existing header building to do this, so we send `bearer $jwt` if specified.
The backend has already been updated to handle this.
=> feat: pass oauth token to sast, if available

src/cli/commands/test/iac/meta.ts, test/jest/unit/cli/commands/test/iac/meta.spec.ts
The `snyk iac test` command doesn't properly parse the Git remote URLs set by `actions/checkout` in GitHub workflows. These URLs are like `https://github.com/user/repo`, which is not a format that the command currently understand. The consequence of this bug is that using `--report` in GitHub actions generates malformed project names as shown below:
=> fix: Correctly parse the remote URLs set by actions/checkokut

cliv2/go.mod, cliv2/go.sum, cliv2/internal/cliv2/cliv2.go, cliv2/internal/cliv2/cliv2_test.go, cliv2/internal/embedded/sha.go, cliv2/internal/utils/directories.go, cliv2/main_integration_test.go, cliv2/pkg/basic_workflows/legacycli.go, test/jest/acceptance/parallel-execution.spec.ts
* Fix a race condition when multiple CLIs are executed at the same time. Therefore it introduces the usage of a filelock using https://github.com/gofrs/flock. 
* Refactor code and introduce Init() to have all code that alters the filesystem together and the synchronization is easy to apply.
* Fixed a bug in ClearCache() which didn't actually count deleted contents to end the loop.
* Improved debug logging
which caused failing tests main_integration_tests.go, instead of adapting these not sustainable tests, I cleaned up most of them, since we have either unit tests or jest acceptance tests covering the functionality. Removing this test suite completely requires more cleanup which should better be done in HEAD-60
* cliv2/internal/cliv2/cliv2.go
Run a script like the one below to spawn …
=> fix: avoid filesystem concurrency during initialization

cliv2/cmd/cliv2/main.go, cliv2/internal/cliv2/cliv2.go, cliv2/pkg/basic_workflows/legacycli.go
* Check if the specified cache directory is an empty string before trying to create it.
* Moved some logging to main for better debugging
=> fix: check if cachedir is empty

src/cli/commands/monitor/index.ts, src/cli/commands/test/index.ts, src/lib/formatters/test/format-test-results.ts, test/acceptance/fake-server.ts, test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts, test/jest/unit/ecosystems-monitor-docker.spec.ts, test/jest/unit/lib/formatters/test/__snapshots__/display-result.spec.ts.snap, test/tap/cli-monitor.acceptance.test.ts, test/tap/cli-test/cli-test.docker.spec.ts
Enables container app scan by default. We are introducing a new flag,
`exclude-app-vulns` in case a user would like to disable app scan.
`snyk container test <image_with_app>` should return app scan results without additional parameters.
`snyk container test --exclude-app-vulns <image_with_app>` should return only operating system scan results.
https://snyksec.atlassian.net/browse/MYC-56
=> feat: container app vulns by default

Makefile
Remove the explicit exclude of changes in the cliv2 directory from the Changelog.
=> chore: enable Extensible CLI changes in release notes

cliv2/go.mod, cliv2/go.sum, cliv2/internal/cliv2/cliv2.go
We can’t use MkdirAll since it’ll result in concurrency issues. Log information if user is trying to use a cache directory path with sub-directories. Also update go-application-framework to use version that returns “snyk” instead of an empty string in case of an error creating a cache directory
[JIRA ticket](https://snyksec.atlassian.net/browse/HEAD-84)
=> chore: improve cache directory

src/lib/config/api-url.ts, src/lib/config/index.ts, test/jest/unit/config/api-url.spec.ts
Previously we assumed that the root hostname shouldn't start with "app." but this is actually the consistent endpoint for  cross region usage.
=> fix: host URL for instances in different regions

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/snyk-config/snyk-config.spec.ts
In addition to SNYK_API the Extensible CLI now supports the endpoint being configured via `snyk config endpoint=<value>`. Therefore the go-application-framework was updated.
* The actual logic is in the go-application-framework
* The newly added test
`snyk config endpoint=https://app.eu.snyk.io/api`
`snyk auth`
--> should lead to authenticate against https://app.eu.snyk.io
=> Fix: support configured endpoint in Extensible CLI

package-lock.json, package.json, src/cli/index.ts, src/lib/common.ts
Introduces a check and warning if the platform the CLI runs on is actually not supported.
Example of the message. The shown platform is supported.
=> chore: check if the platform is supported

cliv2/cmd/cliv2/main.go
Improves logging format and contents of the Extensible CLI.
Now printing a common debug header like this
> 2023/01/31 12:06:53.176236 main - Version:        1.1092.0
> 2023/01/31 12:06:53.176256 main - Platform:       darwin arm64
> 2023/01/31 12:06:53.176260 main - API:            https://app.snyk.io/api
> 2023/01/31 12:06:53.176264 main - Cache:          /Users/username/Library/Caches/snyk
> 2023/01/31 12:06:53.176266 main - Token-Hash:     8f6a2dc9a14238c5bc319c6919e7ea89
> 2023/01/31 12:06:53.176267 main - Organization:   aaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee
> 2023/01/31 12:06:53.176269 main - Insecure HTTPS: false
=> chore: add additional debug info

.circleci/config.yml, Makefile, release-scripts/upload-artifacts.sh, release-scripts/validate-npm-artifacts.sh, release-scripts/validate-repository.sh
Split deployment into the following stages (in preparation for HEAD-57)
* Pre-release
* Test Release
* Release
Test Release now runs on the three main OS (linux, win, macos)
.circleci/config.yml
* Can't final test is a release
* A successful run without publishing can be found [here](https://app.circleci.com/pipelines/github/snyk/cli/16653/workflows/c4bf002f-a5f7-4e45-be78-46f1672f7fa2)
=> feat: improve deployment testing

package-lock.json, package.json
Support --dev flag and --maven-aggregate-project. The --maven-aggregate-project flag now defaults to non test scope dependencies. Only when using --dev will Snyk include test scope dependencies.
This is more inline with the way other Snyk plugins work, defaulting to production dependencies only.
See https://github.com/snyk/snyk-mvn-plugin/pull/144
=> fix: maven aggregate project test scope

.circleci/config.yml, Makefile, ts-binary-wrapper/bin/snyk, ts-binary-wrapper/package-lock.json, ts-binary-wrapper/package.json, ts-binary-wrapper/src/bootstrap.ts, ts-binary-wrapper/src/common.ts, ts-binary-wrapper/test/acceptance/basic.spec.ts, ts-binary-wrapper/test/unit/common.spec.ts
Publishing a thin TS Wrapper for the Golang based Extensible CLI to NPM, as a replacement for the previously published TS CLI.
=> feat: Release Extensible CLI via npm

package-lock.json, package.json
This bumps the version of snyk-gradle-plugin. Changes included:
- allow using Gradle daemon to improve performance: https://github.com/snyk/snyk-gradle-plugin/pull/253
- https://github.com/snyk/snyk-gradle-plugin/pull/251
=> feat: allow gradle daemon usage on unix based systems

src/lib/snyk-test/run-test.ts
Allows up to five requests to the `/test-dep-graph` endpoint to be run at a time, reducing `snyk test` wall-clock run times.
There should be no change to outputs or the running order of operations.
There's only one changed file - `src/lib/snyk-test/run-test.ts`.
On a sample repository with multiple Open Source projects within it (ideally ones for which the `/test-dep-graph` API call takes non-trivial amount of time to complete - nuget projects seem to be good for this), run `snyk test --all-projects` for this version of the CLI and compare with `snyk test --all-projects` for another version. The outputs should be identical, but this version should run significantly quicker - specifically in the phase where the spinner displays "Querying vulnerabilities database...".
We've had support …
=> feat: parallel test-dep-graph requests

.circleci/install-sdks-unix.sh
The AdoptOpenJDK distribution of the Java JDK has been renamed, and this is blocking the release pipeline. This PR updates the test setup to install version `11.0.17-tel` of the JDK rather than `11.0.11.hs-adpt`, as its nearest replacement.
=> fix: missing sdkman java version

release-scripts/validate-repository.sh
As a test before pre-releasing to the S3 bucket, ensure that the version is not already there.
=> fix: add check if the s3 bucket contains the version already

release-scripts/validate-repository.sh
due to a fatal exception in git
=> fix: usage of git tag instead of describe

cliv2/go.mod, cliv2/go.sum
We recently extended the SBOM Export API with additional output formats, which enables users to specify a format when running the SBOM command, e.g.
```bash
$ snyk sbom --experimental --format=spdx2.3+json
```
This upgrade the CLI Extension to the latest version which documents the new SBOM formats.
=> chore: upgrade SBOM CLI Extension

src/cli/commands/test/iac/local-execution/file-utils.ts, src/cli/commands/test/iac/local-execution/local-cache.ts, test/jest/unit/iac/file-scanner.spec.ts, test/jest/unit/iac/local-cache.spec.ts
Following a [feedback](https://snyk.slack.com/archives/CEPPB1XNE/p1675794455260329) from @lirantal, we've decided to move the location of the `iac-data` folder from the cwd to the Snyk CLI cache directory.
In addition to that, this PR creates a sub-dir in `iac-data` with a random name to allow the IDE to run several scans concurrently without any problem. 
run IaC commands and check that they are still running and working as expected.
=> fix: ./iac-data/ location

src/lib/errors/unsupported-entitlement-error.ts
Fix to display the entitlement variable when Entitlement error is thrown, with a fall back;
https://github.com/snyk/cli/issues/4268
=> fix: entitlement error should explain which entitlement

package-lock.json, package.json, src/lib/plugins/sast/analysis.ts
Continuation for [code-client#169](https://github.com/snyk/code-client/pull/169):
> fix: fixed http library to properly set API header with organization name
>
>Currently, we don't set a header with organization name for getAnalysis call.
>These changes are all internal and don't affect public API
=> fix: pass org to code-client

.circleci/config.yml, .circleci/install-sdks-unix.sh, cliv2/scripts/sign_windows.sh
* Replace the usage of `sdkman` by `apt-get` on linux and `brew` on macos
* Also update timestamp url for windows signing, since the old one started failing.
=> fix: use apt-get instead of sdkman

src/cli/commands/test/iac/local-execution/types.ts, src/cli/commands/test/iac/v2/assert-iac-options.ts, src/cli/commands/test/iac/v2/index.ts, src/lib/formatters/iac-output/text/formatters.ts, src/lib/iac/test/v2/errors.ts, src/lib/iac/test/v2/json.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/scan/results.ts, src/lib/iac/test/v2/types.ts, test/fixtures/iac/depth_detection/one/one.tf
This PR adds initial support for Snyk Cloud custom rules to `snyk iac test` behind a feature flag. I also needed to fix a bug that caused non-fatal parse errors to be treated as fatal, because the most recent policy-engine emits those non-fatal errors in more situations than it used to. After this PR, we'll just debug log those errors until we can design a better way to communicate them.
Please reach out to me and I can help you get setup to test.
`CLOUD-1176`
A custom rule in the results:
=> feat: add cloud custom rules to iac behind feature flag

src/lib/formatters/iac-output/text/issues-list/issue.ts
[A user reported a bug](https://snyk.slack.com/archives/C034QFM0DH8/p1677532733366459) where we don't output the remediation advice for custom rules in our CLI.
The cause of the issue was the fact that in our custom rules SDK we named the remediation advice field `remediation` and not `resolve`.
This PR fixes this issue by adding the relevant logic to consider this case.
Using a custom rule, run `snyk iac test` and check for remediation advice in output.
https://snyk.zendesk.com/agent/tickets/42713
=> fix: custom rules remediation output

src/cli/commands/apps/create-app.ts, src/lib/apps/constants.ts, src/lib/apps/create-app/index.ts, src/lib/apps/prompts.ts, src/lib/apps/types.ts, test/jest/acceptance/snyk-apps/create-app.spec.ts
Add a new flag `--context` to the Snyk Apps create command.
Run `apps create`, both with and without `--interactive` is supported.
The context flag is just passed to the create app endpoint, at this time we accept 'tenant' (the old option) and 'user'. This is to support Snyk Apps that act on behalf of users rather than utilising a bot user.
=> feat: add context flag to Snyk App create command

ts-binary-wrapper/src/common.ts
Move "Download" message to stderr to not interfer with other output
=> fix: move message from stdout to stderr

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
This PR updates `snyk-iac-test` to v0.40.4. This version fixes a bug in the custom rules feature flag check.
Please reach out to me for help with manual testing.
=> fix: bump snyk-iac-test to v0.40.4

package-lock.json, package.json
Upgrade docker plugin to resolve OCI errors and go 1.20 support
=> fix: upgrade docker plugin to resolve OCI errors and go 1.20 support

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
This commit upgrades snyk-iac-test to v0.41.0. This release contains a fix for a bug which caused Terraform parser errors to be treated as non-fatal.
This fixture file can be used to demonstrate the bug fix:
```
test/fixtures/iac/terraform/sg_open_ssh_invalid_hcl2.tf
```
The current version of the Snyk CLI will output the parser errors as warnings when the `-d` flag is specified, but otherwise continues to parse the file. After this change, it will produce a `Failed to parse input` error:
```
Snyk Infrastructure as Code
Test Failures
Failed to parse input
Path: test/fixtures/iac/terraform/sg_open_ssh_invalid_hcl2.tf
```
This bug was introduced by a change to treat undefined variables as non-fatal. After this change, undefined variables will continue to be treated as non-fatal, whereas …
=> chore: bump snyk-iac-test to v0.41.0

package-lock.json, package.json
since setuptools version 67.1.0 our cli is failing when any dependency/transitive has an unsupported version (i.e. ">dev")
this change includes the changes in the snyk-python-plugin to fix this. link: https://github.com/snyk/snyk-python-plugin/pull/203
=> fix: support new setuptools version

package-lock.json, package.json, src/lib/plugins/get-multi-plugin-result.ts, src/lib/plugins/nodejs-plugin/index.ts, src/lib/plugins/nodejs-plugin/npm-lock-parser.ts, src/lib/plugins/nodejs-plugin/npm-workspaces-parser.ts, test/acceptance/workspaces/npm-package-lockfile-v2/package-lock.json, test/acceptance/workspaces/npm-package-lockfile-v2/package.json, test/acceptance/workspaces/npm-package-lockfile-v3/package-lock.json, test/acceptance/workspaces/npm-package-lockfile-v3/package.json, test/jest/unit/lib/plugins/get-multiplugin-result.spec.ts, test/tap/cli-test/cli-test.npm.spec.ts
This adds cli support for `package-lock` versions 2 and 3. These versions have been in use since npm7.
Previous support for npm-lock-v2 exists but was using older `dep-tree` logic. This PR also upgrades this to use dep-graph solely.
=> feat: npm lock v2 and v3 support

ts-binary-wrapper/test/acceptance/basic.spec.ts
This PR should test that the binary wrapper does not output to stdout. If it does, it could lead to issues when products use the cli output
=> chore: test that binary wrapper does not output to stdout [HEAD-202]

src/lib/snyk-test/run-test.ts
This PR adds some debug info to the failed `sendTestPayload` request. This will help debugging upstream issues.
=> feat: add debug info for failed send test payload request

cliv2/cmd/cliv2/main.go
Add `User-Agent` HTTP header to requests to identify Snyk CLI versions out there from the backend.
=> feat: add user-agent header to HTTP requests

package-lock.json, package.json
This bumps the nodejs parser version. For details please see https://github.com/snyk/nodejs-lockfile-parser/releases/tag/v1.48.1
=> fix: bump nodejs parser to 1.48.1

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, cliv2/pkg/basic_workflows/legacycli.go
This PR should update the go-application-framework dependency and allow the CLI to pass a logger when creating the app engine
=> chore: pass logger into updated gaf

package-lock.json, package.json
This bumps the nodejs parser version. For details please see https://github.com/snyk/nodejs-lockfile-parser/releases/tag/v1.48.2
=> fix: bump nodejs parser to 1.48.2

src/cli/commands/test/iac/v2/index.ts, src/lib/config/index.ts, src/lib/iac/test/v2/index.ts, src/lib/iac/test/v2/local-cache/index.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/local-cache/rules-bundle/index.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/types.ts, test/jest/unit/lib/iac/test/v2/setup/local-cache/index.spec.ts
This is a "hidden" (aka for development) env var to override the url of the rulesClient that is being used later in snyk-iac-test, to create a client for opa-rules-distribution. With this flag, we will be able to test bundles in development, while going through the opa-rules-distribution automatic download process.
To use locally:
``` 
SNYK_IAC_RULES_CLIENT_URL=https://something.com snyk-dev iac test test/fixtures/iac/terraform/sg_open_ssh.tf
```
To use with this branch: https://github.com/snyk/snyk-iac-test/pull/187: build the executable and run:
```
SNYK_IAC_RULES_CLIENT_URL=https://something.com SNYK_IAC_POLICY_ENGINE_PATH=~/snyk-repos/snyk-iac-test/snyk-iac-test  snyk-dev iac test test/fixtures/iac/terraform/sg_open_ssh.tf
```
Override with the bucket we already have:
Override with a …
=> feat: add `IAC_RULES_CLIENT_URL` to override the URL of the rules client [CCSC-1536]

cliv2/go.mod, cliv2/go.sum
Through the update of the application framework the oauth authentication will also be added for requests to deeproxy.
=> feat: support oauth for deeproxy

cliv2/cmd/cliv2/main.go, cliv2/cmd/cliv2/main_test.go
Fix logic to ensure that in case of usage errors for commands that are implemented as Extension, the help is properly shown.
=> fix: Help behaviour for Extensions

src/cli/commands/test/iac/local-execution/file-scanner.ts, src/cli/commands/test/iac/local-execution/types.ts
Users and other Snyk tools(`snyk-to-html` for example) expect to have a `resolve` field with remediation advice for each IaC issue.
Currently, IaC issues that got generated by using custom rules will not have this field, this PR fix this issue.
https://snyk.slack.com/archives/C034QFM0DH8/p1680119186872949
Before
After
=> fix: custom rules json output missing `resolve` field

package-lock.json, package.json
This bumps the nodejs parser version. For details please see https://github.com/snyk/nodejs-lockfile-parser/releases/tag/v1.48.3
=> fix: bump nodejs parser to 1.48.3

package-lock.json, package.json, src/lib/plugins/sast/analysis.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts
Pass additional parameters related to Code CLI uploads/reporting to `analyzeFolders`.
TODO:
```
snyk code test --report --org=test-org --project-name=test-project --target-name=test-target --target-reference=test-ref --remote-repo-url=https://test.com
```
=> fix: send additional report options to analyzeFolders [ZEN-556]

package-lock.json, package.json
This PR upgrade `snyk-nuget-plugin` dependency to `1.24.1` in order to fix a bug where large dotnet project files would fail to test.
Further information is in https://github.com/snyk/snyk-nuget-plugin/pull/131
=> fix: upgrade nuget plugin - enable large dotnet core projects

.github/workflows/iac-smoke-tests.yml, .github/workflows/smoke-tests.yml, .github/workflows/snyk-protect-production-smoke-tests.yml
=> chore: run smoketests only at 11 pm instead of hourly

package-lock.json, package.json, src/lib/plugins/nodejs-plugin/npm-lock-parser.ts, src/lib/plugins/nodejs-plugin/npm-workspaces-parser.ts
This bumps the version of `snyk-nodejs-lockfile-parser` please see here for details: https://github.com/snyk/nodejs-lockfile-parser/releases/tag/v1.49.0
=> feat: bump nodejs parser version 1.49.0

cliv2/Makefile
`cliv2/Makefile` is using `echo` in a way that relies on MacOS/zsh specifics, where `echo` will interpret escape sequences by default.  This not the case everywhere. Using `echo -e` works on some platforms (zsh and bash) but it's not part of POSIX, so using `printf` is the most idiomatic way to do it.
N/A
1. Run `bash`
2. Run `echo "foo\nbar"` -- escaping is not interpreted
3. Run `printf "foo\nbar"`  -- outputs foo and bar with a newline between them
Without this, we write badly formatted files to `_cache/variables.mk` and `_cache/version.mk`, e.g.:
```
$ cat _cache/variables.mk
GOOS=linux\nGOARCH=amd64\n
```
This causes a bizarre interpretation of `$GOOS` leading to bizarre files like:
```
Generating ( /home/jasper/Snyk/cli/cliv2/internal/embedded/cliv1/embedded_linux\nGOARCH=amd64\n_amd …
```
=> fix: use printf rather than echo for escaping in cliv2 Makefile

test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
To unblock the pipeline, skip a test that is only failing in CI.
=> fix: temporarily skip failing gradle test

package-lock.json, package.json
The new version contains a fix for Go binary scanning on Windows.
See https://github.com/snyk/snyk-docker-plugin/pull/485.
=> fix: bump snyk-docker-plugin

cliv2/Makefile
On macos security tools might consider the binary insecure when it copies over an already existing binary.
This is why, we remove the binary before copying it to the install directory.
=> fix: avoid security tools to kill installed binaries

.circleci/config.yml, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
- Fixes Gradle acceptance test by pinning Ubuntu image used in the pipeline to the one with JDK 11.
The problem stem from the current version [updated lately](https://discuss.circleci.com/t/ubuntu-linux-vm-machine-images-2022-april-q2-update/43749) by CircleCI.
- Pins image version for Linux executor as well.
=> fix: gradle acceptance test [HEAD-283]

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/cli-token-precedence.spec.ts
* Some of the configuration initialization logic previously done in the application framework is more specific to the CLI, so we moved it out of the framework to the CLI code.
* Also the logic about token precedence required a small change for oauth authentication.
cmd/cliv2/main.go
=> chore: moved logic from application framework to CLI

package-lock.json, package.json
upgrades a version of the snyk-python-plugin to support newer versions of setuptools (>=67.0.0)
=> fix: support new setuptools

package-lock.json, package.json
This bumps the version of `snyk-go-plugin` to v1.21.0 for additional details see https://github.com/snyk/snyk-go-plugin/pull/111
=> feat: bump go plugin v1.21.0

package-lock.json, package.json, src/cli/main.ts
Makes sure that the CLI exits with error codes provided by the snyk-cpp-plugin.
Run `snyk test --unmanaged` with:
- an empty project (dir)
- an unmanaged project
Sanity-check the behaviour for Snyk's goof-project, so that existing logic for managed ecosystems is not broken.
Make sure the exit values follow the values specified in
`snyk test --help`
=> fix: respect exit codes for unmanaged

src/lib/feature-flags/index.ts, test/jest/unit/lib/feature-flags/feature-flags.spec.ts
Enforces the usage of integrated IaC (disables standalone IaC) for FedRAMP.
-
1. Set the endpoint like: `snyk-dev config set endpoint=http://api.snykgov.io/v1`
2. `snyk-dev iac test (-- report)` and see integrated IaC is used
In the future we will transition all our customers to the integrated IaC and decommission the standalone one. 
So no real disablement here, just enforcing the new flow on which we focus to make compliant.
[CFG-2291](https://snyksec.atlassian.net/browse/CFG-2291)
-
-
[CFG-2291]: https://snyksec.atlassian.net/browse/CFG-2291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: disable standalone iac for fedramp

src/lib/ecosystems/resolve-test-facts.ts, test/jest/unit/lib/ecosystems/resolve-test-facts.spec.ts
Removes check of unused feature flag to decide which endpoint to use for tests of unmanaged source code.
- Removes support for USE_UNMANAGED_DEPS environment variable
- Removes support for snykNewUnmanagedTest feature flag
0. Use `snyk test --unmanaged` with an installation that has not been authenticated
1. Verify that the user receives a human readable reply, informing the user it's not authenticated
2. Run `snyk auth` to authenticate
3. Test the build with an unmanaged project, with following command `snyk test --unmanaged`
4. Verify the output correspond to the expected output
=> fix: remove feature flag used to toggle old and new unmanaged service

package-lock.json, package.json
This bumps the snyk-go-plugin version to 1.23.0 - for more info see here https://github.com/snyk/snyk-go-plugin/releases
=> feat: bump go plugin to v1.23.0

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum
Bumping GAF version.
Also, when determining oauth token precedence, replace the existing default value function for `FF_OAUTH_AUTH_FLOW_ENABLED`, by explicitly setting it to false if necessary.  This enables deriving the oauth feature flag from the endpoint.
=> chore: bump GAF version to include OAuth

cliv2/cmd/cliv2/main.go, cliv2/cmd/cliv2/main_test.go, test/jest/acceptance/analytics.spec.ts
This PR adds alternative config parameter names, to support previously communicated ways to disable analytics (e.g. https://docs.snyk.io/snyk-cli/configure-the-snyk-cli/configure-snyk-cli-to-connect-to-snyk-api, https://snyk.io/policies/tracking-and-analytics/)
This is achieved by registering aliases for the `ANALYTICS_DISABLED` configuration key.
```
config.AddAlternativeKeys(configuration.ANALYTICS_DISABLED, []string{"snyk_analytics_disabled", "disable-analytics", "disable_analytics", "snyk_cfg_disable_analytics"})
```
https://github.com/snyk/cli/blob/277a1e0a1432201ffeed9b3a3eb64e8e791e75c3/cliv2/cmd/cliv2/main.go#L91
use `snyk config set disable-analytics=1` and start snyk with -d. It should NOT output any text in the end regarding sending analytics. …
=> fix: respect different ways to disable analytics

src/lib/feature-flags/index.ts, test/jest/unit/lib/feature-flags/feature-flags.spec.ts
Following the merge of [this PR](https://github.com/snyk/registry/pull/31790), the check we are currently doing in the CLI to enforce the Integrated IaC experience in the FedRAMP environment is not needed anymore.
This PR basically deletes all the logic/test that was added in [this PR](https://github.com/snyk/cli/pull/4597).
https://snyksec.atlassian.net/jira/software/c/projects/CFG/boards/301?modal=detail&selectedIssue=CFG-2413
=> chore: remove integrated IaC FF check in FedRAMP env [CFG-2413]

package-lock.json, package.json, src/lib/plugins/nodejs-plugin/npm-lock-parser.ts, src/lib/plugins/nodejs-plugin/yarn-workspaces-parser.ts, test/tap/cli-test/cli-test.yarn-workspaces.spec.ts
We have recently introduced a fix in our yarn parsing logic of Node package files that now creates a depGraph directly, instead of the legacy depTree logic, which required doing a lot of conversions back and forward.
Now we're introducing the use of this parser in the CLI for generating yarn-workspace results, which increases the performance of scanning yarn workspaces tremendously.
Scanning a yarn workspace with 72 projects in it using `snyk test --yarn-workspaces --detection-depth=3`
Previous: 32 minutes
This fix: 43 seconds
An increase of 45x.
=> feat: [SUP-1093] improve cli yarn performance for yarn workspaces

cliv2/Makefile
Add ldflags=-s -w to the go build
=> fix: remove debug symbols to reduce binary size

package-lock.json, package.json
The previous version of SwiftPM had some broken logic that would cause dependency graph generation to error out in some cases.
This is now [fixed](https://github.com/snyk/snyk-swiftpm-plugin/pull/28).
=> feat: bump SwiftPM

.circleci/config.yml
Missing copy step for alpine binaries, which causes them to not be deployed.
After merging and releasing, download the alpine binary and run `snyk sbom`
=> fix: add final copy step to deploy alpine binaries

.circleci/config.yml
[Jira ticket](https://snyksec.atlassian.net/browse/HEAD-267)
Replace deprecated macos Cirecle CI runner with the new runner. This will make testing and signing our macos binaries a lot faster.
=> chore: replace deprecated macos CCI runner

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
bump snyk-iac-test to 0.45.2 that uses the newest opa version (0.53.0)
=> bump snyk-iac-test to 0.45.2

package-lock.json, package.json, src/lib/plugins/nodejs-plugin/yarn-workspaces-parser.ts
This change simply passes workspace information to the yarn parser when we are parsing yarn 2+ workspaces projects
=> fix: pass resolution to yarn workspaces parser

test/jest/acceptance/iac/output-formats/text.spec.ts
Fix failing tests in 'test/jest/acceptance/iac/output-formats/text.spec.ts'
=> chore: Fix failing IaC acceptance tests

cliv2/pkg/basic_workflows/legacycli.go
Always modify HTTP headers from the legacy CLI to make them consistent with headers from the Extensible CLI.
=> feat: Enable header modification for all legacy CLI requests

src/lib/formatters/get-sarif-result.ts, test/jest/unit/lib/formatters/get-sarif-result.spec.ts
When using sarif as output and the Dockerfile is not specified, the `path` is used as the sarif results location uri (added with PR: https://github.com/snyk/cli/pull/4649). 
But the `path` can contain colon characters (e.g. between repo and tag) and GitHub Code Scanning seems to return an error in that case. 
Replaces the colon characters from the sarif results location uri with underscore characters.
Issue: LUM-257
=> fix: container sarif replace colon within location uri

.circleci/config.yml
* Update golang to 1.20.5
* Pin th build image to a fix version to avoid breaking pipelines when we work on the build image.
=> feat: update to golang 1.20.5 and pin build image version

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, test/jest/acceptance/iac/test-cloudformation.spec.ts
Upgrades `snyk-iac-test` to latest that has the latest rules bundle and policy engine
The checksums are from here: https://github.com/snyk/snyk-iac-test/releases/tag/v0.47.3
Have an org with integrated IaC and try `snyk iac test` for it.
-
-
-
-
=> chore: upgrade snyk-iac-test to latest (latest rules bundle and policy engine)

test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts
Increased timeout from 10s to 30s, to avoid test flakiness.
=> chore: increase timeout to avoid flaky tests

package-lock.json, package.json, test/acceptance/workspaces/npm-package-lockfile-v3-bundled-deps/package-lock.json, test/acceptance/workspaces/npm-package-lockfile-v3-bundled-deps/package.json, test/tap/cli-test/cli-test.npm.spec.ts
This bumps nodejs parser 1.52.1
The changes in this lib update allow more accurate dependency resolution of transitive dependencies in npm lockfile v2 and v3 projects that use bundled dependencies. 
There is an [existing acceptance test](https://github.com/snyk/cli/blob/master/test/tap/cli-test/cli-test.npm.spec.ts#L36-L46) that should cover any breaking behavior and we have added a new one that takes a test fixture from the library to add another layer of testing on this specific feature.
=> chore: bump nodejs parser 1.52.1

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum
* Update GAF to replace TOKEN as configuration key by SNYK_TOKEN
* Remove now unnecessary SNYK_TOKEN alias
=> fix: Colliding Environment Variables TOKEN and SNYK_TOKEN

.circleci/config.yml, .github/CODEOWNERS, package-lock.json, packages/snyk-fix/package.json, test/fixtures/snyk-fix-pipenv/Pipfile, test/fixtures/snyk-fix-pipenv/Pipfile.lock, test/jest/acceptance/snyk-fix/dep-graph-response.json, test/jest/acceptance/snyk-fix/fix.spec.ts
Currently the `snyk fix` command fails to run due to the subshell running `poetry` and `pipenv` being unable to make network requests to pypy. This is due to the proxy configuration used by the Go wrapper. We've now updated the `@snyk/child-process` library in snyk/python-fix to reset these environment variables before invoking the subshell. This fixes the issue.
The change here is to bump the sub dependencies in the `snyk-fix` package to use the latest @snyk/child-process library (see: https://github.com/snyk/python-fix/pull/68).
This was tested on the above pipenv project and with the changes we can now successfully run `snyk fix` with no errors.
NOTE: We also update the CODEOWNERS to move ownership of snyk-fix from Tech Services over to Team Fix.
=> fix: restore ability for snyk fix to make network requests [FIX-138]

.gitleaksignore, package-lock.json, package.json, src/lib/plugins/sast/analysis.ts, src/lib/plugins/sast/types.ts, src/lib/types.ts, test/fixtures/sast/sample-analyze-scm-project-response.json, test/jest/unit/snyk-code/snyk-code-test-report.spec.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts
Implements support for running Code tests against existing SCM projects and uploading/reporting results under them.
AKA CLI Uploads Phase 2, AKA CLI-triggered SCM Tests.
Follows the existing `--report` flow logic, with some distinctions:
- It is triggered by providing `--project-id` and `--commit-id` instead of `--project-name` as used by the files flow. That is because the files flow can create or fetch a CLI project, whereas this one relies on an SCM Code project existing.
- It calls `analyzeScmProject` from `code-client`, instead of `analyzeFolders`. That is because it triggers an SCM analysis in our backend, and does not need to upload local files first like the file-based flow.
Otherwise the interfaces and handling logic are very similar.
```
export …
```
=> feat: add SCM report test support [ZEN-668]

test/smoke/spec/snyk_fix_spec.sh
Adapt regression test for snyk fix, to unblock the build pipeline.
=> chore: temporarily adapt tes expectation

package-lock.json, package.json
Updates package version for `code-client`.
Updated version removes project-name length limit for Code Report flow.
More context [here](https://snyk.slack.com/archives/C01DGQ3AT09/p1689238829165069).
=> fix: update code-client version

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum
This PR should avoid potential env var collisions by not using the generic env var name `BEARER_TOKEN`.
=> fix: do not use generic bearer_token naming

src/lib/formatters/iac-output/text/issues-list/index.ts, src/lib/formatters/iac-output/text/types.ts, src/lib/iac/test/v2/analytics/iac-type.ts, src/lib/iac/test/v2/scan/results.ts
- Defines the file path for resources associated with IaC+ test issues as optional.
- Test an IaC file that generates issues without an associated file origin, e.g., an issue for a non-existing resource that needs to be added.
- Ensure the test output for the CLI test is generated as expected.
- [A support thread](https://snyk.slack.com/archives/C034QFM0DH8/p1690280367869079) revealed that we currently incorrectly assume that all the resources associated with a generated IaC+ issue have a file origin.
- Looking at the [CLI code](https://github.com/snyk/cli/blob/bc7ecc2a5552e92c12b514c3ef37341ac0106eb4/src/lib/iac/test/v2/scan/results.ts#L117-L118), we currently assume the file path is required for resources.
The resource file paths for issues are retrieved from `snyk-iac-test`, after …
=> fix: make IaC issue resource file optional

test/jest/acceptance/iac/output-formats/text.spec.ts
Fixes an IaC test that from time to time fails when rules change. In order for this to not happen again - the assertions were changed to be more generic and only care about the format of the output and not the actual output.
See a recent failure: [here](https://app.circleci.com/pipelines/github/snyk/cli/19045/workflows/10172117-6b97-4eea-a556-22d3b2482d66/jobs/282447)
See an ask for this: [here](https://snyk.slack.com/archives/C02JMMTLUF9/p1691564705804269)
`npm run test:acceptance` (test/jest/acceptance/iac/output-formats/text.spec.ts)
-
-
=> fix: assertions for the iac output formats test to be more generic

.circleci/chocolatey.config, .circleci/config.yml, Makefile, cliv2/Makefile, cliv2/cmd/cliv2/main.go, cliv2/internal/cliv2/cliv2.go, cliv2/internal/cliv2/cliv2_test.go, cliv2/internal/embedded/cliv1/cliv1.go, cliv2/internal/embedded/cliv1/dummy_embedded_legacy_cli.go, scripts/download_go.py
* This PR introduces a new way to download and install the golang version used for building the CLI. 
* This enables to use different golang versions besides the google version, we are looking towards using the MS Go Fork in the future.
* It also includes some pipeline refactorings to unify the build job.
* In addition it supports detecting the GOEXPERIMENT values introduced in the [MS Go Fork](https://github.com/microsoft/go/tree/microsoft/main/eng/doc/fips#usage-build) to enable FIPS validated crypto.
The different build steps should include log messages like this
```
-- Pre-paring to build
--  Using Go:        ***/go/bin/go
--  Building Binary: ***/snyk/cliv2/_bin/snyk-linux
--  GOEXPERIMENT:    
```
The _download go binary_ step should include
`--base_url=https://go.dev/dl/`
Currently …
=> feat: build windows and linux binaries with fips enabled Microsoft Go Fork

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum
* Show fips status in logs
* Panic if fips is enabled in a non fips CLI
WIth a CLI that wasn't build with FIPS enabled, running the call below should panic
> GOFIPS=1 snyk test
Setting GOFIPS=0 the CLI should run normally.
=> feat: add fips status 

src/lib/ecosystems/test.ts, src/lib/snyk-test/assemble-payloads.ts, src/lib/snyk-test/common.ts, src/lib/snyk-test/run-test.ts, test/jest/acceptance/snyk-container/container.spec.ts
This commit adds support for the `--print-graph` argument that will print the dependency graph after a container scan. We need this feature in order to build the `snyk container sbom` command later on.
The flag works the exact same way as the normal `snyk test --print-graph` does.
=> chore: implement --print-graph for container

src/cli/commands/test/iac/local-execution/assert-iac-options-flag.ts, src/cli/commands/test/iac/local-execution/types.ts, src/cli/commands/test/iac/v2/assert-iac-options.ts, src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/analytics/iac-cloud-context.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/types.ts, test/jest/unit/iac/assert-iac-options-flag.spec.ts, test/jest/unit/lib/iac/test/v2/analytics/fixtures/iac-analytics.json, test/jest/unit/lib/iac/test/v2/analytics/index.spec.ts
This PR removes the `--cloud-context` flag, as it was deprecated and scheduled for removal before releasing IaC+ to a wider public.
=> IAC-2550 - Remove the --cloud-context flag

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Upgrades `snyk-iac-test` to the latest version. This fixes a bug where CloudFormation templates with non-string tags could not be scanned and silently failed the whole scan.
=> feat: upgrade snyk-iac-test

src/lib/iac/test/v2/errors.ts
Updates the error message for `EvaluationError` warnings after getting feedback from this [thread](https://snyk.slack.com/archives/C034QFM0DH8/p1691695718161549).
=> feat: update EvaluationError message

package-lock.json, package.json
This PR updates the version of the snyk-docker-plugin dependency.
The snyk-docker-plugin did not handle correctly in the previous version the case when the docker daemon is unavailable, and both the image digest and tag are passed as arguments. The bug is fixed in the new version.
Snyk-docker-plugin PR: https://github.com/snyk/snyk-docker-plugin/pull/527
=> fix: bump snyk-docker-plugin to fix the snyk container tag and digest handling

src/cli/commands/test/iac/v2/index.ts
When running in a case-insensitive file system (like in macOS), Node and Go use different strategies for obtaining the current working directory. The current working directory in Node is the same returned by `realpath` or `getcwd(3)`. Instead, the current working directory in Go is the same returned by `pwd` or `$PWD`. The former strategy is consistent with the case of the directory when it was created, while the latter is consistent with the case of the directory the user changed into.
For example, let's say you are in `/Users/me/src`. Because you are on macOS, you can run `cd /Users/me/SRC` and actually end up in the same directory, because the file system is not case sensitive. In this case, though, Node believes that the current working directory is `/Users/me/src`, while Go believes …
=> fix: strip CWD from paths before using them

release-scripts/validate-repository.sh
Check if a release is already published to npm instead of static.snyk.io
=> fix: release validation

.circleci/config.yml, CONTRIBUTING.md, release-scripts/upload-artifacts.sh
This PR adds a CircleCI job to trigger a GitHub Actions workflow in the `snyk/snyk-images` repository using `repository_dispatch` [event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows). This will build and push Snyk Docker images after Upload NPM job is completed.
This new job is triggered when Upload NPM job is completed. 
`cURL` the same command written in `build-and-publish-snyk-images`
HEAD-350
|CICD to GHA|
|-|
|![cicd-to-gha](https://github.com/snyk/cli/assets/1948377/7ed57696-6713-4333-9f66-1fd94d701219)|
=> feat: trigger GHA workflow via CircleCI [HEAD-350]

src/lib/plugins/sast/analysis.ts, src/lib/plugins/sast/localCodeEngine.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts
SCLE URL validation was added on the [server](https://github.com/snyk/registry/pull/32946) and hence, is not needed anymore on the clients.
=> chore: removes SCLE URL validation [nebula-1372]

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
This upgrades the snyk-iac-test binary to display remediation advice for kubernetes resources when using Snyk IAC+
=> feat: upgrade snyk iac test to return k8s remediation advice

src/cli/commands/monitor/index.ts
When we scan a mono repo where in the root dir there's no project config but only sub dirs containing sub projects, e.g. like following
```
my-mono-repo
- project-a
- settings.gradle
- build.gradle 
- project-b
- settings.gradle
- build.gradle
```
We noticed that when doing `snyk monitor` instead of creating two projects, it creates one `my-mono-repo` project and the vulnerabilities found in the sub projects are overriding, and the `Explore this snapshot at` message printed out locally points to exactly the same remote URL.
We found that this issue is caused by that the `project-name` is missing as part of the meta data.
This PR supplies that missing `project-name`. The fixing has been tested locally and works well.
Before: 
After:
=> fix: fix project name override with sub projects

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Upgrades `snyk-iac-test` to latest version. This version should contain fixes for the policy-engine related to how loops and vars and errors related to that are threaded.
=> fix: upgrade snyk-iac-test to latest - contains fixes for the policy-engine

packages/iac-cli-alert/src/index.ts, src/cli/commands/test/iac/local-execution/assert-iac-options-flag.ts, src/lib/iac/constants.ts, src/lib/iac/test/v2/output.ts
Updates the naming of Integrated IAC to IAC+
[Internal announcement](https://snyk.slack.com/archives/C2GSU0FCG/p1691690350052209)
Please see [this comment](https://snyksec.atlassian.net/browse/IAC-2572?focusedCommentId=826241) for details around updating the short link. 
https://snyksec.atlassian.net/browse/IAC-2572
=> feat: updated integrated iac naming

package-lock.json, package.json
Updated the snyk-python-plugin package with a version where the pipfile parser was fixed (https://github.com/snyk/snyk-python-plugin/pull/222).
- [Jira ticket SUP-1872](https://snyksec.atlassian.net/browse/SUP-1872)
=> fix: updated snyk-python-plugin package version

package-lock.json, package.json, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
Bumps the Snyk Nuget (.NET) plugin, which enables the specification of a `--target-framework` flag, that will scan for vulnerabilities against a specific runtime version.
=> fix: [OSM-347] Bump `snyk-nuget-plugin`

src/cli/commands/monitor/index.ts, src/lib/monitor/utils.ts, test/jest/unit/cli-monitor-utils.spec.ts
Due to a previous [fixing for gradle](https://github.com/snyk/cli/pull/4837/files), we accidentally also changed the name of many existing CLI projects.
That affects ecosystems such as dotnet, cocoapads, golang projects not using go module, swift and composer.
This PR reverts the name change for those projects while still preserving the expected behavior for gradle.
=> fix: fix wrong project name change

cliv2/cmd/cliv2/main.go, cliv2/internal/proxy/proxy.go
* improved debug logging around authorization
=> Feat: improved oauth support

package-lock.json, package.json
The main goal of this change is to add support for **Node 18**.
As a first step to make this change granular, this PR updates the minimum required Node.js version for the project to `>=16`.
Installing dependencies with a Node version older than 16 will trigger a warning the Node version not being compatible.
```
make build
```
> Bringing forward the End-of-Life Date for Node.js 16
https://nodejs.org/en/blog/announcements/nodejs16-eol
HEAD-497
=> chore: set Node compatibility version to >=16

package-lock.json, package.json, test/acceptance/workspaces/nuget-app-6-7/.gitignore, test/acceptance/workspaces/nuget-app-6-7/dotnet_6_7.csproj, test/acceptance/workspaces/nuget-app-6-7/obj/project.assets.json, test/acceptance/workspaces/nuget-app-6-7/program.cs, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
Same as https://github.com/snyk/cli/pull/4841. As usual, added some better acceptance tests to ensure we're covered.
Added support in the plugin for the imminent support of multiple `<TargetFrameworks>` for .NET.
Agreed with Product to replace `--target-framework` with `--dotnet-target-framework` before this has officially been announced as a closed beta.
=> feat: [OSM-347] Bumping `snyk-nuget-plugin`

.circleci/config.yml
Replace deprecated MacOS amd64 by supported MacOS arm64 runner.
.circleci/config.yml
* Download snyk-macos executable and run `file snyk-macos` this should show
=> chore: replace deprecated macos circleci runner [HEAD-781]

src/lib/iac/test/v2/scan/index.ts
Emits a warning log when the configured API URL is an insecure http one
[IAC-2591](https://snyksec.atlassian.net/browse/IAC-2591)
and [this Slack thread](https://snyk.slack.com/archives/C02JMMTLUF9/p1695980516376749).
[IAC-2591]: https://snyksec.atlassian.net/browse/IAC-2591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: warn when using an insecure http SNYK_API URL

.circleci/config.yml, test/smoke/spec/spec_helper.sh
replace the usage of the legacy token SMOKE_TESTS_SNYK_TOKEN
=> chore: use single test token

cliv2/Makefile, cliv2/cmd/cliv2/logheader.go, cliv2/cmd/cliv2/main.go, cliv2/pkg/basic_workflows/legacycli.go, cliv2/pkg/basic_workflows/legacycli_test.go
* Reduce size of main.go, by moving some functions to a separate file
* renaming function to make more sense 
* ...
=> chore: apply refactorings from a previous PR

release-scripts/upload-artifacts.sh, scripts/install-snyk.py
This PR updates the repository dispatch event trigger to include a version field in the `client_payload`, using the `VERSION_TAG` value. 
This allows the downstream repository to build Snyk images with the specified CLI version.
=> chore: pass explicit version to snyk images [HEAD-746]

.github/workflows/smoke-tests.yml, .github/workflows/snyk-protect-production-smoke-tests.yml, scripts/run-smoke-tests-locally.sh, test/smoke/README.md, test/smoke/spec/snyk_auth_spec.sh
=> fix: inject variable/secret TEST_SNYK_TOKEN into workflow step

.github/CODEOWNERS, package-lock.json, package.json, src/lib/code-config.ts, src/lib/plugins/sast/analysis.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts
=> feat: use gw routing for code

.github/CODEOWNERS
An update for the CODEOWNERS file. updating `potion` to `lumos` team.
=> fix: update CODEOWNERS file for lumos

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum
* update GAF to consistently use default HTTP headers
* make log level configurable to optionally increase information
=> fix: use default HTTP headers consistently [HEAD-936]

package-lock.json, package.json, src/lib/monitor/index.ts, test/tap/cli-monitor.acceptance.test.ts
The entire foundation for utilizing the `targetRuntime` exists in the Snyk backend, but is not utilized by `snyk monitor`.
Adding the `targetRuntime` will decorate the `snyk monitor` results with the Target Runtime information, used in multiple language ecosystems.
Here an example from .NET, before:
After:
This will also pave the way for support of `snyk monitor` of a single project with multiple target runtimes attached, without overwriting the same project multiple times.
=> fix: add `targetRuntime` meta information to monitor

src/lib/monitor/utils.ts, test/jest/unit/cli-monitor-utils.spec.ts
Following on from https://github.com/snyk/cli/pull/4865 this change tightens the method to explicitly check if allProjects is set and acts accordingly, either by making use of project name or falling back to the projectName flag.
=> fix: add condition to preserve project-name with gradle monitor

src/lib/errors/legacy-errors.js, test/jest/unit/lib/errors/legacy-errors.spec.ts
Fixes a misleading error message.
In c2399ae18d0c8f5c7a5cfcdf06460a4b1f29ce74 we assumed that all 400 responses returned by our backends are due to an incorrect severity threshold (eg `snyk test --severity-threshold=non-sense`).
This is incorrect - the CLI calls into many different backend services and we can't assume anything about the reason of the failure.
First understand how error messages are parsed/formatted here:
https://github.com/snyk/cli/blob/351c7bd09071c5db69c8276173ee166021019be5/src/lib/errors/legacy-errors.js#L82-L106
Then it should be clear that this line doesn't really make sense:
https://github.com/snyk/cli/blob/351c7bd09071c5db69c8276173ee166021019be5/src/lib/errors/legacy-errors.js#L56
If we do not provide a value for `400` above, then we'll use a generic error …
=> fix: do not show invalidSeverityThreshold error for HTTP 400 responses

package-lock.json, package.json
Fixes a bug where .NET projects with local `PackageReference`s caused a crash in the v2 beta logic.
=> fix: [OSM-782] Bumping `snyk-nuget-plugin`

package-lock.json, package.json
This bumps the snyk-nodejs-lockfile-parser to 1.52.4. Details can be found here https://github.com/snyk/nodejs-lockfile-parser/releases
=> fix: bump nodejs-parser to 1.52.4 attempt 2

package-lock.json, package.json
This bumps the snyk-nodejs-lockfile-parser to 1.52.6. Details can be found here https://github.com/snyk/nodejs-lockfile-parser/releases
=> fix: bump nodejs-parser to 1.52.6

test/jest/unit/snyk-dep-graph.spec.ts
=> fix: add percent-encoded plus sign in purl version tests

src/lib/plugins/sast/localCodeEngine.ts
- Allows requests made towards the Snyk Code Local Engine `/status` endpoint to respect the protocol of the Local Engine URL set on the org/group
- Fixes conditions where a Snyk Code Local Engine installation responds on both `http` and `https` and we want to query `http` only
- Allows certificate trust to remain intact
=> fix: allow http requests towards code local engine [NEBULA-1541]

package-lock.json, package.json
This bumps the snyk-nodejs-lockfile-parser to 1.52.7. Details can be found here https://github.com/snyk/nodejs-lockfile-parser/releases
=> fix: bump nodejs-parser to 1.52.7

cliv2/cmd/cliv2/main.go, cliv2/cmd/cliv2/main_test.go, cliv2/internal/cliv2/cliv2.go, cliv2/internal/cliv2/cliv2_test.go
=> fix: add timeout handling to legacy cli

package-lock.json, package.json, test/acceptance/workspaces/nuget-app-7-windows/.gitignore, test/acceptance/workspaces/nuget-app-7-windows/dotnet_7.csproj, test/acceptance/workspaces/nuget-app-7-windows/obj/project.assets.json, test/acceptance/workspaces/nuget-app-7-windows/program.cs, test/jest/acceptance/snyk-fix/fix.spec.ts, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
=> fix: [OSM-887] Bumping `snyk-nuget-plugin` for various bugfixes

package-lock.json, package.json
=> fix: incorrect version coercion in container's pip scanner

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, test/acceptance/fake-server.ts, test/jest/acceptance/auth.spec.ts, test/jest/acceptance/cli-args.spec.ts
=> feat: Support OAuth Client Credentials Grant [HEAD-873]

package-lock.json, package.json, src/lib/request/request.ts, test/tap/proxy.test.js
**What**
**Why**
In https://github.com/snyk/cli/pull/4953 we had to revert to an older version of needle.
We want to make sure we can continue to upgrade needle and we don't accidentally break proxy support on upgrades.
=> fix: fix the proxy tests, ensure that CONNECT method is used

cliv2/cmd/cliv2/debug.go, cliv2/cmd/cliv2/logheader.go, cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, cliv2/pkg/basic_workflows/legacycli.go, test/jest/acceptance/debuglog.spec.ts
=> feat: Redact token information from debug logs [HEAD-1184]

.circleci/config.yml
This will allow for (probably) better parallelism, seeing what tests failed, and tracking flakey tests.
=> chore(ci): upload legacy tap test results to circle

package-lock.json, package.json
This gets us away from a *very* old version of uuid in the dep tree, that
leaves a warning when installing. Less warnings are good.
=> chore: upgrade conventional-changelog-cli to latest

src/lib/is-ci.ts, test/acceptance/config-helper.ts, test/acceptance/fake-server.ts, test/jest/acceptance/auth.spec.ts, test/jest/acceptance/https.spec.ts
=> fix: Authentication when a pre-existing invalid token is stored [HEAD-1197]

.circleci/config.yml, .vscode/launch.json, package.json
... so we can remove the explicit import hook for it from test running
=> chore: tap knows about typescript now

src/lib/formatters/get-sarif-result.ts, test/jest/unit/lib/formatters/__snapshots__/open-source-sarif-output.spec.ts.snap
We received a report that `artifactChanges: []` causes an error in GitHub:
> Unable to upload "xyz.sarif" as it is not valid SARIF:
> - instance.runs[2].results[0].fixes[0].artifactChanges does not meet minimum length of 1
cf. https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141791134
This fix populates `artifactChanges` so it's not empty.
=> fix: SARIF: artifactChanges property cannot be empty

Makefile, package-lock.json, package.json
To aid in debugging and development of the Typescript parts of the CLI, this adds an npm script entrypoint to the CLI.
This doesn't run the complete CLI but may be useful for isolating and debugging Typescript CLI issues.
This is not a user-facing change.
Usage:
`npm run dev test` to run the equivalent of `snyk test` from Typescript source.
`npm run dev -- -d` to pass the debug `-d` flag to the Typescript main entrypoint (and not `npm run`).
=> chore: add npm dev script

.circleci/config.yml, Makefile
=> feat: Deploy regular CLI builds to a new preview channel

cliv2/go.mod, cliv2/go.sum
- **Testing**
This updates the Snyk Language Server extension to the latest version. Currently, the `$/snyk.scan` custom message from Snyk Code is sent without a valid range. The range is specified in the structure, but just not filled. The new language server version remedies this.
Have a look at commit 5c61976 of snyk-ls - it contains tests and the changed code.
https://github.com/snyk/snyk-ls/commit/5c619762aff69c79c64b0dd763eddd87555d826f#diff-5fdc92093964521489fec0d3eb3f9384994e19496fc0d274e0d6a3c3086a975dR81
Start up VSCode and have it do a Snyk Code scan
This PR is necessary to use the experimental preview feature of sourcing Snyk Code findings from Language Server …
=> fix: add range to snyk.scan message created by code scanner [IDE-134]

cliv2/go.mod, cliv2/go.sum
- **Testing**
Risk: low
This PR updates Snyk Language Server to the latest version. This version provides a fix for code action handling in language server. Resolvable Code Actions are working in a two-step modus in language server: First, the action is created with a callback function stored in language server. The second step is the code action resolution. When a client calls language server with the codeaction/resolve request, the stored callback function is looked up in the cache and executed. 
Previously, this cache was purged on each code action request call. This is not working well, if code action information is retained by the IDE. Therefore, the cache entry for …
=> fix: do not purge the code action cache in language server before the action is resolved by the client [IDE-134]

.circleci/config.yml, cliv2/go.mod
- **Testing**
Upgrades Go toolchain used to build the CLI to 1.21.7.
Acceptance tests should suffice to catch problems with executable on multiple platforms, however unlikely.
You could manually test this by installing go 1.21.7 and building locally.
Go 1.18 released almost 2 years ago. Most developers (CLI team included) are on a newer version of Go. The world has moved on.
This change omits the `toolchain` directive from `cliv2/go.mod`. That should be OK because we tightly control the toolchain in our CircleCI pipeline. If we specified it, that would tightly couple the build with the tools image, which might use a different version of Go in various contexts. I propose it …
=> fix: upgrade go toolchain to 1.21.7

package-lock.json, package.json
Bump `snyk-docker-plugin` version to 6.10.2 to contain the fix of supporting large/complex container project files files to fix an issue for customers.
For more details : https://github.com/snyk/snyk-docker-plugin/pull/569
=> Fix: support monitoring large/complex container projects

test/jest/acceptance/cli-json-file-output.spec.ts, test/jest/acceptance/cli-json-output.spec.ts
=> refactor: split test suites

src/lib/formatters/open-source-sarif-output.ts, src/lib/formatters/sarif-output.ts, test/fixtures/docker/sarif-container-result.json, test/fixtures/docker/sarif-with-file-container-result.json, test/jest/acceptance/snyk-test/output-formats/sarif.spec.ts, test/jest/unit/lib/formatters/__snapshots__/open-source-sarif-output.spec.ts.snap, test/jest/unit/lib/formatters/__snapshots__/sarif-output.spec.ts.snap
Addresses #2439.
Adds `security-severity` to open source and container SARIF output.
=> feat(#2439): populate CVSS scores in SARIF files

package-lock.json, package.json
Enables multi-platform support for OCI images.
Using Docker engine 25.x test an OCI image with a non-standard platform...
`snyk container test busybox:latest --platform=linux/arm64`
Docker engine 25.x now creates an archive with a compliant OCI layout when running `docker save`. We previously only supported `linux/amd64` for OCI layouts.
https://github.com/snyk/snyk-docker-plugin/pull/571
https://snyksec.atlassian.net/browse/SUP-2577
https://snyksec.atlassian.net/browse/SUP-2579
https://snyksec.atlassian.net/browse/SUP-2594
https://snyksec.atlassian.net/browse/SUP-2595
https://snyksec.atlassian.net/browse/SUP-2630
=> fix: enables multi-platform support for OCI images

release-scripts/determine-release-channel.sh, release-scripts/next-version.sh
=> chore: support additional version postfixes

.circleci/config.yml, package.json
- **Testing**
Continuing the work introduced through https://github.com/snyk/cli/pull/5087, adopts junit reporter for acceptance test suites so we can collect information and gain a better understanding of how these perform. Once we have this data we can make a more informed pitch on where to spend our time to reduce CircleCI duration. 
It is worth noting that there is some delay between test reports being uploaded and being represented in the [CircleCI insights tool](https://app.circleci.com/insights/github/snyk/cli/workflows/test_and_release/tests?branch=chore/ci-persist-acceptance-tests). 
Validate that test reports are being uploaded, heres a direct link through to the …
=> chore(ci): persist acceptance tests

.circleci/config.yml
=> chore(ci): switch to small go image

test/acceptance/workspaces/composer-app/composer.json
- **Testing**
As of Composer v2.7.2 the tool will emit an error
if the version has not been defined on the root composer.json
https://github.com/composer/composer/releases/tag/2.7.2
Rather than updating the tests to expect error output we have introduced the 
`version` property, otherwise we are relying on the fallback behaviour of Composer.
> Note that relying on the default/fallback version might potentially lead to dependency resolution issues, especially when the root package depends on a package which ends up depending (directly or indirectly) [back on the root package itself](https://getcomposer.org/doc/articles/troubleshooting.md#dependencies-on-the-root-package). …
=> test: explicitly state project version

.circleci/config.yml, package.json, test/jest/acceptance/analytics.spec.ts
- **Testing**
This PR implements CircleCI parallelism for all acceptance test suites, significantly reducing the duration for the _acceptance-tests windows amd64_ suite from 41 minutes (p95 last 90 days) to ~14 minutes. 
* Reviewers should start by examining the changes made to the CircleCI configuration files to implement parallelism for acceptance test suites.
* https://github.com/snyk/cli/pull/5097/commits/76fa2da483d054a5b511bdcfb790adcd51912da4 Remove hard coded port from tests which introduced issues when parallelising them. 
* Making use of recently upgraded jest dep. and [adopted `--shard` flag](https://jestjs.io/blog/2022/04/25/jest-28#sharding-of-test-run). 
* …
=> chore(ci): introduce parallel test runs for our acceptance tests

package-lock.json, package.json
=> feat: support -dverbose argument when testing maven projects

release-scripts/create-release.sh
=> chore: introduce script to create release

.circleci/config.yml, .github/workflows/create-build-image.yml, scripts/create-build-image.sh
=> chore: publish build image to snyklabs

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/snyk-code/snyk-code.spec.ts
=> chore: add go entry point for `snyk code test`

check-dependencies.config.ts, package-lock.json, packages/cli-alert/package.json, packages/iac-cli-alert/package.json
=> fix(ci): cli/iac alerts

cliv2/go.mod, cliv2/go.sum, test/acceptance/fake-server.ts, test/jest/acceptance/snyk-container/container.spec.ts, test/jest/acceptance/snyk-sbom/sbom.spec.ts
**Risk assessment**: Low-Medium
- **Testing** …
=> feat: support cyclonedx 1.5

.circleci/config.yml
=> chore(ci): introduce caching around npm install step

package-lock.json, package.json
=> fix: enhance sbt output width, fixing false positives vulns

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
- **Testing**
Once a pull request has been reviewed and all necessary revisions have been made, it is approved for merging into 
the main codebase. The merging of the code PR is performed by the code owners, the merging of the documentation PR 
by our content writers.
Upgrade snyk-iac-test to v0.51.3.  Changes in the snyk-iac-test -> upgrades for policy-engine to version that have the following fixes:
- Print scan URL to debug output after uploading report.
- Fix panic on invalid arm input
- Fix panic on invalid tf input
- Fix tfplan policy-engine detection for resources defined with counts
Risk: LOW
The main change is related to showing an addition log line for when using …
=> feat: upgrade snyk-iac-test to v0.51.3

cliv2/go.mod, cliv2/go.sum
=> fix: add --experimental flag for snyk code test

cliv2/go.mod, cliv2/go.sum
- **Testing**
This PR updates the included language server to protocol version 11. 
🚨This guards & enforces an API change for IDE clients that is needed for global ignores. This version and consecutive versions of the CLI will only be downloaded from IDEs that have require the same protocol version. Older IDE plugins will stay on the previous CLI.
Risk: Low
Snyk-LS, go-releaser.yaml
`make build` should display protocol version 11, the corresponding file (`ls-protocol-version-11`) in `binary-releases` should be generated.
Protocol version 11 is going to be required for global ignores, as it uses a new API call to retrieve feature flags, that is used and exposed as an LSP …
=> feat: bump language server protocol version to 11 [IDE-236]

src/lib/formatters/remediation-based-format-issues.ts, src/lib/formatters/test/format-test-results.ts, src/lib/formatters/types.ts, src/lib/snyk-test/legacy.ts, test/acceptance/workspaces/npm-package-single-vuln/package-lock.json, test/acceptance/workspaces/npm-package-single-vuln/package.json, test/acceptance/workspaces/npm-package-single-vuln/test-graph-results-with-annotation.json, test/acceptance/workspaces/npm-package-single-vuln/test-graph-results.json, test/fixtures/sca-dep-graph-with-annotation/test-graph-results.json, test/fixtures/sca-dep-graph-with-annotation/test-graph-user-note-results.json, test/jest/acceptance/snyk-test/human-formatted-output.spec.ts, test/jest/unit/lib/formatters/__snapshots__/remediation-based-format-issues.spec.ts.snap, test/jest/unit/lib/formatters/remediation-based-format-issues.spec.ts
=> feat: include additional policy properties in plain text output

test/jest/acceptance/cli-json-output.spec.ts
=> test: validate applied policy rules in json output

Makefile, release-scripts/create-release.sh, release-scripts/enable-stable-release-channels.sh, release-scripts/next-version.sh, release-scripts/prepare-release.sh
=> chore(ci): Enable preview and stable deployments

test/jest/acceptance/cli-args.spec.ts, test/jest/util/runCommand.ts
When a Snyk CLI command is expected to exit 0 in acceptance tests, it would be useful for debugging to see the stderr from the process.
This adds an option to runSnykCLI (logErrors) to do this, opt-in. That way we don't pollute the log with expected non-zero exits in tests that expect them.
- **Testing**
=> chore: log errors in acceptance tests

package-lock.json, package.json, test/acceptance/workspaces/nuget-app-8-with-azure-functions/README.md, test/acceptance/workspaces/nuget-app-8-with-azure-functions/dotnet_8_with_azure_functions.csproj, test/acceptance/workspaces/nuget-app-8-with-azure-functions/obj/project.assets.json, test/acceptance/workspaces/nuget-app-8-with-azure-functions/program.cs, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
=> fix: [OSM-1007] Fixing two bugs related to missing `.deps` files (.NET Beta)

cliv2/cmd/cliv2/main.go, cliv2/cmd/cliv2/main_test.go, cliv2/go.mod, cliv2/go.sum
=> feat: parse data from output workflow

cliv2/go.mod, cliv2/go.sum
Low - dependency update covered in existing tests
- **Testing** …
=> feat(code): add support for '.snyk' excludes in go based 'snyk code'

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/auth.spec.ts
=> fix(auth): Autodetect IDE usage and fallback to API token based authentication

cliv2/go.mod, cliv2/internal/proxy/proxy.go, cliv2/internal/proxy/proxy_test.go, cliv2/pkg/basic_workflows/legacycli.go
=> feat(instrumentation): add trace level logging of request CLI-325

Makefile, cliv2/Makefile
Added an option to build the cliv2 go binary with flags for debugging and prevent symbol table stripping if DEBUG var is set to 1. 
Usage:
``DEBUG=1 make build`` 
- **Testing**
For Node projects: It’s important to make sure changes in `package.json` are also affecting `package-lock.json` …
=> chore: added debug option in cliv2 Makefile

cliv2/go.mod, cliv2/go.sum
=> fix (ls): snyk code scanning in consistent ignores flow

cliv2/cmd/cliv2/main.go, test/jest/acceptance/snyk-test/all-projects.spec.ts, test/jest/acceptance/snyk-test/protect-upgrade-notification.spec.ts
=> feat(instrumentation): integrate analytics report workflow CLI-302

.circleci/config.yml, release-scripts/write-ls-protocol-version.go
In #5285 the script which extracts the LS protocol version from snyk-ls was changed to use the Go module cache. `go install` is used as an alternative to fetching directly from Github.
This requires Go to be installed during the deployment release build.
- **Testing**
Manual testing will not be performed by the reviewing team, and is the responsibility of the author of …
=> fix: create_deployment_artifacts needs go installed

cliv2/cmd/cliv2/instrumentation.go, cliv2/cmd/cliv2/instrumentation_test.go, cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum
=> fix: Sending instrumentation data from VS and IntelliJ

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum
=> chore: use convenience method to GetCategory()

.gitleaksignore, test/acceptance/fake-server.ts, test/jest/acceptance/instrumentation.spec.ts, test/jest/util/createProject.ts, test/schemas/instrumentationSchema.json
=> test(instrumentation): acceptance testing instrumentation (CLI-347)

help/cli-commands/container-monitor.md, src/lib/ecosystems/monitor.ts, src/lib/types.ts, test/jest/acceptance/snyk-container/container.spec.ts
=> feat: set target-reference value in the container monitor request UNIFY-124

src/cli/commands/monitor/index.ts, src/lib/monitor/utils.ts, src/lib/types.ts, test/jest/unit/cli-monitor-utils.spec.ts
- **Testing**
When adding a new package as a dependency, make sure …
=> fix: project name when using assets-project-name flag

package-lock.json, package.json
=> fix: upgrade snyk-docker-plugin to fix nodejs-parser dependency type

src/lib/iac/test/v2/json-old.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/output.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/scan/results.ts, test/jest/unit/iac/process-results/fixtures/integrated-json-output-v2.json, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-results-v2.json, test/jest/unit/lib/iac/test/v2/json-old.spec.ts
=> feat(iac): enrich cli json results for iac with successful items (IAC-2962)

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/snyk-sbom-test/all-projects.spec.ts
This fixes two issues in the JSON output of `snyk sbom test --json`:
* the `CWE` of a vulnerability was wrongly attributed to the `CVE` field
* the casing of `@.vulnerabilities[].semver.vulnerable` was wrong
=> fix(sbom test): fix issues in JSON output

test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
A dotnet 8.0.0 vulnerability was discovered on 2024-07-09 which caused dotnet acceptance tests to fail on platforms with the vulnerable version installed.
While the toolchain could be updated, the test can be made more robust to future reoccurances of dotnet system vulns.
For this test we care more about the operation of the test command rather than its findings, so we can test for consistency between exit code and test output instead.
In updating this test, a defect was discovered in the dotnet plugin which corrupts json output. The test works around this, but it will require a dotnet plugin upgrade as a followup to mitigate user impact.
- **Testing**
All pull requests …
=> fix: make dotnet acceptance test resilient to system lib vulns

cliv2/internal/proxy/proxy.go, cliv2/internal/proxy/proxy_test.go, src/lib/ecosystems/resolve-test-facts.ts, src/lib/errors/missing-api-token.ts, src/lib/request/constants.ts, src/lib/request/promise.ts, src/lib/request/request.ts, test/jest/unit/lib/ecosystems/resolve-test-facts.oauth.spec.ts, test/jest/unit/lib/request/request.spec.ts
In the Typescript CLI, when OAuth fails due to an invalid or expired token, throw the same "missing auth" error that one would get if not logged in (no auth token).
The resulting error message will prompt the user to re-authenticate.
This has to be mediated by the legacycli http proxy because the Typescript side of the CLI is not involved in the OAuth flow at all; it is handled transparently by the go-application-framework's networking middleware.
A special HTTP request and response header is used by the legacycli proxy to indicate whether that middleware auth has failed. If it has, the functions which perform HTTP client requests with needle will throw an error that indicates "unauthenticated", resulting in an experience consistent with the legacy token auth flow in the CLI.
Outstanding …
=> fix: align auth failure error messages for oauth

cliv2/go.mod, cliv2/go.sum
```
commit 8f015d9f14f0b7015e58f92618b4322f3ab9fe25
Author: Jérémy Lourenço <jerem.lourenco@gmail.com>
Date:   Mon Jul 15 06:35:29 2024 +0100
refactor: set default api url to api.nyk.io (#583)
:100644 100644 70a10d7 d24aa0d M	README.md
:100644 100644 230f074 a7b5f24 M	application/config/config.go
:100644 100644 8456edd 9187c4c M	application/server/configuration_test.go
:100644 100644 2b9ad7d 46fe344 M	infrastructure/authentication/cli_provider_test.go
:100644 100644 7019864 c6e89cb M	infrastructure/cli/environment_test.go
:100644 100644 456eb87 89f2631 M	infrastructure/learn/service_test.go
commit 7e520c5abf2791d6bdcf7afb36f6af7b850f43f7
Author: Bastian Doetsch <bastian.doetsch@snyk.io>
Date:   Thu Jul 11 19:56:18 2024 +0200
fix: better error reporting for failed scans [IDE-486] (#580) …
```
=> feat(language-server): integrate LS

package-lock.json, package.json, test/jest/acceptance/snyk-container/container.spec.ts, test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
=> fix: remove ignored paths when discovering npm manifests UNIFY-216

.circleci/config.yml, package-lock.json, package.json, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
=> fix(test, monitor): support for pipenv with python 3.12

cliv2/go.mod, cliv2/go.sum
=> chore: update gaf and error-catalog

.circleci/config.yml, Makefile, cliv2/scripts/sign_darwin.sh
=> revert: signing cli macos binary

Makefile, cliv2/scripts/osx-entitlements.plist, cliv2/scripts/sign_darwin.sh
=> fix: Missing entitlements when signing bundled TS binary

package-lock.json, package.json
=> fix: container support hashing .jar files of size up to buffer.constants.MAX_LENGTH

src/lib/ecosystems/test.ts, src/lib/snyk-test/assemble-payloads.ts, src/lib/snyk-test/common.ts, src/lib/snyk-test/run-test.ts, src/lib/stream.ts, test/jest/unit/lib/ecosystems/__snapshots__/common.spec.ts.snap, test/jest/unit/lib/ecosystems/common.spec.ts, test/jest/unit/lib/stream.spec.ts
This PR changes the way we output dep-graph payloads from `console.log` to NodeJS Streams, writing to `process.stdout`. This way we can replace `jsonStringifyLargeObject` with `JsonStreamStringify`.
This PR is a precursor to https://github.com/snyk/cli/pull/5399, which had too much happening all at once.
Can be tested with `snyk test --print-graph`, `snyk container test --print-graph`, and `snyk test --unmanaged --print-graph`.
=> fix: write dep-graph payloads to stdout stream

.gitignore, ts-binary-wrapper/src/bootstrap.ts, ts-binary-wrapper/src/common.ts, ts-binary-wrapper/src/index.ts, ts-binary-wrapper/test/unit/common.spec.ts, ts-binary-wrapper/test/util/prepareEnvironment.ts
=> feat: change binary download url

cliv2/Makefile, cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, cliv2/internal/cliv2/cliv2.go, cliv2/internal/cliv2/cliv2_test.go, cliv2/internal/proxy/proxy.go, cliv2/internal/proxy/proxy_test.go, cliv2/pkg/basic_workflows/globalresources.go, cliv2/pkg/basic_workflows/globalresources_test.go, cliv2/pkg/basic_workflows/init.go, cliv2/pkg/basic_workflows/legacycli.go, test/jest/acceptance/language-server-extension.spec.ts, test/jest/acceptance/parallel-execution.spec.ts
=> fix: Fix multiple parallelization issues 

help/cli-commands/auth.md, help/cli-commands/config-environment.md
=> docs: update help

test/acceptance/deepcode-fake-server.ts, test/acceptance/fake-server.ts, test/fixtures/sast/no-vulnerabilities/index.ts, test/fixtures/sast/with_code_issues/HashingAssignment.java, test/fixtures/snyk-code/sarif-schema.json, test/jest/acceptance/snyk-code/snyk-code.spec.ts
Low - Changes to test files, no functional changes
- **Testing** …
=> test: user journey tests for Go based snyk code test [CLI-225]

package-lock.json, package.json, src/cli/commands/ignore.ts, src/cli/commands/policy.ts, src/cli/commands/test/iac/local-execution/process-results/cli-share-results.ts, src/cli/commands/test/iac/local-execution/process-results/index.ts, src/cli/commands/test/iac/local-execution/process-results/policy.ts, src/cli/commands/test/iac/local-execution/process-results/process-results.ts, src/cli/commands/test/iac/local-execution/process-results/share-results.ts, src/cli/commands/types.ts, src/cli/commands/update-exclude-policy.ts, src/lib/config/index.ts, src/lib/display-policy.ts, src/lib/ecosystems/policy.ts, src/lib/iac/drift.ts, src/lib/iac/envelope-formatters.ts, src/lib/policy/find-and-load-policy.ts, test/acceptance/workspaces/npm-package-policy/.snyk, test/acceptance/workspaces/npm-package-policy/custom-location/.snyk, test/fixtures/snyk-config-no-version/.snyk, test/fixtures/snyk-config-no-version/expected, test/jest/acceptance/iac/update-exclude-policy.spec.ts, test/jest/acceptance/snyk-ignore/snyk-ignore.spec.ts, test/jest/unit/iac/cli-share-results.fixtures.ts, test/jest/unit/iac/cli-share-results.spec.ts, test/jest/unit/iac/process-results/policy.spec.ts, test/jest/unit/lib/ecosystems/policy.spec.ts, test/jest/unit/lib/iac/drift/drift.spec.ts
`snyk policy` output includes the correct url information, udading the url to the snyk.io root rather than security.snyk.io. https://snyksec.atlassian.net/browse/CLI-482
- **Testing**
For Node projects: It’s important to make sure changes in `package.json` are …
=> fix: point snyk policy out urls to snyk.io

test/jest/unit/lib/unexpected-error.spec.ts
Rebase for https://github.com/snyk/cli/pull/4813, but otherwise no changes made.
=> test: unexpected-error test expects non-colored output

cliv2/go.mod, cliv2/go.sum, cliv2/internal/cliv2/cliv2.go, cliv2/internal/cliv2/cliv2_test.go, cliv2/internal/proxy/proxy.go, cliv2/internal/proxy/proxy_test.go, cliv2/internal/utils/directories.go, cliv2/pkg/basic_workflows/globalresources.go
=> chore(GAF): bump gaf version

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts
=> fix(iac):pass allow analytics flag to snyk-iac-test [IAC-3017]

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
=> fix(iac): paths showing proper resource for partial tfplans [IAC-2940]

src/lib/package-managers.ts, test/tap/cli-monitor.acceptance.test.ts
=> feat: enable cocoapods to send graphs for cli monitor

CONTRIBUTING.md
=> docs(contributing): add section on setting up debugger

src/cli/commands/test/iac/v2/index.ts, src/cli/commands/test/index.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/types.ts, test/acceptance/fake-server.ts, test/jest/acceptance/iac/cli-share-results.spec.ts, test/jest/acceptance/iac/test-terraform.spec.ts
=> fix(iac): check iacNewEngine FF and pass it to snyk-iac-test [IAC-3059]

cliv2/cmd/cliv2/main.go, cliv2/internal/proxy/proxy_test.go, cliv2/pkg/basic_workflows/globalresources.go, cliv2/pkg/basic_workflows/globalresources_test.go, test/jest/acceptance/analytics.spec.ts, test/jest/acceptance/cli-in-memory-threshold-bytes.spec.ts
Risk assessment is low as this feature is only enabled for GAF workflows larger than 512MB by default and can be manually disabled
- **Testing**
For Node projects: It’s important to make sure changes in `package.json` are also affecting `package-lock.json` …
=> feat: conditionally write data to file instead of keeping it in memory

.circleci/config.yml, package-lock.json, package.json
Bump snyk-nodejs-plugin to fix a micromatch vulnerability
package.json and package-lock.json
=> fix: update snyk-nodejs-plugin to fix micromatch vuln

cliv2/go.mod, cliv2/go.sum
This adds `snyk test` option `--gradle-normalize-deps` to the `snyk sbom` command, which will get passed down to the underlying `snyk test` execution that generates the dep-graph.
Diffs of the extension changes can be seen here:
* https://github.com/snyk/cli-extension-dep-graph/compare/8d56ac52821e...main
* https://github.com/snyk/cli-extension-sbom/compare/68258cba52c7...main
=> fix: add missing option --gradle-normalize-deps to SBOM command

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/snyk-sbom-test/all-projects.spec.ts
Upgrades the SBOM CLI Extension to include a fix where the CVE of a vulnerability had not been added to the JSON output of the `sbom test` command.
See https://github.com/snyk/cli-extension-sbom/pull/96.
=> fix: include CVE in JSON output of `sbom test` command

cliv2/cmd/cliv2/instrumentation_test.go, cliv2/cmd/cliv2/main.go, cliv2/cmd/cliv2/main_test.go, cliv2/go.mod, cliv2/go.sum, cliv2/internal/cliv2/cliv2_test.go, cliv2/internal/proxy/proxy_test.go, cliv2/pkg/basic_workflows/globalresources_test.go, test/jest/acceptance/iac/capture.spec.ts
The existing behaviour, although not correct, may be used by clients without knowing that it's unintentional. This would lead to breaking changes for them. The fix for them would be to use the intended env var for their purpose.
This PR updates the CLI so that it no longer automatically detects supported env vars. The automatic detection led to bugs where ambiguous environment variables (e.g. `ORG`) would be picked up and used in the CLI.
By explicitly configuring the supported env vars, we can avoid these sorts of bugs (e.g. by requiring namespace prefixes in env vars we want to support).
Review the related GAF [PR](https://github.com/snyk/go-application-framework/pull/265)
=> fix: manually configure supported env vars

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts
`snyk iac test` command [was broken](https://app.firehydrant.io/org/snyk/incidents/407705e9-afc4-4463-96b9-646c480179ec/timeline) for IaC+ (FF `iacIntegratedExperience`) when using `snyk auth`, because the `snyk-iac-test` binary used Oauth token from env var (which was removed at some point) instead of directing the API calls through the internal proxy of the CLI (which handles auth)
This PR upgrades to a new version of `snyk-iac-test` that uses the internal proxy for API calls.
See https://github.com/snyk/snyk-iac-test/pull/256 for the changes done on the `snyk-iac-test` side.
Run `snyk iac test` with an org that has `iacIntegratedExperience` FF enabled, with Oauth2 or with token via env var.
Run `snyk iac test` with an org that has `iacIntegratedExperience` FF disabled, with Oauth2 or …
=> fix: use proxy aware snyk-iac-test [INC-1647]

package-lock.json, package.json
Updates snyk-nuget-plugin to fix a bug regarding restoring dotnet projects that have <TreatWarningsAsErrors> turned on, and also adds a property named `SnykTest` that will be present when we run `dotnet publish`. The scope for this property is to allow customers to enable/disable properties that might interfere and break out scanning.
Looking over this PRs:
https://github.com/snyk/snyk-nuget-plugin/pull/226
https://github.com/snyk/snyk-nuget-plugin/pull/225
Using this fixtures:
Treat warnings as error [issue](https://github.com/snyk/snyk-nuget-plugin/tree/main/test/fixtures/dotnetcore/dotnet_8_treat_warnings_as_errors)
[SnykTest property](https://github.com/snyk/snyk-nuget-plugin/tree/main/test/fixtures/dotnetcore/dotnet_8_with_snyk_test_property)
=> fix: do not treat warnings as errors on restore

src/lib/ecosystems/resolve-test-facts.ts
Fixes the reported unmanaged dependencies count in snyk analytics.
Before the change:
With the fix, the debug logs report the correct detected number of dependencies as can be seen below:
[](url)
=> fix: mismatch/off-by-one on unmanagedDependencyCount in snyk analytics UNIFY-340

.circleci/config.yml, package-lock.json, package.json, test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts
Upgrades snyk-docker-plugin to pull in this fix: https://github.com/snyk/snyk-docker-plugin/pull/610, which ensures `--exclude-app-vulns` works correctly if you are authed with OAuth.
Build locally and run the following command:
```
~/snyk/cli/binary-releases/snyk-macos container monitor --exclude-app-vulns mathiasconradt/goof
```
If it completes successfully then the fix is working as expected. 
Ref: CLI-543
Additionally this upgrade to `snyk-docker-plugin` addresses the following:
* [UNIFY-243](https://snyksec.atlassian.net/browse/UNIFY-243) - fix: dependencies detection from container removed layers
* [UNIFY-264](https://github.com/snyk/snyk-docker-plugin/pull/604) - fix: ignore npm/yarn cache directories
[UNIFY-243]: https://snyksec.atlassian.net/browse/UNIFY-243?atlOrigin=eyJpIjoiNWRk …
=> fix(container): support --exclude-app-vulns with oauth

cliv2/cmd/cliv2/main.go, cliv2/cmd/cliv2/main_test.go, cliv2/cmd/cliv2/testdata/sarif.json, cliv2/go.mod, cliv2/go.sum
- Bumps GAF to add a new filter workflow that filters a local findings model based on severity-threshold
```
make build && INTERNAL_SNYK_TRANSFORMATION_WORKFLOW_ENABLED=true ./binary-releases/snyk-macos-arm64 code test --org=<org-slug> . --severity-threshold=medium
```
=> chore(localfindings): add new filter workflow for local findings

package-lock.json, package.json
Updates `snyk-policy` library to remove logging messages from being emitted on stdout. This was breaking Snyk CLI commands where stdout is used to build JSON documents.
=> fix(general): prevent snyk-policy lib from interrupting stdout to ensure valid --json --sarif output

cliv2/.golangci.yaml
Before:
```
WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`.
WARN [config_reader] The configuration option `linters.govet.check-shadowing` is deprecated. Please enable `shadow` instead, if you are not using `enable-all`.
WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
```
After:
🕊️
=> chore: remove deprecated linters and config props

package-lock.json, package.json
See https://github.com/snyk/snyk-docker-plugin/pull/614
Fixing a bug in snyk-docker-plugin so that optional dependencies are properly connected in the dep-graph.
This could mean that 'snyk container monitor' commands that previously timed out or errored may now start working. The fix reduces unnecessary (optional) paths in the dep-graph and so reduce the work Snyk needs to do when scanning for vulnerabilities.
`snyk container monitor` on a docker image using requirements.txt to install python dependencies.
=> fix: container optional python dependencies

package-lock.json, package.json, test/acceptance/workspaces/npm-package-single-ignored-vuln/.snyk, test/acceptance/workspaces/npm-package-single-ignored-vuln/package-lock.json, test/acceptance/workspaces/npm-package-single-ignored-vuln/package.json, test/acceptance/workspaces/npm-package-single-ignored-vuln/test-graph-results.json, test/jest/acceptance/cli-json-output.spec.ts
This pull request updates the `policy` library to `4.1.4` to fix an issue introduced in [snyk-policy version 3.0](https://github.com/snyk/policy/releases/tag/v3.0.0). In that version the [debug library ](https://github.com/debug-js/debug) began logging messages to `stdout` instead of `stderr`, causing JSON parsing to break.
The branch was created based on the [test/capture-valid-esoj-output-with-policy branch](https://github.com/snyk/cli/tree/test/capture-valid-esoj-output-with-policy), which includes an acceptance test to check if the CLI returns a well-structured json.
- [IGNR-730](https://snyksec.atlassian.net/browse/IGNR-730)
- [IGNR-786](https://snyksec.atlassian.net/browse/IGNR-786)
[IGNR-730]: https://snyksec.atlassian.net/browse/IGNR-730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …
=> fix: policy library logging messages to stdout instead of stderr

.circleci/config.yml
Removes EOL ubuntu image from e2e test matrix. The Releases for these are currently unavailable due to an ongoing maintenance incident: https://status.canonical.com/#/incident/KNms6QK9ewuzz-7xUsPsNylV20jEt5kyKsd8A-3ptQHSMVTAPVH4_LjQCYu8J9Cus3zqZwIrEn6enyZkKH6Mvg==
We should remove testing for these as they are no longer supported by ubuntu:
https://fridge.ubuntu.com/2024/07/17/ubuntu-23-10-mantic-minotaur-reached-end-of-life-on-july-11-2024/
=> chore(ci): remove EOL ubuntu from e2e test matrix

package-lock.json, package.json, test/fixtures/gradle-with-repeated-deps/build.gradle, test/fixtures/gradle-with-repeated-deps/lib/build.gradle, test/jest/acceptance/snyk-test/print-graph.spec.ts
Upgrades gradle-plugin to implement a similar resolution of depgraphs as recently done for maven.
See https://github.com/snyk/snyk-gradle-plugin/pull/290.
* run `snyk sbom --format=cyclonedx1.4+json` on the newly added gradle project in the cli (`cli/test/fixtures/gradle-with-repeated-deps`)
Current version of CLI will output pruned deps, while the new version will not prune any nodes.
=> feat: support verbose gradle graphs for sbom generation

src/cli/commands/monitor/index.ts
Fixes a typo (`--project-tag`) in a hint. `--project-tags` is the correct flag.
=> chore: fix --project-tag typo in hint message

binary-releases/RELEASE_NOTES.md, package-lock.json, package.json, test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts
=> hotfix for v1.1294.1 - Snyk Container - Ignore npm/cache directories 

cliv2/cmd/cliv2/logheader.go, cliv2/go.mod, cliv2/go.sum
Introduces a Region key to our debug output to make it quicker to troubleshoot the region we are currently configured to run against.
Associated documentation: https://docs.snyk.io/working-with-snyk/regional-hosting-and-data-residency#available-snyk-regions
* `snyk config environment default`
* `snyk help -d` The output will include _Region: snyk-us-01_
* `snyk config environment dev`
* `snyk help -d` will not include a Region property as we are running against a dev instance.
```shell
2024-11-27T13:57:14Z main - Using a preview feature!
2024-11-27T13:57:14Z main - Version:               1.1295.0-dev
2024-11-27T13:57:14Z main - Platform:              darwin amd64
2024-11-27T13:57:14Z main - API:                   https://api.snyk.io
2024-11-27T13:57:14Z main - Region: …
```
=> chore: include region value in output

src/lib/iac/test/v2/json.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/results.ts, test/jest/unit/iac/process-results/fixtures/integrated-json-output-v2.json, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-results-v2.json
IaC custom rules may include evidence to why a certain policy passed for a resource. If that evidence (string) is specified, we display it in the JSON output for the rule.
Note: this applies only for custom IaC rules, since the standard rules are not required to provide this evidence, and were not modified to include it.
There should be no concerns about output size increase, IaC custom rules are used by a small fraction of the customers, and this field should be a one line string in the majority of cases, if at all added.
This functionality is fully covered by tests, so no need for a manual test, which is a bit complicated. 
I write it here nevertheless, just in case.
1. A custom rule needs to be created and pushed to Snyk using `snyk iac rules init`. See an example …
=> feat: (IaC) include evidence field in json output [IAC-3161]

src/lib/monitor/index.ts, src/lib/request/constants.ts, src/lib/request/promise.ts, src/lib/snyk-test/run-test.ts, test/jest/acceptance/error-catalog.spec.ts
Following the previous changes to the `snyk test` and `snyk code test` of returning an error message from the Error Catalog for unsuccessful network requests, this PR adds the same functionality to the `snyk monitor` and `snyk container monitor` commands. 
- Ensure a clean build of the CLI
- Clear you configuration using `snyk config clear` to ensure further request towards Snyk services will fail with a 401 unauthorized response code
- Running `snyk monitor` or `snyk container monitor <image>` (eg. image: alpine or any available Docker image) should return a nicely formatted error message from the Error Catalog. You can also include the `-d` debug flag and look for the analytics payload sent, that should contain the same ID for the error and the status code for it. 
Ticket: …
=> fix: error catalog messages for monitor commands

src/lib/snyk-test/legacy.ts, test/jest/acceptance/cli-json-file-output.spec.ts
When both `--print-deps` and `--json-file-output` are being used produce a depGraph object in the resulting JSON file.
Does not attempt to fix any existing `--json` output formats to reduce the potential of breaking changes.
This allows CLI users to see the dependency graph that was resolved by the plugin code and scanned.
Useful for those users that are interested in what dependencies where resolved by Snyk and for debugging.
```bash
snyk test --print-deps --json-file-output=out.json
cat out.json | jq .depGraph
```
=> feat: dep-graph json output file

help/cli-commands/container-monitor.md, package-lock.json, package.json, src/lib/types.ts, test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts
Before [v6.12.0](https://github.com/snyk/snyk-docker-plugin/releases/tag/v6.12.0), the docker cli plugin was able to scan npm projects only when [strict package.json and package-lock.json pairs](https://github.com/snyk/snyk-docker-plugin/blob/ac707fdb49a29406e61d04a26ddd6f3c91b626a1/lib/analyzer/applications/node.ts#L88-L104) of files were identified within container images. The pair of files [had to be outside](https://github.com/snyk/snyk-docker-plugin/blob/ac707fdb49a29406e61d04a26ddd6f3c91b626a1/lib/inputs/node/static.ts#L12) of a node_modules folder’s context in order to avoid creating projects out of the dependencies. Scanning container images that had the manifests/lockfiles removed was not possible and customer needs were created to remove that constraint.
The scanning of npm …
=> feat: container add --exclude-node-modules option

help/cli-commands/container-test.md, src/lib/types.ts
=> fix: add container test doc info for --exclude-node-modules

help/cli-commands/container-monitor.md, help/cli-commands/container-test.md, package-lock.json, package.json, src/lib/types.ts, test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts
Before [v6.12.0](https://github.com/snyk/snyk-docker-plugin/releases/tag/v6.12.0), the docker cli plugin was able to scan npm projects only when [strict package.json and package-lock.json pairs](https://github.com/snyk/snyk-docker-plugin/blob/ac707fdb49a29406e61d04a26ddd6f3c91b626a1/lib/analyzer/applications/node.ts#L88-L104) of files were identified within container images. The pair of files [had to be outside](https://github.com/snyk/snyk-docker-plugin/blob/ac707fdb49a29406e61d04a26ddd6f3c91b626a1/lib/inputs/node/static.ts#L12) of a node_modules folder’s context in order to avoid creating projects out of the dependencies. Scanning container images that had the manifests/lockfiles removed was not possible and customer needs were created to remove that constraint.
The scanning of npm …
=>   feat: container test/monitor add support for --exclude-node-modules option

.circleci/config.yml, .snyk
- **chore(ci): update gitleaks fingerprints**
Updates gitleaks ignore file to use new fingerprints.
=> chore(ci): update gitleaks ignore due to fingerprints changing

.circleci/config.yml, cliv2/go.mod
This pull request updates the Go version and toolchain used in the cliv2 directory to version 1.23.4.
Go 1.23.4 (released 2024-12-03) includes fixes to the compiler, the runtime, the trace command, and the syscall package. You can find the full release notes here: [invalid URL removed]
The reviewer can start by reviewing the changes in the .circleci/config.yml and cliv2/go.mod files.
Download the artefact built by the CI/CD process and run `snyk test`
=> chore(deps): upgrade golang v1.23.4

release-scripts/sha256sums.txt.asc.sh
This PR updates the sha256sums.txt.asc.sh script to replace the hardcoded GPG key (3676C4B8289C296E) with a dynamic environment variable (`SNYK_CODE_SIGNING_PGP_KEY_ID`). This enhances the flexibility of the signing process by allowing different GPG keys to be used depending on the environment.
Additionally, this change introduces the use of --default-key instead of --local-user. This switch offers two key benefits:
- Dynamic Key Selection:
- --default-key relies on the value of the GPG_KEY_ID provided at runtime, making it adaptable to different environments or pipelines.
- --local-user is more static, requiring the exact key ID at the time of script authoring, limiting its reusability without manual code changes.
- Environment-Driven Configuration:
- --default-key aligns with best …
=> chore(ci): move to use keyId

.circleci/config.yml, release-scripts/upload-artifacts.sh
Adds a trigger docker images task to each of the release pipelines so that we start building images for each distribution channel. The change here is intended to be straight forward by introducing a single additional property to the event payload which includes the release channel. Then it is for the receiving component to respond to the behaviour. 
Related PR, which should be merged first
https://github.com/snyk/snyk-images/pull/122
=> chore(ci): include release channel in payload

.snyk, cliv2/go.mod, cliv2/go.sum, src/cli/args.ts
Upgrades goproxy to v1.5.0 which removes the need for a workaround introduced here:
https://github.com/snyk/cli/commit/2aed7cb97fb36bb0a2664c7a06ef41d70a87c9d5#diff-cb98b6b0e8336713b5d56cb8986db5a61310c740a8317b9bf42bc90be49e0fb8
=> chore(deps): upgrade go proxy 1.5

cliv2/go.mod, cliv2/go.sum
Updates goproxy to v1.6.0, aimed at mitigating some unhandled error states during the TLS handshake.
=> fix(deps): upgrade goproxy to latest

package-lock.json, package.json
Fixes an issue where users trying to run snyk sbom (or test with `-- -Dverbose`) on a maven project with --maven-aggregate-project fails on the test-compile phase we invoke in case a user is using an older versions of the maven-depepndency-plugin. Since sbom forces a newer version of the plugin, there is no need to invoke that phase.
Run current version and this Pr's snyk on the following pom.xml:
`snyk test --maven-aggregate-project -- -Dverbose`
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>com.example</groupId>
<artifactId>test-compile-failure</artifactId> …
```
=> fix: remove test-compile for mavenAggregateProject with Dverbose or sbom

package-lock.json, package.json
Update snyk-python-plugin in order to support `sys_platform` as specified in PEP508
- Test by scanning a `requirements.txt file with a dependacies like this or similar 
```
six==1.16.0 ; sys_platform == 'darwin' or sys_platform == 'linux'
```
=> feat(python): added Python support for sys_platform [PEP-508]

src/cli/commands/test/iac/scan.ts, src/lib/constants.ts, src/lib/plugins/sast/utils/testEmitter.ts, src/lib/request/request.ts
This PR should set an upper limit on the length of some logs outputted by the `debug` lib. In particular, log a log that outputs an full api response which can lead to the CLI quitting unexpectedly.
=> fix: debug logs causing CLI to quit unexpectedly [CLI-638]

cliv2/cmd/cliv2/errorhandling.go, cliv2/cmd/cliv2/errorhandling_test.go, cliv2/cmd/cliv2/main.go, test/jest/acceptance/snyk-sbom-test/all-projects.spec.ts, test/jest/acceptance/snyk-sbom/npm-options.spec.ts, test/jest/acceptance/snyk-sbom/sbom.spec.ts
This PR introduces a wrapping of golang Errors returned from various places and dependencies in a generic Error Catalog Error. Exceptions are exit code errors and if there is already an Error Catalog Error.
The risk of the change is relatively low, as the changes only focus on decorating errors without altering the content itself
`decorateError()` implements the logic and is integrated in main.go
Run the command below. which will show an error that tells users to add the missing format parameter.
```
snyk sbom
```
=> chore: add generic error catalog errors for golang Errors

src/lib/snyk-test/legacy.ts, src/lib/snyk-test/run-test.ts, src/lib/types.ts, test/jest/acceptance/cli-json-file-output.spec.ts
To support clients that prefer our older depTree format.
When '--print-tree' and '--json-file-output' are used together a depTree object is included in the JSON file.
```shell
snyk test --print-tree --json-file-output=out.json
cat out.json | jq .depTree
```
=> feat: print legacy tree with json file output

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/cli-in-memory-threshold-bytes.spec.ts
This PR changes an often flaky test by removing the usage of an intensive command and replace it by the much simpler command whoami. This requires a small change in gaf to actually support the feature that is being tested here.
https://github.com/snyk/go-application-framework/pull/301
=> fix: replace code test with whoami command

package-lock.json, package.json
Fixes an issue with the nuget cli scanner not being able to process files encoded with UTF-16LE
https://github.com/snyk/snyk-nuget-plugin/pull/232
Can be manually tested with [this fixture](https://github.com/snyk/snyk-nuget-plugin/tree/71556cea22748c20f79b73e6be3b11ddf26af8e6/test/fixtures/target-framework/target-framework-utf16le)
automated test [here](https://github.com/snyk/snyk-nuget-plugin/blob/71556cea22748c20f79b73e6be3b11ddf26af8e6/test/parsers/csproj.spec.ts#L50)
=> fix (test, monitor): Fix dotnet UTF-16LE support for target framework

src/cli/commands/test/iac/output.ts, src/cli/commands/test/iac/v2/index.ts, src/lib/formatters/iac-output/text/share-results.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/output.ts, src/lib/iac/test/v2/scan/results.ts
This PR is related to the IaC V2 product (i.e. `iacNewEngine` feature flag).
Based on the project public id received from `snyk-iac-test` when the --report option is used, show the correct link (Snyk UI) to the project results. If the project is not created properly, show an error message.
Make sure to have the `iacNewEngine` feature flag.
Run the snyk iac test --report command using the corresponding snyk-iac-test version (https://github.com/snyk/snyk-iac-test/pull/264).
The output should include a link to the specific project for which the results are reported.
=> fix (iac): update project page link for iac v2 --report 

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/cli-json-file-output.spec.ts, test/smoke/spec/snyk_code_spec.sh, test/smoke/spec/snyk_monitor_spec.sh
A potential race condition related to authentication has been identified in IntelliJ.
1. IDE starts up CLI with initializationOptions incl. OAuth2 token
2. LS starts WHOAMI workflow with (expired) credentials
3. WHOAMI workflow refreshes OAuth2 token
4. LS saves token and triggers $/hasAuthenticated with new token
5. At the same time, IDE sends the current configuration with DidChangeConfiguration, with the old credentials
6. LS updates the credentials to the old credentials
7. Next call to API returns not authenticated and creds are deleted in LS
8. LS forwards the logout to the IDE.
**Solution: when updating the token, do not accept super-seded tokens (check Expiry)**
Risk: Low and only affects language server
reference: https://github.com/snyk/snyk-ls/releases/tag/hotfix-1.1295.3
=> feat(language-server): hotfix for OAuth2 races

test/fixtures/sast/folder with spaces/index.js, test/jest/acceptance/snyk-code/snyk-code.spec.ts
This PR adds more User Journey tests for consistent ignores to implement the full verification plan
=> chore(code): Add automated tests for consistent ignores

binary-releases/RELEASE_NOTES.md, cliv2/.snyk, cliv2/go.mod, cliv2/go.sum, cliv2/internal/proxy/proxy.go
The downgrade required a replace due to go-git adding goproxy v1.2.3 as a transitive dependency.
=> revert: Undo dependency change to reduce risk for hotfix

release-scripts/next-version.sh
=> chore: update main from 1.1295.3

package-lock.json, package.json
Adds support for scanning kaniko images as they aren't always OCI compliant.
https://github.com/snyk/snyk-docker-plugin/pull/642
Create a kaniko image: `docker run -v .:/workspace [gcr.io/kaniko-project/executor:latest](http://gcr.io/kaniko-project/executor:latest) --dockerfile /workspace/Dockerfile --destination "my-kaniko:latest" --context dir:///workspace/ --tar-path my-kaniko.tar --no-push`
Then scan it with `snyk container test kaniko-archive:my-kaniko.tar`
Low. Is backwards compatible and requires users to manually specify `kaniko-archive:`.
https://github.com/snyk/snyk-docker-plugin/pull/642 (Multiple tests as part of that PR)
=> feat: adds kaniko support

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/cli-json-file-output.spec.ts
This PR implements the same behavior for the golang native code test as the legacy implementation, when scanning a code base without findings and using `--sarif-file-output`. The expected behavior based on the legacy implementation is, that if there are no code test findings, the sarif file is not created at all.
The risk of the change is low, since currently the only affected flow is code test.
The main functionality is implemented here https://github.com/snyk/go-application-framework/pull/304
This PR just configures the output workflow and re-enables a test for the golang native implementation, that previously failed due to the difference in behavior.
Run `snyk code test --sarif-file-output=myfile` on a code base 
1. with findings => myfile is created
2. without findings => myfile is …
=> fix(code): Don't write sarif files when no results are found

package-lock.json, package.json
Allows `snyk test --scan-all-unmananged` in a directory with jar/war/aar files, to identify all possible identities based on the sha1 hash of the files. 
It will take the file name into consideration when identifying the package. 
For example: 
- `some-maven-jar-1.0.0.jar` resolves to <some-sha1> 
which corresponds with `group1:artifact:1.0.0` and `group2:artifact:1.0.0` 
will result in showing both `group1:artifact:1.0.0` and `group2:artifact:1.0.0`
- `group1-artifact-1.0.0.jar` resolves to <some-sha1> 
which corresponds with `group1:artifact:1.0.0` and `group2:artifact:1.0.0` 
will result in only `group1:artifact:1.0.0`
After this change some users of `--scan-all-unamnaged` will potentially see more packages showing than previously.
https://github.com/snyk/snyk-mvn-plugin/pull/182
1. …
=> feat: display all applicable maven unmanaged identities

src/lib/prune.ts, test/jest/acceptance/analytics.spec.ts
This PR makes two optimisations to the `run-test` flow. These are designed so as to be transparent to users except for increased performance for projects with dense dependency graphs - "dense" defined as graphs with many cross linking dependencies leading to very many paths to the root of the graph.
Our main culprit is `countPathsToRoot()` which goes through every pkg in a graph and accumulates a count of all paths to root from all nodes. This is then compared to our prune limits to see whether we should prune, the only other thing this result is used for is analytics.
**`--pruneRepeatedSubdependencies` short circuit:**
Previously if a user passed the `--pruneRepeatedSubdependencies` flag the prune functionality still counted paths to root and calculated whether we were dealing with a …
=> feat: minimise how often countPathsToGraphRoot is called

src/cli/ipc.ts, src/cli/main.ts, src/lib/unexpected-error.ts, test/jest/unit/cli/ipc.spec.ts, test/jest/unit/lib/unexpected-error.spec.ts
This PR ensure that unhandled errors/exceptions are also passed between the Typescript and Golang CLI.
=> fix: preserve unhandled errors

cliv2/internal/cliv2/cliv2.go, src/cli/ipc.ts, src/cli/main.ts, src/lib/unexpected-error.ts, test/jest/unit/cli/ipc.spec.ts, test/jest/unit/lib/unexpected-error.spec.ts
Previously, we would try to open the IPC error file even though the legacy cli run didn't result in any errors (this would not create the file as a result). The debug logs would log `Failed to read error file:  open <err-file-path>:  no such file or directory`, which might cause confusion for users. 
If the legacy CLI run resulted in an exit error with an exit code 0 or 1, we would not attempt to read from the error file; meaning if the exit code is greater or equal to 2, the error file should be checked against.
- run a commad that invokes the Typescript CLI and would exit with the exit code 0 or 1 -> the debug logs should not contain the message listed above
- run a commad that invokes the Typescript CLI and would exit with the exit code 0 or 1 -> the debug logs should contain a log …
=> fix: fix IPC error handling

src/cli/commands/test/iac/local-execution/types.ts, src/lib/iac/test/v2/errors.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, test/jest/acceptance/iac/cli-share-results.spec.ts
Removes the `FeatureFlagNotEnabled ` error code that was mapping an error we added in snyk-iac-test to stop the scan of an IaC project when we run `snyk iac test --report` with the FF `iacNewEngine` being enabled. As we completed the CLI flow, we can now safely create an `IaCV2 Project` in the UI therefore we can stop adding an error when we try to do a scan from the CLI with `iacNewEngine` FF enabled and the `--report` command.
Update the `snyk-iac-test` to latest version where we removed this error.
Risk: low
`<local build> iac test --org=<org_that_has_iacv2>`
Run comand: `snyk iac test --report` on an IaC Project, having the FF `iacNewEngine` enabled. This command should run a complete scan your IaC Project and create a target in the UI and not the error: `flag --report is not yet …
=> fix(iac): removed FeatureFlagNotEnabled error and updated snyk-iac-test [IAC-3235]

cliv2/internal/cliv2/cliv2.go, cliv2/internal/cliv2/cliv2_test.go
Adds some unit tests for the IPC, as the missing part of [CLI-755](https://snyksec.atlassian.net/browse/CLI-755).
[CLI-755]: https://snyksec.atlassian.net/browse/CLI-755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add IPC unit tests

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/snyk-code/snyk-code-user-journey.spec.ts
This PR fixes an incompatibility between the CLI and snyk-to-html, when trying to generate an html report for `snyk code test` using consistent ignores. The inconsistency comes from a change in the Driver Name as part of the Sarif content. The Driver Name now matches `SnykCode` again and an existing USer Journey test has been extended.
The risk of the change is low, as it only affects the Driver Name written for the new native code test implementation, which is still behind a feature flag.
https://github.com/snyk/go-application-framework/pull/316
Given an org that uses consistent ignores, run
```
snyk code test --sarif | snyk-to-html --output=out.html
```
inspect the file out.html to be a `Snyk Code Report`.
=> fix(code): fix backward compatibility issue in sarif driver name

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Updates snyk-iac-test for the following:
- proxies a request in the IaC+ scanning process that might get blocked if the customer environment blocks non-proxied traffic
- other security fixes
`snyk iac test` with an org that has IaC+
No product update that needs to be communicated. We are fixing a bug that made IaC+ not work for customers that have internal proxies.
https://snyksec.atlassian.net/browse/IAC-3264
=> fix: proxy iac test request [IAC-3264]

.dockerignore
Adding a default `.dockerignore` file as per best practice guidelines. Values are not explicitly for our current need, also potential future additions, took most from our service template.
=> chore: adding default dockerignore from node service template

cliv2/go.mod, cliv2/go.sum
This PR updates the version of the `container-cli` plugin (to make use of the changes [here](https://github.com/snyk/container-cli/pull/30)), adding a `--platform` flag to the container sbom command. The value for the platform is passed through to the container test command, and results in the SBOM specifically for that platform.
To test, build and run the CLI with the arguments
```sh
container sbom --format spdx2.3+json nginx:latest --platform=linux/amd64
```
Test with different values for `--platform`, e.g. `linux/386`, and you should see different results
=> feat(sbom): add `--platform` flag to `container sbom` command

cliv2/internal/cliv2/cliv2.go, test/jest/acceptance/api-auto-detect.spec.ts, test/jest/acceptance/snyk-config/snyk-config-endpoint.spec.ts
The PR ensures to always specify the API URL when running the legacy Typescript CLI. Before the API URL was only set when the API was explicitly set but given the possibility to derive an URL from a OAuth claim, we need to always set the URL.
There was no closed box test for this, which is now there and one test had to be adapted since a side-effect of the change is, that an error message changed. Since the error message is only a side effect of one command and testing the edge case of an incorrectly specified `endpoint`, I removed these unrelated checks from the test.
The Risk of the change should be low, as it only ensures that both golang and typescript CLI actually use the same API URL, making the golang CLI as the single source of truth.
`cliv2/internal/cliv2/cliv2.go`
Run the test …
=> fix: Always set the API URL for legacy CLI invocations

.circleci/config.yml
Manual resync the signing certificates when windows code signing happens as an extra step in the build pipeline.
After recent failures in the pipelines we discovered that the code signing for Windows was not working as expected and required manual resyncing in order for the certificates to be valid.
=> chore: manual resync windows signing certs

package-lock.json, package.json, test/jest/acceptance/snyk-container/container.spec.ts
Adds support for scanning archives without specifying the image type. This implies finding the absolute path of the archive file specified and fallback on different type of extractors when decompressing the archive.
Snyk can directly scan or monitor a Docker or OCI archive by running the following commands: 
```
snyk container test docker-archive:archive.tar
snyk container test oci-archive:archive.tar
snyk container test kaniko-archive:archive.tar
```
Manually defining the image type adds complexity, increases the risk of errors, and may not account for dynamic updates of the pipelines where the customer has deployed snyk. This change adds support for scanning archives without specifying the image type.
The change can be tested by providing only the .tar filename without specifying …
=> feat: container scan support for image.tar scan with unspecified image type CN-62

cliv2/cmd/cliv2/main.go, cliv2/internal/proxy/interceptor/interceptor.go, cliv2/internal/proxy/interceptor/interceptor_test.go, cliv2/internal/proxy/interceptor/v1_analytics.go, cliv2/internal/proxy/interceptor/v1_analytics_test.go, cliv2/internal/proxy/proxy.go, cliv2/pkg/basic_workflows/legacycli.go, test/jest/acceptance/analytics.spec.ts, test/jest/acceptance/instrumentation.spec.ts
We need to move our old `v1` analytics to the new `v2` analytics service. Since most `v1` analytics are sent from the legacy CLI, this logic needs to introduce a concept of a proxy interceptor to catch the data sent from the legacy CLI to the GAF.
This PR does not include logic to stop sending `v1` analytics to the old analytics endpoint. This will be done later after we're satisfied that this solution is working properly. 
`v1` analytics will not be included for users that have opted out using the `SNYK_DISABLE_ANALYTICS` environment variable.
[legacycli.go](https://github.com/snyk/cli/pull/5813/files#diff-4335575c8f0b1309962060936d3e65b1d200ede93a64a6faeab366204a1dc65aR182-R185) does the registration of interceptors. These have been engineered to be extendable in case we need to …
=> feat: [CLI-825] Including sanitized legacy `v1` analytics in `v2` analytics payload

cliv2/cmd/cliv2/main.go
=> chore: added ignore wf cmd

package-lock.json, package.json
This bumps the snyk-gradle-plugin version to 4.9.2 (https://github.com/snyk/snyk-gradle-plugin/releases/tag/v4.9.2 & https://github.com/snyk/snyk-gradle-plugin/releases/tag/v4.9.1) what contain fixes for running on windows only. Plugin has been fully tested and new tested have been added within the plugin.
https://snyksec.atlassian.net/browse/OSM-2475
https://snyksec.atlassian.net/browse/OSM-2534
=> feat: bump gradle plugin to v4.9.2

package-lock.json, package.json
Bumps the version of the PHP Plugin used by the CLI, which fixes Open Source scanning of PHP projects.
Previously when  `composer`/ `composer.phar` is available on the machine, the command's result `stdout` was not handled properly and resulted in `[object Object]` being parsed as JSON.
Risk is **Low** as this only affects PHP, which has low traffic and it fixes a bug rather than changing any logic.
- Run the CLI on a directory containing PHP code, making sure that you have [composer](https://getcomposer.org/download/) either installed globally or the `composer.phar` file in the current working directory.
- This should output scan results as expected, while before this would have crashed with a JSON parsing error
Scanning open source dependencies of PHP projects when composer is installed …
=> fix: [OSM-2584] Bump PHP plugin version to fix project scanning

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, test/fixtures/ai-bom/python-chatbot/chatbot.py, test/fixtures/ai-bom/python-chatbot/requirements.txt, test/fixtures/ai-bom/sample-ai-bom-sarif.json, test/jest/acceptance/snyk-aibom/aibom.spec.ts
Registers a new CLI extention cli-extension-ai-bom. This version of the extension adds a single command `snyk aibom` which creates an AI Bill Of Materials in CycloneDX format and outputs it to the command line.
The codebase for the extension is: https://github.com/snyk/cli-extension-ai-bom . It's currently relatively small & follows the standard structure of a golang CLI extension.
The main thing we do to the CLI in this PR is register the extension in `cliv2/cmd/cliv2/main.go`.
This CLI extension adds a new command. It should not impact any other commands. The command requires both a `--experimental` flag and an org_public_id based Feature Flag to be enabled.
Build the CLI, `make build`. Run the CLI against any python project with AI assets. e.g. 
`snyk aibom …
=> feat: added aibom extension

package-lock.json, package.json, test/acceptance/workspaces/maven-dverbose-scopes-collision/pom.xml, test/jest/acceptance/snyk-test/maven-dverbose.spec.ts
Fixes a bug in the maven Dverbose graph building algorithm for specific cases where there are collisions of scope for some packages from the '-Dverbose' maven output.
These 3 PRs come together:
https://github.com/snyk/snyk-mvn-plugin/pull/188 - split of dverbose/not dverbose graph build functions. dverbose function includes the fix where we use scope in the package key for visited + correct queue push in the bfs.
https://github.com/snyk/snyk-mvn-plugin/pull/186
https://github.com/snyk/snyk-mvn-plugin/pull/187
This PR explains the fix: https://github.com/snyk/snyk-mvn-plugin/pull/188 and also includes a fixture to represent the use case for the bug.
Using [this](https://github.com/snyk/snyk-mvn-plugin/pull/188/files#diff-4d3fa7b6d46cb0847aee3aab11bab7acafa86f304e49ade1064f8fa222398a62) …
=> fix: maven dverbose scope collisions failures

help/cli-commands/container-test.md, package-lock.json, package.json, test/jest/acceptance/snyk-test/target-reference.spec.ts
Adds test cases for the target ref support in container monitor and test, following support addition in the snyk-docker-plugin https://github.com/snyk/snyk-docker-plugin/pull/649.
This change mainly bumps the docker plugin to 7.0.1 and add tests for the newly added target reference support in snyk container test.
Running  `snyk container test <IMAGE> --target-reference=<VALUE>` should send a payload containing the target reference in the scanResult object sent to /test-dependencies endpoint.
The product update is deferred to a later time. This change currently requires a FF in the platform to be effective. 
While the plan is for a wider rollout, we're taking extra precautions to validate that no one is relying on the "erroneous" behavior. 
Behavior that could cause a change is a …
=> fix: add container test target reference support [CN-71]

test/jest/acceptance/iac/file-output.spec.ts, test/jest/acceptance/iac/multidoc-yaml.spec.ts, test/jest/acceptance/iac/org-flag.spec.ts, test/jest/acceptance/iac/test-arm.spec.ts, test/jest/acceptance/iac/test-cloudformation.spec.ts, test/jest/acceptance/iac/test-directory.spec.ts, test/jest/acceptance/iac/test-kubernetes.spec.ts, test/jest/acceptance/iac/test-terraform-plan.spec.ts
Adds acceptance tests for `IaCV2`. We need acceptance test for IaCV2 to verify that a new change made in the CLI does not affect IaC scans for IaCV2.
The new acceptance tests cover a range of scenarios, including:
- Verification of file output (`file-output.spec.ts`).
- Directory scanning across multiple IaC types (`test-directory.spec.ts`).
- Correct handling of the --org flag (`org-flag.spec.ts`).
And the folowing tests validating scans for multiple IaC types (like `arm`, `cloudformation`, `terraform`, `terraform-plan`, `kubernetes`):
- `multidoc-yaml.spec.ts`
- `test-arm.spec.ts`
- `test-cloudformation.spec.ts`
- `test-kubernetes.spec.ts`
- `test-terraform-plan.spec.ts`
These tests validate behavior with different output formats (`--json`, `--sarif`), severity threshold filtering …
=> test: add acceptance tests for IaCV2 [IAC-3297]

package-lock.json, package.json, test/acceptance/workspaces/maven-dverbose-omitted-versions/pom.xml, test/jest/acceptance/snyk-sbom/all-projects.spec.ts, test/jest/acceptance/snyk-sbom/maven-options.spec.ts, test/jest/acceptance/snyk-test/maven-dverbose.spec.ts
Bumps snyk-mvn-plugin to include: https://github.com/snyk/snyk-mvn-plugin/pull/189.
Includes:
1. dfs for graph creation - for cycles and dense graphs.
2. package version in the key for the visited/ancestry.
As mentioned on the PR, dependening on the decision to only keep the scope/versions that maven resolves dependencies to, instead of the Dverbose output, a change will come on top of this one.
https://github.com/snyk/snyk-mvn-plugin/pull/189
Test with the example [here](https://snyksec.atlassian.net/browse/OSM-2668?focusedCommentId=1183736).
[test, monitor, sbom] Maven Dverbose improvement for long running scans resulting from dense dependency graphs creation.
https://snyksec.atlassian.net/browse/OSM-2668
=> feat: [OSM-2668] introduced dfs for  maven dverbose

package-lock.json, package.json, test/jest/acceptance/snyk-sbom/all-projects.spec.ts, test/jest/acceptance/snyk-sbom/maven-options.spec.ts
Follow-up from https://github.com/snyk/cli/pull/5891: keep only the versions resolved by maven in the Dverbose algorithm.
Tests are reverted to the values before this PR: the dependency that actually gets resolved by maven (not considered, but omitted) is at version 1.0.3. Same thing for the length of the dependencies array.
This is introduced: https://github.com/snyk/snyk-mvn-plugin/pull/190, see tests.
`snyk test/monitor -- -Dverbose` or `snyk sbom` on the fixtures projects.
[test, monitor, sbom] Maven Dverbose algorithm adds only the dependencies resolved by maven in the dependency graph/sbom.
https://snyksec.atlassian.net/browse/OSM-2668
=> fix: [OSM-2662] maven dverbose show resolved deps versions only

.vscode/launch.json
Small addition to the launch configuration for VSCode. The new option will open the prompt for choosing the CLI process to attach to. Note this debug option applies to the Golang binary.
- `.vscode/launch.json` - Almost the same configuration as the one listed in [the contributing guidelines](https://github.com/snyk/cli/blob/main/CONTRIBUTING.md#debugging-the-go-binary-with-vscode), but the remote path is not necessary since you would still need to choose the process to attach to (shoutout to @j-luong).
Put some breakpoints, make a debug build of the CLI and run it, switch to VSCode and use the new launch config option to select the CLI process to attach to (searching for snyk make it easy to find).
Nil
=> chore: Add attach to CLI process debug configuration for VSCode

cliv2/go.mod, cliv2/go.sum
We recently introduced changes in cli-extension-aibom (in [this PR](https://github.com/snyk/cli-extension-ai-bom/pull/19)) and in code-client-go (in [this PR](https://github.com/snyk/code-client-go/pull/101)) that allow the aibom cli-extension to use depgraphs as part of the resulting BOM.
This PR aims to bump the corresponding versions in `go.mod` so they can be used by the CLI. Risk level should be minimal as this does not modify any existing behavior, just adds new one.
~**DO NOT MERGE** until [PR#876](https://github.com/snyk/snyk-ls/pull/876) has been merge in snyk-ls and the `go.mod` version has been bumped accordingly.~
[The PR](https://github.com/snyk/snyk-ls/pull/876) has been merged, and snyk-ls version has been bumped as part of this PR (notably, this means that the PR now also …
=> chore: version bump to allow ai-bom extension to use depgraphs

release-scripts/upload-artifacts.sh
In the previous version of the script that triggers snyk-images to build when a new CLI version is deployed, error cases where only showing the status code of the API request. While the response body was swallowed, it actually contains valuable information to debug or resolve issues. 
With this PR the response body is preserved and displayed in case of an error.
Risk: Low, since it only changes the error handling of a deploy script
Run the following steps in a terminal
```
export HAMMERHEAD_GITHUB_PAT=random
./release-scripts/upload-artifacts.sh trigger-snyk-images
```
the output should look like this
```
Triggering build-and-publish workflow at snyk-images...
Version: v1.1298.0-preview.d70f16aba24ba882785a0869bc42dffcc15ff408
Release Channel: dev
Failed to trigger build-and-publish …
```
=> chore(ci): Print details when failing to trigger snyk-images

.circleci/config.yml, Makefile
This PR adds an additional earlier check of the generated version to the build pipeline.
The reason is, that issues with the version number where only checked and alerted on when the builds were done, which increases the feedback loop unnecessarily. Now the version is additionally checked when the it is generated. Doing it twice doesn't hurt and keeps all the validations in the pre-release step in one place.
Risk: Low, since it is just an additional check that is already part of the pipeline.
Execute `make release-validate-version` in the repository root.
N/A
=> chore(ci): Check the version earlier during a build

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/snyk-aibom/aibom.spec.ts
This PR bumps the version of the https://github.com/snyk/cli-extension-ai-bom dependency.
The change there (see https://github.com/snyk/cli-extension-ai-bom/compare/60fe93bb8ab6...68d20d659a0e) consists of the new flag `--html` added to the experimental `aibom` command and a minor dependency bump.
The new flag changes the output that `aibom` produces - instead of CycloneDX JSON it is a pretty-printed HTML.
We deem the risk of merging this PR as small.
Run `make build` inside the CLI, then inside a python repo run `$HOME/cli/binary-releases/snyk-linux aibom --experimental --html >aibom.html`. This command will write the AIBOM, visualized as a graph, to `aibom.html` that you can open in the browser.
This PR contains an new automated test for it as well. …
=> feat(aibom): support optional html rendering when using --html

package-lock.json, package.json, test/acceptance/workspaces/nuget-app-9-globaljson/dotnet_9.csproj, test/acceptance/workspaces/nuget-app-9-globaljson/global.json, test/acceptance/workspaces/nuget-app-9-globaljson/program.cs, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
Improved support for comments in Dotnet's `global.json` file using a JSONC parser.
Run `snyk test` on a Dotnet project having a `global.json` file which containing a URL, such as:
```json
{
"comment": "Only update the version manually with major SDK updates, see https://dotnet.microsoft.com/en-us/download/dotnet.",
"sdk": {
"version": "9.0.100",
"rollForward": "latestMajor"
}
}
```
Improved support for comments in Dotnet's `global.json` file. Imports that failed when that file contained special content such as URLs will no longer fail because of it.
[OSM-2902](https://snyksec.atlassian.net/browse/OSM-2902)
[OSM-2902]: …
=> fix: [OSM-2902] Better support for comments in Dotnet global.json

src/lib/config/api-url.ts, src/lib/formatters/iac-output/text/share-results.ts, test/jest/unit/config/api-url.spec.ts, test/jest/unit/lib/formatters/iac-output/text/share-results.spec.ts
This change updates the URL generated by `snyk iac test --report` command to consistently use the `app.snyk.io` domain (or its regional equivalent, e.g., `app.eu.snyk.io`) instead of the root `snyk.io` domain. This was previously working because of some redirects between the Snyk domains, that were redirecting the domain `https://eu.snyk.io` to `https://app.eu.snyk.io/`.
A new `getAppUrl` helper function has been introduced in `lib/config/api-url.ts` to reliably derive the correct application base URL, which is now used in the output formatting for shared IaC test results.
`<local build> iac test --report`
Run comand: `snyk iac test --report` …
=> fix(iac): output URL for IaC to contain correct domain [IAC-3367]

.circleci/config.yml, .snyk, binary-releases/RELEASE_NOTES.md, cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/debuglog.spec.ts
With this change debug logs will redact Basic Authorization header if they would accour. While Basic Auth is not a common case in the CLI, there are edge cases where this could happen.
In addition, this PR updates the golang version from 1.23.8 to 1.23.10.
https://github.com/snyk/go-application-framework/pull/363
1. Stop docker daemon
2. snyk container test ubuntu:latest --username=us --password=pw -d
3. The debug logs must include `Basic ***`
N/A
CLI-949
=> fix(logging): Redact Basic auth from debug logs if it exists

.github/workflows/sync-cli-help-to-user-docs.yml, .github/workflows/sync-cli-readme.yml
Fixes bugs that I didn't catch in the https://github.com/snyk/cli/pull/5955. Among other things, commits must be signed, so we're utilizing the Team CLI Bot's keys to do the commit.
Same as https://github.com/snyk/cli/pull/5955
Same as https://github.com/snyk/cli/pull/5955
None, infrastructure change.
=> chore: [CLI-936] Fix bugs from previous update-docs commit

cliv2/go.mod, cliv2/go.sum
Updates the experimental cli extension ai-bom.
The output of `snyk aibom --experimental --html` was improved:
* updates the aibom colors to better distinguish the MCP components
* introduces a fixed order in the legend
* adds the type of the components to the label in the graph, to make the graph more readable
https://github.com/snyk/cli-extension-ai-bom/pull/25 and https://github.com/snyk/cli-extension-ai-bom/pull/26.
`snyk aibom --experimental --html`. Users need to be on an allow-listed org to use this command.
None.
https://snyksec.atlassian.net/browse/AIBOM-100
Low. `snyk aibom` is an experimental feature, the rollout is tightly …
=> feat: support mcp components in aibom html output

.circleci/config.yml
Fixes the build dependency of testing go before build preparations have finished.
=> chore: wait for testing go until prepare build is done

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, package.json, test/jest/acceptance/snyk-code/snyk-code-user-journey.spec.ts
This PR changes the behaviour of the golang native `code test` implementation to match the typescript implementation with regards to output file handling.
1. It enables to specify and write two different files when specifying `--sarif-file-output` and `--json-file-output`.
2. It mimics the behaviour where testing a code base without issues creates an empty sarif file for `--sarif-file-output` but doesn't create a file for `--json-file-output`.
The main changes can be found in [this GAF PR](https://github.com/snyk/go-application-framework/pull/375). 
This PR also adds user journey tests for both cases and adapt the output configuration based on …
=> fix: support using sarif and json output files at the same time

package-lock.json, package.json, src/cli/commands/monitor/index.ts, src/lib/package-managers.ts, src/lib/snyk-test/index.js, src/lib/types.ts, test/jest/acceptance/snyk-sbom/all-projects.spec.ts, test/jest/acceptance/snyk-sbom/maven-options.spec.ts
Sends an option 'mavenVerboseIncludeAllVersions' to the snyk-maven-plugin based on a feature flag. 
This option enables returning a more exhaustive dep graph/sbom for maven (Dverbose) - including all versions of dependencies that maven considers for resolution (not just the versions that get resolved). 
Also bumps snyk-mvn-plugin to include the behaviour with the enabled option: https://github.com/snyk/snyk-mvn-plugin/pull/195.
This change enables the behaviour in this previous PR: https://github.com/snyk/cli/pull/5891 (under a feature flag).
The default behaviour is the one last introduced here: https://github.com/snyk/cli/pull/5894
Use any …
=> chore: maven dverbose returns all versions of deps under ff

cliv2/go.mod, cliv2/go.sum
```
commit af6f306b820ec2f5fd314fcdd841f5c7d6265d43
Author: Bastian Doetsch <bastian.doetsch@snyk.io>
Date:   Mon Jul 21 17:13:12 2025 +0200
fix: populate local branches even when base branch cannot be determined [IDE-1238] (#927)
fix: populate local branches even when base branch cannot be determined
When neither 'main' nor 'master' branches exist in a git repository,
the getFromGit function was returning an error and preventing local
branches from being stored in the folder config.
This change allows local branches to be populated in the folder config
even when a base branch cannot be determined. The base branch field
will simply remain empty in such cases.
Added tests to verify the fix works correctly, with Windows compatibility
by ensuring git user configuration is set before commits. …
```
=> chore(language-server): integrate LS

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/snyk-sbom-monitor/all-projects.spec.ts, test/jest/acceptance/snyk-sbom-test/all-projects.spec.ts
This PR is based on newly introduced helper functions to ensure experimental workflows are handled consistently. 
It also moves the responsibility to raise an error from the workflows themselves to the application layer, which is more correct from the perspective of concerns as an error might not be the correct behaviour for every application.
Some existing tests had to be adapted to not expected an explicit text but rather ensure that the cli fails.
https://github.com/snyk/go-application-framework/pull/386
Running the following commands should behave the same and show the following error
Errors (SNYK-CLI-0015)
```
snyk whoami
snyk sbom test …
```
=> chore: adding a central check for the experimental flag

.circleci/Dockerfile, .circleci/config.yml, .dockerignore, cliv2/Makefile, cliv2/go.mod, cliv2/go.sum
This PR updates golang from 1.23 to 1.24 and adapt to the new FIPS related aspects. 
1. Updated how FIPS is enabled https://github.com/snyk/go-application-framework/pull/391
2. Update golang version build image 
3. Updated e2e test image to use an image that has fips enabled by default
=> chore(dependency): Upgrade to golang 1.24.4

package-lock.json, package.json
Bumps snyk-nuget-plugin to version 2.10.4. This was done in order to correctly locate the `project.assets.json` files in cases where it's destination path was altered with .Net properties. Related snyk-nuget-plugin [PR here](https://github.com/snyk/snyk-nuget-plugin/pull/258)
Checking the snyk-nuget-plugin [PR here](https://github.com/snyk/snyk-nuget-plugin/pull/258)
By testing the CLI versions again [this fixture](https://github.com/snyk/snyk-nuget-plugin/pull/258/files#diff-39a2e085ff3ffb024f8f8acc7aa9a7126548ce926a1176fa0afdc0197d579038R1)
-
Low, we try to fetch the assets file by it's normal location and only if that fails we're going to …
=> fix: resolve project assets file path dynamically

cliv2/go.mod, cliv2/go.sum, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Upgrades IaC components to the latest version in which a minor fix of a package that had a vulnerability was added.
```
<local build> iac test --help
<local build> iac rules --help
```
^ but no changes were introduced, those should work as until now
The commands would work for orgs that have IaC+ enabled.
For IaC command:
```
<local build> iac test <path_for_iac_files>
```
For the rules extension:
```
<local build> iac rules init - try something from this interactive UX
For something already written rules from here: https://github.com/chdorner-snyk/sandbox-custom-rules use <local build> iac rules push --org=<that_has_iac+>
```
None, no …
=> fix(iac): upgrade iac components to address a vulnerability [IAC-3439]

.circleci/config.yml
This PR fixes our CICD pipelines, which broke due to a deprecation in the goobject-introspection homebrew [formula](https://github.com/Homebrew/homebrew-core/pull/240475).
CICD should not fail due to 
```
Error: gobject-introspection: no bottle available!
If you're feeling brave, you can try to install from source with:
brew install --build-from-source gobject-introspection
```
n/a - this is an internal change for our CICD pipelines
=> fix(cicd): "gobject-introspection" error when setting up macos acceptance tests

package-lock.json, package.json, test/jest/unit/policy.spec.ts
We're fixing an issue where where:
You have ignores with different casing e.g. NPM:HAWK:20160119 vs npm:hawk:20160119 
The first ignore is expired
The other ignores that are active do not have the same casing 
Then no ignores are applied to the vuln
What was happening in the logic is that we were setting the value of the vulnId to the value of whatever matches first when checking the ignore keys. That vulnId is then used to check the ignores, so if you have other ignores that do not have the same casing exactly they are never checked.
This PR introduces logic to have a variable for all matching vuln IDs with all types of casing to then check …
=> fix: ignore casing fix in the policy lib

package-lock.json, package.json, test/fixtures/maven-metaversion/pom.xml, test/jest/acceptance/snyk-test/print-graph.spec.ts
Bumps `snyk-mvn-plugin` to `v4.3.0` and adds simple fixture exercising metaversion resolution.
`snyk-mvn-plugin` contains two notable PRS:
- https://github.com/snyk/snyk-mvn-plugin/pull/198 -- adds support for fingerprinting of artifacts
- https://github.com/snyk/snyk-mvn-plugin/pull/202 -- adds support for maven metaversions
We are only concerned with the features added by the second PR. The first has its functionality locked behind additional options and will _not_ affect the behaviour of the `snyk-mvn-plugin` without changes to the `cli` as well as various `cliv2` extension repositories. See …
=> feat(test): Adds support for maven metaversions

src/cli/commands/constants.ts, src/cli/commands/monitor/index.ts, src/cli/commands/test/index.ts, src/lib/feature-flags/index.ts, test/acceptance/fake-server.ts, test/jest/unit/cli-commands/test-and-monitor.spec.ts, test/tap/cli-test/cli-test.docker.spec.ts
use the --include-system-jars option on the Snyk Docker Plugin to scan the usr/lib folder for JAR files
Reads the `scanUsrLibJars` feature flag and correspondingly sets the `--include-system-jars` parameter when calling snyk-docker-plugin
Main change is in test (cli/commands/test/index.ts) and monitor (cli/commands/monitor/index.ts) command files.  The rest is updating testing.
A default `snyk container test/monitor` should return identical results (since the feature flag is off by default).  You can turn the feature flag on, then us `--print-deps` on a container image with JARs in the usr/lib (example openjdk:8-jdk-alpine), and ensure that …
=> feat: [CN-249] support scanning system JARs

package-lock.json, package.json, test/acceptance/workspaces/nuget-app-pinned-deps/pinned-deps.csproj, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
Bumps the snyk-nuget-plugin in order to fix an issue with NuGet v3 scanner where the pinned dependencies were not discovered.
By reviewing [this PR](https://github.com/snyk/snyk-nuget-plugin/pull/262)
Using this [fixture](https://github.com/snyk/snyk-nuget-plugin/pull/262/files#diff-9dbf354d0d14054b62ef9d797a89aea62f9ca8fb549245047391d470e511d95cR1) or by running this [test](https://github.com/snyk/snyk-nuget-plugin/pull/262/files).
This is a small fix, no product update apart from the one going to a support ticket. Also, NuGet v3 scanner is not GA yet, it is currently beta tested by customers.
=> fix: OSM-2364 discover pinned dependencies in nuget v3 scanner

package-lock.json, package.json, test/acceptance/workspaces/nuget-app-netcore31/netcore31.csproj, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
Bumps the snyk-nuget-plugin in order to fix an issue with NuGet v3 scanner where the netstandard and netcoreapp TargetFrameworks were treated as .netx.x
By reviewing [this PR](https://github.com/snyk/snyk-nuget-plugin/pull/264)
Using this [fixture](https://github.com/snyk/snyk-nuget-plugin/pull/264/files#diff-2ad7e47f491557dbeb622ceee0b69d716386163c5f6cc63e23283789efbdfc0dR1) or by running this [test](https://github.com/snyk/snyk-nuget-plugin/pull/264/files#diff-df7909f937abc25b7051556819b8a8347adfa7d5133bd1e15be6e9161005b1ecR302).
This is a small fix, no product update apart from the one going to a support ticket. Also, NuGet v3 scanner is …
=> fix: exclude assemblies for netstandard and netcoreapp for nuget v3

.gitleaksignore, src/lib/errors/error-catalog-factory.ts, src/lib/errors/failed-to-get-vulnerabilities-error.ts, src/lib/errors/failed-to-run-test-error.ts, src/lib/errors/monitor-error.ts, src/lib/request/promise.ts, test/jest/acceptance/error-catalog.spec.ts
This PR mainly fixes multiple issues in the Typescript Error Handling for Errors with dynamic status code. 
It implements a simple factory to create error catalog errors based on status codes and uses it for the 3 dynamic Errors that require it. A forth Auth Error, doesn't require this dynamic handling.
The PR adds an integration test for `snyk container monitor`, which previously incorrectly mapped all errors to SNYK-9999 (which represents a 500 status). No SNYK-9999 is only mapped if the status is 500 otherwise the Generic Error is being raised.
To enable the tests this PR also fixes a small bug that was causing a crash when a network …
=> fix: Fix incorrect error mapping for varying status codes
