help/cli-commands/iac-describe.md
Adds documentation for the service argument that can be passed to `snyk iac describe `command.
help/cli-commands/iac-describe.md
This md file is used to present information directly in the command line and I started with presenting the service to resource infromation in a table, the table directives however are not rendered properly so decided to stick with a simple list. I'm aware that the list output is a bit long however I think presenting the whole list of available services is valuable.
`snyk iac  describe --help`
https://snyksec.atlassian.net/browse/CFG-1529
=> chore: document drift service argument

help/cli-commands/iac-gen-driftignore.md, test/jest/unit/cli/commands/help/help.spec.ts
This PR is a follow up of #2768 and inspired of #2780 
`help/cli-commands/iac-drift-gen-driftignore.md`
`snyk iac drift gen-driftignore --help`
https://snyksec.atlassian.net/browse/CFG-1606
=> Add gen-driftignore help

help/cli-commands/iac-describe.md
Remove service to resource mapping information from CLI help.
=> docs: remove service to resource mapping information

src/cli/commands/protect/wizard.ts
Log wizard removal message when wizard is called
=> feat: wizard removal message

src/cli/commands/protect/index.ts, test/jest/acceptance/snyk-protect/protect-patch-skip.spec.ts, test/jest/acceptance/snyk-protect/protect-patch.spec.ts
Log protect removal message when protect is called.
=> feat: log protect removal message

release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/go.mod, release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/go.sum, test/fixtures/iac/terraform/var_deref/nested_var_deref/sg_open_ssh.tf, test/fixtures/iac/terraform/var_deref/sg_open_ssh.tf, test/jest/acceptance/iac/test-directory.spec.ts, test/jest/acceptance/iac/test-terraform-var-deref.spec.ts
Adds support for local variables by updating the `snyk-iac-parsers` version.
Test a TF file that uses local variables and experience  M A G I C!!
https://snyksec.atlassian.net/browse/CFG-1500
=> feat: update snyk-iac-parsers version

.github/workflows/smoke-tests.yml
Fixes https://github.com/snyk/cli/runs/5499742074
=> chore: scoop requires a flag to install as admin

package-lock.json, package.json
- add support for handling `.snyk` policy files in unmanaged
c/c++ flows.
- bump the cpp-plugin version to enable the functionality
=> feat: unmanaged cpp snyk policy support

package-lock.json, package.json
- update the error message shown to the client when exiting with a status code 3
to make it less confusing (for the unmanaged c/c++ flows)
- bump the cpp-plugin version to enable the above change
=> fix: unmanaged cpp error message

release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/go.mod, release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/go.sum, test/fixtures/iac/terraform/var_deref/sg_open_ssh.tf
This PR adds support for locals that reference other locals, using [v1.1.0](https://github.com/snyk/snyk-iac-parsers/releases/tag/v1.1.0) of `snyk-iac-parsers`. 
The existing fixture was modified so that the test verifies locals support and locals referencing other locals. There's no need for manual testing.
https://snyksec.atlassian.net/browse/CFG-1654
=> feat: add support for locals referencing locals [CFG-1654]

.github/CODEOWNERS
This PR changes the code owners of src/lib/container path.
=> chore: Change codeowners for src/lib/container

src/cli/commands/test/iac-local-execution/assert-iac-options-flag.ts, src/cli/commands/test/iac-local-execution/index.ts, src/cli/commands/test/iac-local-execution/share-results.ts, src/cli/commands/test/iac-local-execution/types.ts, src/lib/iac/cli-share-results.ts, test/jest/acceptance/iac/cli-share-results.spec.ts
This PR adds support for passing project tags and attributes when invoking the `snyk iac test --report` command.
=> feat: Add support for IaC project tags and attributes

packages/snyk-protect/test/unit/fetch-patches.spec.ts
Fix broken patch test to unblock release pipeline
=> fix: skip broken patch test

test/jest/acceptance/iac/report.spec.ts
=> fix: iac report acceptence test

src/lib/iac/drift.ts
Revert of https://github.com/snyk/cli/pull/3034 since docker image support will be dropped
=> chore: remove useless comment

README.md
Also reworded some sentences for consistency.
=> docs: link to contributing from readme

package-lock.json, package.json
- Add support for objects and expiries in .snyk files during scan
- Update node version matrix
=> feat: unmanaged cpp support for expiry policy

package-lock.json, package.json, src/lib/plugins/sast/analysis.ts
Adds logging in debug mode to CLI to warn when files are skipped due to their size and lists which ones were skipped.
This is the CLI side where the debugging was added.
[Link to code-client side](https://github.com/snyk/code-client/pull/141)
**TODO**:
[NEBULA-481](https://snyksec.atlassian.net/browse/NEBULA-481)
=> feat: log files over size limit [NEBULA-481]

.circleci/config.yml
Test snyk-linux binary to ensure it works and keeps working.
Similar to #3068
=> chore(ci): test snyk-linux

package-lock.json, package.json, src/lib/polling/common.ts, src/lib/polling/types.ts
- propagate the target reference value from the `ScanResult` to the `ResolutionMeta`
=> fix: unmanaged target reference

.github/CODEOWNERS, .github/workflows/cliv2-dev.yml, cliv2/.gitignore, cliv2/Makefile, cliv2/cmd/cliv2/main.go, cliv2/cmd/make-cert/main.go, cliv2/go.mod, cliv2/go.sum, cliv2/internal/certs/certs.go, cliv2/internal/cliv2/cliv2.go, cliv2/internal/embedded/cliv1/cliv1.go, cliv2/internal/embedded/cliv1/embedded_binary_template.txt, cliv2/internal/embedded/extract.go, cliv2/internal/embedded/sha.go, cliv2/internal/proxy/proxy.go, cliv2/internal/proxy/proxy_test.go, cliv2/internal/utils/array.go, cliv2/internal/utils/cache-dir.go, cliv2/internal/utils/file.go, cliv2/internal/utils/temp-dir.go, cliv2/main_integration_test.go, cliv2/test/fixtures/.certs/make-ss-cert.sh, cliv2/test/fixtures/.certs/test-corp-proxy/v3.ext, cliv2/test/fixtures/npm-test-proj-no-vulns/package.json, cliv2/test/fixtures/npm-test-proj-with-vulns/package-lock.json, cliv2/test/fixtures/npm-test-proj-with-vulns/package.json, cliv2/test/testlib.go
Migrates our initial CLIv2 spike into the real Snyk CLI repo.
=> Migrate cliv2

package-lock.json, package.json
See https://github.com/snyk/snyk-mvn-plugin/pull/121
=> fix: add debug logs to snyk-mvn-plugin

cliv2/Makefile, cliv2/cmd/cliv2/main.go, cliv2/cmd/cliv2/main_test.go, cliv2/internal/cliv2/cliv2.go, cliv2/internal/cliv2/cliv2_test.go, cliv2/internal/utils/array.go, cliv2/scripts/issigned_darwin.sh, cliv2/scripts/issigned_windows.sh, cliv2/scripts/sign_darwin.sh, cliv2/scripts/sign_windows.sh
=> chore: sync cliv2

.circleci/config.yml
=> chore: add signing steps for cliv2 macOS and windows

src/lib/code-config.ts
=> chore: remove-path-from-url

cliv2/cmd/cliv2/main.go, cliv2/cmd/cliv2/main_test.go, cliv2/cmd/make-cert/main.go, cliv2/internal/certs/certs.go, cliv2/internal/proxy/proxy.go, cliv2/internal/proxy/proxy_test.go
=> chore: remove DNS names

cliv2/cmd/make-cert/main.go, cliv2/internal/certs/certs.go, cliv2/internal/proxy/proxy.go
Fix broken proxy test of CLI v2
=> chore: fix broken proxy test in cli v2

src/cli/commands/monitor/index.ts, src/lib/ecosystems/monitor.ts, src/lib/ecosystems/resolve-monitor-facts.ts, src/lib/polling/polling-monitor.ts
[TUN-189](https://snyksec.atlassian.net/browse/TUN-189?atlOrigin=eyJpIjoiNGE5NjQ2NTJmYjg4NDc0NGJhZWI5MmY0NDBmMDBiYTUiLCJwIjoiaiJ9) this adds contributor tracking for unmanaged monitoring.
=> fix: add tracking of contributors in unmanaged monitoring

package-lock.json, package.json
bump the version of snyk-mvn-plugin to introduce additional debug logging.
=> feat: bump snyk-mvn-plugin version

src/cli/commands/fix/validate-fix-command-is-supported.ts, src/lib/formatters/show-fix-tip.ts, test/acceptance/workspaces/pip-app-transitive-vuln/cli-output-actionable-remediation.txt, test/acceptance/workspaces/pip-app-transitive-vuln/cli-output.txt, test/jest/acceptance/snyk-fix/fix.spec.ts, test/jest/unit/lib/formatters/show-fix-tip.spec.ts, test/jest/unit/lib/formatters/test/__snapshots__/display-result.spec.ts.snap
=> fix: link to correct `snyk fix` docs

src/cli/commands/test/iac/index.ts
This PR removes some inactive code from the `iac test` command:
- Support for `snyk protect`, which has been deprecated in favour of `@snyk/protect` and is not relevant to the `iac test` command anyway.
- Support for detecting ecosystems, only relevant for the `code test` command.
- Argument validation for the `docker test` command, which is an alias for `container test`.
=> refactor: remove inactive code from iac test

package-lock.json, package.json
Bump version of snyk-gradle-plugin
Changes introduced with this release of the plugin:
- upgrade Node 8 to 16 and include tests for Node, JDK and Gradle versions
- lint README and config file
- update PR review template
=> feat: bump snyk-gradle-plugin version

package-lock.json, package.json
See https://github.com/snyk/snyk-gradle-plugin/pull/207
When we see multiple JSONDEPS lines, assume the first line was correct and do not throw an exception.
=> fix: gradle projects producing multiple jsondeps

package-lock.json, package.json
Upgrade `snyk-docker-plugin` to add support for scanning PHP (composer) applications inside containers.
with the code updated, running
`snyk container test --app-vulns snykgoof/os-app:php-simple`
will detect vulnerabilities in a PHP application
[MYC-83](https://snyksec.atlassian.net/browse/MYC-83)
=> feat: container php app scan

.circleci/config.yml, Makefile, release-scripts/make-binaries.sh, release-scripts/prepare-packages-for-release.sh
Also added a cleanup step so this target can be run and rolled back locally.
=> chore(ci): migrate prepack step to make

CONTRIBUTING.md
Extend CONTRIBUTING.md to include --runInBand
=> docs: Add --runInBand to jest execution

package-lock.json, package.json
adds the ability to send arguments to the "go list" command when testing go projects with "--" flag at the end
=> feat: add additinal arguments ability for go projects

src/lib/ecosystems/resolve-test-facts.ts, src/lib/package-managers.ts, src/lib/polling/polling-test.ts, src/lib/snyk-test/legacy.ts, test/jest/unit/lib/ecosystems/resolve-test-facts.spec.ts
Add support of snyk-to-html for snyk test --unmanaged --json
https://github.com/snyk/snyk-to-html/blob/master/README.md
Run the following commands in the folder of unmanaged project/repo:
- to create vulnerability test for unmanaged project/repo:
path_to_git/cli/bin/snyk test --json --unmanaged | path_to_git/snyk-to-html/dist/index.js -o result.json
- to build HTML report of received test resluts:
path_to_git/snyk-to-html/dist/index.js -i result.json -o result.html
[snyk code for snyk-to-html](https://www.notion.so/snyk/snyk-code-for-snyk-to-html-9231a0bd986e42fab61780eeca476998#8b1663e9273240a4aee23f72a272a2b4)
[Jira ticket TUN-27](https://snyksec.atlassian.net/browse/TUN-27)
=> feat: support for unmanaged snyk-to-html

cliv2/internal/proxy/proxy.go
Added and moved some logging for kerberos
=> chore: log token and proxy url

test/jest/acceptance/iac/experimental.spec.ts
A small fix for the --experimental acceptance test
=> fix: --experimental acceptance test

src/lib/formatters/iac-output/v2/share-results.ts, test/jest/unit/lib/formatters/iac-output/v2/share-results.spec.ts
=> fix: typo in IaC v2 --report output

package-lock.json, package.json
- Include improvements for EU environments
=> [NEBULA-635] chore: bump code-client version

src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/download.ts, test/jest/unit/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.spec.ts, test/jest/unit/lib/iac/test/v2/setup/local-cache/policy-engine/download.spec.ts
Refactors and simplifies how we return the expected checksum for a given file.
=> refactor: snyk-iac-test checksum

src/lib/plugins/sast/format/output-format.ts, test/fixtures/sast/test-output.txt
Fixes of the UI of CLI
Bold and lines indention 
Approved by Andy
Part of Code-Independent-day
https://snyksec.atlassian.net/browse/ZEN-236
https://snyksec.atlassian.net/browse/ZEN-235
=> fix: cli output adjustment

src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts
=> feat: bump snyk-iac-test version

package-lock.json, package.json
This PR bumps the version of snyk-sbt-plugin dependency to include recent changes to how comments are handled when checking for plugins in a project. The contents of single and multi-line comments will now be ignored by the plugin search.
=> feat: improve comment handling for SBT scans

CONTRIBUTING.md
Updates the contributing readme to add a bit more info around smoke tests
=> feat: update README

CONTRIBUTING.md
Mention conventional commits and swap word customer to user
=> Update contributing readme

package-lock.json, package.json
Upgrade docker plugin to improve stream parsing
=> fix: upgrade docker plugin to improve stream parsing

src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts
upgrade snyk iac test to 0.13.1
=> feat: upgrade snyk iac test to 0.13.1

src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/index.ts, src/lib/iac/test/v2/setup/local-cache/policy-engine/constants/utils.ts
- Updates the `snyk-iac-test` version to [`v0.15.0`](https://github.com/snyk/snyk-iac-test/releases/tag/v0.15.0)
=> chore: Update snyk-iac-test to v0.15.0

package-lock.json, package.json
Upgrade docker-registry-v2-client lib to support additional redirect status codes.
=> fix: upgrade docker-registry-v2-client lib

package-lock.json, package.json
Fix for container scan of images with RPM version >= 4.16.
=> fix: missing release in package version string

src/lib/iac/test/v2/output.ts, test/jest/unit/cli/commands/test/iac/v2/index.spec.ts
- Adds support for the exit code value `2`, when all scans fail.
- This PR is stacked on top of #3557, in which the response from `snyk-iac-test` is treated as a DTO and is mapped to an internal test output model for the CLI, in which the errors are of type `SnykIacTestError`.
- Please review the properties added for the new error and ensure they are identical to the ones from the original test flow.
- At the moment, we return an exit code value of 0 when any of the cases described above happen.
- According to the [Snyk CLI docs](https://docs.snyk.io/snyk-cli/cli-reference#subcommands-of-cli-commands), these cases should return an exit code value of 2 for all output formats.
- This is aligned with the existing code return in the local-execution flow, where we also return an exit code of …
=> chore: Added support for exit code `2`

test/smoke/spec/snyk_test_spec.sh
Re-enabled tests that have been disabled temporarily.
=> chore: re-enable test

test/smoke/spec/snyk_basic_spec.sh
This PR updates container help text in smoke test.
=> test: update container help text in smoke test

src/cli/commands/test/iac/local-execution/types.ts, src/lib/iac/test/v2/errors.ts, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Adds more IaC error codes
https://snyksec.atlassian.net/browse/CTX-373
=> [CTX-373] fix: more IaC error codes

package-lock.json, package.json
Bump `snyk-docker-plugin` version to add support for Python app scanning in containers.
https://snyksec.atlassian.net/browse/MYC-93
=> feat: container python app scan

src/cli/commands/test/iac/local-execution/types.ts, src/cli/commands/test/iac/v2/assert-iac-options.ts, src/cli/commands/test/iac/v2/index.ts, src/lib/iac/test/v2/scan/index.ts, src/lib/iac/test/v2/types.ts
feat: cloud context for IaC tests
Undocumented, and does nothing when not combined with `--experimental`.
Docs will be added when this moves out of experimental usage.
https://snyksec.atlassian.net/browse/CTX-58
=> [CTX-58] feat: cloud context for IaC tests

package-lock.json, package.json
Improves the performance issues that cause errors while scanning python apps in some images
=> fix: container python app scan performance issues

package-lock.json, package.json
upgrade danger from 10.7.1 to 10.9.0
=> chore: upgrade danger from 10.7.1 to 10.9.0

package-lock.json, package.json
Upgrade the snyk-docker-plugin.
See [snyk-docker-plugin #456](https://github.com/snyk/snyk-docker-plugin/pull/456) for more info.
=> fix: update snyk-docker-plugin to fix CGo binaries issue

src/lib/ecosystems/resolve-test-facts.ts
This PR fixes a bug where the looping of data doesn't check for an existing key.
TUN-390
=> fix: added check for existing key in loop

package-lock.json, package.json
Update the version of snyk-cpp-plugin, that improves performance of unmanaged ecosystems on Windows
=> fix: improve cpp-plugin performance on windows

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
bumps the version to include the new URL link
=> feat: new version to update url docs link [cfg-2167]

package-lock.json, package.json
Adds support for deleted files, so that we won't detect app files that were deleted as part of the image build steps.
https://snyksec.atlassian.net/browse/MYC-147
=> feat: container support for deleted files

package-lock.json, package.json
Bumping the version of snyk-gradle-plugin to 3.23.2
This version of the plugin includes refactoring, adding tests and adding @types/needle in devDeps, see the following PRs:
https://github.com/snyk/snyk-gradle-plugin/pull/233
https://github.com/snyk/snyk-gradle-plugin/pull/231
https://github.com/snyk/snyk-gradle-plugin/pull/230
https://github.com/snyk/snyk-gradle-plugin/pull/228
=> feat: refactor and add tests on gradle plugin

package-lock.json, packages/snyk-fix/package.json
Upgrades `snyk fix` Python fix packages to latest version that uses `@snyk/child-process` package without shell
=> fix: use @snyk/child-process package without shell

cliv2/scripts/sign_windows.sh, release-scripts/sign-windows-binary.sh
Affects Windows executable `snyk-win.exe`
=> Renew code signing certificate

src/lib/iac/test/v2/local-cache/rules-bundle/download.ts, src/lib/iac/test/v2/local-cache/rules-bundle/index.ts
Adds a debug log when pointing to a local bundle.
=> chore: Add debug log for local bundle

package-lock.json, package.json
Updates code-client to support latest changes in https://github.com/snyk/code-client/pull/161
=> feat: update code client

cliv2/go.mod, cliv2/go.sum
Upgraded all dependencies of the cliv2 golang project
=> chore: upgrade cliv2 deps

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
This PR upgrades snyk-iac-test to v0.33.1.
=> feat: Upgrade snyk-iac-test to v0.33.1

src/lib/ecosystems/resolve-test-facts.ts, src/lib/ecosystems/unmanaged/types.ts, src/lib/polling/polling-test.ts, test/jest/unit/lib/ecosystems/fixtures/get-dep-graph-response.ts, test/jest/unit/lib/ecosystems/resolve-test-facts.spec.ts
Make use of InProgress-field to decide if we are going to retry our unmanaged tasks.
=> feat: use in_progress to decide if unmanage-deps task has finished

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
This PR upgrades  snyk-iac-test to v0.33.3.
=> feat: Upgrade snyk-iac-test to v0.33.3

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
This PR upgrades snyk-iac-test to v0.33.5.
=> feat: Upgrade snyk-iac-test to v0.33.5

src/lib/snyk-test/run-test.ts, test/fixtures/print-graph-multiple-projects/proj1/package.json, test/fixtures/print-graph-multiple-projects/proj2/package.json, test/fixtures/print-graph-no-deps/package.json, test/jest/acceptance/print-graph.spec.ts
Prints the dep graph to stdout if you use `snyk test --print-graph`.
=> Print dep graph if --print-graph is used

src/lib/iac/drift/driftctl.ts
driftctl and terraform provider do not support trusting our certificate so we are (temporarly ?) reverting the proxy configuration before spawning them
Running `snyk iac describe --all` on a mac should work.
https://snyksec.atlassian.net/browse/HMMR-587
https://snyksec.atlassian.net/browse/HMMR-585
https://snyksec.atlassian.net/browse/INC-203
https://snyk.zendesk.com/agent/tickets/34682
=> restore system proxy for describe

src/lib/iac/drift/driftctl.ts
The release of this fix https://github.com/snyk/cli/pull/4158 didn't go through properly (assets weren't added) so am trying to trigger a new release with this commit.
=> fix: fixing typo to trigger a failed release

package-lock.json, package.json
Bump snyk-sbt-plugin version [2.15.1](https://github.com/snyk/snyk-sbt-plugin/compare/v2.15.0...v2.15.1)
Changes in the plugin:
- update docs: https://github.com/snyk/snyk-sbt-plugin/pull/108
- reduce Scala script output size: https://github.com/snyk/snyk-sbt-plugin/pull/111
=> fix: reduce scala script output size

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
This PR upgrades snyk-iac-test to v0.36.1.
=> feat: Upgrade snyk-iac-test to v0.36.1

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Upgrade snyk-iac-test to v0.36.2.
=> feat: Upgrade snyk-iac-test to v0.36.2

src/lib/ecosystems/resolve-test-facts.ts, src/lib/snyk-test/legacy.ts, test/jest/unit/lib/ecosystems/fixtures/expected-test-result-new-impl.ts, test/jest/unit/lib/ecosystems/resolve-test-facts.spec.ts
Add Test Support for IDE plugins for C/C++
https://docs.snyk.io/ide-tools
https://docs.snyk.io/ide-tools
[C++ Test Support for IDE plugins TUN-347](https://snyksec.atlassian.net/browse/TUN-347)
=> fix: support unmanaged for ide plugins

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
This PR bumps the snyk-iac-test binary.
=> chore: bump snyk-iac-test

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Upgrade snyk-iac-test to v0.36.5
=> feat: Upgrade snyk-iac-test to v0.36.5

cliv2/go.mod, cliv2/go.sum
update to a fixed version of the application framework, which uses the correct analytics endpoint again
=> chore: update version of application framework

package-lock.json, package.json
Includes the latest release of snyk-sbt-plugin v.2.16.3, which includes the following changes:
- fix for a bug when merging scopes together in the Scala script
- include scopes runtime and provided (in addition to previously used scope compile)
See: https://github.com/snyk/snyk-sbt-plugin/pull/121
=> fix: merge scopes in sbt projects

package-lock.json, package.json, src/cli/commands/test/iac/local-execution/yaml-parser.ts
Includes the fix in https://github.com/snyk/cloud-config-parser/pull/47
You would need a Linux VM to verify the fix. I've provided screenshots of both MacOS and Linux successfully running.
https://snyk.zendesk.com/agent/tickets/35401
=> fix: use JSON.parse to avoid OOM error

package-lock.json, package.json
Bumping snyk-sbt-plugin version to [2.17.0](https://github.com/snyk/snyk-sbt-plugin/releases/tag/v2.17.0). It includes changes:
- all tests to use jest framework (remove dependency on tap) https://github.com/snyk/snyk-sbt-plugin/pull/122
- use prettier for formatting and eslint for linting https://github.com/snyk/snyk-sbt-plugin/pull/123
- introduce linting rules and format all .ts files https://github.com/snyk/snyk-sbt-plugin/pull/124
=> chore: update formatting in sbt plugin

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, cliv2/internal/cliv2/cliv2.go, test/jest/acceptance/analytics.spec.ts, test/jest/acceptance/iac/cli-share-results.spec.ts, test/jest/acceptance/snyk-fix/fix.spec.ts, test/jest/acceptance/snyk-test/fail-on.spec.ts, test/jest/acceptance/snyk-test/missing-node-modules.spec.ts, test/jest/acceptance/snyk-test/snyk-test-local-policy-file.spec.ts
It integrates sbom as a local extension and improves the general application behaviour around extensions.
In addition some tests required adaption in the sense that they were expecting a certain order of messages being send which has now changed a bit. They have been either adapted to focus on certain messages or to avoid sending new messages.
As usual start in cmd/cliv2/main.go
snyk sbom --experimental
=> Integrate local sbom extension

cliv2/internal/cliv2/cliv2.go, cliv2/internal/cliv2/cliv2_test.go
[Jira task](https://snyksec.atlassian.net/browse/HMMR-594)
=> chore: clean old cliv1 versions in cache directory

package-lock.json, package.json, src/lib/detect.ts, src/lib/package-managers.ts, src/lib/plugins/index.ts, test/acceptance/workspaces/swift-app/Package.swift, test/fixtures/basic-swift/Package.swift, test/tap/cli-test.acceptance.test.ts, test/tap/cli-test/cli-test.swift.spec.ts
=> feat: add support for swiftpm plugin

package-lock.json, package.json
Update lib Snyk Docker Plugin, so we can use the new fact ImageNames.
=> RUN-1928 fix: upgrade snyk docker plugin

src/lib/ecosystems/resolve-test-facts.ts
This PR introduces new tracking analytics properties within the unmanaged test flow.
=> feat: add unmanaged analytics

.circleci/config.yml
Release golang CLI on linux.
[JIRA ticket](https://snyksec.atlassian.net/browse/HMMR-567)
=> chore: release golang cli on linux

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Upgrade snyk-iac-test to v0.37.2.
=> feat: Upgrade snyk-iac-test to v0.37.2

.circleci/config.yml
Release golang CLI on linux.
[JIRA ticket](https://snyksec.atlassian.net/browse/HMMR-567)
=> chore: release golang cli on linux and arm64

test/jest/acceptance/proxy-behavior.spec.ts
Increase timeout on proxy test.
=> chore: increase timeout on proxy test

src/cli/commands/monitor/index.ts
=> fix: add logic to ignore unsupporting package managers during snyk monitor

package-lock.json, package.json
- container python dist-packages support
- https://github.com/snyk/snyk-docker-plugin/pull/476
=> fix: container python dist-packages support

README.md
Update description on how to use gpg for verifying shasum signatures.
=> chore: update gpg section in readme

src/lib/find-files.ts, test/fixtures/find-files/.build/dependency/Package.swift, test/fixtures/find-files/swift/test.build/Package.swift, test/tap/find-files.test.ts
=> chore: ignore .build folder for swift

.github/CODEOWNERS
=> chore: change codeowners from hammer to hammerhead

test/tap/find-files.test.ts
=> fix: exclude .build folder

package-lock.json, package.json
- Increments `code-client` version
=> feat: allow .snyk file upload via code-client

.github/workflows/iac-smoke-tests-pulls.yml
This PR updates the code owners we check of in our smoke tests.
=> chore: update iac smoke tests

ts-binary-wrapper/src/common.ts
don't use randomInt() to generate a temp filename to ensure compatibility with 
* Node 12 < 12.19
* Node 14 < 14.10
=> feat: use date to create filename

.circleci/config.yml, .github/workflows/smoke-tests.yml, Makefile, test/smoke/docker-root/Dockerfile, test/smoke/docker-root/entrypoint.sh, test/smoke/run-shellspec-win.sh, test/smoke/spec/snyk_code_spec.sh, test/smoke/spec/snyk_monitor_spec.sh, test/smoke/spec/snyk_test_spec.sh, test/smoke/spec/spec_helper.sh, ts-binary-wrapper/bin/snyk, ts-binary-wrapper/package-lock.json, ts-binary-wrapper/package.json, ts-binary-wrapper/src/bootstrap.ts, ts-binary-wrapper/src/common.ts, ts-binary-wrapper/src/index.ts, ts-binary-wrapper/test/acceptance/basic.spec.ts, ts-binary-wrapper/test/unit/common.spec.ts
Release the Extensible CLI via NPM
=> feat: Release of the Extensible CLI via NPM

cliv2/go.mod, cliv2/go.sum, src/lib/ecosystems/resolve-test-facts.ts, src/lib/ecosystems/test.ts, src/lib/ecosystems/unmanaged/utils.ts, test/jest/unit/lib/ecosystems/common.spec.ts
Add support for the `snyk sbom --unmanaged` command.
The above command will enable customers to generate SBOMs for their unmanaged projects.
=> feat: unmanaged sbom support

.circleci/config.yml, release-scripts/validate-repository.sh
* Fix incorrect usage of `git -P tag --list --contains`
* Fix/improve check of S3 bucket
* !!!! TEMPORARILY REMOVE TESTS to unblock deployment !!!!
something like below
> make release-pre
> -- Validating repository
> Version v1.1104.0 LGTM!
> -- Validating artifacts
> /mnt/ramdisk/snyk/binary-releases /mnt/ramdisk/snyk
=> Fix: pre-release validation

.circleci/config.yml
This PR changes the test_and_release workflow like follows:
- tests are run on all branches excluding master
- releases are only run on master (as before)
have a look at the parts that filter:
```
filters:
branches:
ignore: master
```
We have also updated the settings in this github project, so that now:
- PRs must be synchronized with master before merging
- New commits cause new need to approve
- have a look at the CircleCI pipeline during this PR and later for the release after merge
Failing tests because of 3rd party dependencies were prohibiting releases.
=> chore: only and always run tests on pull request

.circleci/config.yml, cliv2/go.mod, cliv2/go.sum
Introduce a more graceful handling of unknown output mimetypes.
=> chore: support different output mime types more gracefully

cliv2/cmd/cliv2/main.go, cliv2/cmd/cliv2/main_test.go
With this an extension can be registered in a subtree, e.g. `snyk iac capture`. 
`main_test.go`
=> feat: support extensions with nested subcommands [HEAD-86]

.github/workflows/smoke-tests.yml, package-lock.json
Smoke test matrix was corrupt, that made it to pull the latest Node 18 as part of some tests.
The issue originated after we saw runner image update https://github.com/actions/runner-images/issues/7002
=> fix: smoke test matrix 

package-lock.json, package.json, src/lib/plugins/sast/analysis.ts, src/lib/plugins/sast/format/output-format.ts, src/lib/plugins/sast/index.ts, src/lib/plugins/sast/types.ts, test/fixtures/sast/sample-analyze-folders-with-report-and-ignores-response.json, test/jest/unit/snyk-code/snyk-code-test.spec.ts
- Adds the report upload/ignores feature to the CLI
- Adds tests for:
- reportResults in Code Test results
- ignored issues through `suppressions` in sarif
- [CLI Uploads Feature Plan](https://www.notion.so/snyk/Snyk-Code-Publish-CLI-results-to-the-web-UI-7b48a23e44634c60a5063d2eb8b6c528)
- [CLI Ignores Feature Plan](https://www.notion.so/snyk/Snyk-Code-CLI-Ignore-support-ae5eb72f6af940e087e801ade11154c9)
- [ZEN-494](https://snyksec.atlassian.net/browse/ZEN-494)
- Related [code-client PR](https://github.com/snyk/code-client/pull/170)
[ZEN-494]: https://snyksec.atlassian.net/browse/ZEN-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add report upload to code test [ZEN-494]

src/cli/commands/woof/getWoof.ts, test/jest/unit/woof.spec.ts
Respects German puppies.
In "Files changed" tab.
Run `snyk woof --language=de`
=> feat: add missing language representation

cliv2/pkg/basic_workflows/legacycli.go
Remove additional debug argument
=> fix: remove additional debug parameter [HEAD-155]

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/extra-certs.spec.ts, test/jest/acceptance/snyk-config/snyk-config.spec.ts
This upgrades the SBOM CLI extension. New additions are:
* correct MIME-types on returned `Data` payloads
* `--format` argument is now mandatory
=> chore: upgrade SBOM CLI extension

ts-binary-wrapper/.snyk
Ignore issues that reference the Snyk CLI
=> chore: add ignore for self referenced issues

cliv2/go.mod, cliv2/go.sum
Upgrade application framework to fix the lookup of orgs by slugname
=> fix: org slugname lookup

package-lock.json, package.json
Bump Snyk docker plugin to 6.0.0 as a part of RedHat support.
[Jira ticket](https://snyksec.atlassian.net/browse/LUM-123)
=> feat: bump Snyk docker plugin to 6.0.0

.circleci/config.yml
Persist version file to fix incorrect version number display
=> fix: persist version file

package-lock.json, package.json
snyk-cpp-plugin 2.22.0 version is able to display licenses issues along with vuln issues.
https://github.com/snyk/snyk-cpp-plugin/pull/100
=> feat: bump snyk cpp plugin to 2.22.0

cliv2/go.mod, cliv2/go.sum
bump snyk-iac-capture to 0.6.0
- [CTX-470](https://snyksec.atlassian.net/browse/CTX-470)
- [CTX-531](https://snyksec.atlassian.net/browse/CTX-531)
[CTX-470]: https://snyksec.atlassian.net/browse/CTX-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CTX-531]: https://snyksec.atlassian.net/browse/CTX-531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: bump snyk-iac-capture to 0.6.0

ts-binary-wrapper/src/common.ts
Uses stdErr for logging so it does not conflict with the CLI using stdOut
=> fix: revert to using console.error for debug messages

cliv2/go.mod, cliv2/go.sum, test/jest/util/isCLIV2.ts
Legacy CLI and Extensible CLI read configuration from the same configuration sources but may process and use these values differently. For example the canonical API URL that is derived from the user input might look differently.
This PR updates the application framework to ensure that authentication header are used correctly.
=> chore: ensure adding authentication headers to the correct requests

package-lock.json, package.json
Update the gradle plugin. This adds a fix to prevent the Snyk gradle tasks to run twice when other tasks change a configuration.
=> fix: update gradle plugin

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, cliv2/pkg/basic_workflows/legacycli.go
Use central configuration to disable oauth authentication support and all related changes. Default is disabled.
=> chore: disable oauth support globally

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum
Improve debug logging around authorization usage by using the active authenticator.
=> chore: improve auth debug logging

package-lock.json, package.json
This PR updates the snyk-gradle-plugin dependency
=> chore: updates snyk-gradle-plugin [HEAD-218]

package-lock.json, package.json
The update fixes an issue within the snyk-go-plugin that resulted in a changed Proxy environment.
=> feat: update snyk-go-plugin 1.19.5

CONTRIBUTING.md
Add basic instructions on how to build the Extensible CLI
=> docs: update basic build instructions.

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Upgrade snyk-iac-test to v0.43.1.
=> fix: Upgrade snyk-iac-test to v0.43.1 [CFG-2370]

package-lock.json, package.json
See https://github.com/snyk/snyk-gradle-plugin/pull/260
=> fix: gradle normalize deps transitives

package-lock.json, package.json
Bumps snyk-cpp-plugin to fix an unmanaged-cpp bug.
Please see https://github.com/snyk/snyk-cpp-plugin/pull/106.
=> fix: support tar files-only projects

src/lib/plugins/sast/analysis.ts, src/lib/plugins/sast/format/output-format.ts, src/lib/plugins/sast/index.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts
Including suppressions (ignored rules) in SARIF outputs (`--sarif` and `--sarif-file-output`).
`snyk code test --report --project-name=<PROJECT_NAME> --sarif`
[ZEN-577](https://snyksec.atlassian.net/browse/ZEN-577)
[ZEN-577]: https://snyksec.atlassian.net/browse/ZEN-577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: include suppressions in sarif output

src/lib/plugins/sast/format/output-format.ts, src/lib/plugins/sast/index.ts, src/lib/plugins/sast/utils/filter.ts, src/lib/plugins/sast/utils/index.ts, test/fixtures/sast/sample-analyze-folders-with-report-and-ignores-only-response.json, test/jest/unit/snyk-code/snyk-code-test.spec.ts
Fix handling of Code ignored issues (suppressions).
When all found issues are suppressed, the exit code should be 0 (success).
Look at first commit for the relevant business logic changes.
The second (chore) commit is just an optimisation to run stringification only once, but does not affect functionality.
The third (refactor) commit is adding types and moving the ignored issue filtering function, it also does not affect functionality.
1. Run a test with `--report` and `--project-name` flags.  
`snyk code test --report --project-name="test-project"`
For any issues found, the CLI should exit with code 1.
2. Go to the project and ignore all found issues. Run the CLI command again.
This time, as all found issues are ignored, the CLI should exit with code 0.
- …
=> fix: handle suppressed issues (no fail when only ignored issues are returned)

package-lock.json, package.json
Integrates [the following change](https://github.com/snyk/code-client/pull/184) to be case-insensitive for file extension filtering when running Code scans.
=> chore: bump code-client version to latest [ZEN-371]

.circleci/config.yml, Makefile
This PR splits the final release steps in the CICD so that we have release jobs for each platform
=> feat: split release workflow

release-scripts/upload-artifacts.sh
This PR should fix publishing to the `latest` folder in S3
=> fix: publish to latest in S3

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts
Upgrade snyk-iac-test to 0.45.0.
=> Upgrade snyk-iac-test to 0.45.0

cliv2/go.mod, cliv2/go.sum
Incorporates a few recent extension changes: 
- https://github.com/snyk/cli-extension-iac-rules/pull/32
- https://github.com/snyk/cli-extension-iac-rules/pull/33
- https://github.com/snyk/cli-extension-iac-rules/pull/34
=> [CTX-600] [CTX-604] [CTX-606] feat: bump cloud custom rules extension

package-lock.json, package.json
The SwiftPM plugin [needed to pass some proxy vars](https://github.com/snyk/snyk-swiftpm-plugin/pull/29) due to the extensible CLI wrapper stuff.
=> fix: bump SwiftPM

cliv2/go.mod, cliv2/go.sum, cliv2/internal/cliv2/cliv2.go, cliv2/internal/proxy/proxy.go, cliv2/internal/utils/directories.go
=> chore: change cache directory to avoid collision [HEAD-341]

package-lock.json, package.json
See https://github.com/snyk/snyk-sbt-plugin/pull/133
=> fix: parse sbt console output

package-lock.json, package.json
Adds https://github.com/snyk/snyk-python-plugin/pull/210
=> fix: broken pkg-resources in some python projects

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts, src/lib/iac/test/v2/scan/index.ts
These logs weren't showing up when `-d` was passed. Also bump snyk-iac-test.
https://snyksec.atlassian.net/browse/CTX-608
=> [CTX-608] fix: iac-test debug namespaces

cliv2/Makefile, cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum
* Ingest the OS at build time and use this value in Analytics and User-Agent
* Set Command in Analytics, instead of deriving it from args
* Makefile for ingest of OS value
* main.go usage of values
=> feat: set OS and command explicitly

cliv2/go.mod, cliv2/go.sum
… through updating the application framework
=> fix: remove now obsolete process name from user-agent

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Update to the `snyk-iac-test` version we are using for Integrated IaC
=> feat: new snyk-iac-test version

package-lock.json, package.json
Bump related to https://github.com/snyk/gradle-plugin/pull/24
=> feat: bump gradle-plugin

.gitleaksignore, package-lock.json, package.json
Contains an important fix for Debian source package lookups.
=> fix: bump snyk-docker-plugin

package-lock.json
- fix: bump snyk-docker-pull
[SUP-1641]
[SUP-1641]: https://snyksec.atlassian.net/browse/SUP-1641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: bump snyk-docker-pull

Makefile
determine the python command to use in the main Makefile
For testing, run `make build` it should result in a cli binary that can be executed normally.
=> chore: auto select python version

.circleci/Dockerfile, .circleci/config.yml, .github/workflows/create-build-image.yml, scripts/create-build-image.sh
[The previous PR](https://github.com/snyk/cli/pull/4768) got auto-merged, sorry about that. Had one final ting to address in it.
=> fix [OSM-515] Refactor `dotnet` CLI installation to build image Dockerfile

cliv2/go.mod, cliv2/go.sum
For future use of oauth, update the token urls, through updating GAF
=> chore: update oauth urls

package-lock.json, package.json, test/jest/acceptance/https.spec.ts
=> chore: bump needle

.circleci/config.yml
Remove usage of circleci win orb and pin all windows executors to fix versions.
=> chore: pin version of all windows executors

.github/workflows/smoke-tests.yml, .github/workflows/snyk-protect-production-smoke-tests.yml, package-lock.json, package.json, src/cli/runtime.ts, test/jest/unit/runtime.spec.ts
This PR updates Nodejs version from 12 to 14.
- https://github.com/snyk/cli/pull/1042
- https://github.com/snyk/cli/pull/1639
HEAD-496
=> chore: drop Node 12 support

.circleci/config.yml, Makefile, cliv2/go.mod, cliv2/go.sum, release-scripts/release-fips.json, release-scripts/release.json.sh, release-scripts/sha256sums.txt.asc.sh, release-scripts/upload-artifacts.sh, release-scripts/validate-checksums.sh, scripts/install-snyk.py
* Deploy FIPS enabled CLI binaries to static.snyk.io
* Add e2e test for FIPS binaries
* Improve e2e tests by running whoami command
* .circleci/config.yml
* Makefile
* Download deployed binaries from static.snyk.io/fips/cli/...
=> feat: Deploy FIPS enabled binaries for Linux and Windows

.circleci/config.yml
Store signed artificats in circleci
=> chore: storing artifacts after signing

cliv2/go.mod, cliv2/go.sum
This PR update GAF version
https://github.com/snyk/go-application-framework/pull/87
HEAD-562
=> chore: update GAF version [HEAD-562]

package-lock.json, package.json
Bumps snyk-docker-plugin to v6.5.7
See: https://github.com/snyk/snyk-docker-plugin/commit/f8c4894a40559216e551a472de059e07150cefe4
=> chore: bumps sdp to v6.5.7

CONTRIBUTING.md
Mentioning `--experimental` for beta features in the CONTRIBUTING.md
=> docs: adding info for beta features

package-lock.json, package.json, test/jest/acceptance/snyk-test/all-projects.spec.ts, test/tap/cli-monitor.acceptance.test.ts, test/tap/cli-monitor/cli-monitor.all-projects.spec.ts
See https://github.com/snyk/snyk-mvn-plugin/pull/154
=> feat: snyk-mvn-plugin to use Snyk dep-graph

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Upgrade snyk-iac-test to v0.48.3.
=> feat: upgrade snyk-iac-test to v0.48.3

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, cliv2/internal/cliv2/cliv2.go, cliv2/pkg/basic_workflows/legacycli.go
Prepare to implement LS as a CLI Extension.
* Fix missing output handling in the legacy CLI
* Introduce optional working directory config parameter in the legacy CLI
* Adapt output mime type depending on parameter
=> chore: prepare language server extension

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Upgrade snyk-iac-test to v0.48.4.
=> feat: upgrade snyk-iac-test to v0.48.4

.circleci/config.yml
Try to set timezone to fix e2e test
=> fix: set timezone explicitly

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum
This PR enables license data from LS to be shown
=> feat: HEAD-685 inject ls license data

package-lock.json, package.json, src/lib/polling/polling-test.ts, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
By updating to latest unmanaged-deps API version, we allow user to list package URL with print-deps.
This also requires us to update to the latest snyk-cpp-plugin, which also enables us to list the package URL in the human readable format.
We have also included a commit, to set endpoints to latest GA. This is just in case we need to rollback by doing a `git revert`.
Make sure the package URL (aka purl) is listed in the output for following two commands:
- `snyk test --unmanaged --json`
- `snyk test --unmanaged --print-deps`
Example human readable:
```
Dependencies:
https://curl.se|curl@7.29.0
purl: pkg:generic/curl@7.29.0?download_url=https:%2F%2Fcurl.se%2Fdownload%2Farcheology%2Fcurl-7.29.0.tar.gz
confidence: 1.000
https://github.com|nih-at/libzip@1.8.0
purl: …
```
=> feat: stage unmanaged depgraph-endpoints

Makefile, package-lock.json, package.json, test/jest/acceptance/language-server-extension.spec.ts, test/setup.js
This tests the successful embedding of language server as extension into the CLI binary. It is not a complete check, but a sanity check using Snyk Open Source scans and their reported diagnostics.
Tests: 
- display licenses
- display version
- run and wait for diagnostics
=> feat: add acceptance test for running language server integrated in CLI [HEAD-687]

cliv2/cmd/cliv2/main.go
Add Integration and Integration Environment Information to the debug logs.
run
```
SNYK_INTEGRATION_NAME=world SNYK_INTEGRATION_VERSION=4.5.6 SNYK_INTEGRATION_ENVIRONMENT=hello SNYK_INTEGRATION_ENVIRONMENT_VERSION=1.2.3 snyk -d
```
```
2023-09-08T16:43:41Z main - Version:               1.1213.0
2023-09-08T16:43:41Z main - Platform:              darwin arm64  world/4.5.6  hello/1.2.3
2023-09-08T16:43:41Z main - API:                   https://api.snyk.io
```
=> chore: extend platform with environment info

package-lock.json
Bumping `@snyk/code-client` from 4.19.1 to 4.21.0.
Updated version contains several bug fixes, including a fix for `.snyk` exclude rule handling.
See https://github.com/snyk/code-client/pull/200 for context.
Run `snyk code test [-d]` in a directory with `.snyk` exclude rules, and a nested `.gitignore` file with negative ignore pattern for a path under the `.snyk` exclude rule(s).
E.g.
```
/ .snyk - defining exclude for "/node-modules"
| node_modules/
|- .gitignore - defining negative pattern for "!/test"
|- test/
|-- index.js - containing vulns
```
The `node_modules/test/index.js` file should not surface any issues.
https://github.com/snyk/code-client/pull/200
https://snyksec.atlassian.net/browse/ZEN-588
=> fix: update @snyk/code-client to 4.21.0

cliv2/go.mod, cliv2/go.sum
Bump `container-cli` extension version (some bug fixes to the extension workflows).
=> feat: bump `container-cli` extension version

package-lock.json
Fixing an unwanted side effect when having a proxy specified and testing python projects.
HEAD-820
=> fix: changing global proxy setting as a side effect when testing python projects

.circleci/config.yml, cliv2/scripts/sign_windows.ps1
Renew Code Signing Certificate
=> feat: renew windows code signing certificate

docker/Dockerfile.docker, docker/Dockerfile.gradle-2.8, docker/Dockerfile.gradle-4.4, docker/Dockerfile.gradle-5.4, docker/Dockerfile.gradle-5.4_java11, docker/Dockerfile.maven-3.5.4, docker/Dockerfile.maven-3.6.3, docker/Dockerfile.maven-3.6.3_java11, docker/Dockerfile.npm_ruby, docker/Dockerfile.python-2, docker/Dockerfile.python-3, docker/Dockerfile.python-3.6, docker/Dockerfile.python-3.8, docker/Dockerfile.python-3.9, docker/Dockerfile.sbt-0.13.16, docker/Dockerfile.sbt-1.0.4, docker/README.md, docker/docker-entrypoint.sh, docker/docker-python-entrypoint.sh
This reverts commit 48da04e3e22eb5601f3cb62f001aa85602a7f408.
This PR reverts the commit to remove the deprecated docker images, reasoning given in linked ticket
HEAD-842
=> revert: remove Dockerfiles for deprecated images (#4762)

package-lock.json, package.json
Same as https://github.com/snyk/cli/pull/4869, found a small bug. Acceptance tests still covers all.
=> fix: bumped `snyk-nuget-plugin`

.circleci/config.yml
This reverts commit b25f3a941ebe5babca5e5925640748dbd369f93a.
Temporary revert changing macos runners to fix some tests
=> revert: replace deprecated macos circleci runner [HEAD-781] (#4884)

.circleci/config.yml, Makefile, binary-deployments.json, cliv2/Makefile, release-scripts/release.json, release-scripts/release.json.sh, release-scripts/upload-artifacts.sh, scripts/install-snyk.py, ts-binary-wrapper/test/acceptance/basic.spec.ts, ts-binary-wrapper/test/unit/common.spec.ts
In addition to amd64 binaries this PR introduces arm64 binaries for MacOS.
HEAD-204
=> feat: add MacOS arm64 binaries [HEAD-204]

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Upgrade snyk-iac-test to v0.50.0.
=> feat: upgrade snyk-iac-test to v0.50.0 [IAC-2637]

release-scripts/release.json
=> fix: remove space in release json

cliv2/go.mod, cliv2/go.sum
Update GAF to temporarily add Session-Token Header
=> feat: temporarily add legacy Session-Token [HEAD-884]

cliv2/go.mod, cliv2/go.sum
=> fix: update snyk-ls to v0.0.0-20231018080541-3a486664f5ac [HEAD-779]

Makefile
=> fix: increase memory limit for node [HEAD-893]

package-lock.json, package.json, test/acceptance/workspaces/nuget-app-6-no-rid/.gitignore, test/acceptance/workspaces/nuget-app-6-no-rid/dotnet_6.csproj, test/acceptance/workspaces/nuget-app-6-no-rid/obj/project.assets.json, test/acceptance/workspaces/nuget-app-6-no-rid/program.cs, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
Bump of https://github.com/snyk/snyk-nuget-plugin/pull/192
=> fix :[SUP-2193] Fix `v2` .net parsing not honoring missing `rid`s.

package-lock.json, package.json, src/lib/plugins/sast/errors/code-client-error.ts, src/lib/plugins/sast/errors/index.ts, src/lib/plugins/sast/index.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts
- Implements error handling and user messaging for code client errors containing error details
- Updates code-client package
=> feat: add code client detail error [NEBULA-1511]

cliv2/go.mod, cliv2/go.sum
Update dependencies:
* goproxy
* grpc
=> fix: update dependencies goproxy and grpc

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
=> [CLOUD-1829] fix: bump snyk-iac-test

package-lock.json, package.json, test/jest/acceptance/snyk-sbom/gradle-options.spec.ts
Updates the Gradle plugin to solve a regression bug causing ignores in the UI to not be reflected in `snyk test` for certain Gradle projects.
Long read here: https://github.com/snyk/snyk-gradle-plugin/pull/266
=> feat: [SUP-2164] bump gradle-plugin

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/https.spec.ts
=> feat: use global runtime information [LINK-881]

cliv2/go.mod, cliv2/go.sum
Please see below for the description
- **Testing**
When adding a …
=> chore: update gaf to 9719383

package-lock.json, package.json
=> fix: bumping nuget plugin

cliv2/go.mod, cliv2/go.sum
=> feat: Update Snyk LS dep [HEAD-1063]

cliv2/go.mod, cliv2/go.sum, test/acceptance/fake-server.ts, test/jest/acceptance/snyk-sbom/sbom.spec.ts
- **Testing**
This upgrades the `snyk/cli-extension-sbom` to include a `tool` entry for the Snyk CLI in generated SBOM documents.
=> feat: include Snyk CLI as a generator tool in SBOM documents

package-lock.json, package.json, test/acceptance/workspaces/npm-package-with-overrides/package-lock.json, test/acceptance/workspaces/npm-package-with-overrides/package.json, test/tap/cli-test/cli-test.npm.spec.ts
=> fix: bump nodejs-parser to 1.52.8

package-lock.json, package.json, test/tap/proxy.test.js
- Downgrade of needle 3.2.0 to 3.0.0 -> low (https://github.com/tomas/needle/releases)
- Upgrade of code-client to downgrade needle -> low (https://github.com/snyk/code-client/releases)
- 
For Node projects: It’s important to make sure changes in `package.json` are also affecting …
=> fix: downgrade needle for CONNECT mode proxy support

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Upgrade snyk-iac-test to v0.50.4.
=> feat: upgrade snyk-iac-test to v0.50.4

package-lock.json, package.json, test/acceptance/workspaces/pip-app-python-3.12/requirements.txt
=> fix: [OSM-855] fixed python 3.12 support in snyk-python-plugin

package-lock.json, package.json, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
=> fix: bump snyk python plugin

test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
=> test: temporarily skip failing tests

package-lock.json, package.json
=> feat: update gradle plugin version

package-lock.json, package.json
=> fix: ignore php composer lockfiles that are invalid

.circleci/config.yml, test/smoke/spec/snyk_monitor_spec.sh, test/smoke/spec/spec_helper.sh
Persist SNYK_API value in CircleCI to enable configuring this value later.
=> chore: persist SNYK_API in CCI config

dangerfile.js
Clean up of unused danger message.
=> chore: remove redundant msg. Tests are run on every PR

package-lock.json, package.json
=> fix: bump snyk-python-plugin version

CONTRIBUTING.md
=> docs: add command to run acceptance tests

src/cli/main.ts, test/acceptance/workspaces/golang-gomodules/main.go, test/jest/acceptance/cli-json-file-output.spec.ts
=> fix: Do not write an empty file when using --json-file-output [CLI-115]

package-lock.json, package.json, test/acceptance/workspaces/nuget-app-8-custom-output-path/.gitignore, test/acceptance/workspaces/nuget-app-8-custom-output-path/Directory.Build.props, test/acceptance/workspaces/nuget-app-8-custom-output-path/Program.cs, test/acceptance/workspaces/nuget-app-8-custom-output-path/program.csproj, test/acceptance/workspaces/nuget-app-8-custom-output-path/random-output/company/obj/project.assets.json, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
=> feat: [OSM-955] Support for custom output paths for dotnet `v2` projects

test/jest/acceptance/woof.spec.ts, test/smoke/spec/snyk_basic_spec.sh
=> test: move woof coverage to jest

.github/workflows/synchronize-readme.yml
=> chore: fix path for prettier command in synchronize-readme workflow

Makefile
=> fix: increase max allocatable heap memory to 32GB

scripts/create-build-image.sh
=> docs: introduce comments to create-build-script

release-scripts/validate-repository.sh
=> chore: improve release gate based on version number

.circleci/config.yml, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md, dangerfile.js, packages/cli-alert/src/index.ts, src/lib/protect-update-notification.ts
=> chore: Rename occurrences of master to main

.github/workflows/check-dependencies.yml, .github/workflows/danger-zone.yml
=> chore: Adapt github actions to consider main

catalog-info.yaml
=> chore: update ownership for catalog info

CONTRIBUTING.md
=> docs: update acceptance test doc

package-lock.json, package.json
=> fix: [OSM-998] Scanning of .NET projects with the `--dotnet-runtime-resolution` flag now uses existing NuGet package cache if available

.github/workflows/iac-smoke-tests-pulls.yml
=> chore: update remaining reference to master branch

release-scripts/validate-repository.sh
=> chore: Improve release sanity check messages 

dangerfile.js
=> fix(#2138): commit pattern in danger to disable certain characters

package-lock.json, package.json
=> fix: remove dependencies when parent folder is deleted

CONTRIBUTING.md
=> docs: add guidance on writing commit messages

package-lock.json, package.json
=> feat: Feature - add python optional dependencies/extras support

test/jest/acceptance/snyk-apps/config.spec.ts
=> test: group app tests under common folder

.circleci/config.yml
- feat: upload legacy tap test results to circle
- feat: run tap tests in parallel
=> chore: run tap tests in parallel

.circleci/config.yml, release-scripts/determine-release-channel.sh, release-scripts/enable-stable-release-channels.sh, release-scripts/skip-deployment.sh, release-scripts/upload-artifacts.sh
=> chore: Add support for additional deployment channels

.github/workflows/danger-zone.yml, dangerfile.js
A first pass at validating the PR title using Danger. 
* It will re-evaluate when PR is edited.
=> chore: enforce pr title formatting

package-lock.json, package.json
=> fix: add support for dev/alpha/beta/rc python versions

.circleci/config.yml
=> fix(ci): End to end test by updating to a newer test image

.github/workflows/synchronize-readme.yml
=> chore: disable readme sync workflow schedule

.gitignore, CONTRIBUTING.md, scripts/Brewfile, scripts/install-dev-dependencies.sh
=> chore: add a simple script to install dev tools

.github/workflows/iac-cli-alert.yml, package-lock.json, packages/iac-cli-alert/package.json
=> chore(deps): upgrade slack webhook

cliv2/go.mod, cliv2/go.sum
- **Testing**
All pull requests must undergo a thorough review process before being merged.
The review process of the code PR should include code review, testing, and any necessary feedback or revisions.
Pull request reviews of functionality developed in other teams only review the given documentation and test reports.
****************************If a dependency is not necessary, don’t add it.**************************** …
=> chore: support feature flags for snyk code test

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/snyk-sbom/sbom.spec.ts
=> fix: Fix error in sbom command when using --json-file-output

.prettierignore
=> chore: ignore tap files when formatting

src/lib/request/request.ts
Low - minor change to a debug log message
- **Testing** …
=> fix: avoid outputting potentially very large JSON objects

CONTRIBUTING.md
=> docs: mention how to test against a binary

.gitignore
=> chore: ignore go sum

src/lib/formatters/iac-output/text/formatters.ts, src/lib/iac/test/v2/json.ts, test/jest/unit/iac/process-results/fixtures/integrated-json-output.json, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-text-output-data-with-suppressions.json, test/jest/unit/iac/process-results/fixtures/snyk-iac-test-text-output-data.json
=> fix(iac): Fix Issue Path in human readable and json output [IAC-2935]

test/jest/acceptance/snyk-sbom/pip-options.spec.ts
=> test: install pip deps during setup

cliv2/cmd/cliv2/main.go, cliv2/cmd/cliv2/main_test.go, cliv2/internal/cliv2/cliv2.go
=> fix: return error as pointer

dangerfile.js
=> chore(ci): extend commit pattern to allow more complex scope

jest.config.js, test/jest/acceptance/extra-certs.spec.ts
=> chore(ci): increase timeouts to reduce flakiness

src/cli/commands/woof.ts, src/cli/commands/woof/getWoof.ts, test/jest/acceptance/woof.spec.ts
=> feat: snyk woof ro language support and tests

Makefile
=> fix(ci): adapt script to work on different environments

release-scripts/prepare-release.sh
=> fix(ci): remove failing checks and simplify prepare release

.circleci/config.yml
=> fix(ci): add deployment steps to release branches

.circleci/config.yml
=> fix(ci): Fix build pipeline for release branches [CLI-287]

.github/workflows/check-dependencies.yml, .github/workflows/cli-alert.yml, .github/workflows/danger-zone.yml, .github/workflows/iac-cli-alert.yml, .github/workflows/iac-smoke-tests.yml, .github/workflows/smoke-tests.yml, .github/workflows/snyk-protect-production-smoke-tests.yml
=> fix(ci): Remove node 14 from github actions and add node 20 for testing

.github/workflows/danger-zone.yml
=> chore(ci): cover release-candidate branch with danger

package-lock.json, package.json
=> hotfix: dverbose cyclic dependencies support

package-lock.json, package.json
=> fix: support cyclic dependencies in maven with dverbose

Makefile, check-dependencies.config.ts, release-scripts/conventional-changelog-cli-config.js, release-scripts/prepare-release.sh
=> chore(ci): improve release notes generation

.circleci/config.yml, Makefile, release-scripts/next-version.sh, release-scripts/upload-artifacts.sh
=> chore(ci): Upload release notes to static.snyk.io

.circleci/config.yml
Low - No code changes
- **Testing** …
=> chore(ci): fix sending snyk scan report to organisation

cliv2/go.mod, cliv2/go.sum
=> fix(ls): caching problem when no vulnerabilities in the IDE

package-lock.json, package.json, test/jest/acceptance/snyk-container/container.spec.ts
=> fix(sbom): Fix container purl generation for apt and rpm

src/lib/project-metadata/target-builders/git.ts, src/lib/snyk-test/run-test.ts
Low - only debug logs added
- **Testing** …
=> chore(logs): add extra debug logging for target info

Makefile, release-scripts/prepare-release.sh
=> fix: remove dependency for release notes

dangerfile.js
=> fix: allow Merge commits

cliv2/go.mod, cliv2/go.sum
=> fix(utils): do not parse invalid ignore files (CLI-321)

.snyk
Our direct usage of this package is not using a vulnerable method.
We are using the isMatch function which does not make use of the underlying braces pkg, which is where the vulnerability has been reported.
https://github.com/micromatch/micromatch/blob/2c56a8604b68c1099e7bc0f807ce0865a339747a/index.js#L106-L123
- **Testing**
Manual testing will not be performed by the …
=> chore(security): ignore SNYK-JS-BRACES-6838727

cliv2/cmd/cliv2/main.go, cliv2/cmd/cliv2/main_test.go, cliv2/go.mod, cliv2/go.sum
=> feat(code): Add central enabled check

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, test/smoke/spec/snyk_auth_spec.sh
=> feat(auth): Make OAuth the default authentication mechanism

test/jest/unit/cli/commands/monitor/project-attributes.spec.ts
=> test: refactor to unit

cliv2/cmd/cliv2/logheader.go, cliv2/cmd/cliv2/main.go, cliv2/cmd/cliv2/main_test.go, cliv2/go.mod, cliv2/go.sum
=> feat(instrumentation): integrate instrumentation collector 

cliv2/go.mod, cliv2/go.sum
=> fix: sbom test output padding

binary-releases/RELEASE_NOTES.md
=> docs: adapt release notes

cliv2/go.mod, cliv2/go.sum
- **Testing**
- bumps LS to the latest release version
[releases since last update](https://github.com/snyk/snyk-ls/compare/v20240510.143016...v20240521.134551)
Link above with the comparison.
Build and launch VSCode.
=> feat(language-server): add `--all-projects` flag scans by default [IDE-318]

src/lib/errors/no-supported-sast-files-found.ts
=> docs: update no-supported-sast-files-found.ts

cliv2/cmd/cliv2/main_test.go
=> test: refactor to use assert.NoError

cliv2/cmd/cliv2/instrumentation.go, cliv2/cmd/cliv2/instrumentation_test.go, cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum
=> fix(instrumentation): Send transformed v1 data from IDEs

release-scripts/write-ls-protocol-version.go
Instead of fetching the goreleaser config from github in release scripts, get it from the local Go module cache. The snyk-ls package at the git commit version has already been downloaded to the cache during a build during Go CLI compilation.
- **Testing**
For …
=> chore: extract snyk-ls protocol version from go mod cache

.github/workflows/iac-smoke-tests-pulls.yml
=> Bump tj-actions/changed-files version to latest

cliv2/go.mod, cliv2/go.sum
=> feat(language-server): update ls for analytics usagev2

cliv2/go.mod, cliv2/go.sum
=> fix(instrumentation): use cli runtime info when translating v1 data

cliv2/go.mod, cliv2/go.sum
- **Testing**
- updates LS to the latest released version incl. a bump of the protocol version to force LS/CLI updates when we release ignores & instrumentation functionality in the IDE plugins.
Risk: LOW
https://github.com/snyk/snyk-ls/releases/tag/v20240611.145743
=> feat(language-server): increase protocol version to 12 [IDE-376]

cliv2/go.mod, cliv2/go.sum
This version of Language Server refactors the layout of fixed code examples for Code Issue by replacing the tab-based navigation with arrow-based navigation. It also includes several styling and script improvements.
- Removed the Community Examples tab layout.
- Implemented arrow-based navigation for fixed code examples.
- Reorganised constants, variables, and functions.
- Moved DOM-dependent functions inside `DOMContentLoaded`.
This functionality belong to the Code Issue panel rendered from LSP and it's behind a feature flag.
https://snyksec.atlassian.net/browse/IDE-294
---
- **Testing**
The …
=> refactor(language-server): replace tab-based with arrow-based navigation

Makefile
=> chore: ensure that RELEASE_NOTES dependencies are installed

cliv2/go.mod, cliv2/go.sum
=> fix: only log when endpoint not available

binary-releases/RELEASE_NOTES.md
=> chore: update release notes

cliv2/cmd/cliv2/main.go, cliv2/internal/cliv2/cliv2.go, cliv2/internal/cliv2/cliv2_test.go, cliv2/internal/utils/directories.go, cliv2/pkg/basic_workflows/legacycli.go
=> fix(language-server): Fix race conditions when using internal proxy concurrently

Makefile, cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, cliv2/internal/cliv2/cliv2.go, cliv2/internal/cliv2/cliv2_test.go, cliv2/internal/utils/directories.go, cliv2/pkg/basic_workflows/legacycli.go, release-scripts/prepare-release.sh
=> chore: update main from release-candidate

src/cli/commands/monitor/index.ts, src/lib/snyk-test/index.js
=> fix(test, monitor): handle error from pnpm FF check 

src/cli/commands/monitor/index.ts, src/lib/snyk-test/index.js
=> fix(test, monitor): handle error from pnpm FF check (#5348)

src/cli/commands/monitor/index.ts, src/lib/snyk-test/index.js
=> chore: update main after hotfix

src/lib/ecosystems/monitor.ts, test/jest/acceptance/snyk-container/container.spec.ts
`snyk container monitor --json` was writing separators between multiple depgraph test results in the output, resulting in an invalid JSON output which does not parse.
This fixes the output by using the same function used to process multiple open source results in the `snyk monitor` command.
---
- **Testing**
Manual testing will not be performed by the reviewing team, …
=> fix: container monitor json output

package-lock.json, package.json
=> fix: support multi-part comparison for python pip versions.

test/setup.js
=> chore: add default value for TEST_SNYK_API

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/snyk-config/snyk-config-environment.spec.ts
=> feat(config): Introduce config environment command

.circleci/config.yml
=> fix: pin to setuptools to a version that doesn't crash

package-lock.json, package.json, test/jest/acceptance/snyk-container/container.spec.ts
=> feat: forward platform parameter to snyk-docker-pull UNIFY-163

CONTRIBUTING.md, README.md
Updated ReadMe.md to reflect closed contributions policy
- **Testing**
****************************If a dependency is not necessary, …
=> docs: Update README.md for closed contributions

cliv2/go.mod, cliv2/go.sum
=> fix: sbom test vulnerability titles

cliv2/cmd/cliv2/main.go, cliv2/internal/cliv2/cliv2.go, src/cli/commands/woof/getWoof.ts, test/jest/acceptance/exitcode.spec.ts
=> fix: map subprocess errors to exit code 2 and improve logging

scripts/install-snyk.py
=> chore(scripts): update install-snyk.py to use downloads.snyk.io by default

.github/workflows/smoke-tests.yml
=> chore: update download url for smoketests

cliv2/cmd/cliv2/logheader.go, cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/snyk-config/snyk-config-environment.spec.ts
=> chore(config): Introduce sanity check for config environment

package-lock.json, package.json, test/jest/acceptance/snyk-container/container.spec.ts, test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts
=> chore: update main from rc 1.1292.2

scripts/install-snyk.py
- [] contain a risk assessment of the change (Low | Medium | High) with regards to breaking existing functionality. A change e.g. of an underlying language plugin can completely break the functionality for that language, but appearing as only a version change in the dependencies.
- **Testing**
Manual testing will not be performed by the reviewing team, and is the …
=> fix(scripts): wrap download request in try/except block

release-scripts/release-fips.json, release-scripts/release.json
=> feat: update release-scripts to use downloads.snyk.io

cliv2/cmd/cliv2/debug.go, cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, cliv2/internal/cliv2/cliv2.go, cliv2/internal/debug/debug.go, cliv2/internal/proxy/proxy.go
=> chore(logging): Improve and fix issues in trace level logging

package-lock.json, package.json
=> fix: reading wrong deps.json file for nuget

.circleci/config.yml, Makefile, binary-releases/RELEASE_NOTES.md, cliv2/scripts/sign_darwin.sh
=> fix: sign macos TS CLI binaries

.circleci/config.yml, Makefile, cliv2/scripts/sign_darwin.sh
=> chore: update main from rc 1.1292.3

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
=> fix: upgrade snyk-iac-test to v0.54.0 [IAC-3015]

cliv2/go.mod, cliv2/go.sum
=> feat(auth): Use OAuth2 as default authentication mechanism

cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum
=> chore: Add request and interaction id to http headers

package-lock.json, package.json, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
=> fix: nuget plugin writes messages to stderr

CONTRIBUTING.md
=> fix(docs): update contributing.md

.gitignore, ts-binary-wrapper/src/bootstrap.ts, ts-binary-wrapper/src/common.ts, ts-binary-wrapper/src/index.ts, ts-binary-wrapper/test/unit/common.spec.ts, ts-binary-wrapper/test/util/prepareEnvironment.ts
=> revert: "feat: change binary download url"

package-lock.json, packages/cli-alert/package.json, packages/iac-cli-alert/package.json
=> fix: upgrade slack/webhook to 7.0.3

package-lock.json, package.json
=> fix: do not show test deps for Dverbose mvn with dependencyManagement

cliv2/go.mod, cliv2/go.sum
```
commit f340bd73b5146a0653b2126e7900c467c89e4398
Author: Abdelrahman Shawki Hassan <shawki.hassan@snyk.io>
Date:   Mon Sep 2 10:25:43 2024 +0200
feat: send a new publishDiagnostics notification (#639)
:100644 100644 55888a4 d85cb64 M	README.md
:100644 100644 2d62af8 2533bba M	application/server/notification.go
```
=> feat(language-server): integrate LS

release-scripts/upload-artifacts.sh
=> fix(deployment): upload sequence to s3

package-lock.json, package.json
=> fix: scan non publishable projects on improved net

cliv2/internal/proxy/proxy.go, cliv2/pkg/basic_workflows/globalresources.go, cliv2/pkg/basic_workflows/globalresources_test.go
=> fix: restore cert file if it was externally removed

.github/workflows/sync-cli-help-to-user-docs.yml
=> chore(ci): reduce cadence of docs sync

.gitignore
=> chore: ignore swift artifacts

.vscode/launch.json
Launching the Typescript CLI in the debugger can be useful for tracing through and introspecting on CLI behavior.
Adding a few common test workflows that transit the Typescript CLI codebase along different routes.
- **Testing**
For Node projects: It’s …
=> chore: add several ts cli launch configs

dangerfile.js
=> chore: add warning to squash commits

.circleci/config.yml, release-scripts/create-jira-release.sh
=> chore(deployment): automatically create a jira release

cliv2/Makefile, cliv2/cmd/cliv2/debug.go, cliv2/cmd/cliv2/logheader.go, cliv2/cmd/cliv2/main.go
=> chore: add a sleep to allow attaching the debugger

cliv2/go.mod, cliv2/go.sum, test/acceptance/fake-server.ts, test/jest/acceptance/snyk-container/container.spec.ts, test/jest/acceptance/snyk-sbom/sbom.spec.ts
=> feat: add CycloneDX 1.6 SBOM support

binary-releases/RELEASE_NOTES.md
=> docs: update release notes on rc

.gitignore, ts-binary-wrapper/src/bootstrap.ts, ts-binary-wrapper/src/common.ts, ts-binary-wrapper/src/index.ts, ts-binary-wrapper/test/unit/common.spec.ts, ts-binary-wrapper/test/util/prepareEnvironment.ts
=> chore: merge release into main

src/lib/index.js, src/lib/snyk-test/run-test.ts
=> chore: refactor perform direct import

cliv2/go.mod, cliv2/go.sum
=> chore: update gaf to set oauth type in params

.snyk
=> chore: temporary ignore on vuln

.snyk, package-lock.json, package.json
- **chore(deps): upgrade micromatch@4.0.8**
- **chore: remove ignore from .snyk**
- **Testing**
****************************If a …
=> fix: upgrade micromatch 4.0.8

package-lock.json, package.json
=> fix: scan nuget with PublishSingleFile turned on

src/cli/commands/monitor/index.ts, src/lib/normalize-target-file.ts, src/lib/snyk-test/run-test.ts, test/acceptance/workspace-helper.ts, test/tap/cli-monitor/cli-monitor.all-projects.spec.ts
=> fix: add normalize help for deriving target files [CLI-448]

.circleci/config.yml, cliv2/internal/proxy/proxy_test.go, src/cli/commands/test/iac/local-execution/local-cache.ts, src/lib/iac/drift/driftctl.ts, src/lib/iac/test/v2/local-cache/policy-engine/download.ts, ts-binary-wrapper/test/util/prepareEnvironment.ts
=> chore: replace static urls with downloads

.circleci/config.yml
=> chore(ci): speed up build

cliv2/internal/cliv2/cliv2.go, cliv2/internal/cliv2/cliv2_test.go, cliv2/internal/embedded/cliv1/cliv1.go, cliv2/internal/embedded/cliv1/dummy_embedded_legacy_cli.go, cliv2/internal/embedded/cliv1/embedded_binary_template.txt, cliv2/pkg/basic_workflows/legacycli.go, test/jest/acceptance/extra-certs.spec.ts, test/jest/acceptance/parallel-execution.spec.ts, test/jest/acceptance/woof.spec.ts
=> fix: use runtimeInfo to derive the version for cliv1 path

.github/workflows/smoke-tests.yml, test/smoke/alpine/entrypoint.sh, test/smoke/install-snyk-binary-win.sh
=> chore(ci): remove use of EOL node

.circleci/config.yml
=> chore: improve win build time

src/lib/constants.ts, src/lib/find-files.ts, src/lib/plugins/get-deps-from-plugin.ts, src/lib/plugins/get-extra-project-count.ts, test/acceptance/workspaces/mono-repo-nested/.gitignore, test/acceptance/workspaces/mono-repo-nested/README.md, test/acceptance/workspaces/mono-repo-nested/level-1/level-2/Gemfile, test/acceptance/workspaces/mono-repo-nested/level-1/level-2/Gemfile.lock, test/acceptance/workspaces/mono-repo-nested/level-1/level-2/level-3/level-4/Gemfile, test/acceptance/workspaces/mono-repo-nested/level-1/level-2/level-3/level-4/Gemfile.lock, test/acceptance/workspaces/mono-repo-nested/level-1/level-2/level-3/level-4/level-5/level-6/Gemfile, test/acceptance/workspaces/mono-repo-nested/level-1/level-2/level-3/level-4/level-5/level-6/Gemfile.lock, test/acceptance/workspaces/mono-repo-nested/level-1/level-2/level-3/level-4/level-5/package-lock.json, test/acceptance/workspaces/mono-repo-nested/level-1/level-2/level-3/level-4/level-5/package.json, test/acceptance/workspaces/mono-repo-nested/level-1/level-2/level-3/package-lock.json, test/acceptance/workspaces/mono-repo-nested/level-1/level-2/level-3/package.json, test/acceptance/workspaces/mono-repo-nested/level-1/node_modules/node-uuid/README.md, test/acceptance/workspaces/mono-repo-nested/level-1/node_modules/node-uuid/package.json, test/acceptance/workspaces/mono-repo-nested/level-1/node_modules/qs/Readme.md, test/acceptance/workspaces/mono-repo-nested/level-1/node_modules/qs/package.json, test/acceptance/workspaces/mono-repo-nested/level-1/package.json, test/acceptance/workspaces/mono-repo-nested/node_modules/node-uuid/README.md, test/acceptance/workspaces/mono-repo-nested/node_modules/node-uuid/package.json, test/acceptance/workspaces/mono-repo-nested/node_modules/qs/Readme.md, test/acceptance/workspaces/mono-repo-nested/node_modules/qs/package.json, test/acceptance/workspaces/mono-repo-nested/package-lock.json, test/acceptance/workspaces/mono-repo-nested/package.json, test/jest/acceptance/snyk-test/all-projects.spec.ts, test/tap/find-files.test.ts
=> fix: respect default detection depth of 4

cliv2/cmd/cliv2/main.go, cliv2/cmd/cliv2/main_test.go, cliv2/cmd/cliv2/testdata/sarif.json, cliv2/go.mod, cliv2/go.sum, cliv2/scripts/prepare_licenses.sh
=> feat: add data transformation workflow [CLI-502]

cliv2/go.mod, cliv2/go.sum
=> chore: update gaf to use new feature flag helper

cliv2/scripts/prepare_licenses.sh
=> chore: restore licenses script

.gitleaksignore
=> fix: ignore false positive

cliv2/go.mod, cliv2/go.sum, src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
=> fix: upgrade IaC rules extension and snyk-iac-test

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
=> chore: update pr template and contribution guide

cliv2/cmd/cliv2/main_test.go, cliv2/go.mod, cliv2/go.sum
=> feat: introduce template based renderer

.circleci/Dockerfile, .circleci/config.yml, CONTRIBUTING.md, cliv2/Makefile, cliv2/cmd/cliv2/main.go, cliv2/go.mod
=> chore: upgrade go 1.23

package-lock.json, package.json
Tracking https://github.com/snyk/cli/pull/5531. Once the other PR has been merged successfully this changeset will move to Ready for Review
=> fix: upgrade nodejs plugin (target release candidate)

cliv2/go.mod, cliv2/go.sum, package-lock.json, package.json, test/jest/acceptance/snyk-sbom-test/all-projects.spec.ts
=> fix: upgrade release candidate

package-lock.json, package.json
Updates `snyk-gradle-plugin` to the latest version to improve how we run gradle wrapper to generate dep-graphs
=> fix(deps): address security vulnerability in snyk-gradle-plugin

cliv2/go.mod, cliv2/go.sum
=> fix(language-server): update styles

cliv2/go.mod, cliv2/go.sum
=> fix(language-server): run scans async when updating workspace folders [IDE-690]

binary-releases/RELEASE_NOTES.md
Updates the Release Notes for the next artefact.
=> docs: update release notes

test/smoke/alpine/Dockerfile, test/smoke/docker-root/Dockerfile
=> fix: smoke test failure no gradle

.snyk
=> chore: ignore cross-spawn vuln due to no upgrade path available

.snyk
Ignores vulnerability that is not reachable as the vulnerable function is not invoked within our dependencies.
=> chore(ci): ignore unreachable vuln

package-lock.json, package.json
Updates snyk-nuget-plugin in order to fix a bug regarding false positives, details [here](https://github.com/snyk/snyk-nuget-plugin/pull/228)
There is no risk, this upgrade will fix the bug regarding False Positives on runtime dependencies when using Improved Dotnet
Check the snyk-nuget-plugin PR
Please use [this](https://github.com/snyk/snyk-nuget-plugin/tree/main/test/fixtures/dotnetcore/dotnet_8_false_positive/FirstProject) fixture
Automated test [here](https://github.com/snyk/snyk-nuget-plugin/blob/main/test/parsers/parse-core-v2.spec.ts#L143)
=> fix: runtime versions overwriting nuget versions

release-scripts/hcl-to-json-parser-generator-v2/Makefile, release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/go.mod, release-scripts/hcl-to-json-parser-generator-v2/src/hcltojson-v2/go.sum, src/cli/commands/test/iac/local-execution/file-parser.ts
Updates snyk-iac-parsers to 1.3.1, containing [fix](https://github.com/snyk/snyk-iac-parsers/pull/52) for https://snyksec.atlassian.net/browse/IAC-3138
Test [was added](https://github.com/snyk/snyk-iac-parsers/blob/9ac5d7e6736674eea4c9d33119245b9c27f5cada/terraform/hcl2json_test.go#L315) in `snyk-iac-parsers`
Just a regular `snyk iac test` on a folder containing the `ssm.tf` attachment to [the issue](https://snyksec.atlassian.net/browse/IAC-3138)
=> fix: update  snyk-iac-parsers version [IAC-3138]

test/jest/util/runSnykCLI.ts
Small QOL life change to make the test behaviour easier to understand.
=> chore: introduce logging on tests

cliv2/scripts/sign_darwin.sh
This PR triples the sleep time for signing darwin binaries
=> chore: triple the sleep time for signing darwin binaries

binary-releases/RELEASE_NOTES.md, package-lock.json, package.json, test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts
=> Release rc 1.1294.2

.circleci/config.yml
=> fix: job name typo

cliv2/go.mod, cliv2/go.sum
=> fix(instrumentation): add default oss product for monitor as well

.circleci/config.yml
Upgrade macos acceptance test to use gradle8 instead of 6, since 6 was disabled due to it being end of life.
=> chore: update gradle for macos runners

cliv2/go.mod, cliv2/go.sum
=> chore: add cross-region-routing flag

src/lib/iac/test/v2/local-cache/policy-engine/constants/utils.ts
Security update for `snyk-iac-test`.
=> fix: snyk-iac-test security update [IAC-3171]

.snyk, cliv2/.snyk
=> chore(ci): ignore snyk finding to allow time to validate fix path

.snyk, cliv2/.snyk, cliv2/go.mod, cliv2/go.sum
chore(ci): ignore snyk finding to allow time to validate fix path
fix(snyk-ls): upgrade vulnerable pkg gomarkdown
fix(snyk-ls): dont resolve venv symlinks
=> chore: include fixes in RC

release-scripts/upload-artifacts.sh
The current output does not provide enough visibility
on what data is being sent as part of the event payload.
Before:
```
Triggering build-and-publish workflow at snyk-images...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   161    0     0  100   161      0    525 --:--:-- --:--:-- --:--:--   527
Successfully triggered build-and-publish workflow at snyk-images.
```
After
```
Triggering build-and-publish workflow at snyk-images...
Version: v1.1296.0-preview.2aa94d168a8a77f016067a6da836a6b537f2ee69
Release Channel: preview
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   161    0     0  100   161      0    525 --:--:-- --:--:-- …
```
=> chore(ci): print out versions and distribution channel

.circleci/config.yml, cliv2/go.mod
Upgrades go runtime to address security fixes to the crypto/x509 and net/http packages, as well as bug fixes to the compiler, the runtime, and the net package. 
More information:
https://github.com/golang/go/issues?q=milestone%3AGo1.23.5+label%3ACherryPickApproved
Reference: CLI-658
=> chore(deps): upgrade go v1.23.5

cliv2/go.mod, cliv2/go.sum, cliv2/internal/proxy/proxy.go
Switch from elazarl/goproxy => stripe/goproxy.
Aim here is to create an artifact on our preview channel can be used for validation with our customers. 
Reference: CLI-658
* Install on a Linux machine
* Set some additional certificate bundles, for example `export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-bundle.crt`
* Run `snyk test .`
Expected result: The test will exit in an expected outcome, rather than an excesssive message size error message.
=> chore(deps): switch to stripe/goproxy

cliv2/go.mod, cliv2/go.sum
- bump go-application-framework to remove cuelang from the transformation workflow and instead use a native go trasnformer. This should improve performance significantly.
Check the changes on gaf
https://github.com/snyk/go-application-framework/pull/298
These changes should have 100% parity with the previous implementation so there should be no change in output. Run a test using the new transformation workflow, everything should work as before. 
```bash
INTERNAL_SNYK_TRANSFORMATION_WORKFLOW_ENABLED=true ./binary-releases/snyk-macos-arm64 code test ../shallow-goof --org=ide-consistent-ignores-test -d
```
=> chore: 598 transformation perf

package-lock.json, package.json
Fixes a bug in Improved .NET solution where we failed to pick up the right version for runtime dependencies.
https://github.com/snyk/snyk-nuget-plugin/pull/233
Using [this](https://github.com/snyk/snyk-nuget-plugin/blob/main/test/fixtures/dotnetcore/dotnet_8_transitive_false_positive/SecondProject/dotnet_8_second_project.csproj) fixture, check for the version of Microsoft.EntityFrameworkCore.Analyzers, correct version is 8.0.12
=> fix: (test/monitor) improved dotnet false positives

cliv2/go.mod, cliv2/go.sum
* Improved memory usage when executing code scans on large projects
* Fix incorrect filtering of files when executing code scans which could fail the analysis
https://github.com/snyk/snyk-ls/pull/767
=> fix(language-server): Improved memory usage and fix incorrect filtering of files when executing code scans

test/smoke/spec/snyk_monitor_spec.sh
=> chore: adapt expectation after changing test endpoint

test/jest/acceptance/cli-json-file-output.spec.ts, test/smoke/spec/snyk_code_spec.sh, test/smoke/spec/snyk_monitor_spec.sh
We have been changing the test configuration (instance, org, feature flags) which now causes some failures due to bugs and incorrect expectations. To unblock the pipeline, the too narrow expectations have been adapted and until a bug is fixed, one test has been configured to forcefully run against the legacy but still current code test implementation.
=> fix: adapt test expectations due to test config changes

binary-releases/RELEASE_NOTES.md
Update of the release notes. No Risk.
=> docs: Update release notes for 1.1295.3

binary-releases/RELEASE_NOTES.md, release-scripts/next-version.sh
Merging a final fix for the version number.
=> chore: update release branch for 1.1295.3

.github/PULL_REQUEST_TEMPLATE.md
=> chore: Update PULL_REQUEST_TEMPLATE.md to include ask for product notes

cliv2/go.mod, cliv2/go.sum, cliv2/internal/proxy/proxy.go, cliv2/internal/proxy/proxy_test.go
Cherry picks the goproxy updates from #5739 
Reference CLI-658
=> fix: upgrade goproxy to v1.7.0

test/jest/acceptance/snyk-fix/fix.spec.ts
This PR temporarily disables a failing test for `snyk fix`
=> chore: temporarily disable failing test

cliv2/go.mod, cliv2/go.sum
Upgrades `cli-extension-iac-rules` to a version in which the following vulns are addressed:
- https://app.snyk.io/org/cloud-cloud/project/9f68bc13-627e-47a5-9be8-e52204243575#issue-SNYK-GOLANG-GOLANGORGXCRYPTOSSH-8747056
- https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXOAUTH2JWS-8749594
No changes involved.
Risk: low
`<local build> iac rules --help`
`<local build> iac rules init` - try something from this interactive UX
For something already written rules from here: https://github.com/chdorner-snyk/sandbox-custom-rules use <local build> iac rules push --org=<that_has_iac+>
No
Changes included: [snyk/cli-extension-iac-rules](https://github.com/snyk/cli-extension-iac-rules)
[IAC-3242](https://snyksec.atlassian.net/browse/IAC-3242)
-
[IAC-3242]: …
=> fix (iac): update iac-rules [IAC-3242]

cliv2/pkg/basic_workflows/legacycli.go
These changes aim to remove buffering of the debug logs to have the TypeScript CLI write out directly if it hangs.
=> fix: do not buffer error logs in tscli

package-lock.json, package.json
Corrects some typos in some Error Catalog errors
=> chore: typos corrected in error catalog errors

.github/workflows/snyk-protect-production-smoke-tests.yml
Risk assessment: low
Updates the `actions/cache` to a non-deprecated version
=> chore: update actions/cache in github action workflow

cliv2/go.mod, cliv2/go.sum
Pulls in latest code-client-go and language-server fixes for Cycle 2
=> fix(language-server): bug fixes for Cycle 2 release

cliv2/go.mod, cliv2/go.sum
=> chore: merge release-candidate

.github/workflows/pr-housekeeping.yml
We should not have an open PR without any activity for a month. 
N/A.
=> fix: adding a stale PR check script

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/snyk-code/snyk-code-user-journey.spec.ts
Updates GAF dependency and the environment variables for snyk code test following the work from [this GAF PR].(https://github.com/snyk/go-application-framework/pull/318)
The actual changes were done in https://github.com/snyk/go-application-framework/pull/318. The acceptance tests around snyk code just needed to use the new environment variable for enabling the native code workflow even if CCI is not enabled.
- Use the new `FF_CODE_NATIVE_IMPLEMENTATION` to run the native code workflow even if CCI is not enabled for the org you are testing with.
=> chore: update native code test workflow feature flags

cliv2/go.mod, cliv2/go.sum
=> fix: snyk ls hotfix

.snyk
Temporary ignoring to unblock pipelines until the dependency is upgraded.
```
Issues with no direct upgrade or patch:
✗ Symlink Attack [High Severity][https://security.snyk.io/vuln/SNYK-JS-TARFS-9535930] in tar-fs@3.0.6
introduced by snyk-docker-plugin@6.17.1 > @snyk/snyk-docker-pull@3.13.0 > tar-fs@3.0.6
This issue was fixed in versions: 1.16.4, 2.1.2, 3.0.7
```
=> chore: tmp ignore

src/lib/snyk-test/run-test.ts, test/jest/acceptance/snyk-test/all-projects.spec.ts
When using `--fail-fast` and `--json` in a project with multiple manifest files, when there is at least one file that fails to scan the relevant error message is not shown and a generic error message is shown instead.
In addition, in the same scenario when using `--fail-fast` only, the Error Catalog error contains the generic error message instead of the relevant error message.
This PR surfaces the relevant error message.
Setup a folder with multiple projects, and make sure at least one project fails to scan. Then in the root project, execute:
`snyk test --all-projects --fail-fast --json`. JSON formatted response should contain the relevant error message such as:
```
{
"ok": false,
"error": "/path/to/projects/borkedProject/package-lock.json: Dependency express@^5.1.0 was not found in …
```
=> fix(test): clearer error message when testing multi-projects with fail-fast

cliv2/cmd/cliv2/logheaderfooter.go
This PR changes the way how the `Authorization` log header is redacted in the debug logs, so that log files are less likely detected by secret scanners.
=> chore: Change redaction logic to avoid false positive secret detection in log files

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/snyk-code/snyk-code-user-journey.spec.ts, test/jest/acceptance/snyk-sbom/sbom.spec.ts
This PR ensure that json and sarif output files that are specified will be written even if the folders they are in do not exist.
Missing folder structure will be created.
https://github.com/snyk/go-application-framework/pull/329
With CCI enabled
`snyk code test --sarif-file-output=not-existing/file.sarif`
=> fix: Write json/sarif files when defined directories do not exist

cliv2/go.mod, cliv2/go.sum, release-scripts/next-version.sh
=> chore: updating rc from last release

release-scripts/create-release.sh
This PR fixes a couple of issues we encountered in our release management scripts, especially when creating a new patch release.
Major changes:
* Regenerate the version when running the script rather than reading from the version file.
* Simplify and fix logic to create a new branch when creating a path version.
=> fix: script to create a patch release

cliv2/go.mod, cliv2/go.sum
IaC v2 scan fixes
https://snyksec.atlassian.net/browse/IAC-3284
https://snyksec.atlassian.net/browse/IAC-3286
=> fix: update iac extension [IAC-3284]

test/setup.js
This PR introduces a default org for tests, so that if not explicitly set tests don't just use a random org. If devs don't have access to the org they should experience a meaningful message.
=> chore: add default org name for testing

.circleci/Dockerfile, .circleci/config.yml, .dockerignore, cliv2/Makefile, cliv2/go.mod
* This PR upgrades the golang version used when building the CLI and in the build image to 1.24.2.
* The risk of the change is Low to Mid which is why we want to have it done early so that we can get feedback from the preview.
=> chore: upgrade to go 1.24

cliv2/cmd/cliv2/instrumentation.go, cliv2/cmd/cliv2/main.go
This PR introduces a temporary solution to include linux OS and glibc details in the instrumentation data to create a better picture of the OS environments the CLI is deployed to and understand compatibility expectations.
This change should have low risk, as it is limited to linux and just adds additional instrumentation data.
CLI-874
=> chore: temporarily add runtime details

.circleci/config.yml, cliv2/go.mod
Minor version bump from golang 1.23.6 to 1.23.8 (CLI-873)
=> chore: upgrade to go 1.23.8

test/jest/acceptance/snyk-code/snyk-code-user-journey.spec.ts
This PR tries to ensure that each User Journey test for `snyk code test` uploads a new bundle and therefore performs the full API interactions each time. In the previous version, cached bundles have covered up issues before.
This is achieved by applying a workaround and adding a random file to the code base that will be tested.
The risk should be low as this PR only changes tests.
=> chore: ensure to use a new bundle each snyk code test

package-lock.json, package.json
Fixes the vulnerability introduced by `cross-spawn` by using overrides. We had two different  dependencies that had to be patched.
=> chore: fix cross-spawn vulnerability

binary-releases/RELEASE_NOTES.md
=> chore: update release notes for 1.1297.0

binary-releases/RELEASE_NOTES.md
=> chore: update rc 1297.1

.circleci/config.yml, cliv2/cmd/cliv2/instrumentation.go, cliv2/cmd/cliv2/logheaderfooter.go, cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/error-catalog.spec.ts, test/jest/acceptance/snyk-code/snyk-code-user-journey.spec.ts, test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts
This PR introduces optional network request retries. They are per default disabled and only enabled in the preview version or if explicitly enabled by setting the environment variable `INTERNAL_NETWORK_REQUEST_MAX_ATTEMPTS=<N>`, with N being 1 by default.
The changes affect the CLI network behaviour and have therefore the risk to have unpredictable effects. This is why this is currently only enabled in preview CLIs. Later changes might include a gradual rollout in the stable version depending on the learnings during the preview phase.
Note: In addition to the changes I increased some of the test timeouts to decrease flakiness and increased the test sharding to speedup the build pipeline.
The associated  GAF PR https://github.com/snyk/go-application-framework/pull/346
=> feat: Increase stability through network request retries

cliv2/go.mod, cliv2/go.sum, test/acceptance/deepcode-fake-server.ts, test/fixtures/ai-bom/not-supported/markdown.MD, test/jest/acceptance/snyk-aibom/aibom.spec.ts
Bumps the version of aibom command & error catalog. The changes included are improved error handling & error messaging for the scenarios:
- User is not authenticated
- User has no access to feature
- User is scanning unsupported files
- No experimental flag is provided
- This acceptance tests
- Run the commands as they are in the acceptance tests. To simulate 401 or 403 statuses you can remove the SNYK_TOKEN and use an unprivileged SNYK_TOKEN respectively.
None required. No customer has access to this feature yet.
=> feat: improved aibom error handling

cliv2/go.mod, cliv2/go.sum
Upgrades `cli-extension-iac` to a version that addresses vulns with the `whilp/git-urls` pkg.
Jira ticket: https://snyksec.atlassian.net/browse/IAC-3320
`snyk iac test`
`snyk iac test` should have the same behaviour as before.
None.
=> fix(iac): fix CVE-2023-46402 [IAC-3320]

.github/workflows/deployment-monitor.yml
Extends https://github.com/snyk/cli/pull/5907 to fail or succeed if stable and preview versions  are not identical. Next PR will add more Slack notification infrastructure.
https://github.com/snyk/cli/actions/runs/15194476305
=> chore(ci): extend deployment monitor script with version comparison

test/jest/acceptance/snyk-code/snyk-code-user-journey.spec.ts
This PR removes a second shorter timeout from the code test User Journey tests to reduce the flakiness of these tests.
=> chore(ci): use single higher test timeout to reduce flakiness

cliv2/go.mod, cliv2/go.sum
- Bumps to the latest ai-bom extension version. This new version includes two bugfixes: [1](https://github.com/snyk/cli-extension-ai-bom/commit/526cc37d5195212a0b05caa359bc95437c7b4140), [2](https://github.com/snyk/cli-extension-ai-bom/commit/9a4b94382ef7b8df7e50dc2891d847db41ee47eb)
Specified in https://snyksec.atlassian.net/browse/AIBOM-90
None
https://snyksec.atlassian.net/browse/AIBOM-90
=> feat: bumped ai-bom version[AIBOM-90]

test/jest/acceptance/about.spec.ts, test/jest/acceptance/woof.spec.ts
This PR increases the timeout for two of the tests that often fail with timeouts and thereby contribute to a flaky build pipeline.
This change has no product risk!
N/A
=> chore(ci): increase test timeout

.snyk
Temporary ignore until the fix comes in from `snyk-docker-plugin`:
```sh
✗ Improper Link Resolution Before File Access ('Link Following') [High Severity][https://security.snyk.io/vuln/SNYK-JS-TARFS-10293725] in tar-fs@3.0.8
introduced by snyk-docker-plugin@7.0.1 > @snyk/snyk-docker-pull@3.14.0 > tar-fs@3.0.8
```
=> chore: temporary ignore 

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Added more emphasis on commit messages in the PR template, as we are often asking contributors about this specific part. It's important to our release notes, which is often thoroughly read by a wider audience.
Changed some grammar in the contribution guidelines as well, based on the docs team's best practices around active voice and punctuation, etc.
=> chore(docs): added more emphasis on commit messages in the PR template

package-lock.json, package.json, test/fixtures/snyk-ignores-invalid-expiry/.snyk, test/fixtures/snyk-ignores-invalid-expiry/vulns.json, test/jest/unit/iac/process-results/fixtures/policy-ignore-invalid-expiry.yml, test/jest/unit/iac/process-results/policy.spec.ts, test/jest/unit/policy.spec.ts
IGNR-1093 Fix to align handling for invalid ignore expiry across Snyk product lines.
https://snyksec.atlassian.net/browse/IGNR-1093
Fix to align handling for invalid ignore expiry across Snyk product lines.
=> fix: bump snyk-policy lib

cliv2/go.mod, cliv2/go.sum, cliv2/internal/proxy/interceptor/v1_analytics.go, cliv2/internal/proxy/interceptor/v1_analytics_test.go
This PR updates the go-applicatiom-framework to support Extensions to add custom instrumentation data for Interactions. The actual implementation and tests are here https://github.com/snyk/go-application-framework/pull/358.
The overall change should be of low risk as it doesn't alter any business logic.
https://github.com/snyk/go-application-framework/pull/358
Run the command below and find similar information in the instrumentation data,.
```
INTERNAL_SNYK_CODE_IGNORES_ENABLED=false snyk code test -d
...
2025-06-11T09:06:28Z analytics.report:3 - [0] Data: {"data":{"attributes":{"interaction":{"categories":["code","test","debug"],"errors":[],"e …
```
=> chore: Enable Extensions to add instrumentation data

test/jest/acceptance/pat.spec.ts
=> chore(test): updates pat tests to not use the localhost for fakeserver

.github/workflows/deployment-monitor.yml
Fix a syntax error in the deployment test to send out slack alerts again if it fails.
No Risk, since it is only affecting the CI pipeline.
N/A
=> fix(ci): deployment alert

.github/workflows/sync-cli-help-to-user-docs.yml, .github/workflows/sync-cli-readme.yml
Updates the order of PR creation / commit in the docs sync scripts. After adding some branch protection rules this started to cause failures, since we were pushing before creating PRs.
=> chore: updating the order of commit/pr in the docs sync script

.github/workflows/sync-cli-help-to-user-docs.yml, .github/workflows/sync-cli-readme.yml
OK, so required checks are not run if this is triggered by the `GITHUB_TOKEN`. (See [this](https://github.com/orgs/community/discussions/57484)).
=> chore: fixing more docs issues

cliv2/go.mod, cliv2/go.sum
=> fix(logging): redact negotiate in debug logs

binary-releases/RELEASE_NOTES.md, cliv2/go.mod, cliv2/go.sum, package-lock.json, package.json, packages/cli-alert/package.json, packages/iac-cli-alert/package.json
This PR cherry picks changes for the fix release 1.1298.1.
=> chore: pick fixes for hotfix 1.1298.1

binary-releases/RELEASE_NOTES.md, cliv2/go.mod, cliv2/go.sum, package-lock.json, package.json, packages/cli-alert/package.json, packages/iac-cli-alert/package.json
This PR merges the changes from 1.1298.1 into the rc
=> chore: update rc with 1.1298.1

release-scripts/next-version.sh, release-scripts/validate-repository.sh
* This PR temporarily ensures to use a new patch version.
* This PR extends the version validation to catch version issues early
=> fix(ci): Fix incorrect version bump

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/snyk-code/snyk-code-user-journey.spec.ts
This PR fixes the incorrect usage of certain environment variables. This means that in some cases, Environment Variables have been read and values have been used, even if they were not supposed to be used. One example where this caused an issue is the following case
```
export PROJECT_ID=1234
snyk code test --report --project-name=name
```
This example returned an error like this `"commit-id" must be provided for "report"`.
The actual fix is implemented here https://github.com/snyk/go-application-framework/pull/388
https://github.com/snyk/go-application-framework/pull/388
see above
The fix addresses issue with `snyk code test --report` when an …
=> fix(code): Fix code test --report when a project_id env var is exists

binary-releases/RELEASE_NOTES.md, cliv2/go.mod, cliv2/go.sum
* fix: set org header for aifix request
* fix: traceId Key Type
LS Hotfix PR:
https://github.com/snyk/snyk-ls/pull/941
Code-Client-Go PR:
https://github.com/snyk/code-client-go/pull/106
=> fix(language-server): Fixed missing AI Fix entitlements for cases where the default org didn’t have AI Fix enabled.

cliv2/go.mod, cliv2/go.sum
- adds Risk Score to Open Source test if feature flags are present
- [x ] Follows [CONTRIBUTING](https://github.com/snyk/cli/blob/main/CONTRIBUTING.md) guidelines
- [x ] Commit messages
- [x ] Includes detailed description of changes
- [x ] Contains risk assessment (Low | Medium | High)
- [x ] Highlights breaking API changes (if applicable)
- [x ] Links to automated tests covering new functionality
- [x ] Includes manual testing instructions (if necessary)
Adds risk score to the JSON and human readable CLI output of the Open Source Test for users with these feature flags enabled.
Testing that existing features are unaffected. Users opting in …
=> feat: update cli-extension-os-flows for Closed Beta.

ts-binary-wrapper/src/common.ts
Add node version to instrumentation data when using `npm install`.
=> chore: add environment name and version to ts wrapper

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/auth.spec.ts, test/jest/acceptance/pat.spec.ts, test/jest/util/createPAT.ts
Adds auto region configuration when using Snyk PATs for authorised requests
Relevant GAF PR: https://github.com/snyk/go-application-framework/pull/395
Run a Snyk command with Snyk PAT configured (will require Snyk PAT feature support)
- `SNYK_TOKEN=<MY_PAT> snyk whoami --experimental`
- `SNYK_API=<region> snyk auth <PAT_MATCHING_REGION> && snyk whoami --experimental`
API region is now automatically determined when using Snyk PATs for authorised requests
=> feat: support PAT auto region configuration

.circleci/config.yml, package-lock.json, package.json, scripts/jvm-install.sh, test/acceptance/workspaces/gradle-monorepo/subproj/build.gradle, test/acceptance/workspaces/gradle-multi-project/subproj/build.gradle, test/acceptance/workspaces/gradle-with-orphaned-build-file/subproj/build.gradle, test/acceptance/workspaces/large-mono-repo/gradle-multi-project/subproj/build.gradle, test/fixtures/find-files/gradle-and-kotlin/build.gradle.kts, test/fixtures/find-files/gradle-kts/build.gradle.kts, test/fixtures/find-files/gradle-kts/subproj/build.gradle.kts, test/fixtures/gradle-configurations/build.gradle
Make `snyk test`/`snyk monitor` work on projects using Gradle 9 (currently they fail with an error). Gradle 9 support was added to `snyk-gradle-plugin` and this PR bumps its version.
https://github.com/snyk/snyk-gradle-plugin/pull/314
1. Have Gradle 9 installed system-wide or via [Gradle Wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html).
2. Run `snyk test` on a Gradle project, e.g. https://github.com/snyk-fixtures/gradle-simple-repo.
`snyk test` now supports Gradle 9.
Low. The functional change is in the `snyk-gradle-plugin` that stops using the deprecated and removed Gradle's `--build-file` CLI flag in favour of an …
=> feat: add gradle 9 support to snyk test

.circleci/config.yml, binary-releases/RELEASE_NOTES.md, cliv2/go.mod, cliv2/go.sum, help/cli-commands/aibom.md, package-lock.json, package.json, scripts/jvm-install.sh, test/acceptance/fake-server.ts, test/acceptance/workspaces/gradle-monorepo/subproj/build.gradle, test/acceptance/workspaces/gradle-multi-project/subproj/build.gradle, test/acceptance/workspaces/gradle-with-orphaned-build-file/subproj/build.gradle, test/acceptance/workspaces/large-mono-repo/gradle-multi-project/subproj/build.gradle, test/fixtures/ai-bom/sample-ai-bom.json, test/fixtures/find-files/gradle-and-kotlin/build.gradle.kts, test/fixtures/find-files/gradle-kts/build.gradle.kts, test/fixtures/find-files/gradle-kts/subproj/build.gradle.kts, test/fixtures/gradle-configurations/build.gradle, test/jest/acceptance/snyk-aibom/aibom.spec.ts
=> chore: hotfix for `v1.1298.3`

.github/workflows/cli-alert.yml, .github/workflows/iac-cli-alert.yml, packages/cli-alert/src/index.ts, packages/iac-cli-alert/src/index.ts
=> chore: unify two identical environment variables

test/jest/acceptance/snyk-sbom-test/snyk-sbom-test-reachability-user-journey.spec.ts
Temporarily skips the sbom reachability test until the issue is fixed in the service.
=> feat: skip sbom reachability test

test/jest/acceptance/snyk-sbom-test/snyk-sbom-test-reachability-user-journey.spec.ts
Re-enables the sbom reachability user journey test which was temporarily disabled in a [previous PR](https://github.com/snyk/cli/pull/6121) in order to unblock the pipeline.
=> feat: re-enable sbom reachability user journey test

src/cli/commands/monitor/index.ts, src/lib/monitor/index.ts, src/lib/types.ts, test/jest/acceptance/snyk-monitor/reachability-id.spec.ts
Adds a `--reachability-id` argument to the `monitor` command.
N/A
=> feat(monitor): add --reachability-id support

cliv2/go.mod, cliv2/go.sum, test/jest/acceptance/snyk-code/snyk-code-user-journey.spec.ts
This PR adapts the previous fix https://github.com/snyk/cli/pull/6119 to be less restrictive on whitespaces and thereby leave it to the OS filesystem to resolve or not.
https://github.com/snyk/go-application-framework/pull/413 
Similar to the added test, create a directory starting or ending with a space or both
and then run `snyk code test " directoryWithSpace "` from the parent directory.
=> fix: adapt input directory handling to preserve whitespaces

scripts/install-snyk.py
Allows `install-snyk.py` to download the `snyk-alpine-amd64` instead of the `snyk-linux-arm64` binary on Alpine-based Docker images.
On an alpine-based Docker image (e.g. `alpine:latest`), first run this without these changes
```
RUN apk update && apk add --no-cache git curl python3 py3-requests
RUN curl --compressed --output /usr/local/bin/install-snyk.py https://raw.githubusercontent.com/snyk/cli/main/scripts/install-snyk.py
RUN chmod +x /usr/local/bin/install-snyk.py
RUN install-snyk.py v1.1299.0-preview.15085b358984de2122cce250f836e356b2a6892c
```
.. and see it fail.
Do the same with this script, see it work.
N/A, bugfix
=> fix: [CLI-1105] fixing broken alpine `arm64` installation

cliv2/go.mod, cliv2/go.sum
Details here: https://github.com/snyk/go-application-framework/pull/415
N/A
N/A
N/A
=> fix: fixing host auto-detection bug in `snyk auth`

package-lock.json, package.json
bumps snyk-nuget-plugin in order to allow godot sdks to be scanned by dotnet v3 scanner
https://github.com/snyk/snyk-nuget-plugin/pull/259
https://github.com/snyk/dotnet-deps-parser/pull/96
https://github.com/snyk/cli/pull/6117
By testing the CLI versions again [this fixture](https://github.com/snyk/snyk-nuget-plugin/pull/258/files#diff-39a2e085ff3ffb024f8f8acc7aa9a7126548ce926a1176fa0afdc0197d579038R1)
Low, no prod comm needed
https://snyksec.atlassian.net/browse/OSM-3021
=> feat: add support for godot projects

cliv2/go.mod, cliv2/go.sum
Bumps the GAF dependency for [this PR](https://github.com/snyk/go-application-framework/pull/416).
N/A
N/A
N/A, bugfix of unreleased feature.
=> fix: [CLI-1118] conforming the way we take precedence of auth config values

.circleci/config.yml
This PR upgrades golang from 1.24.5 to 1.24.6.
=> fix: upgrade to go 1.24.6

.circleci/config.yml, test/jest/acceptance/snyk-sbom-test/snyk-sbom-test-reachability-user-journey.spec.ts
=> chore: enable auto re-run of workflows to avoid manual intervention

cliv2/go.mod, cliv2/go.sum
```
commit b98640ff2ec286b8ea3de8ff94dad877df62a48f
Author: Knut Funkel <knut.funkel@snyk.io>
Date:   Fri Aug 29 14:13:48 2025 +0200
fix: idea crash on codeactions [IDE-1273] (#981)
* fix: added failing test to replicate the issue with appending codeaction title
* fix: added method to check that we use a valid title
* fix: add original title to the codeaction interface and use that for subsequent calls
* fix: removed unneeded code
M	application/codeaction/codeaction.go
M	application/codeaction/codeaction_test.go
M	domain/snyk/codeaction.go
M	infrastructure/code/issue_enhancer.go
M	infrastructure/oss/code_actions.go
M	internal/types/issues.go
```
[IDE-1273]: https://snyksec.atlassian.net/browse/IDE-1273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> chore(language-server): integrate LS

.circleci/config.yml
Disabling auto rerun for pipelines, since it has mostly rerun permanently failed pipelines.
=> chore: disable auto rerun

cliv2/cmd/cliv2/debug.go, cliv2/cmd/cliv2/main.go, cliv2/go.mod, cliv2/go.sum, cliv2/internal/utils/args.go, cliv2/internal/utils/args_test.go, cliv2/pkg/basic_workflows/legacycli.go, test/jest/acceptance/debuglog.spec.ts, test/jest/acceptance/snyk-test/basic-test-all-languages.spec.ts
This PR updates the log scrubbing logic to use a more layered approach of regex pattern matching and exact term matching. It should make log scrubbing more resilient and make logs less likely to contain sensitive data.
Increase the resiliency of log scrubbing
=> fix(logging): base sanitisation of logs on known parameter values

.circleci/config.yml
This PR sets the minimum macOS version to ensure the same compatibility with previous CLI binaries.
=> fix: Explicitly set minimum macos version

.circleci/config.yml
=> chore: sync main release candidate

cliv2/internal/proxy/interceptor/v1_analytics.go, cliv2/internal/proxy/interceptor/v1_analytics_test.go
This PR adds a missing mapping of float64 values when mapping legacy analytics data.
Run `snyk test -d` on a project with vulnerabilities and search the debug logs for `legacycli::metadata__vulns`.
There is no user impact.
Low
=> fix(instrumentation): Fix mapping of floating point values

.circleci/config.yml, test/jest/acceptance/snyk-container/container.spec.ts
The existing acceptance tests cover the scanning of public images or .tar images.
This PR extends the existing acceptance tests to cover scanning of local private docker images by:
- adding Docker support in CI using setup_remote_docker on linux/alpine executor machines 
- adds a test that validates the successful scan of a local private docker image
=> test: add container scan test for local private Docker Images

cliv2/go.mod, cliv2/go.sum, src/lib/formatters/iac-output/sarif.ts, src/lib/formatters/open-source-sarif-output.ts, src/lib/formatters/sarif-output.ts, src/lib/iac/test/v2/sarif.ts, src/lib/plugins/sast/analysis.ts, test/fixtures/docker/sarif-container-result.json, test/fixtures/docker/sarif-with-file-container-result.json, test/fixtures/sast/sample-analyze-folders-response.json, test/fixtures/sast/sample-sarif.json, test/jest/acceptance/cli-sarif-output.spec.ts, test/jest/unit/cli/commands/test/iac/v2/index.spec.ts, test/jest/unit/iac/process-results/fixtures/integrated-sarif-output.json, test/jest/unit/lib/formatters/__snapshots__/open-source-sarif-output.spec.ts.snap, test/jest/unit/lib/formatters/__snapshots__/sarif-output.spec.ts.snap, test/jest/unit/lib/formatters/open-source-sarif-output.spec.ts, test/jest/unit/lib/formatters/sarif-output.spec.ts, test/jest/unit/lib/iac/test/v2/sarif.spec.ts, test/jest/unit/snyk-code/snyk-code-test.spec.ts, test/tap/cli-test/cli-test.docker.spec.ts
Adds a new SARIF propriety to the CLI output. Specifically, this includes the `runAutomationDetails` ID field, SARIF specification can be consulted [here](https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790776). The generated identifier is based on scan product line and the scanned project name (where this information is available).
- This [GAF PR](https://github.com/snyk/go-application-framework/pull/433) updates the SARIF presenter to include this for the native code workflow
- `src/lib/plugins/sast/analysis.ts` update the legacy Code flow
- `src/lib/formatters/iac-output/sarif.ts` and …
=> feat: add runAutomationDetailsID to the CLI SARIF output

.circleci/config.yml, .gitleaksignore, binary-releases/RELEASE_NOTES.md, cliv2/cmd/cliv2/instrumentation.go, cliv2/cmd/cliv2/logheaderfooter.go, cliv2/cmd/cliv2/main.go, cliv2/cmd/cliv2/main_test.go, cliv2/go.mod, cliv2/go.sum, help/cli-commands/code-test.md, help/cli-commands/iac-test.md, help/cli-commands/monitor.md, help/cli-commands/test.md, package-lock.json, package.json, release-scripts/upload-artifacts.sh, src/lib/errors/error-catalog-factory.ts, src/lib/errors/failed-to-get-vulnerabilities-error.ts, src/lib/errors/failed-to-run-test-error.ts, src/lib/errors/monitor-error.ts, src/lib/request/promise.ts, test/jest/acceptance/error-catalog.spec.ts
* This PR cherry picks final changes for the release.
* It updates the help.
* It updates the release notes.
=> chore: update 1.1300
