appveyor.yml
package.json

Introduces `npm run build` in appveyor settings

chore: 'npm run build' in appveyor

---

lib/protect/fetch-patch.js

Adds proxy support when fetching patches, see https://github.com/snyk/snyk/pull/112
Let me know if you think this should be refactored into the lib/request/request file, 
https://github.com/snyk/snyk/pull/112

fix: add proxy support when fetching patches

---

.travis.yml

Adds the needed `@semantic-release/exec` plugin as a dependency to enable the semantic release process.

chore: add exec plugin to enable release process

---

cli/commands/test.js
test/acceptance/cli.acceptance.test.js

A cosmetics issue, aligning spaces in output like this:
```
Testing /Users/anton/code/snyk/snyk...
Organisation:      snyk
Package manager:   npm
Target file:       package.json
Open source:       no
Project path:      /Users/anton/code/snyk/snyk
Local Snyk policy: found
Licenses:          enabled
✓ Tested 246 dependencies for known issues, no vulnerable paths found.
```

fix: adjust spacing on 'test' output

---

package.json

- explicitly include files in npm package (pass list) instead of ignoring files with .npmignore (block list)
- https://docs.npmjs.com/files/package.json#files
- checkout branch
- navigate elsewhere
- `npm pack path/to/branch`
- unpack resultant tarball
- `npm install package` (tarball will unpack into a folder named `package`)
- ensure `cli` works: `path/to/unpacked-package/node_modules/snyk/cli/index.js <command>`
- we had inadvertently started bundling package binaries into the npm package

fix: explicitly include files in npm package

---

package.json

Bumps `snyk-docker-plugin` to achieve a smaller footprint of the overall published package.
See https://github.com/snyk/snyk-docker-plugin/pull/40

fix: bump snyk-docker-plugin for smaller footprint

---

cli/commands/auth.js
cli/commands/monitor.js
cli/commands/protect/wizard.js
cli/commands/unpublished/index.js
lib/protect/patch.js
lib/protect/update.js
lib/snyk-test/npm/index.js
lib/snyk-test/run-test.js

In error flows, spinner labels are not cleared, causing a failed invocation of the CLI to have excess output at the last line like this:
```
...
<Some error message explaining the failure>
...
<Stack trace>
...
\ Analyzing maven dependencies for pom.xml
```
This change clears all running spinners in case an error is being thrown.

fix: clear spinner labels on errors

---

cli/commands/monitor.js
lib/spinner.js
test/acceptance/cli.acceptance.test.js

When `snyk monitor` fails, exit with `RC 1` by throwing an error. Prior to this change, `snyk monitor` failures used to have `RC 0`.

exit code 1 on monitor failure, better monitor output readability

---

.travis.yml
package-lock.json
package.json

this includes a fix @darscan reported in https://github.com/tomas/needle/issues/261
updating `.travis.yaml` to use up-to-date `node 8` in tests again

fix: bump needle to ^2.2.4 to fix bug with node 8.12.0

---

package.json

This updates `snyk-python-plugin` to handle pip 18 (relevant PR: https://github.com/snyk/snyk-python-plugin/pull/47)

fix: bump snyk-python-plugin to 1.8.2 - to handle pip 18

---

src/cli/commands/protect/wizard.js

Fixing a bug where if a yarn project is fixed with wizard we traversed the node modules via a specially set flag but then did not set this back just before monitoring.
While traversing node_modules for yarn is a must for now for patching (old style node_module traversal populates where each package lives on disk which is used during patch time) this fall back is not needed for yarn projects node > 6 when we run a test just before monitoring the project & sending the snapshot to snyk web.
To replicate:
- clone https://github.com/lili2311/npm-lockfiles
- run `snyk wizard` in the `yarn-lockfiles` folder and see the error appear: not a node project (this is an error encountered because we are sending yarn.lock as a filename to the `resolve-deps` lib instead pf `package.json`)

fix: do not traverse node_modules on wizard monitor for yarn

---

.snyk
src/cli/commands/test.js
test/acceptance/cli.acceptance.test.js
test/acceptance/fixtures/docker/vulns.json

Removes display of number of vulnerable paths for docker, since currently the count is inaccurate for several reasons:
1. the trees are trimmed quite aggressively in snyk-docker-plugin to reduce size.
2. for rpm & apk based images, we don't differentiate between packages installed manually vs. transitives that were installed automatically.
[Jira ticket SC-6459](https://snyksec.atlassian.net/browse/SC-6459)

fix: don't print vulnerable paths count for docker tests

---

src/cli/commands/monitor.js
src/cli/commands/test.js
src/lib/error.js
src/lib/monitor.js
src/lib/snyk-test/npm/index.js
src/lib/snyk-test/run-test.js
test/acceptance/cli.acceptance.test.js
test/acceptance/fake-server.js

Rename cliMessage to userMessage as it is to be re-used throughout other services and needs to be more generic/consistent
https://github.com/snyk/registry/pull/5937

feat: Rename cliMessage to userMessage for consistency

---

src/cli/commands/protect/wizard.js
src/lib/protect/get-vuln-source.js
src/lib/protect/index.js
src/lib/protect/patch.js
src/lib/protect/update.js
test/deduped-package-patch.test.js
test/wizard-package-changes.test.js
test/wizard-prepare.test.js
test/wizard-prepublish.test.js

Also amend how we re-lock the lockfile
- Fixes a bug where for package-lock.json projects we are relying on the assumed patch paths for patching (since the lockfile is the exact shape of the `node_modules`)
The bug was around us using `cwd` which is mostly used for tests and this was returning path paths like: `/npm/node_modules/path-to-module/` instead of  `/node_modules/path-to-module/`
- Also fixing how we regenerate the lockfile if user selected to add snyk to dependencies. Update is relying on having the vuln from paths present, so skipping straight past all this and directly calling `install` && `installDev` since adding `snyk` is not part of the vuln testing flow 
https://github.com/snyk/snyk/compare/fix/file-path-fix?expand=1#diff-7d011e4c9a3d66fcafd27dede7916a27R17
Project `goof` …

fix: fix for assumed patch paths

---

src/cli/commands/protect/wizard.js
src/cli/commands/test.js
src/lib/plugins/npm/index.js
src/lib/snyk-test/npm/index.js

Always fall back to node_module traversal for the initial wizard test, then test using lockfile parser before monitor for lockfile based projects

fix: Fallback to node_modules for initial wizard  & protect test

---

src/lib/snyk-test/run-test.js
src/lib/snyk-test/run-test.ts

chore: async/await and TS in lib/snyk-test/run-test

---

src/lib/monitor.js

- shows a "Connection Timeout" message when `monitor` times out
- previously this should show `unexpected error: undefined`

fix: show friendly message on monitor timeout

---

.snyk
src/cli/commands/monitor.js
test/acceptance/cli.acceptance.test.js

Sends the base image to registry when running `snyk monitor --docker`.

feat: send the base image when running `snyk monitor`

---

package.json

This patch raises the snyk-docker-plugin version, fixing an issue where
we failed to parse ARGs used in a Dockerfile FROM instruction

fix: Parse ARGs in Dockerfile FROM instructions 

---

package.json
src/lib/plugins/npm/index.js
src/lib/plugins/yarn/index.js

Projects with no name property in package.json will now be named by their relative path
https://snyksec.atlassian.net/browse/SC-6758
Also related to snyk/nodejs-lockfile-parser#29 and
snyk/npm-deps#53

fix: move to the new version of nodejs-lockfile-parser 

---

package.json
src/cli/index.ts

Adding a message to CLI when a newer version is available
https://snyksec.atlassian.net/browse/SC-6399

feat: add a CLI message when newer version is available

---

docker/docker-entrypoint.sh
docker/docker-python-entrypoint.sh

Fixes two issues in the docker entrypoint that wraps the CLI and supports a Jenkins context:
* Project paths that include spaces were causing the build report to be lost. Specifically, `${PROJECT_PATH}/${PROJECT_FOLDER}/...` needed to be quoted.
* `snyk monitor` command with standalone double-dash args was having an extra standalone double-dash.
* General sanitisation of `$ARG` to `${ARG}`
* Breaking long lines with `\` for readability

fix: docker image fails with spaces in project folder names

---

docker/Dockerfile.gradle-2.8
docker/Dockerfile.gradle-4.4
docker/Dockerfile.maven-3.5.4
docker/Dockerfile.sbt-0.13.16
docker/Dockerfile.sbt-1.0.4

A recent change to `gpg` invoked by `apt-key` broke our image building process with this message:
```
Step 6/22 : RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
---> Running in 75c61f36c92b
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.3O5vEEFljY/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
gpg: key 8F9293A1EEA14886: public key "Totally Legit Signing Key <mallory@example.org>" imported
gpg: cannot open '/dev/tty': No such device or address
The command '/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886' returned a non-zero code: 2
```
Solving this with the wisdom of the Internet by using `--no-tty`.

fix: gpg complains on non-tty mode in docker building process

---

src/cli/index.ts
src/lib/updater.ts
test/updater.test.js

Adds tests for update-notifier API

fix: add tests for update-notifier and adjust code

---

.gitignore

A change to the gitignore started picking up the package-lock.json again; this patch re-ignores it

chore: ignore root package-lock.json

---

package.json

`snyk-python-plugin` PR: https://github.com/snyk/snyk-python-plugin/pull/50

fix: bump python-plugin to not depend on `pip` being available

---

package.json
test/acceptance/workspaces/npm-package-policy/.snyk
test/acceptance/workspaces/npm-package-policy/custom-location/.snyk
test/acceptance/workspaces/npm-package-with-git-url/.snyk
test/acceptance/workspaces/npm-with-dep-missing-policy/.snyk
test/acceptance/workspaces/ruby-app-policy/.snyk
test/fixtures/pkg-SC-1472/.snyk

bump version for snyk-policy dependency
https://snyksec.atlassian.net/browse/BST-264

fix: bump version for snyk-policy dependency

---

src/cli/commands/test.js
test/acceptance/cli.acceptance.test.ts
test/acceptance/fixtures/docker/find-result-binaries.json
test/fixtures/cli-test-results/semver@2

Adds a `Fixed in` version key in binaries/output, using npm semver rules.
Refactors formatting issues logic.
Run `snyk test --docker node:5.10.1` for example to see the fixed versions of found vulnerabilities.

feat: fixed in key in binaries output

---

package.json
src/cli/commands/test.js
src/lib/snyk-test/run-test.ts
test/acceptance/cli.acceptance.test.ts

This patch adds an extra line to vulnerabilities found in a Dockerfile, indicating whether they came from the base Docker image (FROM: ) or your Dockerfile. In the latter case, the instruction that installed the vulnerable package is also highlighted.

feat: Split dockerfile / base image vulns

---

src/lib/snyk-test/run-test.ts

In order to collect improve our docker image matching, we want to start looking on the layers SHAs.
In his PR we'll send the layers SHAs as part of the analytics.

feat: send docker image layers SHAs

---

src/cli/commands/test.js

This patch updates the conditions in which docker file instructions are
shown in remediation advice; currently they are shown even the file is
not used, resulting in some strange "undefined" messages.

fix: Undefined base image

---

test/fixtures/protect-via-snyk/package.json

This change was needed in #340 because one strange test tested via installing an already released snyk version ... now the fixed version is already released, so can restore the fixture ...

test: remove a fixture change done in PR #340

---

src/cli/commands/test.ts

`test` command rewritten to TS.

refactor: test command rewritten to TS

---

help/file.txt

Updates the Snyk CLI help for `snyk help file` to also include `composer.lock` as a supported ecosystem

fix(docs): add missing composer.lock file

---

src/cli/commands/test.ts
src/lib/snyk-test/legacy.ts
test/acceptance/fixtures/docker/find-result-binaries.json

Removes calculation of `fixedInVersion` for binaries, as the calculation of it has moved
to phoenix.
https://snyksec.atlassian.net/browse/DC-53

feat: remove semver and use nearestFixedInVersion instead

---

src/cli/commands/test.ts
src/lib/snyk-test/legacy.ts

The calculation is now done only once on our backend services
and our UI(cli & registry) are getting it as a vulnerability attribute.

feat: move fixed in calculation for os packages to phoenix

---

package.json

bumps docker plugin to `1.19.0` recognize `openjdk-jre` origin of installation.

feat: bump docker plugin

---

help/help.txt
src/cli/commands/test.ts

- Introduces `user layer` flag, when used, only user layer issues will be displayed.
- fixes single/multiple vulnerabilities text for key binaries display.
added `Pro tip` to introduce flag:

feat: docker exclude base image vulns flag

---

package.json

commit 7f41eac1e3a introduced a change to snyk-docker-plugin
where the subprocess module would return both stdout and stderr.
unfortunately, due to backward compatibility considerations,
java's "-version" command outputs strictly to stderr; naively,
we were looking for stdout.
(https://stackoverflow.com/questions/17968856/redirect-to-stdout-in-bash)
the fix in snyk-docker-plugin propagates both stdout and stderr
for further parsing.

feat: bump snyk-docker-plugin to include openjdk analyser fix

---

src/cli/commands/test.ts

Removes misleading docker layers vulns count breakdown. After introducing a breakdown of the total amount of vulns to base image vulns and other layers vulns, we've realized the number might be misleading since base image vulns and other layers vulns may overlap which means they won't add up to the total amount vulns and the breakdown will be misleading as seen in the screenshot below.
Here we can see the total number of vulns is 166, user layers vulns amount is 94 and base image vulns is 126. (the line `Vulnerabilities introduced by your base image: 72.` is a mistake since it ignores the real count of base image vulns and base on `total amount of vulns - other layers vulns`).
This PR will propose this output when using the flags `--file` and `--exclude-base-image-vulns`:
and this output …

feat: remove misleading docker layers vulns count breakdown

---

package.json
src/cli/commands/protect/prompts.js

- Replace [undefsafe](https://www.npmjs.com/package/undefsafe) with `lodash.get` which is essentially the same thing.
- Throw away `undefsafe` dependency.

chore: replace undefsafe with lodash.get

---

package.json

Remove dependencies:
- `get-uri`
- `hasbin`
Because nobody use it in the code.

chore: remove get-uri and hasbin

---

package.json
test/fixtures/protect-via-snyk/package.json

`get-uri` was removed by https://github.com/snyk/snyk/commit/c3c1a337f33f6986e6ef049eea3ffbaed5a755f4 because it didn't seem to have any direct usage.
However, it was originally added by https://github.com/snyk/snyk/commit/8bfae15559fdc502974853ddebfd66fcb0a11f47 to prevent `get-uri@2.0.3` from breaking Node 4 compatibility.
This patch reintroduces `get-uri` as a top level dependency to prevent npm from installing the higher version (effectively relying on npm's deduping mechanism to restrict the version used). Also changes a test fixture temporarily (see the previous get-uri pin and subsequent revert in https://github.com/snyk/snyk/commit/bbfd7002aed081b4c4018c4f2743a11329c93f9a)

fix: Re-pin get-uri at 2.0.2

---

src/lib/error.js
src/lib/protect/apply-patch.js
src/lib/protect/patch.js
test/protect-fail.test.js

Some better verbosity in case of `snyk protect` errors with more data about the failing patch.
Before:
```
The patch against "node_modules/debug" (npm:debug:20170905) failed.
Please email support@snyk.io if this problem persists.
```
After:
```
Failed to apply patch against npm:debug:20170905 on debug@2.5.2 at "node_modules/debug"
Error: Found a mismatching patch, reference ID: e2c6c2e5-42ad-4754-aa7a-5c6956777974
Please email support@snyk.io if this problem persists.
```

fix: more verbose error in case of patch failure

---

package.json

Update nuget-plugin version to fix issue where we set the `--file` flag from a different directory (`--file='./path/to/file.txt`) and the lock file was not found in the directory (`.`)

fix: update nuget-plugin version

---

docker/docker-entrypoint.sh

Currently, only the regular result is output
However, the monitor result has some useful info such as the scan URL

Output the monitor result as a json

---

docker/docker-entrypoint.sh

Currently, only the regular result is output
However, the monitor result has some useful info such as the scan URL
This merges #381 as an internal contribution to overcome CI.

fix: when running in a docker container, save monitor command output in a file

---

src/cli/commands/test.ts

@robcresswell asked me to find a bug in CLI, and this is what I've come up with 😂 
It removes unnecessary space in the happy case where `snyk test` finds 0 vulnerabilities.

Remove unnecessary space before comma in the summary output text

---

src/lib/plugins/index.ts
src/lib/plugins/npm/index.ts
src/lib/plugins/yarn/index.ts
src/lib/snyk-test/npm/index.js
test/acceptance/cli.acceptance.test.ts

- The value provided to the cli can be a string or a bool, handle both
See the commands below
```snyk-dev test --strictOutOfSync=true
An unknown error occurred. Please include the trace below when reporting to Snyk:
Error:
Testing /Users/lili/www/-CSUP...
Dependency @/ops-admin was not found in yarn.lock. Your package.json and yarn.lock are probably out of sync. Please run "yarn install" and try again.
at /Users/lili/www/snyk/snyk/src/cli/commands/test.ts:141:19
at step (/Users/lili/www/snyk/snyk/dist/cli/commands/test.js:32:23)
at Object.throw (/Users/lili/www/snyk/snyk/dist/cli/commands/test.js:13:53)
at rejected (/Users/lili/www/snyk/snyk/dist/cli/commands/test.js:5:65)
at <anonymous>
at runMicrotasksCallback (internal/process/next_tick.js:122:5)
at _combinedTickCallback …
```

fix: Parse bool or string out of sync option

---

README.md

Updates the README page layout 
Confirm links, call to actions and information is correct and fits.

fix(README): update layout for project page

---

help/help.txt

Current help advises to use specify the org name but it isn't clear about the fact that you need to specify the "machine name" representation of the org name.
If I have an org called "Liran demo", it has a machine name of "liran-demo-123" associated with it and the latter is the one that should be provided to the CLI.

fix: highlight the use of machine name for orgs help

---

README.md

Contributed by: https://github.com/snyk/snyk/pull/266
```bash
cd snyk/docker
docker build -f Dockerfile.docker -t snyk/snyk-cli:docker .
docker run -it --rm -e SNYK_TOKEN=$SNYK_TOKEN -v $PWD:/project -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk-cli:docker test --docker snyk/snyk-cli:docker --file=/project/Dockerfile.docker
```

Add Dockerfile.docker and update README.md

---

package.json

Fixes issue when target file for scanning is a Gradle subproject.
As per https://github.com/snyk/snyk-gradle-plugin/issues/33, scan subproject/build.gradle
https://github.com/snyk/snyk-gradle-plugin/issues/33

fix: correct scanning when targeting Gradle subprojects

---

package.json

Fixes an issue where scans will fail because `--no-parallel` flag is not supported on Gradle <4.3
Plugin version bump.
https://snyksec.atlassian.net/browse/BST-530

fix: support for Gradle < 4.3

---

package.json
src/lib/snyk-test/run-test.ts
test/acceptance/cli.acceptance.test.ts

In order to resolve some bugs and improve the code, move exclude-base-image-vulns option logic out of this repo and into the docker plugin:
* Remove logic for excluding base image vulns from this repo - now handled in docker plugin.
* Bump docker plugin version to include support for this option.
More info on the docker plugin implementation and effects can be found in original [PR](https://github.com/snyk/snyk-docker-plugin/pull/74).

fix: Move exclude-base... option to docker plugin

---

package.json

More reliable support for Gradle analysis using standalone Snyk CLI binaries.
Applies especially for Windows (Unix builds should have been fixed in 1.143.2, but that was not properly mentioned in the release notes.)
Build binaries via `pkg` and let 'em loose, under Linux, Mac and Windows.
Depends on writable tmp filesystem being available, which seems to be usually the case, given data from plugins for different build systems, e.g. Python.

fix: Gradle analysis fixed in standalone Snyk binaries

---

src/lib/protect/apply-patch.js
src/lib/protect/patch.js
test/protect-apply-same-patch-again.test.js

Fixes a bug where the patched files object was iterated over as an array `for ... of`, instead of an object `for ... in`.
This revealed another issue where the `.orig` copies of patched files were not being created. This is needed as our logic undoes a patch using the `.orig` pre-patched file when the same patch is re-applied twice. This is needed in cases where a protected project is being protected again, for the chance the used patch has been updated in the meantime.
😌

fix: create copies of original files prior to patching

---

.eslintrc
.travis.yml
package.json
src/cli/runtime.ts
src/lib/snyk-test/npm/index.js
test/runtime.test.js
test/wizard-package-changes.test.js
tsconfig.json

This PR raises our minimum support Node version to 6. See https://snyk.io/blog/snyk-cli-drops-support-for-node-js-4-argon/ for more detail

feat: Update unsupported runtimes

---

package.json

bump snyk-nuget-plugin version so CLI can now process nuget projects that have their target frameworks available in the project.assets.json lock file but not in the csproj file. 
Run snyk test on nuget project that doesn't have TF specified in .csproj file. -> should now work.
https://snyk.slack.com/archives/C85KJCJAJ/p1547042854066600

feat: read targetFramework from assets file

---

tsconfig.json

Our tsconfig had es2017 library enabled in it.
The library must match the target runtime (https://stackoverflow.com/a/50987516), and Snyk CLI needs to run on Node 6 which only supports (roughly) es2015: https://node.green/

chore: downgrade tsconfig lib to match Node 6+

---

help/help.txt
package.json
src/cli/commands/monitor.js
src/cli/commands/test.ts
src/lib/plugins/index.ts
src/lib/plugins/types.ts
src/lib/snyk-test/index.js
src/lib/snyk-test/run-test.ts
test/acceptance/cli.acceptance.test.ts

This is done in preparation for getting multiple trees from gradle plugin.
Currently gradle plugin will return multiple test results iff the `--all-subprojects` flag is passed.
We don't support multiple trees for monitor as of yet, because it breaks our upstream handling of projects. so we fail if the argument `--scan-all-subprojects` is passed.

feat: plugin returns multiple trees

---

package.json

Bump to latest parser version that drops node 4

chore: Use new node js parser that drops node 4

---

package.json
src/cli/commands/monitor.ts
src/lib/monitor.ts

Converts Monitor command to Typescript. This is going to be helpful in the light of support for scanning multiple sub-projects, refactoring of the plugin APIs and pinning down the type definitions for plugins and monitors.
The diff is minimal: no conversion to async/await, no thorough types, many modules still use "default exports".
The usual; nothing in the CLI should break.

chore: convert the monitor command to Typescript

---

src/cli/commands/monitor.ts

In preparation for the `--all-sub-projects` feature, convert the `monitor` code from a poorly readable promise chain to async/await syntax.

chore: convert monitor code to async/await

---

package.json

Fixes an issue where parsing of the Gradle project with cyclic deps fails with StackOverflowError.
This also picks up changes introduced in gradle plugin version 2.7.0, but they should not affect anything (a new field with trivially generated data was added to the output, this field is unused so far).
https://snyksec.atlassian.net/browse/BST-575

fix: handle dependency cycles in Gradle projects

---

package.json

Large nuget projects might not have their csproj file next to their obj/project.assets.json file. The paths to each of the files is listed in a properties file that we don't parse yet. Since we don't require the target framework from the csproj, yet, we can stop failing if we can't find the csproj where we expect it. This PR allows such projects to succeed when sending --file=path/to/project.assets.json flag.
https://github.com/snyk/snyk-nuget-plugin/pull/52

fix: do not fail if csproj not found

---

help/help.txt
package.json

Bump the nuget plugin to release improved naming behind the flag `--assets-project-name`
```snyk monitor --file=pathtosln --org=snykorg --assets-project-name```
https://github.com/snyk/snyk-nuget-plugin/pull/50

feat: Release improved project naming for csproj behind a flag

---

src/lib/request/request.js

Improve gzip compression.
On a npm project with Jest this reduces the payload from 1.8MB to 1.5MB, which means it will be accepted by Akamai.

fix: improve gzip compression of the payloads to handle some larger ones

---

src/cli/commands/test.ts
src/lib/detect.ts
test/acceptance/cli.acceptance.test.ts

Currently we display remediation advice even when a non-local package is scanned.
We should not, since the user does not own the package and cannot fix it.
https://snyksec.atlassian.net/browse/BST-591

fix: do not offer remediation advice when scanning a non-local package

---

src/cli/commands/test.ts

Fixes the ugliness (see the screenshot).

fix: newline formatting for the suggestion to use --all-sub-projects

---

package.json

We recently added some extra logic around handling scratch Docker images; unfortunately one of the fields missing from this broke snyk monitor for scratch images only. Bumping the snyk-docker-plugin allows monitor to function correctly.

fix: Add package manager data to scratch images

---

package.json
src/cli/commands/monitor.ts
src/lib/monitor.ts
src/lib/project-metadata/index.ts
src/lib/project-metadata/target-builders/git.ts
src/lib/project-metadata/types.ts
test/monitor-target.test.ts

We are adding git metadata to monitor when sending the payload to snyk.io for grouping CLI projects

feat: add git metadata to monitor payload

---

src/lib/monitor.ts

Improves the error message to make debugging easier.
The existing error just produces `unexpected error: undefined` in the stack trace, which is not helpful.

fix: display monitor error code in the error message

---

package.json
src/lib/snyk-test/index.js
src/lib/snyk-test/legacy.ts
src/lib/snyk-test/nodejs-plugin/index.ts
src/lib/snyk-test/nodejs-plugin/npm-lock-parser.ts
src/lib/snyk-test/nodejs-plugin/npm-modules-parser.ts
src/lib/snyk-test/nodejs/index.ts
test/acceptance/cli.acceptance.test.ts
test/acceptance/fixtures/npm-package-policy/test-graph-result.json
test/acceptance/fixtures/npm-package-with-git-url/test-graph-result.json
test/acceptance/workspaces/npm-package-with-git-url/node_modules/qs/package.json

Effectively the second part of https://github.com/snyk/snyk/pull/459 , with updates
https://snyksec.atlassian.net/browse/BST-582

feat: use depGraph lib for npm and yarn snyk-test path

---

src/lib/protect/apply-patch.js
src/lib/snyk-test/nodejs/index.ts

Fixes a remediation bug introduced by the recent switch to depGraph. (https://github.com/snyk/snyk/commit/a085a05845430254a47b6eddb5066be1e107f3c6)
Injection of remediation-related information into snyk-test response should happen _after_ conversion to the legacy response format.
Additionally: more useful error message when failing to apply a patch.

fix: correct remediation (after switching to dep-graph)

---

docker/Dockerfile.gradle-2.8
docker/Dockerfile.gradle-4.4
docker/Dockerfile.maven-3.5.4
docker/Dockerfile.sbt-0.13.16
docker/Dockerfile.sbt-1.0.4

Because of the license change, Oracle JDK is not available anymore. In order to keep maven docker image working, another version of JDK has to be used.

fix: switch to openjdk

---

src/cli/commands/protect/wizard.js
src/lib/snyk-test/legacy.ts
src/lib/snyk-test/run-test.ts
test/acceptance/cli.acceptance.test.ts
test/acceptance/fixtures/npm-package/test-graph-result.json
test/acceptance/run-test.test.ts

Fixes remediation which got broken in v1.161.2
Remediation relies on annotations added to the test result from the Registry. These annotations are added depending on `payload.modules`, which is a piggybacking field on a request description object. In the latest refactoring, modules were erroneously (and under inverse conditions) assigned to `body.modules`, which broke the refactoring workflow.
Apart from the fix, now there are:
- a test that ensures the annotations are added
- type-checks for Policy, Body and friends
The fix itself is at the bottom of src/lib/snyk-test/run-test.ts
The rest is just tests and typechecks.
`snyk wizard` now forks on snyk-fixtures/npm-lockfiles/goof-yarn (e.g. not offering to fix `braces` which it shouldn't).
The bug was introduced in …

fix: correct remediation broken after last refactoring

---

src/cli/commands/protect/wizard.js
src/cli/index.ts
src/lib/errors/index.ts
src/lib/errors/missing-targetfile-error.ts
src/lib/plugins/nodejs-plugin/index.ts
src/lib/plugins/rubygems/index.ts
test/acceptance/sln-app.test.ts

Add more safe checking before proceeding to process projects via their plugin, if a user runs `snyk test some/path/file` 
We will try to treat it as a package name, then proceed to assume it is `npm` as fallback and send it to the nodejs-plugin which fails as there is no targetFile identified via this path. The user get's a bad error, adding more errors in and with a suggestion that perhaps they meant --file or check for help docs.
Follow the reproduceable steps on https://github.com/snyk/snyk/issues/481
Follow the reproduceable steps on https://github.com/snyk/snyk/issues/481

Feat: Don't assume targetFile is always present & show a user message with a suggestion to help guide

---

src/cli/commands/protect/prompts.js

The current message is confusing; changed it to a more straightforward one.

fix: better wording for the "revisit policy" prompt.

---

src/cli/commands/protect/index.js
src/cli/commands/protect/wizard.js
src/lib/detect.ts
src/lib/package-managers.ts
src/lib/plugins/index.ts
src/lib/snyk-test/index.js
src/lib/types.ts
test/acceptance/cli.acceptance.test.ts

Keep track of supported package managers rather than unsupported ones for wizard, easier to read and less risk of missing to add one into this array

refactor: Keep track of supported wizard package managers instead

---

package.json

We used to scan all gradle subprojects always, and maybe return the result for one (because we thought we will switch to --all-sub-projects as a default soon).
However, there's value in scanning one project only, if requested to do so: it's faster, and won't fail on every subproject if we have trouble scanning only one.
The plugin version bump includes the fix, and a fix for the fix :)

fix: do not scan all Gradle subprojects unless requested

---

src/lib/monitor.ts

As part of the layers work, pass layer information in the monitor flow

feat: pass dockerfileLayers in metadata

---

src/cli/commands/test.ts

Adds the option to set the color of the docker remediation advice message.
src/cli/commands/test.ts
run test --docker goof (even better to add --file=Dockerfile)
Recently we added a new alert as part of the docker remediation advice which provides information about whether or not the os distribution version is supported by Snyk. In order to make it more visible, I added to the code an option to choose a different color from the default. 
https://snyksec.atlassian.net/browse/DC-79

feat: allow passing color for docker cli response

---

src/cli/commands/protect/prompts.js
src/cli/commands/scenario.js
src/cli/commands/unpublished/index.js
src/lib/isolate.js

Just tidying up, removing unused console.logs

chore: drop console.logs

---

package.json

A bug in the oracle linux version detection meant that we were incorrectly remediation oraclelinux-based images. See https://github.com/snyk/snyk-docker-plugin/commit/ed780b61650fd71e5ba59bf13b289b7b0ef67ecd for more detail

fix: oracle linux version detection

---

src/lib/snyk-test/run-test.ts

During refactor the packageManager was accidentally hardcoded to 'npm', setting this back

fix: Use actual package manager on test runs

---

package.json
src/cli/args.ts
src/cli/index.ts
src/lib/analytics.js

Enables output from the Gradle plugin via the `-d` flag.
Drive-by: reduce debug logging spam related to analytics payloads.

fix: enable debug output from Gradle plugin

---

package.json

Removes a debug logging statement accidentally added to `snyk-gradle-plugin` that would pollute the output.

fix: remove incorrect Gradle logging

---

src/cli/args.ts
src/cli/commands/monitor.ts
src/cli/commands/test.ts
src/cli/index.ts

Adds types to the objects produced by args parser (to the extent possible),
The arguments object is quite messy, this is the first step towards making it manageable.

refactor: add types to args parser, simplify the code

---

src/cli/index.ts
src/lib/errors/file-flag-bad-input.ts
src/lib/errors/index.ts
test/acceptance/cli-args.test.ts

Gives nice, human-readable error message, if --file value was passed with space, but now as expected (--file=[filename])
From root folder of this project run command:
`node ./dist/cli/index.js test --file package.json`
[BST-606](https://snyksec.atlassian.net/browse/BST-606)

Make human-readable error message if --file value wasn't passed correctly

---

src/lib/monitor.ts

We want to add branch and project name to the data that we send to analytics.

feat: add branch and pkg name to monitor analytics

---

src/cli/commands/auth/index.ts
src/cli/commands/auth/is-authed.ts

- Refactor auth handling to use `async/await` instead of promises
- Slightly refactor to simplify + for readability
`auth/index.ts`
- Build with `npm run build` & then test out using `snyk auth`

chore: refactor auth to async await

---

src/cli/commands/auth/index.ts
src/cli/commands/auth/is-authed.ts

Revert "chore: refactor auth to async await"

---

package.json

Raises the version of `snyk-docker-plugin` to more accurately parse `Dockerfile` instructions in some edge cases

fix: Improve dockerfile instruction parser

---

package.json

Adds bugfixes to the Gradle plugin to restore the functionality of legacy unocumented `-- --configuration=foo` option and enable proper configuration resolution when scanning from a sub-project.

fix: gradle legacy --configuration flag and scanning from child project

---

help/help.txt

Updates the help to match the rollback in https://github.com/snyk/snyk/pull/563

fix: temporarily remove new Gradle configuration options from help

---

src/cli/commands/help.ts
test/acceptance/cli.acceptance.test.ts

Fix `snyk help` which was broken by https://github.com/snyk/snyk/pull/547; add test.

fix: fix broken `snyk help`

---

help/help.txt
package.json
src/cli/commands/monitor.ts
src/lib/snyk-test/run-test.ts
src/lib/types.ts
test/acceptance/cli.acceptance.test.ts

Restores temporarily downgraded Gradle plugin to add Android config selection support while preserving Gradle 2.x compatibility.
Also, reinstate the advertisement for `--all-sub-projects` flag.

feat: Gradle Android config selection, verified Gradle 2.x support

---

package.json

Better error message (names of missing packages) when scanning Python projects.

fix: better error message when scanning Python projects

---

src/cli/commands/ignore.ts
src/cli/commands/protect/wizard.js
src/lib/errors/misconfigured-auth-in-ci-error.ts

`Wizard` and `Ignore` commands have been doing automated authentication in case of no authentication, this behaviour is different to what test or monitor do - which is to bail out if there is no auth. This PR aims to regulate auth behaviour across all the commands. 
In addition, wording for the CI auth error is changed to 
run 
`snyk test`
`snyk protect`
`snyk monitor`
`snyk ignore`
`snyk wizard`
See that we require authentication.

fix: remove auto authentication on all commands other than auth

---

package.json
src/lib/detect.ts
src/lib/monitor.ts
src/lib/package-managers.ts
src/lib/plugins/index.ts
src/lib/snyk-test/run-test.ts
test/acceptance/cli.acceptance.test.ts
test/acceptance/workspaces/golang-mod/go.mod

Enables go.mod files support for test command via `--file=go.mod` flag. Sending organisation has to be enabled on the backend.
Monitor command will go in soon.
As usual, with the tests.
Running test command on this branch with `--file=go.mod` using entitled organisation.
This change means that go.mod files is scanned and tree is created always, but backend than denies the request if sending organisation is not entitled.
This is not ideal, but I believe it pays off given the temporary nature of the beta release. Otherwise, we would need to create whole new communication flow for feature flag pre-check.

Go Modules support in `snyk test`

---

src/lib/errors/legacy-errors.js
src/lib/protect/patch.js
src/lib/protect/update.js

Most stacktraces are only visible in debug mode, but there were a few that fell through the cracks. This PR fixes this.
`https://github.com/snyk/snyk/blob/master/src/cli/index.ts#L45` will handle most of the errors. But some places were still using the legacy error handling to show errors. Removed the stack from the message, and only logging it in debug mode.

fix: show stacktrace only when in debug mode

---

help/help.txt
src/cli/commands/monitor.ts
src/lib/plugins/nodejs-plugin/npm-modules-parser.ts
src/lib/print-deps.ts
src/lib/snyk-test/run-test.ts
src/lib/types.ts

Experimental undocumented flag `--print-dependencies` for `snyk test`, useful for debugging.

feat: experimental command line flag to print the dependency tree

---

package.json

Moving version to 0.0.0 from unknown and setting default name to base path of the file by bumping snyk-go-plugin module.

fix: name and version in gomodules

---

.releaserc

The naive approach didn't work - apparently `pkg` won't generate a `musl`-based binary when running in a `glibc` env. Needs something deeper, maybe a second publish job that would run in an alpine container?

chore: Revert "fix: add alpine platform to standalone binary release assets"

---

src/cli/commands/protect/index.ts
src/cli/commands/test.ts
src/lib/errors/index.ts
src/lib/print-deps.ts
src/lib/snyk-test/run-test.ts
src/lib/types.ts
tsconfig.json

- Convert patch from `.js` to `.ts`
- Split Options type into base (cli commands), test options & patch options
- Rename TestOptions to Options (not all of them were test specific, most were base CLI options that are exposed to the user)

feat: Convert patch to `.ts` & split option types by command

---

src/cli/commands/monitor.ts
src/lib/errors/connection-timeout-error.ts
src/lib/errors/index.ts
src/lib/errors/monitor-error.ts
src/lib/monitor.ts
src/lib/types.ts

Add custom Monitor & Timeout Error with error code + message
Improving cli error handling + analytics
Fixing errors like this: 
`Server returned unexpected error for the monitor request. Status code: 502, response: undefined` 
=>  `Server returned unexpected error for the monitor request. Status code: 502`

feat: add monitor errors

---

help/help.txt
package.json
src/cli/commands/monitor.ts
src/lib/monitor.ts
src/lib/types.ts
test/acceptance/cli.acceptance.test.ts
test/acceptance/workspaces/npm-package-pruneable/package-lock.json
test/acceptance/workspaces/npm-package-pruneable/package.json

Adds an experimental flag to prune large dependency trees for `snyk monitor` (preserves vulns, can lose some vuln paths).
This is backed up by the new logic in dep-graph: https://github.com/snyk/dep-graph/pull/27
Should be matched by changes in the Registry UI (PR TBD).
Out of scope: snyk test (already converted to DepGraph, will not reap any benefits), snyk wizard / protect (degraded remediation advice; needs more research).
Drive-by: some Typescript definitions.
See dep-graph first.
**if the build is breaking maybe it's because new dep-graph version hasn't been released yet?**
Get a big-tree project (e.g. a npm one requiring jest) and try `snyk monitor`. Compare to `snyk test`.
Temporary stop-gap until we convert monitor to graphs.
https://snyksec.atlassian.net/browse/BST-696 …

feat: pruning of big-trees if a flag is specified

---

src/cli/commands/test.ts

Remove isOutdated remediation advice to display more accurate remediation.
https://snyksec.atlassian.net/browse/BST-697
Remediation advice with isOutdated:
Remediation advice with isOutdated removed prompts users to updgrade deps:

feat: remove isOutdated functionality from snyk test

---

docker/Dockerfile.docker

After making docker images smaller, one necessary `apt-get update` was removed. This PR adds it back.

fix: apt update after adding docker repository

---

.releaserc
scripts/alpine-build.sh

Finding a way to build a good standalone alpine image using `pkg`.
Naive `pkg . -t alpine` generates a broken binary (segfault on a plain alpine image). Generating one inside an alpine container works.

fix: add alpine platform to standalone binary release assets

---

src/lib/monitor.ts

Makes sure we preserve all the additional fields of the tree.

fix: preserve all additional deptree fields when pruning

---

package.json

Fixes a customer issue where dependency variants could not be resolved because our constructed configuration did not scan all of the subprojects to select unambiguous attributes.
(see https://github.com/snyk/snyk-gradle-plugin/pull/81)

fix: scan all Gradle subprojects when computing config attributes

---

.releaserc
scripts/alpine-build.sh

Prior to this change we relied on pkg's default node version, which can change with time. Setting it to the current default to be explicit.
Also, no need for a special way to build the alpine target, reverting the container-building flow.

fix: make sure binaries are built on node8

---

src/lib/snyk-test/run-test.ts

Add more analytics to better monitor failures of:
- docker based projects vs not
- when test is using a `depGraph` vs not

feat: send analytics for docker and depgraph

---

src/lib/snyk-test/run-test.ts

Fix analytics to send `depgraph` meta as a boolean

fix: send depgraph as a bool

---

.travis.yml
dangerfile.js

PoC: Use danger.system checks for PRs
Add dangerfile to check commit messages.
Commit messages will be corrected before merging, they now serve as an illustration of the output.

Add dangerfile

---

src/lib/monitor.ts
src/lib/snyk-test/run-test.ts

Analytics would pick up an non-boolean value for the `isDocker` key sometimes. Fixed.

fix: isDocker is a boolean flag in analytics

---

README.md

When testing the published package, we do not take the `.snyk` policy into account. Instead, testing the GH repo of the CLI.

docs: vulns badge in readme tests the repo

---

README.md

Update the example badge to test the GH repo. Testing the npm package ignores the policy for the time being, providing partial results.

docs: update vuln badge in readme example

---

docker/Dockerfile.python-2
docker/Dockerfile.python-3

Some packages require higher versions to be installed
Some packages need features from newer python versions so Python should be kept up-to-date. The current Python docker image has Python 3.5.3 which is pretty old.
Here is an example error from incompatible packages:
`ERROR: dacite requires Python '>=3.6' but the running Python is 3.5.3`
The Python 2 image was also migrated to use the same format (`FROM python`) to facilitate changes to both images

Upgrade Python3 to 3.7 instead of 3.5

---

src/lib/protect/apply-patch.js
test/fixtures/lodash@4.17.11-vuln.json
test/protect-patch-skip.test.js

Updates the logic for checking whether to apply patch A on dep B to fix vuln C.
Prior to this change, our logic would sometime lead to a misdetection of the following kind:
Patch A is applicable to `pkg@1.0.0`
Dep B is located in node_modules as `pkg@2.0.0`
Vuln C was detected on `pkg@1.0.0`, which was then resolved on the disk as dep B.
This would cause a clash and fail when applying the patch due to version incompatibility.
The fix is a stop-gap measure that validates the version of the dep located in node_modules prior to applying a patch.

fix(protect): only patch when version on disk satisfies vuln

---

docker/Dockerfile.python-2
docker/Dockerfile.python-3

Some python dependencies need a C compiler to be installed
Example (uwsgi):
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-1ow3u21k/uwsgi/setup.py", line 138, in <module>
'Programming Language :: Python :: 3.6',
File "/home/node/snyk/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
return distutils.core.setup(**attrs)
File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
dist.run_commands()
File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
self.run_command(cmd)
File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File …
```

Add build-essential for Python

---

.releaserc

For some reason, nodejs10 alpine build segfaults. Need to investigate, reverting for now.

fix: revert to nodejs8 on standalone binaries

---

src/cli/commands/monitor.ts
src/lib/types.ts

Allow to check for `experimentalDepGraph` feature flag in monitor flow.
[BST-771](https://snyksec.atlassian.net/browse/BST-771)

feat: add check for `experimental-dep-graph`  for monitor

---

src/cli/commands/monitor.ts
src/lib/monitor.ts
src/lib/types.ts
test/acceptance/cli.acceptance.test.ts
test/acceptance/fake-server.js

- behind a feature flag start sending graphs across
- ignore prune flag as it does the same thing as a graph and send to the new endpoint too
Graphs are a more compact format and should improve performance of sending data between services.
- [ticket](https://snyksec.atlassian.net/secure/RapidBoard.jspa?rapidView=58&modal=detail&selectedIssue=BST-773)

feat: Behind FF send graphs to new endpoint + tests

---

help/help.txt

Add `config` to help text command

fix: missing config command in help.txt

---

docker/Dockerfile.sbt-0.13.16
docker/Dockerfile.sbt-1.0.4

Our CLI docker images that include `sbt` were broken for a while due to how we build them:
```
...
Selecting previously unselected package sbt.
(Reading database ... 10366 files and directories currently installed.)
Preparing to unpack sbt.deb ...
Unpacking sbt (1.0.4) ...
Setting up sbt (1.0.4) ...
Creating system group: sbt
Creating system user: sbt in sbt with sbt daemon-user and shell /bin/false
+ apt-get update
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Ign:4 https://dl.bintray.com/sbt/debian  InRelease
Get:5 https://dl.bintray.com/sbt/debian  Release [815 B]
Get:6 https://dl.bintray.com/sbt/debian  Release.gpg [821 B]
Ign:6 …
```

fix: sbt docker images are now buildable

---

src/cli/commands/protect/wizard.js
test/wizard-package-changes.test.ts

Make `prepare` / `prepublish` scripts windows compatible by using `&&` instead of `;`. This will fail the whole script if `snyk-protect` fails.
https://github.com/snyk/snyk/issues/683
https://github.com/snyk/snyk/issues/646

feat: Make prepare/prepublish scripts windows compatible

---

src/lib/errors/failed-to-run-test-error.ts
src/lib/errors/index.ts
src/lib/snyk-test/run-test.ts

Change errors like this:
to this:

fix: Propagate plugin error to users

---

.github/CODEOWNERS

chore: add boost as codeowners

---

src/cli/commands/test/formatters/legacy-format-issue.ts
src/cli/commands/test/index.ts
src/lib/snyk-test/common.ts
src/lib/snyk-test/run-test.ts
test/acceptance/cli.acceptance.test.ts

- convert `src/lib/snyk-test/common.js` to `src/lib/snyk-test/common.ts`
- send ignorePolicy as a query param to server so we can start acting on it in a future PR

feat: Send ignorePolicyOption to the server

---

src/lib/errors/index.ts
src/lib/errors/too-many-vuln-paths.ts
src/lib/monitor.ts
src/lib/prune.ts
src/lib/snyk-test/run-test.ts
src/lib/types.ts

Prune graphs on test if asked to improve perf

feat: prune graph on test if asked

---

src/cli/commands/test/formatters/remediation-based-format-issues.ts

Add vulnerable module info to remediation based formatter

feat: show vulnerable module in actionable remediation

---

help/help.txt
src/cli/args.ts
test/args.test.js

Fixes Gradle subproject arguments that were lost after upgrading Gradle plugin to version 2.x

fix: reinstate Gradle subproject arguments

---

src/cli/commands/monitor.ts
src/lib/module-info/index.ts
src/lib/monitor.ts
src/lib/plugins/index.ts
src/lib/plugins/types.ts
src/lib/print-deps.ts
src/lib/snyk-test/run-test.ts
src/lib/types.ts
test/acceptance/cli.acceptance.test.ts

Fixes `--all-sub-project` flag broken by the Gradle plugin upgrade.
Also, fully use the plugin type definitions from the snyk-cli-interface package.

fix: reinstate --all-sub-project support for Gradle

---

package.json

This package is node8+, downgrade for node 6 support
https://github.com/snyk/snyk/issues/724

fix: downgrade ansi escapes

---

help/help.txt

Update docs for pruning to reference support for `test` and `monitor`

docs: prune flag works on test and monitor

---

help/help.txt
src/cli/commands/monitor.ts
src/lib/monitor.ts
src/lib/project-metadata/types.ts
src/lib/types.ts
test/acceptance/cli.acceptance.test.ts

Add an optional `--remote-repo-url` flag to `snyk monitor` which sets the `remoteUrl` for the target (or overrides it if it was obtained from git). This enables manual specifying of the remote for environments without git configured to support grouping in the web interface.
https://snyksec.atlassian.net/browse/UNICORN-431
Various different types of project:

feat: add --remote-repo-url flag

---

src/cli/commands/policy.ts
test/system/cli.test.ts

Fix execution error of CLI command `snyk policy`. 
The problem was with named export instead default. In addition tests and TypeScript notations added.
Run in terminal `snyk policy`

fix: snyk policy command execution error and missed tests

---

package.json
src/lib/snyk-test/run-test.ts
test/acceptance/cli.acceptance.test.ts
test/acceptance/fake-server.ts
test/acceptance/run-test.test.ts
test/monitor-target.test.ts
test/system/remote-package.test.ts

Fixes the error handling so that we don't get the mysterious "Failed to get vulns" message for incorrect auth.
Drive-by: typescriptify fake-server

fix: proper error handling for snyk test command

---

src/cli/commands/test/formatters/remediation-based-format-issues.ts
test/acceptance/display-test-results.test.ts
test/acceptance/workspaces/ruby-app/test-graph-response-with-remediation.json

- Ignore empty `fixedIn` arrays
- Update test fixture to show a diverse set of remediations
*Before*
*After*

fix: Ignore empty fixedIn arrays

---

package.json
src/cli/commands/auth/index.ts
test/fixtures/pkg-mean-io/npm-shrinkwrap.json
test/fixtures/protect-via-snyk/yarn.lock

Dropped [opn](npmjs.com/package/opn) and made the necessary workarounds to use [open](npmjs.com/package/open) instead.
> [opn](npmjs.com/package/open) was deprecated and renamed to [open](npmjs.com/package/open)
related: [#1679](https://github.com/mozilla/web-ext/pull/1679)

feat: switch to open

---

package.json

Update `snyk-resolve-deps` to not have vulnerable dependency that brought only 1 type into package

feat: update resolve-deps to remove @types/package-json dependancy

---

src/cli/commands/test/formatters/remediation-based-format-issues.ts
src/cli/commands/test/index.ts
src/lib/snyk-test/common.ts
src/lib/snyk-test/legacy.ts
src/lib/types.ts

Sort vulns output for actionable remediation view.

feat: sort all vulns by severity before display

---

package.json

Enables support for lines like `enum34==1.1.6 ; python_version == '2.*'` in requirements.txt

fix: support python_version wildcards in requirements.txt

---

package.json
src/cli/commands/test/formatters/legacy-format-issue.ts
src/cli/commands/test/formatters/remediation-based-format-issues.ts
src/cli/commands/test/index.ts
src/lib/snyk-test/legacy.ts
test/acceptance/display-test-results.test.ts
test/acceptance/workspaces/pip-app-license-issue/requirements.txt
test/acceptance/workspaces/pip-app-license-issue/test-pip-stub-with-legal-instructions.json
test/acceptance/workspaces/ruby-app/test-graph-response-with-legal-instruction.json

Add legal instruction text to old and new formatters
https://snyksec.atlassian.net/browse/BST-804
new formatter
old formatter

feat: add legal instructions

---

src/cli/commands/test/formatters/remediation-based-format-issues.ts

Do not display empty "licenses" block in the new style output.

fix: do not display empty "licenses" block

---

help/help.txt
src/cli/commands/test/formatters/legacy-format-issue.ts
src/cli/commands/test/formatters/remediation-based-format-issues.ts
src/cli/commands/test/index.ts
src/lib/snyk-test/legacy.ts
src/lib/types.ts
test/acceptance/cli.acceptance.test.ts

Updates `--show-vulnerable-paths` flag support.
3 modes now available: `none`, `some` (3 in the legacy mode, 1 in the actionableCliRemediation mode), `all` (up to 1000).
Old `true` is now `some` (default); old `false` is now `none`.
https://snyksec.atlassian.net/browse/FIX-19
snyk help
goof actionableCliRemediation=false show-vulnerable-paths=some (current default)
goof actionableCliRemediation=false show-vulnerable-paths=none
goof actionableCliRemediation=false show-vulnerable-paths=all
goof actionableCliRemediation=true show-vulnerable-paths=some (upcoming default)
goof actionableCliRemediation=true show-vulnerable-paths=none
goof actionableCliRemediation=true show-vulnerable-paths=all

feat: show vulnerable paths: 3 modes, support new test output

---

src/cli/commands/test/formatters/remediation-based-format-issues.ts
test/acceptance/workspaces/pip-app-transitive-vuln/cli-output-actionable-remediation.txt

Fix alignment of legal instructions text

fix: align indent for legal instructions

---

src/cli/commands/test/formatters/remediation-based-format-issues.ts
src/cli/commands/test/index.ts
test/acceptance/workspaces/pip-app-transitive-vuln/cli-output-actionable-remediation.txt

In the new ("actionable") output format, show the test summary at the top.
https://snyksec.atlassian.net/browse/FIX-20
Old-style output is unchanged:
New-style output, before this change:
New-style output, after this change:

feat: in the new output mode, show the test summary first

---

help/help.txt

The information on how to select python2 vs python3 in CLI is not visible for the users.
Let's document it.

fix: document --command option for Python

---

src/cli/commands/test/formatters/remediation-based-format-issues.ts

Unresolved contains both vulns & licenses, so they go accidentally shown in both license and unresolved issues.

fix: Do not show duplicate license issues

---

help/help.txt
src/cli/args.ts
src/lib/plugins/nodejs-plugin/npm-lock-parser.ts
src/lib/plugins/types.ts
test/acceptance/cli.acceptance.test.ts
test/args.test.js

Changes the help text to document the default behavior of the `--strict-out-of-sync` flag and change the options type signature to eliminate the previously present string typed boolean option values `"true" | "false"`.
The current default behavior was manually verified by @darscan and me, by running `snyk test` on a project with a lockfile (npm and yarn). Also I verified that the behavior is still the same.
This will make it easier to get the CocoaPods plugin working. This failed because it had a stricter options definition, not including string typed booleans:
```
src/lib/plugins/index.ts:59:7 - error TS2322: Type 'typeof import("/Users/shaun/dev/work/snyk/repos/snyk/node_modules/@snyk/snyk-cocoapods-plugin/dist/index")' is not assignable to type 'Plugin'.
Types of property 'inspect' are …
```

fix: correctly document behavior of `--strict-out-of-sync` and avoid string typed booleans

---

package.json
src/lib/detect.ts
src/lib/package-managers.ts
src/lib/plugins/index.ts
test/acceptance/cli.acceptance.test.ts
test/acceptance/workspaces/cocoapods-app/Podfile
test/acceptance/workspaces/cocoapods-app/Podfile.lock

This PR integrates the [CocoaPods plugin](https://github.com/snyk/snyk-cocoapods-plugin) to the Snyk CLI:
* adding CocoaPods and its artifacts as supported dependency managers in respective enums
* testing the integration via the acceptance tests
* ~~adding a help text to document the `--strict-out-of-sync` option~~ (postponed to regular release, with auto-detect / without explicit opt-in)
The CocoaPods plugin repo includes some tests, which have fixtures with `Podfile` and `Podfile.lock`. These can be used for `snyk test` or `snyk monitor`

feat: add CocoaPods support

---

.snyk

ignoring SNYK-JS-HTTPSPROXYAGENT-469131 so'll be able to publish new vuln and patch it afterwards

fix: ignoring SNYK-JS-HTTPSPROXYAGENT-469131

---

package.json

Support 'or' operators in marker expressions when parsing `requirements.txt` files.

fix: Improve parsing for marker expressions for python projects

---

test/protect-patch-filter.test.js

- Skips a `test` that is invalid (as it uses the previously released version)
- Needed to unblock release

test: skip test that uses previous bad version

---

package.json

Fix yarn installation of snyk cli with bundled deps
https://github.com/snyk/snyk/issues/796

fix: leave proxy-agent as bundled only to fix yarn install

---

src/cli/commands/test/formatters/legacy-format-issue.ts
src/cli/commands/test/formatters/legal-license-instructions.ts
src/cli/commands/test/formatters/remediation-based-format-issues.ts
src/cli/commands/test/index.ts
src/lib/snyk-test/legacy.ts
test/acceptance/display-test-results.test.ts
test/acceptance/workspaces/pip-app-license-issue/test-pip-stub-with-legal-instructions.json
test/acceptance/workspaces/ruby-app/test-graph-response-with-legal-instruction.json

Add formatting for licenses new data shape and add some extra styles for multi licenses
####### remediation based
####### non-remediation
Relies on https://github.com/snyk/registry/pull/9720/files

feat: Multi licenses formatting

---

package.json

New version of snyk-go-plugin improves go modules error messaging
Bump snyk-go-plugin version
New version improves go modules error messaging
BST-883
https://github.com/snyk/snyk-go-plugin/pull/53

fix: bump snyk-go-plugin to v1.11.1

---

src/cli/commands/monitor.ts
src/cli/commands/test/index.ts
src/lib/plugins/nodejs-plugin/index.ts
src/lib/plugins/rubygems/index.ts
src/lib/snyk-test/run-test.ts
src/lib/types.ts
test/acceptance/cli.acceptance.test.ts

Convert the nodejs plugin code to use the new multi result format in preparation for auto detections and handling of multiple file results.

feat: convert nodejs plugin response to use multi format

---

src/cli/commands/auth/index.ts
src/lib/plugins/rubygems/index.ts
src/lib/plugins/rubygems/inspectors/try-get-spec.ts
src/lib/snyk-test/run-test.ts
test/acceptance/cli.acceptance.test.ts

- Return a dependency tree instead of files from the ruby handler (dropping legacy code)
- Always return an array of results in preparation of allowing scanning multiple of the same project type in one go.

feat: convert ruby to send back multi project result

---

src/cli/commands/protect/wizard.ts
src/lib/project-metadata/target-builders/git.ts

- fix a bug introduced when adding multi scan support for npm, wizard was not prepared to work with this shape for monitoring after completing fix.

fix: wizard support for multi result

---

src/lib/snyk-test/run-test.ts

Fix the lookup for the associated Dockerfile instruction that introduced a package.
The lookup key should include both the package name and version and not just the package name.
Perform a test on an image which is a product of a Dockerfile such as:
```
FROM python:3.7-alpine3.8
RUN apk add --no-cache --update git=2.18.1-r0
```
Expect the **git** vulnerability to be introduced by instruction in the Dockerfile and not by the base image.
Before this fix, the **git** vulnerability was wrongly identified as Introduced by the base image

fix: include package version in vulns lookup

---

src/cli/commands/test/index.ts

For smooth rollout of new issues format with actionable remmediation,
it's useful to monitor how it is used and verify potential edgecases.
Adds an analytics property to recored which format of remediation was used.
Running `snyk test -d` and check analytics output.
It's very hard to test this automatically because of the current test suite. In order to speed up the release, I've decided to be happy with the manual verification.

fix: add analytics for new issues format

---

.releaserc
package.json
src/lib/updater.ts
test/updater.test.js

During the packaging process for the binary adds a `STANDALONE` to the bundle. The `updateCheck` will then bail out early without displaying the upgrade prompt. The aim of this is to prevent users who installed without node being prompted to upgrade `npm`.

feat: removes npm update prompt

---

src/cli/commands/test/formatters/remediation-based-format-issues.ts

Vulns and remediation get filtered by severity in totally different ways and in different places, we can't expect all vuln data to always be present so check for safety first just like we already do in upgrades.
https://snyk.slack.com/archives/CGHELPDHN/p1571407777053500
To test run `snyk test --severity-threshold=high` in the snyk/goof repo.

fix: safely check for vuln info

---

src/lib/protect/apply-patch.js
test/fixtures/hoek@4.2.0-nopatch.json
test/fixtures/hoek@4.2.0-vuln.json
test/fixtures/protect-semver-patch/.snyk
test/fixtures/protect-semver-patch/package-lock.json
test/fixtures/protect-semver-patch/package.json
test/protect-semver-patch.test.ts

A previous commit introduced semver.coerce() on the patch version range, when doing 'snyk protect'.
The problem is that coerce() returns a SemVer type, not a string. The existing code uses semver.satisfies() to check if the given patch applies to the node_module, but since satisfies() expects a string, the patch was not applied since the check never passed.
This resulted in patches being skipped, but we marked them as applied.
The following fix restores the previous functionality of running satisfies() on the patch range but also keeps the existing check of using coerce() while also fixing the output of coerce() to be a string (by reading the version property of the SemVer type). This way we do a check that the patch version is a SemVer range, but we also correctly cover the case where …

fix: match semver patch

---

package.json

Bumping `@snyk/dep-graph` to version `1.13.1`. This change should fix this issue - https://github.com/snyk/dep-graph/commit/0bd6afbfdec6131ea7ca55357930b1edec736d2a

fix: avoid stack overflow with spread operator

---

src/cli/index.ts
src/lib/errors/unsupported-option-combination-error.ts
test/acceptance/cli-args.test.ts

throw error when cli runs with multiple paths or sln and project-name option
run `snyk-local test path1 path2 --project-name="blah"`
https://snyk.zendesk.com/agent/tickets/2401

fix: throw error when cli runs with multiple paths or sln and project-name option

---

package.json

Bump `snyk-nuget-plugin` to enable the fix of https://github.com/snyk/snyk-nuget-plugin/pull/66

fix: don't fail when there are no deps in csproj

---

src/cli/commands/monitor.ts
src/lib/plugins/nodejs-plugin/npm-lock-parser.ts
src/lib/plugins/nodejs-plugin/npm-modules-parser.ts
src/lib/snyk-test/run-test.ts
test/acceptance/cli.acceptance.test.ts
test/acceptance/protect.test.ts
test/missing-node-modules.test.ts
test/package-no-name.test.ts
test/system/remote-package.test.ts

- Introduce external spinner lib gradually

Feat: replace spinner

---

src/cli/index.ts

Generate valid json when `--json` flag is passed, introducing a better spinner created a regression where ansi escape codes were not stripped
*Before*:
`snyk test --json --severity-threshold=high --org=banana 2>error | more`
```
ESC[2KESC[1GESC[2KESC[1GESC[2KESC[1G{
"vulnerabilities": [],
"ok": true,
"dependencyCount": 351,
"org": "banana",
"policy": "# Snyk (https://snyk.io) policy file, patches or ignores known vulnerabilities.\nversion: v1.13.5\nignore: {}\npatch: {}\nsuggest: {}\n",
"isPrivate": true,
"licensesPolicy": {
"severities": {},
"orgLicenseRules": {}
},
"packageManager": "npm",
"ignoreSettings": null,
"summary": "No high severity vulnerabilities",
"severityThreshold": "high",
"filesystemPolicy": true,
"uniqueCount": 0,
"path": "/Users/lili/www/snyk/snyk"
}
```
*After*:
```
{ …
```

fix: strip ansi chars when using --json

---

src/lib/sln/index.ts
test/acceptance/sln-app.test.ts

When unsupported file found upon specifying .sln file, show the folder path, not the .*proj file path
https://github.com/snyk/snyk/issues/841

fix: propagate correct path on sln scan error

---

package.json
src/lib/monitor.ts

DepTree interface in snyk-nodejs-lockfile-parser was aligned with standard used in DepGraph library. Dependency update is marked as a fix to catch hidden issues sooner than later.

fix: Update interface of DepTree from lockfile

---

src/cli/index.ts
src/cli/runtime.ts

- Adds an EOL warning at the end of the CLI output for users that are still using Node v6. 
[src/cli/index.ts:162](https://github.com/YashdalfTheGray/snyk/blob/master/src/cli/index.ts#L162)
- Either spin up a Docker container or use `nvm` to switch to Node.js v6
- Run any `snyk` command
- **Expected** - should see an EOL warning
- Either spin up a Docker container or use `nvm` to switch to a supported version of Node >=v7
- Run any `snyk` command
- **Expected** - should not see an EOL warning
I saw that there was a `runtime` module and an alert system built already. So I simply append a new alert for Node.js v6 using the new [`runtime.isUsingNode6()`](https://github.com/YashdalfTheGray/snyk/blob/master/src/cli/runtime.ts#L11) function. 
#787

add a deprecation warning for users using node v6

---

.releaserc

Fixes an issue where our semantic release build pipeline includes a file intended only for the standalone binary. 
It appears that our semantic release process is adding STANDALONE to all builds of our CLI, not only those intended to be used by pkg.
Run a deployment of the CLI

fix: update blocker on npm

---

src/lib/monitor.ts
src/lib/types.ts
test/acceptance/cli.acceptance.test.ts

- send back any `missingDeps` as a prop to trigger the UI alert to show in the main app
- we already do this for the new monitor path (with graph)
If any deps are labeled as missing, filter them out
and add them as a prop to monitor.
This will display it as an alert in UI

feat: show missing deps for old monitor too

---

src/cli/commands/auth/index.ts
test/system/auth.test.ts

Previously when `snyk auth` failed for any reason we would always show the `AuthFailed` error without checking what the status code was. This PR attempts to make the error message more useful to the user by distinguishing failed authorisation checks from other types of errors (network timeouts etc.)
Run against a local registry, override the endpoint called by `verifyAPI` to return a 502 response (or any other).
There is already handling in place for 502 errors, but coercing all error types into a Not Authorised error resulted in it never being reached
Zendesk

fix: show more meaningful error message for failed auth

---

src/cli/commands/monitor/index.ts
src/lib/errors/authentication-failed-error.ts
src/lib/errors/index.ts
src/lib/feature-flags.ts
test/acceptance/cli-monitor.acceptance.test.ts

Fix auth error if experimental-dep-graph exists.
If cli was invoked with experimental-dep-graph flag and invalid token, user will get error message
Feature flag 'experimental-dep-graph' is not currently enabled for your org, to enable please contact snyk support, cos token wasn't checked for validity and line https://github.com/snyk/snyk/blob/master/src/cli/commands/monitor/index.ts#L91 will return actually 401 Not Authorised, but because we do isFFSupported.ok and it was undefined, user will see totally unrelated error message.

fix: bug with --experimental-dep-graph and wrong auth token

---

src/cli/commands/monitor/index.ts
test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
test/acceptance/fake-server.ts

Use Promise.all on each path passed to monitor.
Added test for monitor using multiple paths.
Run 'snyk monitor ./path1 ./path2 ./path3 ...'
Use DEBUG=* to see each path is now processed asynchronously.
In preparation for auto detect --all-projects feature.
BST-1079

feat: asynchronously process monitor args

---

src/cli/commands/test/formatters/legacy-format-issue.ts
src/cli/commands/test/formatters/remediation-based-format-issues.ts
src/cli/index.ts
src/lib/analytics.js
src/lib/project-metadata/target-builders/git.ts
src/lib/request/types.ts
test/analytics.test.ts

Up until now the analytics payload that we send did not include the organisation specified as the --org parameter.
While normal calls to `snyk test` resulted in the right org, analytics was saving data to the user's default organisation.
This change now correctly collects the specified org so that the data is connected correctly.
Run a local backend and point your snyk CLI there.
Set a breakpoint in `analytics.js` line 8 (to capture the `/cli` API call).
Run `snyk test --org=<some org other than your preferred or default org>`
Notice the organisation is now the one specified by `--org`!
[Report in #boost-asks](https://snyk.slack.com/archives/CFTAUCYQ7/p1574784548361700)
[Jira ticket BST-425](https://snyksec.atlassian.net/browse/BST-425)

feat: analytics include org

---

src/lib/find-files.ts
test/find-files.test.ts
test/fixtures/find-files/README.md

Added find-files module with find function to help search for files.
Added test for find and test fixtures.
Just helper function at the moment, separate PR to integrate with CLI commands and auto detection.
BST-1072

feat: find files func in prep for auto detection

---

.travis.yml
package.json

The `tree-kill` package, introduced by `snyk-sbt-plugin` has a RCE vulnerability. This patch raises the version of `snyk-sbt-plugin` to remove the vulnerability.
See https://github.com/snyk/snyk-sbt-plugin/pull/72 for further information

fix: Remove tree-kill dependency

---

src/lib/errors/invalid-remote-url-error.ts
src/lib/monitor.ts
src/lib/project-metadata/index.ts
src/lib/snyk-test/run-test.ts
test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts

Check that the value passed to --remote-repo-url is a string (it is possible for it to be a boolean otherwise)
Setting the flag with no argument caused the value `true` to be persisted

fix: check that provided remote url is a string

---

src/cli/commands/test/index.ts
test/acceptance/cli-fail-on.test.ts
test/acceptance/workspaces/fail-on/pinnable/vulns-result.json
test/acceptance/workspaces/fail-on/pinnable/vulns.json

Use remediation object when calculating fail-on exit code.
snyk test --fail-on=<all|upgradable|patchable>
Response to customer confusion over exit code and messages shown in CLI
BST-1094

fix: use remediation to calculate fail-on arg

---

.releaserc

The latest release of `pkg`, `4.4.1`, seems to have issues with our usage of require. Rolling back to an older version to unblock the deploy pipeline, until we can address this properly.
zeit/pkg#806
zeit/pkg#807
zeit/pkg#808

fix: unblock deploy pipeline by pinning `pkg`

---

package.json

This patch updates the python plugin, rolling out initial support for `setup.py` files (https://github.com/snyk/snyk-python-plugin/commit/90a41409a8414491e0cd3b3cd60ff911929b6de7) and fixing some issues with package casing (https://github.com/snyk/snyk-python-plugin/commit/07e424bb5c2c4986fd04c07a6fa60c96a864071d)
`snyk-python-plugin` releases https://github.com/snyk/snyk-python-plugin/releases

feat: support setup.py & normalise package casing

---

package.json

We vendored the `tree-kill` dep in `snyk-sbt-plugin` so that we could temporarily patch it to avoid a vulnerability. Now that it has been fixed upstream, the change in `snyk-sbt-plugin` has been reverted, and a new version released with the fixed upstream `tree-kill`.
https://github.com/snyk/snyk-sbt-plugin/pull/73
This patch updates the Snyk CLI with this new release of `snyk-sbt-plugin`.

fix: Remove vendored tree-kill dep

---

src/lib/detect.ts
src/lib/find-files.ts
test/find-files.test.ts

- for every manifest we find we should only return 1 default manifest to process based on project type & which plugin will process it

fix: filter each folder to grab 1 file per project type

---

src/cli/commands/test/index.ts
test/acceptance/cli-fail-on-docker.test.ts
test/acceptance/cli-fail-on.test.ts
test/acceptance/workspaces/fail-on/docker/fixable/vulns-result.json
test/acceptance/workspaces/fail-on/docker/fixable/vulns.json
test/acceptance/workspaces/fail-on/docker/no-fixable/vulns-result.json
test/acceptance/workspaces/fail-on/docker/no-fixable/vulns.json

Add fallback logic to shouldFail, when remediation is not
available use vuln 'isUpgradable' or 'isPatchable'.
Add test for --docker and --fail-on.
Fix use of --fail-on arg with docker in CLI,
snyk test --docker garethr/snyky:alpine --fail-on=upgradable

fix: fail-on arg with docker

---

docker/Dockerfile.maven-3.6.3
docker/Dockerfile.maven-3.6.3_java11

- 3.6.1 is not available use 3.6.3  https://www-eu.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz

fix: use maven 3.6.3 as 3.6.1 is no longer available

---

src/lib/snyk-test/run-test.ts
test/acceptance/cli-test/cli-test.ruby.spec.ts

To match a project on the BE the targetFile must be send only if the plugin exposes it, just like for monitor. This will allow us to always match the same project by name
Original PR that added this: https://github.com/snyk/snyk/pull/662

feat: send targetfile same as for monitor

---

package.json

Bump snyk-python-plugin to introduce a better error when deps are not installed for setup.py

feat: better error for setup.py when deps are not installed

---

src/lib/detect.ts
test/acceptance/cli-test/cli-test.all-projects.spec.ts

Enable pom.xml to be auto detected when` --all-projects` flag is used

feat: auto detect maven pom.xml with --all-projects flag

---

src/cli/commands/protect/wizard.ts
test/fixtures/four-spaces/package.json
test/wizard-process-answers.test.js

Calculates `package.json` indentation when running `snyk wizard`
Fixes https://github.com/snyk/snyk/issues/911
We use to have a default value of 2 as the white indentation number.
This change calculates the indentation used in the package.json file
and uses it when updating the file.

fix: calculate package.json indentation when running snyk wizard

---

src/cli/commands/monitor/index.ts
src/cli/commands/protect/wizard.ts
src/lib/monitor/index.ts
src/lib/plugins/get-multi-plugin-result.ts
src/lib/plugins/get-single-plugin-result.ts
test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
test/acceptance/cli-test/cli-test.acceptance.test.ts

Always work with multiProject results for Monitor, this will be default response for all plugins soon.

feat: work with multi result for monitor always

---

src/cli/commands/monitor/index.ts
src/cli/commands/monitor/process-json-monitor.ts
src/cli/commands/monitor/types.ts

Split out the functionality to handle the monitor response if `--json` flag is set

feat: process monitor json results

---

test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
test/acceptance/cli-wizard/cli-monitor.acceptance.test.ts

Remove some comments, remove unnessesary tests, split out wizard test into it's own

test: Split away wizard acceptance tests

---

src/cli/commands/monitor/process-json-monitor.ts
test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
test/system/cli.test.ts

- attach json object to monitor error response when `--json` flag is used just like we do for `snyk test` so the response is always correctly processed and only valid json is output.
- add tests to verify correct monitor json data is sent on success & error
*Single monitor*
*Multiple monitored* `snyk monitor --json . bundler-app`

fix: monitor --json errors are valid json

---

test/fixtures/oui.json
test/fixtures/scenarios/SC-965.json

Updates test fixtures to point to the correct path for snyk patches. All new snapshots from the past month or so have been using a new patch url.
All the urls were updating using this command:
```
sed -i "s/https:\/\/s3.amazonaws.com\/snyk-rules-pre-repository\/snapshots\/develop\/patches\//https:\/\/snyk-patches.s3.amazonaws.com\//g" **/*.json
```
Check that the change to the urls make sense
If these tests are run as part of the CLI they shouldnt need to be
The update to the urls is part of an effort to delete old snapshot data.
https://www.notion.so/snyk/Cleanup-old-snapshot-publication-code-and-data-96dd26aa28914350a2ed875c43eba4e3

Update fixtures to point to correct patch urls

---

src/cli/args.ts
src/cli/commands/test/formatters/format-test-meta.ts
src/cli/commands/test/index.ts
src/cli/index.ts
src/lib/plugins/get-deps-from-plugin.ts
src/lib/plugins/get-multi-plugin-result.ts
src/lib/snyk-test/index.js
src/lib/snyk-test/legacy.ts
src/lib/snyk-test/run-test.ts
src/lib/types.ts
test/acceptance/cli-args.test.ts
test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
test/acceptance/cli-test/cli-test.all-projects.spec.ts
test/acceptance/workspaces/ruby-app-no-vulns/test-result.json
test/acceptance/workspaces/ruby-app-policy/test-result-cloud-ignore.json
test/acceptance/workspaces/ruby-app-policy/test-result.json
test/acceptance/workspaces/ruby-app-thresholds/test-result-high-severity.json
test/acceptance/workspaces/ruby-app-thresholds/test-result-low-severity.json
test/acceptance/workspaces/ruby-app-thresholds/test-result-medium-severity.json
test/acceptance/workspaces/sbt-simple-struts/legacy-res-json.json

Add support to CLI to auto detect projects in multiple level deep folders.
Added --detection-depth CLI argument to support user supplied folder depth to search.
snyk test --all-projects --detection-depth=2
To detect all projects in current directory and one subfolder.
BST-1118
snyk test test/acceptance/workspaces/large-mono-repo --all-projects --detection-depth=2

feat: multi level auto detect

---

test/fixtures/cli-test-results/qs@1

missed in previous PR due to not having a .json extension
Follow up from #942

chore: fix remaining patch urls

---

help/help.txt

Add experimental options to help text.
Includes --all-projects and --detection-depth to begin with.
snyk help
Allows us to indicate how to use beta features that have not gone GA in the CLI.
BST-1125

feat: add experimental options to help text

---

help/usage.txt
src/cli/args.ts
src/cli/commands/help.ts
test/acceptance/cli-args.test.ts

The current `snyk` cli shows a `usage.txt` help file when no command is given. That `usage.txt` file points to executing `snyk --help` to get more information in the usage. This PR simplifies that and directly shows `help`
Run `snyk` and see if the `help.txt` is displayed by default
Executing `snyk`, `snyk --help` should both display `help.txt`
It's just an improvement, making it a little bit more user friendly.
None. Encountered this on first usage, and wanted to fix it directly. Let me know if you need a github issue.
*before*
*after*
None

feat: switching from usage to help documentation by default

---

.gitignore

Ignore generated reports files to avoid accidentally commiting generated files when using snyk CLI with Docker

fix: Ignore snyk Docker generated reports and result files

---

test/policy-display.test.ts

Allow CLI tests to be run against any snyk API.
Enables us to switch AppVeyor to test against our dev API.
`SNYK_API="......" SNYK_API_KEY="......" npm test`
Will clean up dashboards reporting CLI usage, at the moment AppVeyor clutters these dashboard with each CI run.

fix: allow tests to be run against any snyk API

---

src/cli/commands/auth/index.ts
test/system/cli.test.ts

Increase tap timeout from 300 to 400 due to increased test count we're
regularly hitting this timeout.
npm test:acceptance

fix: increase cli test timeout

---

.travis.yml

Change node version used during travis release job. Semantic release now requires versions >=10.
https://github.com/semantic-release/semantic-release/releases/tag/v16.0.0

fix: use node 10 during travis release

---

src/cli/index.ts

instead of sending full json string of error, only send that there was an error

fix: stop sending full error to bq

---

src/cli/commands/protect/wizard.ts
test/fixtures/basic-npm/answers.json
test/fixtures/basic-npm/package.json
test/wizard-process-answers.test.js

Fix for issue where snyk gets added as a dependency whenever there are version updates to anything in package.json.

fix: snyk always being added as dependency when running wizard

---

help/help.txt
src/lib/plugins/get-deps-from-plugin.ts
test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
test/acceptance/cli-test/cli-test.all-projects.spec.ts

Enable the default detection depths to increase from 1 to 2 folders deep.

feat: increase default levels deep to 2 for `--all-projects`

---

src/cli/commands/protect/wizard.ts
src/cli/commands/version.ts
src/lib/version.ts
test/acceptance/cli-args.test.ts

Fix the `snyk --version` hotload import, which was broken during refactor
https://github.com/snyk/snyk/issues/969

fix: snyk --version

---

package.json

Bumping snyk-docker-plugin (contains a fix for parsing dockerfiles written in lowercase)

fix: correctly parse multistage dockerfiles written in lowercase

---

src/lib/detect.ts
test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
test/acceptance/cli-test/cli-test.all-projects.spec.ts

Auto detect and scan Composer (Php) projects
when `snyk test` or `snyk monitor` is run with
`--all-projects`

feat: enable composer.lock for --all-projects

---

README.md
docker/docker-entrypoint.sh
docker/docker-python-entrypoint.sh

- Setup.py support was added in the python plugin but the image doesn't install the dependencies
- Custom requirements.txt support
- Improve docs / drop repetitive examples
Check the updated README for more examples:
Build the local image from the docker dir:
```docker build -f Dockerfile.python-3  . -t snyk/snyk-cli:python-3-local```
Run on a `setup.py` project:
```
docker run -it -e "SNYK_TOKEN=*******" -e "TARGET_FILE=setup.py" -v "$PWD:/project" snyk/snyk-cli:python-3-local
``` 
https://github.com/snyk/snyk/issues/786
https://github.com/snyk/snyk/issues/332

feat: Support setup.py & Pipfile dependencies in the python docker images

---

docker/docker-entrypoint.sh

Move the `--json` param to directly after the snyk command in case some arguments are being passed down to the language plugin like maven / gradle directly

fix: move --json for  docker cli right after the command

---

src/lib/detect.ts
test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
test/acceptance/cli-test/cli-test.all-projects.spec.ts
test/acceptance/workspaces/mono-repo-project/packages.config
test/acceptance/workspaces/mono-repo-project/paket.dependencies
test/acceptance/workspaces/mono-repo-project/paket.lock

Enables paket projets to be autodetected with the --all-projects option set.

feat: enable paket to be autodetected with --all-projects

---

help/help.txt

Moving --all-projects, --detection-depth and --exclude help test
out of experimental section, and higher up now that this feature
has been released.
`snyk help`

fix: move --all-projects help text

---

src/lib/detect.ts
src/lib/find-files.ts
test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
test/acceptance/cli-test/cli-test.all-projects.spec.ts
test/acceptance/workspaces/mono-repo-project/Pipfile
test/acceptance/workspaces/mono-repo-project/python-app-with-req-file/requirements.txt
test/acceptance/workspaces/mono-repo-project/requirements.txt
test/acceptance/workspaces/monorepo-with-nuget/test/paket-app/paket.dependencies
test/acceptance/workspaces/monorepo-with-nuget/test/paket-app/paket.lock

Adding `Pipfile` and `requirements.txt` to auto-detection w/ `--all-projects`
[BST-1112](https://snyksec.atlassian.net/browse/BST-1112)

Feat: add python to auto detect for `--all-projects`

---

src/lib/snyk-test/run-test.ts

Push `targetFileRelativePath` to `registry` and in turn to `logz`;
This is w.r.t https://github.com/snyk/registry/pull/11380 requirements;

feat: push `targetFileRelativePath` to registry payload

---

package.json
src/lib/snyk-test/run-test.ts

Adds java and maven version to analytics

feat: add java and maven version to analytics

---

src/lib/snyk-test/run-test.ts

Optional chaining operator was forgotten in new analytics path in
lodash.get.
Just fixes wrong object path.

fix: correct object path to mvn and java version

---

README.md

Bringing in a contribution from https://github.com/snyk/snyk/pull/985

fix: fix small typo gradle => docker in the README

---

package.json
src/lib/updater.ts
src/lib/user-config.js
test/updater.test.js

Replaces configstore to a fork from snyk which patches version `3.1.2` to use the latest version of `dot-prop`.
- removing direct deps `update-notifier` and `configstore`
- replace them with forked and published versions under `@snyk` scope `@snyk/configstore` `@snyk/update-notifier`
- Each of the new deps has their version of `dot-prop` raised to `5.2.0`

fix: vuln in transitive pkg of configstore (dot-prop)

---

package.json

Fix the problem caused by https://github.com/snyk/snyk/pull/990 which broke the functionality of `update-notifier`.
The issues was raised on https://github.com/snyk/snyk/issues/991.
Bumping to the latest version of `@snyk/update-notifier` will fix the issue :)

fix: vuln in transitive pkg of configstore (dot-prop) - rc2

---

.travis.yml
test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts

Trying to fix what looks like a **tap** & node **12.16.0** incompatibility, it is probably fine with later versions of tap but we are for using custom forked tap due to legacy issues with TypeScript support & some places still using **tape**
```
/home/travis/.nvm/versions/node/v12.16.0/bin/node[5501]: ../src/node_util.cc:216:static void node::util::WeakReference::DecRef(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `(weak_ref->reference_count_) >= (1)' failed.
```

chore: fix for node 12 assertion error

---

.travis.yml
scripts/check_circleci_status.sh

On releasing CLI we don't care if Windows tests are passing, cos Travis is the one who triggers `semantic release`. This bash script is doing API call to GitHub in order to check are windows test failing.

feat: check Windows tests in Travis

---

package.json

Bumped `snyk-docker-plugin`. This version includes logic that when using `snyk test --docker <docker image>`, if the image doesn't exist locally, it will be pulled if possible and then scanned.
Previously this used to fail and show an error that the image doesn't exist, but still pull the image in the background (without indication).

feat: bump snyk-docker-plugin. Added pull if image isn't local logic

---

src/lib/plugins/nodejs-plugin/npm-lock-parser.ts
test/acceptance/cli-test/cli-test.npm.spec.ts

replaces npm-shrinkwrap.json throw error message when exists as well a package-lock.json file on the same project.
Check https://snyksec.atlassian.net/browse/BST-502

fix: npm-lock-parser npm-shrinkwrap's error msg.

---

help/help.txt

Improve the documentation of `--command` to assign a python version

fix: improved python --command documentation

---

package.json

support scratch images in the snyk-docker-plugin for the dynamic image scanning flow
https://github.com/snyk/snyk-docker-plugin/pull/143
https://github.com/snyk/snyk-docker-plugin/pull/144
npm install, build, then
```node dist/cli/index.js test --docker busybox:1.31.1```
https://www.notion.so/snyk/Improve-how-we-handle-scratch-images-6fe2d0dbb1584c69b2d185a0cee9e976
https://snyksec.atlassian.net/browse/RUN-728

fix: bump snyk-docker-plugin to 2.2.2

---

package.json
test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts

Bumps the version of dep-graph to v1.16.1 to help fix an issue with pruned subdependency labeling
https://github.com/snyk/dep-graph/releases/tag/v1.16.1
A test needed updating as it was incorrectly validating a that a pruned package was given the label when actually, it was the second, non-deps version which is pruned. It also was incorrectly looking for a `dependencies` value on the object when it was actually `deps`.
Here is the correct shape of the data which is tested for.
```
{
"nodeId": "c@1.0.0|1",
"pkgId": "c@1.0.0",
"deps": [{ "nodeId": "v@5.0.0" }],
"info": { "labels": { "scope": "prod" } }
},
{
"nodeId": "c@1.0.0|2",
"pkgId": "c@1.0.0",
"deps": [],
"info": { "labels": { "scope": "prod", "pruned": "true" } }
},
```

fix: bumps dep-graph to v1.16.1

---

src/lib/monitor/index.ts

We are wrongly sending the same analytic twice but this one is in the wrong place. Leave the one tracking graphMonitor correctly in place

fix: only send analytics Monitor Graph as true when appropriate

---

src/cli/commands/auth/index.ts
src/lib/utm.ts
test/system/cli.test.ts

Adds support for reading UTM configuration from environment variables, prefixed with SNYK_UTM_* and supports all 3 UTM options: Source, Medium, Campaign.
When UTM data is available, the authentication (a `snyk auth`) flow will append this data to the query params of the URL that is opened in the browser for authenticating.
Reviewing the auth flow that now gets the UTMs appended to the URL.
To test manually in a cloned repository:
```bash
SNYK_UTM_MEDIUM=test_medium SNYK_UTM_SOURCE=test_source SNYK_UTM_CAMPAIGN=test_campaign node --require ts-node/register src/cli auth
```
and ensure the URL is being opened with the UTMs data as well as shown in the console's stdout from the auth flow.
This allows to better track and monitor sign-ups and registrations with the Snyk CLI.
None

Feat: support UTM in login URL from environment variables

---

src/cli/commands/test/index.ts
src/lib/plugins/convert-single-splugin-res-to-multi-custom.ts
src/lib/plugins/get-deps-from-plugin.ts
src/lib/plugins/get-multi-plugin-result.ts
src/lib/plugins/nodejs-plugin/npm-lock-parser.ts
src/lib/sub-process.ts

Hide the failed project scans behind `-d` for `--all-projects` as it is too noisy.
Add some separate debug contexts for for fancy colours
https://github.com/snyk/snyk/issues/993

feat: silence noisy error behind -d for --all-projects

---

src/cli/runtime.ts
test/runtime.test.ts

- Update our minSupportedRuntime function to no longer consider `6` supported.

feat: use 8 as min supported runtime message

---

package.json

bump snyk-docker-plugin to a version where the image ID we collect is fixed to align with what the dynamic image scanning collects (which is actually the image digest)
```node ./dist/cli/index.js monitor --docker debian --experimental```
https://github.com/snyk/snyk-docker-plugin/pull/164

fix: image static scanning to send correct image ID (digest)

---

help/help.txt
src/cli/args.ts
test/args.test.ts

Adds `--container` alias for `--docker` in CLI
Using `--container` should have the same result as using `--docker`
DC-591

feat: container alias for docker flag

---

src/cli/commands/test/formatters/format-reachability.ts
src/cli/commands/test/formatters/legacy-format-issue.ts
src/cli/commands/test/formatters/remediation-based-format-issues.ts
src/cli/commands/test/index.ts
src/lib/snyk-test/legacy.ts
test/acceptance/display-test-results.test.ts
test/acceptance/workspaces/reachable-vulns/maven/test-dep-graph-response.json
test/reachable-vulns.test.ts

Support reachable vulnerabilities *output* for `snyk test` and `snyk test --json`.
This diff only deals with the test output to include reachability metadata on the vuln output,     Steps to include it as part of the `snyk test` will be pushed as a subsequent PR.
Those will show only if the metadata is returned for out backend services, which are currently protected behind a feature flag.
**This is not the final design of the output, we will iterate**
https://snyksec.atlassian.net/browse/FLOW-162

feat: support reachable vulnerabilities output for `snyk test`

---

package.json

Upgrade Snyk CLI with new nodejs-lockfile-parser

fix: upgrade @snyk/snyk/nodejs-lockfile-parser from 1.17.0 to 1.18.0

---

package.json

All libraries that are used in CLI must remain using min Node.js version >=8 to maintain support. Reverting the ruby-semver change that upgraded this to 10.
snyk/snyk#1060

fix: bump ruby-semver to use min Node 8 instead of 10

---

package.json
src/cli/commands/auth/index.ts
test/system/cli.test.ts

`opn` is deprecated package. Maintainers moved code to `open` package.

feat: switch to use 'open' since 'opn' is deprecated

---

package.json
src/lib/types.ts
test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
test/acceptance/cli-test/cli-test.docker.spec.ts

Upgrade the snyk-docker-plugin to allow this new feature under the --experimental flag.
```bash
snyk test --docker --experimental docker-archive:path/to/archive.tar
snyk monitor --docker --experimental docker-archive:path/to/archive.tar
```
https://github.com/snyk/snyk-docker-plugin/pull/191
Regular scans:
With `--project-name` specified:

feat: enable experimental docker-archive scanning

---

docker/docker-entrypoint.sh

Fixes an error thrown by `jq` when using our Docker images to monitor multiple projects (i.e. using `--all-projects`.
The error thrown by jq is: 
```
jq: error (at <stdin>:737): Cannot index array with string "uri"
```
- Pull down branch
- Build local docker image (`cd docker && docker build -f Dockerfile.docker . -t snyk/snyk-cli:local`
- Monitor a single project via this docker image
- `docker run --rm -e 'SNYK_TOKEN=***-**-**' -e 'MONITOR=true' -v <full-path-to-repo>:/project snyk/snyk-cli:local test -d`
- Monitor a multi project directory via this docker image
- `docker run --rm -e 'SNYK_TOKEN=***-**-**' -e 'MONITOR=true' -v <full-path-to-repo>:/project snyk/snyk-cli:local test --all-projects '--detection-depth=3' -d`
- Confirm that no errors occur and the HTML file for both single …

fix: docker error on monitoring multiple projects

---

src/lib/monitor/index.ts

Add call graph metrics to `snyk monitor`

feat: add monitor call graph metrics

---

.circleci/config.yml

Updated the CircleCi step where it invoked `test` incorrectly;
[Slack thread](https://snyk.slack.com/archives/CFTAUCYQ7/p1589208414100000)

fix: updated test command so Circle will test properly

---

package.json
src/cli/args.ts

Enable mvn plugin to log when running the cli with `DEBUG=snyk-mvn-plugin snyk monitor --scan-all-unmanaged -d` just like we do for gradle plugin
https://github.com/snyk/snyk-mvn-plugin/pull/65

fix: enable mvn plugin logging

---

src/cli/commands/test/index.ts
src/cli/commands/test/utils.ts
test/commands/test/utils.test.ts

- [ X] Ready for review
- [ X] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ X] Reviewed by Snyk internal team
When we have a multi project the path we return back from the CLI is correct only for the first (master) project.
It came from an on-call ticket where the customer was trying to snyk-to-html the results from snyk test and he saw:
After the fix the page looks like that:

Snyk test results contain wrong path if scanning a multi-module project

---

package.json

CLI command is `--skip-unresolved` but the legacy alias for python plugin was `--allow-missing`, drop suggesting the older alias and suggest the new one only.

fix: suggest --skip-unresolved for python test

---

package.json
src/lib/updater.ts
src/lib/user-config.ts
test/updater.test.ts

Undo the workaround added in #990, as upstream have fixed the issues. Their major version bumps are mostly about dropping support for older node.

feat: switch back to upstream versions of forks

---

src/cli/args.ts
src/cli/index.ts
src/cli/modes.ts
test/args.test.ts
test/modes.test.ts

This is the first step to create a "snyk container test" or "snyk container monitor" commands that doesn't require Docker engine running. Although it's not relevant to all users, more flexibility here is both more technically correct, future proofs our technology, and is important to several separate strategic partners.
Include the command `container` that is an alias for the option `--docker`. The command accepts the sub commands `test` and `monitor`. 
Run the commands `snyk container test <image> ...` and `snyk container monitor <image> ...`. After check `src/cli/args.ts` where the `mode` concept was introduced. 
You should be able to run the command `snyk container test <image> ...`, and get the same result when running the command `snyk test --docker <image> ...`.
The same should work …

feat: include command "container" as alias for option "--docker"

---

src/lib/container/index.ts
test/container.test.ts

Adds checking if `imageName` undefined for non container projects.

fix: add check if image name undefined

---

package.json

`@types` packages are only needed at compile time. `typescript` is a `devDependency`, so I'm reasonably sure we're not compiling with only prod deps installed, so this can definitely be a `devDependency`.
Aiming to reduce bundle size.

feat: @types are not prod dependencies

---

package.json

Upgrade a plugin. The upgrade brings the removal of two huge dependencies, giving us a 16MB smaller (pre-compression) bundle size / install size.

feat: upgrade cocoapods plugin (bundle shrink)

---

help/container.txt
src/cli/args.ts
src/cli/modes.ts
test/args.test.ts
test/modes.test.ts

Allow mode displays its custom help message. It follows up work to create a "snyk container test" and "snyk container monitor" that doesn't require Docker engine running.
It allows all `modes` to have a custom help message. Also it includes a help message for `snyk container` modes. 
Execute the command `snyk container --help` to see the custom help message. After taking a look at files `src/cli/args.ts` and `src/cli/modes.ts`.
It's good to notice that the previous behaviour for help command was not changed. `snyk test --help` and `snyk test --help=config` still having the same behaviour that it had before.
For manual testing you should run `snyk container`, `snyk container --help` and `snyk container test -h` and the result should be the custom help message for the container, as you can …

feat: allow a mode displays its custom help message

---

help/help.txt
src/cli/args.ts
src/cli/commands/auth/index.ts
src/cli/commands/test/index.ts
src/cli/commands/types.ts
src/cli/index.ts
src/lib/errors/json-file-output-bad-input-error.ts
src/lib/json-file-output.ts
test/acceptance/cli-args.test.ts
test/acceptance/cli-json-file-output.test.ts
test/acceptance/cli-test/cli-test.all-projects.spec.ts
test/acceptance/cli-test/cli-test.generic.spec.ts
test/acceptance/cli-test/cli-test.gradle.spec.ts
test/acceptance/cli-test/cli-test.npm.spec.ts
test/acceptance/cli-test/cli-test.ruby.spec.ts
test/cli-command-types.test.ts
test/json-file-output.test.ts
test/system/remote-package.test.ts

This allows a user to directly save JSON format output to a file as specified by the --json-file-output=<file> parameter, regardless of whether they are using the human-readable or json output. The primary use-case of this is to enable users (and Snyk CI plugins) to simultaneously get the human readable output while saving a JSON format output to a file for other purposes (for example, generating a report).
Please take a look at the code and advise as to testing best-practices. I will then include appropriate tests for this PR.
Say you want to save the JSON output to a file called "snyk-output.json" in the current directory. You could then run snyk test --json-file-output=snyk-output.json which should do a normal snyk test and generate the human-readable output to stdout but at the same …

feat: add --json-file-output option for snyk test

---

src/cli/commands/monitor/index.ts
src/lib/analytics.js
src/lib/monitor/dev-count-analysis.ts
src/lib/monitor/index.ts
test/analytics.test.ts
test/dev-count-analysis.jest-test.ts

Upon `snyk monitor`, run git log in the direcotry `snyk monitor` is run; this means that that we are assuming it is run from a directory which is in a git repo. We git log only the last 90 days. Look at the hash(author email) and the commit timestamps. We create a map of (hashed author email) -> (latest commit timestamp for that author). Send that along with the API call to Snyk that is already used in monitor.
This is for the "contributing developer" count feature.
HAMMER-36
https://github.com/snyk/registry/pull/13742

feat: add lib for dev count

---

src/lib/monitor/index.ts

Split out monitor depTree to it's own function in preparation for CLI gradle dep-graph support.
Just moving code around.

chore: split out monitor depTree to it's own func

---

src/lib/options-validator.ts
src/lib/reachable-vulns.ts
test/reachable-vulns.test.ts

Adding support of `--all-projects` flag altogether with `--reachable-vulns` for `snyk test` CLI command
Run in CLI `snyk test --all-projects --reachable-vulns`

feat: --reachable-vulns supports --all-projects flag in CLI

---

src/cli/commands/auth/index.ts
src/lib/is-docker.ts
src/lib/query-strings.ts
test/is-docker.test.ts
test/system/cli.test.ts

- adding 2 query params to `snyk-auth` web page
- `os` indicate the os the user have.
- `docker` indicate if the `snyk-auth` command run in docker.
- run snyk-auth in the repo and see the url is expected
- run this docker file with `docker build -f Dockerfile .` inside snyk repo and see the isDocker argument return as `true`
```
FROM node:10-slim
MAINTAINER Koby Ltd
RUN mkdir /home/kobyownz
WORKDIR /home/kobyownz
RUN pwd
COPY . .
RUN rm -rf node_modules
RUN ls
RUN npm i
RUN npm run snyk-auth
CMD ["sleep", "6000"]
```
[Jira Ticket- TAILWIND-119 ](https://snyksec.atlassian.net/browse/TAILWIND-119)

feat: add os and isDocker query strings

---

.github/CODEOWNERS

Adds 🔨  as co-codeowners for the CLI

chore: add hammer team as codeowners on CLI

---

package.json

snyk-docker-plugin v3.10.0 adds OCI archive scanning support in the `experimental` container flow.
Update to `snyk-docker-plugin` v3.10.0, which adds OCI archive scanning support in the `experimental` container flow.
Manually tested with `snyk container test --experimental` & `snyk container monitor --experimental` for different archives: oci, docker-archive & distroless images.
[RUN-592](https://snyksec.atlassian.net/browse/RUN-592)

feat: Update snyk-docker-plugin for OCI images support

---

config.default.json
src/lib/config.ts
src/lib/monitor/index.ts
src/lib/prune.ts
src/lib/snyk-test/run-test.ts

The goal of this pr is to remove the previously logic that did not make much sense,
and makes the way that we prune depGraphs more accurate

fix: prune depGraph paths accuracy

---

package.json

Bumping snyk docker progin lib to v3.12.0, which added error handling when an oci archive provided with docker-archive manifest.
[RUN-1003](https://snyksec.atlassian.net/browse/RUN-1003)

fix: Bump snyk docker plugin to handle errors

---

package.json

Old version drops support for node 4 and 5, which doesn't
affect us all that much.

feat: upgrade debug

---

src/cli/commands/monitor/index.ts

We are accidentally printing deps twice

fix: remove duplicated call to maybePrintDeps

---

src/cli/modes.ts
test/args.test.ts
test/modes.test.ts

Continue the efforts to have "snyk container test" or "snyk container monitor" commands that doesn't require Docker engine running. In this step we make these commands always use the static scan. Although it's not relevant to all users, more flexibility here is both more technically correct, future proofs our technology, and is important to several separate strategic partners.
It makes the command `snyk container` always use the static scan.
The result for `snyk container test <image>...` has to be equal `snyk test --docker --experimental <image>...`
Run the following command and compare the output. It has to me the same:
- `snyk container test <image>...`
- `snyk test --docker --experimental <image>...`
- [RUN-986](https://snyksec.atlassian.net/browse/RUN-986)
- …

fix: make container commands use always static scan

---

package.json

It updates the `snyk-docker-plugin` verstion to `3.12.2`.
You should run `snyk test --docker <centos-image>` and get the same result when run `snyk test --docker --experimental <centos-image>`.
Fix some inconsistency in the static analysis.
- [RUN-1005](https://snyksec.atlassian.net/browse/RUN-1005)

fix: upgrade snky-docker-plugin

---

src/cli/args.ts
src/cli/commands/ignore.ts
src/cli/commands/types.ts
src/cli/index.ts

Fixes an issue where if one of the CLI commands (specifically ignore) does not return a CommandResult | string, but rather returns nothing, causes a failure.
The `ignore` command does not return anything when it runs successfully and that was causing a failure in runCommand when we tried to .toString() the result.
- HAMMER-70

Handle undefined return from CLI command

---

package.json

Brings snyk-gradle-plugin support of dep-graph and drop the usage of dep-tree.
- Solve OOM Issues
- get correct project version (no longer 0.0.0 by default) 
- Performance Improvements
- Allow projects of large scale to be imported

feat: gradle support of depgraph

---

.github/CODEOWNERS

now boost and hammer are codeowners

chore: fix codeowners

---

src/cli/args.ts

When using `--all-projects` the debug is not showing with `-d` making it hard to see errors which we silence on purpose to not spam the user. Expose the rleevant debug context so it is visible with `-d`
run `snyk test` on an out of sync yarn project with and without `--all-projects`
*Before*
*After*

feat: expose snyk-test debug context

---

src/lib/config.ts
src/lib/errors/invalid-endpoint-config-error.ts
test/endpoint-config.test.ts

Adds a info log that `endpoint` is set in config, and adds a URL validation.
This fixes 2 use cases:
- users having `endpoint` in snyk config, without even realising it's there: CLI now announces it's trying to connect somewhere non-standard
- user having invalid `endpoint` in snyk config, resulting in `$ snyk auth` URL being `null//null/login?token=<token>`
https://snyksec.atlassian.net/browse/HAMMER-40

Show message when using a custom API endpoint and validate its value

---

src/cli/commands/monitor/index.ts
src/cli/commands/protect/index.ts
src/cli/commands/protect/wizard.ts
src/lib/monitor/index.ts
src/lib/plugins/nodejs-plugin/npm-modules-parser.ts
src/lib/policy/find-and-load-policy.ts
src/lib/policy/index.ts
src/lib/policy/pluck-policies.ts
src/lib/snyk-test/run-test.ts
src/lib/types.ts
test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts

- Unify how we find & load policies for all the 4 places where we need to do the exact same thing.
- add some types
- update pluck policies to always return an string or string array
There is a policy handling but with `--all-project` , `gradle sub-projects` and `--file` where we look for policy in the root of where the command is run and not next to the manifest, which can be exposed in a test and fixed in a PR after this initial refactor so that the change is made in one place not 4.

feat: unify policy handling & plucking

---

src/cli/commands/monitor/formatters/format-monitor-response.ts
src/cli/commands/test/index.ts
test/acceptance/cli-test/cli-test.gradle.spec.ts

- show the gradle `--all-rub-projects` suggestion when running `test` as well ` monitor`
- add the wording `Tip:` 
run `snyk test --file-build.gradle` on a gradle project with subprojects and `snyk monitor --file-build.gradle` 
*Before* only monitor showed the suggestion
*After* test also shows the suggestion

fix: show gradle suggestion on test too

---

src/lib/package-managers.ts

Dropping gradle from experimental monitor.
Why? It's unused there, snyk-gradle-plugin sends a graph by default so there is no reason to keep it on experimental monitor.

refactor: drop unused gradle from experimental

---

src/lib/monitor/index.ts
src/lib/policy/find-and-load-policy.ts
src/lib/snyk-test/run-test.ts
test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
test/acceptance/cli-test/cli-test.all-projects.spec.ts
test/acceptance/cli-test/cli-test.gradle.spec.ts
test/acceptance/cli-test/cli-test.yarn.spec.ts
test/acceptance/workspaces/gradle-multi-project/settings.gradle
test/acceptance/workspaces/gradle-multi-project/subproj/.snyk
test/acceptance/workspaces/gradle-multi-project/subproj/build.gradle
test/acceptance/workspaces/mono-repo-with-ignores/package-lock.json
test/acceptance/workspaces/mono-repo-with-ignores/package.json
test/acceptance/workspaces/mono-repo-with-ignores/vulnerable/.snyk
test/acceptance/workspaces/mono-repo-with-ignores/vulnerable/package-lock.json
test/acceptance/workspaces/mono-repo-with-ignores/vulnerable/package.json
test/acceptance/workspaces/yarn-package/.snyk
test/package-no-name.test.ts

Show that when triggering a test with `--file` or `--all-project` the policy is not discovered as we expect to find it in the `root` which is where the command is run and it should instead be where the manifest was discovered.
While working on yarn workspaces feature test noticed the policy from the workspaces were not being used or sent.

fix: policies to be correctly picked up from nested scans

---

package.json
src/cli/commands/help.ts
src/cli/commands/monitor/index.ts
src/cli/commands/protect/wizard.ts
src/lib/detect.ts
src/lib/plugins/nodejs-plugin/npm-modules-parser.ts
src/lib/plugins/rubygems/inspectors/try-get-spec.ts
src/lib/protect/patch.js
src/lib/protect/write-patch-flag.js
test/missing-node-modules.test.ts
test/policy-display.test.ts
test/protect-apply-same-patch-again.test.js
test/protect-fail.test.js
test/protect-patch-same-pkg.test.js
test/wizard-package-changes.test.ts
test/wizard-prepare.test.js
test/wizard-prepublish.test.js
test/wizard-process-answers.test.js

Part of the effort to slim down the dependency tree in CLI, this PR removes then-fs and replaces it with a native fs module. Most of the usage don't even need the promisified version, but is fine with a sync one.
Added two TODO on pieces I've found could be improved.

feat: remove then-fs package

---

.github/CODEOWNERS

Make @snyk/flow the owners of the reachability formatters since Flow owns reachable vulns.

chore: make Flow code owner for reachability formatters

---

src/cli/commands/test/formatters/format-reachability.ts
src/cli/commands/test/formatters/remediation-based-format-issues.ts
src/cli/commands/test/formatters/types.ts
src/lib/snyk-test/legacy.ts
test/reachable-vulns.test.ts

This change set makes the `test` command show a number of sample call paths from the user code to the affected function of each vulnerability, if any could be found. Currently this shows only 2 compressed code paths. A compressed call path shows only the 2 leading an 2 trailing function calls.
`src/cli/commands/test/formatters/remediation-based-format-issues.ts:518` is where we build the output message. The most interesting functions are `formatReachablePaths` and `reachablePathsTemplate`.
Clone a maven project (https://github.com/snyk-flow/JMinerGuide is a good candidate), build it, and run this version of the `snyk` CLI with `test --reachable-vulns` from the project root. You need to have reachable vulns enabled on your account.
https://snyksec.atlassian.net/browse/FLOW-296

feat: show reachable paths for supported projects

---

src/cli/commands/constants.ts
src/cli/commands/protect/prompts.ts
src/cli/commands/test/formatters/format-reachability.ts
src/cli/commands/test/formatters/legacy-format-issue.ts
src/cli/commands/test/formatters/remediation-based-format-issues.ts
src/lib/snyk-test/legacy.ts

We renamed the field in the result returned by the server to avoid awkward looking code like `reachablePaths.reachablePaths`. This changes the type definition to use the new name.

chore: rename reachable paths field

---

package.json

Missing `lodash` dep in nodejs-lockfile-parser module

fix: missing dep in nodejs-lockfile-parser

---

package.json
src/cli/index.ts
src/cli/modes.ts
src/lib/types.ts
test/modes.test.ts

Adding a flag to activate parser based application scanning.
There are a few special cases in the moment:
- Using `snyk --docker --experimental` we do not want to allow `--json` output when requesting application scanning
- Using the `snyk container` alias we don't want to throw an error but rather only show the image project when `--json` output is requested. So the alias is:
```
snyk container test/monitor -> snyk --docker --experimental --app-vulns test/monitor
snyk container test/monitor --json -> snyk --docker --experimental --json test/monitor 
```
See the slack threads or reach out to me if it is still confusing.
Add a flag next to the experimental flag to the CLI
See also this slack thread:  https://snyk.slack.com/archives/CLB5WDQRF/p1593610184000200?thread_ts=1592825658.001300&cid …

fix: Adding a flag to activate applications scans for container images

---

package.json

Remove lodash main package from nodejs-lockfile-parser

fix: remove lodash main package from nodejs-lockfile-parser

---

src/lib/snyk-test/legacy.ts

Include projectId in the JSON output.

feat: if matched display the project ID

---

src/cli/commands/test/index.ts

Skip suggesting `--all-projects` when scanning a yarn workspace as it essentially does the same thing.
https://github.com/snyk/snyk/issues/350#issuecomment-655571961

fix: skip --all-projects suggestion when a yarn workspace

---

package.json

Add support of depgraph to **gomodules**, drop deptree and finally gets rid of the OutOfMemory issues problem

feat: add gomodules support depgraph, drop deptree

---

package.json
src/cli/args.ts
src/lib/container/index.ts
test/args.test.ts
test/container.test.ts

Increase the tool flexibility allowing the user choose a location on disk with the best storage characteristics for storage images during the static analysis process.
It captures the option `imageSavePath` from env var or configured via `snyk config` to allow the `container` static analysis flow to store the downloaded image in a custom path given by the user.
Take a look at `args.ts` file. 
1. Run the command `snyk container test nginx:latest` to check the tool behaviour without the new option.
2. `SNYK_IMAGE_SAVE_PATH=./your/custom/path snyk container test nginx:latest` and check if the result was the same as the previous command. Also the path `./your/custom/path` would be created and it has to be empty.
- [RUN-582](https://snyksec.atlassian.net/browse/RUN-582)

fix: increase tool flexibility for container static analysis

---

help/help.txt
package.json
src/cli/args.ts
src/lib/monitor/index.ts
src/lib/snyk-test/run-test.ts
src/lib/types.ts

This is meant to improve the experience around reachable vulns by:
- giving control to the CLI on how long the call graph generator can run;
- running the user command (e.g. monitor, test) even if the call graph generation failed;
- allowing for better error messages is the call graph generation fails.
Merge after https://github.com/snyk/snyk-cli-interface/pull/36 and https://github.com/snyk/snyk-mvn-plugin/pull/73, and after updating the dependencies to the appropriate versions.
https://snyksec.atlassian.net/browse/FLOW-336
Running with a timeout:
Running with a timeout and passing `-d`:

fix: improve reliability around call graph generation

---

src/lib/error-format.ts
src/lib/monitor/index.ts
src/lib/snyk-test/run-test.ts
test/error-format.test.ts

Since the call graph error messages can get pretty big, abridge them to something more manageable. This keep the beginning, and end of the message since, presumably, that's where the most important details are.

fix: abridge call graph creation error messages in analytics

---

.circleci/config.yml
.github/workflows/smoke-tests.yml
test/smoke/.shellspec
test/smoke/install-shellspec-win.sh
test/smoke/install-snyk-binary-win.sh
test/smoke/run-shellspec-win.sh
test/smoke/spec/snyk_basic_spec.sh
test/smoke/spec/snyk_test_spec.sh
test/smoke/spec/spec_helper.sh

Run a production check against CLI distribution channels every hour

feat: smoke tests

---

src/lib/plugins/nodejs-plugin/yarn-workspaces-parser.ts

Pass `dev` which is the property from `--dev` option passed to CLI in a workspace workflow

fix: pass --dev to yarn workspace scan

---

src/lib/snyk-test/run-test.ts

When modules count is not provided we need to count the packages from graph ourselves. Fixing a bug where the calculation was incorrect and returned `1` most of the time.
Repro:
run `snyk test --yarn-workspaces` for some reason it only affects this flow.
Fixed:

fix: correctly count graph packages

---

docker/docker-python-entrypoint.sh

It allows the user to specify a -f `Pipfile` when running the CLI in a containerized environment.
Also, fix issues with automatically detecting a `setup.py` file and installing its dependencies, but only if no `-f` was provided.

feat: support pipfile on containerized cli

---

src/cli/commands/test/index.ts
src/lib/api-token.ts
src/lib/snyk-test/run-test.ts
src/lib/types.ts
test/acceptance/docker-token.test.ts
test/acceptance/fake-server.ts

Adding support for using `snyk test --docker` without an API key, using a JWT generated by Docker.
Removing the existing api key and setting an env var `SNYK_DOCKER_TOKEN`.
An alternative test endpoint should be called - `docker-jwt/test-dep-graph`.
Note - the entire flow will not work until we deploy the changes to the relevant endpoint.

feat: Support using Docker JWT token for snyk test

---

.circleci/config.yml
test/smoke/README.md
test/smoke/setup-alias-for-snyk.sh
test/smoke/spec/snyk_basic_spec.sh

Replaced the "Common" step with "Smoke tests". It's using the same spec files as our GitHub Action smoke tests.
Also simplified the dependency graph:

chore(test): use shellspec for regression test

---

.circleci/config.yml

[Missing osslsigncode](https://app.circleci.com/pipelines/github/snyk/snyk/1576/workflows/5d9ffe13-b75a-4cde-b1c1-e229516a3953/jobs/7778) for Windows binary signing

chore: install osslsigncode in release step

---

src/cli/commands/protect/index.ts
test/acceptance/cli-protect-no-vulns-to-patch.test.ts
test/acceptance/cli-protect.test.ts

Prevents `snyk protect` from failing if no vulnerabilities were found.
Without this fix, if the project didn't have vulns it would fail with
```
'error-message': 'Code is already patched',
error: 'CustomError: Code is already patched\n' +
'    at patch (/Users/andrejasiskis/workspace/snyk/snyk-cli/src/cli/commands/protect/index.ts:92:17)\n' +
'    at processTicksAndRejections (internal/process/task_queues.js:94:5)\n' +
'    at runCommand (/Users/andrejasiskis/workspace/snyk/snyk-cli/src/cli/index.ts:49:25)\n' +
'    at main (/Users/andrejasiskis/workspace/snyk/snyk-cli/src/cli/index.ts:288:11)',
```

fix: protect will not fail when there are not vulns to patch

---

package.json

In order to prevent too long command, transfer classpath through a file in a new version of snyk-mvn-plugin
How should this be manually tested?
Use your local installation of snyk and run snyk test/monitor command with --reachable.
https://github.com/snyk/snyk-mvn-plugin/pull/77
snyk/java-call-graph-builder#25
snyk/java-call-graph-generator#24
One more fix of the fix was added:
https://github.com/snyk/snyk-mvn-plugin/pull/78
https://github.com/snyk/snyk-mvn-plugin/pull/78

fix: transfer classpath via file

---

package.json
test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
test/acceptance/cli-test/cli-test.acceptance.test.ts

Seeing this from time to time:
```
1) test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts test count !== plan:
test count !== plan
+ expected - actual
-27 // <- variable, so I suspect a race-condition of some sort
+1
```
Couldn't figure out the actual cause here.
Added tons of `await` `t.end` and `t.plan` all over, but that still didn't help. Tried adding a sleep between steps, still didn't solve the issue. Most of the time, there was no helpful output coming from the node-tap failures/errors. It's a complicated test  setup, so not really surprised with the issues, but it work reliably on non-windows pipelines.
Wrapped those two tests in an `if` to turn them off on windows. You need to see PR changes with whitespace ignored …

chore(test): fix flaky acceptance test

---

src/lib/snyk-test/index.js
src/lib/snyk-test/run-test.ts
test/acceptance/run-test.test.ts

Update the import/exports for runTest()

chore: update run test exports to modules syntax

---

.gitignore
src/cli/commands/monitor/index.ts
src/cli/commands/test/index.ts
src/lib/plugins/get-deps-from-plugin.ts
src/lib/plugins/get-multi-plugin-result.ts
src/lib/plugins/nodejs-plugin/npm-modules-parser.ts
src/lib/snyk-test/run-test.ts
test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
test/acceptance/cli-test/cli-test.all-projects.spec.ts

- Collect failed dependency extractions with `--all-projects` and propagate it higher up.
- For `monitor` these are now propagated all the way and will appear in output + json output. This may affect the existing error code as previously we silently skipped failure like these but not failures to get vulnerabilities during monitor or when a path test failed. So it was inconsistent.
- For test more work / refactor needed to get these to the output & json so for now warning the user & providing instructions how to see the error with `-d`
https://github.com/snyk/snyk/compare/fix/throw-erorr-if-all-tests-failed?expand=1#diff-e4ec2ebbae5004d31be7a5b680580a46R42
You can use `cd snyk/test/acceptance/workspaces && snyk test --all-projects` and `cd snyk/test/acceptance/workspaces && snyk monitor …

fix: propagate failed scans with --all-projects

---

src/cli/args.ts
src/lib/analytics-sources.ts
src/lib/analytics.js
src/lib/types.ts
test/analytics-sources.test.ts
test/analytics.test.ts

This PR adds an integrationName and integrationVersion optional parameters to the Analytics.
We are collecting Snyk CLI usage in our official integrations
We distinguish them by either:
- Setting integrationNameHeader or integrationVersionHeader in environment when CLI is run
- passing an --integration-name or --integration-version flags on CLI invocation
Integration name is validated with a list

Capture snyk integration name

---

src/lib/types.ts

Commenting out from SupportedCliCommands enum as it doesn't support argv._ yet.
snyk auth
Breaking CLI auth command since v1.370.0

fix: snyk auth command

---

help/iac.txt

Remove `file` flag from IaC help file

fix: remove file flag from IaC help

---

.gitignore
src/cli/commands/monitor/formatters/format-monitor-response.ts
src/cli/commands/monitor/index.ts
src/cli/commands/test/index.ts
src/lib/detect.ts
src/lib/find-files.ts
src/lib/plugins/get-deps-from-plugin.ts
test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
test/acceptance/cli-test/cli-test.acceptance.test.ts
test/acceptance/cli-test/cli-test.all-projects.spec.ts
test/acceptance/workspaces/gradle-monorepo/package-lock.json
test/acceptance/workspaces/gradle-monorepo/package.json
test/acceptance/workspaces/gradle-monorepo/settings.gradle
test/acceptance/workspaces/gradle-monorepo/subproj/.snyk
test/acceptance/workspaces/gradle-monorepo/subproj/build.gradle
test/acceptance/workspaces/large-mono-repo/gradle-app/build.gradle
test/acceptance/workspaces/large-mono-repo/gradle-multi-project/settings.gradle
test/acceptance/workspaces/large-mono-repo/gradle-multi-project/subproj/.snyk
test/acceptance/workspaces/large-mono-repo/gradle-multi-project/subproj/build.gradle
test/find-files.test.ts

[x] Add monitor test
[x] Update the `test --all-projects` to assert `allSubProjects` is passed
- Scan `build.gradle` files behind `--all-projects` flag with an implied `--all-sub-projects` to scan everything at once.
- Update the `find()` function to only detect root level `build.gradle` files for projects and not scan any nested files unnecessarily
https://github.com/snyk/snyk/compare/feat/enable-gradle-all-projects?expand=1#diff-46067fcff3540c568100c842d5c0f6a4R190
`snyk test --all-projects` in the `test/acceptance/workspaces` should now also return gradle results.

feat: scan gradle projects behind --all-projects

---

help/help.txt

Update help text for `--all-projects` to remove the note about gradle not being supported

chore: update help docs to remove gradle exclusion.

---

test/acceptance/cli-test/cli-test.iac-k8s.spec.ts

This PR is an empty commit in order to re-trigger the release process due to a previous merged commit with a faulty message: `feat:improve iac test json output`
Commit message fixed to:
`feat: improve iac test json output`
*missed a white space
This PR references the following:
https://github.com/snyk/snyk/commit/b68890a18447505f1d5a005de8cf801a77493c4f

feat: improve iac test json output - retrigger

---

src/lib/snyk-test/run-test.ts

Hotfix for an issue with invalid output for projects with `--json` and `--all-projects` flag.

fix(test): json output with all-projects flag

---

.github/workflows/smoke-tests.yml
test/smoke/README.md
test/smoke/spec/snyk_auth_spec.sh
test/smoke/spec/snyk_basic_spec.sh
test/smoke/spec/snyk_test_spec.sh
test/smoke/spec/spec_helper.sh

Following issue with `snyk auth` command https://github.com/snyk/snyk/pull/1315 this PR extends the tests for it
I can't test "opens a browser" flow, since it's near impossible (?) in CI. But this verifies the URL is valid, pointing to snyk.io and contains an UUID token parameter.
This test runs locally, in CI as a regression test and works as a Smoke test against our prod releases.
Verified it captures the regression:

chore(test): extend smoke test for auth

---

.circleci/config.yml
.github/workflows/smoke-tests.yml
test/smoke/README.md
test/smoke/spec/sanity_spec.sh
test/smoke/spec/snyk_test_spec.sh
test/smoke/spec/spec_helper.sh

Following an issue with extraneous output in stderr with `--json` and `--all-projects` flags https://github.com/snyk/snyk/pull/1324
This PR:
- adds a test for scenario above
- adds a jq dependency to validate command output is a valid JSON

chore(test): add regression test for valid JSON bodies

---

src/lib/config.ts
src/lib/user-config.ts

Adding a wrapper around configstore to allow environment variables to override config values.
You can run the following to disable suggestions:
```
$ SNYK_CFG_DISABLESUGGESTIONS=true snyk test
```
https://snyksec.atlassian.net/browse/DC-881

feat: Allow environment variables to override config values

---

.github/workflows/smoke-tests.yml
.releaserc
test/smoke/README.md
test/smoke/alpine/Dockerfile
test/smoke/alpine/entrypoint.sh
test/smoke/spec/snyk_auth_spec.sh
test/smoke/spec/snyk_test_spec.sh

Currently our CLI Alpine executable based on Node v12 is throwing segfault errors.
This PR introduces an Alpine docker container that runs shellspec tests for our CLI.
Smoke tests are passing with the latest working version using Node v14. They will fail in this PR, until we release a new version with v14:

fix(build): use node 14 for alpine executable

---

.releaserc

Follow up to #1337 - this PR makes it that we don't rely on automatic naming from `pkg`.
Since we've had to diverge Node 12 and 14 version, autogenerated names specified Node version as well:
`pkg` mentions in `--help` that `--output`may be used with a template string, but it seems like it's not implemented, so I broke the command into multiple `pkg` calls with a specified filename

chore(build): don’t rely on dynamic names from pkg

---

src/lib/config.ts

Changes the output stream for the "Using a custom API endpoint..." warning message from stdout to stderr.
src/lib/config.ts: line 33
test with `snyk-to-html` using
```bash
$ snyk test --json | snyk-to-html
```
This message currently outputs to stdout, which when running snyk with `--json`, breaks tools like `snyk-to-html` that require valid json input
N/A
Before change:
After change:
I didn't find an existing test for this, so would be happy to add one with your guidance.

fix: move custom API endpoint warning message to stderr

---

src/lib/plugins/rubygems/inspectors/gemfile.ts
src/lib/plugins/rubygems/inspectors/gemspec.ts
src/lib/plugins/rubygems/inspectors/try-get-spec.ts

Removes code in rubygems plugin that is unused around locating Gemfile - this file is not being used anywhere in the code unless there is no lockfile, in which case it will be detected as the what is called the `gemfileLock`
this is prep work for https://github.com/snyk/snyk/pull/1345

chore: remove unused gemfile detection

---

src/lib/plugins/rubygems/index.ts
src/lib/plugins/rubygems/inspectors/gemfile.ts
src/lib/plugins/rubygems/inspectors/gemspec.ts
src/lib/plugins/rubygems/inspectors/try-get-spec.ts
test/acceptance/cli-test/cli-test.ruby.spec.ts
test/acceptance/workspaces/ruby-app-custom-names/123.gemfile
test/acceptance/workspaces/ruby-app-custom-names/123.gemfile.lock
test/acceptance/workspaces/ruby-app-custom-names/gemfiles/Gemfile.rails-2.4.5
test/acceptance/workspaces/ruby-app-custom-names/gemfiles/Gemfile.rails-2.4.5.lock

Allow custom ruby file names to be tested when scanned with:
`snyk test --file=rails.2.4.5.gemfile --package-manager=rubygems`
`snyk monitor --file=gemfiles/Gemfile.lock.rails-2.4.5 --package-manager=rubygems`
https://github.com/snyk/snyk/compare/feat/allow-custom-ruby-file-names?expand=1#diff-4871998b3f946a79dad807557f130ed6R5
Relies on this PR: https://github.com/snyk/snyk/pull/1344

Feat: allow custom ruby file names

---

package.json

Pin transitives as they have moved on to requireing Node.js 10 >.

fix: pin transitives for Node 8 support

---

package.json
src/cli/commands/test/index.ts
src/cli/modes.ts
src/lib/ecosystems.ts
src/lib/types.ts
test/ecosystems.spec.ts
test/fixtures/cpp-project/add.cpp
test/fixtures/cpp-project/add.h
test/fixtures/cpp-project/display.txt
test/fixtures/cpp-project/main.cpp
test/fixtures/cpp-project/scan.json
test/modes.spec.ts

Add snyk-cpp-plugin.
In order to test C/C++ projects:
* Add source mode for C/C++ projects.
* Use snyk-cpp-plugin to scan and display C/C++ projects.
* Use scan & display plugin mechanism in snyk test.
`snyk source test` in a C/C++ project directory and the file fingerprints will be displayed
`snyk source test --json` for json output
This is the initial version, later pull requests will send this data to Snyk so that vulnerabilities can be found and reported back to user.

feat: add snyk-cpp-plugin

---

help/help.txt
src/cli/args.ts
src/cli/commands/monitor/index.ts
src/lib/snyk-test/run-test.ts
src/lib/types.ts
test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts

Using the full form is a mouthfull & hard to spell specially when debugging! Allow a simpler alternative as well.
- add alias -p for --prune-repeated-subdependencies
- convert `prune-repeated-subdependencies` internally to camel case

feat: add `-p` as alias for `--prune-repeated-subdependencies`

---

src/cli/args.ts
src/lib/find-files.ts
src/lib/snyk-test/run-test.ts
test/find-files.test.ts
test/fixtures/find-files/broken-symlink

Fixes an edge case when using "snyk test --all-projects" in a project that contains a broken symlink. (Currently it fails catastrophically.)
Small change to src/lib/find-files.ts
$ ln -s /path-that-does-not-exist broken-symlink
$ node dist/cli/index.js test --all-projects

Fix: handle broken symlinks

---

help/iac.txt

This PR removes the `--project-name=` details from the `snyk iac` help output.
Ticket: https://snyksec.atlassian.net/browse/CC-281
```
Usage:
$ snyk iac [command] [options] <path>
Find security issues in your Infrastructure as Code files.
Commands:
test ............... Test for any known issue.
Options:
-h, --help
--json .................................. Return results in JSON format.
--severity-threshold=<low|medium|high>... Only report issues of provided level or higher.
Examples:
$ snyk iac test /path/to/Kubernetes.yaml
For more information see https://support.snyk.io/hc/en-us/categories/360001342678-Infrastructure-as-code
```
```
Usage:
$ snyk iac [command] [options] <path>
Find security issues in your Infrastructure as Code files.
Commands:
test ............... Test for any known …
```

refactor: remove project from iac help

---

src/cli/commands/test/index.ts
src/lib/errors/index.ts
src/lib/errors/test-limit-reached-error.ts
src/lib/types.ts
test/acceptance/docker-token.test.ts

Adding a CTA if a test is made without an API key and with a Docker JWT. 
There are 2 cases - 
* Scan successful
* Scan not successful - the user has reached the free test limit
Need to setup the env locally with JWT auth enabled and with a valid token.
In any `snyk test` where the API key doesn't exist and the `SNYK_DOCKER_TOKEN` env var is set, the CTA should be displayed.

feat: adding cta for docker users

---

src/lib/snyk-test/run-test.ts

When running with `snyk test --reachable --all-projects` and one of the projects is not supported for reachable vulns
i.e. not maven, we are failing with this error `Cannot read property 'message' of undefined”.`.
This change makes sure that the project does have a call graph.

fix: check if scanned project does have a callgraph

---

package.json

Bumping `snyk-docker-plugin` to 3.18.1
Fixing issue #1363 - calling `map` on undefined object.

fix: Bumping sdp to 3.18.1

---

.github/workflows/smoke-tests.yml

There was a yaml lint error, and I missed the action failing
<sub><img src="https://user-images.githubusercontent.com/4775299/87437657-e7332b00-c5ee-11ea-958d-589dfb19d72c.png" alt=" " width="10" height="9"> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

chore: fix smoke test action yaml

---

docker/Dockerfile.docker
docker/Dockerfile.gradle-2.8
docker/Dockerfile.gradle-4.4
docker/Dockerfile.gradle-5.4
docker/Dockerfile.maven-3.5.4
docker/Dockerfile.maven-3.6.3
docker/Dockerfile.maven-3.6.3_java11
docker/Dockerfile.npm_ruby
docker/Dockerfile.python-2
docker/Dockerfile.python-3
docker/Dockerfile.sbt-0.13.16
docker/Dockerfile.sbt-1.0.4

Following https://github.com/snyk/snyk/pull/1304
This will allow us to see usage for a specific published docker image (~tag)
At the same time, you can overwrite these envvars during runtime with `-eSNYK_INTEGRATION_NAME`
<sub><img src="https://user-images.githubusercontent.com/4775299/87437657-e7332b00-c5ee-11ea-958d-589dfb19d72c.png" alt=" " width="10" height="9"> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

Track Snyk-CLI docker usage

---

src/lib/ecosystems.ts
src/lib/request/promise.ts
test/ecosystems.spec.ts
test/fixtures/cpp-project/display.txt
test/fixtures/cpp-project/error.txt
test/fixtures/cpp-project/testResults.json

Use scan result type when making request to test dependencies.
Split out makeRequest to it's own file so that it can be mocked.
snyk source test

fix: test dependencies scan result type

---

src/cli/args.ts
src/lib/get-file-contents.ts
src/lib/plugins/nodejs-plugin/npm-modules-parser.ts
src/lib/plugins/nodejs-plugin/yarn-workspaces-parser.ts
test/fixtures/npm/no-dependencies/package.json
test/missing-node-modules.test.ts

If the package.json has no `dependencies` property defined then assume no deps and do not throw and error that `node_modules` are needed.
Example **package.json**:
```
{
"name": "subpkg",
"version": "1.0.0",
"description": "",
"main": "index.js",
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1"
},
"author": "",
"license": "ISC"
}
```
Some lerna projects may have many sub packages that have no dependencies and scanning them with `--all-projects` skips the local packages & throws an error.
**Before**
**After**

feat: handle empty package.json dependencies better

---

package.json
src/lib/plugins/get-deps-from-plugin.ts
test/acceptance/cli-test/cli-test.all-projects.spec.ts

Use latest gradle plugin that sends scanned project targetFile as meta

feat: use snyk-gradle-plugin@3.6.2 that sends back project targetFile

---

package.json
test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
test/acceptance/cli-test/cli-test.yarn-workspaces.spec.ts
test/acceptance/cli-test/cli-test.yarn.spec.ts

Yarn2 requires node>10. We still have users on node8 using yarn and ever since we added yarn2 they are no longer able to add snyk to their projects.
Since snyk still supports node8, we must unfortunately remove our support for yarn2.
Node8 support will be dropped in the near future, after which we can reinstate yarn2 support.
In the meantime, users can pin the version 1.387.0 to retain yarn 2 support
See relevant issue: snyk/snyk#1270

feat: remove yarn2 support

---

package.json

We're adding 'arm' architecture support to the cli scanning. Firstly the 'platform' flag is supported if docker available locally and experimental features configured.
We support `docker buildx` format of the `platform` flag, so it's familiar to the user, eg. `linux/arm64/v8`
https://snyksec.atlassian.net/browse/RUN-1146

feat: Adding '--platform' flag to 'snyk container' commands

---

src/lib/analytics-sources.ts

Use `JETBRAINS_IDE` as integration name for all IntelliJ based IDEs from JetBrains.

fix: align integration naming for JetBrains IDEs

---

help/container.txt

The snyk container CLI now supports passing an explicit platform value.
This will then test the image with that platform, rather than just the
default (probably amd64).
Adds details about `--platform` to the help text.
```
snyk container --help
```
See https://github.com/snyk/snyk/pull/1389

feat: Add platform details to help for snyk container

---

help/container.txt
help/iac.txt
package.json
src/cli/commands/test/iac-output.ts
src/cli/commands/test/index.ts
src/cli/commands/test/sarif-output.ts
src/cli/commands/types.ts
src/cli/index.ts
src/lib/errors/empty-sarif-output-error.ts
src/lib/snyk-test/iac-test-result.ts
src/lib/types.ts
test/acceptance/cli-args.test.ts
test/acceptance/cli-test/cli-test.docker.spec.ts
test/acceptance/cli-test/cli-test.iac-k8s.spec.ts
test/acceptance/cli-test/cli-test.iac-k8s.utils.ts
test/acceptance/fixtures/docker/sarif-container-result.json

Introduces SARIF support for both containers and IaC.
Support for `--sarif` flag to output SARIF to stdout.
Support for `--sarif-file-output` to save SARIF results to specified file.
`snyk container test alpine --file=Dockerfile --sarif --sarif-output-file=test-container-sarif.json`
`snyk iac test file.yaml --sarif --sarif-file-output=test-iac-sarif.json`

feat: SARIF format support for IaC and containers

---

.github/CODEOWNERS
help/iac.txt
src/cli/commands/test/iac-output.ts
src/cli/commands/test/index.ts
src/lib/detect.ts
src/lib/errors/invalid-iac-file.ts
src/lib/iac/constants.ts
src/lib/iac/iac-parser.ts
src/lib/iac/iac-projects.ts
src/lib/snyk-test/index.js
src/lib/snyk-test/payload-schema.ts
src/lib/snyk-test/run-iac-test.ts
src/lib/types.ts
test/acceptance/cli-test/cli-test.iac-k8s.utils.ts
test/fixtures/iac-terraform/sg_open_ssh.tf
test/fixtures/iac-terraform/sg_open_ssh_invalid_go_templates.tf
test/fixtures/iac-terraform/sg_open_ssh_invalid_hcl2.tf
test/smoke/alpine/Dockerfile
test/smoke/spec/snyk_test_iac_spec.sh

This PR adds the following:
- a validation request to Registry to a new endpoint in order to validate Terraform files before passing them to the `iac-test` endpoint in registry.
- Support across the CLI IaC command for Terraform Project types.
- Regression Smoke tests with ShellSpec for the main Use-Cases for TF files.
Todo:
`snyk iac test someTerraformFile.tf`

feat: iac test terraform support

---

package.json
src/lib/ecosystems.ts
test/ecosystems.spec.ts

Add facts and identity to the scan result interface used to test dependencies.
See https://github.com/snyk/snyk-cpp-plugin/pull/16

feat: update scan result test dependencies

---

src/lib/errors/feature-not-supported-by-package-manager-error.ts
src/lib/reachable-vulns.ts
test/acceptance/cli-reachable-vulns.test.ts
test/dev-count-analysis.spec.ts
test/reachable-vulns.test.ts

- [ x] Ready for review
When a developer tries to run the Reachable Vulnerability feature (snyk test --reachable) for a non-supported package manager, we want to direct them to a web page where they can view which package managers we do support this feature.
I would advise starting test test/reachable-vulns.test.ts line 168. You can see the expected message on line 190.
run a local build with parameters `test --reachable`
Output should be:
'Reachable vulns' is not supported for package manager 'npm'. For a list of supported package managers go to https://support.snyk.io/hc/en-us/articles/360010554837-Reachable-Vulnerabilities
Unless you're testing with another package manager, then the package manager name will be different
Change provides more context to developer about which package …

feat: add url link to supported pkg mngrs for  --reachable

---

package.json

We support the '--platform' flag only when Docker experimental features enabled, throwing a user friendly error otherwise.
https://snyksec.atlassian.net/browse/RUN-1197

feat: [RUN-1197] Fail 'snyk container' if '--platform' unsupported

---

src/lib/analytics-sources.ts

Adds an expected environment variable for the Netlify plugin as a source for tracking Snyk CLI analytics usage
Here, and then view the associated update for the plugin here: https://github.com/snyk-labs/netlify-plugin-snyk/pull/5

feat: add tracking for netlify plugin as source

---

package.json
src/lib/monitor/index.ts
src/lib/package-managers.ts
test/acceptance/cli-reachable-vulns.test.ts
test/acceptance/cli-test/cli-test.gradle.spec.ts
test/reachable-vulns.test.ts

Adds reachable vulnerabilities feature support for Gradle projects.
⚠️ Will fail unless https://github.com/snyk/snyk-gradle-plugin/pull/147 is merged.

feat: add reachable vulnerabilities support for gradle

---

src/cli/commands/test/iac-output.ts
src/cli/commands/test/sarif-output.ts
test/acceptance/fixtures/docker/sarif-container-result.json

Small change to SARIF output description, severity to look the same in IaC and containers.

fix: sarif descirption change

---

test/dev-count-analysis.spec.ts

Fixes a flakey test that relied on hard-coded hashes to work (which, turns out, change more often than we expected).
https://github.com/snyk/snyk/pull/1426
HAMMER-166

Fix flaky test - remove reliance on hard coded values

---

.github/workflows/smoke-tests.yml
dangerfile.js
test/smoke/README.md
test/smoke/alpine/Dockerfile
test/smoke/spec/snyk_auth_spec.sh
test/smoke/spec/spec_helper.sh

This PR clears the output of Smoke test commands, by silencing some before/after hooks. And fixes an issue on Windows.

Cleaner Smoke test output

---

src/cli/commands/woof.ts
test/woof.spec.ts

ensure that woof is using only valid language names

woof command language selection works

---

src/cli/modes.ts
test/modes.spec.ts

removes containers test default `--app-vulns` scan
* `snyk container test mladkau/snykin`
[Slack Thread](https://snyk.slack.com/archives/CDSMEJ29E/p1601447472250500?thread_ts=1601396580.226500&cid=CDSMEJ29E)
[DC-852](https://snyksec.atlassian.net/browse/DC-852)

fix: container test should not run app vulns scan by default

---

.circleci/config.yml

Gives a standard approach to install JVM ecosystems for unix (maven, gradle and sbt) by Using SDKMAN, 
and introduces `install_gradle_unix` & `install_gradle_windows`

refactor: circle-ci jvm unix using sdkman install

---

dangerfile.js

Warns if you create a new Tap test file and suggests making anew Jest test file instead.
We want people to stop making new Tap tests and make Jest tests instead.
This won't warn if you're adding a new test to an existing Tap test file.

Warn on new tap tests with dangerjs

---

.vscode/launch.json
src/cli/commands/auth/index.ts
src/lib/analytics-sources.ts
src/lib/query-strings.ts
test/analytics-sources.spec.ts
test/query-strings.spec.ts

This PR propagates integration names to the UTM parameters used for `$ snyk auth` command.
You can check the logic https://github.com/snyk/snyk/pull/1432/files#diff-a66b785903d0b694ec783784733b20a3, but in general it will result in this:
- UTM_MEDIUM = 'cli' 
- UTM_SOURCE = 'cli'
- UTM_CAMPAIGN = integrationName https://github.com/snyk/snyk/blob/master/src/lib/analytics-sources.ts#L14 e.g. `JENKINS` 
- UTM_CAMPAIGN_CONTENT = integrationVersion e.g. `2.12.1`
HAMMER-117

Pass integration name and version to UTM parameters

---

package.json

Possible fix for #1453 - we've pushed a new tag with correct name package name

fix: update docker-legacy plugin name to resolve npm@5 issue

---

package.json

Sets that right command for maven to get the classpath for the
correct repo.
For more info go to:
https://github.com/snyk/java-call-graph-builder/pull/36

fix: correct classpath extraction for reachable vulns on windows

---

dangerfile.js

We are getting false positives because `!![] => true`, so you need to check for the actual array length because `!!0 => false`

Fix dangerfile tap test detection

---

src/lib/analytics-sources.ts
test/analytics-sources.spec.ts
test/fixtures/homebrew/Cellar/snyk/vX/.brew/snyk.rb

Adds the integration name`HOMEBREW` when the running CLI instances is installed with Homebrew.
HAMMER-135

Set integration name for Homebrew installs

---

src/lib/snyk-test/run-test.ts
test/acceptance/cli-test/cli-test.generic.spec.ts
test/run-test.spec.ts

test: runTest jest test, user sees userMessage when generic error occurs

---

help/help.txt

The container subcommand is now the default, so updating the
documentation to reference it.
I've also tidied up the subcommand list, and split it into 3 sections:
1. Primary commands for most common workflow
2. Additional product or type entry points
3. Everything else
I've also ordered each of those sections alphabetically. This should
help with adding additional items.

feat: add container subcommand to main help text

---

src/lib/analytics-sources.ts
src/lib/analytics.js
test/analytics-sources.spec.ts
test/analytics.test.ts

This will help us capture debug/analytics data if CLI is running e.g. in a specific IDE version.

Analytics: track integration environment

---

src/cli/commands/test/formatters/remediation-based-format-issues.ts
test/acceptance/workspaces/pip-app-transitive-vuln/cli-output-actionable-remediation.txt

Currently paths for top-level dependencies that have a vuln are only shown if the `all` flag is passed to `--show-vulnerable-paths`. This can be a bit confusing and some people don't understand why they're not seeing an "introduced by:" line for these top-level deps (e.g. if you have a direct dependency of `adm-zip@0.4.7`)
This PR changes that so that whenever a path is available it will also be shown when the default of `some` is used for `show-vulnerable-paths`

feat: paths always shown where available

---

.github/workflows/smoke-tests.yml
dangerfile.js
test/smoke/README.md

- add new node versions
- disable fail-fast strategy
- use homebrew that's already installed
- test homebrew installation
- test yarn installation

Update Smoke tests workflow

---

package.json

Fixes a regression where dependencies were not annotated with the Dockerfile instruction that introduced them.

fix: annotate deps with Dockerfile instruction that introduced them

---

package.json
src/lib/plugins/nodejs-plugin/yarn-workspaces-parser.ts
test/acceptance/cli-test/cli-test.yarn-workspaces.spec.ts
test/acceptance/workspaces/yarn-workspaces/libs/apple-lib/package.json
test/acceptance/workspaces/yarn-workspaces/package.json

Yarn workspaces patterns also support *globs* pattern, update the matching to cover this too.
> The workspaces field is an array containing the paths to each workspace. Since it might be tedious to keep track of each of them, this field also accepts glob patterns! For example, Babel reference all of their packages through a single packages/* directive.
https://classic.yarnpkg.com/en/docs/workspaces/
Also added a failing test to show a deep globs pattern in workspaces definitions was not supported until the fix

fix: support globs pattern in yarn workspaces definitions

---

.github/workflows/smoke-tests.yml
test/smoke/docker-root/Dockerfile
test/smoke/docker-root/entrypoint.sh

This PR introduces:
New docker container for Smoke Tests, that runs CLI install as root, replicating the issue from https://github.com/snyk/snyk/issues/1453

test(smoke): scenario where root user installing Snyk

---

src/lib/api-token.ts
src/lib/snyk-test/assemble-payloads.ts
src/lib/snyk-test/run-test.ts
test/acceptance/docker-token.test.ts
test/acceptance/fake-server.ts

Fixing an issue where incorrect auth header was sent to the docker-jwt endpoint and improving test coverage in that area.

fix: incorrect header sent for Docker Desktop requests

---

src/lib/ecosystems/monitor.ts
src/lib/errors/docker-image-not-found-error.ts
src/lib/errors/index.ts
src/lib/snyk-test/run-test.ts
test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
test/acceptance/cli-test/cli-test.docker.spec.ts

Converts an internal error into an actionable human readable message. 
* `snyk container monitor doesnotexist`
* `snyk container test doesnotexist`
* [JIRA: DC-948](https://snyksec.atlassian.net/browse/DC-948)

fix: Improve error message for scanning an image that doesn't exist

---

src/lib/iac/iac-parser.ts
test/fixtures/iac/kubernetes/pod-invalid.yaml

This PR removes the requirement of `spec` to accept yaml files as valid k8s objects
We currently reject yaml files if the `spec` field is not present in k8s object.
This is not valid requirement for all k8s object for example service-account
[Zendesk](https://snyk.zendesk.com/agent/tickets/7401)

fix: remove spec requirement

---

package.json

Bump python plugin version to include graceful fail when no deps

feat: bump python plugin version to include graceful fail when no deps

---

package.json

Bump snyk-python-plugin version to include auto-resolving dependencies with underscores to hyphens

fix: bump python plugin version

---

package.json

This PR bumps the NuGet plugin to 1.9.4
https://github.com/snyk/snyk-nuget-plugin/issues/75

fix: bump nuget plugin to fix diff target monikers

---

src/cli/commands/test/formatters/format-test-results.ts
src/lib/json.ts
test/fixtures/basic-npm/jsonData.json
test/fixtures/basic-npm/results.json
test/format-test-results.spec.ts
test/json.spec.ts

Two important things wrt generating the Snyk-format JSON or SARIF-format JSON output from the test command:
- don't do `JSON.stringify` at all if we don't need it
- produce only the JSON formats we need: if we need Snyk-format JSON then generate that; if we need SARIF-format JSON, then generate that. If we need both (ex if the user uses `--json` and `--sarif-file-output`), then produce both.
We're also try/catching the `JSON.stringify` for the test output and, if it throws, we'll automatically try again without pretty-print. This may help in some scenarios where JSON.stringify is failing with `RangeError: Invalid string length`. Other `JSON.stringify` calls are likely to be tiny by comparison so we don't really need this for those, but we could consider it in the future.
- @lili2311 …

Don't create JSON if we don't need it

---

src/lib/snyk-test/run-test.ts

Restore analytics for tracking Docker/container calls.
[Slack thread where it was first reported](https://snyk.slack.com/archives/CFVCSBXN0/p1604590163176000?thread_ts=1604586579.175300&cid=CFVCSBXN0)

fix: restore analytics for tracking Docker/container calls

---

package.json

Bumps the version of the maven plugin to include the long path fix for the java call graph builder.
snyk/java-call-graph-builder#38

fix: use Java call graph builder with long path fix

---

test/metrics.spec.ts

In the modified test file, sleep() is backed by setTimeout(), and some Node runtimes might execute setTimeout callback before the specified delay, meaning that tmi.getValue() will occasionally return `9`. This produces a flaky test, eg https://app.circleci.com/pipelines/github/snyk/snyk/3074/workflows/f11955a8-5ffc-450a-94be-387dfdfc55a8/jobs/17080. An extra ms leeway in the assertion works round the issue. https://github.com/nodejs/node/issues/10154.
Test name updated to reflect that the timer's accuracy does not have single-digit precision

test: Fix a flaky test

---

package.json

Setting SNYK_REGISTRY_USERNAME and/or SNYK_REGISTRY_PASSWORD environment variables allows these credentials to be used to log in to remote registries. The existing --username and --password flags, if present, take precedence
Documentation updates to follow in a separate PR

feat: Bump docker plugin to enable env var auth

---

src/lib/errors/docker-image-not-found-error.ts
src/lib/snyk-test/run-test.ts
test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
test/acceptance/cli-test/cli-test.docker.spec.ts

Container registries can return an error which we don't currently catch as a Docker one, resulting in user getting shown JSON in the terminal. This fixes that by replacing it with a human-readable message, as well as clarifying that the same error can also result from bad credentials
Example commands are in #run-1041-demo
https://snyk.slack.com/archives/C01EXBHKVML/p1605797706005400?thread_ts=1605797655.004700&cid=C01EXBHKVML
[RUN-1041]
https://snyk.slack.com/archives/C01EXBHKVML/p1605868316000300
[RUN-1041]: https://snyksec.atlassian.net/browse/RUN-1041

fix: correct credential auth failure error text

---

test/cli-alert/src/index.ts

CLI alert will now check the latest 7 smoke tests and would be less chatty as a result

fix: only check latest 7 smoke tests

---

src/cli/commands/test/formatters/format-test-results.ts
src/cli/index.ts
src/lib/types.ts
test/fixtures/basic-apk/jsonData.json
test/fixtures/basic-apk/jsonDataGrouped.json
test/fixtures/basic-apk/results.json
test/format-test-results.spec.ts

This PR adds an '--group-vulns' which can be used to group vulnerabilities by ID while the different vuln paths are displayed as a list of lists.
Can be best tested with: `snyk container test alpine:3.12.1  --json --group-vulns`
See Jira: [DC-1001](https://snyksec.atlassian.net/browse/DC-1001)
Example with the list of lists in the `from` attribute:

feat: Adding group-issues option for JSON output

---

src/cli/index.ts
test/acceptance/cli-args.test.ts

Currently when running:
```
% snyk iac test --sarif --json # or
% snyk container test --sarif --json
```
We output the error stack to the terminal (due to the `--json` flag):
```
UnsupportedOptionCombinationError: The following option combination is not currently supported: test + sarif + json
at validateUnsupportedSarifCombinations (/Users/$USER/.nvm/versions/node/v12.19.0/lib/node_modules/snyk/src/cli/index.ts:383:11)
at main (/Users/$USER/.nvm/versions/node/v12.19.0/lib/node_modules/snyk/src/cli/index.ts:265:5)
at Object.<anonymous> (/Users/$USER/.nvm/versions/node/v12.19.0/lib/node_modules/snyk/src/cli/index.ts:293:13)
at Module._compile (internal/modules/cjs/loader.js:1015:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
at Module.load …
```

fix: Error output for mismatched options

---

src/cli/commands/test/iac-output.ts
src/lib/snyk-test/iac-test-result.ts
test/acceptance/cli-test/iac/cli-test.iac-dir.spec.ts
test/acceptance/cli-test/iac/cli-test.iac-utils.ts

Fixes [CC-525] & [CC-563]
Previously when running the `iac test --sarif` command we would assign one "run" entry for each file. 
```json
{
"version": "2.1.0",
"runs": [{
"tool": {
"driver": {
"name": "Snyk Infrastructure as Code",
"rules": [  "... all rules for file A..." ]
}
},
"results": [ "/* ... results for file A... */" ]
}, {
"tool": {
"driver": {
"name": "Snyk Infrastructure as Code",
"rules": [ "... rules for file B ..." ]
}
},
"results": [ "... results for file B..." ]
}
]}
```
Customers were expecting to have a single "run" entry with all results included together under a single list. This PR refactors the IaC Sarif formatter to take this approach.
```json
{
"version": "2.1.0",
"runs": [{
"originalUriBaseIds": {
"PROJECTROOT": {
"uri": "file:///Users/Aron/Code/snyk/", …
```

fix: Include all results under a single run

---

src/lib/errors/non-existing-package-error.ts
src/lib/snyk-test/run-test.ts
test/acceptance/cli-test/cli-test.generic.spec.ts

Allow users to see a 404 message for non-existing packages

fix: allow indicative messages for CLI users

---

src/cli/commands/test/formatters/format-test-results.ts
src/cli/index.ts
test/fixtures/basic-apk/jsonDataGrouped.json

Small fix for the `--group-issues` flag. We should also group the name attribute along with the from attribute.

fix: Group issues should also group names

---

src/cli/commands/test/iac-output.ts
src/lib/snyk-test/iac-test-result.ts
test/acceptance/cli-test/iac/cli-test.iac-utils.ts

CC-517
This PR adds the 'resolve' and 'impact' fields in the results of the sarif output in order to give more useful information to the users and show that to the Github Security page (coming from the registry's AnnotatedIssues object).
Check the two new fields in `iac-output.ts. The resolution is added to the 'help' field and the impact is included in the full description.
We are using the reportingDescriptor object, more info on the docs here [Github Security SARIF Docs](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/sarif-support-for-code-scanning#supported-sarif-output-file-properties)
[Jira CC-517](https://snyksec.atlassian.net/browse/CC-517)
**CLI Output:**
**Github Security:**

feat: Add impact and resolve fields in sarif output.

---

src/cli/index.ts
src/lib/analytics.ts
src/lib/protect/apply-patch.js
src/lib/request/index.ts
src/lib/user-config.ts
test/analytics.spec.ts
test/analytics.test.ts

Fixes some typing issues that are needed for the upcoming modular CLI init PR (https://github.com/snyk/snyk/pull/1564).
For the modular CLI init / monorepo PR, we will be turning on `"composite": true` in the tsconfig which requires certain typing things be addressed beforehand.
Why not just do this as part of the aforementioned PR (https://github.com/snyk/snyk/pull/1564)? Because that PR is going to touch a lot of things and I would prefer to keep that PR as small as reasonably possible and since this is just about improving some typing (and refactoring analytics into TypeScript) I think it is best kept on its own.
HAMMER-237

Resolve type annotation changes required to enable `composite` in tsconfig

---

package.json

when no tag is provided when scanning container images
the plugin will now always append latest tag
Fixes an issue where the user has multiple images from the same repo - not all docker commands implicitly append `latest` tag when none is received.
In this version `latest` will always be appended if not present.

fix: bump docker plugin to explicity append latest

---

src/lib/find-files.ts

Only log the filtered out files when we show debug log: `Filtered out 4/26 files....`, issue seen in https://github.com/snyk/snyk/issues/1563
```
snyk:find-files File does not seem to exist, skipping:  broken-symlink +0ms
snyk:find-files Encountered multiple node lockfiles files, defaulting to /Users/lili/www/snyk/snyk/test/cli-alert/package-lock.json +22ms
snyk:find-files Encountered multiple node lockfiles files, defaulting to /Users/lili/www/snyk/snyk/test/fixtures/package-sans-name-lockfile/package-lock.json +3ms
snyk:find-files Encountered multiple node lockfiles files, defaulting to /Users/lili/www/snyk/snyk/test/fixtures/protect-semver-patch/package-lock.json +0ms
snyk:find-files Encountered multiple node lockfiles files, defaulting to …
```

fix: log filtered out files instead of all

---

.github/workflows/smoke-tests.yml
test/smoke/alpine/entrypoint.sh
test/smoke/install-snyk-binary-win.sh

Seems like GitHub changed capitalization of the `Location` header in the HTTP response for `https://github.com/snyk/snyk/releases/latest`
Added case insensitive `-i` flag to the grep command

chore(smoke): handle uppercase header in release downloader

---

package.json
src/lib/iac/detect-iac.ts
src/lib/request/request.ts
src/lib/snyk-test/run-test.ts
test/request.test.ts

Currently for a call to snyk iac test our CLI process makes the following sequential requests to our backend API:
- One request per file to validate each Terraform file in the directory tree (or provided via arguments)
- One request pre file to test each matching IaC file in the directory tree (or provided via arguments)
1. As part of cloud-config's work on making tthe cli more performant, we are changing the requests above to **run in parallel.** Various tests were made to determine how this affects the timings, with results showing an average decrease of 8m30s. This is a small win which makes the cli run much faster.
2. In order not to throttle the system in the case of a big number of files being tested, we also introduced two small changes. By default, HTTP connections close after …

Update snyk iac cli to issue parallel requests

---

.github/workflows/smoke-tests.yml
test/smoke/alpine/entrypoint.sh
test/smoke/install-snyk-binary-win.sh

Fix smoke tests' Snyk binary download and installation.
- [✅ ] Ready for review
- [✅ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [✅ ] Reviewed by Snyk internal team

fix: smoke tests’ snyk binary download

---

src/cli/commands/monitor/index.ts

We log this `pluginOptions` field only in the `monitor` command. Since we are not using it in `test`, we shouldn't keep it here either.

fix: remove extraneous logging field

---

help/commands-docs/_SNYK_COMMAND_OPTIONS.md
package.json
test/args.test.ts

Adds help text for new `--project-name-prefix` flag added to the Nuget plugin. Also added tests for all Nuget-specific CLI args: `--project-name-prefix`, `--assets-project-name` and `--packages-folder`

chore: add help for new --project-name-prefix flag

---

docker/Dockerfile.gradle-5.4_java11

When building docker image we see error message:
```
The following packages have unmet dependencies:
nodejs : Conflicts: npm
npm : Depends: node-gyp (>= 3.6.2~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Removing explicit npm install from 'apt-get install' fixes issue.
Just doing 'apt-get install -y nodejs' will install npm.

fix: gradle 5.4 Java 11 Dockerfile npm install

---

package.json

This pr changes comes from https://github.com/snyk/snyk-gradle-plugin/pull/161
- Renamed snykConf to projectConfigs, to improve the readability
- Created configsSuccessfullyResolved method that confirms if
configs sets as canBeResolved=true, can be really resolved or not.
If there is an error now, while resolving configs set as
canBeResolved=true, we are no longer blocking the scanning. We ignore
those configs whose depGraph cannot be computed and move forward with the
scanning process since it's not a snyk issue but a given gradle project
resolution config caused by bad config or 3rd party gradle dependencies bad behaving.
By going into `test/fixtures/successful-scan-with-unresolved-custom-configs/build.gradle` and running `gradle -q dependencies` you will see the following message (pic …

fix: scanning lock due of unresolved deps

---

package.json

swallowing unresolvable configs error msg in order to prevent mass spam in
script output while scanning projects with large graph output to prevent parse errors...
snyk/snyk-gradle-plugin#162

fix: more than one line with jsondeps

---

src/cli/index.ts
src/lib/json-file-output.ts
test/acceptance/cli-args.test.ts
test/json-file-output.test.ts

Updates the `writeContentsToFileSwallowingErrors` function to use be async and wait for the `finish` event to resolve and then use await when calling this function. This should eliminate the flakeyness of the corresponding tests which manifests intermittently with `test/acceptance/cli-args.test.ts` and `test/json-file-output.test.ts`
This test has been flakey for a while.
Example of test flaking: https://app.circleci.com/pipelines/github/snyk/snyk/3423/workflows/73c644ca-dd4b-4158-9510-ad4efa5b8eb7/jobs/19088
The issue is that the fn that the test is flaking was sometimes not done its IO before returning.

Make fn async and use await to avoid race condition in tests causing test flakeyness

---

.github/workflows/smoke-tests.yml
test/smoke/alpine/entrypoint.sh
test/smoke/install-snyk-binary-win.sh

test: add authorization to curl command
To prevent API rate limit being exceeded, add authorization to curl command in Snyk installation in Smoke Tests.

test: add authorization to GH API calls on smoke tests

---

src/lib/snyk-test/legacy.ts
src/lib/snyk-test/run-iac-test.ts
src/lib/snyk-test/run-test.ts

Today, when running IaC scan with `--json-file-output`, the JSON does not contain the tested file full path.
This PR added the relevant field to the JSON.
` node dist/cli/index.js iac test <folder>  --json-file-output=output.json`

fix: add full file path to output file for iac scan

---

package.json

making configsSuccessfullyResolved more graceful, when at least a single
dependency available in a config failed e.g. 1/5, we immediately were
considering the config not resolvable and filtering it out.
By using configuration.resolvedConfiguration.firstLevelModuleDependencies;
We no longer try to locate and download files as we were doing with
configuration.resolve. With the new approach we just ask for the instances
available for each direct dependency of the configuration that matches the given spec.
Continue reading https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ResolvedConfiguration.html
https://github.com/snyk/snyk-gradle-plugin/releases/tag/v3.12.3

fix: gradle graceful resolvable configs

---

help/commands-docs/_SNYK_COMMAND_OPTIONS.md
src/cli/commands/test/formatters/format-test-results.ts
src/cli/commands/test/open-source-sarif-output.ts
src/lib/snyk-test/legacy.ts
test/__snapshots__/sarif.spec.ts.snap
test/acceptance/cli-test/cli-test.generic.spec.ts
test/sarif.spec.ts
test/support/sarif-schema-2.1.0.js

Add "--sarif" option to Snyk Open Source
Here's a screenshot from [Github code scanning with the result of the --sarif run](https://github.com/admon-synk/LOKI-121-sarif/security/code-scanning)

feat: add SARIF support for snyk open-source

---

package.json

Bumps the python plugin to include the following fixes:
- Stop parser from trying to look up packages not propagated to the lockfile (wheel, distributed, pip,  setuptools)
- Stop parser from failing when failing to locate dependency in lockfile and instead log a warning. This could be because of python requirements allowing it in the manifest but not actually installing it and adding a lockfile entry or because of how Poetry treats the use of underscores and hyphens when installing packages
- Reversed PR that introduced swapping underscores in manifest for hyphens in lockfile. This was due to a misunderstanding of how Poetry worked and is remediated by the above.
[LOKI-174](https://snyksec.atlassian.net/browse/LOKI-174)
[LOKI-175](https://snyksec.atlassian.net/browse/LOKI-175) …

fix: bump python plugin version to include multiple fixes

---

src/cli/commands/test/formatters/legacy-format-issue.ts
src/lib/snyk-test/run-test.ts
test/acceptance/cli-test/cli-test.docker.spec.ts

Updated 'container test' Dockerfile instructions to "Image layer:" to be consistent with what we show in the UI.
Added showing auto detected instructions if Dockerfile not present.
https://snyksec.atlassian.net/browse/CAP-149
```
✗ Low severity vulnerability found in bzip2/libbz2-1.0
Description: Denial of Service (DoS)
Info: http://localhost:12346/vuln/SNYK-LINUX-BZIP2-106947
Introduced through: bzip2/libbz2-1.0@1.0.6-8.1, apt/libapt-pkg5.0@1.6.3ubuntu0.1
From: bzip2/libbz2-1.0@1.0.6-8.1
From: apt/libapt-pkg5.0@1.6.3ubuntu0.1 > bzip2/libbz2-1.0@1.0.6-8.1
Image layer: 'RUN test instruction'
```

feat: Show auto detected user instructions in 'container test' output

---

.circleci/config.yml

Adds a npx command to generate a release notes from the latest tag

Introduce release notes generation

---

src/cli/commands/protect/prompts.ts
src/cli/commands/test/formatters/legacy-format-issue.ts
src/cli/commands/test/formatters/remediation-based-format-issues.ts
src/cli/commands/test/iac-output.ts
src/lib/snyk-test/common.ts
src/lib/snyk-test/legacy.ts
test/acceptance/cli-test/cli-test.ruby.spec.ts
test/acceptance/workspaces/ruby-app-thresholds/test-graph-result-critical-severity.json
test/acceptance/workspaces/ruby-app-thresholds/test-result-critical-severity.json
test/acceptance/workspaces/ruby-app-thresholds/test-result-medium-severity.json

* Adds colors for future support for critical severity
* Adds default fallback color for unknown severities
* Single place for color definitions

feat: update critical sev colour

---

help/commands-docs/_SNYK_COMMAND_OPTIONS.md
package.json
src/cli/args.ts
src/lib/types.ts
test/acceptance/cli-test/cli-test.gradle.spec.ts

This PR was submitted by @pwnslinger, this pull request was opened because CircleCI is unable to pull a forked repository. Credit where it's due, this fix was created by @pwnslinger as well.
init-script is part of gradle and is used for certain use cases such as private artifact inventories.
This is required for reachability in order to get the classpath required for building the call graph.
Using a gradle project, create a file `init.gradle` for example and run
`snyk test -d --file=./build.gradle --insecure  --severity-threshold=medium --reachable --init-script=init.gradle`
or
`snyk monitor -d --file=./build.gradle --insecure  --severity-threshold=medium --reachable --init-script=init.gradle`
We need the inner gradle commands of the java call graph builder to succeed in order to retrieve …

feat: add init-script argument to CLI for gradle

---

.circleci/config.yml

Removes the publishing of the npm packages from the `dev-release` job in CircleCI.
Creating too much noise in the versions list on npmjs.

Remove dev-release package publishing

---

src/cli/commands/auth/index.ts
test/smoke/spec/snyk_auth_spec.sh
test/system/cli.test.ts

Allows running auth command when inside a docker container by:
* not trying to open a browser via xdg open (breaks if not present or in container)
* providing a better auth prompt/message
* doubling the auth timeout period, so users have more time open browser
manually
This makes it possible to use auth command via "docker scan" on soon to be released scan plugin for docker linux.
Run "snyk auth" inside a container.
https://snyksec.atlassian.net/browse/DC-1077

feat: Don't open browser auth if inside container

---

src/lib/errors/invalid-iac-file.ts
test/smoke/spec/iac/snyk_test_directory_spec.sh
test/smoke/spec/iac/snyk_test_terraform_spec.sh

Fixes wrong error message output for `iac test` and removes tests that will break soon due to backend change.
We have a wider ticket for doing an overhaul on our documentation and error messages, this mainly quickly fixes a wrong error message that claims that we support only Kubernetes.

refactor: iac test docs

---

package.json

For docker archives we extract auto detected user instructions from the image config. Some of the entries are missing "created_by" so we were throwing an error.

fix: Added filtering history entries with no "created_by"

---

test/acceptance/workspaces/no-vulns/package.json
test/analytics.spec.ts
test/cli-json-file-output.spec.ts
test/dev-count-analysis.spec.ts

Convert some flaky tests to jest from tap
Increase timeout for analytics tests
Use a smaller fixture with a lockfile for a slow test `test/monitor-target.spec.ts` that was running on `node_modules`

test: convert flaky tests to jest & increase timeout

---

src/cli/commands/help.ts
test/smoke/spec/snyk_basic_spec.sh

When the terminal doesn't support colour (either NO_COLOR env variable or not TTY as detected by NodeJS), it will remove every ANSI escape code when printing the `help` output. This avoids printing them in plain text and obfuscating the help text.
Only a few files to check.
Run `snyk help | cat` will print ANSI codes in plain text before this change. After it should print plain unformatted text.
Originally noticed in some Powershell sessions.
None.
None.
`strip-ansi` is a part of `chalk` so it's not added as a direct dependency, but as best practice, maybe it should be as we use it directly?

fix: avoid ansi escape codes in non-tty and no color output

---

test/cli-alert/package-lock.json
test/cli-alert/package.json
test/cli-alert/src/index.ts

* Add PagerDuty to CLI alerts
* Check if latest Smoke Test workflow is still running **before** checking conclusion and attempting re-run

test: add pagerduty, check if test is running before attemmpting rerun

---

src/lib/request/request.ts

Today we're serialising the request's payload to debug it. this fails when the payload is too be (see ticket https://snyk.zendesk.com/agent/tickets/6712).
This will skip and log another message in this scenario.

fix: don't fail on request's big payload

---

.github/workflows/cli-alert.yml

Small fix to add PagerDuty routing key as environment variable, so that CLI alerts workflow works properly

test: CLI alert: add PD_ROUTING_KEY env variable

---

.github/CODEOWNERS
.gitignore
packages/snyk-fix/README.md
packages/snyk-fix/SECURITY.md
packages/snyk-fix/jest.config.js
packages/snyk-fix/package.json
packages/snyk-fix/src/index.ts
packages/snyk-fix/src/lib/errors/custom-error.ts
packages/snyk-fix/src/lib/errors/error-to-user-message.ts
packages/snyk-fix/src/lib/errors/unsupported-type-error.ts
packages/snyk-fix/src/plugins/load-plugin.ts
packages/snyk-fix/src/plugins/python/index.ts
packages/snyk-fix/src/plugins/types.ts
packages/snyk-fix/src/types.ts
packages/snyk-fix/test/helpers/generate-entity-to-fix.ts
packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
packages/snyk-fix/test/unit/fix.spec.ts
packages/snyk-fix/tsconfig.json
release-scripts/update-versions.sh
tsconfig.json

- setup a new snyk-fix workspace for fix package functionality
- basic loadPlugin functionality & types added
- a couple of basic tests to ensure loadPlugin is working as expected
- add Bull (Tech Services) as codewone
Check the package.json & any relevant release setup mostly 🙏 all the code will change a lot after this initial version and is there mostly to have basic skeleton + tests
`npm run test` inside the package
Package tests will not trigger until this functionality is added shortly.

feat: initial snyk-fix package setup & loadPlugin functionality

---

src/cli/commands/protect/wizard.ts

Fixes #1549
Detecting newlines is dependant on try-require which uses `leading` and `trailing`, not `prefix` and `suffix`.
https://github.com/snyk/snyk/blob/3262519c9ec9b53952d46273e7a733080c9c7388/src/cli/commands/protect/wizard.ts#L205-L206
https://github.com/snyk/try-require/blob/a79f6c1dfe4c806b04f1b847d70b79354e1f78a2/lib/try-require.js#L40-L41
This PR fixes this to use the correct properties.
There are no acceptance tests for the wizard as it's an interactive CLI. So easiest way is to manually run it before and after.
```
cd test/fixtures/protect
snyk wizard # say yes to add snyk command to package.json
git diff package.json # notice new line at end of file is removed
```

fix: ensure wizard maintains newlines in package.json

---

src/cli/commands/ignore.ts
test/system/cli.test.ts

In all the time we’ve had ignores in the CLI, we’ve never set a created date of the current timestamp to them, which is counter to what we do in the UI/API.
Now is the time to change that.
Pull this down and build it locally.
- Find a monitored project which has issues
- Find an issue and run ignore, e.g `snyk-dev ignore --id=npm:qs:20140806`
- Monitor the project
- Call the aggregated issues endpoint for the project to see that the created date is in the returned ignore object on the issue, `http://[host]/api/v1/org/orgId/project/projectId/aggregated-issues`

feat: add default created date to ignores

---

.github/CODEOWNERS
.gitignore
config.default.json
package.json
src/cli/commands/test/index.ts
src/cli/modes.ts
src/lib/config.ts
src/lib/ecosystems/index.ts
src/lib/ecosystems/plugins.ts
src/lib/ecosystems/test.ts
src/lib/ecosystems/types.ts
src/lib/errors/index.ts
src/lib/errors/unsupported-feature-for-org-error.ts
src/lib/plugins/sast/analysis.ts
src/lib/plugins/sast/errors/unsupported-feature-snyk-code-error.ts
src/lib/plugins/sast/format/output-format.ts
src/lib/plugins/sast/index.ts
src/lib/plugins/sast/utils/index.ts
src/lib/plugins/sast/utils/testEmitter.ts
src/lib/plugins/sast/validate.ts
src/lib/types.ts
test/fixtures/sast/sample-analyze-folders-response.json
test/fixtures/sast/sample-sarif.json
test/fixtures/sast/test-output-windows.txt
test/fixtures/sast/test-output.txt
test/snyk-code-test.spec.ts

*Reverts snyk/snyk#1682*
[COD-123]
This introduces an mpv usage for snyk code.
This is a second attempt: 
the first pr failed due to es module issues in flatted from code-client->flat-cache->flatted
This issue has been resolved in code client and we now have a custom implementation of flat-cache specifically for our needs.
A second issue the arose dcignore was not included into executable at compilation stage. dcignore was the deepcode ignore package that is leveraged in the vscode extension through the code-client. However its future is uncertain, I have now raised a discussion around its future that will be decided on in the next week, the most likely outcome will be removing it from the code-client and re-writing the package and only using it through vs-code extension and if needed in …

fix: re-add snyk code support, fixing cli executables

---

.github/CODEOWNERS
jest.config.js
package.json
test/iac-unit-tests/file-loader.fixtures.ts
test/iac-unit-tests/file-loader.spec.ts
test/iac-unit-tests/file-parser.fixtures.ts
test/iac-unit-tests/file-parser.spec.ts
test/iac-unit-tests/file-scanner.fixtures.ts
test/iac-unit-tests/file-scanner.spec.ts

Adds unit-tests to the new local execution implementation for IaC.
As part of the new IaC local execution we're making an effort to achieve 100% unit test coverage for the new code.
For the previous implementation, it was dependant only on regression tests, we had 0% unit-tests.
This PR introduces new unit tests to cover the new modules added for `iac-local-execution`.
As we're basically re-wrote our CLI product from scratch, we're trying to do this incrementally, balance with our priorities, and make sure that this time we don't build tech debt of missing tests.
After this PR, probably 1 or 2 more will follow.
Hammer team  are working at the moment on moving jest-unit tests to new folders as part of a wider test cleanup and organisation they are doing. (branch …

test: iac local exec new unit tests - part 1

---

.gitignore

Ignore `node_modules` folders in the root of a package (`/packages/<package-name>/node_modules`). This will **_NOT_** ignore other `node_modules` such as those used in test fixtures (ex `/packages/<package-name>/test/fixtures...`)
The `node_modules` generated by `npm install` in the root of the new `snyk-fix` package is not being ignored.

Ignore node_modules in the packages

---

.circleci/config.yml
jest.config.js
package.json
src/cli/commands/test/iac-local-execution/file-utils.ts
src/cli/commands/test/iac-local-execution/index.ts
src/cli/commands/test/iac-local-execution/local-cache.ts
test/iac-unit-tests/file-utils.spec.ts
test/iac-unit-tests/local-cache.spec.ts

_This is the basic e2e flow that we need for the Beta release. It will be incrementally enhanced._
Everytime a user runs `snyk iac --experimental`, the wasm policies will be available locally.
What happens in the background: 
- A tarball bundle.tar.gz is downloaded from S3, is extracted and placed in the `.iac-data` directory of your cwd. 
This way, the user will have the policies locally in a wasm file, giving them the ability to scan their files locally against them and not send any files over the network.
**Regarding the smoke tests and the env variable:** 
these are run against a subset of fixtures, but now that we introduce this new flow, the policies would get updated every time. Because of that, we provided an env variable temporarily named `SNYK_IAC_SKIP_BUNDLE_DOWNLOAD` to …

[IaC] feat: fetch policy bundle from S3 for local scans [Beta]- CC-627

---

src/cli/commands/test/iac-local-execution/parsers/terraform-plan-parser.ts
src/cli/commands/test/iac-local-execution/types.ts

Fixes the terraform plan parser to scan also data inputs in addition to resources.

fix: terraform plan scan to include data objects

---

.circleci/config.yml

`aws` command is not preinstalled on CircleCI

Install AWS CLI in the release step

---

src/cli/commands/test/iac-local-execution/file-utils.ts
src/cli/commands/test/iac-local-execution/local-cache.ts
test/iac-unit-tests/file-utils.spec.ts
test/iac-unit-tests/local-cache.spec.ts

On a previous PR, we introduced the download of a tarball with policies and the extraction of its contents.
The code was unnecessarily writing the bundle.tar.gz to the disk before extracting the files too. This file is not needed, we only need its contents to be written to the disk, so this PR removes it.
Run `snyk iac test file.tf --experimental` and check that there is no bundle.tar.gz into your `.iac-data` folder
Related to CC-627

refactor: Remove writeable stream to stop writing tarball to the disk [IaC]

---

src/cli/commands/protect/index.ts
src/cli/commands/protect/wizard.ts
src/cli/commands/test/index.ts
src/cli/commands/test/set-default-test-options.ts
src/lib/types.ts
test/run-test.spec.ts
test/set-default-test-options.spec.ts
test/snyk-code-test.spec.ts

refactor settings default test options so it can be re-used in another command that relies on test running first

refactor: set default test options

---

packages/snyk-fix/src/index.ts
packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
packages/snyk-fix/src/plugins/python/index.ts
packages/snyk-fix/src/types.ts
packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/update-dependencies.spec.ts
packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
packages/snyk-fix/test/unit/fix.spec.ts

- rename outputs from snykFix package
- return some meta about how much was fixed vs failed to be used as analytics / summary
- optionally return output stripped of ansi characters

feat: return fix summary & meta

---

jest.config.js

Jest uses micromatch for these paths which should handle Windows path separators automatically. Removing these will reduce the amount of test config to maintain.
See small diff. Windows tests should run like Linux tests in CI.
Run Jest tests in Windows (or use CI)

chore: remove windows-specific test paths

---

packages/snyk-fix/src/lib/output-formatters/format-unresolved-item.ts
packages/snyk-fix/test/unit/lib/output-formatters/__snapshots__/format-unresolved-item.spec.ts.snap
packages/snyk-fix/test/unit/lib/output-formatters/format-unresolved-item.spec.ts

- some remote scans do not have much information to use to identify the scanned project. If we don't have targetFile for now fallback to `${type} project` e.g. `npm project`
**Before**
**After**

feat: fallback to type when missing targetFile

---

src/lib/iac/iac-parser.ts
src/lib/request/index.ts

Fixes CC-751
Handles 401 authentication errors when making a validation request to Terraform, previously we would always return a result regardless of the HTTP response, this resulted in misleading error messages.
This PR also fixes the type definition of the `request()` function so the caller no longer has to unwrap the returned response from the promise. The return type for the non-callback approach is now `Promise<{res: NeedleRes, body: any}>` instead of `Promise<void | {res: NeedleRes, body: any}>`
All the code is in src/lib/iac/iac-parser.ts, we have no unit tests for this code path :/ and it will all soon be replaced by the `--experimental` branch.
1. Invalidate the API token e.g. `snyk config set api=foo`
2. Test a Terraform file e.g `node ./dist/cli iac test …

fix: Error messages when Terraform validation fails due to bad credentials

---

src/cli/commands/test/iac-local-execution/analytics.ts
src/cli/commands/test/iac-local-execution/file-parser.ts
src/cli/commands/test/iac-local-execution/index.ts

This PR adds a few more analytics for the new iac local execution flow.
- `iac-test-count`: total tested files tested for a run 
- `iac-issues-count`: total issues found for a run
- `iac-terraform-plan`: a boolean flag to indicate if a tf-plan.json was scanned as part of this run
- `iac-type`: an object containing count of file types with issues, by severity, e.g.  
``` 
"iacTerraformPlan": false,
"iacTestCount": 235,
"iacIssuesCount": 1283,
"iacType": "{\"terraformconfig\":{\"low\":385,\"high\":143,\"medium\":267},\"k8sconfig\":{\"low\":257,\"medium\":172,\"high\":59}}",
"packageManagers": [    
"terraformconfig",
"k8sconfig"
]
```
- `package-managers` was already there, but was not picking the type for this flow, so this is updated to reflect what packageManagers our runs contain. This …

feat: Add iac metadata for analytics [CC-731]

---

src/lib/monitor/dev-count-analysis.ts
test/dev-count-analysis.spec.ts
test/dev-count-analysis.test.ts

This prevents a crash when too many commits are returned in the dev count module. Also fixes a broken test in [Node 10 that limits buffer size to 200*1024](https://nodejs.org/docs/latest-v10.x/api/child_process.html)

Dev Count: limit number of commits returned in git log

---

src/cli/commands/test/index.ts
test/acceptance/cli-test/cli-test.generic.spec.ts

This PR adds an error code to the error object when using the --json or --sarif output types.
When the --json or --sarif options are used we do not add the error code in the thrown error, as opposed to when not using these output types.
This results in the error code not being shown in analytics and in logs.
This PR fixes this behavior by adding the error code of the first found error (as done for non-json/sarif outputs).
The review should start in the src/cli/commands/test/index.ts Line 213, where the error code is added.
The code change is based on the same logic that is done for non-json/sarif outputs, in line 270.
This can be reproduced by running the CLI from local code, and changing the following code:
src/lib/snyk-test/assemble-payloads.ts Line 57, change "/test-dependencies" to …

fix: Add error code to error object for json/sarif test output

---

src/cli/commands/test/iac-local-execution/parsers/terraform-plan-parser.ts
test/jest/unit/iac-unit-tests/terraform-plan-parser.fixtures.ts
test/jest/unit/iac-unit-tests/terraform-plan-parser.spec.ts

Adds unit-tests for Terraform Plan parsing in IaC local exec

test: terraform plan parsing

---

.github/PULL_REQUEST_TEMPLATE.md
.prettierignore

Some of the steps on the PR to-do list (as seen above) are already enforced by GitHub's workflow so we end up doing the same thing twice, and often the to-do list isn't in sync as it isn't enforced anyway.
'Ready for review' -> Use Draft PRs if it isn't so that it's visible in the PR list and isn't mergeable. This lets us use GitHub to filter draft/ready PRs easily.
'Reviewed by Snyk internal team' -> Can be seen in the Reviewers sidebar list, PR list and is enforced at the merge dialog.
Could even remove the "Follows CONTRIBUTING" step as GitHub already prompts first PRs to do so. https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

chore: remove duplicate PR steps

---

help/commands-docs/_EXAMPLES.md
help/commands-docs/iac-examples.md
help/commands-docs/iac.md
test/args.test.ts

This PR adds information on how to use the new --experimental flag, when running either `snyk --help` or `snyk iac --help. It also updates the examples.
Check the Markdown documents for any spelling, formatting errors,wrong wording or examples.
You will need to:
- start docker
- Run `npm run generate-help` to generate the help documents
- Run `node ~/snyk-repos/snyk/dist/cli --help` or `node ~/snyk-repos/snyk/dist/cli  iac --help `
[CC-606]: https://snyksec.atlassian.net/browse/CC-606
When running `snyk --help`:
When running `snyk iac --help`:

feat: Update iac --help documentation to include experimental flag

---

docker/Dockerfile.maven-3.6.3

Dockerfile was pointing to an incorrect version:

Dockerfiles: point maven 3.6.3 to correct location

---

package.json

Update docker-plugin to improve detection of the OS of images.
https://github.com/snyk/snyk-docker-plugin/pull/331
https://snyk.zendesk.com/agent/tickets/9475

fix: update docker-plugin to improve detection of the OS of images

---

src/cli/commands/monitor/process-json-monitor.ts
test/system/cli.test.ts

When failed, snyk monitor —json propagated an invalid json to the user. This is a fix for that issue.
Fixes [this issue](https://snyk.zendesk.com/agent/tickets/9120)
Before:
After:

fix: stringify json output to promise valid json

---

src/cli/commands/test/formatters/format-test-meta.ts

This PR changes the formatted output of the Snyk CLI to NOT display an organization name, if it is undefined.
The CLI currently displays `undefined` for the formatted final output of a test run, if an organization is not defined. We add a check here to not print it if it is undefined.
As we are moving towards the Beta release of the IaC experimental flow, we want to have an org name correctly displayed. 
At this moment, the org name is getting passed from a test endpoint, so there is no easy way to do it without using it in the new experimental flow. 
We will tackle this problem in a next PR, however we don't want to show `undefined` to our users for now, so we skip the organization name.
Run `node ~/snyk-repos/snyk/dist/cli iac test file.tf --experimental` before 
Run `npm run build && …

refactor: Check if org is undefined in the CLI formatted output

---

packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/calculate-relevant-fixes.ts
packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/generate-pins.ts
packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/generate-upgrades.ts
packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap

The change in how `isTransitive` is calculated to allow for provenance based fix also means that this is now more lenient and a dependency that is not in the top level deps in a file is considered to be a transitive. This is needed to allow for changes to be applied in files required in via `-r` https://github.com/snyk/snyk/compare/refactor/unify-calculating-fixes?expand=1#diff-f8c9ac4c7f1aac516985a73192c421f938ee5b35250d07f8adb6305d9d9d0e09R20
`packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/calculate-relevant-fixes.ts`
`cd packages/snyk-fix && npm run test`

feat(@snyk/fix): unify calculating relevant pins & upgrades

---

.circleci/config.yml

This will ensure that cross-package dependencies will be all using the same version

chore: lerna release with exact version

---

src/cli/commands/test/iac-local-execution/parsers/terraform-plan-parser.ts
src/cli/commands/test/iac-local-execution/types.ts
test/fixtures/iac/terraform-plan/tf-plan.json
test/jest/unit/iac-unit-tests/terraform-plan-parser.fixtures.ts
test/jest/unit/iac-unit-tests/terraform-plan-parser.spec.ts
test/smoke/spec/iac/snyk_test_local_exec_spec.sh

Enhances the experimental terraform-plan scanning functionality to do delta scans as a default, instead of a full-state scan as a default.
Changes to `terraform-plan-parser.ts` contain the new logic to extract resource changes.
Then check the new unit-tests `terraform-plan-parser.spec.ts`.
And then the rest.
Please not some renaming was done to differentiate between the full & delta scans.
`snyk iac test ./tf-plan.json --experimental`
After some discussions on the topic, we reached consensus that the default should be a delta scan, and not a full scan.
Soon, a flag will be added to allow customers to control which scan they want with a flag.
https://snyksec.atlassian.net/browse/CC-758

feat: scan terraform plan delta, experimental

---

src/cli/index.ts
src/lib/json-file-output.ts
test/jest/acceptance/cli-json-file-output.spec.ts
test/jest/system/json-file-output.spec.ts

Refactor to extract a function for better testability so we can better and more directly test that we can output JSON to a given absolute path and create directories as required without having to run the entire snyk test from the outside in order to do so.
Tests in test/jest/acceptance/cli-json-file-output.spec.ts can be flakey and one of them in particular, `test --json-file-output can handle an absolute path` was recently skipped to unblock other work.
Where the test was skipped: https://github.com/snyk/snyk/pull/1731/commits/453db4c33571b37076d198875ef928e9e6ff7336

Refactor and improve testing and un-skip skipped test re JSON file output

---

release-scripts/make-binaries.sh

We are targeting the latest tag of pkg-fetch and last evening they introduced a new version with no binaries, so our build broke when it tried to download them.
https://github.com/vercel/pkg-fetch/releases/
Tag 2.7.0 is now deleted but our script tries to find an image from a previous version to match.  The last working version is 2.5
We are targeting non existing versions for those images, eg node14 for alpine. 
To unblock the build temporarily this PR targets specific versions:
```
npx pkg . -t node14.4.0-alpine-x64 -o binary-releases/snyk-alpine
npx pkg . -t node12.18.1-linux-x64 -o binary-releases/snyk-linux
npx pkg . -t node12.18.1-macos-x64 -o binary-releases/snyk-macos
npx pkg . -t node12.18.1-win-x64 -o binary-releases/snyk-win-unsigned.exe
```

Fix: target different Node versions for binaries for pkg-fetch

---

src/cli/commands/test/iac-local-execution/local-cache.ts
test/jest/unit/iac-unit-tests/local-cache.spec.ts
test/smoke/spec/iac/snyk_test_local_exec_spec.sh

This PR removes the use of SNYK_IAC_SKIP_BUNDLE_DOWNLOAD env var which we use to skip the download of the bundle in smoke tests. This was because tests were very explicit and we now have changed them in [PR](https://github.com/snyk/snyk/pull/1765) to be more vague.
It also refactors the unit tests which depended on that flag.
Run tests locally.

refactor: remove SNYK_IAC_SKIP_BUNDLE_DOWNLOAD env var from code

---

.github/workflows/smoke-tests.yml
package.json
scripts/run-smoke-tests-locally.sh
test/smoke/README.md
test/smoke/alpine/entrypoint.sh
test/smoke/docker-root/entrypoint.sh
test/smoke/run-shellspec-win.sh
test/smoke/spec/snyk_auth_spec.sh
test/smoke/spec/snyk_basic_spec.sh
test/smoke/spec/spec_helper.sh

Updates the ad hoc experience of running smoke tests locally
Checkout the readme changes: https://github.com/snyk/snyk/blob/smoke/improve-shellspec/test/smoke/README.md

Improve smoke tests dev experience

---

src/lib/plugins/nodejs-plugin/npm-modules-parser.ts
test/jest/unit/npm-modules-parser.spec.ts

This is to fix a bug where package.json without name property would throw an error.

fix: support package.json missing name property

---

.circleci/config.yml

Removes `SNYK_IAC_SKIP_BUNDLE_DOWNLOAD` env var from circleCi. 
All references in code have already been removed in previous PR but the flag has not been removed from the .config.yml
Search for references and confirm there is none.

refactor: Remove unused env var from circleci config

---

src/cli/commands/test/iac-local-execution/local-cache.ts
test/jest/unit/iac-unit-tests/local-cache.spec.ts

We use rimraf to delete a directory and also have a check to see if the path exists and if it is a directory.
This is already done internally from rimraf, as pointed on a [previous PR](https://github.com/snyk/snyk/pull/1762#pullrequestreview-622187515) , and here https://github.com/isaacs/rimraf.
So now we remove the unneeded check.

refactor: remove if guard that checks if dir exists

---

release-scripts/make-binaries.sh

We started targetting specific node versions for our binaries in this PR https://github.com/snyk/snyk/pull/1770
This was breaking our builds. Vercel team has now fixed their side of `pkg` and we do not need to target specific versions anymore.
Relevant links:
- https://github.com/vercel/pkg-fetch/issues/137
- https://github.com/vercel/pkg/releases/tag/4.5.1

refactor: Update release scripts to the previous version

---

src/cli/commands/test/open-source-sarif-output.ts
test/jest/unit/sarif.spec.ts

Adds support for CRITICAL severity in the `--sarif` output format

feat: map 'critical' severity to 'error' in sarif format

---

help/commands-docs/_ENVIRONMENT.md
src/lib/request/request.ts
test/request.test.ts

Follow up to the #1771 
This PR adds an optional ennvar `SNYK_HTTP_PROTOCOL_UPGRADE` to disable the behavior to upgrade `http` endpoints to `https`.
Fixes the behavior about query strings, that could've lacked the `/?` characters
It also updates Help documentation about `HTTP(S)_PROXY` envvar.

feat: introduce envvar to control HTTP-HTTPS upgrade behavior

---

src/cli/commands/test/iac-local-execution/file-loader.ts
src/cli/commands/test/iac-local-execution/file-parser.ts
src/cli/commands/test/iac-local-execution/file-scanner.ts
src/cli/commands/test/iac-local-execution/file-utils.ts
src/cli/commands/test/iac-local-execution/local-cache.ts
src/cli/commands/test/iac-local-execution/parsers/kubernetes-parser.ts
src/cli/commands/test/iac-local-execution/parsers/terraform-file-parser.ts
src/cli/commands/test/iac-local-execution/parsers/terraform-plan-parser.ts
src/cli/commands/test/iac-local-execution/results-formatter.ts
src/cli/commands/test/iac-local-execution/types.ts
test/jest/unit/iac-unit-tests/file-loader.spec.ts
test/jest/unit/iac-unit-tests/file-parser.fixtures.ts
test/jest/unit/iac-unit-tests/file-parser.spec.ts
test/jest/unit/iac-unit-tests/file-scanner.spec.ts
test/jest/unit/iac-unit-tests/local-cache.spec.ts
test/jest/unit/iac-unit-tests/terraform-plan-parser.fixtures.ts
test/jest/unit/iac-unit-tests/terraform-plan-parser.spec.ts
test/smoke/spec/iac/snyk_test_local_exec_spec.sh

Co-authored-by: ipapast <ipapast@users.noreply.github.com>
Adds error types for all potential IaC paths in the new experimental flow that can break.
Each error now has a unique error code that will be visible in analytics and in the debug logs.
Todo:

chore: Add error types and debug logs for IaC [CC-754, CC-764]

---

packages/snyk-fix/src/plugins/python/handlers/pip-requirements/index.ts
packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/calculate-relevant-fixes.ts
packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/generate-pins.ts
packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/generate-upgrades.ts
packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/requirements-file-parser.ts
packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/standardize-package-name.ts
packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/update-dependencies.spec.ts
packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/workspaces/basic-with-newline/prod.txt
packages/snyk-fix/test/unit/plugins/python/handlers/update-dependencies/standardize-package-name.spec.ts

Standadrize pip package names to adhere to docs: https://www.python.org/dev/peps/pep-0426/#name
> All comparisons of distribution names MUST be case insensitive, and MUST consider hyphens and underscores to be equivalent.
packages/snyk-fix/src/plugins/python/handlers/pip-requirements/update-dependencies/standardize-package-name.ts

fix: standardize pip package names

---

src/lib/plugins/sast/index.ts
test/jest/unit/snyk-code-test.spec.ts

[COD-152]
The pr adds analytics to snykcode flow in the cli 
[COD-152]: https://snyksec.atlassian.net/browse/COD-152

[COD-152] feat: analytics added to snykcode flow

---

src/cli/commands/test/validate-credentials.ts
src/lib/api-token.ts
src/lib/snyk-test/assemble-payloads.ts
src/lib/snyk-test/run-test.ts
test/acceptance/docker-token.test.ts
test/acceptance/fake-server.ts
test/jest/acceptance/oauth-token.spec.ts

Adds support for providing an oauth token as authorization using an environment variable, `SNYK_OAUTH_TOKEN`.
- Get hold of an OAuth access token for your user on the Dev server (Extensibility group can help with that).
- Set an environment variable with your access token, e.g. `export SNYK_OAUTH_TOKEN=mytoken`
- Point the CLI to our oauth endpoint, e.g: `snyk-dev set config endpoint=`snyk-dev config set endpoint=https://api.dev.snyk.io/v1`
- Run a test against a project, e.g: `snyk-dev test`
We are in the process of providing an OAuth flow into Snyk for third party integrations and partners. Adding OAuth token support to the CLI allows better integration into these workflows so that they can use the same mechanism to connect their systems to Snyk and then perform various commands on …

feat: adds oauth token support for the test command

---

src/cli/args.ts
src/lib/types.ts
test/jest/unit/lib/commands/fix/__snapshots__/fix.spec.ts.snap
test/jest/unit/lib/commands/fix/fix.spec.ts

Expose `---dry-run` as a `snyk fix` parameter. No help text while this is in Beta.
Update existing tests to ensure both `dryRun` and `quiet` get passed though to the `@snyk/fix` package
Relies on https://github.com/snyk/snyk/pull/1785 being merged that moves the tests

feat: snyk fix --dry-run and --quiet mode

---

src/cli/commands/test/iac-local-execution/file-parser.ts
src/cli/commands/test/iac-local-execution/parsers/kubernetes-parser.ts
src/cli/commands/test/iac-local-execution/types.ts
test/fixtures/iac/kubernetes/helm-config.yaml
test/jest/unit/iac-unit-tests/file-parser.spec.ts
test/smoke/spec/iac/snyk_test_local_exec_spec.sh

This PR fixes the issue where YAML Helm files were scanned incorrectly. 
Instead, we now check if a yaml file contains a template and throw a `HelmFileNotSupportedError` error on that case.
We also add a new smoke test case and a new unit test case.
In the `parser.ts`:
-  we now have a validateYamlFile function for the 'yml' and 'yaml' cases. 
- This function will get the fileContent, split it by line and create an array of strings (every line is a new string).
- Then, we check if there is a template, line by line. A template is considered a line that has both `{{` and `}}` chars.
- The moment we detect a template, we throw a `HelmFileNotSupportedError` with a useful user error message and a new error code.
- Run `node ~/snyk-repos/snyk/dist/cli iac test …

refactor: Scanning Helm files for iac test fails [CC-768]

---

package.json

Error messages regarding missing "mix" and "hex" packages improved.

fix: improved error messages in elixir

---

src/cli/commands/fix/get-display-path.ts
test/jest/unit/lib/commands/fix/get-display-path.spec.ts

Instead of displaying `.` for current directory show directory name being tested similar to `snyk test` command.
**Before**:
**After**:

fix: display current folder instead of . for fix

---

packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
packages/snyk-fix/src/plugins/python/handlers/pip-requirements/index.ts
packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/__snapshots__/update-dependencies.spec.ts.snap
packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/update-dependencies.spec.ts
packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
packages/snyk-fix/test/unit/lib/output-formatters/__snapshots__/show-results-summary.spec.ts.snap

Tweak the user output slightly:
- remove extra `.`
- add extra space before the `Successful Fixes title`
- show the extra folder in the changes messages so the manifest names match always

feat: include full path to files to match targetFiles

---

src/cli/commands/fix/validate-fix-command-is-supported.ts
test/smoke/spec/snyk_fix_spec.sh
test/validate-fix-command-is-supported.spec.ts

Bubble up an auth error and display the message rather than say that the feature is not supported.

fix: bubble up auth error on fix

---

packages/snyk-fix/src/plugins/python/handlers/pip-requirements/index.ts
packages/snyk-fix/src/plugins/types.ts
packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/__snapshots__/update-dependencies.spec.ts.snap
packages/snyk-fix/test/acceptance/plugins/python/update-dependencies/update-dependencies.spec.ts

When an item was already fixed mention though with file
- Update the messaging when a certain file has already been fixed as it is included via another scanned file to point to the original file though which fixes have been applied. We do not try to apply upgrades again to a fixed file as there is nothing left to fix & the upgrades will fail

feat: show which parent fixes occurred in

---

packages/snyk-fix/src/index.ts
packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
packages/snyk-fix/src/plugins/python/index.ts
packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
packages/snyk-fix/test/unit/lib/output-formatters/__snapshots__/show-results-summary.spec.ts.snap
packages/snyk-fix/test/unit/lib/output-formatters/show-results-summary.spec.ts

Only show summary if any items were fixed, failed, unresolved. If a plugin is called with empty test results return `No successful fixes` only.
Changes made as part of a design review of the CLI output

fix(@snyk/fix): hide summary unless any failed, fixed or unresolved

---

package.json

Add support for Pipfile's nested within a project using the `--file=...` flag

fix: add support for Pipfiles nested in a project

---

package.json
src/cli/commands/test/iac-local-execution/results-formatter.ts
src/cli/commands/test/iac-local-execution/types.ts
test/jest/unit/iac-unit-tests/results-formatter.fixtures.ts
test/jest/unit/iac-unit-tests/results-formatter.spec.ts

This PR adds the cloud-config-parser library which is a utility library for identifying the issue path in a YAML/JSON/HCL file and returning the relevant line number in order to highlight the relevant line to the users in their files.
This was an existing functionality in the old flow and it is now added in the `--experimental` flow. 
This way, we can add a line number for the specific issue path when running a test command with the `--json` output option.
If the parser library fails for some reason, we capture this in Debug and we set lineNumber as '-1' to indicate this.
- Package.json for the library
- Results-formatter.ts for adding the function where we call the parser functions to get the lineNumber.
- Run `npm run build` on this branch
- Run `node ~/snyk-repos/snyk/dist/cli iac test …

fix: JSON output for IaC shows line number [CC-680]

---

src/cli/commands/test/iac-local-execution/file-loader.ts
src/cli/commands/test/iac-local-execution/index.ts
test/args.test.ts
test/jest/unit/iac-unit-tests/file-loader.fixtures.ts
test/jest/unit/iac-unit-tests/file-loader.spec.ts
test/smoke/spec/iac/snyk_test_local_exec_spec.sh

This PR adds the already defined `--detection-depth` flag to the `--experimental` flow for IaC. The flag was already defined and used in non-experimental mode, so this PR just passes the CLI options and `detectionDepth` value to the correct function. Unit tests and smoke tests were added to verify functionality, as well as tests to make sure that the flag gets initialised correctly when passed to the CLI.
The flow starts in `src/cli/commands/test/iac-local-execution/index.ts` by passing the `options` variable to the `loadFiles ` function. The rest of the code changes are in `src/cli/commands/test/iac-local-execution/file-loader.ts` and make use of the existing `makeDirectoryIterator` function which is used by the non-experimental flow.
1. Run `npm run build`
2. Run `node ./dist/cli iac …

feat: Add detection-depth flag to IaC for directory scan [CC-769]

---

src/cli/commands/test/iac-local-execution/results-formatter.ts
src/cli/commands/test/iac-local-execution/types.ts
test/jest/unit/iac-unit-tests/results-formatter.fixtures.ts

This PR enhances the JSON file output for the local execution (experimental) flow of IaC so it matches better with the original flow. 
[CC-679]
The `formatScanResult` function in `src/cli/commands/test/iac-local-execution/results-formatter.ts` creates the structure and contents that will end up in the JSON file output. The changes in `src/cli/commands/test/iac-local-execution/types.ts` are the corresponding type changes for the new fields.
1. Download the `deployment_singleissue.yaml` attached to the JIRA task under the cloned `snyk` repo
2. Build the CLI using `npm run build`
3. Get the original JSON file output: `node ./dist/cli iac test deployment_singleissue.yaml --json-file-output=original.json`
4. Get the experimental JSON file output: `node ./dist/cli iac test …

feat: enhance JSON file output for experimental IaC [CC-679]

---

.circleci/config.yml
release-scripts/handle-failed-release.sh

Adds alerting that'd be fired if one of the CircleCI steps during releasing fails.

chore: send alert when release fails

---

packages/snyk-fix/src/plugins/python/index.ts

On error also stop spinner as success as we log the error and keep going

fix: stop spinner on errors too for @snyk/fix python plugin

---

package.json
packages/snyk-fix/src/plugins/python/index.ts
src/cli/commands/fix/index.ts
src/cli/commands/fix/validate-fix-command-is-supported.ts

- Swap out ℹ️ for ⏯️  icon in spinner
- fix clearing bug when multiple paths are tested with `snyk fix path1 path2`
- bump @snyk/fix packages to latest version that has small output improvements (e.g. `Previously fixed` => `Fixed through manifestPath`)
- style the failed test errors
- spacing
**Before**
**After**

Fix: fix spinner multiple paths

---

package.json

change in code client removed axios default proxy support, therefore it
won't be clashing with our own proxy support
Bumps code client version, therefore fixes problems with proxy.

fix: support proxy env vars for code

---

src/cli/commands/test/iac-local-execution/extract-line-number.ts
src/cli/commands/test/iac-local-execution/results-formatter.ts

Move the two functions relevant to getting line numbers to a new module file. 
The results formatter was getting bigger and not easy enough to read, so with this PR I am trying to seperate the concerns of the modules.

refactor: Move linenumber function to its own module.

---

src/cli/commands/fix/convert-legacy-tests-results-to-fix-entities.ts
src/lib/ecosystems/types.ts

Drop `any` and use the @snyk/fix expected type. 
Use expected severity type

chore: use @snyk/fix entity type in conversion

---

src/cli/commands/test/iac-local-execution/file-parser.ts
src/cli/commands/test/iac-local-execution/parsers/kubernetes-parser.ts
src/cli/commands/test/iac-local-execution/parsers/terraform-plan-parser.ts
src/cli/commands/test/iac-local-execution/types.ts
test/jest/unit/iac-unit-tests/file-parser.fixtures.ts
test/jest/unit/iac-unit-tests/file-parser.spec.ts
test/jest/unit/iac-unit-tests/terraform-plan-parser.fixtures.ts
test/jest/unit/iac-unit-tests/terraform-plan-parser.spec.ts

This PR removes the Terraform Plan file name restriction, so that we can run IaC on Terraform Plan files that have any name, not just `tf-plan.json`. 
[CC-793]
- Start with the `tryParseIacFile` function in `src/cli/commands/test/iac-local-execution/file-parser.ts`. For JSON files, we can have either Kubernetes files or Terraform Plans.
- Have a look at `tryParsingTerraformPlan` and `tryParsingKubernetesFile` in their individual parsers and notice that first we parse the files (using `JSON.parse` and `YAML.safeLoadAll` respectively)
- This PR moves this parsing logic to `src/cli/commands/test/iac-local-execution/file-parser.ts` file, so that we can do any non-parser specific transformations before we call `tryParsingTerraformPlan` and `tryParsingKubernetesFile`
- As a result, this PR also …

feat: remove Terraform plan file name restriction [CC-793]

---

packages/snyk-fix/package.json
packages/snyk-fix/src/plugins/python/get-handler-type.ts
packages/snyk-fix/src/plugins/python/handlers/is-supported.ts
packages/snyk-fix/src/plugins/python/handlers/pip-requirements/index.ts
packages/snyk-fix/src/plugins/python/handlers/valdidate-required-data.ts
packages/snyk-fix/src/plugins/python/index.ts
packages/snyk-fix/src/plugins/types.ts
packages/snyk-fix/test/unit/plugins/python/handlers/pip-requirements/get-handler-type.spec.ts
packages/snyk-fix/test/unit/plugins/python/is-supported.spec.ts

- drop micromatch it was under used and not needed, the check is much simpler here as CLI already had done the work of classifying the project type as python.
- add a new check with tests for a project that has a `Pipfile` manifest  + tests (nothing is using it yet)

Feat: pipfile handler check & share common functionality

---

help/commands-docs/iac-examples.md
src/cli/commands/test/iac-local-execution/file-parser.ts

This PR updates the `snyk --help` command to remove the note about the Terraform plan file name restriction.
Have a look at the markdown document for any spelling mistakes.
Run `npm run generate-help` and have a look at the sections that changed.
The code changes were delivered under https://github.com/snyk/snyk/pull/1822.
https://snyksec.atlassian.net/browse/CC-793

docs: remove help note for tf-plan.json restriction [CC-793]

---

test/cli-alert/src/index.ts

https://developer.pagerduty.com/docs/events-api-v2/trigger-events/
> Submitting subsequent events for the same dedup_key will result in those events being applied to an open alert matching that dedup_key. Once the alert is resolved, any further events with the same dedup_key will create a new alert (for trigger events) or be dropped (for acknowledge and resolve events).
This change groups together repeating trigger events caused by smoke tests failing, meaning that PagerDuty won't alert us again and again if the first alert is still open.

test: add dedup key to enable alert grouping

---

packages/snyk-fix/src/lib/errors/common.ts
packages/snyk-fix/src/lib/errors/failed-to-parse-manifest.ts
packages/snyk-fix/src/lib/errors/invalid-workspace.ts
packages/snyk-fix/src/lib/errors/missing-file-name.ts
packages/snyk-fix/src/lib/errors/no-fixes-applied.ts
packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
packages/snyk-fix/test/unit/lib/output-formatters/__snapshots__/show-results-summary.spec.ts.snap

Instead of repeating the messaging under each item, show it once at the end with more information so users can debug & reach out to support if that does not help.

feat: show debug mode tip if something failed

---

src/cli/commands/fix/convert-legacy-tests-results-to-fix-entities.ts
src/cli/commands/fix/index.ts
test/jest/unit/lib/commands/fix/__snapshots__/convert-legacy-tests-results-to-fix-entities.spec.ts.snap
test/jest/unit/lib/commands/fix/convert-legacy-tests-results-to-fix-entities.spec.ts

- send scanned `root` / `path` to @snyk/fix 
- send original CLI options to @snyk/fix 
@snyk/fix requires to know the original options & path for situations where a package manager command has to be run. (E.g. `--command` for Python which provides which Python interpreter to use)

feat: send options & path to @snyk/fix

---

packages/snyk-fix/src/lib/output-formatters/format-unresolved-item.ts
packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
packages/snyk-fix/src/types.ts
packages/snyk-fix/test/unit/lib/output-formatters/__snapshots__/format-unresolved-item.spec.ts.snap
packages/snyk-fix/test/unit/lib/output-formatters/format-unresolved-item.spec.ts

- optionally allow items that errored during fix to show a user `tip` to help users debug the issue locally.

feat: errored items can show a tip

---

package.json
src/lib/monitor/utils.ts
test/jest/unit/lib/monitor/utils.spec.ts

Elixir projects can be `umbrella` projects. These projects can have multiple manifests and dependency declarations so each manifest is scanned individually. 
However if the `--project-name` is provided when running `monitor` each of the sub projects get given the same name so overwrite each other in the ui. This adds a check to use a provided projectName from the scanned projects instead

fix: supports using --project-name flag with hex umbrella projects

---

package.json

Fixes the currently failing Smoke tests under Yarn installation.
This resolve an issue with Node prematurely closing a file descriptor.

Bump gradle plugin to fix macOS issue

---

src/cli/commands/test/iac-local-execution/index.ts
src/cli/commands/test/iac-local-execution/org-settings/apply-custom-severities.ts
src/cli/commands/test/iac-local-execution/org-settings/get-iac-org-settings.ts
src/cli/commands/test/iac-local-execution/results-formatter.ts
src/cli/commands/test/iac-local-execution/types.ts
test/jest/unit/iac-unit-tests/apply-custom-severities.spec.ts
test/jest/unit/iac-unit-tests/results-formatter.fixtures.ts
test/jest/unit/iac-unit-tests/results-formatter.spec.ts

- This PR fetches organization settings data related to IaC, including customPolicies (custom severities) from an external endpoint. These are needed to be used for updating the local violatedPolicies with any custom severities before formatting the results to the user.
- We will also need the metadata for printing other useful info, such as organization name, etc  in a different PR.
There are 2 files of interest:
-  `src/cli/commands/test/iac-local-execution/get-iac-org-settings.ts` to fetch the settings
- `src/cli/commands/test/iac-local-execution/apply-custom-severities.ts` to call the GET endpoint, update the existing severities with new ones
- Check that also a severity of `'none'` now results to the file being filtered out of the results (this happens in results-formatter.ts).
- Run …

Feat: Support custom severities from Org IaC Settings

---

src/cli/commands/test/iac-local-execution/assert-iac-options-flag.ts
src/cli/commands/test/iac-local-execution/types.ts

This commit adds a new error code to the FlagError so we can use the code when debugging.
1. Build the CLI by running `npm run build`
2. Run `node ./dist/cli iac test --experimental test/fixtures/iac/terraform-plan --ignore-policy`
When trying to build the SLO dashboard for the IaC experimental flow we noticed that there are some errors without an `error_code`, specifically ones resulting from `FlagError`. By adding this error code, we are able to debug and differentiate between actual errors and expected errors.
https://snyksec.atlassian.net/browse/CC-777

fix: add error code to FlagError

---

package.json
src/lib/detect.ts
test/acceptance/cli-test/cli-test.elixir.spec.ts

Adds the auto-detect feature to elixir ecosystem (hex package manager)

feat: add auto detect feature for hex package manager

---

packages/snyk-fix/src/lib/output-formatters/format-display-name.ts
packages/snyk-fix/src/lib/output-formatters/format-successful-item.ts
packages/snyk-fix/src/lib/output-formatters/format-unresolved-item.ts
packages/snyk-fix/src/plugins/python/handlers/pip-requirements/index.ts
packages/snyk-fix/src/types.ts
packages/snyk-fix/test/acceptance/plugins/python/handlers/update-dependencies/__snapshots__/update-dependencies.spec.ts.snap
packages/snyk-fix/test/acceptance/plugins/python/handlers/update-dependencies/extract-provenance.spec.ts
packages/snyk-fix/test/acceptance/plugins/python/handlers/update-dependencies/update-dependencies.spec.ts
packages/snyk-fix/test/helpers/generate-entity-to-fix.ts
packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap

when  users run `snyk fix --all-projects` the path is `.` and all manifest files are correctly referenced from here e.g 'requirements.txt'
when users run `snyk fix path/to-folder --all-projects`  the manifest are still being referenced in relation to the provied path so we end up with 'requirements.txt' and if many are found in different folders you can't tell them apart in the output.
Now that CLI sends `path` to @snyk/fix use it to reference the full path relative to where the `snyk fix` command is run
`packages/snyk-fix/src/lib/output-formatters/format-display-name.ts`
- When running `snyk fix test/acceptance/plugins/python/handlers/update-dependencies/workspaces --all-projects`:
- When running `snyk fix test/acceptance/plugins/python/handlers/update-dependencies/workspaces …

Feat: use path in filenames

---

src/cli/commands/test/iac-local-execution/index.ts
src/cli/commands/test/iac-local-execution/org-settings/apply-custom-severities.ts
src/cli/commands/test/iac-local-execution/results-formatter.ts
src/cli/commands/test/iac-local-execution/types.ts
test/jest/unit/iac-unit-tests/apply-custom-severities.spec.ts
test/jest/unit/iac-unit-tests/index.spec.ts
test/jest/unit/iac-unit-tests/results-formatter.fixtures.ts
test/jest/unit/iac-unit-tests/results-formatter.spec.ts

This PR uses the org details we retrieve from registry to populate the results for the JSON file output flag, as well as for the organisation name in the CLI results.
The code flow can be read in the order of the changed files. This PR moves the `getIacOrgSettings` function call to the main index file, where we compute the org settings and then pass the contents of `customPolicies` field to the `applyCustomSeverities` call and then the contents of the `meta` field to `formatScanResults` in order to include the missing fields into the result.
1. Build the CLI using `npm run build`
2. Download `deployment_singleissue.yaml` from the Jira ticket
2. Run `node ./dist/cli iac test --experimental deployment_singleissue.yaml --json-file-output=experimental.json`
3. `node ./dist/cli iac test …

feat: include org details in JSON file output [CC-772]

---

package.json

Adds support for the scanning of peer and optional dependencies in node projects

feat: allow peerDeps and optionalDeps from manifests in npm projects

---

src/cli/commands/test/index.ts
test/acceptance/cli-test/iac/cli-test.iac-dir.spec.ts
test/acceptance/cli-test/iac/cli-test.iac-k8s.spec.ts
test/smoke/spec/iac/snyk_test_local_exec_spec.sh

This PR makes sure that when the `snyk iac test --experimental` command is run with the extra `--json` flag on a file with no vulnerabilities, the command returns successfully.
The first commit contains a new smoke test that covers this edge case. It modifies an existing test by adding the `--json` flag. As we can see from Circle, this new smoke test fails because the command does not return successfully. However, the original smoke test without the `--json` flag returns successfully.
The new IaC experimental flow returns the valid scannings (including vulnerabilities) separately from failed scannings (parse errors or any other errors to return to the user). So, the code needs to check first that there are no vulnerabilities (since there is an if statement a few lines below that deal with …

fix: IaC run with no vulnerabilities and --json flag should be successful [CC-805]

---

package.json

Older versions of update-notifier suggested updating to older versions.
Fix in this PR: https://github.com/yeoman/update-notifier/pull/192
Released in 5.0.0: https://github.com/yeoman/update-notifier/releases
This PR upgrades update-notifier from 4.1.0 to 5.1.0. The major bump was dropping Node 8 support which is fine for us as we only support Node 10 and above.

fix: prevent update notifications to older versions

---

src/cli/index.ts
test/acceptance/cli-test/iac/cli-test.iac-utils.ts
test/acceptance/fake-server.ts

This PR rolls out the experimental CLI by using a feature flag. We want the experimental flow to be the default if the feature flag is enabled or if the `--experimental` flag is provided when running the CLI.
- Start in `src/cli/index.ts`, where if `iac` is running we now make a call to get the org name (i.e. `getIacOrgSettings`), required for checking if the experimental feature flag is enabled. 
- We only make the extra call to registry to see if the feature flag is enabled if the `experimental` is not passed, to minimise the number of network calls we need. 
- These checks are here instead of `src/cli/commands/test/iac-test-shim.ts` because the analytics report the `args` object and we use that object in our SLO dashboard.
The acceptance tests had to be modified with a new API call …

feat: use feature flag to enable local exec [CC-790]

---

package.json

This PR updates the plugin version to add the algorithm prefix ('sha256:') to the imageId.
Run container test with this CLI version on a docker image will create a project where the imageId of the project test snapshot has a 'sha256:' prefix.
The full imageId for docker images should contain the algorithm prefix (as can be seen when running 'docker inspect' command). The new version of the plugin adds this prefix.
https://snyksec.atlassian.net/browse/DC-1195

feat: Update snyk-docker-plugin to v4.20.1

---

src/cli/commands/test/iac-local-execution/local-cache.ts

Replaces the IaC wasm bundle downloading url to be fetched from `static.snyk.io`.

fix: wasm bundle url to snyk domain

---

package.json

- We were wrongly considering a Gradle root project as subproject

fix: excluding gradle root project name from allSubProjectNames

---

.circleci/config.yml
release-scripts/upload-artifacts.sh

Currently we create a published release then upload artifacts. This means:
- If we fail to upload artifacts, we'll have a broken release.
- Someone (especially automation) can grab a release but not find any artifacts.
So we should use Draft Releases to avoid this.
GitHub CLI doesn't have a `release update` command.
https://github.com/cli/cli/issues/1997
So the alternative is to use the GitHub API. However, updating requires knowing the `release_id` or querying for it before updating which is very messy.
https://docs.github.com/en/rest/reference/repos#update-a-release
`gh release create` supports draft releases if you provide files in a single command.
https://github.com/cli/cli/blob/trunk/pkg/cmd/release/create/create.go#L286
So I've squashed the release and upload steps into a single …

chore(ci): use draft release until files are uploaded

---

src/cli/commands/test/index.ts
src/lib/snyk-test/iac-test-result.ts
test/fixtures/iac/no_vulnerabilities/pod-invalid.yaml
test/fixtures/iac/no_vulnerabilities/pod-privileged.yaml
test/smoke/spec/iac/snyk_test_local_exec_spec.sh

This PR improves the consistency between running the experimental flow with the `--json` flag or without. We want the two commands to fail and succeed the same way, regardless of the flag's presence. This way we don't incorrectly report failed commands in our analytics.
Start in `src/lib/snyk-test/iac-test-result.ts`, where we add a new field to our IaC results, `ok`, which changes based on whether there are any vulnerabilities or not. This field fixes the original problem **and** removes the need for custom IaC checks in `src/cli/commands/test/index.ts` (added for https://snyksec.atlassian.net/browse/CC-805).
1. Build the CLI: `npm run build`
2. Run it on a directory containing a mix of valid and invalid files, with an without the `--json` flag:
- contains one valid file with one …

fix: consistent command termination between --json and no --json flag

---

package.json

While processing Gradle snykGraphs from extractedJSON to depGraph,
projectName is generated using the basename of the rootDir,
we were not handling it if by any chance it was null or undefined.
Now that we are handling it properly, we are preventing possible scanning error.

fix: gradle scanning error due of mishandled root value

---

packages/snyk-fix/src/types.ts
packages/snyk-fix/test/acceptance/plugins/python/handlers/pip-requirements/update-dependencies/update-dependencies.spec.ts
packages/snyk-fix/test/helpers/generate-entity-to-fix.ts
packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
src/lib/types.ts

CLI now sends down the options each entity was tested with, define this in @snyk/fix and pass it through ready to be used when we start running commands that require `python` version.

feat(@snyk/fix): propagate cli test options

---

package.json

monitoring container images with app-vulns
will now ignore jar files paths that contain gradle/cache
Bumping `snyk-docker-plugin` to include a fix that excludes paths matching `gradle/cache` when extracting `jar` files from a container image.
Monitor container image with a `jar` in a path that contains `gradle/cache`

fix: exclude gradle/cache path when extracting jars

---

help/commands-docs/iac.md
src/cli/commands/test/iac-local-execution/assert-iac-options-flag.ts
src/cli/commands/test/iac-local-execution/file-parser.ts
src/cli/commands/test/iac-local-execution/index.ts
src/cli/commands/test/iac-local-execution/types.ts
test/jest/unit/iac-unit-tests/assert-iac-options-flag.spec.ts
test/smoke/spec/iac/snyk_test_local_exec_spec.sh

Adds a new flag that supports scanning the full state of a terraform plan (the default is scanning only the delta).
```
snyk iac test tfplan.json --scan=resource-changes --experimental
snyk iac test tfplan.json --scan=planned-values --experimental
```
```
New flag:
src/cli/commands/test/iac-local-execution/types.ts
src/cli/commands/test/iac-local-execution/assert-iac-options-flag.ts
Updated control flow:
src/cli/commands/test/iac-local-execution/index.ts
src/cli/commands/test/iac-local-execution/file-parser.ts
Tests:
test/jest/unit/iac-unit-tests/assert-iac-options-flag.spec.ts
test/smoke/spec/iac/snyk_test_local_exec_spec.sh
Documentation:
help/commands-docs/iac.md
```
https://snyksec.atlassian.net/browse/CC-819
https://snyk.slack.com/archives/CS61093QC/p1619695624205800 …

feat: tf plan full scan flag support

---

src/cli/index.ts

Parse args as a first things, before other modules are required.
That will allow others to pick arguments.

fix: propagate argument to all modules

---

package.json
src/lib/detect.ts

Remove redundant [lodash.endswith](https://www.npmjs.com/package/lodash.endswith) library
The change affects only one comand `snyk test` the test scenario is described below
```bash
snyk test /path/to/any/package/with/known/manifest/file pathB --project-name=ANY
```
Expected output to stderr:
`Not a recognised option did you mean --file=/Users/jan/projects/customer-bugs/snyk-poetry-bug/Pipfile? Check other options by running snyk --help`
As a part of working on other ticket I've noticed that we use `lodash.endswith` only in one place and it can easily be removed.

chore: remove redundant lodash.endswith package

---

src/cli/commands/fix/index.ts
test/fixtures/snyk-fix/test-result-pip-no-vulns.json
test/jest/unit/lib/commands/fix/fix.spec.ts

Improve exit code to help action `snyk fix` output when composing inside pipelines/scripts.
- If `snyk test` failed => error ❌ 
- If `snyk test` returned no vulnerable results => success ✅ 
- If `snyk fix` had some errors and nothing was fixed => error ❌ 
- If `snyk fix` fixed anyrying at all => success ✅

feat: exit code 0 if nothing is vulnerable

---

src/cli/commands/test/iac-local-execution/results-formatter.ts
src/cli/commands/test/iac-output.ts
src/lib/snyk-test/iac-test-result.ts
test/acceptance/cli-test/iac/cli-test.iac-utils.ts
test/jest/unit/iac-unit-tests/results-formatter.fixtures.ts

This PR adds `documentation` links to the IaC `--json` and `--sarif` outputs.
For each issue, we will present a link for the relevant public documentation page.
Run IaC test (new flow / experimental) with json/sarif output
**Json output**
**Sarif output**
**Regular output - not affected**

refactor: iac documentation url in outputs

---

package.json
src/lib/detect.ts
src/lib/package-managers.ts
test/acceptance/cli-monitor/cli-monitor.acceptance.test.ts
test/acceptance/cli-test/cli-test.all-projects.spec.ts
test/acceptance/cli-test/cli-test.python.spec.ts
test/jest/system/snyk-test/python/fixtures/pyproject-with-poetry/Pipfile
test/jest/system/snyk-test/python/fixtures/pyproject-with-poetry/Pipfile.lock
test/jest/system/snyk-test/python/fixtures/pyproject-with-poetry/poetry.lock
test/jest/system/snyk-test/python/fixtures/pyproject-with-poetry/pyproject.toml
test/jest/system/snyk-test/python/fixtures/pyproject-without-poetry/Pipfile
test/jest/system/snyk-test/python/fixtures/pyproject-without-poetry/Pipfile.lock
test/jest/system/snyk-test/python/fixtures/pyproject-without-poetry/pyproject.toml
test/jest/system/snyk-test/python/snyk-test-pyproject.spec.ts

Fix invalid detection of poetry project based solely on presence of `pyproject.toml`. Fixes https://github.com/snyk/snyk/issues/1802
Before we assumed that poetry package manager is present if `pyproject.toml` exists in a folder structure.
The solution is to parse  rely on `poetry.lock` alone to determine if project uses poetry or not.
Run the test cases below
2 testcases:
1. Run `snyk test` for project with `pyproject.toml` that doesn't use poetry
```bash
npm i
npm run build
cd test/jest/system/snyk-test/python/fixtures/pyproject-without-poetry/
pipenv install
cd -
node dist/cli/index.js test test/jest/system/snyk-test/python/fixtures/pyproject-without-poetry/ --all-projects
```
Expected result: only one file package manager is recognised pip for `Pipfile` manifest
2. Run `snyk test` for …

fix: fix invalid poetry detection

---

test/jest/system/json-file-output.spec.ts

I've noticed this JSON test tends to fail now and then so hopefully these changes should make it more reliable.
- Setup and teardown is now encapsulated in a single model.
- Using `afterEach` instead of try/catch.
- Less repetition, less to go wrong.
- The spy was useless as: 
- If the file exists, it will be read and asserted in the next assertion.
- If directories aren't made, it will fail to write.
- If directories already exist and the implementation incorrect tries to make them again, that will also fail the test.

test: improve cleanup for unreliable json test

---

src/cli/commands/test/iac-local-execution/results-formatter.ts
src/cli/commands/test/iac-local-execution/types.ts
test/jest/unit/iac-unit-tests/apply-custom-severities.spec.ts
test/jest/unit/iac-unit-tests/results-formatter.fixtures.ts
test/jest/unit/iac-unit-tests/results-formatter.spec.ts

removes a redundant call to extract line-number in IAC scans whenever the `sarif` or `json` flags are not passed, as it is not being used in the regular default output and has been proved to be quite slow.
https://snyksec.atlassian.net/browse/CC-833

fix: redundant line number extraction call

---

src/cli/commands/monitor/index.ts
src/lib/api-token.ts
src/lib/ecosystems/monitor.ts
src/lib/ecosystems/test.ts
src/lib/monitor/index.ts
test/jest/acceptance/oauth-token.spec.ts

Similar to https://github.com/snyk/snyk/pull/1788, adds OAuth token support for the `monitor` command
* Get hold of an OAuth access token for your user (Extensibility group can help with that).
* Set an environment variable with your access token, e.g. `export SNYK_OAUTH_TOKEN=mytoken`
* Point the CLI to our oauth endpoint, e.g: `snyk-dev set config endpoint=https://api.snyk.io/v1`
* Run a monitor against a project, e.g: snyk-dev monitor

feat: support oauth token for monitor

---

package.json

Previously we were validating if the root cwd value being passed down
from cli was either null or undefined, skipping empty string as an invalid case.
With this pr we are adding empty string as an invalid case and avoid
its usage as a gradle project name. What is the outcome? prevent
`Invalid DepGraph` error during scanning test/monitor phases

fix: gradle project name being empty string

---

packages/snyk-fix/src/index.ts
packages/snyk-fix/src/lib/issues/total-issues-count.ts
packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
packages/snyk-fix/test/acceptance/plugins/python/handlers/pip-requirements/update-dependencies/update-dependencies.spec.ts
packages/snyk-fix/test/helpers/generate-entity-to-fix.ts

- use nullish operator to ensure that fallback is only used when right hand side is `null` or `undefined`
- fix the issue count calculation as the Issues array is ungrouped issues and is not unique per scanned project
**before**
From this test result the total should have been 12 (unique issues) and not 42 which is vulnerable paths
```
Tested 93 dependencies for known issues, found 12 issues, 42 vulnerable paths.
```
**after**

Fix: total issue count

---

src/cli/commands/test/open-source-sarif-output.ts

Today in sarif output we have a result item per each "vulnerable path"
This will reduce the number of items to be the number of vulnerabilities

feat: show only unique vulnerabilities in sarif format

---

test/smoke/spec/iac/snyk_test_terraform_spec.sh

There is a bug in the legacy flow and sometimes the test fails with empty “Validation Error Reason”.
We change the test to be less explicit and very soon we will deprecate. The new flow is handling this correctly.

refactor: update legacy smoke test to be less explicit

---

packages/snyk-protect/test/acceptance/protect.spec.ts

Jest defaults to 5 seconds and these tests can take longer than that. Since networks are unreliable, a minute is good enough. 
Ideally we should decouple ourselves from external networks in our acceptance tests to avoid slowing us down but that's a future step.

test(protect): increase timeout for network-dependent tests

---

packages/snyk-protect/src/lib/snyk-file.ts
packages/snyk-protect/test/unit/snyk-file.spec.ts

When splitting the dependency path in the `.snyk`'s `patch` section, we weren't removing the array indicator, `-`, so the first dependency became `- lodash` rather than just `lodash`.
Also, because we `trim` after, it's good enough to only remove the `-` and not the whitespace after which, given how loose our parsing is, may or may not exist.
I've also reworded test cases to better fit with what the function does, "it extracts", rather than just "it works".

fix(protect): correctly extract patches from direct dependencies

---

packages/snyk-fix/package.json

Use @snyk/pipfile-fix that has engines downgraded from 12 to 10 min

fix: @snyk/pipfile-fix with node 10+ engines

---

package.json

Use latest @snyk/fix packages that includes a fix for Yarn where node engines was set to 12+ in a transitive package @snyk/pipfile-fix

fix: latest @snyk/fix with engines 10+

---

.github/CODEOWNERS
src/cli/commands/test/iac-local-execution/assert-iac-options-flag.ts
src/cli/commands/test/iac-local-execution/index.ts
test/acceptance/fake-server.ts
test/jest/acceptance/iac/custom-rules.spec.ts
test/jest/acceptance/iac/helpers.ts
test/smoke/spec/iac/snyk_test_local_exec_spec.sh

Fixes CC-875
Depends on https://github.com/snyk/snyk/pull/1913
This PR adds support for a new `iacCustomRules` feature flag that will enable the `--rules` flag. For orgs that do not have this feature enabled the flag will be rejected with an error.
The implementation is all in test/local-exec/index.ts
I've also started migrating our Infrastructure as Code tests over to the `jest/acceptance` test folder. Most of our tests feel like they could live under here and talk to the fake backend. There are two files one containing the custom rules acceptance tests and the second a helper function that starts the fake server and returns a `run(cmd: string)` function for executing CLI commands and evaluating the output/exit code. The helper ensures that the CLI is configured (via environment …

chore: IaC --rules feature flag [CC-875]

---

packages/snyk-protect/src/lib/patch.ts
packages/snyk-protect/src/lib/snyk-file.ts
packages/snyk-protect/test/unit/patch.spec.ts
packages/snyk-protect/test/unit/snyk-file.spec.ts

This came up while working on smoke tests. We don't handle carriage returns, which isn't specific to Windows but is most common. Various applications like `git` may automatically translate line endings so we should try our best to keep things as they are. That means:
- Ignore `\r` when parsing `.snyk` file for patches.
- Keep `\r` when patching files.

fix(protect): handle carriage returns

---

packages/snyk-protect/package.json

We dropped Node 8 support a while back but didn't update @snyk/protect's package.json.

chore(protect): drop node 8 in engines

---

packages/snyk-protect/test/unit/fetch-patches.spec.ts

These tests make network calls so it can take longer than 5 seconds. Wait max 60 seconds.

test(protect): increase timeout for network test

---

src/cli/commands/test/iac-local-execution/file-parser.ts
src/cli/commands/test/iac-local-execution/file-scanner.ts
src/cli/commands/test/iac-local-execution/local-cache.ts
src/cli/commands/test/iac-local-execution/parsers/k8s-or-cloudformation-parser.ts
src/cli/commands/test/iac-local-execution/results-formatter.ts
src/cli/commands/test/iac-local-execution/types.ts
src/cli/commands/test/iac-output.ts
src/lib/iac/constants.ts
test/fixtures/iac/cloudformation/aurora-valid.yml
test/fixtures/iac/cloudformation/fargate-valid.json
test/fixtures/iac/cloudformation/invalid-cfn.yml
test/fixtures/iac/kubernetes/pod-valid.json
test/jest/unit/iac-unit-tests/file-parser.cloudformation.fixtures.ts
test/jest/unit/iac-unit-tests/file-parser.fixtures.ts
test/jest/unit/iac-unit-tests/file-parser.spec.ts
test/smoke/spec/iac/snyk_test_local_exec_spec.sh

This PR enables users to scan CloudFormation files (both with `yaml` and `json` extenstions) via CLI. For this purpose it:
1. Adds EngineType for CloudFormation, packagemanager: cloudformationconfig.
2. Adds support for the new wasm bundle for CloudFormation files.
3. Extends the engineTypeToProjectType with the new EngineType=cloudformationconfig.
4. Implements the soultion for the detection of CloudFormation files in a new `k8s-or-cloudformation-parser.ts` by checking whether a file has a top-level `Resourses` field which is the only required field for ClodFormation templates. 
5. Introduces new unit tests and smoke tests for CloudFormation.
The reviewer should start with `src/cli/commands/test/iac-local-execution/file-parser.ts` file.
It can by manually tested by running `snyk-dev iac …

Feat/adding cloudformation support [CC-850]

---

src/cli/commands/test/iac-local-execution/results-formatter.ts
test/jest/acceptance/iac/file-output.spec.ts
test/jest/unit/iac-unit-tests/results-formatter.spec.ts
test/smoke/spec/iac/snyk_test_local_exec_spec.sh

This PR enables the line number functionality for the `--sarif-file-output` and `--json-file-output` flags. Without this line number functionality, the GitHub action for IaC is broken because Sarif expects a non-negative `startLine`.
1. Run `npm run build`
2. Run `node ./dist/cli iac test test/fixtures/iac/terraform/sg_open_ssh.tf --sarif-file-output=snyk.sarif`
3. Run `cat snyk.sarif` and notice that the `startLine` is not -1 anymore.
In https://github.com/snyk/snyk/pull/1901 we wanted to make sure we didn't run the line number functionality if we weren't going to display the line number to a user. This line number is only rendered when we output JSON or Sarif. We forgot about the `--json-file-output` and `--sarif-file-output` flags however.
- …

bug: extract line numbers if sarif-file-output or json-file-output [CC-887]

---

src/cli/commands/test/iac-local-execution/analytics.ts

We were calculating the iac-type based on the `policy.type` field. 
However, we can no longer rely on the `type` field on its own for distinguishing between CloudFormation and Terraform. 
This PR changes from looking at the `policy.type` to the packageManager itself.
For a single file:
```
snyk analytics {
"args": [
"test/fixtures/iac/cloudformation/aurora-valid.yml",
{
"debug": true,
"iac": true
}
],
"command": "test",
"metadata": {
"iac-terraform-plan": false,
"packageManager": [
"cloudformationconfig"
],
"iac-issues-count": 1,
"iac-type": {
"cloudformationconfig": {
"medium": 1
}
},
"iac-metrics": {
"cache-init-ms": 297,
"file-loading-ms": 1,
"file-parsing-ms": 26,
"file-scanning-ms": 111,
"org-settings-ms": 509,
"custom-severities-ms": 2,
"results-formatting-ms": 0, …
```

fix: Analytics show correct number of issues by cloudformation

---

src/cli/commands/test/iac-local-execution/file-loader.ts
test/jest/unit/iac-unit-tests/file-loader.spec.ts

Co-authored-by: Teodora Sandu <teodora.sandu@snyk.io>
This PR skips empty files on an IaC scan instead of failing with a "Could not find any valid IaC files" error.
This implementation does not return any error or a message to indicate that the file is skipped. 
We decided to just skip for now as we have a wider discussion on refactoring our errors and messages.
- In `file.loader.ts`: we filter out files with empty content. The file will never be scanned for issues going down the flow.
```
touch empty.tf
node ~/snyk-repos/snyk/dist/cli/index.js iac test empty.tf
```
[CC-589]
[CC-589]: https://snyksec.atlassian.net/browse/CC-589

fix: Skip empty files on IaC scanning [CC-589]

---

src/cli/commands/test/iac-local-execution/results-formatter.ts
src/cli/commands/test/iac-local-execution/types.ts
test/fixtures/iac/file-output/nested-folder/sg_open_ssh.tf
test/fixtures/iac/file-output/sg_open_ssh.tf
test/jest/acceptance/iac/file-output.spec.ts
test/jest/unit/iac-unit-tests/results-formatter.fixtures.ts

This PR fixes the logic for computing the `targetFile`, `targetFilePath`, and `projectName` for the outputs. The SARIF output for our GitHub action has been broken since making local exec GA and putting the legacy flow behind a flag. Comparing the legacy and GA output for SARIF, there was definitely a difference in the `physicalLocation` fields, **when** passing in the path to the folder as `.`.
The reason we are here today is we previously only tested the results returned by the CLI by scanning a single file, whereas now we've tested it for:
- a single file
- a folder which was passed in via the CLI by providing `.`
- a folder which was picked by default by the CLI by not providing any path to it
- a folder which is in a relative location to the current running directory
Build using `npm …

fix: paths in json and sarif output [CC-563]

---

src/cli/commands/test/iac-local-execution/file-parser.ts
src/cli/commands/test/iac-local-execution/file-utils.ts
src/lib/iac/iac-parser.ts
test/jest/unit/iac-unit-tests/file-parser.fixtures.ts
test/jest/unit/iac-unit-tests/file-parser.spec.ts

We identified a few cases that our services parse the yaml files in a different way. The node 'yaml' library is too 'strict', returning errors for validation of the YAML as well. 
In this PR we focus on two specific errors: bad indentation and duplicate keys. 
These two examples are not consistent with what Policy Engine returns so in this commit we intentionally skip errors for these cases, and return the parsed YAML document instead.
This will improve the consistency between the two parsers.
The changes are in `file-parser.ts` and `iac-parser.ts` where we check if the error is one of the two error strings.
- Create a file with a SemanticError, e.g. duplicate keys:
```
apiVersion: v1
kind: Pod
metadata:
name: myapp-pod
spec:
containers:
something: here
metadata:
another: thing
```
Run …

fix: Skip specific errors when parsing yaml IaC files

---

packages/snyk-fix/test/acceptance/plugins/python/handlers/pip-requirements/update-dependencies/update-dependencies.spec.ts
packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/update-dependencies.spec.ts
packages/snyk-fix/test/helpers/generate-entity-to-fix.ts
packages/snyk-fix/test/helpers/read-file-helper.ts

- re-using test helper across all tests instead of repeated code.

test: re-use the entity generator helpers across all tests

---

packages/snyk-fix/package.json
packages/snyk-fix/src/lib/errors/custom-error.ts
packages/snyk-fix/src/lib/errors/invalid-workspace.ts
packages/snyk-fix/src/lib/errors/missing-remediation-data.ts
packages/snyk-fix/src/lib/errors/no-fixes-applied.ts
packages/snyk-fix/src/plugins/python/handlers/pip-requirements/index.ts
packages/snyk-fix/src/plugins/python/index.ts

- drop unused error
- correct error codes
- partition all items by fixable vs not before the handlers are called instead of repeating it in each

Fix: partition Python projects by fixable earlier on in Snyk fix flow

---

packages/snyk-protect/src/lib/snyk-file.ts
packages/snyk-protect/test/fixtures/single-patchable-module/.snyk
packages/snyk-protect/test/unit/snyk-file.spec.ts

Makes `@snyk/protect` handle `.snyk` files with package paths which are wrapped in either single or double quotes.
The reason for this is because our Snyk Fix PR generates `.snyk` files which have single quotes. For example: 
```
version: v1.19.0
ignore: {}
patch:
SNYK-JS-LODASH-567746:
- '@snyk/patchable-dep-fixture > lodash':
patched: '2021-06-14T22:42:43.116Z'
```

fix(protect): handle package paths in quotes

---

packages/snyk-fix/package.json
packages/snyk-fix/src/plugins/load-plugin.ts
packages/snyk-fix/src/plugins/package-tool-supported.ts
packages/snyk-fix/src/plugins/python/get-handler-type.ts
packages/snyk-fix/src/plugins/python/handlers/poetry/index.ts
packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
packages/snyk-fix/src/plugins/python/load-handler.ts
packages/snyk-fix/src/plugins/python/map-entities-per-handler-type.ts
packages/snyk-fix/src/plugins/python/supported-handler-types.ts
packages/snyk-fix/src/types.ts
packages/snyk-fix/test/acceptance/plugins/package-tool-supported.spec.ts
packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/update-dependencies.spec.ts
packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/fails-to-lock/poetry.lock
packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/fails-to-lock/pyproject.toml
packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/non-existent/poetry.lock
packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/non-existent/pyproject.toml
packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/simple/poetry.lock
packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/simple/pyproject.toml
packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/with-dev-deps/poetry.lock
packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/workspaces/with-dev-deps/pyproject.toml
packages/snyk-fix/test/helpers/generate-entity-to-fix.ts
packages/snyk-fix/test/unit/fix.spec.ts
packages/snyk-fix/test/unit/plugins/python/handlers/pip-requirements/get-handler-type.spec.ts
packages/snyk-fix/test/unit/plugins/python/handlers/pip-requirements/map-entities-per-handler-type.spec.ts
packages/snyk-fix/test/unit/plugins/python/handlers/poetry/generate-upgrades.spec.ts
packages/snyk-fix/test/unit/plugins/python/is-supported.spec.ts

- introduce Poetry fix support to @snyk/fix
- production & development dependencies are updated separately as `poetry` is called directly to apply changes and requires a `--dev` flag to change the correct dependency section.
- `--command` is not yet supported, this is coming next (currently `snyk test` does not use any python interpreter to get to dependencies, but require using it potentially to fix issues since we invoke poetry)
`packages/snyk-fix/src/plugins/load-plugin.ts`
`snyk fix --all-projects` on

Feat: Poetry support for @snyk/fix

---

packages/snyk-protect/src/lib/index.ts
packages/snyk-protect/test/acceptance/protect.spec.ts

Adds the message `Successfully applied Snyk patches`, like the original protect implementation.

feat(protect): add successful message for protect

---

packages/snyk-fix/package.json
packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/update-dependencies.spec.ts

Snyk users can provide a Python interpreter to be used for all
Python opetations via --command parameter to `snyk test` and `snyk fix`
Latest @snyk/fix-poetry package version nos supports it and expects it to be passed through as `python` parameter.

feat: support --command for Poetry fix

---

src/cli/commands/test/iac-local-execution/file-parser.ts
src/cli/commands/test/iac-local-execution/file-utils.ts
src/cli/commands/test/iac-local-execution/parsers/k8s-or-cloudformation-parser.ts
src/cli/commands/test/iac-local-execution/yaml-parser.ts
src/lib/iac/iac-parser.ts
test/jest/unit/iac-unit-tests/file-parser.spec.ts

This PR is refactoring the YAML/JSON parsing logic, so it's easier to update in the future.
The PR contains multiple commits, per type of change. The easiest way to understand the changes is by looking at each commit in order.
There are a few related changes in this PR:
1. Creating a `src/cli/commands/test/iac-local-execution/yaml-parser.ts` file to put all YAML parsing related code in, to improve readability and remove duplication.
2. Refactoring the legacy parser so it parses YAML and JSON using the same library (`yaml`), as we discovered previously that they are dealt with the same. This change was done by using the same YAML parser from stage 1.
3. Moving the Helm validation earlier, to the YALM parser, so that we don't parse unnecessarily.
- …

refactor: yaml parsing for IaC scans [CC-943] 

---

src/cli/commands/test/iac-local-execution/file-parser.ts
src/cli/commands/test/iac-local-execution/parsers/k8s-or-cloudformation-parser.ts
src/cli/commands/test/iac-local-execution/yaml-parser.ts
test/jest/unit/iac-unit-tests/file-parser.spec.ts
test/smoke/spec/iac/snyk_test_local_exec_spec.sh

This PR builds on top of https://github.com/snyk/snyk/pull/2041 and makes the yaml parser consistent with `registry`, since https://github.com/snyk/registry/pull/21629.
The PR technically shouldn't add any new functionality other than if someone were to scan the following file (notice that the template directive is `{ {` rather than `{{`) then we now would throw an error and not allow the CLI to scan it as valid YAML. This check now makes the `assertHelmAndThrow` function redundant. The difference now is if someone uses `{{` we don't tell them we don't support Helm, only that their YAML shouldn't contain template directives.
```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
name: auth-policy
namespace: istio-system
spec:
targets:
- name: catalog
ports:
- number: 5002 …
```

fix: yaml parsing for IaC scans [CC-943]

---

packages/snyk-fix/package.json

Bump fix packages to latest version without `prettier` listed as
a production dep

fix(@snyk/fix): drop prod prettier from fix packages

---

packages/snyk-fix/src/index.ts
packages/snyk-fix/src/lib/errors/common.ts
packages/snyk-fix/src/lib/output-formatters/show-results-summary.ts
packages/snyk-fix/src/plugins/python/handlers/pip-requirements/index.ts
packages/snyk-fix/src/plugins/python/index.ts
packages/snyk-fix/test/acceptance/plugins/python/handlers/pip-requirements/update-dependencies/__snapshots__/update-dependencies.spec.ts.snap
packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/update-dependencies.spec.ts
packages/snyk-fix/test/unit/__snapshots__/fix.spec.ts.snap
packages/snyk-fix/test/unit/lib/output-formatters/__snapshots__/show-results-summary.spec.ts.snap
packages/snyk-fix/test/unit/lib/output-formatters/show-results-summary.spec.ts

- only show summary items if at least 1 item is fixed/skipped/etc (no 0s)
- show a warning when running in `--dry-run` mode to make it clear no changes were applied
- if any items are unresolved the retry help text was showing in red, changed it to white & prefix with `Tip:`

Feat: snyk fix output improvement

---

src/cli/commands/test/iac-local-execution/results-formatter.ts
src/cli/commands/test/iac-output.ts
test/jest/acceptance/iac/file-output.spec.ts

In https://github.com/snyk/snyk/pull/1988 we fixed our GitHub Action by making the GA-ed SARIF output consistent with the legacy one. But there were still bugs left behind from the legacy output This PR completely removes all bugs to do with the file paths in the SARIF output.
The tests have been refactored to make them easier to read, but also modified after implementing the fixes. Each commit contains its respective change to the functionality and tests, so to understand why these changes were made go through each `fix` commit.
Build using `npm run build` and clone https://github.com/teodora-sandu/test. Change directory into `nested` and run the following commands one by one. The result of these commands can be found in the attached ZIP.
```
snyk iac test …
```

fix: IaC SARIF output for GitHub Action [CC-957]

---

test/jest/acceptance/iac/file-output.spec.ts

These tests were added to verify the validity of the file output for our GitHub action.
We have implemented new regression tests under https://github.com/snyk/snyk/pull/2053, so
these tests don't add any value to us. They verify the output of the JSON file output, but
both the SARIF and JSON file output use the same logic so testing the GitHub action should
be enough.
- https://snyksec.atlassian.net/browse/CC-957

refactor: remove redundant file output tests for IaC [CC-957]

---

src/cli/commands/test/iac-local-execution/file-parser.ts
src/cli/commands/test/iac-local-execution/parsers/k8s-or-cloudformation-parser.ts
test/jest/unit/iac-unit-tests/file-parser.fixtures.ts
test/jest/unit/iac-unit-tests/file-parser.spec.ts
test/smoke/spec/iac/snyk_test_local_exec_spec.sh

ignore unrecognised IaC types
No longer return an error when scanning YAML or JSON files that do not
contain recognised infrastructure as code schemas, e.g. Kubernetes or
CloudFormation. Instead, ignore these files.
In YAML files that contain multiple documents, ignore documents that
contain unrecognised schemas. This includes empty documents.
I discovered while implementing this that mixed-recognised-config-type multi-doc yaml files were already supported: e.g. when scanning a 2-doc yaml file that contains a valid kubernetes manifest in 1 doc, and a valid cloudformation config in the other, issues are returned for both. This PR does not break this behaviour, although I suspect it was always undefined and I haven't added a test case for it.
In https://snyksec.atlassian.net/browse/CC-947 …

feat: ignore unrecognised IaC types [CC-947]

---

src/cli/commands/test/iac-local-execution/extract-line-number.ts
src/cli/commands/test/iac-local-execution/results-formatter.ts
test/fixtures/iac/kubernetes/pod-privileged-multi.yaml
test/jest/acceptance/iac/multidoc-yaml.spec.ts
test/jest/unit/iac-unit-tests/results-formatter.fixtures.ts

In the IaC local execution data flow, the stage in results-formatter.ts
takes a list of IacFileScanResult as input, and returns a list of
FormattedResult. One key difference between these two objects is that
the former list contains a distinct object per document in a multi-doc
yaml file, but for the latter we are grouping these so that there is a
distinct object per file.
FormattedResults each contain a list of vulnerabilities, so we end up
with vulnerabilities from different YAML documents (in the same file)
sharing a list. Vulnerabilities with the same "resource path"
(Kubernetes example: `spec.containers[web].securityContext.privileged`),
but in distinct YAML documents in the same file, should be
differentiated by the "cloudConfigPath" (analogous to the "path" of
libraries used to …

fix: IaC multi-doc yaml indexing

---

src/cli/commands/test/iac-local-execution/analytics.ts

This PR adds the `iac-ignored-issues-count` field to the analytics metadata sent to Registry.
This will enable us track how many issues were ignored in a test  run.
- Add a snyk policy to ignore an issue, e.g.:
```
version: v1.19.0
ignore:
SNYK-CC-K8S-1:
- '*':
reason: None Given
expires: 2021-08-26T08:40:35.249Z
created: 2021-07-27T08:40:35.251Z
```
- Run[ local branch of registry](https://github.com/snyk/registry/pull/22813) (if not merged): 
- Run 
```
npm run build 
node ./dist/cli iac test test/fixtures/iac/kubernetes/pod-privileged.yaml --policy-path=.snyk -d
```
to see analytics under the debug flag.
CC-995
Running a test with a Policy file - Ignoring 0 issues:
Running a test with a Policy file - Ignoring 1 issue:

feat: Enable IaC analytics for ignores

---

packages/snyk-protect/bin/snyk-protect
packages/snyk-protect/src/lib/index.ts
packages/snyk-protect/src/lib/patch.ts
packages/snyk-protect/src/lib/snyk-api.ts
packages/snyk-protect/test/acceptance/fix-pr.smoke.spec.ts
packages/snyk-protect/test/acceptance/protect.spec.ts

In the old `snyk protect` we used to add placeholder files to patched modules so indicate we've already patched them. The new snyk/protect doesn't do this so it attempts to patch modules that have already been patched, causing a failure.
This PR fixes that by creating the same placeholder file. The difference is that it's simpler and should work with any existing ignore rules a project might use to exclude them in their builds.
`snyk protect`:
`[filename].snyk-[vuln-id].flag` containing a timestamp.
Now:
`[filename].snyk-protect.flag` containing nothing.
So a project using `*.snyk-*.flag` will still match the same files. Like:
https://github.com/signalapp/Signal-Desktop/blob/f96246fecf4855db88d571e5825132ee4d5605c8/package.json#L435
<details>
<summary>See error logs</summary>
<pre>
node ➜ …

fix(protect): skip previously patched files

---

dangerfile.js

`dangerfile.js` contained some logic regarding adding new Tap tests instead of Jest test. This logic resulted in a redundant warning when adding new test fixtures. This should stop these warnings.

chore: don't warn about changes to test fixtures in dangerjs

---

package.json

Pumbing snyk-docker-plugin to get support for shaded jars scanning. 
If nested jars found, we are not returning the parent (fat / shaded) jar. We are hiding unpacking jar functionality behind CLI flag. The uberjar code wont run at all if app-vulns is not specified. In order to make this clear to the user, we're throwing an error in case
the user specifies --shaded-jars, but does not specify --app-vulns

feat: Return vulns from shaded jars

---

packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/update-dependencies.spec.ts

Bubble up pipenv errors that look like this:
```Updating dependencies
Resolving dependencies... (1.7s)
SolverProblemError
Because package-A (2.6) depends on package-B (>=1.19)
and package-C (2.2.1) depends on package-B (>=1.16.0,<1.19.0), package-D (2.6) is incompatible with package-C (2.2.1).
So, because package-Z depends on both  package-C (2.2.1) and package-D (2.6), version solving failed.```
```
packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts

feat(@snyk/fix): catch version resolving failed pip error.

---

packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/update-dependencies.spec.ts

Bubble up poetry errors that look like this as well:
```Resolving dependencies... (1.7s)
SolverProblemError
Because package-A (2.6) depends on package-B (>=1.19)
and package-C (2.2.1) depends on package-B (>=1.16.0,<1.19.0), package-D (2.6) is incompatible with package-C (2.2.1).
So, because package-Z depends on both  package-C (2.2.1) and package-D (2.6), version solving failed.
```

fix: bubble up SolverProblemError for Poetry

---

src/cli/commands/test/iac-local-execution/parsers/terraform-plan-parser.ts
src/cli/commands/test/iac-local-execution/types.ts
test/fixtures/iac/terraform-plan/expected-parser-results/delta-scan/tf-plan-create.resources.json
test/fixtures/iac/terraform-plan/expected-parser-results/full-scan/tf-plan-create.resources.json
test/fixtures/iac/terraform-plan/tf-plan-create.json

Aligns the Terraform Plan parser with a small change in the way we use the `index` field for naming + added tests for a bug we found in the Go parser.

fix: tf plan parser test index cases

---

packages/snyk-fix/src/lib/errors/no-fixes-applied.ts
packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/attempted-changes-summary.ts
packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
packages/snyk-fix/src/types.ts
packages/snyk-fix/test/acceptance/plugins/python/handlers/poetry/update-dependencies.spec.ts

In preparation for introducing a different sequential fix strategy
refactor the existing code into re-usable blocks needed to add sequential
fix. 
Added some extra optional fields that can be sent in changes so we have all the data we need in case we want to output is as --json or consume it another way
packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts

refactor: extract re-usable code from poetry fix

---

packages/snyk-fix/src/plugins/python/handlers/attempted-changes-summary.ts
packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
packages/snyk-fix/test/acceptance/plugins/python/handlers/pipenv-pipfile/update-dependencies.spec.ts

In preparation for introducing a different sequential fix strategy
refactor the existing code into re-usable blocks needed to add sequential
fix
see https://github.com/snyk/snyk/pull/2240

refactor: extract re-usable code from pipenv fix

---

packages/snyk-fix/src/plugins/python/handlers/ensure-has-updates.ts
packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/index.ts
packages/snyk-fix/src/plugins/python/handlers/pipenv-pipfile/update-dependencies/pipenv-add.ts
packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts

Ensure we separately throw when nothing was changed vs when
100% of fixes failed. And send appropriate message.
Revert a change that was outputting the whole pipenv stderr and only
show a short summary for those caught errors

fix: error to handle when no fixes applied

---

packages/snyk-fix/src/plugins/python/handlers/poetry/update-dependencies/index.ts
packages/snyk-fix/test/unit/plugins/python/handlers/poetry/generate-upgrades.spec.ts

When generating upgrades make sure to standardize both package
names and the remediation package names before comparing
and choosing to do the upgrade for prod / dev dep.

fix: standardize poetry package names before comparing

---

src/lib/plugins/sast/index.ts

Adds metadata before running the test. If the test fails (and throws) metadata will be sent in analytics

fix: add sast-scan metadata before running (possibly throwing) test

---

help/commands-docs/_SNYK_COMMAND_OPTIONS.md
help/commands-man/snyk-auth.1
help/commands-man/snyk-code.1
help/commands-man/snyk-config.1
help/commands-man/snyk-container.1
help/commands-man/snyk-help.1
help/commands-man/snyk-iac.1
help/commands-man/snyk-ignore.1
help/commands-man/snyk-monitor.1
help/commands-man/snyk-policy.1
help/commands-man/snyk-protect.1
help/commands-man/snyk-test.1
help/commands-man/snyk-wizard.1
help/commands-man/snyk-woof.1
help/commands-man/snyk.1
help/commands-md/snyk-monitor.md
help/commands-md/snyk-test.md
help/commands-md/snyk.md
help/commands-txt/snyk-monitor.txt
help/commands-txt/snyk-test.txt
help/commands-txt/snyk.txt
help/generator/generator.ts

A few things:
- `txt` docs weren't being generated due to an issue with ronn-ng.
- https://github.com/apjanke/ronn-ng/issues/71
- The issue is solve but hasn't been released yet.
- I implemented a `PAGER` env workaround that was stated in the thread.
- While I was there:
- I updated the paths to use `path.resolve` so that they're not dependant on the current working directory.
- Removed the `cat` piping as `ronn` can take a file path as input.
- I had to regenerate docs as it seems to have gotten misaligned for some reason. Cross-platform issues maybe. Main changes are:
- Updated date.
- Removed `'` escapes.
- I put the `--target-reference` change in a separate commit for readability.

docs: add help for --target-reference

---

src/lib/plugins/sast/checks.ts
src/lib/plugins/sast/validate.ts
test/jest/unit/snyk-code/snyk-code-test.spec.ts

This PR shows better error when org is not found for user (instead of showing "Snyk code is not enabled for org")
run `snyk code test --org=foo` with this PR
https://snyksec.atlassian.net/browse/COD-556?atlOrigin=eyJpIjoiMTBlZjliODkxMjM4NGVkNjgzMGEyZmE5M2NkMDExMWMiLCJwIjoiaiJ9

fix: better error when org is not found for snyk code

---

package-lock.json
package.json

fix: skip files greater than or equal to 2GB
Due to limitations with nodes Buffer, we agreed
to skip files greater than or equal to 2GB.
This is implemented by following changes:
- Add file size validation to find.ts
To test this fix, run the CLI test with an unmanaged
project containing a file of at least 2GB. Consider
it a success if it's not crashing, and we generate
signatures for all other files.

fix: skip files greater than or equal to 2GB

---

README.md
help/_about-this-project/README.md
help/_about-this-project/why-we-are-bundling-dependencies.md

Documenting why we started bundling dependencies.
Added a new folder where we can document similar decisions. It should be useful for users and contributors.

docs: about dependency bundling

---

test/jest/acceptance/iac/custom-rules.spec.ts

This PR adds an acceptance test for GitHub CR.
This test is one of the acceptance criteria to be able to claim we support GitHub CR for storing custom rules.
https://snyksec.atlassian.net/browse/CFG-1105

test: add acceptance test for github cr [CFG-1105]

---

.github/CODEOWNERS

Mirroring an internal change, this PR assigns reivews at a group level rather than to multiple teams. This should make communication clearer and make it easier for us to understand where we have poor ownership concerns

chore: Update codeowners for the open source group

---

src/cli/commands/test/iac-local-execution/file-utils.ts
src/lib/monitor/dev-count-analysis.ts
src/lib/types.ts
test/dev-count-analysis.spec.ts
test/dev-count-analysis.test.ts

Snyk CLI/API is now collecting emails of developers that contributed to the monitored project in last 90 days.

feat: don't hash emails in monitor command

---

src/cli/commands/config.ts
test/user-config.test.ts

If we run `snyk config set key=value=`, then the value we set is `value` instead of `value=`. This PR uses [capturing parantheses](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split#Capturing_parentheses) so that the value we set becomes `value=`.
2. `synk-dev config set key=value=`
3. `snyk-dev config get key`
https://snyk.slack.com/archives/C0127HWU0E7/p1636722014155100
https://snyksec.atlassian.net/browse/HMMR-470

fix: config set command when value contains =

---

help/commands-docs/_SNYK_COMMAND_OPTIONS.md
help/commands-man/snyk-monitor.1
help/commands-man/snyk-test.1
help/commands-man/snyk.1
help/commands-md/snyk-monitor.md
help/commands-md/snyk-test.md
help/commands-md/snyk.md
help/commands-txt/snyk-auth.txt
help/commands-txt/snyk-code.txt
help/commands-txt/snyk-config.txt
help/commands-txt/snyk-container.txt
help/commands-txt/snyk-help.txt
help/commands-txt/snyk-iac.txt
help/commands-txt/snyk-ignore.txt
help/commands-txt/snyk-monitor.txt
help/commands-txt/snyk-policy.txt
help/commands-txt/snyk-protect.txt
help/commands-txt/snyk-test.txt
help/commands-txt/snyk-wizard.txt
help/commands-txt/snyk-woof.txt
help/commands-txt/snyk.txt

To make the CLI easier to use, we are aliasing `--project-tags` to simply `--tags`.
We shipped the actual change in https://github.com/snyk/snyk/pull/2330

docs: document new flag --tags which aliases to --project-tags

---

.github/CODEOWNERS
src/lib/formatters/iac-output.ts
test/jest/unit/lib/formatters/iac-output.spec.ts

For our `--sarif` output we want to exclude the `region` object and `startLine` field when a misconfiguration has no line number (either missing entirely or set to -1). 
Including a negative number for `startLine` is [invalid in the SARIF spec](https://docs.oasis-open.org/sarif/sarif/v2.0/csprd02/sarif-v2.0-csprd02.html#_Toc10127873) and causes issues with tools such as the GitHub security feature.
Start at the test implementation in iac-output.spec.ts to see the inputs and then check the iac-output.ts file for the implementation.
Run the snyk tool against a CloudFormation file (we have the biggest parser issues here) and ensure that there are no `region` fields with a value of -1. For example check out [snyk-labs/infrastructure-as-code-goof](https://github.com/snyk-labs/infrastructure-as- …

fix: Exclude region field when missing line number

---

src/cli/commands/index.js
src/lib/index.js
src/lib/spinner.ts

Seems this was used at some point when Snyk CLI was used via imports.
We now only support Snyk CLI as an executable via bin/snyk so this shouldn't be needed.

refactor: remove isRequired check

---

src/cli/index.ts

We no longer export "main" in our package.json so we don't need this export.

refactor: remove main cli export

---

webpack.common.js

When providing strings, Webpack matches absolute paths so the current `'/node_modules'` rule excludes nothing.
>A string: To match the input must start with the provided string. I. e. an absolute directory path, or absolute path to the file.
https://webpack.js.org/configuration/module/#condition
Fixing this by using a regex `/node_modules/` does not improve build performance at all since imports via node_modules will likely never match the `test` rule (.ts files) so this exclude is not useful.

chore: remove dud webpack loader exclude rule

---

webpack.common.js

Since our outputs are used only by bin/snyk and bin/snyk uses `require`, there's no need to use UMD exports (which attempts to support a wide range of module formats), we can use regular CommonJS. Reduces our build complexity.
https://webpack.js.org/configuration/output/#outputlibrarytype

chore: use commonjs instead of umd

---

package-lock.json
package.json
src/lib/ecosystems/resolve-test-facts.ts
src/lib/ecosystems/types.ts
src/lib/polling/polling-test.ts
src/lib/snyk-test/legacy.ts
test/jest/unit/lib/ecosystems/resolve-test-facts.spec.ts

The purpose of those changes are related to the addition of a new field (called confidence) in the CLI output for the unmanaged flows.
When using either `--print-deps` or `--print-dep-paths` args along with the `unmanaged scan` command on the CLI you should be able to see the confidence score of the found dependencies.
Yes
TUN-58
`--print-deps`
or 
`--print-dep-paths`

Feat: show confidence score

---

src/cli/commands/test/iac-local-execution/index.ts
src/cli/commands/test/iac-local-execution/oci-pull.ts
src/cli/commands/test/iac-local-execution/url-utils.ts
test/jest/unit/iac-unit-tests/oci-pull.spec.ts
test/jest/unit/iac-unit-tests/url-utils.spec.ts

- Changes the existence of protocols in OCI registry URLs to be optional
- `src/cli/commands/test/iac-local-execution/index.ts`
1. Make sure your org has the `iacCustomRules` and the `infrastructureAsCode` feature flags.
2. Make sure your org has the `iacCustomRulesEntitlement` entitlement.
3. Prepare a custom-rules bundle generated by the [Snyk custom-rules bundles generator](https://github.com/snyk/snyk-iac-rules). 
4. Push the generated bundle to an OCI registry. You can refer to [our docs](https://docs.snyk.io/products/snyk-infrastructure-as-code/custom-rules/getting-started-with-the-sdk/pushing-a-bundle) to learn how.
. In the Snyk CLI, run `snyk-dev iac test <file> --path=<path-to-remote-bundle>`, where the path does not contain a protocol.
5. Verify that:
- No errors were thrown.
- …

fix: Remove http protocols validation in custom rules pull.

---

src/lib/common.ts
src/lib/errors/error-with-retry.ts
src/lib/errors/index.ts
src/lib/errors/legacy-errors.js
src/lib/formatters/format-error-result-summary.ts
src/lib/monitor/index.ts
src/lib/plugins/get-multi-plugin-result.ts
src/lib/protect/patch.js
src/lib/snyk-test/run-test.ts
test/jest/acceptance/snyk-test/all-projects.spec.ts
test/jest/unit/lib/formatters/__snapshots__/format-error-result-summary.spec.ts.snap

Use consistent message for retry & contact where we ask the user to try again but with debug enabled.
src/lib/common.ts

fix: unify the retry & contact support errors across commands

---

test/jest/acceptance/iac/custom-rules.spec.ts

This PR adds acceptance tests for GCR, to prove that we support it and make sure we keep supporting it. The credentials are for a GCR service account set up for automated testing.

chore: add gcr acceptance test [CFG-1111]

---

package-lock.json
package.json
src/lib/snyk-test/run-test.ts
test/acceptance/cli-test/cli-test.docker.spec.ts

This PR allows for use of the installCommand, extracted from a RUN instruction in newer versions of the SDP, to provide a better output for dockerFile user instructions.
https://snyksec.atlassian.net/browse/CAP-280

feat: Improve output for dockerfile instructions

---

test/jest/acceptance/iac/custom-rules.spec.ts

- Temporarily skips the acceptance test for pulling custom rules bundles from GCR.
- `test/jest/acceptance/iac/custom-rules.spec.ts`
- Run the following acceptance test: `test/jest/acceptance/iac/custom-rules.spec.ts`.
- Verify that all tests are passing.
- Some of the IaC tests related credentials were revoked. As a result, the corresponding tests are failing. As a temporary fix, we would like to skip these tests until the credentials are updated.
- [Slack thread](https://snyk.slack.com/archives/C022H54L8PJ/p1637778795222300)

chore: Temporarily skip GCR custom rules  acceptance test

---

package-lock.json
package.json

This adds support for optional peer dependencies in npm7 - stopping Snyk from throwing out of sync errors in cases where it cannot find the peerDep if it is optional.

fix: support optional peerDeps for npm7

---

src/cli/commands/test/iac-local-execution/results-formatter.ts
test/jest/unit/iac-unit-tests/results-formatter.fixtures.ts

This PR makes sure that if a misconfiguration comes from a custom rule, then we don't provide link to the documentation. 
2. Build a custom rules bundle using `snyk-iac-rules` 
3. `snyk-dev iac test test/fixtures/iac/terraform/sg_open_ssh.tf --json --rules=bundle.tar.gz`
- [Slack thread](https://snyk.slack.com/archives/C022H54L8PJ/p1637933370240100)

fix: custom rules json output

---

src/cli/commands/test/iac-local-execution/index.ts
src/cli/commands/test/iac-local-execution/oci-pull.ts
test/jest/acceptance/iac/custom-rules.spec.ts
test/jest/unit/iac-unit-tests/index.spec.ts

- Removes the `iacCustomRules` feature flag validation in custom rules related operations and flags in the CLI.
- `src/cli/commands/test/iac-local-execution/index.ts`
1. Make sure your org has the `iacCustomRulesEntitlement` entitlement.
2. Make sure your org **does not** have the `iacCustomRules` feature flag.
3. Prepare a custom-rules bundle generated by the [Snyk custom-rules bundles SDK](https://github.com/snyk/snyk-iac-rules). 
4. In the Snyk CLI, run:
```
snyk iac test <file> --rules=<path-to-rules-bundle>
```
5. Verify that:
- No errors were thrown.
- The defined custom rules generated the expected issues successfully.
6. Push the generated bundle to an OCI registry. You can refer to [our docs](https://docs.snyk.io/products/snyk-infrastructure-as-code/custom-rules/getting-started-wi …

chore: Deprecate custom rules FF [CFG-1230]

---

src/cli/commands/test/iac-local-execution/index.ts
test/jest/acceptance/iac/custom-rules.spec.ts

- Adds a user message when using custom rules to generate misconfigurations.
- Attaches a link to the troubleshooting page in error messages related to pulling custom rules bundles.
- Clarifies existing error messages.
- `src/cli/commands/test/iac-local-execution/index.ts`
1. Make sure your org has the `iacCustomRulesEntitlement` entitlement.
3. Prepare a custom-rules bundle generated by the [Snyk custom-rules bundles SDK](https://github.com/snyk/snyk-iac-rules). 
6. Push the generated bundle to an OCI registry. You can refer to [our docs](https://docs.snyk.io/products/snyk-infrastructure-as-code/custom-rules/getting-started-with-the-sdk/pushing-a-bundle) to learn how.
7. Configure your remote bundle settings. You can refer to [our …

chore: Improve error messages for the pull flow [CFG-1197]

---

src/cli/commands/test/iac-local-execution/analytics.ts
src/cli/commands/test/iac-local-execution/index.ts

Lets us send the checksum of local scans for analytics.

fix: enable checksum metric for local scans

---

help/commands-md/snyk-auth.md
help/commands-md/snyk-code.md
help/commands-md/snyk-config.md
help/commands-md/snyk-container.md
help/commands-md/snyk-help.md
help/commands-md/snyk-iac.md
help/commands-md/snyk-ignore.md
help/commands-md/snyk-monitor.md
help/commands-md/snyk-policy.md
help/commands-md/snyk-protect.md
help/commands-md/snyk-test.md
help/commands-md/snyk-wizard.md
help/commands-md/snyk-woof.md

While we wait for #2405, this PR fixes the generated docs as they keep showing up in change lists even though the doc sources aren't touched.

chore: fix generated help

---

src/cli/commands/test/iac-local-execution/index.ts
test/jest/acceptance/iac/custom-rules.spec.ts

This commit removes the recently added console.log for (IaC) custom rules from the console, when a `--json` or `--sarif` command is provided. 
I suggest this as a quick fix for a bug that consists now in the CLI and breaks snyk-to-html reports and the IDE integration with IaC.
```
npm run build
snyk-dev iac test test/fixtures/iac/terraform/sg_open_ssh.tf --json
snyk-dev iac test test/fixtures/iac/terraform/sg_open_ssh.tf --sarif
```
Notes:
options['sarif-file-output'] and options['json-file-output'] would still have this console.log. These are different and they are not considered options, they would just return undefined if we tried to check their value:
https://github.com/snyk/snyk/blob/210ec32b93c1b1f6932bddc22f41e9e0c82aa2fc/src/cli/commands/test/iac-local-execution/types.ts#L156-L158 …

fix: remove console.log for custom rules from json,sarif output.

---

src/cli/main.ts
src/lib/snyk-test/legacy.ts
src/lib/types.ts
test/fixtures/container-projects/app-vuln-apk-fixture.json
test/fixtures/container-projects/app-vuln-npm-fixture.json
test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts

Currently if using `--file` and `--exclude-base-image-vulns` flag would filter
out all the vulnerabilities including application vulnerabilites which is not
related to the base image. We want to only filter out the base image vulnerabilites.
src/lib/snyk-test/legacy.ts
* npm run build
* build an image with this project
* `snyk container test <image-has-been-built> --app-vulns --file=Dockerfile --exclude-base-image-vulns; echo $?`
* exit code should be 1 instead of 0
[zendesk ticket](https://snyk.zendesk.com/agent/tickets/16119)

fix: exclude application vulns from filtering

---

package-lock.json
package.json

On the server side, when we construct the package id we
make the output lower cased. We need to align also the
client to mirror that logic in order to successfully
find and extract the required data.
- bump the version of the cpp plugin to include the changes
also in the CLI

fix: fix the cpp package id creation

---

package-lock.json
package.json

Bump `snyk-nuget-plugin` which contains [fix](https://github.com/snyk/snyk-nuget-plugin/pull/111) to parse `.nuspec` files that are encoded in UTF-8 with BOM

fix: parse nuspecs with utf BOM encoding

---

src/cli/main.ts
src/cli/modes.ts
test/args.test.ts
test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts
test/jest/unit/lib/util.spec.ts
test/jest/unit/modes.spec.ts

This PR allows container test with --app-vulns to run with --json output, using the --experimental flag.
The reviewer should start at src/cli/main.ts where we chaeck for the  globalArgs.options['app-vulns'] &&      globalArgs.options['json'] condition.
Run: 
`snyk container test snyk:node-snykin --app-vulns --json` with and without the --experimental flag.

feat: Allow json output for app vulns (experimental)

---

src/lib/formatters/test/format-test-results.ts
test/fixtures/container-app-vulns/jsonData.json
test/fixtures/container-app-vulns/jsonDataGrouped.json
test/fixtures/container-app-vulns/jsonDataNonGrouped.json
test/fixtures/container-app-vulns/results.json
test/jest/unit/lib/formatters/test/format-test-results.spec.ts

Support grouping issues in json output when there are multiple results.
This PR adds support for grouping vulnerabilities for json tests results that are returned as an array. 
This is needed for `snyk container test` when using the `--app-vulns --json --experimental` flags together with `--group-issues` flag. In this case, the returned result may be a JSON array rather than a single JSON object. The code until now did not support grouping for array results, and this PR fixes this behavior.
Start at the `extractDataToSendFromResults` function found in the file `src/lib/formatters/test/format-test-results.ts`.
Run:
```
node dist/cli container test crate:2.0.2 --json --app-vulns --experimental --group-issues
```

fix: support grouping issues for json array results

---

package-lock.json
package.json

Bump snyk-nuget-plugin that added support for utf16le encoding in nuspecs in https://github.com/snyk/snyk-nuget-plugin/pull/112

fix: bump nuget plugin with utf16 nuspec support

---

test/smoke/spec/iac/snyk_test_local_exec_spec.sh

Some IaC tests are broken after an update- remove them for now in order to un-block the release pipeline

fix: remove broken IaC tests to un-block release

---

test/smoke/spec/iac/snyk_test_local_exec_spec.sh

We recently released another version in policies and the description of this policy rule has changed. this updates the smoke tests to reflect that.
Note: we have plans to remove these tests from the regression step, they are brittle.

chore: Update iac smoke test description

---

package-lock.json
package.json

Bumps snyk-docker-plugin to 4.30.0
This version of the plugin looks for dependencies of a JAR by parsing the pom.properties after unpacking it and adding to the jarFingerprints fact when using the --app-vulns and --nested-jars-depth=n flags tested?

feat: return JAR dependencies from pom.properties files

---

.github/workflows/smoke-tests.yml
docker-desktop/README.md
docker-desktop/build.sh
docker-desktop/src/entrypoint.sh
release-scripts/make-binaries.sh
release-scripts/upload-artifacts.sh
release-scripts/validate-checksums.sh

We need darwin/arm64 support for our Docker Desktop integration.
I've renamed and restructured the Docker Desktop bundle to support multiple architectures. We'll keep the old bundle format for backwards compatibility while we wait for migrations to finish. This PR is technically additive, it's not changing anything.
- Download and extract `docker-mac-signed-bundle.tar.gz` 
- Run `./docker/snyk-mac.sh`
```
docker
├── config.default.json
├── dist
├── help
├── node-v12.18.3-darwin-x64
├── package.json
├── pysrc
└── snyk-mac.sh
```
```
31M     ./docker-mac-signed-bundle.tar.gz
133M    ./docker
```
- Download and extract `snyk-for-docker-desktop-darwin-x64.tar.gz` 
- Change `x64` to `arm64` accordingly. 
- Run `./snyk-for-docker-desktop-darwin-x64/entrypoint.sh`
``` …
```

feat: create docker desktop bundle for darwin/arm64

---

.github/workflows/smoke-tests.yml

The docker bundle doesn't support symlinks, never did. So I've reverted
the smoke test setup to use PATH as before.
Symlinks aren't supported because it uses "${0}" assuming it'll point
to the bundle directory, but for symlinks, it'll be the symlink
directory. This can be solved using `realpath` but macOS does not
include that command by default.
Follow up to #2444

test: revert to using PATH instead of symlinks

---

src/lib/formatters/iac-output.ts

This PR makes sure that when custom rules are used for SARIF output we don't include `undefined` for undefined fields.
1. Download [bundle.tar.gz](https://github.com/snyk/snyk/files/7788826/bundle.tar.gz)
2. Clone https://github.com/snyk/custom-rules-example.
3. Run `npm run build` in `snyk/snyk`
4. Run ` snyk-dev iac test ./rules/CUSTOM-RULE-1/fixtures/denied.tf --rules=bundle.tar.gz` in `snyk/custom-rules-example` to see custom rule `CUSTOM-RULE-3` being flagged up, as an example
5. Run `snyk-dev iac test ./rules/CUSTOM-RULE-1/fixtures/denied.tf --rules=bundle.tar.gz --sarif`  in `snyk/custom-rules-example`  to see that there are no more mentions of `undefined` for `CUSTOM-RULE-3`
This is a byproduct of Snyk IaC investigating our existing SARIF output in …

fix: custom rules output for sarif

---

src/lib/plugins/get-multi-plugin-result.ts
src/lib/plugins/nodejs-plugin/yarn-workspaces-parser.ts
src/lib/snyk-test/run-test.ts
test/acceptance/cli-monitor/cli-monitor.all-projects.spec.ts
test/acceptance/cli-test/cli-test.all-projects.spec.ts
test/acceptance/workspaces/yarn-workspaces/ap-dev.json
test/acceptance/workspaces/yarn-workspaces/not-part-of-workspace/package-lock.json
test/acceptance/workspaces/yarn-workspaces/not-part-of-workspace/package.json
test/acceptance/workspaces/yarn-workspaces/yw-dev.json
test/jest/acceptance/snyk-test/all-projects.spec.ts

Support detecting & scanning Yarn workspace projects `--all-projects`.
Process all projects as yarn workspaces first since many files are related to each other and could belong to a workspace, then process the rest as usual.
https://github.com/snyk/snyk/pull/2341/files#diff-2194ffc6b9f5b3533db3a8c636c6fcde3d7f163e92de6d915a5dc542a576fb82R48
Run `snyk test --all-projects` in a yarn workspaces projects
https://github.com/snyk/snyk/issues/1561
`snyk test --all-projects` detects all the Yarn workspace projects + the non-workspace project.
`snyk test --all-projects --json` has the same output all the Yarn workspace projects via `--yarn-workspaces` with the addition of the non-workspace project.
Out of sync error during `--yarn-workspaces` scan is resulting in the same error code and behaviour …

feat: support yarn workspaces projects in --all-projects

---

src/lib/formatters/iac-output.ts
src/lib/formatters/sarif-output.ts
test/jest/unit/lib/formatters/__snapshots__/sarif-output.spec.ts.snap
test/jest/unit/lib/formatters/iac-output.spec.ts
test/jest/unit/lib/formatters/sarif-output.spec.ts

This PR makes sure that `critical` security issues are treated as errors in SARIF for code scanning alerts. At the moment they would be treated as warnings, which is not correct as `critical` is the highest severity.
Snyk IaC only supports critical severity via custom rules. 
1. Download [bundle.tar.gz](https://github.com/snyk/snyk/files/7756000/bundle.tar.gz)
2. Clone https://github.com/snyk/custom-rules-example.
3. Run `npm run build` in `snyk/snyk`
4. Run ` snyk-dev iac test ./rules/CUSTOM-RULE-1/fixtures/denied.tf --rules=bundle.tar.gz` in `snyk/custom-rules-example` to see Critical issue `CUSTOM-RULE-1`
5. Run `snyk-dev iac test ./rules/CUSTOM-RULE-1/fixtures/denied.tf --rules=bundle.tar.gz --sarif`  in `snyk/custom-rules-example`  to see that it's an `error`
This is a byproduct of …

fix: critical level is considered error in sarif

---

.circleci/config.yml
.circleci/vendor/sdkman-install.sh

Follow-up #2308 
Fixed in https://github.com/sdkman/sdkman-cli/pull/1012
SDKMAN's install process does not let us choose a version. This can cause our pipelines to break at any point if SDKMAN makes a breaking change.
To reduce our dependence on SDKMAN's servers, I've vendored the install script so that it's more predictable. I've also cached the install so we don't need to keep pulling in the installation archive from their servers on every PR run.

chore(ci): re-enable sdkman caching

---

.circleci/config.yml
package.json

These jobs utilise less than 50% of a large's resource. It's a waste. Go back to default (medium). For numbers see the "Resources" tab for any job in CircleCI.
I had to add `runInBand` for some of our Jest "package" tests to avoid timeouts.
https://app.circleci.com/pipelines/github/snyk/snyk/8808/workflows/00296f85-f15c-4135-b74b-46a2ce284b0a/jobs/67106
So this could be why we setup "large" resources. "medium" can't handle parallel tests. However, I think adding "runInBand" is fine for now. We do it for other tests too so it's consistent. For parallelism, CircleCI has its own feature which would be a better fit here (see #2232)
- Pretty much the same numbers.

chore(ci): reduce resource class

---

.circleci/config.yml

Old images won't be maintained after December 2021. So this PR migrates us to the new ones.
https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
CircleCI's "node" orb handles caching for us so I tried using `cimg/base` since our Node version varies. However, it has too many issues and limitations.
- It doesn't support ramdisk (it attempts some symlink wizardry and fails, see below).
- It doesn't support Windows.
- We still need to configure `NPM_TOKEN` using `npm config`.
```
ln: failed to create hard link '/tmp/node-project-lockfile' => 'package-lock.json': Invalid cross-device link
```
So in general, it's simpler to keep using a Node image and maintain our existing manual caches and configuration.

chore(ci): migrate to cimg images

---

src/lib/formatters/iac-output.ts
test/jest/acceptance/iac/file-output.spec.ts

The snyk CLI generate SARIF output, which is then used for [code scanning by GitHub]( https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning).
We would like to improve our SARIF output which will enhance the UX when using GH code scanning.
1. Test an IaC file/directory and save the output using `snyk-dev iac test {path to the file/directory} --sarif > sarif.snyk`
2. Create a test repo and upload the `sarif.snyk` file to it
3. Configure the Snyk IaC scanning tool in your repo
4. Commit any changes and check the scanning results in the Securit tab.
The [following Notion page](https://www.notion.so/snyk/SARIF-output-for-GitHub-Security-Alerts-65a89cfa82a74ee79e5d41dfbe452cef) provides additional context.
- …

feat: IaC SARIF output improvements [CFG-1313] [CFG-1314]

---

src/lib/formatters/iac-output.ts

Currently when running the snyk cli by using a docker image we cannot get the repo root cause the container doesn't have git installed which caused the scan to fail.
1. Scan an IaC file / directory inside of a repo
2. Scan an IaC file / directory outside of a repo
Both of the scans should run without any problem.

fix: IaC SARIF output

---

.github/workflows/smoke-tests.yml

symlink needs to be in the same directory as snyk-mac.
Follow up to #2536

chore: fix docker bundle smoke tests

---

package-lock.json
package.json
src/cli/commands/test/iac-local-execution/yaml-parser.ts
src/lib/iac/constants.ts

This PR fixes the bug in https://snyksec.atlassian.net/browse/CFG-1322 by making sure if the parsed file is JSON we don't fail upon finding `\\/`. 
In https://github.com/snyk/cloud-config-parser/pull/39:
2. `npm link`
In this branch:
2. Create a file `test.json` containing:
```
{
"DescribePackagesFilterValue":{
"type":"string",
"pattern":"^[0-9a-zA-Z\\*\\.\\\\/\\?-]*$"
}
}
```
3. Run `snyk iac test test.json` - see an error
4. Run `snyk-dev iac test test.json` - see no errors
A while ago we combined the parsing for JSON and YAML to both use the YAML parser, since they are more or less the same. We know from https://snyksec.atlassian.net/browse/CFG-364, however, that `\\/` is not valid YAML - and we added this check that throws an error when a …

fix: allow escape characters in json parsing [CFG-1322]

---

.circleci/config.yml
package.json

By moving the linter to its own job, we don't need to block test runs on minor linter errors. This lets contributors first get their work done without needing to polish and fix linter errors constantly throughout.
Running the linter in parallel also saves 30s to 3 minutes (linter time varies).
I've kept the linter requirement for dev-release as it should mirror prod-release as much as possible. And of course the linter (and every other job) should pass before we run a prod-release.
Example: https://app.circleci.com/pipelines/github/snyk/snyk/8914/workflows/ed13ac3a-92ec-4aa6-91e7-c2e593354770

chore(ci): run lint and build in parallel

---

help/cli-commands/container.md
test/smoke/spec/snyk_basic_spec.sh

This file has all revisions through January 3, 2022, for review by the Hammer team. Question: For commands with the sub-command test, should the test command be explained the same as as the snyk test command: test a project for open source vulnerabilities and license issues? At this time, the code and iac commands say: test for any known issue. The container command says: test for any known vulnerabilities.

docs: update container command help

---

src/lib/snyk-test/legacy.ts
src/lib/snyk-test/run-test.ts
test/fixtures/container-projects/Dockerfile-vulns
test/jest/acceptance/snyk-test/app-vuln-container-project.spec.ts

A previous [change](https://github.com/snyk/snyk/pull/2138) moved the filtering out of base image vulns (based on
the existence of `dockerfileInstruction`) to be before
`dockerfileInstruction` is assigned to the vulns, so all vulns were
filtered out in case we used the `exclude-base-image-vulns` option.
This fix moves the filtering back to where it was before, and
recalculates the value of `ok`, to account for the reason it was moved
in the first place.
https://snyk.zendesk.com/agent/tickets/16714

fix: exclude base image vulns filtering all vulns

---

help/cli-commands/code.md

This file has all revisions through January 3, 2022, for review by the Hammer team. Question: For commands with the sub-command test, should the test command be explained the same as as the snyk test command: test a project for open source vulnerabilities and license issues? At this time, the code and iac commands say: test for any known issue. The container command says: test for any known vulnerabilities.

docs: update code command help

---

package-lock.json
package.json
src/lib/ecosystems/common.ts
src/lib/ecosystems/monitor.ts
src/lib/ecosystems/test.ts
src/lib/feature-flags/index.ts
src/lib/types.ts
test/jest/unit/lib/ecosystems/common.spec.ts
test/jest/unit/lib/feature-flags/feature-flags.spec.ts

Co-authored-by: @danlucian lucian.rosu@snyk.io
Allows users with snykUnmanagedVulnDB ff in org level to visualize
https://security.snyk.io/vuln/SNYK-UNMANAGED-CURL-2317584 rather than
nvd url
Depends on https://github.com/snyk/snyk-cpp-plugin/pull/61
with feature flag
without feature flag

feat: support unmanaged snyk security url

---

src/lib/formatters/legacy-format-issue.ts
src/lib/formatters/show-fix-tip.ts
test/jest/unit/lib/formatters/show-fix-tip.spec.ts
test/jest/unit/lib/formatters/test/__snapshots__/display-result.spec.ts.snap

Wizard is relatively outdated and advertising it is not necessarily helpful across the board given how Snyk is used. For example, some setups may not want their users to use `wizard`.
Rather than mess with controls or disabling the hint, lets do the simple thing and just remove it

feat: Remove snyk wizard hint

---

src/cli/commands/version.ts
src/lib/analytics/getStandardData.ts
src/lib/request/request.ts
src/lib/version.ts

Currently the `getVersion` function is an async function that is being used like a sync one ( by using `await` everywhere).
This PR removes the need for `await` by changing the function to be a sync function.

feat: Change getVersion() from async to sync

---

src/lib/formatters/iac-output.ts

This PR adds the current version of the CLI to the SARIF output under the driver field.
This is a direct continuation of the following PR: https://github.com/snyk/snyk/pull/2524
1. Run a test with the `--sarif` flag
2. under `runs[].tool.driver.version` you'll found the newly added driver version
https://snyksec.atlassian.net/jira/software/c/projects/CFG/boards/301?modal=detail&selectedIssue=CFG-1313
What's the meaning of life? :)

feat: add driver version to IaC sarif outout

---

.circleci/config.yml

Needing to run `npm ci` on every job (tests, release) is slow and wasteful. Even with an npm cache, it can take around 30 seconds on each job.
So, I've persisted `node_modules` in our CircleCI workspace after the first `npm ci` (in the build job). Every other job attaches the workspace and re-uses the same `node_modules`.
Since our workspace is for Linux environments, Windows still needs to run `npm ci` for a compatible `node_modules` setup. So overall, this may not save total run time, but will provide faster feedback on Linux environments.
There are other ideas to avoid needing to run `npm ci` on Windows, which is being spiked on as part of #2509.
To review, you can see the new pipeline here: https://app.circleci.com/pipelines/github/snyk/snyk/9151/workflows/f3f1a58b-f19c-4c67-979b-4c8c0 …

chore(ci): reduce npm installs

---

package-lock.json
package.json

This patch bumps the `nodejs-lockfile-parser` to `1.38.0`, improving the error message shown when a dependency is missing from the lockfile
https://github.com/snyk/nodejs-lockfile-parser/releases/tag/v1.38.0

feat: Improve npm7+ error message

---

test/jest/acceptance/snyk-protect/deduped-package-patch.spec.ts

Node 10 support is being deprecated so API alerts have been added server-side to show a warning message in CLI.
https://app.circleci.com/pipelines/github/snyk/snyk/9244/workflows/c1dafc02-fe38-4b11-b7ba-bf88b0042784/jobs/71252
This isn't relevant to these tests so I've updated the assertions.
We should mock the response but this is blocking pipelines and it would require re-writing the entire test. There are other tests with the same issue so it'd be easier to migrate them together.

test: fix test failing on node@10 warning messages

---

.github/workflows/smoke-tests.yml
test/smoke/run-shellspec-win.sh
test/smoke/spec/snyk_code_spec.sh
test/smoke/spec/snyk_monitor_spec.sh
test/smoke/spec/snyk_test_spec.sh
test/smoke/spec/spec_helper.sh

Fix failing smoke tests caused by the new deprecation message of node 10.

smoke: add node 10 check to smoke tests

---

src/cli/commands/test/iac-local-execution/index.ts
src/cli/commands/test/iac-local-execution/types.ts
test/acceptance/fake-server.ts
test/jest/acceptance/iac/custom-rules.spec.ts
test/jest/acceptance/iac/iac-entitlement.spec.ts
test/jest/unit/iac-unit-tests/index.spec.ts

The `snyk iac test` command is now looking at the `infrastructureAsCode` entitlement before scanning.
1. Verify that `infrastructureAsCode` is true (by default).
2. Run `snyk iac test` command without any errors.
3. Change your `infrastructureAsCode` entitlement to false.
4. Re-run the above command, you should have now an error.
Will copy-paste what I wrote in registry:
We don’t check in the Snyk CLI if a customer has the infrastructureAsCode entitlement. Thus, for customers not entitled to use IAC, they can't import via the web UI but they still can test IAC files via the CLI.
- [Jira ticket CFG-1090](https://snyksec.atlassian.net/browse/CFG-1090)
- [Registry PR](https://github.com/snyk/registry/pull/25610)

fix: block user from scanning IAC files if not entitled [CFG-1090]

---

src/cli/commands/test/iac-local-execution/analytics.ts
src/cli/commands/test/iac-local-execution/index.ts

This PR improves the Snyk IaC CLI analytics by sending 3 new values:
- `iac-files-count`: will eventually replace `iac-test-count` (hence the TODO), since it actually tells us how many files were scanned
- `iac-local-custom-rules': will eventually be used in Looker by BI, since we learned this is preferred to reading the JSON in the `args` analytics which contains the `--rules `flag
- `iac-remote-custom-rules`: will be eventually be used in Looker by BI, instead of `iac-custom-rules-checksum`
At the moment these won't be used in Looker since our customers would need to update their CLI versions
1. Run `npm run build`
2. Run `snyk-dev iac test ./test/fixtures/iac/kubernetes/pod-privileged.yaml -d` - without custom rules
3. Run `snyk-dev iac test …

chore: improve iac analytics [CFG-1386]

---

.circleci/chocolatey.config
.circleci/config.yml

So that it can benefit from caching.
The previous config was parameterised using `parameters.node_version` but this is actually more like a global constant since we don't pass in any parameters and it falls back to defaults.
Progresses #2599

chore(ci): move windows nodejs to choco config

---

package-lock.json
package.json

Changed the parsing logic to ignore the symlinks while doing unmanaged scanning.
Bumped the cpp-plugin plugin to bring the changes into the CLI.

fix: ignore symlinks for unmanaged scanning

---

src/lib/analytics/index.ts
test/jest/unit/lib/analytics/index.spec.ts

Today a user can test multiple files/directories by using the command `snyk {product} test {path1} {path2}`.
When doing so we are saving some of the analytics incorrectly, some examples:
`"iac-test-count": [1,2],` (should be a numeric value and not an array)
`"packageManager": ["cloudformationconfig",["terraformconfig","cloudformationconfig"]],` (shouldn't be a nested array)
Those are some IaC examples but the problem is shared across all products.
Objects should probably be handled in [registry](https://github.com/snyk/registry/blob/cdc684900ca34379eedb823e5fe0c0deff4b39d1/src/lib/analytics/cli.ts#L200) by each team separately.
Run a test with multiple args and use the `-d` flag to check the metadata field at the bottom.
https://snyksec.atlassian.net/browse/CFG-1446
Before:
After:

feat: modify analytics [CFG-1446]

---

help/cli-commands/code.md
src/lib/plugins/sast/index.ts
src/lib/types.ts
test/jest/unit/snyk-code/snyk-code-test.spec.ts

Adding a new flag to options, `--no-markdown`, which removes the `markdown` property from `result.message` when using `sarif` output.
`snyk code test --sarif --no-markdown`
Slack discussion: https://snyk.slack.com/archives/C01U14WSN73/p1642928960104800
This is a result of a support ticket: https://snyk.zendesk.com/agent/tickets/18450

feat: added a new option: --no-markdown for sarif output

---

.github/CODEOWNERS
config.default.json
help/cli-commands/apps.md
src/cli/commands/apps/create-app.ts
src/cli/commands/apps/index.ts
src/cli/commands/index.js
src/lib/apps/constants.ts
src/lib/apps/create-app/index.ts
src/lib/apps/index.ts
src/lib/apps/input-validator.ts
src/lib/apps/prompts.ts
src/lib/apps/types.ts
src/lib/apps/utils.ts
src/lib/apps/v3-utils.ts
src/lib/config.ts
src/lib/request/promise.ts
src/lib/types.ts
test/acceptance/fake-server.ts
test/jest/acceptance/snyk-apps/create-app.spec.ts
test/jest/unit/lib/apps/input-validator.spec.ts
test/jest/util/runCommand.ts
test/jest/util/runSnykCLI.ts

Adds `$snyk apps` command to the Snyk CLI. This command is available only under the `--experimental` flag. Example: `$snyk apps create --experimental`
The current PR only focuses on the `create` sub-command. There are two modes of the command 
1. `interactive` mode available with the `--interactive` or the `-i` flag. Example: `$ snyk apps create -i --experimental`
2. `scriptable` mode which is the default but has required options. Example: `$ snyk apps create --experimental --org=<your-org-id> --name=<your-snyk-app-name> --redirect-uris=https://example1.com,HTTP://example2.com` --scopes=apps:beta` 
Changes that this PR makes:
- `create` command to create a Snyk App
- `config` value `V3endpoint` to configure the Snyk V3 API endpoint base URL
- Initial acceptance to test the `create` …

feat: add snyk apps command and create sub-command
